from ....NXOpen import *
from ...CAE import *

import typing
import enum

class TBSTopologySensitivityOptimizationParameters(CAE.Optimization.TBSOptimizationParameters):
    def __init__(self) -> None: ...
    @property
    def DensityMove(self) -> float: ...
    @DensityMove.setter
    def DensityMove(self, value: float) -> None: ...
    @property
    def DensityUpdateOption(self) -> CAE.Optimization.TBSTopologySensitivityOptimizationParameters.DensityUpdate: ...
    @DensityUpdateOption.setter
    def DensityUpdateOption(self, value: CAE.Optimization.TBSTopologySensitivityOptimizationParameters.DensityUpdate) -> None: ...
    @property
    def EigenvalueParameters(self) -> CAE.Optimization.TBSEigenvalueOptimizationParameters: ...
    @EigenvalueParameters.setter
    def EigenvalueParameters(self, value: CAE.Optimization.TBSEigenvalueOptimizationParameters) -> None: ...
    @property
    def FilterRadius(self) -> Expression: ...
    @FilterRadius.setter
    def FilterRadius(self, value: Expression) -> None: ...
    @property
    def MaterialInterpolationOption(self) -> CAE.Optimization.TBSTopologySensitivityOptimizationParameters.MaterialInterpolation: ...
    @MaterialInterpolationOption.setter
    def MaterialInterpolationOption(self, value: CAE.Optimization.TBSTopologySensitivityOptimizationParameters.MaterialInterpolation) -> None: ...


    class MaterialInterpolation(enum.Enum):
        Simp= 0
        Ramp= 1
    

    class DensityUpdate(enum.Enum):
        Normal= 0
        Conservative= 1
        Agressive= 2
    

class TBSTopologyRestrictAreaBuilder(CAE.Optimization.TBSRestrictAreaBuilder):
    def __init__(self) -> None: ...
    @property
    def CastCondition(self) -> CAE.Optimization.TBSCastCondition: ...
    @CastCondition.setter
    def CastCondition(self, value: CAE.Optimization.TBSCastCondition) -> None: ...
    @property
    def CheckingElementGroup(self) -> CAE.Optimization.TBSGroupDefinition: ...
    @CheckingElementGroup.setter
    def CheckingElementGroup(self, value: CAE.Optimization.TBSGroupDefinition) -> None: ...
    @property
    def CheckingType(self) -> CAE.Optimization.TBSTopologyRestrictAreaBuilder.CheckTypeOption: ...
    @CheckingType.setter
    def CheckingType(self, value: CAE.Optimization.TBSTopologyRestrictAreaBuilder.CheckTypeOption) -> None: ...
    @property
    def Distance(self) -> Expression: ...
    @Distance.setter
    def Distance(self, value: Expression) -> None: ...
    @property
    def LinkCondition(self) -> CAE.Optimization.TBSTopologyLinkCondition: ...
    @LinkCondition.setter
    def LinkCondition(self, value: CAE.Optimization.TBSTopologyLinkCondition) -> None: ...
    @property
    def MinimumThickness(self) -> Expression: ...
    @MinimumThickness.setter
    def MinimumThickness(self, value: Expression) -> None: ...
    @property
    def Radius(self) -> Expression: ...
    @Radius.setter
    def Radius(self, value: Expression) -> None: ...
    @property
    def Thickness(self) -> Expression: ...
    @Thickness.setter
    def Thickness(self, value: Expression) -> None: ...


    class CheckTypeOption(enum.Enum):
        Frozen= 0
        LinkTopo= 1
        MaximumsSize= 2
        MinimumSize= 3
        Cast= 4
    

class TBSTopologyRestrictArea(CAE.Optimization.TBSRestrictArea):
    def __init__(self) -> None: ...


class TBSTopologyOptimizationSolutionBuilder(CAE.Optimization.TBSOptimizationSolutionBuilder):
    def __init__(self) -> None: ...


class TBSTopologyOptimizationSolution(CAE.Optimization.TBSOptimizationSolution):
    def __init__(self) -> None: ...


class TBSTopologyLinkCondition(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def Axis(self) -> CAE.Optimization.TBSTopologyLinkCondition.AxisType: ...
    @Axis.setter
    def Axis(self, value: CAE.Optimization.TBSTopologyLinkCondition.AxisType) -> None: ...
    @property
    def IgnoreFrozen(self) -> bool: ...
    @IgnoreFrozen.setter
    def IgnoreFrozen(self, value: bool) -> None: ...
    @property
    def ReferenceCoordinateSystem(self) -> CoordinateSystem: ...
    @ReferenceCoordinateSystem.setter
    def ReferenceCoordinateSystem(self, value: CoordinateSystem) -> None: ...
    @property
    def SymmetryType(self) -> CAE.Optimization.TBSTopologyLinkCondition.SymmetryOption: ...
    @SymmetryType.setter
    def SymmetryType(self, value: CAE.Optimization.TBSTopologyLinkCondition.SymmetryOption) -> None: ...
    @property
    def TranslationAmount(self) -> int: ...
    @TranslationAmount.setter
    def TranslationAmount(self, value: int) -> None: ...


    class SymmetryOption(enum.Enum):
        PlaneSymmetry= 0
        CyclicSymmetry= 1
    

    class AxisType(enum.Enum):
        X= 0
        Y= 1
        Z= 2
    

class TBSTopologyControllerOptimizationParameters(CAE.Optimization.TBSOptimizationParameters):
    def __init__(self) -> None: ...
    @property
    def AutomaticFrozenOption(self) -> CAE.Optimization.TBSTopologyControllerOptimizationParameters.AutoFrozen: ...
    @AutomaticFrozenOption.setter
    def AutomaticFrozenOption(self, value: CAE.Optimization.TBSTopologyControllerOptimizationParameters.AutoFrozen) -> None: ...
    @property
    def IterationNumbers(self) -> int: ...
    @IterationNumbers.setter
    def IterationNumbers(self, value: int) -> None: ...
    @property
    def SpeedOption(self) -> CAE.Optimization.TBSTopologyControllerOptimizationParameters.Speed: ...
    @SpeedOption.setter
    def SpeedOption(self, value: CAE.Optimization.TBSTopologyControllerOptimizationParameters.Speed) -> None: ...
    @property
    def StartDeleteVolume(self) -> float: ...
    @StartDeleteVolume.setter
    def StartDeleteVolume(self, value: float) -> None: ...
    @property
    def VolumeDefinitionOption(self) -> CAE.Optimization.TBSTopologyControllerOptimizationParameters.VolumeDefinitionMethod: ...
    @VolumeDefinitionOption.setter
    def VolumeDefinitionOption(self, value: CAE.Optimization.TBSTopologyControllerOptimizationParameters.VolumeDefinitionMethod) -> None: ...


    class VolumeDefinitionMethod(enum.Enum):
        Percent= 0
        Absolute= 1
    

    class Speed(enum.Enum):
        VerySlow= 0
        Slow= 1
        Moderate= 2
        Medium= 3
        Fast= 4
        Iteration= 5
    

    class AutoFrozen(enum.Enum):
        Load= 0
        Off= 1
        Spc= 2
        Both= 3
    

class TBSTestFunction(NXObject):
    def __init__(self) -> None: ...
    @property
    def MaximumDisplacement(self) -> Expression: ...
    @MaximumDisplacement.setter
    def MaximumDisplacement(self, value: Expression) -> None: ...
    @property
    def NumberOfIncrements(self) -> int: ...
    @NumberOfIncrements.setter
    def NumberOfIncrements(self, value: int) -> None: ...
    @property
    def RunTest(self) -> bool: ...
    @RunTest.setter
    def RunTest(self, value: bool) -> None: ...
    @property
    def TestDirectionOption(self) -> CAE.Optimization.TBSTestFunction.Direction: ...
    @TestDirectionOption.setter
    def TestDirectionOption(self, value: CAE.Optimization.TBSTestFunction.Direction) -> None: ...


    class Direction(enum.Enum):
        Grow= 0
        Shrink= 1
        Random= 2
    

class TBSStopCondition(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def MaximumIterationNumber(self) -> int: ...
    @MaximumIterationNumber.setter
    def MaximumIterationNumber(self, value: int) -> None: ...


class TBSSmoothCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.Optimization.TBSSmooth]: ...
    @typing.overload
    def __init__(self, owner: CAE.Optimization.TBSOptimizationSolution) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, smoothName: str) -> CAE.Optimization.TBSSmooth: ...
    def Tag(self) -> Tag: ...



class TBSSmoothBuilder(Builder):
    def __init__(self) -> None: ...
    def GetFormatOption(self) -> typing.List[CAE.Optimization.TBSSmoothBuilder.Format]: ...
    def SetFormatOption(self, formatOption: typing.List[CAE.Optimization.TBSSmoothBuilder.Format]) -> None: ...
    @property
    def Border(self) -> bool: ...
    @Border.setter
    def Border(self, value: bool) -> None: ...
    @property
    def ComponentLimitingSize(self) -> Expression: ...
    @ComponentLimitingSize.setter
    def ComponentLimitingSize(self, value: Expression) -> None: ...
    @property
    def IsoTypeOption(self) -> CAE.Optimization.TBSSmoothBuilder.IsoType: ...
    @IsoTypeOption.setter
    def IsoTypeOption(self, value: CAE.Optimization.TBSSmoothBuilder.IsoType) -> None: ...
    @property
    def IsoValue(self) -> float: ...
    @IsoValue.setter
    def IsoValue(self, value: float) -> None: ...
    @property
    def MinimumAngle(self) -> Expression: ...
    @MinimumAngle.setter
    def MinimumAngle(self, value: Expression) -> None: ...
    @property
    def MixedMesh(self) -> bool: ...
    @MixedMesh.setter
    def MixedMesh(self, value: bool) -> None: ...
    @property
    def NameDescription(self) -> CAE.Optimization.NameDescription: ...
    @NameDescription.setter
    def NameDescription(self, value: CAE.Optimization.NameDescription) -> None: ...
    @property
    def OriginalSurfaceSmooth(self) -> CAE.Optimization.TBSSmoothBuilder.OriginalSurfaceSmoothingOption: ...
    @OriginalSurfaceSmooth.setter
    def OriginalSurfaceSmooth(self, value: CAE.Optimization.TBSSmoothBuilder.OriginalSurfaceSmoothingOption) -> None: ...
    @property
    def ReductionAngle(self) -> Expression: ...
    @ReductionAngle.setter
    def ReductionAngle(self, value: Expression) -> None: ...
    @property
    def ReductionRate(self) -> float: ...
    @ReductionRate.setter
    def ReductionRate(self, value: float) -> None: ...
    @property
    def ResultFilteringOption(self) -> CAE.Optimization.TBSSmoothBuilder.ResultFiltering: ...
    @ResultFilteringOption.setter
    def ResultFilteringOption(self, value: CAE.Optimization.TBSSmoothBuilder.ResultFiltering) -> None: ...
    @property
    def SelfIntersectionChecking(self) -> CAE.Optimization.TBSSmoothBuilder.SelfIntersectionCheckingOption: ...
    @SelfIntersectionChecking.setter
    def SelfIntersectionChecking(self, value: CAE.Optimization.TBSSmoothBuilder.SelfIntersectionCheckingOption) -> None: ...
    @property
    def SliceFormat(self) -> CAE.Optimization.TBSSmoothBuilder.SliceFormatOption: ...
    @SliceFormat.setter
    def SliceFormat(self, value: CAE.Optimization.TBSSmoothBuilder.SliceFormatOption) -> None: ...
    @property
    def SliceNormalVector(self) -> Direction: ...
    @SliceNormalVector.setter
    def SliceNormalVector(self, value: Direction) -> None: ...
    @property
    def SliceNumber(self) -> int: ...
    @SliceNumber.setter
    def SliceNumber(self, value: int) -> None: ...
    @property
    def SmoothArea(self) -> CAE.Optimization.TBSGroupDefinition: ...
    @SmoothArea.setter
    def SmoothArea(self, value: CAE.Optimization.TBSGroupDefinition) -> None: ...
    @property
    def SmoothCycles(self) -> int: ...
    @SmoothCycles.setter
    def SmoothCycles(self, value: int) -> None: ...
    @property
    def TargetVolume(self) -> float: ...
    @TargetVolume.setter
    def TargetVolume(self, value: float) -> None: ...
    @property
    def UseAdditionalParameters(self) -> bool: ...
    @UseAdditionalParameters.setter
    def UseAdditionalParameters(self, value: bool) -> None: ...


    class SliceFormatOption(enum.Enum):
        IgsPolygon= 0
        IgsCurves= 1
        Cli= 2
        All= 3
    

    class SelfIntersectionCheckingOption(enum.Enum):
        Off= 0
        Check= 1
        Runtime= 2
        Iterative= 3
    

    class ResultFiltering(enum.Enum):
        Off= 0
        Moderate= 1
        Full= 2
    

    class OriginalSurfaceSmoothingOption(enum.Enum):
        Off= 0
        Shrink= 1
        Full= 2
    

    class IsoType(enum.Enum):
        Original= 0
        New= 1
        Both= 2
    

    class Format(enum.Enum):
        Bdf= 0
        Stl= 1
        Iges= 2
    

class TBSSmooth(NXObject):
    def __init__(self) -> None: ...
    def Execute(self) -> None: ...
    def Rename(self, name: str, renameResults: bool) -> None: ...
    def GetResults(self) -> str: ...
    def Destroy(self, deleteResult: bool) -> None: ...


class TBSSingleObjective(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def DesignResponse(self) -> CAE.Optimization.TBSDesignResponse: ...
    @DesignResponse.setter
    def DesignResponse(self, value: CAE.Optimization.TBSDesignResponse) -> None: ...
    @property
    def ReferenceValue(self) -> float: ...
    @ReferenceValue.setter
    def ReferenceValue(self, value: float) -> None: ...
    @property
    def Weight(self) -> float: ...
    @Weight.setter
    def Weight(self, value: float) -> None: ...


class TBSShapeRestrictAreaBuilder(CAE.Optimization.TBSRestrictAreaBuilder):
    def __init__(self) -> None: ...
    @property
    def ActLinkConditionButton(self) -> CAE.Optimization.TBSShapeLinkCondition: ...
    @ActLinkConditionButton.setter
    def ActLinkConditionButton(self, value: CAE.Optimization.TBSShapeLinkCondition) -> None: ...
    @property
    def CheckBoundaryCondition(self) -> bool: ...
    @CheckBoundaryCondition.setter
    def CheckBoundaryCondition(self, value: bool) -> None: ...
    @property
    def CheckDof(self) -> bool: ...
    @CheckDof.setter
    def CheckDof(self, value: bool) -> None: ...
    @property
    def CheckElementGroup(self) -> bool: ...
    @CheckElementGroup.setter
    def CheckElementGroup(self, value: bool) -> None: ...
    @property
    def CheckLinkCondition(self) -> bool: ...
    @CheckLinkCondition.setter
    def CheckLinkCondition(self, value: bool) -> None: ...
    @property
    def CheckMaximumGrowValue(self) -> bool: ...
    @CheckMaximumGrowValue.setter
    def CheckMaximumGrowValue(self, value: bool) -> None: ...
    @property
    def CheckMaximumShrinkValue(self) -> bool: ...
    @CheckMaximumShrinkValue.setter
    def CheckMaximumShrinkValue(self, value: bool) -> None: ...
    @property
    def CheckedElements(self) -> CAE.Optimization.TBSGroupDefinition: ...
    @CheckedElements.setter
    def CheckedElements(self, value: CAE.Optimization.TBSGroupDefinition) -> None: ...
    @property
    def DofSettings(self) -> CAE.Optimization.TBSCheckDOF: ...
    @DofSettings.setter
    def DofSettings(self, value: CAE.Optimization.TBSCheckDOF) -> None: ...
    @property
    def MaximumGrowValue(self) -> Expression: ...
    @MaximumGrowValue.setter
    def MaximumGrowValue(self, value: Expression) -> None: ...
    @property
    def MaximumShrinkValue(self) -> Expression: ...
    @MaximumShrinkValue.setter
    def MaximumShrinkValue(self, value: Expression) -> None: ...
    @property
    def RestrictedNodes(self) -> CAE.Optimization.TBSGroupDefinition: ...
    @RestrictedNodes.setter
    def RestrictedNodes(self, value: CAE.Optimization.TBSGroupDefinition) -> None: ...


class TBSShapeRestrictArea(CAE.Optimization.TBSRestrictArea):
    def __init__(self) -> None: ...


class TBSShapeOptimizationSolutionBuilder(CAE.Optimization.TBSOptimizationSolutionBuilder):
    def __init__(self) -> None: ...


class TBSShapeOptimizationSolution(CAE.Optimization.TBSOptimizationSolution):
    def __init__(self) -> None: ...
    def SolveTest(self) -> None: ...
    def GetTestResultFile(self) -> str: ...
    @property
    def MeshSmooth(self) -> CAE.Optimization.TBSMeshSmooth: ...
    @MeshSmooth.setter
    def MeshSmooth(self, value: CAE.Optimization.TBSMeshSmooth) -> None: ...
    @property
    def TestFunction(self) -> CAE.Optimization.TBSTestFunction: ...
    @TestFunction.setter
    def TestFunction(self, value: CAE.Optimization.TBSTestFunction) -> None: ...


class TBSShapeOptimizationParameters(CAE.Optimization.TBSOptimizationParameters):
    def __init__(self) -> None: ...
    @property
    def DisplacementStepSize(self) -> CAE.Optimization.TBSShapeOptimizationParameters.DisplacementStepsize: ...
    @DisplacementStepSize.setter
    def DisplacementStepSize(self, value: CAE.Optimization.TBSShapeOptimizationParameters.DisplacementStepsize) -> None: ...
    @property
    def DisplacementStepSizeOption(self) -> CAE.Optimization.TBSShapeOptimizationParameters.DisplacementStepsize: ...
    @DisplacementStepSizeOption.setter
    def DisplacementStepSizeOption(self, value: CAE.Optimization.TBSShapeOptimizationParameters.DisplacementStepsize) -> None: ...
    @property
    def Scale(self) -> float: ...
    @Scale.setter
    def Scale(self, value: float) -> None: ...


    class DisplacementStepsize(enum.Enum):
        Minimum= 0
        Average= 1
    

class TBSShapeLinkCondition(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def Angle(self) -> Expression: ...
    @Angle.setter
    def Angle(self, value: Expression) -> None: ...
    @property
    def DemoldGroup(self) -> CAE.Optimization.TBSGroupDefinition: ...
    @DemoldGroup.setter
    def DemoldGroup(self, value: CAE.Optimization.TBSGroupDefinition) -> None: ...
    @property
    def Direction(self) -> Direction: ...
    @Direction.setter
    def Direction(self, value: Direction) -> None: ...
    @property
    def ManufacturingType(self) -> CAE.Optimization.TBSShapeLinkCondition.ManufacturingOption: ...
    @ManufacturingType.setter
    def ManufacturingType(self, value: CAE.Optimization.TBSShapeLinkCondition.ManufacturingOption) -> None: ...
    @property
    def SymmetryPlane(self) -> Plane: ...
    @SymmetryPlane.setter
    def SymmetryPlane(self, value: Plane) -> None: ...
    @property
    def Tolerance(self) -> Expression: ...
    @Tolerance.setter
    def Tolerance(self, value: Expression) -> None: ...
    @property
    def UndercutTolerance(self) -> Expression: ...
    @UndercutTolerance.setter
    def UndercutTolerance(self, value: Expression) -> None: ...
    @property
    def UseCylindricalCsys(self) -> bool: ...
    @UseCylindricalCsys.setter
    def UseCylindricalCsys(self, value: bool) -> None: ...
    @property
    def UseSplineToDefineSurface(self) -> bool: ...
    @UseSplineToDefineSurface.setter
    def UseSplineToDefineSurface(self, value: bool) -> None: ...


    class ManufacturingOption(enum.Enum):
        PlaneSymmetry= 0
        RotationSymmetry= 1
        SurfaceStamp= 2
        SurfaceTurn= 3
        SurfaceDrill= 4
        SurfaceDemold= 5
    

class TBSRestrictAreaCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.Optimization.TBSRestrictArea]: ...
    @typing.overload
    def __init__(self, owner: CAE.Optimization.TBSOptimizationSolution) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, name: str) -> CAE.Optimization.TBSRestrictArea: ...
    def Tag(self) -> Tag: ...



class TBSRestrictAreaBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def NameDescription(self) -> CAE.Optimization.NameDescription: ...
    @NameDescription.setter
    def NameDescription(self, value: CAE.Optimization.NameDescription) -> None: ...


class TBSRestrictArea(NXObject):
    def __init__(self) -> None: ...


class TBSOutputControlOptions(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def CustomScratchDirectory(self) -> str: ...
    @CustomScratchDirectory.setter
    def CustomScratchDirectory(self, value: str) -> None: ...
    @property
    def HasCustomScratchDirectory(self) -> bool: ...
    @HasCustomScratchDirectory.setter
    def HasCustomScratchDirectory(self, value: bool) -> None: ...
    @property
    def IsJobRunInForeground(self) -> bool: ...
    @IsJobRunInForeground.setter
    def IsJobRunInForeground(self, value: bool) -> None: ...
    @property
    def Op2OutputOption(self) -> CAE.Optimization.TBSOutputControlOptions.Op2Option: ...
    @Op2OutputOption.setter
    def Op2OutputOption(self, value: CAE.Optimization.TBSOutputControlOptions.Op2Option) -> None: ...


    class Op2Option(enum.Enum):
        None_= 0
        FirstLast= 1
        All= 2
    

class TBSOptimizationSolutionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.Optimization.TBSOptimizationSolution]: ...
    @typing.overload
    def __init__(self, owner: CAE.Optimization.TBSOptimizationManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, solutionName: str) -> CAE.Optimization.TBSOptimizationSolution: ...
    def CloneSolution(self, sourceSolution: CAE.Optimization.TBSOptimizationSolution, cloneResult: bool) -> CAE.Optimization.TBSOptimizationSolution: ...
    def Tag(self) -> Tag: ...



class TBSOptimizationSolutionBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def NameDescription(self) -> CAE.Optimization.NameDescription: ...
    @NameDescription.setter
    def NameDescription(self, value: CAE.Optimization.NameDescription) -> None: ...
    @property
    def ReferencedSolution(self) -> CAE.SimSolution: ...
    @ReferencedSolution.setter
    def ReferencedSolution(self, value: CAE.SimSolution) -> None: ...
    @property
    def Strategy(self) -> CAE.Optimization.TBSOptimizationSolutionBuilder.StrategyType: ...
    @Strategy.setter
    def Strategy(self, value: CAE.Optimization.TBSOptimizationSolutionBuilder.StrategyType) -> None: ...


    class StrategyType(enum.Enum):
        Sensitivity= 0
        Controller= 1
    

class TBSOptimizationSolution(NXObject):
    def __init__(self) -> None: ...
    def Solve(self) -> None: ...
    def GetIterationNumber(self) -> int: ...
    def GetPostResult(self, iterationID: int, postResultName: str) -> CAE.Optimization.TBSOptimizationSolution.ResultStatus: ...
    def GetSmoothResult(self, smooth: CAE.Optimization.TBSSmooth, smoothResultName: str) -> CAE.Optimization.TBSOptimizationSolution.ResultStatus: ...
    def Find(self, journalIdentifier: str) -> TaggedObject: ...
    def Rename(self, name: str, renameResults: bool) -> None: ...
    def Destroy(self, deleteResult: bool) -> None: ...
    @property
    def RestrictAreas(self) -> CAE.Optimization.TBSRestrictAreaCollection: ...
    @RestrictAreas.setter
    def RestrictAreas(self, value: CAE.Optimization.TBSRestrictAreaCollection) -> None: ...
    @property
    def Constraints(self) -> CAE.Optimization.TBSConstraintCollection: ...
    @Constraints.setter
    def Constraints(self, value: CAE.Optimization.TBSConstraintCollection) -> None: ...
    @property
    def DesignVariables(self) -> CAE.Optimization.TBSDesignVariableCollection: ...
    @DesignVariables.setter
    def DesignVariables(self, value: CAE.Optimization.TBSDesignVariableCollection) -> None: ...
    @property
    def Smoothings(self) -> CAE.Optimization.TBSSmoothCollection: ...
    @Smoothings.setter
    def Smoothings(self, value: CAE.Optimization.TBSSmoothCollection) -> None: ...
    @property
    def ControlParameters(self) -> CAE.Optimization.TBSOptimizationParameters: ...
    @ControlParameters.setter
    def ControlParameters(self, value: CAE.Optimization.TBSOptimizationParameters) -> None: ...
    @property
    def DesignArea(self) -> CAE.Optimization.TBSDesignArea: ...
    @DesignArea.setter
    def DesignArea(self, value: CAE.Optimization.TBSDesignArea) -> None: ...
    @property
    def Objectives(self) -> CAE.Optimization.TBSObjectives: ...
    @Objectives.setter
    def Objectives(self, value: CAE.Optimization.TBSObjectives) -> None: ...
    @property
    def OutputControlOptions(self) -> CAE.Optimization.TBSOutputControlOptions: ...
    @OutputControlOptions.setter
    def OutputControlOptions(self, value: CAE.Optimization.TBSOutputControlOptions) -> None: ...
    @property
    def StopCondition(self) -> CAE.Optimization.TBSStopCondition: ...
    @StopCondition.setter
    def StopCondition(self, value: CAE.Optimization.TBSStopCondition) -> None: ...


    class ResultStatus(enum.Enum):
        Valid= 0
        OutOfDate= 1
        Invalid= 2
    

class TBSOptimizationParameters(TaggedObject):
    def __init__(self) -> None: ...


class TBSOptimizationManager(Utilities.NXRemotableObject):
    def __init__(self, owner: CAE.SimSimulation) -> None: ...
    def CreateTopologyOptimizationSolutionBuilder(self, topoSolution: CAE.Optimization.TBSTopologyOptimizationSolution) -> CAE.Optimization.TBSTopologyOptimizationSolutionBuilder: ...
    def CreateShapeOptimizationSolutionBuilder(self, shapeSolution: CAE.Optimization.TBSShapeOptimizationSolution) -> CAE.Optimization.TBSShapeOptimizationSolutionBuilder: ...
    def CreateDesignVariableBuilder(self, designVariable: CAE.Optimization.TBSDesignVariable) -> CAE.Optimization.TBSDesignVariableBuilder: ...
    def CreateDesignResponseBuilder(self, designResponse: CAE.Optimization.TBSDesignResponse) -> CAE.Optimization.TBSDesignResponseBuilder: ...
    def CreateResponseConstraintBuilder(self, responseConstraint: CAE.Optimization.TBSConstraint) -> CAE.Optimization.TBSConstraintBuilder: ...
    def CreateTopologyRestrictAreaBuilder(self, restrictArea: CAE.Optimization.TBSTopologyRestrictArea) -> CAE.Optimization.TBSTopologyRestrictAreaBuilder: ...
    def CreateShapeRestrictAreaBuilder(self, restrictArea: CAE.Optimization.TBSShapeRestrictArea) -> CAE.Optimization.TBSShapeRestrictAreaBuilder: ...
    def CreateSmoothBuilder(self, smooth: CAE.Optimization.TBSSmooth) -> CAE.Optimization.TBSSmoothBuilder: ...
    def CreateSingleObjective(self, designResponse: CAE.Optimization.TBSDesignResponse, weight: float, referenceValue: float) -> CAE.Optimization.TBSSingleObjective: ...
    def CreateLoadCase(self) -> CAE.Optimization.TBSLoadCase: ...
    def Tag(self) -> Tag: ...

    @property
    def OptimizationSolutions(self) -> CAE.Optimization.TBSOptimizationSolutionCollection: ...
    @OptimizationSolutions.setter
    def OptimizationSolutions(self, value: CAE.Optimization.TBSOptimizationSolutionCollection) -> None: ...


class TBSObjectives(TaggedObject):
    def __init__(self) -> None: ...
    def GetObjectives(self) -> typing.List[CAE.Optimization.TBSSingleObjective]: ...
    def SetObjectives(self, objectives: typing.List[CAE.Optimization.TBSSingleObjective]) -> None: ...
    def AddObjectives(self, objectives: typing.List[CAE.Optimization.TBSSingleObjective]) -> None: ...
    def RemoveObjectives(self, objectives: typing.List[CAE.Optimization.TBSSingleObjective], deleteObject: bool) -> None: ...
    @property
    def TargetObjective(self) -> CAE.Optimization.TBSObjectives.ObjectiveType: ...
    @TargetObjective.setter
    def TargetObjective(self, value: CAE.Optimization.TBSObjectives.ObjectiveType) -> None: ...


    class ObjectiveType(enum.Enum):
        Minimum= 0
        Maximum= 1
        MaxMin= 2
    

class TBSMeshSmooth(NXObject):
    def __init__(self) -> None: ...
    @property
    def FixSurfaceNodes(self) -> bool: ...
    @FixSurfaceNodes.setter
    def FixSurfaceNodes(self, value: bool) -> None: ...
    @property
    def MeshSmoothElements(self) -> CAE.Optimization.TBSGroupDefinition: ...
    @MeshSmoothElements.setter
    def MeshSmoothElements(self, value: CAE.Optimization.TBSGroupDefinition) -> None: ...
    @property
    def MeshSmoothStrategy(self) -> CAE.Optimization.TBSMeshSmooth.Strategy: ...
    @MeshSmoothStrategy.setter
    def MeshSmoothStrategy(self, value: CAE.Optimization.TBSMeshSmooth.Strategy) -> None: ...
    @property
    def UseHighestQuality(self) -> bool: ...
    @UseHighestQuality.setter
    def UseHighestQuality(self, value: bool) -> None: ...


    class Strategy(enum.Enum):
        ConstrainedLaplacian= 0
        LocalGradient= 1
    

class TBSLoadCaseManager(TaggedObject):
    def __init__(self) -> None: ...
    def GetLoadCases(self) -> typing.List[CAE.Optimization.TBSLoadCase]: ...
    def SetLoadCases(self, loadCases: typing.List[CAE.Optimization.TBSLoadCase]) -> None: ...
    def AddLoadCases(self, loadCases: typing.List[CAE.Optimization.TBSLoadCase]) -> None: ...
    def RemoveLoadCases(self, loadCases: typing.List[CAE.Optimization.TBSLoadCase], deleteLoadCase: bool) -> None: ...
    @property
    def SelectionOption(self) -> CAE.Optimization.TBSLoadCaseManager.SelectionType: ...
    @SelectionOption.setter
    def SelectionOption(self, value: CAE.Optimization.TBSLoadCaseManager.SelectionType) -> None: ...


    class SelectionType(enum.Enum):
        Maximum= 0
        Minimum= 1
        Sum= 2
    

class TBSLoadCase(TaggedObject):
    def __init__(self) -> None: ...
    def GetSubcase(self, subcaseId: int) -> bool: ...
    def SetSubcase(self, allSubcases: bool, subcaseId: int) -> None: ...
    def GetSubstep(self, subSteps: int) -> bool: ...
    def SetSubstep(self, allSubSteps: bool, subSteps: int) -> None: ...
    @property
    def ShellLayer(self) -> CAE.Optimization.TBSLoadCase.LayerOption: ...
    @ShellLayer.setter
    def ShellLayer(self, value: CAE.Optimization.TBSLoadCase.LayerOption) -> None: ...


    class LayerOption(enum.Enum):
        None_= 0
        Maximum= 1
        Minimum= 2
        Top= 3
        Middle= 4
        Bottom= 5
    

class TBSIOptimizationTest():
    def SolveTest(self) -> None: ...
    def GetTestResultFile(self) -> str: ...


class TBSGroupDefinition(TaggedObject):
    def __init__(self) -> None: ...
    def GetElementType(self) -> CAE.Optimization.TBSGroupDefinition.GroupElementType: ...
    @property
    def Definition(self) -> CAE.Optimization.TBSGroupDefinition.DefinitionType: ...
    @Definition.setter
    def Definition(self, value: CAE.Optimization.TBSGroupDefinition.DefinitionType) -> None: ...
    @property
    def TargetSet(self) -> CAE.SetManager: ...
    @TargetSet.setter
    def TargetSet(self, value: CAE.SetManager) -> None: ...


    class GroupElementType(enum.Enum):
        Element= 0
        Node= 1
    

    class DefinitionType(enum.Enum):
        All= 0
        Selected= 1
        DesignArea= 2
        MeshSmoothingArea= 3
    

class TBSEigenvalueOptimizationParameters(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def ModeNumber(self) -> int: ...
    @ModeNumber.setter
    def ModeNumber(self, value: int) -> None: ...
    @property
    def TrackingMode(self) -> bool: ...
    @TrackingMode.setter
    def TrackingMode(self, value: bool) -> None: ...
    @property
    def TrackingNodes(self) -> CAE.Optimization.TBSGroupDefinition: ...
    @TrackingNodes.setter
    def TrackingNodes(self, value: CAE.Optimization.TBSGroupDefinition) -> None: ...


class TBSDesignVariableCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.Optimization.TBSDesignVariable]: ...
    @typing.overload
    def __init__(self, owner: CAE.Optimization.TBSOptimizationSolution) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, variableName: str) -> CAE.Optimization.TBSDesignVariable: ...
    def Tag(self) -> Tag: ...



class TBSDesignVariableBuilder(CAE.Optimization.TBSBaseDesignVariableBuilder):
    def __init__(self) -> None: ...


class TBSDesignVariable(NXObject):
    def __init__(self) -> None: ...


class TBSDesignResponseBuilder(CAE.Optimization.TBSBaseDesignVariableBuilder):
    def __init__(self) -> None: ...
    @property
    def VariableType(self) -> CAE.Optimization.TBSDesignResponseBuilder.Response: ...
    @VariableType.setter
    def VariableType(self, value: CAE.Optimization.TBSDesignResponseBuilder.Response) -> None: ...


    class Response(enum.Enum):
        DynamicFrequency= 0
        DynamicFrequencyKressissel= 1
        Volume= 2
        VolumeFill= 3
        Weight= 4
        DisplacementAbsolute= 5
        DisplacementX= 6
        DisplacementY= 7
        DisplacementZ= 8
        DisplacementXAbsolute= 9
        DisplacementYAbsolute= 10
        DisplacementZAbsolute= 11
        RotationAbsolute= 12
        RotationX= 13
        RotationY= 14
        RotationZ= 15
        RotationXAbsolute= 16
        RotationYAbsolute= 17
        RotationZAbsolute= 18
        StrainEnergy= 19
        CenterGravityX= 20
        CenterGravityY= 21
        CenterGravityZ= 22
        InertiaXx= 23
        InertiaXy= 24
        InertiaXz= 25
        InertiaYy= 26
        InertiaYz= 27
        InertiaZz= 28
        ReactionForceAbsolute= 29
        ReactionForceX= 30
        ReactionForceY= 31
        ReactionForceZ= 32
        ReactionForceXAbsolute= 33
        ReactionForceYAbsolute= 34
        ReactionForceZAbsolute= 35
        ReactionForceRotationAbsolute= 36
        ReactionForceRotationX= 37
        ReactionForceRotationY= 38
        ReactionForceRotationZ= 39
        ReactionForceRotationXAbsolute= 40
        ReactionForceRotationYAbsolute= 41
        ReactionForceRotationZAbsolute= 42
        InternalForceAbsolute= 43
        InternalForceX= 44
        InternalForceY= 45
        InternalForceZ= 46
        InternalForceXAbsolute= 47
        InternalForceYAbsolute= 48
        InternalForceZAbsolute= 49
        InternalForceRotationAbsolute= 50
        InternalForceRotationX= 51
        InternalForceRotationY= 52
        InternalForceRotationZ= 53
        InternalForceRotationXAbsolute= 54
        InternalForceRotationYAbsolute= 55
        InternalForceRotationZAbsolute= 56
        FrequencyResponseAccelerationX= 57
        FrequencyResponseAccelerationY= 58
        FrequencyResponseAccelerationZ= 59
        FrequencyResponseCompliance= 60
        FrequencyResponseDbaPressure= 61
        FrequencyResponseDbPressure= 62
        FrequencyResponseDisplacementAbsolute= 63
        FrequencyResponseDisplacementXAbsolute= 64
        FrequencyResponseDisplacementYAbsolute= 65
        FrequencyResponseDisplacementZAbsolute= 66
        FrequencyResponsePhaseXAbsolute= 67
        FrequencyResponsePhaseYAbsolute= 68
        FrequencyResponsePhaseZAbsolute= 69
        FrequencyResponsePressure= 70
        FrequencyResponseRmsPressure= 71
        FrequencyResponseVelocityXAbsolute= 72
        FrequencyResponseVelocityYAbsolute= 73
        FrequencyResponseVelocityZAbsolute= 74
        FrequencyResponseNvhSolid= 75
        FrequencyResponseNvhShell= 76
        MisesStressHypothesis= 77
        MaximumPrincipalStress= 78
        MinimumAbsolutePrincipalStress= 79
        MaximumAbsolutePrincipalStress= 80
    

class TBSDesignResponse(CAE.Optimization.TBSDesignVariable):
    def __init__(self) -> None: ...


class TBSDesignArea(NXObject):
    def __init__(self) -> None: ...
    @property
    def DesignElements(self) -> CAE.Optimization.TBSGroupDefinition: ...
    @DesignElements.setter
    def DesignElements(self, value: CAE.Optimization.TBSGroupDefinition) -> None: ...


class TBSConstraintCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.Optimization.TBSConstraint]: ...
    @typing.overload
    def __init__(self, owner: CAE.Optimization.TBSOptimizationSolution) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, constraintName: str) -> CAE.Optimization.TBSConstraint: ...
    def Tag(self) -> Tag: ...



class TBSConstraintBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def ConstraintType(self) -> CAE.Optimization.TBSConstraintBuilder.ConstraintOption: ...
    @ConstraintType.setter
    def ConstraintType(self, value: CAE.Optimization.TBSConstraintBuilder.ConstraintOption) -> None: ...
    @property
    def ConstraintValue(self) -> Expression: ...
    @ConstraintValue.setter
    def ConstraintValue(self, value: Expression) -> None: ...
    @property
    def DesignResponse(self) -> CAE.Optimization.TBSDesignResponse: ...
    @DesignResponse.setter
    def DesignResponse(self, value: CAE.Optimization.TBSDesignResponse) -> None: ...
    @property
    def Magnitude(self) -> CAE.Optimization.TBSConstraintBuilder.MagnitudeType: ...
    @Magnitude.setter
    def Magnitude(self, value: CAE.Optimization.TBSConstraintBuilder.MagnitudeType) -> None: ...
    @property
    def NameDescription(self) -> CAE.Optimization.NameDescription: ...
    @NameDescription.setter
    def NameDescription(self, value: CAE.Optimization.NameDescription) -> None: ...


    class MagnitudeType(enum.Enum):
        Relative= 0
        Absolute= 1
    

    class ConstraintOption(enum.Enum):
        Eq= 0
        Lt= 1
        Gt= 2
    

class TBSConstraint(NXObject):
    def __init__(self) -> None: ...


class TBSCheckDOF(NXObject):
    def __init__(self) -> None: ...
    @property
    def Dofs(self) -> CAE.Optimization.TBSCheckDOF.DofSettings: ...
    @Dofs.setter
    def Dofs(self, value: CAE.Optimization.TBSCheckDOF.DofSettings) -> None: ...
    @property
    def ReferencedCoordinateSystem(self) -> CoordinateSystem: ...
    @ReferencedCoordinateSystem.setter
    def ReferencedCoordinateSystem(self, value: CoordinateSystem) -> None: ...


    class TBSCheckDOFDofSettings():
        @property
        def Dof1(self) -> CAE.Optimization.TBSCheckDOF.CheckDofOption: ...
        @Dof1.setter
        def Dof1(self, value: CAE.Optimization.TBSCheckDOF.CheckDofOption) -> None: ...
        @property
        def Dof2(self) -> CAE.Optimization.TBSCheckDOF.CheckDofOption: ...
        @Dof2.setter
        def Dof2(self, value: CAE.Optimization.TBSCheckDOF.CheckDofOption) -> None: ...
        @property
        def Dof3(self) -> CAE.Optimization.TBSCheckDOF.CheckDofOption: ...
        @Dof3.setter
        def Dof3(self, value: CAE.Optimization.TBSCheckDOF.CheckDofOption) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, Dof1: CAE.Optimization.TBSCheckDOF.CheckDofOption, Dof2: CAE.Optimization.TBSCheckDOF.CheckDofOption, Dof3: CAE.Optimization.TBSCheckDOF.CheckDofOption) -> None: ...
    

    class CheckDofOption(enum.Enum):
        Fix= 0
        Free= 1
    

class TBSCastCondition(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def CheckingGroup(self) -> CAE.Optimization.TBSGroupDefinition: ...
    @CheckingGroup.setter
    def CheckingGroup(self, value: CAE.Optimization.TBSGroupDefinition) -> None: ...
    @property
    def DraftAngle(self) -> Expression: ...
    @DraftAngle.setter
    def DraftAngle(self, value: Expression) -> None: ...
    @property
    def MiddlePlane(self) -> CAE.Optimization.TBSCastCondition.MiddlePlaneType: ...
    @MiddlePlane.setter
    def MiddlePlane(self, value: CAE.Optimization.TBSCastCondition.MiddlePlaneType) -> None: ...
    @property
    def MiddlePlanePoint(self) -> Point: ...
    @MiddlePlanePoint.setter
    def MiddlePlanePoint(self, value: Point) -> None: ...
    @property
    def PullCoordinateSystem(self) -> CoordinateSystem: ...
    @PullCoordinateSystem.setter
    def PullCoordinateSystem(self, value: CoordinateSystem) -> None: ...
    @property
    def PullDirection(self) -> Direction: ...
    @PullDirection.setter
    def PullDirection(self, value: Direction) -> None: ...
    @property
    def Radius(self) -> Expression: ...
    @Radius.setter
    def Radius(self, value: Expression) -> None: ...


    class MiddlePlaneType(enum.Enum):
        None_= 0
        Automatic= 1
        AutomaticTight= 2
        Point= 3
        Surface= 4
        Stamp= 5
    

class TBSBaseDesignVariableBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def DesignElements(self) -> CAE.Optimization.TBSGroupDefinition: ...
    @DesignElements.setter
    def DesignElements(self, value: CAE.Optimization.TBSGroupDefinition) -> None: ...
    @property
    def DesignNodes(self) -> CAE.Optimization.TBSGroupDefinition: ...
    @DesignNodes.setter
    def DesignNodes(self, value: CAE.Optimization.TBSGroupDefinition) -> None: ...
    @property
    def GroupOperatorOption(self) -> CAE.Optimization.TBSBaseDesignVariableBuilder.GroupOperator: ...
    @GroupOperatorOption.setter
    def GroupOperatorOption(self, value: CAE.Optimization.TBSBaseDesignVariableBuilder.GroupOperator) -> None: ...
    @property
    def LoadCases(self) -> CAE.Optimization.TBSLoadCaseManager: ...
    @LoadCases.setter
    def LoadCases(self, value: CAE.Optimization.TBSLoadCaseManager) -> None: ...
    @property
    def NameDescription(self) -> CAE.Optimization.NameDescription: ...
    @NameDescription.setter
    def NameDescription(self, value: CAE.Optimization.NameDescription) -> None: ...
    @property
    def ReferenceCoordinateSystem(self) -> CoordinateSystem: ...
    @ReferenceCoordinateSystem.setter
    def ReferenceCoordinateSystem(self, value: CoordinateSystem) -> None: ...
    @property
    def SelectionAreaType(self) -> CAE.Optimization.TBSGroupDefinition.GroupElementType: ...
    @SelectionAreaType.setter
    def SelectionAreaType(self, value: CAE.Optimization.TBSGroupDefinition.GroupElementType) -> None: ...


    class GroupOperator(enum.Enum):
        Max= 0
        Min= 1
        Sum= 2
        Count= 3
        Deviation= 4
    

class Solver(enum.Enum):
    Optimization= 0
    GlobalSensitivity= 1
    AltairHyperOpt= 2


class Response(enum.Enum):
    None_= 0
    Weight= 1
    Volume= 2
    Frequency= 3
    Temperature= 4
    StressVonMises= 5
    StrainVonMises= 6
    TranslationX= 7
    TranslationY= 8
    TranslationZ= 9
    RotationX= 10
    RotationY= 11
    RotationZ= 12
    Stress2DMaximumShear= 13
    Stress2DMajorPrincipal= 14
    Stress2DMinorPrincipal= 15
    Stress2DVonMises= 16
    Stress2DMaximumShearBottom= 17
    Stress2DMajorPrincipalBottom= 18
    Stress2DMinorPrincipalBottom= 19
    Stress2DVonMisesBottom= 20
    Strain2DMaximumShear= 21
    Strain2DMajorPrincipal= 22
    Strain2DMinorPrincipal= 23
    Strain2DVonMises= 24
    Strain2DMaximumShearBottom= 25
    Strain2DMajorPrincipalBottom= 26
    Strain2DMinorPrincipalBottom= 27
    Strain2DVonMisesBottom= 28
    Stress1DVonMisesStressRecoveryPointC= 29
    Stress1DVonMisesStressRecoveryPointD= 30
    Stress1DVonMisesStressRecoveryPointE= 31
    Stress1DVonMisesStressRecoveryPointF= 32
    Stress1DVonMisesMaximum= 33
    Stress1DVonMisesMinimum= 34
    Strain1DVonMisesStressRecoveryPointC= 35
    Strain1DVonMisesStressRecoveryPointD= 36
    Strain1DVonMisesStressRecoveryPointE= 37
    Strain1DVonMisesStressRecoveryPointF= 38
    Strain1DVonMisesMaximum= 39
    Strain1DVonMisesMinimum= 40
    Stress3DFirstPrincipal= 41
    Stress3DSecondPrincipal= 42
    Stress3DThirdPrincipal= 43
    Stress3DVonMises= 44
    Strain3DFirstPrincipal= 45
    Strain3DSecondPrincipal= 46
    Strain3DThirdPrincipal= 47
    Strain3DVonMises= 48
    ResultMeasure= 49


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class NameDescription(TaggedObject):
    def __init__(self) -> None: ...
    def GetDescription(self) -> str: ...
    def SetDescription(self, description: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...


class Limit(enum.Enum):
    Upper= 0
    Lower= 1


class Hookes(enum.Enum):
    Top= 0
    Bottom= 1
    Middle= 2
    Minimum= 3
    Maximum= 4


class Goal(enum.Enum):
    Minimum= 0
    Maximum= 1
    Target= 2


class Geometry(enum.Enum):
    Body= 0
    Face= 1
    Edge= 2
    Point= 3
    Curve= 4


class DAOStopCondition(NXObject):
    def __init__(self) -> None: ...
    @property
    def AbsoluteConvergence(self) -> float: ...
    @AbsoluteConvergence.setter
    def AbsoluteConvergence(self, value: float) -> None: ...
    @property
    def ConstraintChecking(self) -> bool: ...
    @ConstraintChecking.setter
    def ConstraintChecking(self, value: bool) -> None: ...
    @property
    def MaxConstraintViolation(self) -> float: ...
    @MaxConstraintViolation.setter
    def MaxConstraintViolation(self, value: float) -> None: ...
    @property
    def MaxIterations(self) -> int: ...
    @MaxIterations.setter
    def MaxIterations(self, value: int) -> None: ...
    @property
    def PerturbationFraction(self) -> float: ...
    @PerturbationFraction.setter
    def PerturbationFraction(self, value: float) -> None: ...
    @property
    def RelativeConvergence(self) -> float: ...
    @RelativeConvergence.setter
    def RelativeConvergence(self, value: float) -> None: ...
    @property
    def SaveAllIterationResults(self) -> bool: ...
    @SaveAllIterationResults.setter
    def SaveAllIterationResults(self, value: bool) -> None: ...


class DAOSolutionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.Optimization.DAOSolution]: ...
    @typing.overload
    def __init__(self, owner: CAE.Optimization.DAOOptimizationManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateOptimizationBuilder(self, optimizationSolution: CAE.Optimization.DAOSolution) -> CAE.Optimization.DAOSolutionBuilder: ...
    def FindObject(self, solutionName: str) -> CAE.Optimization.DAOSolution: ...
    def CreateConstraintBuilder(self, designConstraint: CAE.Optimization.DAOConstraint) -> CAE.Optimization.DAOConstraintBuilder: ...
    def CreateDesignVariableBuilder(self, designVariable: CAE.Optimization.DAODesignVariable) -> CAE.Optimization.DAODesignVariableBuilder: ...
    def Tag(self) -> Tag: ...



class DAOSolutionBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AnalysisSolution(self) -> CAE.SimSolution: ...
    @AnalysisSolution.setter
    def AnalysisSolution(self, value: CAE.SimSolution) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def SolverType(self) -> CAE.Optimization.Solver: ...
    @SolverType.setter
    def SolverType(self, value: CAE.Optimization.Solver) -> None: ...


class DAOSolution(NXObject):
    def __init__(self) -> None: ...
    def GetDesignObjective(self) -> CAE.Optimization.DAOObjective: ...
    def GetDesignConstraints(self) -> typing.List[CAE.Optimization.DAOConstraint]: ...
    def SetDesignConstraints(self, designConstraints: typing.List[CAE.Optimization.DAOConstraint]) -> None: ...
    def GetOptimizationDesignVariables(self) -> typing.List[CAE.Optimization.DAODesignVariable]: ...
    def SetOptimizationDesignVariables(self, designVariables: typing.List[CAE.Optimization.DAOConstraint]) -> None: ...
    def GetGlobalSensitivityDesignVariables(self) -> typing.List[CAE.Optimization.DAODesignVariable]: ...
    def SetGlobalSensitivityDesignVariables(self, designVariables: typing.List[CAE.Optimization.DAODesignVariable]) -> None: ...
    def GetSolutionControls(self) -> CAE.Optimization.DAOStopCondition: ...
    def Solve(self) -> None: ...
    def DeleteSolution(self) -> None: ...
    def ActivateSolution(self) -> None: ...
    def CreateConstraintBuilder(self, optimizationConstraint: CAE.Optimization.DAOConstraint) -> CAE.Optimization.DAOConstraintBuilder: ...
    def CreateDesignVariableBuilder(self, optimizationDesvar: CAE.Optimization.DAODesignVariable) -> CAE.Optimization.DAODesignVariableBuilder: ...
    @property
    def DesignConstraint(self) -> CAE.Optimization.DAOConstraintCollection: ...
    @DesignConstraint.setter
    def DesignConstraint(self, value: CAE.Optimization.DAOConstraintCollection) -> None: ...
    @property
    def DesignVariable(self) -> CAE.Optimization.DAODesignVariableCollection: ...
    @DesignVariable.setter
    def DesignVariable(self, value: CAE.Optimization.DAODesignVariableCollection) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def OptimizerControl(self) -> CAE.Optimization.DAOStopCondition: ...
    @OptimizerControl.setter
    def OptimizerControl(self, value: CAE.Optimization.DAOStopCondition) -> None: ...
    @property
    def SolverType(self) -> CAE.Optimization.Solver: ...
    @SolverType.setter
    def SolverType(self, value: CAE.Optimization.Solver) -> None: ...


class DAOOptimizationManager(Utilities.NXRemotableObject):
    def __init__(self, owner: CAE.SimSimulation) -> None: ...
    def Tag(self) -> Tag: ...

    @property
    def OptimizationSolution(self) -> CAE.Optimization.DAOSolutionCollection: ...
    @OptimizationSolution.setter
    def OptimizationSolution(self, value: CAE.Optimization.DAOSolutionCollection) -> None: ...


class DAOObjective(NXObject):
    def __init__(self) -> None: ...
    def GetGeometry(self) -> typing.List[DisplayableObject]: ...
    def SetGeometry(self, geometry: typing.List[DisplayableObject]) -> None: ...
    def GetNumberResultGroup(self) -> int: ...
    def GetResults(self, resultGroupIndex: int) -> float: ...
    @property
    def CategoryType(self) -> CAE.Optimization.Category: ...
    @CategoryType.setter
    def CategoryType(self, value: CAE.Optimization.Category) -> None: ...
    @property
    def GeometryType(self) -> CAE.Optimization.Geometry: ...
    @GeometryType.setter
    def GeometryType(self, value: CAE.Optimization.Geometry) -> None: ...
    @property
    def LoadCase(self) -> int: ...
    @LoadCase.setter
    def LoadCase(self, value: int) -> None: ...
    @property
    def ModeNumber(self) -> int: ...
    @ModeNumber.setter
    def ModeNumber(self, value: int) -> None: ...
    @property
    def ObjectiveGoal(self) -> CAE.Optimization.Goal: ...
    @ObjectiveGoal.setter
    def ObjectiveGoal(self, value: CAE.Optimization.Goal) -> None: ...
    @property
    def Response(self) -> CAE.Optimization.Response: ...
    @Response.setter
    def Response(self, value: CAE.Optimization.Response) -> None: ...
    @property
    def ResultMeasure(self) -> CAE.ResultMeasure: ...
    @ResultMeasure.setter
    def ResultMeasure(self, value: CAE.ResultMeasure) -> None: ...
    @property
    def TargetUnit(self) -> Unit: ...
    @TargetUnit.setter
    def TargetUnit(self, value: Unit) -> None: ...
    @property
    def TargetValue(self) -> float: ...
    @TargetValue.setter
    def TargetValue(self, value: float) -> None: ...


class DAODesignVariableCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.Optimization.DAODesignVariable]: ...
    @typing.overload
    def __init__(self, owner: CAE.Optimization.DAOSolution) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, designVariableName: str) -> CAE.Optimization.DAODesignVariable: ...
    def Tag(self) -> Tag: ...



class DAODesignVariableBuilder(Builder):
    def __init__(self) -> None: ...
    def GetVariable(self, variableType: CAE.Optimization.DAODesignVariableBuilder.Variable, variableExpression: Expression) -> None: ...
    def SetVariable(self, variableType: CAE.Optimization.DAODesignVariableBuilder.Variable, variableExpression: Expression) -> None: ...
    @property
    def GlobalSensitivityFlag(self) -> bool: ...
    @GlobalSensitivityFlag.setter
    def GlobalSensitivityFlag(self, value: bool) -> None: ...
    @property
    def LowerLimit(self) -> float: ...
    @LowerLimit.setter
    def LowerLimit(self, value: float) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def UpperLimit(self) -> float: ...
    @UpperLimit.setter
    def UpperLimit(self, value: float) -> None: ...


    class Variable(enum.Enum):
        SectionProperty= 0
        ShellProperty= 1
        FeatureDimension= 2
        SketchDimension= 3
        AllExpressions= 4
        Count= 5
    

class DAODesignVariable(NXObject):
    def __init__(self) -> None: ...
    def GetResults(self) -> float: ...


class DAOConstraintCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.Optimization.DAOConstraint]: ...
    @typing.overload
    def __init__(self, owner: CAE.Optimization.DAOSolution) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, designConstraintName: str) -> CAE.Optimization.DAOConstraint: ...
    def Tag(self) -> Tag: ...



class DAOConstraintBuilder(Builder):
    def __init__(self) -> None: ...
    def GetGeometry(self) -> typing.List[DisplayableObject]: ...
    def SetGeometry(self, geometry: typing.List[DisplayableObject]) -> None: ...
    @property
    def CategoryType(self) -> CAE.Optimization.Category: ...
    @CategoryType.setter
    def CategoryType(self, value: CAE.Optimization.Category) -> None: ...
    @property
    def GeometryType(self) -> CAE.Optimization.Geometry: ...
    @GeometryType.setter
    def GeometryType(self, value: CAE.Optimization.Geometry) -> None: ...
    @property
    def LimitType(self) -> CAE.Optimization.Limit: ...
    @LimitType.setter
    def LimitType(self, value: CAE.Optimization.Limit) -> None: ...
    @property
    def LimitUnit(self) -> Unit: ...
    @LimitUnit.setter
    def LimitUnit(self, value: Unit) -> None: ...
    @property
    def LimitValue(self) -> float: ...
    @LimitValue.setter
    def LimitValue(self, value: float) -> None: ...
    @property
    def LoadCase(self) -> int: ...
    @LoadCase.setter
    def LoadCase(self, value: int) -> None: ...
    @property
    def ModeNumber(self) -> int: ...
    @ModeNumber.setter
    def ModeNumber(self, value: int) -> None: ...
    @property
    def Response(self) -> CAE.Optimization.Response: ...
    @Response.setter
    def Response(self, value: CAE.Optimization.Response) -> None: ...
    @property
    def ResultMeasure(self) -> CAE.ResultMeasure: ...
    @ResultMeasure.setter
    def ResultMeasure(self, value: CAE.ResultMeasure) -> None: ...


class DAOConstraint(NXObject):
    def __init__(self) -> None: ...
    def GetNumberResultGroup(self) -> int: ...
    def GetResults(self, resultGroupIndex: int) -> float: ...


class Category(enum.Enum):
    OneDimension= 0
    TwoDimension= 1
    ThreeDimension= 2
    All= 3


