from . import SectionAnalysis
from ...NXOpen import *

import typing
import enum

class SurfaceIntersectionBuilder(Builder):
    def __init__(self) -> None: ...
    def UpdateWorkView(self) -> None: ...
    @property
    def CalculationMethod(self) -> GeometricAnalysis.SurfaceIntersectionBuilder.CalculationTypes: ...
    @CalculationMethod.setter
    def CalculationMethod(self, value: GeometricAnalysis.SurfaceIntersectionBuilder.CalculationTypes) -> None: ...
    @property
    def CombOptions(self) -> GeometricUtilities.CombOptionsBuilder: ...
    @CombOptions.setter
    def CombOptions(self, value: GeometricUtilities.CombOptionsBuilder) -> None: ...
    @property
    def DynamicProjection(self) -> bool: ...
    @DynamicProjection.setter
    def DynamicProjection(self, value: bool) -> None: ...
    @property
    def FirstFaceSet(self) -> ScCollector: ...
    @FirstFaceSet.setter
    def FirstFaceSet(self, value: ScCollector) -> None: ...
    @property
    def NeedleDirection(self) -> GeometricAnalysis.SurfaceIntersectionBuilder.DirectionTypes: ...
    @NeedleDirection.setter
    def NeedleDirection(self, value: GeometricAnalysis.SurfaceIntersectionBuilder.DirectionTypes) -> None: ...
    @property
    def ProjectionNormalFace(self) -> GeometricAnalysis.SurfaceIntersectionBuilder.NormalTypes: ...
    @ProjectionNormalFace.setter
    def ProjectionNormalFace(self, value: GeometricAnalysis.SurfaceIntersectionBuilder.NormalTypes) -> None: ...
    @property
    def ProjectionOption(self) -> GeometricAnalysis.SurfaceIntersectionBuilder.ProjectionTypes: ...
    @ProjectionOption.setter
    def ProjectionOption(self, value: GeometricAnalysis.SurfaceIntersectionBuilder.ProjectionTypes) -> None: ...
    @property
    def ProjectionXYZ(self) -> GeometricAnalysis.SurfaceIntersectionBuilder.XyzTypes: ...
    @ProjectionXYZ.setter
    def ProjectionXYZ(self, value: GeometricAnalysis.SurfaceIntersectionBuilder.XyzTypes) -> None: ...
    @property
    def ScalingMethod(self) -> GeometricAnalysis.SurfaceIntersectionBuilder.ScalingTypes: ...
    @ScalingMethod.setter
    def ScalingMethod(self, value: GeometricAnalysis.SurfaceIntersectionBuilder.ScalingTypes) -> None: ...
    @property
    def SecondFaceSet(self) -> ScCollector: ...
    @SecondFaceSet.setter
    def SecondFaceSet(self, value: ScCollector) -> None: ...
    @property
    def Vector(self) -> Direction: ...
    @Vector.setter
    def Vector(self, value: Direction) -> None: ...


    class XyzTypes(enum.Enum):
        X= 0
        Y= 1
        Z= 2
    

    class ScalingTypes(enum.Enum):
        Linear= 0
        Logarithmic= 1
    

    class ProjectionTypes(enum.Enum):
        None_= 0
        Normal= 1
        Vector= 2
        View= 3
        Xyz= 4
    

    class NormalTypes(enum.Enum):
        FaceSet1= 0
        FaceSet2= 1
    

    class LabelValues(enum.Enum):
        Curvature= 0
        RadiusOfCurvature= 1
    

    class DirectionTypes(enum.Enum):
        Inside= 0
        Outside= 1
    

    class CalculationTypes(enum.Enum):
        Curvature= 0
        RadiusofCurvature= 1
    

class SurfaceIntersection(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class SurfaceContinuityAnalysisBuilder(Builder):
    def __init__(self) -> None: ...
    def UpdateFirstEdgeFace(self, edgeOrFace: DisplayableObject, selectionPoint: Point3d) -> None: ...
    def UpdateSecondEdgeFace(self, edgeOrFace: DisplayableObject, selectionPoint: Point3d) -> None: ...
    def UpdateFace(self, face: Face, selectionPoint: Point3d) -> None: ...
    def GetFace1Array(self) -> typing.List[Face]: ...
    def DeselectFirstEdgeFace(self, edge: DisplayableObject, face: DisplayableObject) -> None: ...
    def SelectFirstEdgeFace(self, edge: DisplayableObject, face: DisplayableObject) -> None: ...
    def DeselectSecondEdgeFace(self, edge: DisplayableObject, face: DisplayableObject) -> None: ...
    def SelectSecondEdgeFace(self, edge: DisplayableObject, face: DisplayableObject) -> None: ...
    @property
    def AngularThreshold(self) -> Expression: ...
    @AngularThreshold.setter
    def AngularThreshold(self, value: Expression) -> None: ...
    @property
    def CombOptions(self) -> GeometricUtilities.CombOptionsBuilder: ...
    @CombOptions.setter
    def CombOptions(self, value: GeometricUtilities.CombOptionsBuilder) -> None: ...
    @property
    def CurvatureCheck(self) -> GeometricAnalysis.SurfaceContinuityAnalysisBuilder.CurvatureType: ...
    @CurvatureCheck.setter
    def CurvatureCheck(self, value: GeometricAnalysis.SurfaceContinuityAnalysisBuilder.CurvatureType) -> None: ...
    @property
    def DistanceThreshold(self) -> Expression: ...
    @DistanceThreshold.setter
    def DistanceThreshold(self, value: Expression) -> None: ...
    @property
    def DynamicLabel(self) -> Features.GeometricConstraintDataManager: ...
    @DynamicLabel.setter
    def DynamicLabel(self, value: Features.GeometricConstraintDataManager) -> None: ...
    @property
    def Face(self) -> SelectNXObjectList: ...
    @Face.setter
    def Face(self, value: SelectNXObjectList) -> None: ...
    @property
    def FirstEdge(self) -> SelectNXObjectList: ...
    @FirstEdge.setter
    def FirstEdge(self, value: SelectNXObjectList) -> None: ...
    @property
    def G0(self) -> bool: ...
    @G0.setter
    def G0(self, value: bool) -> None: ...
    @property
    def G0Tolerance(self) -> float: ...
    @G0Tolerance.setter
    def G0Tolerance(self, value: float) -> None: ...
    @property
    def G1(self) -> bool: ...
    @G1.setter
    def G1(self, value: bool) -> None: ...
    @property
    def G1Tolerance(self) -> float: ...
    @G1Tolerance.setter
    def G1Tolerance(self, value: float) -> None: ...
    @property
    def G2(self) -> bool: ...
    @G2.setter
    def G2(self, value: bool) -> None: ...
    @property
    def G2Tolerance(self) -> float: ...
    @G2Tolerance.setter
    def G2Tolerance(self, value: float) -> None: ...
    @property
    def G3(self) -> bool: ...
    @G3.setter
    def G3(self, value: bool) -> None: ...
    @property
    def G3Tolerance(self) -> float: ...
    @G3Tolerance.setter
    def G3Tolerance(self, value: float) -> None: ...
    @property
    def MultiFace(self) -> SelectNXObjectList: ...
    @MultiFace.setter
    def MultiFace(self, value: SelectNXObjectList) -> None: ...
    @property
    def ReportPer(self) -> int: ...
    @ReportPer.setter
    def ReportPer(self, value: int) -> None: ...
    @property
    def SecondEdge(self) -> SelectNXObjectList: ...
    @SecondEdge.setter
    def SecondEdge(self, value: SelectNXObjectList) -> None: ...
    @property
    def ShowOutOfTolerance(self) -> bool: ...
    @ShowOutOfTolerance.setter
    def ShowOutOfTolerance(self, value: bool) -> None: ...
    @property
    def ToleranceMarkup(self) -> bool: ...
    @ToleranceMarkup.setter
    def ToleranceMarkup(self, value: bool) -> None: ...
    @property
    def Type(self) -> GeometricAnalysis.SurfaceContinuityAnalysisBuilder.Types: ...
    @Type.setter
    def Type(self, value: GeometricAnalysis.SurfaceContinuityAnalysisBuilder.Types) -> None: ...


    class Types(enum.Enum):
        EdgeToEdge= 0
        EdgeToFace= 1
        MultiFace= 2
    

    class ReportingType(enum.Enum):
        Analysis= 0
        Pair= 1
    

    class CurvatureType(enum.Enum):
        Sectional= 0
        Gaussian= 1
        Mean= 2
        Absolute= 3
    

class SurfaceContinuityAnalysis(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class SurfaceAnalysisDisplay(Utilities.NXRemotableObject):
    def __init__(self, owner: GeometricAnalysis.AnalysisObjectCollection) -> None: ...
    def SetShowFlag(self, surface: DisplayableObject, choice: GeometricAnalysis.SurfaceAnalysisDisplay.ShowFlagType, on: bool) -> None: ...
    def Tag(self) -> Tag: ...



    class ShowFlagType(enum.Enum):
        Pole= 0
        Knot= 1
    

class SolidDensity(Builder):
    def __init__(self) -> None: ...
    @property
    def Density(self) -> float: ...
    @Density.setter
    def Density(self, value: float) -> None: ...
    @property
    def Solids(self) -> SelectObjectList: ...
    @Solids.setter
    def Solids(self, value: SelectObjectList) -> None: ...
    @property
    def Units(self) -> GeometricAnalysis.SolidDensity.UnitsType: ...
    @Units.setter
    def Units(self, value: GeometricAnalysis.SolidDensity.UnitsType) -> None: ...


    class UnitsType(enum.Enum):
        PoundsPerCubicInches= 0
        PoundsPerCubicFeet= 1
        GramsPerCubicCentimeters= 2
        KilogramsPerCubicMeters= 3
    

class SlopeAnalysisBuilder(Builder):
    def __init__(self) -> None: ...
    def CreatePMILabel(self, location: Point3d, face: DisplayableObject) -> None: ...
    def StartSlopeAnalysis(self) -> None: ...
    @property
    def DataRange(self) -> GeometricAnalysis.FaceAnalysisDataRangeBuilder: ...
    @DataRange.setter
    def DataRange(self, value: GeometricAnalysis.FaceAnalysisDataRangeBuilder) -> None: ...
    @property
    def DisplayMode(self) -> GeometricAnalysis.SlopeAnalysisBuilder.DisplayModes: ...
    @DisplayMode.setter
    def DisplayMode(self, value: GeometricAnalysis.SlopeAnalysisBuilder.DisplayModes) -> None: ...
    @property
    def DisplaySettings(self) -> GeometricAnalysis.FaceAnalysisDisplayBuilder: ...
    @DisplaySettings.setter
    def DisplaySettings(self, value: GeometricAnalysis.FaceAnalysisDisplayBuilder) -> None: ...
    @property
    def Faces(self) -> SelectDisplayableObjectList: ...
    @Faces.setter
    def Faces(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def Normals(self) -> GeometricAnalysis.FaceAnalysisNormalsBuilder: ...
    @Normals.setter
    def Normals(self, value: GeometricAnalysis.FaceAnalysisNormalsBuilder) -> None: ...
    @property
    def NumberOfContourLines(self) -> int: ...
    @NumberOfContourLines.setter
    def NumberOfContourLines(self, value: int) -> None: ...
    @property
    def PmiPoint(self) -> SelectNXObjectList: ...
    @PmiPoint.setter
    def PmiPoint(self, value: SelectNXObjectList) -> None: ...
    @property
    def SpikeLength(self) -> float: ...
    @SpikeLength.setter
    def SpikeLength(self, value: float) -> None: ...
    @property
    def Vector(self) -> Direction: ...
    @Vector.setter
    def Vector(self, value: Direction) -> None: ...


    class DisplayModes(enum.Enum):
        Fringe= 0
        Hedgehog= 1
        ContourLines= 2
    

class SimpleInterference(Builder):
    def __init__(self) -> None: ...
    def PerformCheck(self) -> GeometricAnalysis.SimpleInterference.Result: ...
    def HighlightNextPair(self) -> bool: ...
    def GetInterferenceResults(self) -> typing.List[NXObject]: ...
    def Reset(self) -> None: ...
    @property
    def FaceInterferenceType(self) -> GeometricAnalysis.SimpleInterference.FaceInterferenceMethod: ...
    @FaceInterferenceType.setter
    def FaceInterferenceType(self, value: GeometricAnalysis.SimpleInterference.FaceInterferenceMethod) -> None: ...
    @property
    def FirstBody(self) -> SelectObject: ...
    @FirstBody.setter
    def FirstBody(self, value: SelectObject) -> None: ...
    @property
    def InterferenceType(self) -> GeometricAnalysis.SimpleInterference.InterferenceMethod: ...
    @InterferenceType.setter
    def InterferenceType(self, value: GeometricAnalysis.SimpleInterference.InterferenceMethod) -> None: ...
    @property
    def SecondBody(self) -> SelectObject: ...
    @SecondBody.setter
    def SecondBody(self, value: SelectObject) -> None: ...


    class Result(enum.Enum):
        NoInterference= 0
        OnlyEdgesOrFacesInterfere= 1
        InterferenceExists= 2
        CanNotPerformCheck= 3
    

    class InterferenceMethod(enum.Enum):
        InterferingFaces= 0
        InterferenceSolid= 1
    

    class FaceInterferenceMethod(enum.Enum):
        FirstPairOnly= 0
        AllPairs= 1
    

class SheetBoundaryAnalysisBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Bodies(self) -> ScCollector: ...
    @Bodies.setter
    def Bodies(self, value: ScCollector) -> None: ...
    @property
    def EmphasisColor(self) -> NXColor: ...
    @EmphasisColor.setter
    def EmphasisColor(self, value: NXColor) -> None: ...


class SheetBoundaryAnalysis(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class SectionAnalysisObject(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class ReflectionAnalysisBuilder(Builder):
    def __init__(self) -> None: ...
    def StartReflectionAnalysis(self) -> None: ...
    @property
    def DisplayResolution(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @DisplayResolution.setter
    def DisplayResolution(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def FaceReflectivityScale(self) -> int: ...
    @FaceReflectivityScale.setter
    def FaceReflectivityScale(self, value: int) -> None: ...
    @property
    def Faces(self) -> SelectDisplayableObjectList: ...
    @Faces.setter
    def Faces(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...
    @property
    def ImageMovementType(self) -> GeometricAnalysis.ReflectionAnalysisBuilder.ImageMovementTypes: ...
    @ImageMovementType.setter
    def ImageMovementType(self, value: GeometricAnalysis.ReflectionAnalysisBuilder.ImageMovementTypes) -> None: ...
    @property
    def ImagePosition(self) -> int: ...
    @ImagePosition.setter
    def ImagePosition(self, value: int) -> None: ...
    @property
    def ImageSizeSetting(self) -> GeometricAnalysis.ReflectionAnalysisBuilder.ImageSizeOption: ...
    @ImageSizeSetting.setter
    def ImageSizeSetting(self, value: GeometricAnalysis.ReflectionAnalysisBuilder.ImageSizeOption) -> None: ...
    @property
    def LineImageType(self) -> GeometricAnalysis.ReflectionAnalysisBuilder.LineImageTypes: ...
    @LineImageType.setter
    def LineImageType(self, value: GeometricAnalysis.ReflectionAnalysisBuilder.LineImageTypes) -> None: ...
    @property
    def LineNumber(self) -> GeometricAnalysis.ReflectionAnalysisBuilder.NumberOfLinesOptions: ...
    @LineNumber.setter
    def LineNumber(self, value: GeometricAnalysis.ReflectionAnalysisBuilder.NumberOfLinesOptions) -> None: ...
    @property
    def LineOrientation(self) -> GeometricAnalysis.ReflectionAnalysisBuilder.LineOrientationType: ...
    @LineOrientation.setter
    def LineOrientation(self, value: GeometricAnalysis.ReflectionAnalysisBuilder.LineOrientationType) -> None: ...
    @property
    def LineThickness(self) -> GeometricAnalysis.ReflectionAnalysisBuilder.LineThicknessType: ...
    @LineThickness.setter
    def LineThickness(self, value: GeometricAnalysis.ReflectionAnalysisBuilder.LineThicknessType) -> None: ...
    @property
    def Normals(self) -> GeometricAnalysis.FaceAnalysisNormalsBuilder: ...
    @Normals.setter
    def Normals(self, value: GeometricAnalysis.FaceAnalysisNormalsBuilder) -> None: ...
    @property
    def SceneImageOption(self) -> GeometricAnalysis.ReflectionAnalysisBuilder.SceneImageType: ...
    @SceneImageOption.setter
    def SceneImageOption(self, value: GeometricAnalysis.ReflectionAnalysisBuilder.SceneImageType) -> None: ...
    @property
    def ShowFacetEdge(self) -> bool: ...
    @ShowFacetEdge.setter
    def ShowFacetEdge(self, value: bool) -> None: ...
    @property
    def Type(self) -> GeometricAnalysis.ReflectionAnalysisBuilder.Types: ...
    @Type.setter
    def Type(self, value: GeometricAnalysis.ReflectionAnalysisBuilder.Types) -> None: ...


    class Types(enum.Enum):
        LineImages= 0
        SceneImages= 1
        ImageFromFile= 2
    

    class SceneImageType(enum.Enum):
        SimulatedHorizon= 0
        PhotoHorizon= 1
        SphericalRoom= 2
        SphericalLightTubesRoom= 3
        DaytimeHorizon= 4
        MagentaSunset= 5
        SphericalHorizon= 6
        CylindricalRoom= 7
        MonochromeHorizon= 8
        SmoothGrayScale= 9
        SharpGrayScale= 10
        SphericalTubes= 11
    

    class NumberOfLinesOptions(enum.Enum):
        One= 0
        Two= 1
        Four= 2
        Eight= 3
        Sixteen= 4
        ThirtyTwo= 5
        SixtyFour= 6
        OneTwoEight= 7
        TwoFiveSix= 8
    

    class LineThicknessType(enum.Enum):
        Thin= 0
        Normal= 1
        Thick= 2
    

    class LineOrientationType(enum.Enum):
        Horizontal= 0
        Vertical= 1
        Both= 2
    

    class LineImageTypes(enum.Enum):
        BlackLines= 0
        BlackandWhiteLines= 1
        ColoredLines= 2
    

    class ImageSizeOption(enum.Enum):
        KeepCurrent= 0
        ReduceScale= 1
    

    class ImageMovementTypes(enum.Enum):
        Horizontal= 0
        Vertical= 1
        Rotate= 2
    

class RadiusAnalysisBuilder(Builder):
    def __init__(self) -> None: ...
    def UpdateDisplayOnPlaneChange(self) -> None: ...
    def StartRadiusAnalysis(self) -> None: ...
    @property
    def DataRange(self) -> GeometricAnalysis.FaceAnalysisDataRangeBuilder: ...
    @DataRange.setter
    def DataRange(self, value: GeometricAnalysis.FaceAnalysisDataRangeBuilder) -> None: ...
    @property
    def DisplayMode(self) -> GeometricAnalysis.RadiusAnalysisBuilder.DisplayModes: ...
    @DisplayMode.setter
    def DisplayMode(self, value: GeometricAnalysis.RadiusAnalysisBuilder.DisplayModes) -> None: ...
    @property
    def DisplaySettings(self) -> GeometricAnalysis.FaceAnalysisDisplayBuilder: ...
    @DisplaySettings.setter
    def DisplaySettings(self, value: GeometricAnalysis.FaceAnalysisDisplayBuilder) -> None: ...
    @property
    def Faces(self) -> SelectDisplayableObjectList: ...
    @Faces.setter
    def Faces(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def Normals(self) -> GeometricAnalysis.FaceAnalysisNormalsBuilder: ...
    @Normals.setter
    def Normals(self, value: GeometricAnalysis.FaceAnalysisNormalsBuilder) -> None: ...
    @property
    def NumberOfContourLines(self) -> int: ...
    @NumberOfContourLines.setter
    def NumberOfContourLines(self, value: int) -> None: ...
    @property
    def Plane(self) -> Plane: ...
    @Plane.setter
    def Plane(self, value: Plane) -> None: ...
    @property
    def SpikeLength(self) -> float: ...
    @SpikeLength.setter
    def SpikeLength(self, value: float) -> None: ...
    @property
    def Type(self) -> GeometricAnalysis.RadiusAnalysisBuilder.Types: ...
    @Type.setter
    def Type(self, value: GeometricAnalysis.RadiusAnalysisBuilder.Types) -> None: ...
    @property
    def Vector(self) -> Direction: ...
    @Vector.setter
    def Vector(self, value: Direction) -> None: ...


    class Types(enum.Enum):
        Gaussian= 0
        Minimum= 1
        Maximum= 2
        Mean= 3
        Normal= 4
        Sectional= 5
        U= 6
        V= 7
    

    class DisplayModes(enum.Enum):
        Fringe= 0
        Hedgehog= 1
        ContourLines= 2
    

class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class LocalRadiusAnalysisBuilder(Builder):
    def __init__(self) -> None: ...
    def ButtonOpenInformationWindow(self) -> None: ...
    @property
    def SelectionPoint(self) -> Features.GeometricConstraintDataManager: ...
    @SelectionPoint.setter
    def SelectionPoint(self, value: Features.GeometricConstraintDataManager) -> None: ...
    @property
    def VisibilityCoordinates(self) -> bool: ...
    @VisibilityCoordinates.setter
    def VisibilityCoordinates(self, value: bool) -> None: ...
    @property
    def VisibilityMaxRadius(self) -> bool: ...
    @VisibilityMaxRadius.setter
    def VisibilityMaxRadius(self, value: bool) -> None: ...
    @property
    def VisibilityMinMaxRadiusTangent(self) -> bool: ...
    @VisibilityMinMaxRadiusTangent.setter
    def VisibilityMinMaxRadiusTangent(self, value: bool) -> None: ...
    @property
    def VisibilityMinRadius(self) -> bool: ...
    @VisibilityMinRadius.setter
    def VisibilityMinRadius(self, value: bool) -> None: ...
    @property
    def VisibilityRadius(self) -> bool: ...
    @VisibilityRadius.setter
    def VisibilityRadius(self, value: bool) -> None: ...
    @property
    def VisibilityURadius(self) -> bool: ...
    @VisibilityURadius.setter
    def VisibilityURadius(self, value: bool) -> None: ...
    @property
    def VisibilityUV(self) -> bool: ...
    @VisibilityUV.setter
    def VisibilityUV(self, value: bool) -> None: ...
    @property
    def VisibilityUVTangent(self) -> bool: ...
    @VisibilityUVTangent.setter
    def VisibilityUVTangent(self, value: bool) -> None: ...
    @property
    def VisibilityVRadius(self) -> bool: ...
    @VisibilityVRadius.setter
    def VisibilityVRadius(self, value: bool) -> None: ...


class LocalRadiusAnalysis(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class HighlightLinesAnalysisBuilder(Builder):
    def __init__(self) -> None: ...
    def GetDarkColor(self) -> float: ...
    def SetDarkColor(self, darkColor: float) -> None: ...
    def GetBrightColor(self) -> float: ...
    def SetBrightColor(self, brightColor: float) -> None: ...
    def ReinitializePlane(self) -> None: ...
    def SetLightPlaneOrigin(self, origin: Point3d) -> None: ...
    def SetLightPlaneXAxis(self, xAxis: Vector3d) -> None: ...
    def SetLightPlaneYAxis(self, yAxis: Vector3d) -> None: ...
    @property
    def BetweenPoints(self) -> SelectPointList: ...
    @BetweenPoints.setter
    def BetweenPoints(self, value: SelectPointList) -> None: ...
    @property
    def DisplayMethod(self) -> GeometricAnalysis.HighlightLinesAnalysisBuilder.DisplayMethods: ...
    @DisplayMethod.setter
    def DisplayMethod(self, value: GeometricAnalysis.HighlightLinesAnalysisBuilder.DisplayMethods) -> None: ...
    @property
    def EndIsoAngle(self) -> Expression: ...
    @EndIsoAngle.setter
    def EndIsoAngle(self, value: Expression) -> None: ...
    @property
    def Faces(self) -> SelectDisplayableObjectList: ...
    @Faces.setter
    def Faces(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def IsReflectionLocked(self) -> bool: ...
    @IsReflectionLocked.setter
    def IsReflectionLocked(self, value: bool) -> None: ...
    @property
    def IsoclineVector(self) -> Direction: ...
    @IsoclineVector.setter
    def IsoclineVector(self, value: Direction) -> None: ...
    @property
    def LightDiffuseness(self) -> float: ...
    @LightDiffuseness.setter
    def LightDiffuseness(self, value: float) -> None: ...
    @property
    def LightNumber(self) -> int: ...
    @LightNumber.setter
    def LightNumber(self, value: int) -> None: ...
    @property
    def LightPlacement(self) -> GeometricAnalysis.HighlightLinesAnalysisBuilder.LightPlacements: ...
    @LightPlacement.setter
    def LightPlacement(self, value: GeometricAnalysis.HighlightLinesAnalysisBuilder.LightPlacements) -> None: ...
    @property
    def LightPlaneOrigin(self) -> Point3d: ...
    @LightPlaneOrigin.setter
    def LightPlaneOrigin(self, value: Point3d) -> None: ...
    @property
    def LightPlaneXAxis(self) -> Vector3d: ...
    @LightPlaneXAxis.setter
    def LightPlaneXAxis(self, value: Vector3d) -> None: ...
    @property
    def LightPlaneYAxis(self) -> Vector3d: ...
    @LightPlaneYAxis.setter
    def LightPlaneYAxis(self, value: Vector3d) -> None: ...
    @property
    def LightSpacing(self) -> float: ...
    @LightSpacing.setter
    def LightSpacing(self, value: float) -> None: ...
    @property
    def LightWidth(self) -> float: ...
    @LightWidth.setter
    def LightWidth(self, value: float) -> None: ...
    @property
    def Resolution(self) -> GeometricAnalysis.HighlightLinesAnalysisBuilder.Resolutions: ...
    @Resolution.setter
    def Resolution(self, value: GeometricAnalysis.HighlightLinesAnalysisBuilder.Resolutions) -> None: ...
    @property
    def StartIsoAngle(self) -> Expression: ...
    @StartIsoAngle.setter
    def StartIsoAngle(self, value: Expression) -> None: ...
    @property
    def ThroughPoints(self) -> SelectPointList: ...
    @ThroughPoints.setter
    def ThroughPoints(self, value: SelectPointList) -> None: ...
    @property
    def Type(self) -> GeometricAnalysis.HighlightLinesAnalysisBuilder.Types: ...
    @Type.setter
    def Type(self, value: GeometricAnalysis.HighlightLinesAnalysisBuilder.Types) -> None: ...
    @property
    def Type2(self) -> GeometricAnalysis.HighlightLinesAnalysisBuilder.Types2: ...
    @Type2.setter
    def Type2(self, value: GeometricAnalysis.HighlightLinesAnalysisBuilder.Types2) -> None: ...


    class Types2(enum.Enum):
        Reflection= 0
        Projection= 1
        Isoclines= 2
        Zebra= 3
    

    class Types(enum.Enum):
        Uniform= 0
        ThroughPoints= 1
        BetweenPoints= 2
    

    class Resolutions(enum.Enum):
        Coarse= 0
        Standard= 1
        Fine= 2
        ExtraFine= 3
        SuperFine= 4
        UltraFine= 5
    

    class LightPlaneOptions(enum.Enum):
        YZ= 0
        ZX= 1
        XY= 2
        Arbitrary= 3
    

    class LightPlacements(enum.Enum):
        Uniform= 0
        ThroughPoints= 1
        BetweenPoints= 2
    

    class DisplayMethods(enum.Enum):
        Reflection= 0
        Projection= 1
    

class HighlightLinesAnalysis(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class GeometricProperties(Builder):
    def __init__(self) -> None: ...
    def GetFaceProperties(self, entityTag: NXObject, absPoint: Point3d, face: GeometricAnalysis.GeometricProperties.Face) -> GeometricAnalysis.GeometricProperties.Status: ...
    def GetEdgeProperties(self, entityTag: NXObject, absPoint: Point3d, edge: GeometricAnalysis.GeometricProperties.Edge) -> GeometricAnalysis.GeometricProperties.Status: ...
    def GetCaeFaceProperties(self, entityTag: NXObject, absPoint: Point3d, caeFace: GeometricAnalysis.GeometricProperties.CaeFace) -> GeometricAnalysis.GeometricProperties.Status: ...
    def GetCaeCurveProperties(self, entityTag: NXObject, absPoint: Point3d, caeCurve: GeometricAnalysis.GeometricProperties.CaeCurve) -> GeometricAnalysis.GeometricProperties.Status: ...
    @typing.overload
    def ListProperties(self, entityTag: NXObject, absPoint: Point3d) -> GeometricAnalysis.GeometricProperties.Status: ...
    @typing.overload
    def ListProperties(self, absPoint: Point3d) -> GeometricAnalysis.GeometricProperties.Status: ...
    def Reset(self) -> None: ...
    @property
    def ObjectsForAnalysis(self) -> SelectObjectList: ...
    @ObjectsForAnalysis.setter
    def ObjectsForAnalysis(self, value: SelectObjectList) -> None: ...
    @property
    def OutputMethod(self) -> GeometricAnalysis.GeometricProperties.OutputType: ...
    @OutputMethod.setter
    def OutputMethod(self, value: GeometricAnalysis.GeometricProperties.OutputType) -> None: ...


    class Status(enum.Enum):
        Success= 0
        InvalidInput= 1
        Failed= 2
    

    class OutputType(enum.Enum):
        Dynamic= 0
        Static= 1
    

    class GeometricPropertiesFace():
        @property
        def UParamater(self) -> float: ...
        @UParamater.setter
        def UParamater(self, value: float) -> None: ...
        @property
        def VParamater(self) -> float: ...
        @VParamater.setter
        def VParamater(self, value: float) -> None: ...
        @property
        def PositionInWcs(self) -> Point3d: ...
        @PositionInWcs.setter
        def PositionInWcs(self, value: Point3d) -> None: ...
        @property
        def UDerivativeInWcs(self) -> Vector3d: ...
        @UDerivativeInWcs.setter
        def UDerivativeInWcs(self, value: Vector3d) -> None: ...
        @property
        def VDerivativeInWcs(self) -> Vector3d: ...
        @VDerivativeInWcs.setter
        def VDerivativeInWcs(self, value: Vector3d) -> None: ...
        @property
        def NormalInWcs(self) -> Vector3d: ...
        @NormalInWcs.setter
        def NormalInWcs(self, value: Vector3d) -> None: ...
        @property
        def Position(self) -> Point3d: ...
        @Position.setter
        def Position(self, value: Point3d) -> None: ...
        @property
        def UDerivative(self) -> Vector3d: ...
        @UDerivative.setter
        def UDerivative(self, value: Vector3d) -> None: ...
        @property
        def VDerivative(self) -> Vector3d: ...
        @VDerivative.setter
        def VDerivative(self, value: Vector3d) -> None: ...
        @property
        def Normal(self) -> Vector3d: ...
        @Normal.setter
        def Normal(self, value: Vector3d) -> None: ...
        @property
        def InvOfMinRadiusOfCurvature(self) -> float: ...
        @InvOfMinRadiusOfCurvature.setter
        def InvOfMinRadiusOfCurvature(self, value: float) -> None: ...
        @property
        def InvOfMaxRadiusOfCurvature(self) -> float: ...
        @InvOfMaxRadiusOfCurvature.setter
        def InvOfMaxRadiusOfCurvature(self, value: float) -> None: ...
        def ToString(self) -> str: ...
    

    class Entity(enum.Enum):
        Face= 0
        Edge= 1
        CaeFace= 2
        CaeCurve= 3
    

    class GeometricPropertiesEdge():
        @property
        def ParameterPercentage(self) -> float: ...
        @ParameterPercentage.setter
        def ParameterPercentage(self, value: float) -> None: ...
        @property
        def Parameter(self) -> float: ...
        @Parameter.setter
        def Parameter(self, value: float) -> None: ...
        @property
        def PositionInWcs(self) -> Point3d: ...
        @PositionInWcs.setter
        def PositionInWcs(self, value: Point3d) -> None: ...
        @property
        def Position(self) -> Point3d: ...
        @Position.setter
        def Position(self, value: Point3d) -> None: ...
        @property
        def TangentInWcs(self) -> Vector3d: ...
        @TangentInWcs.setter
        def TangentInWcs(self, value: Vector3d) -> None: ...
        @property
        def Tangent(self) -> Vector3d: ...
        @Tangent.setter
        def Tangent(self, value: Vector3d) -> None: ...
        @property
        def NormalInWcs(self) -> Vector3d: ...
        @NormalInWcs.setter
        def NormalInWcs(self, value: Vector3d) -> None: ...
        @property
        def Normal(self) -> Vector3d: ...
        @Normal.setter
        def Normal(self, value: Vector3d) -> None: ...
        @property
        def BinormalInWcs(self) -> Vector3d: ...
        @BinormalInWcs.setter
        def BinormalInWcs(self, value: Vector3d) -> None: ...
        @property
        def Binormal(self) -> Vector3d: ...
        @Binormal.setter
        def Binormal(self, value: Vector3d) -> None: ...
        @property
        def Torsion(self) -> float: ...
        @Torsion.setter
        def Torsion(self, value: float) -> None: ...
        @property
        def Curvature(self) -> float: ...
        @Curvature.setter
        def Curvature(self, value: float) -> None: ...
        def ToString(self) -> str: ...
    

    class GeometricPropertiesCaeFace():
        @property
        def ClosestPoint(self) -> Vector3d: ...
        @ClosestPoint.setter
        def ClosestPoint(self, value: Vector3d) -> None: ...
        @property
        def UParameter(self) -> float: ...
        @UParameter.setter
        def UParameter(self, value: float) -> None: ...
        @property
        def VParameter(self) -> float: ...
        @VParameter.setter
        def VParameter(self, value: float) -> None: ...
        @property
        def Normal(self) -> Vector3d: ...
        @Normal.setter
        def Normal(self, value: Vector3d) -> None: ...
        @property
        def ClosestPointInWcs(self) -> Point3d: ...
        @ClosestPointInWcs.setter
        def ClosestPointInWcs(self, value: Point3d) -> None: ...
        @property
        def NormalInWcs(self) -> Vector3d: ...
        @NormalInWcs.setter
        def NormalInWcs(self, value: Vector3d) -> None: ...
        @property
        def UDerivative(self) -> Vector3d: ...
        @UDerivative.setter
        def UDerivative(self, value: Vector3d) -> None: ...
        @property
        def VDerivative(self) -> Vector3d: ...
        @VDerivative.setter
        def VDerivative(self, value: Vector3d) -> None: ...
        @property
        def UDerivativeInWcs(self) -> Vector3d: ...
        @UDerivativeInWcs.setter
        def UDerivativeInWcs(self, value: Vector3d) -> None: ...
        @property
        def VDerivativeInWcs(self) -> Vector3d: ...
        @VDerivativeInWcs.setter
        def VDerivativeInWcs(self, value: Vector3d) -> None: ...
        def ToString(self) -> str: ...
    

    class GeometricPropertiesCaeCurve():
        @property
        def ArcLengthParameter(self) -> float: ...
        @ArcLengthParameter.setter
        def ArcLengthParameter(self, value: float) -> None: ...
        @property
        def UnitArcLengthParameter(self) -> float: ...
        @UnitArcLengthParameter.setter
        def UnitArcLengthParameter(self, value: float) -> None: ...
        @property
        def ClosestPointInWcs(self) -> Point3d: ...
        @ClosestPointInWcs.setter
        def ClosestPointInWcs(self, value: Point3d) -> None: ...
        @property
        def NormalInWcs(self) -> Vector3d: ...
        @NormalInWcs.setter
        def NormalInWcs(self, value: Vector3d) -> None: ...
        @property
        def TangentInWcs(self) -> Vector3d: ...
        @TangentInWcs.setter
        def TangentInWcs(self, value: Vector3d) -> None: ...
        @property
        def Tangent(self) -> Vector3d: ...
        @Tangent.setter
        def Tangent(self, value: Vector3d) -> None: ...
        @property
        def Normal(self) -> Vector3d: ...
        @Normal.setter
        def Normal(self, value: Vector3d) -> None: ...
        @property
        def ClosestPoint(self) -> Point3d: ...
        @ClosestPoint.setter
        def ClosestPoint(self, value: Point3d) -> None: ...
        def ToString(self) -> str: ...
    

class GapFlushnessBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def BasePanelFaces(self) -> ScCollector: ...
    @BasePanelFaces.setter
    def BasePanelFaces(self, value: ScCollector) -> None: ...
    @property
    def BasePanelInnerContactCurves(self) -> Section: ...
    @BasePanelInnerContactCurves.setter
    def BasePanelInnerContactCurves(self, value: Section) -> None: ...
    @property
    def BasePanelOuterContactCurves(self) -> Section: ...
    @BasePanelOuterContactCurves.setter
    def BasePanelOuterContactCurves(self, value: Section) -> None: ...
    @property
    def BasePanelType(self) -> GeometricAnalysis.GapFlushnessBuilder.PanelTypes: ...
    @BasePanelType.setter
    def BasePanelType(self, value: GeometricAnalysis.GapFlushnessBuilder.PanelTypes) -> None: ...
    @property
    def CrossSectionCurveOption(self) -> GeometricAnalysis.GapFlushnessBuilder.SectionCurveOptions: ...
    @CrossSectionCurveOption.setter
    def CrossSectionCurveOption(self, value: GeometricAnalysis.GapFlushnessBuilder.SectionCurveOptions) -> None: ...
    @property
    def CrossSectionCurves(self) -> Section: ...
    @CrossSectionCurves.setter
    def CrossSectionCurves(self, value: Section) -> None: ...
    @property
    def EvaluationMode(self) -> GeometricAnalysis.GapFlushnessBuilder.EvaluationModes: ...
    @EvaluationMode.setter
    def EvaluationMode(self, value: GeometricAnalysis.GapFlushnessBuilder.EvaluationModes) -> None: ...
    @property
    def EvaluationPoint(self) -> Point: ...
    @EvaluationPoint.setter
    def EvaluationPoint(self, value: Point) -> None: ...
    @property
    def EvaluationType(self) -> GeometricAnalysis.GapFlushnessBuilder.EvaluationTypes: ...
    @EvaluationType.setter
    def EvaluationType(self, value: GeometricAnalysis.GapFlushnessBuilder.EvaluationTypes) -> None: ...
    @property
    def IsNegativeToleranceLabelDisplayed(self) -> bool: ...
    @IsNegativeToleranceLabelDisplayed.setter
    def IsNegativeToleranceLabelDisplayed(self, value: bool) -> None: ...
    @property
    def IsNominalLabelDisplayed(self) -> bool: ...
    @IsNominalLabelDisplayed.setter
    def IsNominalLabelDisplayed(self, value: bool) -> None: ...
    @property
    def IsPositiveToleranceLabelDisplayed(self) -> bool: ...
    @IsPositiveToleranceLabelDisplayed.setter
    def IsPositiveToleranceLabelDisplayed(self, value: bool) -> None: ...
    @property
    def LabelDisplayOption(self) -> GeometricAnalysis.GapFlushnessBuilder.DisplayOptions: ...
    @LabelDisplayOption.setter
    def LabelDisplayOption(self, value: GeometricAnalysis.GapFlushnessBuilder.DisplayOptions) -> None: ...
    @property
    def NegativeFlushnessTolerance(self) -> float: ...
    @NegativeFlushnessTolerance.setter
    def NegativeFlushnessTolerance(self, value: float) -> None: ...
    @property
    def NegativeGapTolerance(self) -> float: ...
    @NegativeGapTolerance.setter
    def NegativeGapTolerance(self, value: float) -> None: ...
    @property
    def NominalFlushness(self) -> float: ...
    @NominalFlushness.setter
    def NominalFlushness(self, value: float) -> None: ...
    @property
    def NominalGap(self) -> float: ...
    @NominalGap.setter
    def NominalGap(self, value: float) -> None: ...
    @property
    def PositiveFlushnessTolerance(self) -> float: ...
    @PositiveFlushnessTolerance.setter
    def PositiveFlushnessTolerance(self, value: float) -> None: ...
    @property
    def PositiveGapTolerance(self) -> float: ...
    @PositiveGapTolerance.setter
    def PositiveGapTolerance(self, value: float) -> None: ...
    @property
    def PreviewOption(self) -> bool: ...
    @PreviewOption.setter
    def PreviewOption(self, value: bool) -> None: ...
    @property
    def SampleDistance(self) -> Expression: ...
    @SampleDistance.setter
    def SampleDistance(self, value: Expression) -> None: ...
    @property
    def SampleNumber(self) -> int: ...
    @SampleNumber.setter
    def SampleNumber(self, value: int) -> None: ...
    @property
    def SecondPanelFaces(self) -> ScCollector: ...
    @SecondPanelFaces.setter
    def SecondPanelFaces(self, value: ScCollector) -> None: ...
    @property
    def SecondPanelInnerContactCurves(self) -> Section: ...
    @SecondPanelInnerContactCurves.setter
    def SecondPanelInnerContactCurves(self, value: Section) -> None: ...
    @property
    def SecondPanelOuterContactCurves(self) -> Section: ...
    @SecondPanelOuterContactCurves.setter
    def SecondPanelOuterContactCurves(self, value: Section) -> None: ...
    @property
    def SecondPanelType(self) -> GeometricAnalysis.GapFlushnessBuilder.PanelTypes: ...
    @SecondPanelType.setter
    def SecondPanelType(self, value: GeometricAnalysis.GapFlushnessBuilder.PanelTypes) -> None: ...
    @property
    def SectionAlignment(self) -> GeometricAnalysis.GapFlushnessBuilder.SectionAlignments: ...
    @SectionAlignment.setter
    def SectionAlignment(self, value: GeometricAnalysis.GapFlushnessBuilder.SectionAlignments) -> None: ...
    @property
    def SectionAlignmentDirection(self) -> Direction: ...
    @SectionAlignmentDirection.setter
    def SectionAlignmentDirection(self, value: Direction) -> None: ...
    @property
    def ShowOutRangeLabels(self) -> bool: ...
    @ShowOutRangeLabels.setter
    def ShowOutRangeLabels(self, value: bool) -> None: ...


    class SectionCurveOptions(enum.Enum):
        ContactCurve= 0
        UserDefined= 1
    

    class SectionAlignments(enum.Enum):
        Curve= 0
        CurveView= 1
        SpecifiedDirection= 2
    

    class PanelTypes(enum.Enum):
        Hem= 0
        Flange= 1
        Wall= 2
    

    class EvaluationTypes(enum.Enum):
        Absolute= 0
        Visual= 1
    

    class EvaluationModes(enum.Enum):
        Point= 0
        CurveNumber= 1
        Curve= 2
    

    class DisplayOptions(enum.Enum):
        GapOnly= 0
        FlushnessOnly= 1
        Both= 2
    

class GapFlushness(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class FaceCurvatureAnalysisBuilder(Builder):
    def __init__(self) -> None: ...
    def ReverseAllNormals(self) -> None: ...
    def ReverseIndividualNormal(self, face: DisplayableObject) -> None: ...
    def UpdateReverseMap(self) -> None: ...
    def DeselectFaces(self, faces: typing.List[DisplayableObject]) -> None: ...
    @property
    def ContourRefinement(self) -> int: ...
    @ContourRefinement.setter
    def ContourRefinement(self, value: int) -> None: ...
    @property
    def ContourShift(self) -> float: ...
    @ContourShift.setter
    def ContourShift(self, value: float) -> None: ...
    @property
    def CurvatureSectionPlane(self) -> Plane: ...
    @CurvatureSectionPlane.setter
    def CurvatureSectionPlane(self, value: Plane) -> None: ...
    @property
    def CurvatureType(self) -> GeometricAnalysis.FaceCurvatureAnalysisBuilder.CurvatureTypes: ...
    @CurvatureType.setter
    def CurvatureType(self, value: GeometricAnalysis.FaceCurvatureAnalysisBuilder.CurvatureTypes) -> None: ...
    @property
    def DisplayType(self) -> GeometricAnalysis.FaceCurvatureAnalysisBuilder.DisplayTypes: ...
    @DisplayType.setter
    def DisplayType(self, value: GeometricAnalysis.FaceCurvatureAnalysisBuilder.DisplayTypes) -> None: ...
    @property
    def MapCenter(self) -> float: ...
    @MapCenter.setter
    def MapCenter(self, value: float) -> None: ...
    @property
    def MapRange(self) -> float: ...
    @MapRange.setter
    def MapRange(self, value: float) -> None: ...
    @property
    def NormalOption(self) -> GeometricAnalysis.FaceCurvatureAnalysisBuilder.DirectionTypes: ...
    @NormalOption.setter
    def NormalOption(self, value: GeometricAnalysis.FaceCurvatureAnalysisBuilder.DirectionTypes) -> None: ...
    @property
    def NormalOrientation(self) -> Matrix3x3: ...
    @NormalOrientation.setter
    def NormalOrientation(self, value: Matrix3x3) -> None: ...
    @property
    def NormalOrigin(self) -> Point3d: ...
    @NormalOrigin.setter
    def NormalOrigin(self, value: Point3d) -> None: ...
    @property
    def NormalVector(self) -> Direction: ...
    @NormalVector.setter
    def NormalVector(self, value: Direction) -> None: ...
    @property
    def NumberOfContours(self) -> int: ...
    @NumberOfContours.setter
    def NumberOfContours(self, value: int) -> None: ...
    @property
    def Resolution(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @Resolution.setter
    def Resolution(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def ReverseIndividual(self) -> SelectDisplayableObject: ...
    @ReverseIndividual.setter
    def ReverseIndividual(self, value: SelectDisplayableObject) -> None: ...
    @property
    def ScaleType(self) -> GeometricAnalysis.FaceCurvatureAnalysisBuilder.ScaleTypes: ...
    @ScaleType.setter
    def ScaleType(self, value: GeometricAnalysis.FaceCurvatureAnalysisBuilder.ScaleTypes) -> None: ...
    @property
    def SectionOption(self) -> GeometricAnalysis.FaceCurvatureAnalysisBuilder.DirectionTypes: ...
    @SectionOption.setter
    def SectionOption(self, value: GeometricAnalysis.FaceCurvatureAnalysisBuilder.DirectionTypes) -> None: ...
    @property
    def SectionOrientation(self) -> Matrix3x3: ...
    @SectionOrientation.setter
    def SectionOrientation(self, value: Matrix3x3) -> None: ...
    @property
    def SectionOrigin(self) -> Point3d: ...
    @SectionOrigin.setter
    def SectionOrigin(self, value: Point3d) -> None: ...
    @property
    def SelectObject(self) -> SelectDisplayableObjectList: ...
    @SelectObject.setter
    def SelectObject(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def ShowZeroContour(self) -> bool: ...
    @ShowZeroContour.setter
    def ShowZeroContour(self, value: bool) -> None: ...


    class ScaleTypes(enum.Enum):
        Linear= 0
        Log= 1
        Area= 2
    

    class DisplayTypes(enum.Enum):
        Colormap= 0
        Contours= 1
        ColormapAndContours= 2
    

    class DirectionTypes(enum.Enum):
        Primitive= 0
        Manipulator= 1
    

    class CurvatureTypes(enum.Enum):
        Gaussian= 0
        Absolute= 1
        Minimum= 2
        Maximum= 3
        Mean= 4
        Normal= 5
        Sectional= 6
        U= 7
        V= 8
        Radius= 9
    

class FaceCurvatureAnalysis(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class FaceAnalysisNormalsBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def RestoreAll(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def FaceToReverseNormal(self) -> SelectNXObject: ...
    @FaceToReverseNormal.setter
    def FaceToReverseNormal(self, value: SelectNXObject) -> None: ...
    @property
    def Point(self) -> Point: ...
    @Point.setter
    def Point(self, value: Point) -> None: ...


class FaceAnalysisDisplayBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def CanShowFacet(self) -> bool: ...
    @CanShowFacet.setter
    def CanShowFacet(self, value: bool) -> None: ...
    @property
    def ColorLegendOption(self) -> GeometricAnalysis.FaceAnalysisDisplayBuilder.ColorLegendOptions: ...
    @ColorLegendOption.setter
    def ColorLegendOption(self, value: GeometricAnalysis.FaceAnalysisDisplayBuilder.ColorLegendOptions) -> None: ...
    @property
    def DisplayResolution(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @DisplayResolution.setter
    def DisplayResolution(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def NumberOfColors(self) -> GeometricAnalysis.FaceAnalysisDisplayBuilder.ColorsOptions: ...
    @NumberOfColors.setter
    def NumberOfColors(self, value: GeometricAnalysis.FaceAnalysisDisplayBuilder.ColorsOptions) -> None: ...


    class ColorsOptions(enum.Enum):
        Two= 0
        Three= 1
        Four= 2
        Five= 3
        Six= 4
        Seven= 5
        Eight= 6
        Nine= 7
        Ten= 8
        Eleven= 9
        Twelve= 10
    

    class ColorLegendOptions(enum.Enum):
        Blend= 0
        Sharp= 1
    

class FaceAnalysisDataRangeBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def ResetData(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def IsFixed(self) -> bool: ...
    @IsFixed.setter
    def IsFixed(self, value: bool) -> None: ...
    @property
    def Max(self) -> float: ...
    @Max.setter
    def Max(self, value: float) -> None: ...
    @property
    def Middle(self) -> float: ...
    @Middle.setter
    def Middle(self, value: float) -> None: ...
    @property
    def MiddleScale(self) -> float: ...
    @MiddleScale.setter
    def MiddleScale(self, value: float) -> None: ...
    @property
    def Min(self) -> float: ...
    @Min.setter
    def Min(self, value: float) -> None: ...
    @property
    def ZoomScale(self) -> float: ...
    @ZoomScale.setter
    def ZoomScale(self, value: float) -> None: ...


class FaceAnalysis(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class ExamineGeometry(Builder):
    def __init__(self) -> None: ...
    def SetAllChecks(self) -> None: ...
    def ClearAllChecks(self) -> None: ...
    def SetCheck(self, check: GeometricAnalysis.ExamineGeometry.Check) -> None: ...
    def ClearCheck(self, check: GeometricAnalysis.ExamineGeometry.Check) -> None: ...
    def Examine(self) -> None: ...
    def GetResults(self) -> int: ...
    def GetFailedObjects(self, check: GeometricAnalysis.ExamineGeometry.Check) -> typing.List[NXObject]: ...
    def HighlightResult(self, check: GeometricAnalysis.ExamineGeometry.Check) -> bool: ...
    def UnhighlightResult(self, check: GeometricAnalysis.ExamineGeometry.Check) -> None: ...
    def UnhighlightAllResults(self) -> None: ...
    def DisplayResultsAsInfo(self) -> None: ...
    @property
    def CheckCriteriaAngle(self) -> float: ...
    @CheckCriteriaAngle.setter
    def CheckCriteriaAngle(self, value: float) -> None: ...
    @property
    def CheckCriteriaDistance(self) -> float: ...
    @CheckCriteriaDistance.setter
    def CheckCriteriaDistance(self, value: float) -> None: ...
    @property
    def ObjectsToExamine(self) -> SelectObjectList: ...
    @ObjectsToExamine.setter
    def ObjectsToExamine(self, value: SelectObjectList) -> None: ...


    class Check(enum.Enum):
        ObjectTiny= 0
        ObjectMisaligned= 1
        BodyDataStructures= 2
        BodyConsistency= 3
        BodyFaceIntersections= 4
        BodySheetBoundaries= 5
        FaceSmoothness= 6
        FaceSelfIntersection= 7
        FaceSpikesCuts= 8
        EdgeSmoothness= 9
        EdgeTolerances= 10
        NumChecks= 11
    

class DupinBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def ResetAnalysisPoint(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def AnalysisPoint(self) -> Point: ...
    @AnalysisPoint.setter
    def AnalysisPoint(self, value: Point) -> None: ...
    @property
    def Angle(self) -> float: ...
    @Angle.setter
    def Angle(self, value: float) -> None: ...
    @property
    def FlatnessTolerance(self) -> float: ...
    @FlatnessTolerance.setter
    def FlatnessTolerance(self, value: float) -> None: ...
    @property
    def Scale(self) -> float: ...
    @Scale.setter
    def Scale(self, value: float) -> None: ...


class DraftAnalysisBuilder(Builder):
    def __init__(self) -> None: ...
    def ReverseAllNormals(self) -> None: ...
    def GetColorOutsidePositive(self) -> float: ...
    def SetColorOutsidePositive(self, colorOutsidePos: float) -> None: ...
    def GetColorInsidePositive(self) -> float: ...
    def SetColorInsidePositive(self, colorInsidePos: float) -> None: ...
    def GetColorOutsideNegative(self) -> float: ...
    def SetColorOutsideNegative(self, colorOutsideNeg: float) -> None: ...
    def GetColorInsideNegative(self) -> float: ...
    def SetColorInsideNegative(self, colorInsideNeg: float) -> None: ...
    def AddDynamicPoints(self) -> None: ...
    def SetTotalDynamicNormals(self, total: int) -> None: ...
    def SetDynamicNormal(self, index: int, normal: Vector3d) -> None: ...
    def SetDynamicParent(self, index: int, parent: DisplayableObject) -> None: ...
    def ReverseNormal(self, face: DisplayableObject) -> None: ...
    def DeselectFaces(self, faces: typing.List[DisplayableObject]) -> None: ...
    def UpdateReverseMap(self) -> None: ...
    def RemoveLabelParents(self, parents: typing.List[DisplayableObject]) -> None: ...
    def DeleteDynamicLabels(self, deletedLabels: bool) -> None: ...
    @property
    def CoupleLimit(self) -> bool: ...
    @CoupleLimit.setter
    def CoupleLimit(self, value: bool) -> None: ...
    @property
    def CreateCSYS(self) -> bool: ...
    @CreateCSYS.setter
    def CreateCSYS(self, value: bool) -> None: ...
    @property
    def DrawOption(self) -> GeometricAnalysis.DraftAnalysisBuilder.DrawDirection: ...
    @DrawOption.setter
    def DrawOption(self, value: GeometricAnalysis.DraftAnalysisBuilder.DrawDirection) -> None: ...
    @property
    def DrawOrientation(self) -> Matrix3x3: ...
    @DrawOrientation.setter
    def DrawOrientation(self, value: Matrix3x3) -> None: ...
    @property
    def DrawOrigin(self) -> Point3d: ...
    @DrawOrigin.setter
    def DrawOrigin(self, value: Point3d) -> None: ...
    @property
    def DrawVector(self) -> Direction: ...
    @DrawVector.setter
    def DrawVector(self, value: Direction) -> None: ...
    @property
    def DynamicLabel(self) -> Features.GeometricConstraintDataManager: ...
    @DynamicLabel.setter
    def DynamicLabel(self, value: Features.GeometricConstraintDataManager) -> None: ...
    @property
    def JoinIsocline(self) -> bool: ...
    @JoinIsocline.setter
    def JoinIsocline(self, value: bool) -> None: ...
    @property
    def LimitAngleNegative(self) -> float: ...
    @LimitAngleNegative.setter
    def LimitAngleNegative(self, value: float) -> None: ...
    @property
    def LimitAnglePositive(self) -> float: ...
    @LimitAnglePositive.setter
    def LimitAnglePositive(self, value: float) -> None: ...
    @property
    def OutputOption(self) -> GeometricAnalysis.DraftAnalysisBuilder.SelectOutput: ...
    @OutputOption.setter
    def OutputOption(self, value: GeometricAnalysis.DraftAnalysisBuilder.SelectOutput) -> None: ...
    @property
    def Resolution(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @Resolution.setter
    def Resolution(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def ReverseIndividual(self) -> SelectDisplayableObject: ...
    @ReverseIndividual.setter
    def ReverseIndividual(self, value: SelectDisplayableObject) -> None: ...
    @property
    def SelectObject(self) -> SelectDisplayableObjectList: ...
    @SelectObject.setter
    def SelectObject(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def ShowIsoclineNegative(self) -> bool: ...
    @ShowIsoclineNegative.setter
    def ShowIsoclineNegative(self, value: bool) -> None: ...
    @property
    def ShowIsoclinePositive(self) -> bool: ...
    @ShowIsoclinePositive.setter
    def ShowIsoclinePositive(self, value: bool) -> None: ...
    @property
    def ShowPartingLine(self) -> bool: ...
    @ShowPartingLine.setter
    def ShowPartingLine(self, value: bool) -> None: ...
    @property
    def SwitchDisplayMode(self) -> bool: ...
    @SwitchDisplayMode.setter
    def SwitchDisplayMode(self, value: bool) -> None: ...
    @property
    def TranslucencyInsideNegative(self) -> int: ...
    @TranslucencyInsideNegative.setter
    def TranslucencyInsideNegative(self, value: int) -> None: ...
    @property
    def TranslucencyInsidePositive(self) -> int: ...
    @TranslucencyInsidePositive.setter
    def TranslucencyInsidePositive(self, value: int) -> None: ...
    @property
    def TranslucencyOutsideNegative(self) -> int: ...
    @TranslucencyOutsideNegative.setter
    def TranslucencyOutsideNegative(self, value: int) -> None: ...
    @property
    def TranslucencyOutsidePositive(self) -> int: ...
    @TranslucencyOutsidePositive.setter
    def TranslucencyOutsidePositive(self, value: int) -> None: ...


    class SelectOutput(enum.Enum):
        AnalysisObject= 0
        Isoclines= 1
        Both= 2
    

    class DrawDirection(enum.Enum):
        Vector= 0
        Orientation= 1
    

class DraftAnalysis(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class DistanceAnalysisBuilder(Builder):
    def __init__(self) -> None: ...
    def UpdateDisplayOnPlaneChange(self) -> None: ...
    def StartDistanceAnalysis(self) -> None: ...
    @property
    def DataRange(self) -> GeometricAnalysis.FaceAnalysisDataRangeBuilder: ...
    @DataRange.setter
    def DataRange(self, value: GeometricAnalysis.FaceAnalysisDataRangeBuilder) -> None: ...
    @property
    def DisplayMode(self) -> GeometricAnalysis.DistanceAnalysisBuilder.DisplayModes: ...
    @DisplayMode.setter
    def DisplayMode(self, value: GeometricAnalysis.DistanceAnalysisBuilder.DisplayModes) -> None: ...
    @property
    def DisplaySettings(self) -> GeometricAnalysis.FaceAnalysisDisplayBuilder: ...
    @DisplaySettings.setter
    def DisplaySettings(self, value: GeometricAnalysis.FaceAnalysisDisplayBuilder) -> None: ...
    @property
    def Faces(self) -> SelectDisplayableObjectList: ...
    @Faces.setter
    def Faces(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def Normals(self) -> GeometricAnalysis.FaceAnalysisNormalsBuilder: ...
    @Normals.setter
    def Normals(self, value: GeometricAnalysis.FaceAnalysisNormalsBuilder) -> None: ...
    @property
    def NumberOfContourLines(self) -> int: ...
    @NumberOfContourLines.setter
    def NumberOfContourLines(self, value: int) -> None: ...
    @property
    def Plane(self) -> Plane: ...
    @Plane.setter
    def Plane(self, value: Plane) -> None: ...
    @property
    def SpikeLength(self) -> float: ...
    @SpikeLength.setter
    def SpikeLength(self, value: float) -> None: ...


    class DisplayModes(enum.Enum):
        Fringe= 0
        Hedgehog= 1
        ContourLines= 2
    

class DeviationGaugeBuilder(Builder):
    def __init__(self) -> None: ...
    def AddDynamicPoints(self) -> None: ...
    def AddPMILabel(self, snappedObject: NXObject) -> None: ...
    @property
    def ColorPlotType(self) -> GeometricAnalysis.DeviationGaugeBuilder.ColorPlotTypes: ...
    @ColorPlotType.setter
    def ColorPlotType(self, value: GeometricAnalysis.DeviationGaugeBuilder.ColorPlotTypes) -> None: ...
    @property
    def ConstraintManager(self) -> Features.GeometricConstraintDataManager: ...
    @ConstraintManager.setter
    def ConstraintManager(self, value: Features.GeometricConstraintDataManager) -> None: ...
    @property
    def CurveRangeControl(self) -> GeometricUtilities.CurveRangeBuilder: ...
    @CurveRangeControl.setter
    def CurveRangeControl(self, value: GeometricUtilities.CurveRangeBuilder) -> None: ...
    @property
    def DeviationIntervals(self) -> int: ...
    @DeviationIntervals.setter
    def DeviationIntervals(self, value: int) -> None: ...
    @property
    def HasAbsoluteColorPlot(self) -> bool: ...
    @HasAbsoluteColorPlot.setter
    def HasAbsoluteColorPlot(self, value: bool) -> None: ...
    @property
    def HasAdditionalValuesLabel(self) -> GeometricAnalysis.DeviationGaugeBuilder.AdditionalValuesLabelType: ...
    @HasAdditionalValuesLabel.setter
    def HasAdditionalValuesLabel(self, value: GeometricAnalysis.DeviationGaugeBuilder.AdditionalValuesLabelType) -> None: ...
    @property
    def HasCrossCurveDeviationLabel(self) -> bool: ...
    @HasCrossCurveDeviationLabel.setter
    def HasCrossCurveDeviationLabel(self, value: bool) -> None: ...
    @property
    def HasInfoLabel(self) -> bool: ...
    @HasInfoLabel.setter
    def HasInfoLabel(self, value: bool) -> None: ...
    @property
    def HasInnerToleranceLabel(self) -> bool: ...
    @HasInnerToleranceLabel.setter
    def HasInnerToleranceLabel(self, value: bool) -> None: ...
    @property
    def HasMaximumValueLabel(self) -> bool: ...
    @HasMaximumValueLabel.setter
    def HasMaximumValueLabel(self, value: bool) -> None: ...
    @property
    def HasMinimumValueLabel(self) -> bool: ...
    @HasMinimumValueLabel.setter
    def HasMinimumValueLabel(self, value: bool) -> None: ...
    @property
    def InnerTolerance(self) -> float: ...
    @InnerTolerance.setter
    def InnerTolerance(self, value: float) -> None: ...
    @property
    def IsColorMapDisplayed(self) -> bool: ...
    @IsColorMapDisplayed.setter
    def IsColorMapDisplayed(self, value: bool) -> None: ...
    @property
    def IsDirectionReversed(self) -> bool: ...
    @IsDirectionReversed.setter
    def IsDirectionReversed(self, value: bool) -> None: ...
    @property
    def IsLabelDisplayed(self) -> bool: ...
    @IsLabelDisplayed.setter
    def IsLabelDisplayed(self, value: bool) -> None: ...
    @property
    def IsMarkerDisplayed(self) -> bool: ...
    @IsMarkerDisplayed.setter
    def IsMarkerDisplayed(self, value: bool) -> None: ...
    @property
    def IsNeedlePlotDisplayed(self) -> bool: ...
    @IsNeedlePlotDisplayed.setter
    def IsNeedlePlotDisplayed(self, value: bool) -> None: ...
    @property
    def MaxCheckingAngle(self) -> float: ...
    @MaxCheckingAngle.setter
    def MaxCheckingAngle(self, value: float) -> None: ...
    @property
    def MaxCheckingDistance(self) -> float: ...
    @MaxCheckingDistance.setter
    def MaxCheckingDistance(self, value: float) -> None: ...
    @property
    def MeasurementMethod(self) -> GeometricAnalysis.DeviationGaugeBuilder.MeasurementMethodType: ...
    @MeasurementMethod.setter
    def MeasurementMethod(self, value: GeometricAnalysis.DeviationGaugeBuilder.MeasurementMethodType) -> None: ...
    @property
    def MeasurementSamples(self) -> int: ...
    @MeasurementSamples.setter
    def MeasurementSamples(self, value: int) -> None: ...
    @property
    def MinMaxOption(self) -> GeometricAnalysis.DeviationGaugeBuilder.MinMaxType: ...
    @MinMaxOption.setter
    def MinMaxOption(self, value: GeometricAnalysis.DeviationGaugeBuilder.MinMaxType) -> None: ...
    @property
    def NeedleScale(self) -> float: ...
    @NeedleScale.setter
    def NeedleScale(self, value: float) -> None: ...
    @property
    def NegativeInnerTolerance(self) -> float: ...
    @NegativeInnerTolerance.setter
    def NegativeInnerTolerance(self, value: float) -> None: ...
    @property
    def NegativeOuterTolerance(self) -> float: ...
    @NegativeOuterTolerance.setter
    def NegativeOuterTolerance(self, value: float) -> None: ...
    @property
    def OuterTolerance(self) -> float: ...
    @OuterTolerance.setter
    def OuterTolerance(self, value: float) -> None: ...
    @property
    def Plane(self) -> Plane: ...
    @Plane.setter
    def Plane(self, value: Plane) -> None: ...
    @property
    def PositiveInnerTolerance(self) -> float: ...
    @PositiveInnerTolerance.setter
    def PositiveInnerTolerance(self, value: float) -> None: ...
    @property
    def PositiveOuterTolerance(self) -> float: ...
    @PositiveOuterTolerance.setter
    def PositiveOuterTolerance(self, value: float) -> None: ...
    @property
    def ReferenceObjects(self) -> SelectNXObjectList: ...
    @ReferenceObjects.setter
    def ReferenceObjects(self, value: SelectNXObjectList) -> None: ...
    @property
    def ReportingPerType(self) -> GeometricAnalysis.DeviationGaugeBuilder.ReportingPerTypes: ...
    @ReportingPerType.setter
    def ReportingPerType(self, value: GeometricAnalysis.DeviationGaugeBuilder.ReportingPerTypes) -> None: ...
    @property
    def SpatialResolution(self) -> float: ...
    @SpatialResolution.setter
    def SpatialResolution(self, value: float) -> None: ...
    @property
    def SuggestScaleFactor(self) -> bool: ...
    @SuggestScaleFactor.setter
    def SuggestScaleFactor(self, value: bool) -> None: ...
    @property
    def SurfaceRangeControl(self) -> GeometricUtilities.SurfaceRangeBuilder: ...
    @SurfaceRangeControl.setter
    def SurfaceRangeControl(self, value: GeometricUtilities.SurfaceRangeBuilder) -> None: ...
    @property
    def TargetObjects(self) -> SelectNXObjectList: ...
    @TargetObjects.setter
    def TargetObjects(self, value: SelectNXObjectList) -> None: ...
    @property
    def UseDefiningPoints(self) -> bool: ...
    @UseDefiningPoints.setter
    def UseDefiningPoints(self, value: bool) -> None: ...
    @property
    def VectorComponentDirection(self) -> Direction: ...
    @VectorComponentDirection.setter
    def VectorComponentDirection(self, value: Direction) -> None: ...
    @property
    def XyzDirection(self) -> GeometricAnalysis.DeviationGaugeBuilder.XyzDirectionType: ...
    @XyzDirection.setter
    def XyzDirection(self, value: GeometricAnalysis.DeviationGaugeBuilder.XyzDirectionType) -> None: ...


    class XyzDirectionType(enum.Enum):
        X= 0
        Y= 1
        Z= 2
    

    class ReportingPerTypes(enum.Enum):
        AnalysisObject= 0
        Target= 1
        Reference= 2
    

    class MinMaxType(enum.Enum):
        Minmax= 0
        Minimum= 1
        Maximum= 2
        None_= 3
    

    class MeasurementMethodType(enum.Enum):
        ThreeDim= 0
        XyzDirection= 1
        WorkView= 2
        VectorComponent= 3
        Plane= 4
        AlongVector= 5
    

    class ColorPlotTypes(enum.Enum):
        Blend= 0
        Stepped= 1
        None_= 2
    

    class AdditionalValuesLabelType(enum.Enum):
        UserDefined= 0
        Intermediate= 1
        All= 2
        None_= 3
    

class DeviationGauge(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class DeviationChecking(Builder):
    def __init__(self) -> None: ...
    def Check(self) -> None: ...
    @property
    def AngleTolerance(self) -> float: ...
    @AngleTolerance.setter
    def AngleTolerance(self, value: float) -> None: ...
    @property
    def Curve(self) -> SelectIBaseCurve: ...
    @Curve.setter
    def Curve(self, value: SelectIBaseCurve) -> None: ...
    @property
    def DeviationOption(self) -> GeometricAnalysis.DeviationChecking.DeviationOptions: ...
    @DeviationOption.setter
    def DeviationOption(self, value: GeometricAnalysis.DeviationChecking.DeviationOptions) -> None: ...
    @property
    def DistanceTolerance(self) -> float: ...
    @DistanceTolerance.setter
    def DistanceTolerance(self, value: float) -> None: ...
    @property
    def FaceOfFirstEdge(self) -> SelectIParameterizedSurface: ...
    @FaceOfFirstEdge.setter
    def FaceOfFirstEdge(self, value: SelectIParameterizedSurface) -> None: ...
    @property
    def FaceOfSecondEdge(self) -> SelectIParameterizedSurface: ...
    @FaceOfSecondEdge.setter
    def FaceOfSecondEdge(self, value: SelectIParameterizedSurface) -> None: ...
    @property
    def FirstCurve(self) -> SelectIBaseCurve: ...
    @FirstCurve.setter
    def FirstCurve(self, value: SelectIBaseCurve) -> None: ...
    @property
    def FirstEdge(self) -> SelectIBaseCurve: ...
    @FirstEdge.setter
    def FirstEdge(self, value: SelectIBaseCurve) -> None: ...
    @property
    def FirstFace(self) -> SelectIParameterizedSurface: ...
    @FirstFace.setter
    def FirstFace(self, value: SelectIParameterizedSurface) -> None: ...
    @property
    def NumberCheckPoints(self) -> int: ...
    @NumberCheckPoints.setter
    def NumberCheckPoints(self, value: int) -> None: ...
    @property
    def NumberUcheckPoints(self) -> int: ...
    @NumberUcheckPoints.setter
    def NumberUcheckPoints(self, value: int) -> None: ...
    @property
    def NumberVcheckPoints(self) -> int: ...
    @NumberVcheckPoints.setter
    def NumberVcheckPoints(self, value: int) -> None: ...
    @property
    def SecondCurve(self) -> SelectIBaseCurve: ...
    @SecondCurve.setter
    def SecondCurve(self, value: SelectIBaseCurve) -> None: ...
    @property
    def SecondEdge(self) -> SelectIBaseCurve: ...
    @SecondEdge.setter
    def SecondEdge(self, value: SelectIBaseCurve) -> None: ...
    @property
    def SecondFace(self) -> SelectIParameterizedSurface: ...
    @SecondFace.setter
    def SecondFace(self, value: SelectIParameterizedSurface) -> None: ...
    @property
    def Type(self) -> GeometricAnalysis.DeviationChecking.Types: ...
    @Type.setter
    def Type(self, value: GeometricAnalysis.DeviationChecking.Types) -> None: ...


    class Types(enum.Enum):
        CurveToCurve= 0
        CurveToFace= 1
        EdgeToFace= 2
        FaceToFace= 3
        EdgeToEdge= 4
    

    class DeviationOptions(enum.Enum):
        NoDeviations= 0
        AllDeviations= 1
        MaximumDistance= 2
        MinimumDistance= 3
        MaximumAngle= 4
        MinimumAngle= 5
    

class CurveCurvatureAnalysisBuilder(Builder):
    def __init__(self) -> None: ...
    def UpdateWorkView(self) -> None: ...
    def CreateDumbPeakPoints(self) -> typing.List[Point]: ...
    def CreateDumbInflectionPoints(self) -> typing.List[Point]: ...
    def GetCurveRange(self, index: int) -> GeometricUtilities.CurveRangeBuilder: ...
    def GetCurveRangeListLength(self) -> int: ...
    @property
    def CombOptions(self) -> GeometricUtilities.CombOptionsBuilder: ...
    @CombOptions.setter
    def CombOptions(self, value: GeometricUtilities.CombOptionsBuilder) -> None: ...
    @property
    def CombRange(self) -> GeometricUtilities.CurveRangeBuilder: ...
    @CombRange.setter
    def CombRange(self, value: GeometricUtilities.CurveRangeBuilder) -> None: ...
    @property
    def DynamicProjection(self) -> bool: ...
    @DynamicProjection.setter
    def DynamicProjection(self, value: bool) -> None: ...
    @property
    def Method(self) -> GeometricAnalysis.CurveCurvatureAnalysisBuilder.CalculationMethod: ...
    @Method.setter
    def Method(self, value: GeometricAnalysis.CurveCurvatureAnalysisBuilder.CalculationMethod) -> None: ...
    @property
    def Projection(self) -> GeometricAnalysis.CurveCurvatureAnalysisBuilder.ProjectionTypes: ...
    @Projection.setter
    def Projection(self, value: GeometricAnalysis.CurveCurvatureAnalysisBuilder.ProjectionTypes) -> None: ...
    @property
    def ReverseDirection(self) -> int: ...
    @ReverseDirection.setter
    def ReverseDirection(self, value: int) -> None: ...
    @property
    def SelectedCurves(self) -> ScCollector: ...
    @SelectedCurves.setter
    def SelectedCurves(self, value: ScCollector) -> None: ...
    @property
    def ShowCombs(self) -> bool: ...
    @ShowCombs.setter
    def ShowCombs(self, value: bool) -> None: ...
    @property
    def ShowInflections(self) -> bool: ...
    @ShowInflections.setter
    def ShowInflections(self, value: bool) -> None: ...
    @property
    def ShowMaxLabels(self) -> bool: ...
    @ShowMaxLabels.setter
    def ShowMaxLabels(self, value: bool) -> None: ...
    @property
    def ShowMinLabels(self) -> bool: ...
    @ShowMinLabels.setter
    def ShowMinLabels(self, value: bool) -> None: ...
    @property
    def ShowPeaks(self) -> bool: ...
    @ShowPeaks.setter
    def ShowPeaks(self, value: bool) -> None: ...
    @property
    def Style(self) -> GeometricAnalysis.CurveCurvatureAnalysisBuilder.DisplayStyle: ...
    @Style.setter
    def Style(self, value: GeometricAnalysis.CurveCurvatureAnalysisBuilder.DisplayStyle) -> None: ...
    @property
    def Vector(self) -> Direction: ...
    @Vector.setter
    def Vector(self, value: Direction) -> None: ...
    @property
    def Xyz(self) -> GeometricAnalysis.CurveCurvatureAnalysisBuilder.XyzTypes: ...
    @Xyz.setter
    def Xyz(self, value: GeometricAnalysis.CurveCurvatureAnalysisBuilder.XyzTypes) -> None: ...


    class XyzTypes(enum.Enum):
        X= 0
        Y= 1
        Z= 2
    

    class ProjectionTypes(enum.Enum):
        None_= 0
        CurvePlane= 1
        Vector= 2
        View= 3
        Xyz= 4
    

    class NeedleDirection(enum.Enum):
        Inside= 0
        Outside= 1
    

    class LabelValues(enum.Enum):
        Curvature= 0
        RadiusofCurvature= 1
    

    class DisplayStyle(enum.Enum):
        Linear= 0
        Logarithmic= 1
    

    class CalculationMethod(enum.Enum):
        Curvature= 0
        RadiusofCurvature= 1
    

class CurveCurvatureAnalysis(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class CurveContinuityBuilder(Builder):
    def __init__(self) -> None: ...
    def ResetShowDeviation(self) -> None: ...
    @property
    def AngularThreshold(self) -> Expression: ...
    @AngularThreshold.setter
    def AngularThreshold(self, value: Expression) -> None: ...
    @property
    def ContinuityType(self) -> GeometricAnalysis.CurveContinuityBuilder.Type: ...
    @ContinuityType.setter
    def ContinuityType(self, value: GeometricAnalysis.CurveContinuityBuilder.Type) -> None: ...
    @property
    def DistanceThreshold(self) -> Expression: ...
    @DistanceThreshold.setter
    def DistanceThreshold(self, value: Expression) -> None: ...
    @property
    def DynamicLabel(self) -> SelectNXObject: ...
    @DynamicLabel.setter
    def DynamicLabel(self, value: SelectNXObject) -> None: ...
    @property
    def EndPointX(self) -> float: ...
    @EndPointX.setter
    def EndPointX(self, value: float) -> None: ...
    @property
    def EndPointY(self) -> float: ...
    @EndPointY.setter
    def EndPointY(self, value: float) -> None: ...
    @property
    def EndPointZ(self) -> float: ...
    @EndPointZ.setter
    def EndPointZ(self, value: float) -> None: ...
    @property
    def G0Check(self) -> bool: ...
    @G0Check.setter
    def G0Check(self, value: bool) -> None: ...
    @property
    def G0Check2(self) -> bool: ...
    @G0Check2.setter
    def G0Check2(self, value: bool) -> None: ...
    @property
    def G0Tolerance(self) -> float: ...
    @G0Tolerance.setter
    def G0Tolerance(self, value: float) -> None: ...
    @property
    def G1Check(self) -> bool: ...
    @G1Check.setter
    def G1Check(self, value: bool) -> None: ...
    @property
    def G1Check2(self) -> bool: ...
    @G1Check2.setter
    def G1Check2(self, value: bool) -> None: ...
    @property
    def G1Tolerance(self) -> float: ...
    @G1Tolerance.setter
    def G1Tolerance(self, value: float) -> None: ...
    @property
    def G2Check(self) -> bool: ...
    @G2Check.setter
    def G2Check(self, value: bool) -> None: ...
    @property
    def G2Check2(self) -> bool: ...
    @G2Check2.setter
    def G2Check2(self, value: bool) -> None: ...
    @property
    def G2Tolerance(self) -> float: ...
    @G2Tolerance.setter
    def G2Tolerance(self, value: float) -> None: ...
    @property
    def G3Check(self) -> bool: ...
    @G3Check.setter
    def G3Check(self, value: bool) -> None: ...
    @property
    def G3Check2(self) -> bool: ...
    @G3Check2.setter
    def G3Check2(self, value: bool) -> None: ...
    @property
    def G3Tolerance(self) -> float: ...
    @G3Tolerance.setter
    def G3Tolerance(self, value: float) -> None: ...
    @property
    def MultiCurve(self) -> SelectDisplayableObjectList: ...
    @MultiCurve.setter
    def MultiCurve(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def SelectCurve(self) -> SelectNXObject: ...
    @SelectCurve.setter
    def SelectCurve(self, value: SelectNXObject) -> None: ...
    @property
    def SelectObject(self) -> SelectNXObject: ...
    @SelectObject.setter
    def SelectObject(self, value: SelectNXObject) -> None: ...
    @property
    def ShowDeviation(self) -> bool: ...
    @ShowDeviation.setter
    def ShowDeviation(self, value: bool) -> None: ...
    @property
    def ShowMarkup(self) -> bool: ...
    @ShowMarkup.setter
    def ShowMarkup(self, value: bool) -> None: ...
    @property
    def ShowMaximum(self) -> bool: ...
    @ShowMaximum.setter
    def ShowMaximum(self, value: bool) -> None: ...
    @property
    def ShowMinimum(self) -> bool: ...
    @ShowMinimum.setter
    def ShowMinimum(self, value: bool) -> None: ...
    @property
    def ShowNeedle(self) -> bool: ...
    @ShowNeedle.setter
    def ShowNeedle(self, value: bool) -> None: ...
    @property
    def ShowOutOfTolerance(self) -> bool: ...
    @ShowOutOfTolerance.setter
    def ShowOutOfTolerance(self, value: bool) -> None: ...


    class Type(enum.Enum):
        CurvetoObject= 0
        Multicurve= 1
    

class CurveContinuity(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class CurveAnalysisRecord(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def CombDensity(self) -> int: ...
    @CombDensity.setter
    def CombDensity(self, value: int) -> None: ...
    @property
    def CombInterneedleDensity(self) -> int: ...
    @CombInterneedleDensity.setter
    def CombInterneedleDensity(self, value: int) -> None: ...
    @property
    def CombMaxLength(self) -> float: ...
    @CombMaxLength.setter
    def CombMaxLength(self, value: float) -> None: ...
    @property
    def CombScaleFactor(self) -> float: ...
    @CombScaleFactor.setter
    def CombScaleFactor(self, value: float) -> None: ...
    @property
    def Direction(self) -> Vector3d: ...
    @Direction.setter
    def Direction(self, value: Vector3d) -> None: ...
    @property
    def DirectionOption(self) -> GeometricAnalysis.CurveAnalysisRecord.DirectionOptionType: ...
    @DirectionOption.setter
    def DirectionOption(self, value: GeometricAnalysis.CurveAnalysisRecord.DirectionOptionType) -> None: ...
    @property
    def End(self) -> float: ...
    @End.setter
    def End(self, value: float) -> None: ...
    @property
    def ShowComb(self) -> bool: ...
    @ShowComb.setter
    def ShowComb(self, value: bool) -> None: ...
    @property
    def ShowInflection(self) -> bool: ...
    @ShowInflection.setter
    def ShowInflection(self, value: bool) -> None: ...
    @property
    def ShowKnot(self) -> bool: ...
    @ShowKnot.setter
    def ShowKnot(self, value: bool) -> None: ...
    @property
    def ShowPeak(self) -> bool: ...
    @ShowPeak.setter
    def ShowPeak(self, value: bool) -> None: ...
    @property
    def ShowPole(self) -> bool: ...
    @ShowPole.setter
    def ShowPole(self, value: bool) -> None: ...
    @property
    def Start(self) -> float: ...
    @Start.setter
    def Start(self, value: float) -> None: ...
    @property
    def UseMaxLength(self) -> bool: ...
    @UseMaxLength.setter
    def UseMaxLength(self, value: bool) -> None: ...


    class DirectionOptionType(enum.Enum):
        None_= 0
        PlaneOfCurve= 1
        SpecifyVector= 2
        WorkView= 3
    

class CurveAnalysisDisplay(Utilities.NXRemotableObject):
    def __init__(self, owner: GeometricAnalysis.AnalysisObjectCollection) -> None: ...
    def SetAnalysisRecord(self, curve: Curve, record: GeometricAnalysis.CurveAnalysisRecord) -> None: ...
    def GetAnalysisRecord(self, curve: Curve) -> GeometricAnalysis.CurveAnalysisRecord: ...
    def NewRecord(self) -> GeometricAnalysis.CurveAnalysisRecord: ...
    def SetShowFlag(self, curve: Curve, choice: GeometricAnalysis.CurveAnalysisDisplay.ShowFlagType, on: bool) -> None: ...
    def SetShowPole(self, curve: Curve, show: bool) -> None: ...
    def GetShowPole(self, curve: Curve) -> bool: ...
    def SetShowKnot(self, curve: Curve, show: bool) -> None: ...
    def GetShowKnot(self, curve: Curve) -> bool: ...
    def SetShowEndPoints(self, curve: Curve, show: bool) -> None: ...
    def GetShowEndPoints(self, curve: Curve) -> bool: ...
    def Tag(self) -> Tag: ...



    class ShowFlagType(enum.Enum):
        Pole= 0
        Comb= 1
        Inflection= 2
        Peak= 3
        Knot= 4
        Endpoint= 5
    

class ContactAnalysisSectionCurveBuilder(Display.DynamicSectionBuilder):
    def __init__(self) -> None: ...
    def OrientToPlane(self) -> None: ...
    @property
    def BallDiameter(self) -> float: ...
    @BallDiameter.setter
    def BallDiameter(self, value: float) -> None: ...
    @property
    def DisplaySlice(self) -> bool: ...
    @DisplaySlice.setter
    def DisplaySlice(self, value: bool) -> None: ...
    @property
    def PointToPlaceSphere(self) -> Point: ...
    @PointToPlaceSphere.setter
    def PointToPlaceSphere(self, value: Point) -> None: ...
    @property
    def SectionBoundary(self) -> Expression: ...
    @SectionBoundary.setter
    def SectionBoundary(self, value: Expression) -> None: ...
    @property
    def SectionCurveColor(self) -> NXColor: ...
    @SectionCurveColor.setter
    def SectionCurveColor(self, value: NXColor) -> None: ...


class ContactAnalysisResult(Validate.AnalysisResult):
    def __init__(self) -> None: ...


class ContactAnalysisBuilder(Builder):
    def __init__(self) -> None: ...
    def CreateCheckPoints(self) -> None: ...
    def CreateSectionCurves(self) -> GeometricAnalysis.ContactAnalysisSectionCurveBuilder: ...
    def SaveContourCurves(self) -> None: ...
    def Update(self) -> None: ...
    def AddGCPoint(self, face: Face, point: Point) -> None: ...
    def SetGCPoint(self, face: Face, point: Point) -> None: ...
    def DeleteGCPoint(self, point: Point) -> None: ...
    def ClearGConstraintPointData(self) -> None: ...
    @property
    def AreasNotTouchedByBall(self) -> NXColor: ...
    @AreasNotTouchedByBall.setter
    def AreasNotTouchedByBall(self, value: NXColor) -> None: ...
    @property
    def AreasTouchedByBall(self) -> NXColor: ...
    @AreasTouchedByBall.setter
    def AreasTouchedByBall(self, value: NXColor) -> None: ...
    @property
    def AutomaticUpdate(self) -> bool: ...
    @AutomaticUpdate.setter
    def AutomaticUpdate(self, value: bool) -> None: ...
    @property
    def BallDiameter(self) -> Expression: ...
    @BallDiameter.setter
    def BallDiameter(self, value: Expression) -> None: ...
    @property
    def BodySelection(self) -> ScCollector: ...
    @BodySelection.setter
    def BodySelection(self, value: ScCollector) -> None: ...
    @property
    def CreateMinRadiusPoints(self) -> bool: ...
    @CreateMinRadiusPoints.setter
    def CreateMinRadiusPoints(self, value: bool) -> None: ...
    @property
    def CreatePointsAtStepDist(self) -> bool: ...
    @CreatePointsAtStepDist.setter
    def CreatePointsAtStepDist(self, value: bool) -> None: ...
    @property
    def DisplayContourCurves(self) -> bool: ...
    @DisplayContourCurves.setter
    def DisplayContourCurves(self, value: bool) -> None: ...
    @property
    def DisplayResolution(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @DisplayResolution.setter
    def DisplayResolution(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def EnableRadiusAnalysis(self) -> bool: ...
    @EnableRadiusAnalysis.setter
    def EnableRadiusAnalysis(self, value: bool) -> None: ...
    @property
    def ExternalBallDiameter(self) -> Expression: ...
    @ExternalBallDiameter.setter
    def ExternalBallDiameter(self, value: Expression) -> None: ...
    @property
    def GeometricConstraintDataManager(self) -> Features.GeometricConstraintDataManager: ...
    @GeometricConstraintDataManager.setter
    def GeometricConstraintDataManager(self, value: Features.GeometricConstraintDataManager) -> None: ...
    @property
    def HemishpericalBallDiameter(self) -> Expression: ...
    @HemishpericalBallDiameter.setter
    def HemishpericalBallDiameter(self, value: Expression) -> None: ...
    @property
    def IntermediateAreas(self) -> NXColor: ...
    @IntermediateAreas.setter
    def IntermediateAreas(self, value: NXColor) -> None: ...
    @property
    def InternalBallDiameter(self) -> Expression: ...
    @InternalBallDiameter.setter
    def InternalBallDiameter(self, value: Expression) -> None: ...
    @property
    def MaximumRadius(self) -> Expression: ...
    @MaximumRadius.setter
    def MaximumRadius(self, value: Expression) -> None: ...
    @property
    def MinimumRadius(self) -> Expression: ...
    @MinimumRadius.setter
    def MinimumRadius(self, value: Expression) -> None: ...
    @property
    def Normals(self) -> GeometricAnalysis.FaceAnalysisNormalsBuilder: ...
    @Normals.setter
    def Normals(self, value: GeometricAnalysis.FaceAnalysisNormalsBuilder) -> None: ...
    @property
    def ProtrusionLimit(self) -> Expression: ...
    @ProtrusionLimit.setter
    def ProtrusionLimit(self, value: Expression) -> None: ...
    @property
    def RamDiameter(self) -> Expression: ...
    @RamDiameter.setter
    def RamDiameter(self, value: Expression) -> None: ...
    @property
    def SharpAreas(self) -> NXColor: ...
    @SharpAreas.setter
    def SharpAreas(self, value: NXColor) -> None: ...
    @property
    def ShowOnlyContactAnalysisAreas(self) -> bool: ...
    @ShowOnlyContactAnalysisAreas.setter
    def ShowOnlyContactAnalysisAreas(self, value: bool) -> None: ...
    @property
    def ShowOnlySharpAreas(self) -> bool: ...
    @ShowOnlySharpAreas.setter
    def ShowOnlySharpAreas(self, value: bool) -> None: ...
    @property
    def SmoothAreas(self) -> NXColor: ...
    @SmoothAreas.setter
    def SmoothAreas(self, value: NXColor) -> None: ...
    @property
    def StepDistance(self) -> Expression: ...
    @StepDistance.setter
    def StepDistance(self, value: Expression) -> None: ...


class AnalysisResultCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Validate.AnalysisResult]: ...
    @typing.overload
    def __init__(self, owner: BasePart) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateContactAnalysisBuilder(self, persistentResult: Validate.AnalysisResult) -> GeometricAnalysis.ContactAnalysisBuilder: ...
    def CreateContactAnalysisSectionCurveBuilder(self, view: ModelingView, contactAnalysisBuilder: GeometricAnalysis.ContactAnalysisBuilder) -> GeometricAnalysis.ContactAnalysisSectionCurveBuilder: ...
    def Tag(self) -> Tag: ...



class AnalysisObjectCollectionEx(Utilities.NXRemotableObject):
    def __init__(self, owner: GeometricAnalysis.AnalysisObjectCollection) -> None: ...
    def CreateRadiusAnalysisBuilder(self, radiusAO: DisplayableObject) -> GeometricAnalysis.RadiusAnalysisBuilder: ...
    def CreateSlopeAnalysisBuilder(self, slopeAO: DisplayableObject) -> GeometricAnalysis.SlopeAnalysisBuilder: ...
    def CreateDistanceAnalysisBuilder(self, distanceAO: DisplayableObject) -> GeometricAnalysis.DistanceAnalysisBuilder: ...
    def CreateReflectionAnalysisBuilder(self, reflectionAO: DisplayableObject) -> GeometricAnalysis.ReflectionAnalysisBuilder: ...
    def CreateSheetBoundaryAnalysisBuilder(self, sheetBoundaryAnalysisAO: GeometricAnalysis.SheetBoundaryAnalysis) -> GeometricAnalysis.SheetBoundaryAnalysisBuilder: ...
    def Tag(self) -> Tag: ...



class AnalysisObjectCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[GeometricAnalysis.AnalysisObject]: ...
    @typing.overload
    def __init__(self, owner: GeometricAnalysis.AnalysisManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateGapFlushnessBuilder(self, gfaoObject: GeometricAnalysis.GapFlushness) -> GeometricAnalysis.GapFlushnessBuilder: ...
    def CreateSurfaceContinuityAnalysisBuilder(self, scaoObject: DisplayableObject) -> GeometricAnalysis.SurfaceContinuityAnalysisBuilder: ...
    def CreateCurveCurvatureAnalysisBuilder(self, caaoObject: DisplayableObject) -> GeometricAnalysis.CurveCurvatureAnalysisBuilder: ...
    def CreateHighlightLinesAnalysisBuilder(self, hpaoObject: DisplayableObject) -> GeometricAnalysis.HighlightLinesAnalysisBuilder: ...
    def CreateSectionAnalysisBuilder(self, msaoObject: GeometricAnalysis.SectionAnalysisObject) -> GeometricAnalysis.SectionAnalysis.SectionAnalysisBuilder: ...
    def CreateSectionAnalysisExBuilder(self, csaoObject: GeometricAnalysis.SectionAnalysis.SectionAnalysisExObject) -> GeometricAnalysis.SectionAnalysis.SectionAnalysisExBuilder: ...
    def CreateDeviationGaugeBuilder(self, ddaoObject: DisplayableObject) -> GeometricAnalysis.DeviationGaugeBuilder: ...
    def CreateCurveContinuityBuilder(self, ccaoObject: DisplayableObject) -> GeometricAnalysis.CurveContinuityBuilder: ...
    def CreateSurfaceIntersectionBuilder(self, siaoObject: DisplayableObject) -> GeometricAnalysis.SurfaceIntersectionBuilder: ...
    def CreateDraftAnalysisBuilder(self, daoObject: DisplayableObject) -> GeometricAnalysis.DraftAnalysisBuilder: ...
    def CreateLocalRadiusAnalysisBuilder(self, lrao: GeometricAnalysis.LocalRadiusAnalysis) -> GeometricAnalysis.LocalRadiusAnalysisBuilder: ...
    def CreateFaceCurvatureAnalysisBuilder(self, fcaoObject: DisplayableObject) -> GeometricAnalysis.FaceCurvatureAnalysisBuilder: ...
    def Tag(self) -> Tag: ...

    @property
    def CurveAnalysisDisplayObject(self) -> GeometricAnalysis.CurveAnalysisDisplay: ...
    @CurveAnalysisDisplayObject.setter
    def CurveAnalysisDisplayObject(self, value: GeometricAnalysis.CurveAnalysisDisplay) -> None: ...
    @property
    def SurfaceAnalysisDisplayObject(self) -> GeometricAnalysis.SurfaceAnalysisDisplay: ...
    @SurfaceAnalysisDisplayObject.setter
    def SurfaceAnalysisDisplayObject(self, value: GeometricAnalysis.SurfaceAnalysisDisplay) -> None: ...
    @property
    def AnalysisObjectsEx(self) -> GeometricAnalysis.AnalysisObjectCollectionEx: ...
    @AnalysisObjectsEx.setter
    def AnalysisObjectsEx(self, value: GeometricAnalysis.AnalysisObjectCollectionEx) -> None: ...


class AnalysisObject(DisplayableObject):
    def __init__(self) -> None: ...


class AnalysisManager(Utilities.NXRemotableObject):
    def __init__(self, owner: BasePart) -> None: ...
    def CreateExamineGeometryObject(self) -> GeometricAnalysis.ExamineGeometry: ...
    def CreateSimpleInterferenceObject(self) -> GeometricAnalysis.SimpleInterference: ...
    def CreateGeometricPropertiesObject(self) -> GeometricAnalysis.GeometricProperties: ...
    def CreateSolidDensityObject(self) -> GeometricAnalysis.SolidDensity: ...
    def CreateDeviationCheckingObject(self) -> GeometricAnalysis.DeviationChecking: ...
    def Tag(self) -> Tag: ...

    @property
    def AnalysisObjects(self) -> GeometricAnalysis.AnalysisObjectCollection: ...
    @AnalysisObjects.setter
    def AnalysisObjects(self, value: GeometricAnalysis.AnalysisObjectCollection) -> None: ...


