from ...NXOpen import *

import typing
import enum

class WrapMeshBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AngleThreshold(self) -> float: ...
    @AngleThreshold.setter
    def AngleThreshold(self, value: float) -> None: ...
    @property
    def AverageSize(self) -> Expression: ...
    @AverageSize.setter
    def AverageSize(self, value: Expression) -> None: ...
    @property
    def ChordalTolerance(self) -> float: ...
    @ChordalTolerance.setter
    def ChordalTolerance(self, value: float) -> None: ...
    @property
    def GapFaces(self) -> ScCollector: ...
    @GapFaces.setter
    def GapFaces(self, value: ScCollector) -> None: ...
    @property
    def InputBodyCollector(self) -> ScCollector: ...
    @InputBodyCollector.setter
    def InputBodyCollector(self, value: ScCollector) -> None: ...
    @property
    def InputBodyOption(self) -> Facet.WrapMeshBuilder.KeepInputBodyType: ...
    @InputBodyOption.setter
    def InputBodyOption(self, value: Facet.WrapMeshBuilder.KeepInputBodyType) -> None: ...
    @property
    def IntendedGapSize(self) -> Expression: ...
    @IntendedGapSize.setter
    def IntendedGapSize(self, value: Expression) -> None: ...
    @property
    def KeepSharpEdges(self) -> bool: ...
    @KeepSharpEdges.setter
    def KeepSharpEdges(self, value: bool) -> None: ...
    @property
    def MaxGapSize(self) -> Expression: ...
    @MaxGapSize.setter
    def MaxGapSize(self, value: Expression) -> None: ...
    @property
    def MaximumSize(self) -> Expression: ...
    @MaximumSize.setter
    def MaximumSize(self, value: Expression) -> None: ...
    @property
    def Method(self) -> Facet.WrapMeshBuilder.MethodType: ...
    @Method.setter
    def Method(self, value: Facet.WrapMeshBuilder.MethodType) -> None: ...
    @property
    def SeedPoint(self) -> SelectDisplayableObjectList: ...
    @SeedPoint.setter
    def SeedPoint(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def WrapMeshMode(self) -> Facet.WrapMeshBuilder.WrapMeshModeType: ...
    @WrapMeshMode.setter
    def WrapMeshMode(self, value: Facet.WrapMeshBuilder.WrapMeshModeType) -> None: ...


    class WrapMeshModeType(enum.Enum):
        Constant= 0
        Variable= 1
    

    class MethodType(enum.Enum):
        External= 0
        LargestInternal= 1
        InternalBySeedPoint= 2
    

    class KeepInputBodyType(enum.Enum):
        Keep= 0
        Hide= 1
    

class SubdivideFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AngleThreshold(self) -> float: ...
    @AngleThreshold.setter
    def AngleThreshold(self, value: float) -> None: ...
    @property
    def Bodies(self) -> SelectDisplayableObjectList: ...
    @Bodies.setter
    def Bodies(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def EdgeLength(self) -> float: ...
    @EdgeLength.setter
    def EdgeLength(self, value: float) -> None: ...
    @property
    def FacetBodies(self) -> Facet.SelectFacetedBodyList: ...
    @FacetBodies.setter
    def FacetBodies(self, value: Facet.SelectFacetedBodyList) -> None: ...
    @property
    def FacetCollector(self) -> FacetCollector: ...
    @FacetCollector.setter
    def FacetCollector(self, value: FacetCollector) -> None: ...
    @property
    def InterpolationMethod(self) -> Facet.SubdivideFacetBodyBuilder.InterpolationMethodType: ...
    @InterpolationMethod.setter
    def InterpolationMethod(self, value: Facet.SubdivideFacetBodyBuilder.InterpolationMethodType) -> None: ...
    @property
    def IsEditCopy(self) -> bool: ...
    @IsEditCopy.setter
    def IsEditCopy(self, value: bool) -> None: ...
    @property
    def IsOptimize(self) -> bool: ...
    @IsOptimize.setter
    def IsOptimize(self, value: bool) -> None: ...
    @property
    def RegionList(self) -> GeometricUtilities.BoundaryDefinitionBuilderList: ...
    @RegionList.setter
    def RegionList(self, value: GeometricUtilities.BoundaryDefinitionBuilderList) -> None: ...
    @property
    def SubdivisionMethod(self) -> Facet.SubdivideFacetBodyBuilder.SubdivisionMethodType: ...
    @SubdivisionMethod.setter
    def SubdivisionMethod(self, value: Facet.SubdivideFacetBodyBuilder.SubdivisionMethodType) -> None: ...


    class SubdivisionMethodType(enum.Enum):
        SubdivideIntoFour= 0
        SubdividebyEdgeLength= 1
    

    class InterpolationMethodType(enum.Enum):
        Linear= 0
        Cubic= 1
    

class STLImportBuilder(Builder):
    def __init__(self) -> None: ...
    def GetTopology(self) -> typing.List[Part]: ...
    @property
    def AngularTolerance(self) -> Facet.STLImportBuilder.AngularToleranceTypes: ...
    @AngularTolerance.setter
    def AngularTolerance(self, value: Facet.STLImportBuilder.AngularToleranceTypes) -> None: ...
    @property
    def CleanUp(self) -> bool: ...
    @CleanUp.setter
    def CleanUp(self, value: bool) -> None: ...
    @property
    def FacetBodyType(self) -> Facet.STLImportBuilder.FacetBodyTypes: ...
    @FacetBodyType.setter
    def FacetBodyType(self, value: Facet.STLImportBuilder.FacetBodyTypes) -> None: ...
    @property
    def File(self) -> str: ...
    @File.setter
    def File(self, value: str) -> None: ...
    @property
    def HideSmoothEdges(self) -> bool: ...
    @HideSmoothEdges.setter
    def HideSmoothEdges(self, value: bool) -> None: ...
    @property
    def MinimumAngleFoldedFacets(self) -> float: ...
    @MinimumAngleFoldedFacets.setter
    def MinimumAngleFoldedFacets(self, value: float) -> None: ...
    @property
    def MinimumFacetNumber(self) -> int: ...
    @MinimumFacetNumber.setter
    def MinimumFacetNumber(self, value: int) -> None: ...
    @property
    def STLFileUnits(self) -> Facet.STLImportBuilder.STLFileUnitsTypes: ...
    @STLFileUnits.setter
    def STLFileUnits(self, value: Facet.STLImportBuilder.STLFileUnitsTypes) -> None: ...
    @property
    def ShowInformationWindow(self) -> bool: ...
    @ShowInformationWindow.setter
    def ShowInformationWindow(self, value: bool) -> None: ...


    class STLFileUnitsTypes(enum.Enum):
        Meters= 0
        Millimeters= 1
        Inches= 2
    

    class FacetBodyTypes(enum.Enum):
        Psm= 0
        Nx= 1
        Jt= 2
    

    class AngularToleranceTypes(enum.Enum):
        Coarse= 0
        Medium= 1
        Fine= 2
    

class SplitCurveMethodListDataManager(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def SplitCurveMethodList(self) -> TaggedObjectList: ...
    @SplitCurveMethodList.setter
    def SplitCurveMethodList(self, value: TaggedObjectList) -> None: ...


class SplitCurveMethodBuilder(Builder):
    def __init__(self) -> None: ...
    def AddCurveOnBodies(self, bodyArray: typing.List[Body]) -> None: ...
    def CreateSplitCurveWithUseExisting(self) -> typing.List[Spline]: ...
    @property
    def ExistingCurves(self) -> Section: ...
    @ExistingCurves.setter
    def ExistingCurves(self, value: Section) -> None: ...
    @property
    def ProjectDirection(self) -> GeometricUtilities.ProjectionOptions: ...
    @ProjectDirection.setter
    def ProjectDirection(self, value: GeometricUtilities.ProjectionOptions) -> None: ...


    class ProjectOption(enum.Enum):
        NormalToFace= 0
        AlongVector= 1
    

class SnipFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    def SwitchRegion(self) -> None: ...
    @property
    def AlongDirection(self) -> Facet.SnipFacetBodyBuilder.DirectionType: ...
    @AlongDirection.setter
    def AlongDirection(self, value: Facet.SnipFacetBodyBuilder.DirectionType) -> None: ...
    @property
    def AutomaticFillType(self) -> Facet.SnipFacetBodyBuilder.AutomaticFillTypes: ...
    @AutomaticFillType.setter
    def AutomaticFillType(self, value: Facet.SnipFacetBodyBuilder.AutomaticFillTypes) -> None: ...
    @property
    def Bodies(self) -> SelectDisplayableObjectList: ...
    @Bodies.setter
    def Bodies(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def BoundaryFacetTreatmentType(self) -> Facet.SnipFacetBodyBuilder.BoundaryFacetTreatmentMethod: ...
    @BoundaryFacetTreatmentType.setter
    def BoundaryFacetTreatmentType(self, value: Facet.SnipFacetBodyBuilder.BoundaryFacetTreatmentMethod) -> None: ...
    @property
    def CanDivide(self) -> bool: ...
    @CanDivide.setter
    def CanDivide(self, value: bool) -> None: ...
    @property
    def FacetBodies(self) -> Facet.SelectFacetedBodyList: ...
    @FacetBodies.setter
    def FacetBodies(self, value: Facet.SelectFacetedBodyList) -> None: ...
    @property
    def FacetCollector(self) -> FacetCollector: ...
    @FacetCollector.setter
    def FacetCollector(self, value: FacetCollector) -> None: ...
    @property
    def IsEditCopy(self) -> bool: ...
    @IsEditCopy.setter
    def IsEditCopy(self, value: bool) -> None: ...
    @property
    def IsSnipNearFacets(self) -> bool: ...
    @IsSnipNearFacets.setter
    def IsSnipNearFacets(self, value: bool) -> None: ...
    @property
    def Plane(self) -> Plane: ...
    @Plane.setter
    def Plane(self, value: Plane) -> None: ...
    @property
    def ProfileList(self) -> SectionList: ...
    @ProfileList.setter
    def ProfileList(self, value: SectionList) -> None: ...
    @property
    def ProjectionVector(self) -> Direction: ...
    @ProjectionVector.setter
    def ProjectionVector(self, value: Direction) -> None: ...
    @property
    def RegionList(self) -> GeometricUtilities.BoundaryDefinitionBuilderList: ...
    @RegionList.setter
    def RegionList(self, value: GeometricUtilities.BoundaryDefinitionBuilderList) -> None: ...
    @property
    def RegionPoint(self) -> SelectPointList: ...
    @RegionPoint.setter
    def RegionPoint(self, value: SelectPointList) -> None: ...
    @property
    def RegionsOption(self) -> Facet.SnipFacetBodyBuilder.RegionsOptionType: ...
    @RegionsOption.setter
    def RegionsOption(self, value: Facet.SnipFacetBodyBuilder.RegionsOptionType) -> None: ...
    @property
    def Type(self) -> Facet.SnipFacetBodyBuilder.Types: ...
    @Type.setter
    def Type(self, value: Facet.SnipFacetBodyBuilder.Types) -> None: ...
    @property
    def ViewDirection(self) -> Vector3d: ...
    @ViewDirection.setter
    def ViewDirection(self, value: Vector3d) -> None: ...


    class Types(enum.Enum):
        SnipByBoundary= 0
        SnipByRegion= 1
        SnipWithCurves= 2
        SnipAtPlane= 3
    

    class RegionsOptionType(enum.Enum):
        RemoveSelected= 0
        KeepSelected= 1
        Divide= 2
    

    class DirectionType(enum.Enum):
        ViewDirection= 0
        FacetNormal= 1
        AlongVector= 2
    

    class BoundaryFacetTreatmentMethod(enum.Enum):
        SnipFacets= 0
        RemoveFacets= 1
    

    class AutomaticFillTypes(enum.Enum):
        None_= 0
        Linear= 1
        Refined= 2
        TangentBased= 3
        CurvatureBased= 4
    

class SmoothFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Bodies(self) -> SelectDisplayableObjectList: ...
    @Bodies.setter
    def Bodies(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def FaceEdge(self) -> SelectNXObjectList: ...
    @FaceEdge.setter
    def FaceEdge(self, value: SelectNXObjectList) -> None: ...
    @property
    def FacetBodies(self) -> Facet.SelectFacetedBodyList: ...
    @FacetBodies.setter
    def FacetBodies(self, value: Facet.SelectFacetedBodyList) -> None: ...
    @property
    def FacetCollector(self) -> FacetCollector: ...
    @FacetCollector.setter
    def FacetCollector(self, value: FacetCollector) -> None: ...
    @property
    def IsEditCopy(self) -> bool: ...
    @IsEditCopy.setter
    def IsEditCopy(self, value: bool) -> None: ...
    @property
    def IsLockBoundary(self) -> bool: ...
    @IsLockBoundary.setter
    def IsLockBoundary(self, value: bool) -> None: ...
    @property
    def IsSmoothOverEdges(self) -> bool: ...
    @IsSmoothOverEdges.setter
    def IsSmoothOverEdges(self, value: bool) -> None: ...
    @property
    def ModifyPercent(self) -> int: ...
    @ModifyPercent.setter
    def ModifyPercent(self, value: int) -> None: ...
    @property
    def NumberOfIterations(self) -> int: ...
    @NumberOfIterations.setter
    def NumberOfIterations(self, value: int) -> None: ...
    @property
    def RegionList(self) -> GeometricUtilities.BoundaryDefinitionBuilderList: ...
    @RegionList.setter
    def RegionList(self, value: GeometricUtilities.BoundaryDefinitionBuilderList) -> None: ...
    @property
    def SmoothFactor(self) -> int: ...
    @SmoothFactor.setter
    def SmoothFactor(self, value: int) -> None: ...
    @property
    def Type(self) -> Facet.SmoothFacetBodyBuilder.Types: ...
    @Type.setter
    def Type(self, value: Facet.SmoothFacetBodyBuilder.Types) -> None: ...


    class Types(enum.Enum):
        Mesh= 0
        Edge= 1
    

class SewFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    def FlipRange(self) -> None: ...
    @property
    def DeformBody(self) -> Facet.SelectFacetedBody: ...
    @DeformBody.setter
    def DeformBody(self, value: Facet.SelectFacetedBody) -> None: ...
    @property
    def DeformDistance(self) -> Expression: ...
    @DeformDistance.setter
    def DeformDistance(self, value: Expression) -> None: ...
    @property
    def DistanceTolerance(self) -> float: ...
    @DistanceTolerance.setter
    def DistanceTolerance(self, value: float) -> None: ...
    @property
    def InputStatus(self) -> Facet.SewFacetBodyBuilder.Input: ...
    @InputStatus.setter
    def InputStatus(self, value: Facet.SewFacetBodyBuilder.Input) -> None: ...
    @property
    def TargetBody(self) -> Facet.SelectFacetedBody: ...
    @TargetBody.setter
    def TargetBody(self, value: Facet.SelectFacetedBody) -> None: ...
    @property
    def Vertex1(self) -> Point: ...
    @Vertex1.setter
    def Vertex1(self, value: Point) -> None: ...
    @property
    def Vertex2(self) -> Point: ...
    @Vertex2.setter
    def Vertex2(self, value: Point) -> None: ...


    class VertexIndex(enum.Enum):
        First= 0
        Second= 1
    

    class Input(enum.Enum):
        Keep= 0
        Delete= 1
        Hide= 2
    

class SelectFacetedBodyList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Add(self, object: Facet.FacetedBody) -> bool: ...
    @typing.overload
    def Add(self, objects: typing.List[Facet.FacetedBody]) -> bool: ...
    @typing.overload
    def Add(self, inputSelectionMethod: SelectionMethod) -> bool: ...
    @typing.overload
    def Add(self, selection: Facet.FacetedBody, view: View, point: Point3d) -> bool: ...
    @typing.overload
    def Remove(self, object: Facet.FacetedBody) -> bool: ...
    @typing.overload
    def Remove(self, object: Facet.FacetedBody, view: View) -> bool: ...
    @typing.overload
    def Remove(self, snapType: InferSnapType.SnapType, selection1: Facet.FacetedBody, view1: View, point1: Point3d, selection2: Facet.FacetedBody, view2: View, point2: Point3d) -> bool: ...
    def RemoveArray(self, objects: typing.List[Facet.FacetedBody]) -> bool: ...
    @typing.overload
    def Remove(self, inputSelectionMethod: SelectionMethod) -> bool: ...
    def Clear(self) -> None: ...
    def Contains(self, object: Facet.FacetedBody) -> bool: ...
    def SetArray(self, objects: typing.List[Facet.FacetedBody]) -> None: ...
    def GetArray(self) -> typing.List[Facet.FacetedBody]: ...
    def GetSelectObjectArray(self) -> typing.List[SelectObject]: ...
    @typing.overload
    def Add(self, snapType: InferSnapType.SnapType, selection1: Facet.FacetedBody, view1: View, point1: Point3d, selection2: Facet.FacetedBody, view2: View, point2: Point3d) -> bool: ...
    @typing.overload
    def Add(self, selection: Facet.FacetedBody, caeSubType: CaeObjectType.CaeSubType, caeSubId: int) -> bool: ...
    def Validate(self) -> bool: ...
    @property
    def DuplicatesAllowed(self) -> bool: ...
    @DuplicatesAllowed.setter
    def DuplicatesAllowed(self, value: bool) -> None: ...
    @property
    def Size(self) -> int: ...
    @Size.setter
    def Size(self, value: int) -> None: ...


class SelectFacetedBody(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def SetValue(self, selection: Facet.FacetedBody, view: View, point: Point3d) -> None: ...
    @typing.overload
    def GetValue(self, selection: Facet.FacetedBody, view: View, point: Point3d) -> None: ...
    @typing.overload
    def SetValue(self, snapType: InferSnapType.SnapType, selection1: Facet.FacetedBody, view1: View, point1: Point3d, selection2: Facet.FacetedBody, view2: View, point2: Point3d) -> None: ...
    @typing.overload
    def GetValue(self, snapType: InferSnapType.SnapType, selection1: Facet.FacetedBody, view1: View, point1: Point3d, selection2: Facet.FacetedBody, view2: View, point2: Point3d) -> None: ...
    @typing.overload
    def SetValue(self, selection: Facet.FacetedBody, caeSubType: CaeObjectType.CaeSubType, caeSubId: int) -> None: ...
    @typing.overload
    def GetValue(self, caeSubType: CaeObjectType.CaeSubType, caeSubId: int) -> Facet.FacetedBody: ...
    def Validate(self) -> bool: ...
    @property
    def Value(self) -> Facet.FacetedBody: ...
    @Value.setter
    def Value(self, value: Facet.FacetedBody) -> None: ...


class ReplaceMeshWithFaceBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def ConeAverageConstrainToDirectionToggle(self) -> bool: ...
    @ConeAverageConstrainToDirectionToggle.setter
    def ConeAverageConstrainToDirectionToggle(self, value: bool) -> None: ...
    @property
    def ConeAverageConstrainToDirectionVector(self) -> Direction: ...
    @ConeAverageConstrainToDirectionVector.setter
    def ConeAverageConstrainToDirectionVector(self, value: Direction) -> None: ...
    @property
    def ConeColinearConstraintAxis(self) -> Axis: ...
    @ConeColinearConstraintAxis.setter
    def ConeColinearConstraintAxis(self, value: Axis) -> None: ...
    @property
    def ConeConstraintTypes(self) -> Facet.ReplaceMeshWithFaceBuilder.ConeConstraint: ...
    @ConeConstraintTypes.setter
    def ConeConstraintTypes(self, value: Facet.ReplaceMeshWithFaceBuilder.ConeConstraint) -> None: ...
    @property
    def ConeHalfAngle(self) -> Expression: ...
    @ConeHalfAngle.setter
    def ConeHalfAngle(self, value: Expression) -> None: ...
    @property
    def ConeParallelConstraintVector(self) -> Direction: ...
    @ConeParallelConstraintVector.setter
    def ConeParallelConstraintVector(self, value: Direction) -> None: ...
    @property
    def CylinderAverageConstrainToDirectionToggle(self) -> bool: ...
    @CylinderAverageConstrainToDirectionToggle.setter
    def CylinderAverageConstrainToDirectionToggle(self, value: bool) -> None: ...
    @property
    def CylinderAverageConstrainToDirectionVector(self) -> Direction: ...
    @CylinderAverageConstrainToDirectionVector.setter
    def CylinderAverageConstrainToDirectionVector(self, value: Direction) -> None: ...
    @property
    def CylinderColinearConstraintAxis(self) -> Axis: ...
    @CylinderColinearConstraintAxis.setter
    def CylinderColinearConstraintAxis(self, value: Axis) -> None: ...
    @property
    def CylinderConstraintTypes(self) -> Facet.ReplaceMeshWithFaceBuilder.CylinderConstraint: ...
    @CylinderConstraintTypes.setter
    def CylinderConstraintTypes(self, value: Facet.ReplaceMeshWithFaceBuilder.CylinderConstraint) -> None: ...
    @property
    def CylinderOrSphereRadius(self) -> Expression: ...
    @CylinderOrSphereRadius.setter
    def CylinderOrSphereRadius(self, value: Expression) -> None: ...
    @property
    def CylinderParallelConstraintVector(self) -> Direction: ...
    @CylinderParallelConstraintVector.setter
    def CylinderParallelConstraintVector(self, value: Direction) -> None: ...
    @property
    def FacetCollector(self) -> FacetCollector: ...
    @FacetCollector.setter
    def FacetCollector(self, value: FacetCollector) -> None: ...
    @property
    def HalfAngleToggle(self) -> bool: ...
    @HalfAngleToggle.setter
    def HalfAngleToggle(self, value: bool) -> None: ...
    @property
    def MaxDeviation(self) -> Expression: ...
    @MaxDeviation.setter
    def MaxDeviation(self, value: Expression) -> None: ...
    @property
    def MinimumFacetNumber(self) -> int: ...
    @MinimumFacetNumber.setter
    def MinimumFacetNumber(self, value: int) -> None: ...
    @property
    def OrthogonalOrCoplanarConstraintPlane(self) -> Plane: ...
    @OrthogonalOrCoplanarConstraintPlane.setter
    def OrthogonalOrCoplanarConstraintPlane(self, value: Plane) -> None: ...
    @property
    def PlaneAverageConstrainToNormalToggle(self) -> bool: ...
    @PlaneAverageConstrainToNormalToggle.setter
    def PlaneAverageConstrainToNormalToggle(self, value: bool) -> None: ...
    @property
    def PlaneAverageConstrainToNormalVector(self) -> Direction: ...
    @PlaneAverageConstrainToNormalVector.setter
    def PlaneAverageConstrainToNormalVector(self, value: Direction) -> None: ...
    @property
    def PlaneConstraintTypes(self) -> Facet.ReplaceMeshWithFaceBuilder.PlaneConstraint: ...
    @PlaneConstraintTypes.setter
    def PlaneConstraintTypes(self, value: Facet.ReplaceMeshWithFaceBuilder.PlaneConstraint) -> None: ...
    @property
    def PlaneParallelConstraintNormal(self) -> Direction: ...
    @PlaneParallelConstraintNormal.setter
    def PlaneParallelConstraintNormal(self, value: Direction) -> None: ...
    @property
    def RadiusToggle(self) -> bool: ...
    @RadiusToggle.setter
    def RadiusToggle(self, value: bool) -> None: ...
    @property
    def ReplaceMeshOn(self) -> Facet.ReplaceMeshWithFaceBuilder.ReplaceMeshOnOption: ...
    @ReplaceMeshOn.setter
    def ReplaceMeshOn(self, value: Facet.ReplaceMeshWithFaceBuilder.ReplaceMeshOnOption) -> None: ...
    @property
    def SphereConcentricConstraintPoint(self) -> Point: ...
    @SphereConcentricConstraintPoint.setter
    def SphereConcentricConstraintPoint(self, value: Point) -> None: ...
    @property
    def SphereConstraintTypes(self) -> Facet.ReplaceMeshWithFaceBuilder.SphereConstraint: ...
    @SphereConstraintTypes.setter
    def SphereConstraintTypes(self, value: Facet.ReplaceMeshWithFaceBuilder.SphereConstraint) -> None: ...
    @property
    def Type(self) -> Facet.ReplaceMeshWithFaceBuilder.Types: ...
    @Type.setter
    def Type(self, value: Facet.ReplaceMeshWithFaceBuilder.Types) -> None: ...


    class Types(enum.Enum):
        Plane= 0
        Cylinder= 1
        Cone= 2
        Sphere= 3
    

    class SphereConstraint(enum.Enum):
        None_= 0
        Concentric= 1
        AverageConcentric= 2
    

    class ReplaceMeshOnOption(enum.Enum):
        OriginalBody= 0
        NewBody= 1
    

    class PlaneConstraint(enum.Enum):
        None_= 0
        Orthogonal= 1
        Parallel= 2
        Coplanar= 3
        AverageParallel= 4
        AverageCoplanar= 5
    

    class CylinderConstraint(enum.Enum):
        None_= 0
        Parallel= 1
        Colinear= 2
        AverageParallel= 3
        AverageColinear= 4
    

    class ConeConstraint(enum.Enum):
        None_= 0
        Parallel= 1
        Colinear= 2
        AverageParallel= 3
        AverageColinear= 4
    

class RemoveUndercutsBuilder(Builder):
    def __init__(self) -> None: ...
    def GenerateIsoclines(self) -> None: ...
    @property
    def DraftAngle(self) -> Expression: ...
    @DraftAngle.setter
    def DraftAngle(self, value: Expression) -> None: ...
    @property
    def DrawDirection(self) -> Direction: ...
    @DrawDirection.setter
    def DrawDirection(self, value: Direction) -> None: ...
    @property
    def FacetBody(self) -> SelectDisplayableObject: ...
    @FacetBody.setter
    def FacetBody(self, value: SelectDisplayableObject) -> None: ...
    @property
    def IsEditCopy(self) -> bool: ...
    @IsEditCopy.setter
    def IsEditCopy(self, value: bool) -> None: ...
    @property
    def MatchFace(self) -> bool: ...
    @MatchFace.setter
    def MatchFace(self, value: bool) -> None: ...
    @property
    def PartingObject(self) -> SelectDisplayableObject: ...
    @PartingObject.setter
    def PartingObject(self, value: SelectDisplayableObject) -> None: ...
    @property
    def SelectedCurve(self) -> ScCollector: ...
    @SelectedCurve.setter
    def SelectedCurve(self, value: ScCollector) -> None: ...


class RemeshFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AngularThreshold(self) -> float: ...
    @AngularThreshold.setter
    def AngularThreshold(self, value: float) -> None: ...
    @property
    def AverageSize(self) -> Expression: ...
    @AverageSize.setter
    def AverageSize(self, value: Expression) -> None: ...
    @property
    def ChordalTolerance(self) -> float: ...
    @ChordalTolerance.setter
    def ChordalTolerance(self, value: float) -> None: ...
    @property
    def FacetRegion(self) -> FacetCollector: ...
    @FacetRegion.setter
    def FacetRegion(self, value: FacetCollector) -> None: ...
    @property
    def IsEditCopy(self) -> bool: ...
    @IsEditCopy.setter
    def IsEditCopy(self, value: bool) -> None: ...
    @property
    def IsLockBoundary(self) -> bool: ...
    @IsLockBoundary.setter
    def IsLockBoundary(self, value: bool) -> None: ...
    @property
    def IsShowDeviationPlot(self) -> bool: ...
    @IsShowDeviationPlot.setter
    def IsShowDeviationPlot(self, value: bool) -> None: ...
    @property
    def MaximumSize(self) -> Expression: ...
    @MaximumSize.setter
    def MaximumSize(self, value: Expression) -> None: ...
    @property
    def RemeshMode(self) -> Facet.RemeshFacetBodyBuilder.RemeshModeType: ...
    @RemeshMode.setter
    def RemeshMode(self, value: Facet.RemeshFacetBodyBuilder.RemeshModeType) -> None: ...
    @property
    def SharpEdgesLockOption(self) -> Facet.RemeshFacetBodyBuilder.SharpEdgesLockType: ...
    @SharpEdgesLockOption.setter
    def SharpEdgesLockOption(self, value: Facet.RemeshFacetBodyBuilder.SharpEdgesLockType) -> None: ...


    class SharpEdgesLockType(enum.Enum):
        NoLock= 0
        SoftLock= 1
        HardLock= 2
    

    class RemeshModeType(enum.Enum):
        Constant= 0
        Variable= 1
    

class PolygonModelingBuilder(Builder):
    def __init__(self) -> None: ...
    def RemoveParameterOfBody(self, bodyTag: Body) -> None: ...
    def MergeAllFaces(self, bodyTag: Body) -> None: ...
    @property
    def ConvertType(self) -> Facet.PolygonModelingBuilder.ConvertTypes: ...
    @ConvertType.setter
    def ConvertType(self, value: Facet.PolygonModelingBuilder.ConvertTypes) -> None: ...
    @property
    def EditCopy(self) -> bool: ...
    @EditCopy.setter
    def EditCopy(self, value: bool) -> None: ...
    @property
    def SelectFacetBodies(self) -> SelectNXObjectList: ...
    @SelectFacetBodies.setter
    def SelectFacetBodies(self, value: SelectNXObjectList) -> None: ...


    class ConvertTypes(enum.Enum):
        Convergent= 0
        Facet= 1
    

class PlugLeakageBuilder(Builder):
    def __init__(self) -> None: ...
    def FindPath(self) -> None: ...
    def CreatePatch(self) -> None: ...
    @property
    def HoleMinimumSize(self) -> Expression: ...
    @HoleMinimumSize.setter
    def HoleMinimumSize(self, value: Expression) -> None: ...
    @property
    def InnerPoint(self) -> Point3d: ...
    @InnerPoint.setter
    def InnerPoint(self, value: Point3d) -> None: ...
    @property
    def InputBodyCollector(self) -> ScCollector: ...
    @InputBodyCollector.setter
    def InputBodyCollector(self, value: ScCollector) -> None: ...
    @property
    def OuterPoint(self) -> Point3d: ...
    @OuterPoint.setter
    def OuterPoint(self, value: Point3d) -> None: ...
    @property
    def RegionList(self) -> GeometricUtilities.BoundaryDefinitionBuilderList: ...
    @RegionList.setter
    def RegionList(self, value: GeometricUtilities.BoundaryDefinitionBuilderList) -> None: ...


class PaintFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    def GetPaintBrushColor(self) -> float: ...
    def SetPaintBrushColor(self, paintBrushColor: float) -> None: ...
    def SetupBodyColorData(self, bodies: typing.List[DisplayableObject]) -> None: ...
    def SetupColorData(self, facets: typing.List[Facet.FacetedBody]) -> None: ...
    def PaintBodiesBackgroundColor(self, bodies: typing.List[DisplayableObject]) -> None: ...
    def PaintFacetsBackGroundColor(self, facets: typing.List[Facet.FacetedBody]) -> None: ...
    def PaintSelectedFacets(self) -> None: ...
    @property
    def FacetCollector(self) -> FacetCollector: ...
    @FacetCollector.setter
    def FacetCollector(self, value: FacetCollector) -> None: ...
    @property
    def InheritBodyColorPick(self) -> SelectDisplayableObject: ...
    @InheritBodyColorPick.setter
    def InheritBodyColorPick(self, value: SelectDisplayableObject) -> None: ...
    @property
    def InheritColorPick(self) -> Facet.SelectFacetedBody: ...
    @InheritColorPick.setter
    def InheritColorPick(self, value: Facet.SelectFacetedBody) -> None: ...
    @property
    def PaintBrush(self) -> Facet.PaintBrushBuilder: ...
    @PaintBrush.setter
    def PaintBrush(self, value: Facet.PaintBrushBuilder) -> None: ...
    @property
    def PaintBrushSize(self) -> Expression: ...
    @PaintBrushSize.setter
    def PaintBrushSize(self, value: Expression) -> None: ...


class PaintBrushBuilder(Builder):
    def __init__(self) -> None: ...
    def GetPaintBrushColor(self) -> float: ...
    def SetPaintBrushColor(self, paintBrushColor: float) -> None: ...
    def SetFacetBeingPainted(self, facet: Facet.FacetedBody) -> None: ...
    def SetBodyBeingPainted(self, body: DisplayableObject) -> None: ...
    def PaintVertexColor(self, position: Point3d) -> None: ...
    def ClearThePaintPath(self) -> None: ...
    def SetupPaintFacetBody(self) -> None: ...
    def SetTemporaryFacetDisplay(self, tempDisplay: bool) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MultiPatchAlignmentBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AlignFacetPatches(self) -> SelectDisplayableObjectList: ...
    @AlignFacetPatches.setter
    def AlignFacetPatches(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def AlignmentBodies(self) -> Facet.SelectFacetedBodyList: ...
    @AlignmentBodies.setter
    def AlignmentBodies(self, value: Facet.SelectFacetedBodyList) -> None: ...
    @property
    def Iteration(self) -> int: ...
    @Iteration.setter
    def Iteration(self, value: int) -> None: ...
    @property
    def MaximumCheckingDistance(self) -> float: ...
    @MaximumCheckingDistance.setter
    def MaximumCheckingDistance(self, value: float) -> None: ...
    @property
    def ReferenceFacetPatches(self) -> SelectDisplayableObjectList: ...
    @ReferenceFacetPatches.setter
    def ReferenceFacetPatches(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def ReferencePatches(self) -> Facet.SelectFacetedBodyList: ...
    @ReferencePatches.setter
    def ReferencePatches(self, value: Facet.SelectFacetedBodyList) -> None: ...
    @property
    def Resolution(self) -> Facet.MultiPatchAlignmentBuilder.ResolutionType: ...
    @Resolution.setter
    def Resolution(self, value: Facet.MultiPatchAlignmentBuilder.ResolutionType) -> None: ...
    @property
    def Tolerance(self) -> float: ...
    @Tolerance.setter
    def Tolerance(self, value: float) -> None: ...


    class ResolutionType(enum.Enum):
        High= 0
        Medium= 1
        Low= 2
    

class MeshFromCloudBuilder(Builder):
    def __init__(self) -> None: ...
    def SuggestNeighborhoodSize(self) -> None: ...
    @property
    def AnalyzeMeshQuality(self) -> bool: ...
    @AnalyzeMeshQuality.setter
    def AnalyzeMeshQuality(self, value: bool) -> None: ...
    @property
    def ModeOptions(self) -> Facet.MeshFromCloudBuilder.ModeOption: ...
    @ModeOptions.setter
    def ModeOptions(self, value: Facet.MeshFromCloudBuilder.ModeOption) -> None: ...
    @property
    def NeighborhoodSize(self) -> float: ...
    @NeighborhoodSize.setter
    def NeighborhoodSize(self, value: float) -> None: ...
    @property
    def PointFile(self) -> str: ...
    @PointFile.setter
    def PointFile(self, value: str) -> None: ...
    @property
    def SelectPoints(self) -> SelectPointList: ...
    @SelectPoints.setter
    def SelectPoints(self, value: SelectPointList) -> None: ...
    @property
    def SmoothingFactor(self) -> int: ...
    @SmoothingFactor.setter
    def SmoothingFactor(self, value: int) -> None: ...
    @property
    def SourceOptions(self) -> Facet.MeshFromCloudBuilder.SourceOption: ...
    @SourceOptions.setter
    def SourceOptions(self, value: Facet.MeshFromCloudBuilder.SourceOption) -> None: ...
    @property
    def TargetVertexNumber(self) -> int: ...
    @TargetVertexNumber.setter
    def TargetVertexNumber(self, value: int) -> None: ...
    @property
    def TessellationPercentage(self) -> float: ...
    @TessellationPercentage.setter
    def TessellationPercentage(self, value: float) -> None: ...


    class SourceOption(enum.Enum):
        FromFile= 0
        ExistingPoints= 1
    

    class ModeOption(enum.Enum):
        UniformDensity= 0
        VariableDensity= 1
        KeepAllPoints= 2
    

class MergeFacetFacesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def FaceCollector(self) -> ScCollector: ...
    @FaceCollector.setter
    def FaceCollector(self, value: ScCollector) -> None: ...
    @property
    def IsEditCopy(self) -> bool: ...
    @IsEditCopy.setter
    def IsEditCopy(self, value: bool) -> None: ...


class MergeFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AngleTolerance(self) -> float: ...
    @AngleTolerance.setter
    def AngleTolerance(self, value: float) -> None: ...
    @property
    def ChordHeight(self) -> Expression: ...
    @ChordHeight.setter
    def ChordHeight(self, value: Expression) -> None: ...
    @property
    def DistanceTolerance(self) -> float: ...
    @DistanceTolerance.setter
    def DistanceTolerance(self, value: float) -> None: ...
    @property
    def EdgeLength(self) -> Expression: ...
    @EdgeLength.setter
    def EdgeLength(self, value: Expression) -> None: ...
    @property
    def FacetBodyOne(self) -> Facet.SelectFacetedBody: ...
    @FacetBodyOne.setter
    def FacetBodyOne(self, value: Facet.SelectFacetedBody) -> None: ...
    @property
    def FacetBodyTwo(self) -> Facet.SelectFacetedBody: ...
    @FacetBodyTwo.setter
    def FacetBodyTwo(self, value: Facet.SelectFacetedBody) -> None: ...
    @property
    def InputStatus(self) -> Facet.MergeFacetBodyBuilder.Input: ...
    @InputStatus.setter
    def InputStatus(self, value: Facet.MergeFacetBodyBuilder.Input) -> None: ...


    class Input(enum.Enum):
        Keep= 0
        Delete= 1
        Hide= 2
    

class LocalOffsetBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def FacetRegion(self) -> FacetCollector: ...
    @FacetRegion.setter
    def FacetRegion(self, value: FacetCollector) -> None: ...
    @property
    def FacetTransitionRegions(self) -> FacetCollector: ...
    @FacetTransitionRegions.setter
    def FacetTransitionRegions(self, value: FacetCollector) -> None: ...
    @property
    def IsEditCopy(self) -> bool: ...
    @IsEditCopy.setter
    def IsEditCopy(self, value: bool) -> None: ...
    @property
    def IsRegenerateOffsetMesh(self) -> bool: ...
    @IsRegenerateOffsetMesh.setter
    def IsRegenerateOffsetMesh(self, value: bool) -> None: ...
    @property
    def IsReverseDirection(self) -> bool: ...
    @IsReverseDirection.setter
    def IsReverseDirection(self, value: bool) -> None: ...
    @property
    def IsSmoothEdge(self) -> bool: ...
    @IsSmoothEdge.setter
    def IsSmoothEdge(self, value: bool) -> None: ...
    @property
    def OffsetDistance(self) -> Expression: ...
    @OffsetDistance.setter
    def OffsetDistance(self, value: Expression) -> None: ...
    @property
    def RegionDistance(self) -> Expression: ...
    @RegionDistance.setter
    def RegionDistance(self, value: Expression) -> None: ...
    @property
    def ShapeMethod(self) -> Facet.LocalOffsetBuilder.ShapeMethodType: ...
    @ShapeMethod.setter
    def ShapeMethod(self, value: Facet.LocalOffsetBuilder.ShapeMethodType) -> None: ...
    @property
    def TransitionMethod(self) -> Facet.LocalOffsetBuilder.TransitionMethodType: ...
    @TransitionMethod.setter
    def TransitionMethod(self, value: Facet.LocalOffsetBuilder.TransitionMethodType) -> None: ...


    class TransitionMethodType(enum.Enum):
        None_= 0
        ByConstantOffset= 1
        ByRegionSelection= 2
    

    class ShapeMethodType(enum.Enum):
        Sharp= 0
        Smooth= 1
    

class FillMeshBuilder(Builder):
    def __init__(self) -> None: ...
    def FlipRangeStart(self) -> None: ...
    def FlipRangeEnd(self) -> None: ...
    def SetCloseNotchVertex1(self, facetVertexData: Facet.FillMeshBuilder.FacetVertexData) -> None: ...
    def SetCloseNotchVertex2(self, facetVertexData: Facet.FillMeshBuilder.FacetVertexData) -> None: ...
    def SetBridgeGapStartEdgeVertex1(self, facetVertexData: Facet.FillMeshBuilder.FacetVertexData) -> None: ...
    def SetBridgeGapStartEdgeVertex2(self, facetVertexData: Facet.FillMeshBuilder.FacetVertexData) -> None: ...
    def SetBridgeGapEndEdgeVertex1(self, facetVertexData: Facet.FillMeshBuilder.FacetVertexData) -> None: ...
    def SetBridgeGapEndEdgeVertex2(self, facetVertexData: Facet.FillMeshBuilder.FacetVertexData) -> None: ...
    def UpdateHoles(self) -> None: ...
    @property
    def EdgeHole(self) -> SelectNXObjectList: ...
    @EdgeHole.setter
    def EdgeHole(self, value: SelectNXObjectList) -> None: ...
    @property
    def EdgeSelectionMethod(self) -> Facet.FillMeshBuilder.EdgeOptionMenu: ...
    @EdgeSelectionMethod.setter
    def EdgeSelectionMethod(self, value: Facet.FillMeshBuilder.EdgeOptionMenu) -> None: ...
    @property
    def EditCopy(self) -> bool: ...
    @EditCopy.setter
    def EditCopy(self, value: bool) -> None: ...
    @property
    def EndEdgeVertex1(self) -> Point: ...
    @EndEdgeVertex1.setter
    def EndEdgeVertex1(self, value: Point) -> None: ...
    @property
    def EndEdgeVertex2(self) -> Point: ...
    @EndEdgeVertex2.setter
    def EndEdgeVertex2(self, value: Point) -> None: ...
    @property
    def EndHole(self) -> SelectNXObjectList: ...
    @EndHole.setter
    def EndHole(self, value: SelectNXObjectList) -> None: ...
    @property
    def FacetBodies(self) -> SelectNXObjectList: ...
    @FacetBodies.setter
    def FacetBodies(self, value: SelectNXObjectList) -> None: ...
    @property
    def InnerHole(self) -> SelectNXObjectList: ...
    @InnerHole.setter
    def InnerHole(self, value: SelectNXObjectList) -> None: ...
    @property
    def MaxEdges(self) -> int: ...
    @MaxEdges.setter
    def MaxEdges(self, value: int) -> None: ...
    @property
    def OuterHole(self) -> SelectNXObjectList: ...
    @OuterHole.setter
    def OuterHole(self, value: SelectNXObjectList) -> None: ...
    @property
    def SmoothnessOption(self) -> Facet.FillMeshBuilder.SmoothnessOptionMenu: ...
    @SmoothnessOption.setter
    def SmoothnessOption(self, value: Facet.FillMeshBuilder.SmoothnessOptionMenu) -> None: ...
    @property
    def StartEdgeVertex1(self) -> Point: ...
    @StartEdgeVertex1.setter
    def StartEdgeVertex1(self, value: Point) -> None: ...
    @property
    def StartEdgeVertex2(self) -> Point: ...
    @StartEdgeVertex2.setter
    def StartEdgeVertex2(self, value: Point) -> None: ...
    @property
    def StartHole(self) -> SelectNXObjectList: ...
    @StartHole.setter
    def StartHole(self, value: SelectNXObjectList) -> None: ...
    @property
    def Type(self) -> Facet.FillMeshBuilder.Types: ...
    @Type.setter
    def Type(self, value: Facet.FillMeshBuilder.Types) -> None: ...
    @property
    def Vertex1(self) -> Point: ...
    @Vertex1.setter
    def Vertex1(self, value: Point) -> None: ...
    @property
    def Vertex2(self) -> Point: ...
    @Vertex2.setter
    def Vertex2(self, value: Point) -> None: ...


    class Types(enum.Enum):
        FillHole= 0
        CloseNotch= 1
        FillIsland= 2
        ConnectHoles= 3
        BridgeGap= 4
    

    class SmoothnessOptionMenu(enum.Enum):
        Linear= 0
        Refined= 1
        TangentBased= 2
        CurvatureBased= 3
    

    class FillMeshBuilderFacetVertexData():
        @property
        def Face(self) -> NXObject: ...
        @Face.setter
        def Face(self, value: NXObject) -> None: ...
        @property
        def NxFacetIndex(self) -> int: ...
        @NxFacetIndex.setter
        def NxFacetIndex(self, value: int) -> None: ...
        @property
        def PointCoord(self) -> Point3d: ...
        @PointCoord.setter
        def PointCoord(self, value: Point3d) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, Face: NXObject, NxFacetIndex: int, PointCoord: Point3d) -> None: ...
    

    class EdgeOptionMenu(enum.Enum):
        All= 0
        UserSelected= 1
        ByNumberofEdges= 2
    

    class FillMeshBuilder_FacetVertexData():
        @property
        def face(self) -> Tag: ...
        @face.setter
        def face(self, value: Tag) -> None: ...
        @property
        def nxFacetIndex(self) -> int: ...
        @nxFacetIndex.setter
        def nxFacetIndex(self, value: int) -> None: ...
        @property
        def pointCoord(self) -> Point3d: ...
        @pointCoord.setter
        def pointCoord(self, value: Point3d) -> None: ...
    

class FillHoleBuilder(Builder):
    def __init__(self) -> None: ...
    def ClearHoles(self) -> None: ...
    def FindHoles(self) -> None: ...
    def ClearHoleFills(self) -> None: ...
    def FillHoles(self, globalUpdate: bool) -> DisplayableObject: ...
    def SwitchHoleFillType(self) -> None: ...
    def GetHoleFillsOnly(self) -> DisplayableObject: ...
    def GetAllHoles(self, holeCurveTags: typing.List[DisplayableObject]) -> None: ...
    def GetNumberOfHoles(self) -> int: ...
    def GetHoleByIndex(self, index: int) -> ICurve: ...
    def GetTargetHolesByEdgeNumber(self, numMaxEdges: int, holeCurveTags: typing.List[DisplayableObject]) -> None: ...
    @property
    def BridgeEdges1(self) -> SelectICurveList: ...
    @BridgeEdges1.setter
    def BridgeEdges1(self, value: SelectICurveList) -> None: ...
    @property
    def BridgeEdges2(self) -> SelectICurveList: ...
    @BridgeEdges2.setter
    def BridgeEdges2(self, value: SelectICurveList) -> None: ...
    @property
    def InnerHole(self) -> SelectICurveList: ...
    @InnerHole.setter
    def InnerHole(self, value: SelectICurveList) -> None: ...
    @property
    def IsEditCopy(self) -> bool: ...
    @IsEditCopy.setter
    def IsEditCopy(self, value: bool) -> None: ...
    @property
    def MaxEdges(self) -> int: ...
    @MaxEdges.setter
    def MaxEdges(self, value: int) -> None: ...
    @property
    def OuterHole(self) -> SelectICurveList: ...
    @OuterHole.setter
    def OuterHole(self, value: SelectICurveList) -> None: ...
    @property
    def SmoothType(self) -> Facet.FillHoleBuilder.SmoothTypes: ...
    @SmoothType.setter
    def SmoothType(self, value: Facet.FillHoleBuilder.SmoothTypes) -> None: ...
    @property
    def TargetBody(self) -> SelectDisplayableObject: ...
    @TargetBody.setter
    def TargetBody(self, value: SelectDisplayableObject) -> None: ...
    @property
    def TargetFacetBody(self) -> Facet.SelectFacetedBody: ...
    @TargetFacetBody.setter
    def TargetFacetBody(self, value: Facet.SelectFacetedBody) -> None: ...
    @property
    def TargetHole(self) -> SelectICurveList: ...
    @TargetHole.setter
    def TargetHole(self, value: SelectICurveList) -> None: ...
    @property
    def TargetType(self) -> Facet.FillHoleBuilder.TargetTypes: ...
    @TargetType.setter
    def TargetType(self, value: Facet.FillHoleBuilder.TargetTypes) -> None: ...
    @property
    def Type(self) -> Facet.FillHoleBuilder.Types: ...
    @Type.setter
    def Type(self, value: Facet.FillHoleBuilder.Types) -> None: ...


    class Types(enum.Enum):
        FillHole= 0
        FillIsland= 1
        BridgeGap= 2
    

    class TargetTypes(enum.Enum):
        UserDefined= 0
        ByNumberOfEdges= 1
    

    class SmoothTypes(enum.Enum):
        Linear= 0
        Refined= 1
        TangentBased= 2
        CurvatureBased= 3
    

class FeatureExtractionBuilder(Builder):
    def __init__(self) -> None: ...
    def GetExtractedRegions(self) -> typing.List[Facet.FacetedBody]: ...
    def GetExtractedBorders(self) -> typing.List[Spline]: ...
    @property
    def AreBordersEnabled(self) -> bool: ...
    @AreBordersEnabled.setter
    def AreBordersEnabled(self, value: bool) -> None: ...
    @property
    def AreRegionsEnabled(self) -> bool: ...
    @AreRegionsEnabled.setter
    def AreRegionsEnabled(self, value: bool) -> None: ...
    @property
    def FacetBodies(self) -> Facet.SelectFacetedBodyList: ...
    @FacetBodies.setter
    def FacetBodies(self, value: Facet.SelectFacetedBodyList) -> None: ...
    @property
    def InputAction(self) -> Facet.FeatureExtractionBuilder.InputActions: ...
    @InputAction.setter
    def InputAction(self, value: Facet.FeatureExtractionBuilder.InputActions) -> None: ...
    @property
    def IsSmoothingEnabled(self) -> bool: ...
    @IsSmoothingEnabled.setter
    def IsSmoothingEnabled(self, value: bool) -> None: ...
    @property
    def MinimumBorderLength(self) -> float: ...
    @MinimumBorderLength.setter
    def MinimumBorderLength(self, value: float) -> None: ...
    @property
    def SmoothingFactor(self) -> float: ...
    @SmoothingFactor.setter
    def SmoothingFactor(self, value: float) -> None: ...


    class InputActions(enum.Enum):
        Blank= 0
        Retain= 1
        Delete= 2
    

class FacetModelingCollection(Utilities.NXRemotableObject):
    def __init__(self, owner: Facet.FacetedBodyCollection) -> None: ...
    def CreateConvertFacetBodyBuilder(self) -> Facet.ConvertFacetBodyBuilder: ...
    def CreateCleanupFacetBodyBuilder(self) -> Facet.CleanupFacetBodyBuilder: ...
    def CreateCombineFacetBodyBuilder(self) -> Facet.CombineFacetBodyBuilder: ...
    def CreateFacetBodyFromBodyBuilder(self) -> Facet.FacetBodyFromBodyBuilder: ...
    def CreateDetectPrimitivesBuilder(self) -> Facet.DetectPrimitivesBuilder: ...
    def CreatePaintFacetBodyBuilder(self) -> Facet.PaintFacetBodyBuilder: ...
    def CreatePaintBrushBuilder(self) -> Facet.PaintBrushBuilder: ...
    def CreateRemoveUndercutsBuilder(self) -> Facet.RemoveUndercutsBuilder: ...
    def CreateCreateTransitionBuilder(self) -> Facet.CreateTransitionBuilder: ...
    def CreateLocalOffsetBuilder(self) -> Facet.LocalOffsetBuilder: ...
    def CreateMergeFacetFacesBuilder(self) -> Facet.MergeFacetFacesBuilder: ...
    def CreateFacetAdjustMinimumRadiusBuilder(self) -> Facet.AdjustMinimumRadiusBuilder: ...
    def CreateDivideFacetFaceBuilder(self) -> Facet.DivideFacetFaceBuilder: ...
    def CreatePolygonModelingBuilder(self) -> Facet.PolygonModelingBuilder: ...
    def CreateRemeshFacetBodyBuilder(self) -> Facet.RemeshFacetBodyBuilder: ...
    def CreateSplitCurveMethodBuilder(self) -> Facet.SplitCurveMethodBuilder: ...
    def CreateSplitCurveMethodListDataManager(self) -> Facet.SplitCurveMethodListDataManager: ...
    def CreateFillMeshBuilder(self) -> Facet.FillMeshBuilder: ...
    def CreateMeshFromCloudBuilder(self) -> Facet.MeshFromCloudBuilder: ...
    def CreateCombineFacetBodiesBuilder(self) -> Facet.CombineFacetBodiesBuilder: ...
    def CreateWrapMeshBuilder(self) -> Facet.WrapMeshBuilder: ...
    def CreatePlugLeakageBuilder(self) -> Facet.PlugLeakageBuilder: ...
    def CreateReplaceMeshWithFaceBuilder(self) -> Facet.ReplaceMeshWithFaceBuilder: ...
    def CreateTubeLatticeBuilder(self, tubeLattice: Features.TubeLattice) -> Features.TubeLatticeBuilder: ...
    def Tag(self) -> Tag: ...



class FacetingParameters():
    @property
    def MaximumFacetEdges(self) -> int: ...
    @MaximumFacetEdges.setter
    def MaximumFacetEdges(self, value: int) -> None: ...
    @property
    def SpecifySurfaceTolerance(self) -> bool: ...
    @SpecifySurfaceTolerance.setter
    def SpecifySurfaceTolerance(self, value: bool) -> None: ...
    @property
    def SurfaceDistanceTolerance(self) -> float: ...
    @SurfaceDistanceTolerance.setter
    def SurfaceDistanceTolerance(self, value: float) -> None: ...
    @property
    def SurfaceAngularTolerance(self) -> float: ...
    @SurfaceAngularTolerance.setter
    def SurfaceAngularTolerance(self, value: float) -> None: ...
    @property
    def SpecifyCurveTolerance(self) -> bool: ...
    @SpecifyCurveTolerance.setter
    def SpecifyCurveTolerance(self, value: bool) -> None: ...
    @property
    def CurveDistanceTolerance(self) -> float: ...
    @CurveDistanceTolerance.setter
    def CurveDistanceTolerance(self, value: float) -> None: ...
    @property
    def CurveAngularTolerance(self) -> float: ...
    @CurveAngularTolerance.setter
    def CurveAngularTolerance(self, value: float) -> None: ...
    @property
    def CurveMaximumLength(self) -> float: ...
    @CurveMaximumLength.setter
    def CurveMaximumLength(self, value: float) -> None: ...
    @property
    def SpecifyConvexFacets(self) -> bool: ...
    @SpecifyConvexFacets.setter
    def SpecifyConvexFacets(self, value: bool) -> None: ...
    @property
    def SpecifyMaximumFacetSize(self) -> bool: ...
    @SpecifyMaximumFacetSize.setter
    def SpecifyMaximumFacetSize(self, value: bool) -> None: ...
    @property
    def MaximumFacetSize(self) -> float: ...
    @MaximumFacetSize.setter
    def MaximumFacetSize(self, value: float) -> None: ...
    @property
    def SpecifyParameters(self) -> bool: ...
    @SpecifyParameters.setter
    def SpecifyParameters(self, value: bool) -> None: ...
    @property
    def NumberStorageType(self) -> int: ...
    @NumberStorageType.setter
    def NumberStorageType(self, value: int) -> None: ...
    @property
    def SpecifyViewDirection(self) -> bool: ...
    @SpecifyViewDirection.setter
    def SpecifyViewDirection(self, value: bool) -> None: ...
    @property
    def SilhouetteViewDirection(self) -> Vector3d: ...
    @SilhouetteViewDirection.setter
    def SilhouetteViewDirection(self, value: Vector3d) -> None: ...
    @property
    def SilhouetteChordTolerance(self) -> float: ...
    @SilhouetteChordTolerance.setter
    def SilhouetteChordTolerance(self, value: float) -> None: ...
    @property
    def StoreFaceTag(self) -> bool: ...
    @StoreFaceTag.setter
    def StoreFaceTag(self, value: bool) -> None: ...
    @property
    def WithLODS(self) -> bool: ...
    @WithLODS.setter
    def WithLODS(self, value: bool) -> None: ...
    def ToString(self) -> str: ...


class FacetedFace(DisplayableObject):
    def __init__(self) -> None: ...
    def GetNumberOfEdges(self) -> int: ...
    def GetEdges(self) -> typing.List[Facet.FacetedEdge]: ...
    def GetBody(self) -> Facet.FacetedBody: ...
    def GetSurfaceData(self, position: Point3d, dir: Point3d, radius: float, radiusOrAngle: float, sense: bool) -> None: ...
    @property
    def FaceType(self) -> Facet.FacetedFace.FacetedfaceType: ...
    @FaceType.setter
    def FaceType(self, value: Facet.FacetedFace.FacetedfaceType) -> None: ...


    class FacetedfaceType(enum.Enum):
        Undefined= 0
        Planar= 1
        Cylindrical= 2
        Conical= 3
        Spherical= 4
        Toroidal= 5
        Parametric= 6
    

class FacetedEdge(DisplayableObject):
    def __init__(self) -> None: ...
    def GetFaces(self) -> typing.List[Facet.FacetedFace]: ...
    def GetVertices(self, vertex1: Point3d, vertex2: Point3d) -> None: ...
    def GetBody(self) -> Facet.FacetedBody: ...
    def GetCurveData(self, position: Point3d, dirOrEndPt: Point3d, xAxis: Point3d, radius: float, minorRadius: float) -> None: ...
    def GetLength(self) -> float: ...
    def GetLocations(self) -> typing.List[GeometricUtilities.CurveLocation]: ...
    @property
    def EdgeType(self) -> Facet.FacetedEdge.FacetededgeType: ...
    @EdgeType.setter
    def EdgeType(self, value: Facet.FacetedEdge.FacetededgeType) -> None: ...
    @property
    def IsReference(self) -> bool: ...
    @IsReference.setter
    def IsReference(self, value: bool) -> None: ...


    class FacetededgeType(enum.Enum):
        Undefined= 0
        Linear= 1
        Circular= 2
        Elliptical= 3
        Intersection= 4
        Spline= 5
    

class FacetedBodyCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Facet.FacetedBody]: ...
    @typing.overload
    def __init__(self, owner: Part) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> Facet.FacetedBody: ...
    def CreateFacetCurvatureBuilder(self) -> Facet.CurvatureBuilder: ...
    def CreateFacetFeatureExtractionBuilder(self) -> Facet.FeatureExtractionBuilder: ...
    def Convert(self, fromBody: Facet.FacetedBody, toFacetType: Facet.FacetedBodyCollection.Type) -> None: ...
    def Copy(self, fromBody: Facet.FacetedBody, toPart: Part, toFacetType: Facet.FacetedBodyCollection.Type) -> Facet.FacetedBody: ...
    def GetAssociatedFacetedBodies(self, solidBody: Body, numberOfUnloadedFacetedBodies: int) -> typing.List[Facet.FacetedBody]: ...
    def DeleteTemporaryFacesAndEdges(self) -> None: ...
    def CreateBestFitAlignBuilder(self) -> Facet.BestFitAlignBuilder: ...
    def CreateFillHoleBuilder(self) -> Facet.FillHoleBuilder: ...
    def CreateSTLImportBuilder(self) -> Facet.STLImportBuilder: ...
    def CreateDecimateFacetBodyBuilder(self) -> Facet.DecimateFacetBodyBuilder: ...
    def CreateMultiPatchAlignmentBuilder(self) -> Facet.MultiPatchAlignmentBuilder: ...
    def CreateSubdivideFacetBodyBuilder(self) -> Facet.SubdivideFacetBodyBuilder: ...
    def CreateSmoothFacetBodyBuilder(self) -> Facet.SmoothFacetBodyBuilder: ...
    def CreateSnipFacetBodyBuilder(self) -> Facet.SnipFacetBodyBuilder: ...
    def CreateFacetBody(self, solidBodies: typing.List[Body], facetBodies: typing.List[Facet.FacetedBody], errorTable: int) -> None: ...
    def CreateFacetBodyFromFaces(self, solidFaces: typing.List[Face], facetBodies: typing.List[Facet.FacetedBody], errorTable: int) -> None: ...
    def CreateExtrudeFacetBodyBuilder(self) -> Facet.ExtrudeFacetBodyBuilder: ...
    def CreateExtrudeProfileBuilder(self) -> Facet.ExtrudeProfileBuilder: ...
    def CreateMergeFacetBodyBuilder(self) -> Facet.MergeFacetBodyBuilder: ...
    def CreateBridgeFacetBodyBuilder(self) -> Facet.BridgeFacetBodyBuilder: ...
    def CreateSewFacetBodyBuilder(self) -> Facet.SewFacetBodyBuilder: ...
    def Tag(self) -> Tag: ...

    @property
    def FacetModelingCollection(self) -> Facet.FacetModelingCollection: ...
    @FacetModelingCollection.setter
    def FacetModelingCollection(self, value: Facet.FacetModelingCollection) -> None: ...


    class Type(enum.Enum):
        Nx= 0
        Jt= 1
    

class FacetedBody(DisplayableObject):
    def __init__(self) -> None: ...
    def GetNumberOfFacets(self, levelOfDetail: int) -> int: ...
    def GetFaces(self) -> typing.List[Facet.FacetedFace]: ...
    def GetNumberOfEdges(self) -> int: ...
    def GetEdges(self) -> typing.List[Facet.FacetedEdge]: ...
    def HasTopologyInformation(self) -> bool: ...
    def HasLightWeightAnalytics(self) -> bool: ...
    def GetParameters(self) -> Facet.FacetingParameters: ...
    def SetParameters(self, parameters: Facet.FacetingParameters) -> None: ...
    def DestroyOwnedFacets(self) -> None: ...
    @property
    def AssociatedBody(self) -> Body: ...
    @AssociatedBody.setter
    def AssociatedBody(self, value: Body) -> None: ...
    @property
    def BodyType(self) -> Facet.FacetedBody.FacetedbodyType: ...
    @BodyType.setter
    def BodyType(self, value: Facet.FacetedBody.FacetedbodyType) -> None: ...
    @property
    def IsAssemblyLevel(self) -> bool: ...
    @IsAssemblyLevel.setter
    def IsAssemblyLevel(self, value: bool) -> None: ...
    @property
    def IsAssociatedBodyLoaded(self) -> bool: ...
    @IsAssociatedBodyLoaded.setter
    def IsAssociatedBodyLoaded(self, value: bool) -> None: ...
    @property
    def IsSheetBody(self) -> bool: ...
    @IsSheetBody.setter
    def IsSheetBody(self, value: bool) -> None: ...
    @property
    def IsSolidBody(self) -> bool: ...
    @IsSolidBody.setter
    def IsSolidBody(self, value: bool) -> None: ...
    @property
    def NumberOfFaces(self) -> int: ...
    @NumberOfFaces.setter
    def NumberOfFaces(self, value: int) -> None: ...
    @property
    def NumberOfLevelsOfDetail(self) -> int: ...
    @NumberOfLevelsOfDetail.setter
    def NumberOfLevelsOfDetail(self, value: int) -> None: ...
    @property
    def SurfaceArea(self) -> float: ...
    @SurfaceArea.setter
    def SurfaceArea(self, value: float) -> None: ...
    @property
    def Volume(self) -> float: ...
    @Volume.setter
    def Volume(self, value: float) -> None: ...


    class FacetedbodyType(enum.Enum):
        Undefined= 0
        SolidBody= 1
        SheetBody= 2
    

class FacetBodyFromBodyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Associative(self) -> bool: ...
    @Associative.setter
    def Associative(self, value: bool) -> None: ...
    @property
    def MaximumDeviation(self) -> float: ...
    @MaximumDeviation.setter
    def MaximumDeviation(self, value: float) -> None: ...
    @property
    def NonFacetedBodiesToConvert(self) -> SelectDisplayableObjectList: ...
    @NonFacetedBodiesToConvert.setter
    def NonFacetedBodiesToConvert(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def OriginalBodyOption(self) -> Facet.FacetBodyFromBodyBuilder.OriginalBodyOptions: ...
    @OriginalBodyOption.setter
    def OriginalBodyOption(self, value: Facet.FacetBodyFromBodyBuilder.OriginalBodyOptions) -> None: ...
    @property
    def OutputType(self) -> Facet.FacetBodyFromBodyBuilder.OutputTypes: ...
    @OutputType.setter
    def OutputType(self, value: Facet.FacetBodyFromBodyBuilder.OutputTypes) -> None: ...


    class OutputTypes(enum.Enum):
        ConvergentBody= 0
        NXFacetBody= 1
        JTFacetBody= 2
    

    class OriginalBodyOptions(enum.Enum):
        Keep= 0
        Hide= 1
        Delete= 2
    

class ExtrudeProfileBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Direction(self) -> Direction: ...
    @Direction.setter
    def Direction(self, value: Direction) -> None: ...
    @property
    def FirstDistance(self) -> Expression: ...
    @FirstDistance.setter
    def FirstDistance(self, value: Expression) -> None: ...
    @property
    def Offset(self) -> Expression: ...
    @Offset.setter
    def Offset(self, value: Expression) -> None: ...
    @property
    def Profile(self) -> Section: ...
    @Profile.setter
    def Profile(self, value: Section) -> None: ...
    @property
    def SecondDistance(self) -> Expression: ...
    @SecondDistance.setter
    def SecondDistance(self, value: Expression) -> None: ...
    @property
    def Tolerance(self) -> Expression: ...
    @Tolerance.setter
    def Tolerance(self, value: Expression) -> None: ...


class ExtrudeFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Direction(self) -> Direction: ...
    @Direction.setter
    def Direction(self, value: Direction) -> None: ...
    @property
    def Distance(self) -> Expression: ...
    @Distance.setter
    def Distance(self, value: Expression) -> None: ...
    @property
    def DistanceTolerance(self) -> float: ...
    @DistanceTolerance.setter
    def DistanceTolerance(self, value: float) -> None: ...
    @property
    def FacetBody(self) -> SelectDisplayableObjectList: ...
    @FacetBody.setter
    def FacetBody(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def Offset(self) -> Expression: ...
    @Offset.setter
    def Offset(self, value: Expression) -> None: ...
    @property
    def Plane(self) -> Plane: ...
    @Plane.setter
    def Plane(self, value: Plane) -> None: ...
    @property
    def Type(self) -> Facet.ExtrudeFacetBodyBuilder.LimitType: ...
    @Type.setter
    def Type(self, value: Facet.ExtrudeFacetBodyBuilder.LimitType) -> None: ...


    class LimitType(enum.Enum):
        Distance= 0
        ToPlane= 1
    

class DivideFacetFaceBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Degree(self) -> int: ...
    @Degree.setter
    def Degree(self, value: int) -> None: ...
    @property
    def FacetBodyCollector(self) -> ScCollector: ...
    @FacetBodyCollector.setter
    def FacetBodyCollector(self, value: ScCollector) -> None: ...
    @property
    def FacetCollector(self) -> FacetCollector: ...
    @FacetCollector.setter
    def FacetCollector(self, value: FacetCollector) -> None: ...
    @property
    def IsEditCopy(self) -> bool: ...
    @IsEditCopy.setter
    def IsEditCopy(self, value: bool) -> None: ...
    @property
    def IsSmoothEdge(self) -> bool: ...
    @IsSmoothEdge.setter
    def IsSmoothEdge(self, value: bool) -> None: ...
    @property
    def Segments(self) -> int: ...
    @Segments.setter
    def Segments(self, value: int) -> None: ...
    @property
    def SplitCurveMethodListDataManager(self) -> Facet.SplitCurveMethodListDataManager: ...
    @SplitCurveMethodListDataManager.setter
    def SplitCurveMethodListDataManager(self, value: Facet.SplitCurveMethodListDataManager) -> None: ...
    @property
    def Type(self) -> Facet.DivideFacetFaceBuilder.DivideFacetTypes: ...
    @Type.setter
    def Type(self, value: Facet.DivideFacetFaceBuilder.DivideFacetTypes) -> None: ...


    class DivideFacetTypes(enum.Enum):
        ByColor= 0
        ByRegion= 1
        ByCurves= 2
    

class DetectPrimitivesBuilder(Builder):
    def __init__(self) -> None: ...
    def GetPlaneColor(self) -> float: ...
    def SetPlaneColor(self, planeColor: float) -> None: ...
    def GetSphereColor(self) -> float: ...
    def SetSphereColor(self, sphereColor: float) -> None: ...
    def GetCylinderColor(self) -> float: ...
    def SetCylinderColor(self, cylinderColor: float) -> None: ...
    def GetConeColor(self) -> float: ...
    def SetConeColor(self, coneColor: float) -> None: ...
    def GetBlendColor(self) -> float: ...
    def SetBlendColor(self, blendColor: float) -> None: ...
    def GetOtherColor(self) -> float: ...
    def SetOtherColor(self, otherColor: float) -> None: ...
    def AdjustShapeBoundary(self) -> None: ...
    @property
    def BlendFactor(self) -> Expression: ...
    @BlendFactor.setter
    def BlendFactor(self, value: Expression) -> None: ...
    @property
    def CurvatureSensitivity(self) -> int: ...
    @CurvatureSensitivity.setter
    def CurvatureSensitivity(self, value: int) -> None: ...
    @property
    def FacetSelection(self) -> SelectDisplayableObjectList: ...
    @FacetSelection.setter
    def FacetSelection(self, value: SelectDisplayableObjectList) -> None: ...


class DecimateFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AngleThreshold(self) -> float: ...
    @AngleThreshold.setter
    def AngleThreshold(self, value: float) -> None: ...
    @property
    def Bodies(self) -> SelectDisplayableObjectList: ...
    @Bodies.setter
    def Bodies(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def DecimateMethod(self) -> Facet.DecimateFacetBodyBuilder.DecimateMethodType: ...
    @DecimateMethod.setter
    def DecimateMethod(self, value: Facet.DecimateFacetBodyBuilder.DecimateMethodType) -> None: ...
    @property
    def FacetBodies(self) -> Facet.SelectFacetedBodyList: ...
    @FacetBodies.setter
    def FacetBodies(self, value: Facet.SelectFacetedBodyList) -> None: ...
    @property
    def FacetCollector(self) -> FacetCollector: ...
    @FacetCollector.setter
    def FacetCollector(self, value: FacetCollector) -> None: ...
    @property
    def IsEditCopy(self) -> bool: ...
    @IsEditCopy.setter
    def IsEditCopy(self, value: bool) -> None: ...
    @property
    def IsLockBoundary(self) -> bool: ...
    @IsLockBoundary.setter
    def IsLockBoundary(self, value: bool) -> None: ...
    @property
    def MinimumArea(self) -> float: ...
    @MinimumArea.setter
    def MinimumArea(self, value: float) -> None: ...
    @property
    def Percentage(self) -> float: ...
    @Percentage.setter
    def Percentage(self, value: float) -> None: ...
    @property
    def RegionList(self) -> GeometricUtilities.BoundaryDefinitionBuilderList: ...
    @RegionList.setter
    def RegionList(self, value: GeometricUtilities.BoundaryDefinitionBuilderList) -> None: ...
    @property
    def Tolerance(self) -> float: ...
    @Tolerance.setter
    def Tolerance(self, value: float) -> None: ...


    class DecimateMethodType(enum.Enum):
        ChordalDeviation= 0
        SmallestFacet= 1
        Percentage= 2
    

class CurvatureBuilder(Builder):
    def __init__(self) -> None: ...
    def DeleteCurvature(self) -> None: ...
    @property
    def Bodies(self) -> SelectDisplayableObjectList: ...
    @Bodies.setter
    def Bodies(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def ConcaveRadius(self) -> float: ...
    @ConcaveRadius.setter
    def ConcaveRadius(self, value: float) -> None: ...
    @property
    def ConvexRadius(self) -> float: ...
    @ConvexRadius.setter
    def ConvexRadius(self, value: float) -> None: ...
    @property
    def FacetBodies(self) -> Facet.SelectFacetedBodyList: ...
    @FacetBodies.setter
    def FacetBodies(self, value: Facet.SelectFacetedBodyList) -> None: ...
    @property
    def IsDirectionReversed(self) -> bool: ...
    @IsDirectionReversed.setter
    def IsDirectionReversed(self, value: bool) -> None: ...
    @property
    def SmoothingFactor(self) -> float: ...
    @SmoothingFactor.setter
    def SmoothingFactor(self, value: float) -> None: ...


class CreateTransitionBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Distance(self) -> Expression: ...
    @Distance.setter
    def Distance(self, value: Expression) -> None: ...
    @property
    def IsClosed(self) -> bool: ...
    @IsClosed.setter
    def IsClosed(self, value: bool) -> None: ...
    @property
    def IsEditCopy(self) -> bool: ...
    @IsEditCopy.setter
    def IsEditCopy(self, value: bool) -> None: ...
    @property
    def Radius(self) -> Expression: ...
    @Radius.setter
    def Radius(self, value: Expression) -> None: ...
    @property
    def SelectedBody(self) -> DisplayableObject: ...
    @SelectedBody.setter
    def SelectedBody(self, value: DisplayableObject) -> None: ...
    @property
    def SelectedPoints(self) -> Features.GeometricConstraintDataManager: ...
    @SelectedPoints.setter
    def SelectedPoints(self, value: Features.GeometricConstraintDataManager) -> None: ...
    @property
    def Type(self) -> Facet.CreateTransitionBuilder.Types: ...
    @Type.setter
    def Type(self, value: Facet.CreateTransitionBuilder.Types) -> None: ...


    class Types(enum.Enum):
        Round= 0
        Flat= 1
    

class ConvertFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CleanUp(self) -> bool: ...
    @CleanUp.setter
    def CleanUp(self, value: bool) -> None: ...
    @property
    def FacetedBodiesToConvert(self) -> SelectDisplayableObjectList: ...
    @FacetedBodiesToConvert.setter
    def FacetedBodiesToConvert(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def MinimumAngleFoldedFacets(self) -> float: ...
    @MinimumAngleFoldedFacets.setter
    def MinimumAngleFoldedFacets(self, value: float) -> None: ...
    @property
    def MinimumFacetNumber(self) -> int: ...
    @MinimumFacetNumber.setter
    def MinimumFacetNumber(self, value: int) -> None: ...
    @property
    def OriginalBodyOption(self) -> Facet.ConvertFacetBodyBuilder.OriginalBodyOptions: ...
    @OriginalBodyOption.setter
    def OriginalBodyOption(self, value: Facet.ConvertFacetBodyBuilder.OriginalBodyOptions) -> None: ...
    @property
    def OutputType(self) -> Facet.ConvertFacetBodyBuilder.OutputTypes: ...
    @OutputType.setter
    def OutputType(self, value: Facet.ConvertFacetBodyBuilder.OutputTypes) -> None: ...


    class OutputTypes(enum.Enum):
        ConvergentBody= 0
        NXFacetBody= 1
        JTFacetBody= 2
    

    class OriginalBodyOptions(enum.Enum):
        Keep= 0
        Hide= 1
        Delete= 2
    

class CombineFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def FacetedBodiesToCombine(self) -> SelectDisplayableObjectList: ...
    @FacetedBodiesToCombine.setter
    def FacetedBodiesToCombine(self, value: SelectDisplayableObjectList) -> None: ...


class CombineFacetBodiesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AnalyzeMeshQuality(self) -> bool: ...
    @AnalyzeMeshQuality.setter
    def AnalyzeMeshQuality(self, value: bool) -> None: ...
    @property
    def AverageFacetSize(self) -> float: ...
    @AverageFacetSize.setter
    def AverageFacetSize(self, value: float) -> None: ...
    @property
    def InputBodiesOptions(self) -> Facet.CombineFacetBodiesBuilder.InputBodiesOption: ...
    @InputBodiesOptions.setter
    def InputBodiesOptions(self, value: Facet.CombineFacetBodiesBuilder.InputBodiesOption) -> None: ...
    @property
    def InputFacetBodies(self) -> SelectNXObjectList: ...
    @InputFacetBodies.setter
    def InputFacetBodies(self, value: SelectNXObjectList) -> None: ...


    class InputBodiesOption(enum.Enum):
        Delete= 0
        Keep= 1
        Hide= 2
    

class CleanupFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    def SetAllOptionsToNone(self) -> None: ...
    def SetAllOptionsToAnalyze(self) -> None: ...
    def SetAllOptionsToRepair(self) -> None: ...
    def DisplayCleanupReportInListWindow(self) -> None: ...
    @property
    def DistanceTolerance(self) -> float: ...
    @DistanceTolerance.setter
    def DistanceTolerance(self, value: float) -> None: ...
    @property
    def FoldedEdges(self) -> Facet.CleanupFacetBodyBuilder.CleanupOptions: ...
    @FoldedEdges.setter
    def FoldedEdges(self, value: Facet.CleanupFacetBodyBuilder.CleanupOptions) -> None: ...
    @property
    def InconsistentNormals(self) -> Facet.CleanupFacetBodyBuilder.CleanupOptions: ...
    @InconsistentNormals.setter
    def InconsistentNormals(self, value: Facet.CleanupFacetBodyBuilder.CleanupOptions) -> None: ...
    @property
    def InputBodies(self) -> SelectDisplayableObjectList: ...
    @InputBodies.setter
    def InputBodies(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def LaminarSlits(self) -> Facet.CleanupFacetBodyBuilder.CleanupOptions: ...
    @LaminarSlits.setter
    def LaminarSlits(self, value: Facet.CleanupFacetBodyBuilder.CleanupOptions) -> None: ...
    @property
    def LongFacets(self) -> Facet.CleanupFacetBodyBuilder.CleanupOptions: ...
    @LongFacets.setter
    def LongFacets(self, value: Facet.CleanupFacetBodyBuilder.CleanupOptions) -> None: ...
    @property
    def MaxRatioLongFacets(self) -> float: ...
    @MaxRatioLongFacets.setter
    def MaxRatioLongFacets(self, value: float) -> None: ...
    @property
    def MinAngleFoldedFacets(self) -> float: ...
    @MinAngleFoldedFacets.setter
    def MinAngleFoldedFacets(self, value: float) -> None: ...
    @property
    def MinFacetNumberPerBody(self) -> int: ...
    @MinFacetNumberPerBody.setter
    def MinFacetNumberPerBody(self, value: int) -> None: ...
    @property
    def OriginalBodyOption(self) -> Facet.CleanupFacetBodyBuilder.OriginalBodyOptions: ...
    @OriginalBodyOption.setter
    def OriginalBodyOption(self, value: Facet.CleanupFacetBodyBuilder.OriginalBodyOptions) -> None: ...
    @property
    def SelfIntersections(self) -> Facet.CleanupFacetBodyBuilder.CleanupOptions: ...
    @SelfIntersections.setter
    def SelfIntersections(self, value: Facet.CleanupFacetBodyBuilder.CleanupOptions) -> None: ...
    @property
    def ShowInfo(self) -> bool: ...
    @ShowInfo.setter
    def ShowInfo(self, value: bool) -> None: ...
    @property
    def ThinFacets(self) -> Facet.CleanupFacetBodyBuilder.CleanupOptions: ...
    @ThinFacets.setter
    def ThinFacets(self, value: Facet.CleanupFacetBodyBuilder.CleanupOptions) -> None: ...
    @property
    def ToleranceFactor(self) -> float: ...
    @ToleranceFactor.setter
    def ToleranceFactor(self, value: float) -> None: ...


    class OriginalBodyOptions(enum.Enum):
        Keep= 0
        Hide= 1
        Delete= 2
    

    class CleanupOptions(enum.Enum):
        None_= 0
        Analyze= 1
        Repair= 2
    

class BridgeFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    def FlipRange1(self) -> None: ...
    def FlipRange2(self) -> None: ...
    @property
    def DistanceTolerance(self) -> float: ...
    @DistanceTolerance.setter
    def DistanceTolerance(self, value: float) -> None: ...
    @property
    def FacetBodyOne(self) -> Facet.SelectFacetedBody: ...
    @FacetBodyOne.setter
    def FacetBodyOne(self, value: Facet.SelectFacetedBody) -> None: ...
    @property
    def FacetBodyTwo(self) -> Facet.SelectFacetedBody: ...
    @FacetBodyTwo.setter
    def FacetBodyTwo(self, value: Facet.SelectFacetedBody) -> None: ...
    @property
    def InputStatus(self) -> Facet.BridgeFacetBodyBuilder.Input: ...
    @InputStatus.setter
    def InputStatus(self, value: Facet.BridgeFacetBodyBuilder.Input) -> None: ...
    @property
    def Smoothness(self) -> Facet.BridgeFacetBodyBuilder.SmoothTypes: ...
    @Smoothness.setter
    def Smoothness(self, value: Facet.BridgeFacetBodyBuilder.SmoothTypes) -> None: ...
    @property
    def Vertex1Range1(self) -> Point: ...
    @Vertex1Range1.setter
    def Vertex1Range1(self, value: Point) -> None: ...
    @property
    def Vertex1Range2(self) -> Point: ...
    @Vertex1Range2.setter
    def Vertex1Range2(self, value: Point) -> None: ...
    @property
    def Vertex2Range1(self) -> Point: ...
    @Vertex2Range1.setter
    def Vertex2Range1(self, value: Point) -> None: ...
    @property
    def Vertex2Range2(self) -> Point: ...
    @Vertex2Range2.setter
    def Vertex2Range2(self, value: Point) -> None: ...


    class SmoothTypes(enum.Enum):
        Linear= 0
        TangentBased= 1
    

    class Input(enum.Enum):
        Keep= 0
        Delete= 1
        Hide= 2
    

class BestFitAlignBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def DestinationObjects(self) -> SelectNXObjectList: ...
    @DestinationObjects.setter
    def DestinationObjects(self, value: SelectNXObjectList) -> None: ...
    @property
    def Direction(self) -> Direction: ...
    @Direction.setter
    def Direction(self, value: Direction) -> None: ...
    @property
    def FitConstraints(self) -> Facet.BestFitAlignBuilder.ConstraintOptions: ...
    @FitConstraints.setter
    def FitConstraints(self, value: Facet.BestFitAlignBuilder.ConstraintOptions) -> None: ...
    @property
    def GlobalSearch(self) -> bool: ...
    @GlobalSearch.setter
    def GlobalSearch(self, value: bool) -> None: ...
    @property
    def MobileObjects(self) -> SelectNXObjectList: ...
    @MobileObjects.setter
    def MobileObjects(self, value: SelectNXObjectList) -> None: ...
    @property
    def RotateCenter(self) -> Point: ...
    @RotateCenter.setter
    def RotateCenter(self, value: Point) -> None: ...
    @property
    def SourceObjects(self) -> SelectNXObjectList: ...
    @SourceObjects.setter
    def SourceObjects(self, value: SelectNXObjectList) -> None: ...


    class ConstraintOptions(enum.Enum):
        Free= 0
        OnlyTranslation= 1
        TranslationInPlane= 2
        TranslationAlongDirection= 3
        OnlyRotation= 4
        RotationAroundPoint= 5
        RotationAroundLine= 6
        HoldToPlane= 7
        HoldToLine= 8
    

class AdjustMinimumRadiusBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Facets(self) -> FacetCollector: ...
    @Facets.setter
    def Facets(self, value: FacetCollector) -> None: ...
    @property
    def IsEditCopy(self) -> bool: ...
    @IsEditCopy.setter
    def IsEditCopy(self, value: bool) -> None: ...
    @property
    def MinimumRadius(self) -> float: ...
    @MinimumRadius.setter
    def MinimumRadius(self, value: float) -> None: ...


