from ...NXOpen import *

import typing
import enum

class UserTextItem(Report.TextItem):
    def __init__(self) -> None: ...
    def SetDisplayName(self, displayName: str) -> None: ...


class UserInput(TaggedObject):
    def __init__(self) -> None: ...
    def GetHint(self, inputHint: str) -> None: ...
    def SetHint(self, inputHint: str) -> None: ...
    def FindObject(self, journalIdentifier: str) -> INXObject: ...
    def Print(self) -> None: ...
    def SetName(self, name: str) -> None: ...
    @property
    def InputType(self) -> Report.UserInput.Type: ...
    @InputType.setter
    def InputType(self, value: Report.UserInput.Type) -> None: ...
    @property
    def IsOccurrence(self) -> bool: ...
    @IsOccurrence.setter
    def IsOccurrence(self, value: bool) -> None: ...
    @property
    def JournalIdentifier(self) -> str: ...
    @JournalIdentifier.setter
    def JournalIdentifier(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def OwningComponent(self) -> Assemblies.Component: ...
    @OwningComponent.setter
    def OwningComponent(self, value: Assemblies.Component) -> None: ...
    @property
    def OwningPart(self) -> BasePart: ...
    @OwningPart.setter
    def OwningPart(self, value: BasePart) -> None: ...
    @property
    def Prototype(self) -> INXObject: ...
    @Prototype.setter
    def Prototype(self, value: INXObject) -> None: ...


    class Type(enum.Enum):
        Text= 0
        Images= 1
    

class UserImagesGroupItem(Report.ImagesGroupItem):
    def __init__(self) -> None: ...
    def SetDisplayName(self, displayName: str) -> None: ...


class TextItem(Report.BaseItem):
    def __init__(self) -> None: ...
    def GetText(self, lineTexts: str) -> None: ...
    def SetText(self, lineTexts: str) -> None: ...


class TemplateItem(Report.BaseItem):
    def __init__(self) -> None: ...
    def GetChildItems(self, itemsLocation: Report.CommandBuilder.UserInputLocation, pItems: typing.List[Report.BaseItem]) -> None: ...


class StringArgument(Report.BaseArgument):
    def __init__(self) -> None: ...
    @property
    def DefaultValue(self) -> str: ...
    @DefaultValue.setter
    def DefaultValue(self, value: str) -> None: ...


class ResultXmlFileWriter(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def AddText(self, textContent: str) -> OpenXml.TextDocumentData: ...
    def AddImageGroup(self) -> OpenXml.ImageGroupDocumentData: ...
    def AddTable(self, columnSize: int, rowSize: int) -> OpenXml.TableDocumentData: ...
    def GetDataCount(self) -> int: ...
    def GetNthData(self, index: int) -> OpenXml.DocumentData: ...
    def DeleteNthData(self, index: int) -> None: ...
    def DeleteAllData(self) -> None: ...
    def SaveToFile(self, fileName: str) -> None: ...


class ReportPreference(TaggedObject):
    def __init__(self) -> None: ...
    def SaveMemoryFile(self) -> None: ...
    @property
    def MaximumRecentReportDocumentCount(self) -> int: ...
    @MaximumRecentReportDocumentCount.setter
    def MaximumRecentReportDocumentCount(self, value: int) -> None: ...
    @property
    def OpenReportDocumentAfterExport(self) -> bool: ...
    @OpenReportDocumentAfterExport.setter
    def OpenReportDocumentAfterExport(self, value: bool) -> None: ...
    @property
    def SearchTemplateFromSiteDirectory(self) -> bool: ...
    @SearchTemplateFromSiteDirectory.setter
    def SearchTemplateFromSiteDirectory(self, value: bool) -> None: ...
    @property
    def UsePartDirectoryAsDefaultExportLocation(self) -> bool: ...
    @UsePartDirectoryAsDefaultExportLocation.setter
    def UsePartDirectoryAsDefaultExportLocation(self, value: bool) -> None: ...
    @property
    def ViewImageAfterSnapshotting(self) -> bool: ...
    @ViewImageAfterSnapshotting.setter
    def ViewImageAfterSnapshotting(self, value: bool) -> None: ...


class ReportManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def CreateResultXmlFileWriter(self) -> Report.ResultXmlFileWriter: ...
    def GetOriginalImageDimension(self, imageFullFileName: str, width: float, height: float) -> None: ...
    def Tag(self) -> Tag: ...

    @property
    def AutomationLogger(self) -> Report.AutomationLogger: ...
    @AutomationLogger.setter
    def AutomationLogger(self, value: Report.AutomationLogger) -> None: ...
    @property
    def CommandManager(self) -> Report.CommandManager: ...
    @CommandManager.setter
    def CommandManager(self, value: Report.CommandManager) -> None: ...
    @property
    def Preference(self) -> Report.ReportPreference: ...
    @Preference.setter
    def Preference(self, value: Report.ReportPreference) -> None: ...


class ReportImage(NXObject):
    def __init__(self) -> None: ...
    def SetImage(self, imageFile: str) -> None: ...
    @property
    def Caption(self) -> str: ...
    @Caption.setter
    def Caption(self, value: str) -> None: ...
    @property
    def ImageOption(self) -> Report.ImageOption: ...
    @ImageOption.setter
    def ImageOption(self, value: Report.ImageOption) -> None: ...


class Report(NXObject):
    def __init__(self) -> None: ...
    def GetTemplateItems(self, pTemplateItems: typing.List[Report.TemplateItem]) -> None: ...
    def CreateUserItem(self, inputType: Report.UserInput.Type) -> Report.IUserItem: ...
    def CopyUserItem(self, userItem: Report.IUserItem) -> Report.IUserItem: ...
    def GetUserItems(self, userItems: typing.List[Report.IUserItem]) -> None: ...
    def MoveUserItems(self, userItems: typing.List[Report.IUserItem], newLocation: Report.Report.MoveItemLocation, referencedItem: Report.IUserItem) -> None: ...
    def Export(self, reportDocument: str, listError: bool) -> None: ...
    def ClearTemplateItems(self) -> None: ...
    def DeleteUserItems(self) -> None: ...
    def HideTempalteItemsWithoutInput(self, hideTemplateItemsWithoutInput: bool) -> None: ...
    def SynchronizeWithCommands(self) -> None: ...
    @property
    def ReportCollection(self) -> Report.IReportCollection: ...
    @ReportCollection.setter
    def ReportCollection(self, value: Report.IReportCollection) -> None: ...
    @property
    def TemplateFile(self) -> str: ...
    @TemplateFile.setter
    def TemplateFile(self, value: str) -> None: ...


    class MoveItemLocation(enum.Enum):
        Before= 0
        After= 1
    

class ProgramInformation(TaggedObject):
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> INXObject: ...
    def Print(self) -> None: ...
    def SetName(self, name: str) -> None: ...
    @property
    def FunctionName(self) -> str: ...
    @FunctionName.setter
    def FunctionName(self, value: str) -> None: ...
    @property
    def Language(self) -> Report.ProgramInformation.LanguageType: ...
    @Language.setter
    def Language(self, value: Report.ProgramInformation.LanguageType) -> None: ...
    @property
    def ProgramFile(self) -> str: ...
    @ProgramFile.setter
    def ProgramFile(self, value: str) -> None: ...
    @property
    def IsOccurrence(self) -> bool: ...
    @IsOccurrence.setter
    def IsOccurrence(self, value: bool) -> None: ...
    @property
    def JournalIdentifier(self) -> str: ...
    @JournalIdentifier.setter
    def JournalIdentifier(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def OwningComponent(self) -> Assemblies.Component: ...
    @OwningComponent.setter
    def OwningComponent(self, value: Assemblies.Component) -> None: ...
    @property
    def OwningPart(self) -> BasePart: ...
    @OwningPart.setter
    def OwningPart(self, value: BasePart) -> None: ...
    @property
    def Prototype(self) -> INXObject: ...
    @Prototype.setter
    def Prototype(self, value: INXObject) -> None: ...


    class LanguageType(enum.Enum):
        None_= 0
        CPlusplus= 1
        CSharp= 2
        Vb= 3
        Java= 4
        Python= 5
    

class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class IUserItem():
    def SetDisplayName(self, displayName: str) -> None: ...


class IReportCollection():
    def CreateReport(self, templateFile: str, reportName: str, listError: bool) -> Report.Report: ...
    def GetReports(self, pReports: typing.List[Report.Report]) -> None: ...


class IntegerArgument(Report.BaseArgument):
    def __init__(self) -> None: ...
    @property
    def DefaultValue(self) -> int: ...
    @DefaultValue.setter
    def DefaultValue(self, value: int) -> None: ...
    @property
    def IncludeLowerBound(self) -> bool: ...
    @IncludeLowerBound.setter
    def IncludeLowerBound(self, value: bool) -> None: ...
    @property
    def IncludeUpperBound(self) -> bool: ...
    @IncludeUpperBound.setter
    def IncludeUpperBound(self, value: bool) -> None: ...
    @property
    def MaximumValue(self) -> int: ...
    @MaximumValue.setter
    def MaximumValue(self, value: int) -> None: ...
    @property
    def MinimumValue(self) -> int: ...
    @MinimumValue.setter
    def MinimumValue(self, value: int) -> None: ...


class ImagesGroupItem(Report.BaseItem):
    def __init__(self) -> None: ...
    def CreateImage(self, imageFile: str, displayName: str) -> Report.ReportImage: ...
    def CopyImage(self, pReportImage: Report.ReportImage) -> Report.ReportImage: ...
    def GetImages(self, pReportImages: typing.List[Report.ReportImage]) -> None: ...
    def MoveImages(self, pReportImages: typing.List[Report.ReportImage], newLocation: Report.Report.MoveItemLocation, pReferencedImage: Report.ReportImage) -> None: ...
    def DeleteImages(self) -> None: ...


class ImageOption(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def ImageHeight(self) -> float: ...
    @ImageHeight.setter
    def ImageHeight(self, value: float) -> None: ...
    @property
    def ImageRotation(self) -> float: ...
    @ImageRotation.setter
    def ImageRotation(self, value: float) -> None: ...
    @property
    def ImageWidth(self) -> float: ...
    @ImageWidth.setter
    def ImageWidth(self, value: float) -> None: ...
    @property
    def LockOriginalAspectRatio(self) -> bool: ...
    @LockOriginalAspectRatio.setter
    def LockOriginalAspectRatio(self, value: bool) -> None: ...


class EnumerationArgument(Report.BaseArgument):
    def __init__(self) -> None: ...
    def GetEnumerationOptions(self, enumerationOptions: str) -> None: ...
    def SetEnumerationOptions(self, enumerationOptions: str) -> None: ...
    @property
    def DefaultValue(self) -> int: ...
    @DefaultValue.setter
    def DefaultValue(self, value: int) -> None: ...


class DoubleArgument(Report.BaseArgument):
    def __init__(self) -> None: ...
    @property
    def DefaultValue(self) -> float: ...
    @DefaultValue.setter
    def DefaultValue(self, value: float) -> None: ...
    @property
    def IncludeLowerBound(self) -> bool: ...
    @IncludeLowerBound.setter
    def IncludeLowerBound(self, value: bool) -> None: ...
    @property
    def IncludeUpperBound(self) -> bool: ...
    @IncludeUpperBound.setter
    def IncludeUpperBound(self, value: bool) -> None: ...
    @property
    def MaximumValue(self) -> float: ...
    @MaximumValue.setter
    def MaximumValue(self, value: float) -> None: ...
    @property
    def MimimumValue(self) -> float: ...
    @MimimumValue.setter
    def MimimumValue(self, value: float) -> None: ...


class CommandManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Report.ReportManager) -> None: ...
    def ExportCommandsToLibraryFile(self, pCommands: typing.List[Report.Command], libraryFile: str) -> None: ...
    def GetCommandLibraries(self, pCommandLibraries: typing.List[Report.CommandLibrary]) -> None: ...
    def CreateCommandBuilder(self, commandLibrary: Report.CommandLibrary, command: Report.Command) -> Report.CommandBuilder: ...
    def NewCommandImporter(self, pCommandLibrary: Report.CommandLibrary, libraryFile: str) -> Report.CommandImporter: ...
    def Find(self, journalIdentifier: str) -> TaggedObject: ...
    def Tag(self) -> Tag: ...



class CommandLibrary(TaggedObject):
    def __init__(self) -> None: ...
    def GetCommands(self, pCommands: typing.List[Report.Command]) -> None: ...
    def Save(self) -> None: ...
    def MoveCommands(self, pCommand: typing.List[Report.Command], newLocation: Report.CommandLibrary.MoveCommandLocation, pReferenceCommand: Report.Command) -> None: ...
    def FindObject(self, journalIdentifier: str) -> INXObject: ...
    def Print(self) -> None: ...
    def SetName(self, name: str) -> None: ...
    @property
    def IsOccurrence(self) -> bool: ...
    @IsOccurrence.setter
    def IsOccurrence(self, value: bool) -> None: ...
    @property
    def JournalIdentifier(self) -> str: ...
    @JournalIdentifier.setter
    def JournalIdentifier(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def OwningComponent(self) -> Assemblies.Component: ...
    @OwningComponent.setter
    def OwningComponent(self, value: Assemblies.Component) -> None: ...
    @property
    def OwningPart(self) -> BasePart: ...
    @OwningPart.setter
    def OwningPart(self, value: BasePart) -> None: ...
    @property
    def Prototype(self) -> INXObject: ...
    @Prototype.setter
    def Prototype(self, value: INXObject) -> None: ...


    class MoveCommandLocation(enum.Enum):
        Before= 0
        After= 1
    

class CommandImporter(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def GetImportCandidates(self, pCommands: typing.List[Report.Command]) -> None: ...
    def ImportCommands(self, pCommandIndexes: int) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def ImportOption(self) -> Report.CommandImporter.OverrideOption: ...
    @ImportOption.setter
    def ImportOption(self, value: Report.CommandImporter.OverrideOption) -> None: ...


    class OverrideOption(enum.Enum):
        Ignore= 0
        Replace= 1
        Copy= 2
    

class CommandBuilder(Builder):
    def __init__(self) -> None: ...
    def GetHint(self, commandHint: str) -> None: ...
    def SetHint(self, commandHint: str) -> None: ...
    def SetNamespaces(self, pNamespaces: str) -> None: ...
    def GetNamespaces(self, pNamespaces: str) -> None: ...
    def AddArgument(self, argumentType: Report.BaseArgument.Type) -> Report.BaseArgument: ...
    def GetArguments(self, pArguments: typing.List[Report.BaseArgument]) -> None: ...
    def RemoveArguments(self, pArguments: typing.List[Report.BaseArgument]) -> None: ...
    def AddUserInput(self, userInputLocation: Report.CommandBuilder.UserInputLocation, userInputType: Report.UserInput.Type) -> Report.UserInput: ...
    def GetUserInputs(self, userInputLocation: Report.CommandBuilder.UserInputLocation, pUserInputs: typing.List[Report.UserInput]) -> None: ...
    def RemoveUserInputs(self, userInputLocation: Report.CommandBuilder.UserInputLocation, pUserInputs: typing.List[Report.UserInput]) -> None: ...
    def MoveUserInputs(self, userInputLocation: Report.CommandBuilder.UserInputLocation, pUserInputs: typing.List[Report.UserInput], isBeforeRefUserInput: bool, pRefUserInputs: Report.UserInput) -> None: ...
    @property
    def Active(self) -> bool: ...
    @Active.setter
    def Active(self, value: bool) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def ProgramInformation(self) -> Report.ProgramInformation: ...
    @ProgramInformation.setter
    def ProgramInformation(self, value: Report.ProgramInformation) -> None: ...


    class UserInputLocation(enum.Enum):
        BeforeAutomation= 0
        AfterAutomation= 1
    

class Command(NXObject):
    def __init__(self) -> None: ...
    def Delete(self) -> None: ...


class BaseItem(NXObject):
    def __init__(self) -> None: ...
    def Clear(self) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> None: ...
    @property
    def Hint(self) -> str: ...
    @Hint.setter
    def Hint(self, value: str) -> None: ...


class BaseArgument(TaggedObject):
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> INXObject: ...
    def Print(self) -> None: ...
    def SetName(self, name: str) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> None: ...
    @property
    def Hint(self) -> str: ...
    @Hint.setter
    def Hint(self, value: str) -> None: ...
    @property
    def Optional(self) -> bool: ...
    @Optional.setter
    def Optional(self, value: bool) -> None: ...
    @property
    def IsOccurrence(self) -> bool: ...
    @IsOccurrence.setter
    def IsOccurrence(self, value: bool) -> None: ...
    @property
    def JournalIdentifier(self) -> str: ...
    @JournalIdentifier.setter
    def JournalIdentifier(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def OwningComponent(self) -> Assemblies.Component: ...
    @OwningComponent.setter
    def OwningComponent(self, value: Assemblies.Component) -> None: ...
    @property
    def OwningPart(self) -> BasePart: ...
    @OwningPart.setter
    def OwningPart(self, value: BasePart) -> None: ...
    @property
    def Prototype(self) -> INXObject: ...
    @Prototype.setter
    def Prototype(self, value: INXObject) -> None: ...


    class Type(enum.Enum):
        Integer= 0
        Double= 1
        String= 2
        Enumeration= 3
    

class AutomationLogger(Utilities.NXRemotableObject):
    def __init__(self, owner: Report.ReportManager) -> None: ...
    @typing.overload
    def LogMessage(self, message: str) -> None: ...
    @typing.overload
    def LogMessage(self, message: str, messageType: Report.AutomationLogger.MessageType) -> None: ...
    def Clear(self) -> None: ...
    def SaveLog(self, logFileName: str) -> None: ...
    def IsEmpty(self) -> bool: ...
    def Tag(self) -> Tag: ...



    class MessageType(enum.Enum):
        Empty= 0
        Information= 1
        Debug= 2
        Exception= 3
    

