from ...NXOpen import *

import typing
import enum

class PasteBuilder(Builder):
    def __init__(self) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MassValueBuilder(Builder):
    def __init__(self) -> None: ...
    def GetMassValues(self) -> None: ...
    def UpdateMassValueSource(self, valueType: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    def UpdateDensityValueSource(self, valueType: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    def UpdateVolumeValueSource(self, valueType: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    @property
    def Area(self) -> Gateway.MassValueBuilder.ValueSourceType: ...
    @Area.setter
    def Area(self, value: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    @property
    def AssignRolledUpAttribute(self) -> bool: ...
    @AssignRolledUpAttribute.setter
    def AssignRolledUpAttribute(self, value: bool) -> None: ...
    @property
    def Density(self) -> Gateway.MassValueBuilder.ValueSourceType: ...
    @Density.setter
    def Density(self, value: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    @property
    def DeriveOption(self) -> int: ...
    @DeriveOption.setter
    def DeriveOption(self, value: int) -> None: ...
    @property
    def GravityCenterX(self) -> Gateway.MassValueBuilder.ValueSourceType: ...
    @GravityCenterX.setter
    def GravityCenterX(self, value: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    @property
    def GravityCenterY(self) -> Gateway.MassValueBuilder.ValueSourceType: ...
    @GravityCenterY.setter
    def GravityCenterY(self, value: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    @property
    def GravityCenterZ(self) -> Gateway.MassValueBuilder.ValueSourceType: ...
    @GravityCenterZ.setter
    def GravityCenterZ(self, value: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    @property
    def InertiaXX(self) -> Gateway.MassValueBuilder.ValueSourceType: ...
    @InertiaXX.setter
    def InertiaXX(self, value: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    @property
    def InertiaXY(self) -> Gateway.MassValueBuilder.ValueSourceType: ...
    @InertiaXY.setter
    def InertiaXY(self, value: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    @property
    def InertiaXZ(self) -> Gateway.MassValueBuilder.ValueSourceType: ...
    @InertiaXZ.setter
    def InertiaXZ(self, value: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    @property
    def InertiaYY(self) -> Gateway.MassValueBuilder.ValueSourceType: ...
    @InertiaYY.setter
    def InertiaYY(self, value: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    @property
    def InertiaYZ(self) -> Gateway.MassValueBuilder.ValueSourceType: ...
    @InertiaYZ.setter
    def InertiaYZ(self, value: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    @property
    def InertiaZZ(self) -> Gateway.MassValueBuilder.ValueSourceType: ...
    @InertiaZZ.setter
    def InertiaZZ(self, value: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    @property
    def Mass(self) -> Gateway.MassValueBuilder.ValueSourceType: ...
    @Mass.setter
    def Mass(self, value: Gateway.MassValueBuilder.ValueSourceType) -> None: ...
    @property
    def MassType(self) -> Gateway.MassValueBuilder.MassTypes: ...
    @MassType.setter
    def MassType(self, value: Gateway.MassValueBuilder.MassTypes) -> None: ...
    @property
    def Objects(self) -> SelectNXObjectList: ...
    @Objects.setter
    def Objects(self, value: SelectNXObjectList) -> None: ...
    @property
    def Volume(self) -> Gateway.MassValueBuilder.ValueSourceType: ...
    @Volume.setter
    def Volume(self, value: Gateway.MassValueBuilder.ValueSourceType) -> None: ...


    class ValueSourceType(enum.Enum):
        Unset= 0
        Computed= 1
        Asserted= 2
        UserDefined1= 3
        UserDefined2= 4
        UserDefined3= 5
        UserDefined4= 6
        ComputedCoated= 7
    

    class MassTypes(enum.Enum):
        Unset= 0
        MassOnly= 1
        DensityOnly= 2
        VolumeOnly= 3
        DensityMass= 4
        DensityVolume= 5
        MassVolume= 6
        AssertAll= 7
    

class MassPropertyOptionsBuilder(Builder):
    def __init__(self) -> None: ...
    def GetSourceHierarchy(self, variableSources: int) -> None: ...
    def SetSourceHierarchy(self, variableSources: int) -> None: ...
    @property
    def AccuracyType(self) -> Gateway.MassPropertyOptionsBuilder.AccuracyTypes: ...
    @AccuracyType.setter
    def AccuracyType(self, value: Gateway.MassPropertyOptionsBuilder.AccuracyTypes) -> None: ...
    @property
    def ComponentGroupName(self) -> str: ...
    @ComponentGroupName.setter
    def ComponentGroupName(self, value: str) -> None: ...
    @property
    def MarkerColorOfAllComponents(self) -> int: ...
    @MarkerColorOfAllComponents.setter
    def MarkerColorOfAllComponents(self, value: int) -> None: ...
    @property
    def MarkerColorOfDisplayedPart(self) -> int: ...
    @MarkerColorOfDisplayedPart.setter
    def MarkerColorOfDisplayedPart(self, value: int) -> None: ...
    @property
    def MarkerColorOfSelectedComponentSet(self) -> int: ...
    @MarkerColorOfSelectedComponentSet.setter
    def MarkerColorOfSelectedComponentSet(self, value: int) -> None: ...
    @property
    def MarkerColorOfSelectedComponents(self) -> int: ...
    @MarkerColorOfSelectedComponents.setter
    def MarkerColorOfSelectedComponents(self, value: int) -> None: ...
    @property
    def UseAllComponents(self) -> bool: ...
    @UseAllComponents.setter
    def UseAllComponents(self, value: bool) -> None: ...
    @property
    def UseDisplayedPart(self) -> bool: ...
    @UseDisplayedPart.setter
    def UseDisplayedPart(self, value: bool) -> None: ...
    @property
    def UseSelectedComponentSet(self) -> bool: ...
    @UseSelectedComponentSet.setter
    def UseSelectedComponentSet(self, value: bool) -> None: ...
    @property
    def UseSelectedComponents(self) -> bool: ...
    @UseSelectedComponents.setter
    def UseSelectedComponents(self, value: bool) -> None: ...
    @property
    def UseSourceHierarchy(self) -> bool: ...
    @UseSourceHierarchy.setter
    def UseSourceHierarchy(self, value: bool) -> None: ...


    class AccuracyTypes(enum.Enum):
        Value1= 0
        Value2= 1
        Value3= 2
        Value4= 3
        Value5= 4
        Value6= 5
    

class MassPartSpecificOptionsBuilder(Builder):
    def __init__(self) -> None: ...
    def RemovePartSpecificSetting(self) -> None: ...
    @property
    def ReferenceSetName(self) -> str: ...
    @ReferenceSetName.setter
    def ReferenceSetName(self, value: str) -> None: ...


class MassLimitationBuilder(Builder):
    def __init__(self) -> None: ...
    def GetLimitationValues(self) -> None: ...
    @property
    def MaximumArea(self) -> Expression: ...
    @MaximumArea.setter
    def MaximumArea(self, value: Expression) -> None: ...
    @property
    def MaximumAreaStatus(self) -> bool: ...
    @MaximumAreaStatus.setter
    def MaximumAreaStatus(self, value: bool) -> None: ...
    @property
    def MaximumDensity(self) -> Expression: ...
    @MaximumDensity.setter
    def MaximumDensity(self, value: Expression) -> None: ...
    @property
    def MaximumDensityStatus(self) -> bool: ...
    @MaximumDensityStatus.setter
    def MaximumDensityStatus(self, value: bool) -> None: ...
    @property
    def MaximumGravityCenterStatusX(self) -> bool: ...
    @MaximumGravityCenterStatusX.setter
    def MaximumGravityCenterStatusX(self, value: bool) -> None: ...
    @property
    def MaximumGravityCenterStatusY(self) -> bool: ...
    @MaximumGravityCenterStatusY.setter
    def MaximumGravityCenterStatusY(self, value: bool) -> None: ...
    @property
    def MaximumGravityCenterStatusZ(self) -> bool: ...
    @MaximumGravityCenterStatusZ.setter
    def MaximumGravityCenterStatusZ(self, value: bool) -> None: ...
    @property
    def MaximumGravityCenterX(self) -> Expression: ...
    @MaximumGravityCenterX.setter
    def MaximumGravityCenterX(self, value: Expression) -> None: ...
    @property
    def MaximumGravityCenterY(self) -> Expression: ...
    @MaximumGravityCenterY.setter
    def MaximumGravityCenterY(self, value: Expression) -> None: ...
    @property
    def MaximumGravityCenterZ(self) -> Expression: ...
    @MaximumGravityCenterZ.setter
    def MaximumGravityCenterZ(self, value: Expression) -> None: ...
    @property
    def MaximumMass(self) -> Expression: ...
    @MaximumMass.setter
    def MaximumMass(self, value: Expression) -> None: ...
    @property
    def MaximumMassStatus(self) -> bool: ...
    @MaximumMassStatus.setter
    def MaximumMassStatus(self, value: bool) -> None: ...
    @property
    def MaximumMomentsInertiaStatusXX(self) -> bool: ...
    @MaximumMomentsInertiaStatusXX.setter
    def MaximumMomentsInertiaStatusXX(self, value: bool) -> None: ...
    @property
    def MaximumMomentsInertiaStatusYY(self) -> bool: ...
    @MaximumMomentsInertiaStatusYY.setter
    def MaximumMomentsInertiaStatusYY(self, value: bool) -> None: ...
    @property
    def MaximumMomentsInertiaStatusZZ(self) -> bool: ...
    @MaximumMomentsInertiaStatusZZ.setter
    def MaximumMomentsInertiaStatusZZ(self, value: bool) -> None: ...
    @property
    def MaximumMomentsInertiaXX(self) -> Expression: ...
    @MaximumMomentsInertiaXX.setter
    def MaximumMomentsInertiaXX(self, value: Expression) -> None: ...
    @property
    def MaximumMomentsInertiaYY(self) -> Expression: ...
    @MaximumMomentsInertiaYY.setter
    def MaximumMomentsInertiaYY(self, value: Expression) -> None: ...
    @property
    def MaximumMomentsInertiaZZ(self) -> Expression: ...
    @MaximumMomentsInertiaZZ.setter
    def MaximumMomentsInertiaZZ(self, value: Expression) -> None: ...
    @property
    def MaximumProductsInertiaStatusXY(self) -> bool: ...
    @MaximumProductsInertiaStatusXY.setter
    def MaximumProductsInertiaStatusXY(self, value: bool) -> None: ...
    @property
    def MaximumProductsInertiaStatusXZ(self) -> bool: ...
    @MaximumProductsInertiaStatusXZ.setter
    def MaximumProductsInertiaStatusXZ(self, value: bool) -> None: ...
    @property
    def MaximumProductsInertiaStatusYZ(self) -> bool: ...
    @MaximumProductsInertiaStatusYZ.setter
    def MaximumProductsInertiaStatusYZ(self, value: bool) -> None: ...
    @property
    def MaximumProductsInertiaXY(self) -> Expression: ...
    @MaximumProductsInertiaXY.setter
    def MaximumProductsInertiaXY(self, value: Expression) -> None: ...
    @property
    def MaximumProductsInertiaXZ(self) -> Expression: ...
    @MaximumProductsInertiaXZ.setter
    def MaximumProductsInertiaXZ(self, value: Expression) -> None: ...
    @property
    def MaximumProductsInertiaYZ(self) -> Expression: ...
    @MaximumProductsInertiaYZ.setter
    def MaximumProductsInertiaYZ(self, value: Expression) -> None: ...
    @property
    def MaximumVolume(self) -> Expression: ...
    @MaximumVolume.setter
    def MaximumVolume(self, value: Expression) -> None: ...
    @property
    def MaximumVolumeStatus(self) -> bool: ...
    @MaximumVolumeStatus.setter
    def MaximumVolumeStatus(self, value: bool) -> None: ...
    @property
    def MinimumArea(self) -> Expression: ...
    @MinimumArea.setter
    def MinimumArea(self, value: Expression) -> None: ...
    @property
    def MinimumAreaStatus(self) -> bool: ...
    @MinimumAreaStatus.setter
    def MinimumAreaStatus(self, value: bool) -> None: ...
    @property
    def MinimumDensity(self) -> Expression: ...
    @MinimumDensity.setter
    def MinimumDensity(self, value: Expression) -> None: ...
    @property
    def MinimumDensityStatus(self) -> bool: ...
    @MinimumDensityStatus.setter
    def MinimumDensityStatus(self, value: bool) -> None: ...
    @property
    def MinimumGravityCenterStatusX(self) -> bool: ...
    @MinimumGravityCenterStatusX.setter
    def MinimumGravityCenterStatusX(self, value: bool) -> None: ...
    @property
    def MinimumGravityCenterStatusY(self) -> bool: ...
    @MinimumGravityCenterStatusY.setter
    def MinimumGravityCenterStatusY(self, value: bool) -> None: ...
    @property
    def MinimumGravityCenterStatusZ(self) -> bool: ...
    @MinimumGravityCenterStatusZ.setter
    def MinimumGravityCenterStatusZ(self, value: bool) -> None: ...
    @property
    def MinimumGravityCenterX(self) -> Expression: ...
    @MinimumGravityCenterX.setter
    def MinimumGravityCenterX(self, value: Expression) -> None: ...
    @property
    def MinimumGravityCenterY(self) -> Expression: ...
    @MinimumGravityCenterY.setter
    def MinimumGravityCenterY(self, value: Expression) -> None: ...
    @property
    def MinimumGravityCenterZ(self) -> Expression: ...
    @MinimumGravityCenterZ.setter
    def MinimumGravityCenterZ(self, value: Expression) -> None: ...
    @property
    def MinimumMass(self) -> Expression: ...
    @MinimumMass.setter
    def MinimumMass(self, value: Expression) -> None: ...
    @property
    def MinimumMassStatus(self) -> bool: ...
    @MinimumMassStatus.setter
    def MinimumMassStatus(self, value: bool) -> None: ...
    @property
    def MinimumMomentsInertiaStatusXX(self) -> bool: ...
    @MinimumMomentsInertiaStatusXX.setter
    def MinimumMomentsInertiaStatusXX(self, value: bool) -> None: ...
    @property
    def MinimumMomentsInertiaStatusYY(self) -> bool: ...
    @MinimumMomentsInertiaStatusYY.setter
    def MinimumMomentsInertiaStatusYY(self, value: bool) -> None: ...
    @property
    def MinimumMomentsInertiaStatusZZ(self) -> bool: ...
    @MinimumMomentsInertiaStatusZZ.setter
    def MinimumMomentsInertiaStatusZZ(self, value: bool) -> None: ...
    @property
    def MinimumMomentsInertiaXX(self) -> Expression: ...
    @MinimumMomentsInertiaXX.setter
    def MinimumMomentsInertiaXX(self, value: Expression) -> None: ...
    @property
    def MinimumMomentsInertiaYY(self) -> Expression: ...
    @MinimumMomentsInertiaYY.setter
    def MinimumMomentsInertiaYY(self, value: Expression) -> None: ...
    @property
    def MinimumMomentsInertiaZZ(self) -> Expression: ...
    @MinimumMomentsInertiaZZ.setter
    def MinimumMomentsInertiaZZ(self, value: Expression) -> None: ...
    @property
    def MinimumProductsInertiaStatusXY(self) -> bool: ...
    @MinimumProductsInertiaStatusXY.setter
    def MinimumProductsInertiaStatusXY(self, value: bool) -> None: ...
    @property
    def MinimumProductsInertiaStatusXZ(self) -> bool: ...
    @MinimumProductsInertiaStatusXZ.setter
    def MinimumProductsInertiaStatusXZ(self, value: bool) -> None: ...
    @property
    def MinimumProductsInertiaStatusYZ(self) -> bool: ...
    @MinimumProductsInertiaStatusYZ.setter
    def MinimumProductsInertiaStatusYZ(self, value: bool) -> None: ...
    @property
    def MinimumProductsInertiaXY(self) -> Expression: ...
    @MinimumProductsInertiaXY.setter
    def MinimumProductsInertiaXY(self, value: Expression) -> None: ...
    @property
    def MinimumProductsInertiaXZ(self) -> Expression: ...
    @MinimumProductsInertiaXZ.setter
    def MinimumProductsInertiaXZ(self, value: Expression) -> None: ...
    @property
    def MinimumProductsInertiaYZ(self) -> Expression: ...
    @MinimumProductsInertiaYZ.setter
    def MinimumProductsInertiaYZ(self, value: Expression) -> None: ...
    @property
    def MinimumVolume(self) -> Expression: ...
    @MinimumVolume.setter
    def MinimumVolume(self, value: Expression) -> None: ...
    @property
    def MinimumVolumeStatus(self) -> bool: ...
    @MinimumVolumeStatus.setter
    def MinimumVolumeStatus(self, value: bool) -> None: ...
    @property
    def Objects(self) -> SelectNXObjectList: ...
    @Objects.setter
    def Objects(self, value: SelectNXObjectList) -> None: ...


class MassExportBuilder(Builder):
    def __init__(self) -> None: ...
    def LoadSystemDefault(self) -> None: ...
    def SaveAsDefault(self) -> None: ...
    def RestoreDefault(self) -> None: ...
    def SaveToFile(self, fileName: str) -> None: ...
    def OpenFromFile(self, fileName: str) -> None: ...
    def SetToggleState(self, nodeType: Gateway.MassExportBuilder.NodeType, nodeId: int, state: bool) -> None: ...
    def MoveUp(self, nodeType: Gateway.MassExportBuilder.NodeType, nodeId: int) -> None: ...
    def MoveDown(self, nodeType: Gateway.MassExportBuilder.NodeType, nodeId: int) -> None: ...
    @property
    def DataMode(self) -> Gateway.MassExportBuilder.DataModes: ...
    @DataMode.setter
    def DataMode(self, value: Gateway.MassExportBuilder.DataModes) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...
    @property
    def Objects(self) -> SelectNXObjectList: ...
    @Objects.setter
    def Objects(self, value: SelectNXObjectList) -> None: ...
    @property
    def Output(self) -> Gateway.MassExportBuilder.OutputTypes: ...
    @Output.setter
    def Output(self, value: Gateway.MassExportBuilder.OutputTypes) -> None: ...
    @property
    def TemplateFileName(self) -> str: ...
    @TemplateFileName.setter
    def TemplateFileName(self, value: str) -> None: ...
    @property
    def UseLegacyLayoutForXLSX(self) -> bool: ...
    @UseLegacyLayoutForXLSX.setter
    def UseLegacyLayoutForXLSX(self, value: bool) -> None: ...


    class PerComponentResult(enum.Enum):
        ComponentName= 0
        ObjectDisplayName= 1
        ItemID= 2
        ItemName= 3
        ItemRevision= 4
        FileName= 5
        DescriptivePartName= 6
        ParentName= 7
        Count= 8
    

    class PerBodyResult(enum.Enum):
        BodyName= 0
        Count= 1
    

    class OverallResult(enum.Enum):
        Density= 0
        DensitySource= 1
        Area= 2
        AreaSource= 3
        Volume= 4
        VolumeSource= 5
        Mass= 6
        MassSource= 7
        Weight= 8
        WeightSource= 9
        CenterOfMassWCS= 10
        CenterOfMassAbsolute= 11
        CenterOfMassSource= 12
        FirstMomentsWCS= 13
        MomentsOfInertiaWCS= 14
        MomentsOfInertiaCentroidal= 15
        MomentsOfInertiaCentroidalSource= 16
        MomentsOfInertiaSpherical= 17
        ProductsOfInertiaWCS= 18
        ProductsOfInertiaCentroidal= 19
        ProductsOfInertiaCentroidalSource= 20
        PrincipalMomentsOfInertia= 21
        RadiiOfGyrationWCS= 22
        RadiiOfGyrationCentroidal= 23
        RadiiOfGyrationSpherical= 24
        PrincipalAxisWCS= 25
        EstimatedErrorRanges= 26
        Warnings= 27
        Count= 28
    

    class OutputTypes(enum.Enum):
        Information= 0
        Xlsx= 1
        Csv= 2
        Xml= 3
        Json= 4
    

    class NodeType(enum.Enum):
        ComponentHeader= 2
        BodyHeader= 3
        PerComponentResult= 4
        PerBodyResult= 5
        OverallResult= 6
    

    class DataModes(enum.Enum):
        AssemblyOnly= 0
        IncludeChildren= 1
        Solid= 2
    

    class ComponentHeader(enum.Enum):
        SourcePrecedence= 0
        ReferenceSetPrecedence= 1
        ReferenceSetUsed= 2
        ComponentGroup= 3
        Arrangement= 4
        Accuracy= 5
        Coating= 6
        Count= 7
    

    class BodyHeader(enum.Enum):
        SourcePrecedence= 0
        ReferenceSetUsed= 1
        Accuracy= 2
        Count= 3
    

class MassCollection(Utilities.NXRemotableObject):
    def __init__(self, owner: PropertiesManager) -> None: ...
    def CreateCalculationBuilder(self, componentTags: typing.List[NXObject]) -> Gateway.MassCalculationBuilder: ...
    def CreateAssignmentBuilder(self, componentTag: NXObject) -> Gateway.MassAssignmentBuilder: ...
    def CreateLimitationBuilder(self, componentTag: NXObject) -> Gateway.MassLimitationBuilder: ...
    def CreateValueBuilder(self, componentTag: NXObject) -> Gateway.MassValueBuilder: ...
    def CreatePropertyOptionsBuilder(self) -> Gateway.MassPropertyOptionsBuilder: ...
    def CreatePartSpecificOptionsBuilder(self) -> Gateway.MassPartSpecificOptionsBuilder: ...
    def CreateExportBuilder(self, componentTags: typing.List[NXObject]) -> Gateway.MassExportBuilder: ...
    def Tag(self) -> Tag: ...



class MassCalculationBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def ComponentGroupName(self) -> str: ...
    @ComponentGroupName.setter
    def ComponentGroupName(self, value: str) -> None: ...
    @property
    def IncludeChildren(self) -> bool: ...
    @IncludeChildren.setter
    def IncludeChildren(self, value: bool) -> None: ...
    @property
    def Objects(self) -> SelectNXObjectList: ...
    @Objects.setter
    def Objects(self, value: SelectNXObjectList) -> None: ...


class MassAssignmentBuilder(Builder):
    def __init__(self) -> None: ...
    def GetAssignmentValues(self) -> None: ...
    @property
    def Area(self) -> Expression: ...
    @Area.setter
    def Area(self, value: Expression) -> None: ...
    @property
    def AreaStatus(self) -> bool: ...
    @AreaStatus.setter
    def AreaStatus(self, value: bool) -> None: ...
    @property
    def AssignmentStatus(self) -> bool: ...
    @AssignmentStatus.setter
    def AssignmentStatus(self, value: bool) -> None: ...
    @property
    def Density(self) -> Expression: ...
    @Density.setter
    def Density(self, value: Expression) -> None: ...
    @property
    def DensityStatus(self) -> bool: ...
    @DensityStatus.setter
    def DensityStatus(self, value: bool) -> None: ...
    @property
    def DeriveOption(self) -> int: ...
    @DeriveOption.setter
    def DeriveOption(self, value: int) -> None: ...
    @property
    def GravityCenterStatus(self) -> bool: ...
    @GravityCenterStatus.setter
    def GravityCenterStatus(self, value: bool) -> None: ...
    @property
    def GravityCenterX(self) -> Expression: ...
    @GravityCenterX.setter
    def GravityCenterX(self, value: Expression) -> None: ...
    @property
    def GravityCenterY(self) -> Expression: ...
    @GravityCenterY.setter
    def GravityCenterY(self, value: Expression) -> None: ...
    @property
    def GravityCenterZ(self) -> Expression: ...
    @GravityCenterZ.setter
    def GravityCenterZ(self, value: Expression) -> None: ...
    @property
    def InertiaStatus(self) -> bool: ...
    @InertiaStatus.setter
    def InertiaStatus(self, value: bool) -> None: ...
    @property
    def Mass(self) -> Expression: ...
    @Mass.setter
    def Mass(self, value: Expression) -> None: ...
    @property
    def MassStatus(self) -> bool: ...
    @MassStatus.setter
    def MassStatus(self, value: bool) -> None: ...
    @property
    def MassType(self) -> Gateway.MassAssignmentBuilder.MassTypes: ...
    @MassType.setter
    def MassType(self, value: Gateway.MassAssignmentBuilder.MassTypes) -> None: ...
    @property
    def MomentsInertiaXX(self) -> Expression: ...
    @MomentsInertiaXX.setter
    def MomentsInertiaXX(self, value: Expression) -> None: ...
    @property
    def MomentsInertiaYY(self) -> Expression: ...
    @MomentsInertiaYY.setter
    def MomentsInertiaYY(self, value: Expression) -> None: ...
    @property
    def MomentsInertiaZZ(self) -> Expression: ...
    @MomentsInertiaZZ.setter
    def MomentsInertiaZZ(self, value: Expression) -> None: ...
    @property
    def Objects(self) -> SelectNXObjectList: ...
    @Objects.setter
    def Objects(self, value: SelectNXObjectList) -> None: ...
    @property
    def ProductsInertiaXY(self) -> Expression: ...
    @ProductsInertiaXY.setter
    def ProductsInertiaXY(self, value: Expression) -> None: ...
    @property
    def ProductsInertiaXZ(self) -> Expression: ...
    @ProductsInertiaXZ.setter
    def ProductsInertiaXZ(self, value: Expression) -> None: ...
    @property
    def ProductsInertiaYZ(self) -> Expression: ...
    @ProductsInertiaYZ.setter
    def ProductsInertiaYZ(self, value: Expression) -> None: ...
    @property
    def ValueType(self) -> Gateway.MassAssignmentBuilder.ValueTypes: ...
    @ValueType.setter
    def ValueType(self, value: Gateway.MassAssignmentBuilder.ValueTypes) -> None: ...
    @property
    def Volume(self) -> Expression: ...
    @Volume.setter
    def Volume(self, value: Expression) -> None: ...
    @property
    def VolumeStatus(self) -> bool: ...
    @VolumeStatus.setter
    def VolumeStatus(self, value: bool) -> None: ...


    class ValueTypes(enum.Enum):
        Asserted= 0
        UserDefined1= 1
        UserDefined2= 2
        UserDefined3= 3
        UserDefined4= 4
    

    class MassTypes(enum.Enum):
        MassOnly= 0
        DensityMass= 1
        DensityVolume= 2
        MassVolume= 3
    

class ImageExportBuilder(Builder):
    def __init__(self) -> None: ...
    def GetRegionTopLeftPoint(self) -> int: ...
    def SetRegionTopLeftPoint(self, regionTopLeftPoint: int) -> None: ...
    def GetCustomBackgroundColor(self) -> float: ...
    def SetCustomBackgroundColor(self, customBackgroundColor: float) -> None: ...
    @property
    def BackgroundOption(self) -> Gateway.ImageExportBuilder.BackgroundOptions: ...
    @BackgroundOption.setter
    def BackgroundOption(self, value: Gateway.ImageExportBuilder.BackgroundOptions) -> None: ...
    @property
    def EnhanceEdges(self) -> bool: ...
    @EnhanceEdges.setter
    def EnhanceEdges(self, value: bool) -> None: ...
    @property
    def FileFormat(self) -> Gateway.ImageExportBuilder.FileFormats: ...
    @FileFormat.setter
    def FileFormat(self, value: Gateway.ImageExportBuilder.FileFormats) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...
    @property
    def RegionHeight(self) -> int: ...
    @RegionHeight.setter
    def RegionHeight(self, value: int) -> None: ...
    @property
    def RegionMode(self) -> bool: ...
    @RegionMode.setter
    def RegionMode(self, value: bool) -> None: ...
    @property
    def RegionWidth(self) -> int: ...
    @RegionWidth.setter
    def RegionWidth(self, value: int) -> None: ...


    class FileFormats(enum.Enum):
        Png= 0
        Jpg= 1
        Gif= 2
        Tiff= 3
        Bmp= 4
        Xwd= 5
    

    class BackgroundOptions(enum.Enum):
        Original= 0
        CustomColor= 1
        Transparent= 2
    

class ImageCaptureManager(Utilities.NXRemotableObject):
    def __init__(self, owner: BasePart) -> None: ...
    def CreateImageCaptureBuilder(self) -> Gateway.ImageCaptureBuilder: ...
    def Tag(self) -> Tag: ...



class ImageCaptureBuilder(Builder):
    def __init__(self) -> None: ...
    def GetRegion(self, topLeftCorner: int, bottomRightCorner: int) -> None: ...
    def SetRegion(self, topLeftCorner: int, bottomRightCorner: int) -> None: ...
    @property
    def CaptureMethod(self) -> Gateway.ImageCaptureBuilder.CaptureMethodType: ...
    @CaptureMethod.setter
    def CaptureMethod(self, value: Gateway.ImageCaptureBuilder.CaptureMethodType) -> None: ...
    @property
    def File(self) -> str: ...
    @File.setter
    def File(self, value: str) -> None: ...
    @property
    def Format(self) -> Gateway.ImageCaptureBuilder.ImageFormat: ...
    @Format.setter
    def Format(self, value: Gateway.ImageCaptureBuilder.ImageFormat) -> None: ...
    @property
    def ImageFile(self) -> str: ...
    @ImageFile.setter
    def ImageFile(self, value: str) -> None: ...
    @property
    def Size(self) -> Gateway.ImageCaptureBuilder.ImageSize: ...
    @Size.setter
    def Size(self, value: Gateway.ImageCaptureBuilder.ImageSize) -> None: ...


    class ImageSize(enum.Enum):
        Pixels16= 0
        Pixels24= 1
        Pixels32= 2
        Pixels48= 3
        Pixels64= 4
        Pixels96= 5
        Pixels128= 6
    

    class ImageFormat(enum.Enum):
        Bmp= 0
        Jpg= 1
        Gif= 2
        Png= 3
        Tiff= 4
    

    class CaptureMethodType(enum.Enum):
        GraphicsArea= 0
        Region= 1
        File= 2
        Automatic= 3
    

class IGenericFileNewApplicationBuilder(Builder):
    def __init__(self) -> None: ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList: ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList: ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject: ...


class GenericFileNewBuilder(Builder):
    def __init__(self) -> None: ...
    def CreateLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    def SetApplicationBuilder(self, applicationBuilder: Gateway.IGenericFileNewApplicationBuilder) -> None: ...


class CopyCutBuilder(Builder):
    def __init__(self) -> None: ...
    def GetCopyCutStatus(self) -> Gateway.CopyCutBuilder.Status: ...
    def GetNonExportableObjects(self) -> typing.List[NXObject]: ...
    def GetObjects(self) -> typing.List[NXObject]: ...
    def SetObjects(self, objects: typing.List[NXObject]) -> None: ...
    def ResetInitialCopyLocation(self) -> None: ...
    @property
    def CanCopyAsSketch(self) -> bool: ...
    @CanCopyAsSketch.setter
    def CanCopyAsSketch(self, value: bool) -> None: ...
    @property
    def DestinationFilename(self) -> str: ...
    @DestinationFilename.setter
    def DestinationFilename(self, value: str) -> None: ...
    @property
    def InitialCopyLocation(self) -> Point3d: ...
    @InitialCopyLocation.setter
    def InitialCopyLocation(self, value: Point3d) -> None: ...
    @property
    def IsCut(self) -> bool: ...
    @IsCut.setter
    def IsCut(self, value: bool) -> None: ...
    @property
    def ToClipboard(self) -> bool: ...
    @ToClipboard.setter
    def ToClipboard(self, value: bool) -> None: ...


    class Status(enum.Enum):
        NoObjectsCopied= 0
        NonExportableObjects= 1
        PartExportFailed= 2
        ErrorDuringCut= 3
        AllObjectsCopied= 4
    

class BookmarkFile(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def SaveWithDescription(self, pathName: str, bookmarkOption: BasePart.BookmarkOption, description: str) -> None: ...
    def Rename(self, oldPathName: str, newFileName: str, okToOverwriteExistingFile: bool) -> str: ...
    def SetDescription(self, pathName: str, description: str) -> None: ...
    def Delete(self, pathName: str) -> None: ...
    def Tag(self) -> Tag: ...



class BaseExplicitOrderBuilder(Builder):
    def __init__(self) -> None: ...
    def Save(self, orderList: str, saveName: str) -> None: ...
    def Paste(self, pastePoint: int, selectedEntries: str, currentOrder: str) -> str: ...
    def Delete(self, selectedEntries: str, currentOrder: str, numOfRemainingEntries: int) -> str: ...
    def Clear(self) -> None: ...
    def DownArrow(self, selectedEntries: str, currentOrder: str) -> str: ...
    def UpArrow(self, selectedEntries: str, currentOrder: str) -> str: ...
    def SaveAsTextFile(self, savedOrderName: str, saveFileName: str, overwriteFile: bool) -> None: ...
    @property
    def SaveName(self) -> str: ...
    @SaveName.setter
    def SaveName(self, value: str) -> None: ...


