from ...NXOpen import *

import typing
import enum

class SymbolSaveBuilder(Builder):
    def __init__(self) -> None: ...
    def GetDescription(self) -> str: ...
    def SetDescription(self, text: str) -> None: ...
    @property
    def FolderPath(self) -> str: ...
    @FolderPath.setter
    def FolderPath(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...


class SymbolPortBuilder(Builder):
    def __init__(self) -> None: ...
    def GetPortObject(self) -> DiagrammingLibraryAuthor.AttributeHolder: ...
    def SetLocation(self, portLocation: Point2d) -> None: ...
    def GetLocation(self) -> Point2d: ...
    def SetConnectionDirection(self, connectionDirection: Point2d) -> None: ...
    def GetConnectionDirection(self) -> Point2d: ...
    def SetPortID(self, portID: str) -> None: ...
    def GetPortID(self) -> str: ...
    def SetDirection(self, portDirection: str) -> None: ...
    def GetDirection(self) -> str: ...


class SymbolDesignerManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetSymbolDesignerManager(self, owner: Session) -> DiagrammingLibraryAuthor.SymbolDesignerManager: ...
    def CreateSymbolPart(self, symbolName: str) -> Part: ...
    def OpenSymbolPart(self, partSpec: str) -> Part: ...
    def CreateSymbolSaveBuilder(self, part: Part) -> DiagrammingLibraryAuthor.SymbolSaveBuilder: ...
    def CreateSymbolPortBuilder(self, part: Part, portID: str) -> DiagrammingLibraryAuthor.SymbolPortBuilder: ...
    def CreateSymbolBuilder(self, part: Part) -> DiagrammingLibraryAuthor.SymbolBuilder: ...
    def Tag(self) -> Tag: ...



class SymbolBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AnchorPoint(self) -> Point2d: ...
    @AnchorPoint.setter
    def AnchorPoint(self, value: Point2d) -> None: ...
    @property
    def TagLocation(self) -> Point2d: ...
    @TagLocation.setter
    def TagLocation(self, value: Point2d) -> None: ...


class Symbol3DBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def PortMappingData(self) -> ITableEditorDataProvider: ...
    @PortMappingData.setter
    def PortMappingData(self, value: ITableEditorDataProvider) -> None: ...


class Symbol2DBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def CreateFromSymbol(self, symbolId: str) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def AnchorPoint(self) -> Point2d: ...
    @AnchorPoint.setter
    def AnchorPoint(self, value: Point2d) -> None: ...
    @property
    def DraftingSymbol(self) -> Tooling.SelectReuseLibraryItemBuilder: ...
    @DraftingSymbol.setter
    def DraftingSymbol(self, value: Tooling.SelectReuseLibraryItemBuilder) -> None: ...
    @property
    def EnableScale(self) -> bool: ...
    @EnableScale.setter
    def EnableScale(self, value: bool) -> None: ...
    @property
    def Image(self) -> Gateway.ImageCaptureBuilder: ...
    @Image.setter
    def Image(self, value: Gateway.ImageCaptureBuilder) -> None: ...
    @property
    def IsInline(self) -> bool: ...
    @IsInline.setter
    def IsInline(self, value: bool) -> None: ...
    @property
    def PortData(self) -> DiagrammingLibraryAuthor.PortDataBuilder: ...
    @PortData.setter
    def PortData(self, value: DiagrammingLibraryAuthor.PortDataBuilder) -> None: ...
    @property
    def PrefixLetters(self) -> str: ...
    @PrefixLetters.setter
    def PrefixLetters(self, value: str) -> None: ...
    @property
    def TagLocation(self) -> Point2d: ...
    @TagLocation.setter
    def TagLocation(self, value: Point2d) -> None: ...


class PortDataBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def GetPortObjects(self, portObjects: typing.List[DiagrammingLibraryAuthor.AttributeHolder]) -> None: ...
    def GetPointLocation(self, portObject: DiagrammingLibraryAuthor.AttributeHolder) -> Point2d: ...
    def SetPointLocation(self, portObject: DiagrammingLibraryAuthor.AttributeHolder, portLocation: Point2d) -> None: ...
    def GetConnectionDirection(self, portObject: DiagrammingLibraryAuthor.AttributeHolder) -> Point2d: ...
    def SetConnectionDirection(self, portObject: DiagrammingLibraryAuthor.AttributeHolder, connectionDirection: Point2d) -> None: ...
    def CreatePort(self) -> DiagrammingLibraryAuthor.AttributeHolder: ...
    def DeletePort(self, portObject: DiagrammingLibraryAuthor.AttributeHolder) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def NozzleBottom(self) -> bool: ...
    @NozzleBottom.setter
    def NozzleBottom(self, value: bool) -> None: ...
    @property
    def NozzleLeft(self) -> bool: ...
    @NozzleLeft.setter
    def NozzleLeft(self, value: bool) -> None: ...
    @property
    def NozzleRight(self) -> bool: ...
    @NozzleRight.setter
    def NozzleRight(self, value: bool) -> None: ...
    @property
    def NozzleTop(self) -> bool: ...
    @NozzleTop.setter
    def NozzleTop(self, value: bool) -> None: ...


class PipeStockBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def SelectFolder(self, classId: str) -> None: ...
    def SelectPipeStock(self, symbolId: str) -> None: ...
    def GetPipeStockObjects(self, pipeStockObjects: typing.List[DiagrammingLibraryAuthor.AttributeHolder]) -> None: ...
    def CreatePipeStock(self, instanceId: str, partId: str, partName: str, numberName: str) -> DiagrammingLibraryAuthor.AttributeHolder: ...
    def DeletePipeStock(self, pipeStockObject: DiagrammingLibraryAuthor.AttributeHolder) -> None: ...
    def Validate(self) -> bool: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class LineTypeBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[DiagrammingLibraryAuthor.LineTypeBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: DiagrammingLibraryAuthor.LineTypeBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: DiagrammingLibraryAuthor.LineTypeBuilder) -> int: ...
    def FindItem(self, index: int) -> DiagrammingLibraryAuthor.LineTypeBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: DiagrammingLibraryAuthor.LineTypeBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: DiagrammingLibraryAuthor.LineTypeBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[DiagrammingLibraryAuthor.LineTypeBuilder]: ...
    def SetContents(self, objects: typing.List[DiagrammingLibraryAuthor.LineTypeBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: DiagrammingLibraryAuthor.LineTypeBuilder, object2: DiagrammingLibraryAuthor.LineTypeBuilder) -> None: ...
    def Insert(self, location: int, object: DiagrammingLibraryAuthor.LineTypeBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class LineTypeBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def LineColor(self) -> NXColor: ...
    @LineColor.setter
    def LineColor(self, value: NXColor) -> None: ...
    @property
    def LineFont(self) -> DisplayableObject.ObjectFont: ...
    @LineFont.setter
    def LineFont(self, value: DisplayableObject.ObjectFont) -> None: ...
    @property
    def LineTypeName(self) -> str: ...
    @LineTypeName.setter
    def LineTypeName(self, value: str) -> None: ...
    @property
    def LineTypePriority(self) -> int: ...
    @LineTypePriority.setter
    def LineTypePriority(self, value: int) -> None: ...
    @property
    def LineWidth(self) -> DisplayableObject.ObjectWidth: ...
    @LineWidth.setter
    def LineWidth(self, value: DisplayableObject.ObjectWidth) -> None: ...
    @property
    def ObjectId(self) -> str: ...
    @ObjectId.setter
    def ObjectId(self, value: str) -> None: ...


class AttributeHolder(NXObject):
    def __init__(self) -> None: ...


