from ...NXOpen import *

import typing
import enum

class Positioner(NXObject):
    def __init__(self) -> None: ...
    @typing.overload
    def CreateConstraint(self, persistent: bool) -> Positioning.Constraint: ...
    @typing.overload
    def CreateConstraint(self) -> Positioning.Constraint: ...
    def EstablishNetwork(self) -> Positioning.Network: ...
    def ClearNetwork(self) -> None: ...
    def DeleteNonPersistentConstraints(self) -> None: ...
    @property
    def Constraints(self) -> Positioning.ConstraintCollection: ...
    @Constraints.setter
    def Constraints(self, value: Positioning.ConstraintCollection) -> None: ...


class Network(NXObject):
    def __init__(self) -> None: ...
    def AddConstraint(self, constraint: Positioning.Constraint) -> None: ...
    def RemoveConstraint(self, constraint: Positioning.Constraint) -> None: ...
    def RemoveAllConstraints(self) -> None: ...
    def AddMovableObject(self, movableObject: NXObject) -> None: ...
    def RemoveMovableObject(self, movableObject: NXObject) -> None: ...
    def ApplyToModel(self) -> None: ...
    def Solve(self) -> None: ...
    def ResetDisplay(self) -> None: ...
    def GetMovableObjectStatus(self, movableObject: NXObject) -> Positioning.Network.ObjectStatus: ...
    def BeginDrag(self) -> None: ...
    def DragByRay(self, point: Point3d, direction: Vector3d) -> None: ...
    def DragByTransform(self, translation: Vector3d, rotation: Matrix3x3) -> None: ...
    def DragByTranslation(self, translation: Vector3d) -> None: ...
    def EndDrag(self) -> None: ...
    def SetMovingGroup(self, movableObjects: typing.List[NXObject]) -> None: ...
    def EmptyMovingGroup(self) -> None: ...
    def IsReferencedGeometryLoaded(self) -> bool: ...
    def LoadReferencedGeometry(self) -> None: ...
    @property
    def DisplayComponent(self) -> Assemblies.Component: ...
    @DisplayComponent.setter
    def DisplayComponent(self, value: Assemblies.Component) -> None: ...
    @property
    def MoveObjectsState(self) -> bool: ...
    @MoveObjectsState.setter
    def MoveObjectsState(self, value: bool) -> None: ...
    @property
    def NonMovingGroupGrounded(self) -> bool: ...
    @NonMovingGroupGrounded.setter
    def NonMovingGroupGrounded(self, value: bool) -> None: ...


    class ObjectStatus(enum.Enum):
        Unknown= 0
        Fixed= 1
        OverDefined= 2
        NotConsistentDims= 3
        NotConsistentOther= 4
        NotConsistentUnknown= 5
        NotChanged= 6
        WellDefined= 7
        UnderDefined= 8
    

class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MatingConverter(TaggedObject):
    def __init__(self) -> None: ...
    def ConvertMatingConditions(self) -> None: ...
    def GetConvertedConstraints(self) -> typing.List[Positioning.Constraint]: ...
    def GetConvertedParts(self) -> typing.List[Positioning.Constraint]: ...
    def GetLatestResults(self, showAllResults: bool) -> str: ...
    def GetResults(self, showAllResults: bool) -> str: ...
    def DeleteResults(self) -> None: ...
    def Destroy(self) -> None: ...
    @property
    def Context(self) -> Positioning.MatingConverter.PartContext: ...
    @Context.setter
    def Context(self, value: Positioning.MatingConverter.PartContext) -> None: ...
    @property
    def LoadReferencedGeometry(self) -> bool: ...
    @LoadReferencedGeometry.setter
    def LoadReferencedGeometry(self, value: bool) -> None: ...
    @property
    def LoadStatus(self) -> PartLoadStatus: ...
    @LoadStatus.setter
    def LoadStatus(self, value: PartLoadStatus) -> None: ...
    @property
    def NumberOfConvertedParts(self) -> int: ...
    @NumberOfConvertedParts.setter
    def NumberOfConvertedParts(self, value: int) -> None: ...


    class PartContext(enum.Enum):
        InOwningPart= 0
        InLoadedChildren= 1
        InAllChildren= 2
    

class DisplayedConstraintCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Positioning.DisplayedConstraint]: ...
    @typing.overload
    def __init__(self, owner: Part) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def Tag(self) -> Tag: ...



class DisplayedConstraint(DisplayableObject):
    def __init__(self) -> None: ...
    def GetConstraint(self) -> Positioning.Constraint: ...
    def GetConstraintPart(self) -> Part: ...
    def GetContextComponent(self) -> Assemblies.Component: ...


class ConstraintReference(NXObject):
    def __init__(self) -> None: ...
    def GetGeometry(self) -> NXObject: ...
    def GetPrototypeGeometry(self) -> NXObject: ...
    def GetMovableObject(self) -> NXObject: ...
    def GetUsesGeometryAxis(self) -> bool: ...
    def SetFixHint(self, set: bool) -> None: ...
    def SetFixHintForUpdate(self, set: bool) -> None: ...
    def GetUsePortRotate(self) -> bool: ...
    def GetHasPerpendicularVector(self) -> bool: ...
    def GetPrototypePerpendicularVector(self) -> Vector3d: ...
    def SetPrototypePerpendicularVector(self, perpendicularVector: Vector3d) -> None: ...
    @property
    def ConstraintReferenceHalfSpace(self) -> Positioning.ConstraintReference.HalfSpace: ...
    @ConstraintReferenceHalfSpace.setter
    def ConstraintReferenceHalfSpace(self, value: Positioning.ConstraintReference.HalfSpace) -> None: ...
    @property
    def GeometryDirectionReversed(self) -> bool: ...
    @GeometryDirectionReversed.setter
    def GeometryDirectionReversed(self, value: bool) -> None: ...
    @property
    def HelpPoint(self) -> Point3d: ...
    @HelpPoint.setter
    def HelpPoint(self, value: Point3d) -> None: ...
    @property
    def Order(self) -> Positioning.ConstraintReference.ConstraintOrder: ...
    @Order.setter
    def Order(self, value: Positioning.ConstraintReference.ConstraintOrder) -> None: ...
    @property
    def SolverGeometryType(self) -> Positioning.ConstraintReference.GeometryType: ...
    @SolverGeometryType.setter
    def SolverGeometryType(self, value: Positioning.ConstraintReference.GeometryType) -> None: ...
    @property
    def UsePortRotateFlag(self) -> bool: ...
    @UsePortRotateFlag.setter
    def UsePortRotateFlag(self, value: bool) -> None: ...


    class HalfSpace(enum.Enum):
        Infer= 0
        Positive= 1
        Negative= 2
    

    class GeometryType(enum.Enum):
        Unknown= -1
        Point= 0
        Line= 1
        Circle= 2
        Plane= 3
        Cylinder= 4
        Sphere= 5
        SweepSurface= 6
        ParametricSurface= 7
        ParametricCurve= 8
        SplineCurve= 9
        Torus= 10
        Cone= 11
        Ellipse= 12
        SplineSurface= 13
        CoordinateSystem= 1001
    

    class ConstraintOrder(enum.Enum):
        Unknown= 0
        Inside= 1
        Outside= 2
    

class ConstraintCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Positioning.Constraint]: ...
    @typing.overload
    def __init__(self, owner: Positioning.Positioner) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def Tag(self) -> Tag: ...



class Constraint(NXObject):
    def __init__(self) -> None: ...
    def GetReferences(self) -> typing.List[Positioning.ConstraintReference]: ...
    def DeleteConstraintReference(self, constraintReference: Positioning.ConstraintReference) -> None: ...
    @typing.overload
    def CreateConstraintReference(self, movableObject: NXObject, geometry: NXObject, usesAxis: bool, isIndirect: bool) -> Positioning.ConstraintReference: ...
    @typing.overload
    def CreateConstraintReference(self, movableObject: NXObject, geometry: NXObject, usesAxis: bool, isIndirect: bool, usePortRotate: bool) -> Positioning.ConstraintReference: ...
    def EditConstraintReference(self, constraintReference: Positioning.ConstraintReference, movableObject: NXObject, geometry: NXObject, usesAxis: bool, isIndirect: bool, usePortRotate: bool) -> None: ...
    def FlipAlignment(self) -> None: ...
    def SetExpression(self, expression: str) -> None: ...
    def GetConstraintStatus(self) -> Positioning.Constraint.SolverStatus: ...
    def SetAlignmentHint(self, alignment: Positioning.Constraint.Alignment) -> None: ...
    def GenerateConversionReport(self, lines: str) -> None: ...
    def ReverseDirection(self) -> None: ...
    def GetDisplayedConstraint(self) -> Positioning.DisplayedConstraint: ...
    def Renew(self) -> None: ...
    def CreateCouplerReference(self, coupledConstraint: NXObject) -> Positioning.ConstraintReference: ...
    def EditCouplerReference(self, couplerReference: Positioning.ConstraintReference, coupledConstraint: NXObject) -> None: ...
    @property
    def Automatic(self) -> bool: ...
    @Automatic.setter
    def Automatic(self, value: bool) -> None: ...
    @property
    def ConstraintAlignment(self) -> Positioning.Constraint.Alignment: ...
    @ConstraintAlignment.setter
    def ConstraintAlignment(self, value: Positioning.Constraint.Alignment) -> None: ...
    @property
    def ConstraintSecondAlignment(self) -> Positioning.Constraint.Alignment: ...
    @ConstraintSecondAlignment.setter
    def ConstraintSecondAlignment(self, value: Positioning.Constraint.Alignment) -> None: ...
    @property
    def ConstraintType(self) -> Positioning.Constraint.Type: ...
    @ConstraintType.setter
    def ConstraintType(self, value: Positioning.Constraint.Type) -> None: ...
    @property
    def Expression(self) -> Expression: ...
    @Expression.setter
    def Expression(self, value: Expression) -> None: ...
    @property
    def ExpressionDriven(self) -> bool: ...
    @ExpressionDriven.setter
    def ExpressionDriven(self, value: bool) -> None: ...
    @property
    def LowerLimitEnabled(self) -> bool: ...
    @LowerLimitEnabled.setter
    def LowerLimitEnabled(self, value: bool) -> None: ...
    @property
    def LowerLimitExpression(self) -> Expression: ...
    @LowerLimitExpression.setter
    def LowerLimitExpression(self, value: Expression) -> None: ...
    @property
    def LowerLimitRightHandSide(self) -> str: ...
    @LowerLimitRightHandSide.setter
    def LowerLimitRightHandSide(self, value: str) -> None: ...
    @property
    def OffsetExpression(self) -> Expression: ...
    @OffsetExpression.setter
    def OffsetExpression(self, value: Expression) -> None: ...
    @property
    def OffsetRightHandSide(self) -> str: ...
    @OffsetRightHandSide.setter
    def OffsetRightHandSide(self, value: str) -> None: ...
    @property
    def Persistent(self) -> bool: ...
    @Persistent.setter
    def Persistent(self, value: bool) -> None: ...
    @property
    def SecondExpression(self) -> Expression: ...
    @SecondExpression.setter
    def SecondExpression(self, value: Expression) -> None: ...
    @property
    def SecondExpressionDriven(self) -> bool: ...
    @SecondExpressionDriven.setter
    def SecondExpressionDriven(self, value: bool) -> None: ...
    @property
    def SecondExpressionRightHandSide(self) -> str: ...
    @SecondExpressionRightHandSide.setter
    def SecondExpressionRightHandSide(self, value: str) -> None: ...
    @property
    def SecondLowerLimitEnabled(self) -> bool: ...
    @SecondLowerLimitEnabled.setter
    def SecondLowerLimitEnabled(self, value: bool) -> None: ...
    @property
    def SecondLowerLimitExpression(self) -> Expression: ...
    @SecondLowerLimitExpression.setter
    def SecondLowerLimitExpression(self, value: Expression) -> None: ...
    @property
    def SecondLowerLimitRightHandSide(self) -> str: ...
    @SecondLowerLimitRightHandSide.setter
    def SecondLowerLimitRightHandSide(self, value: str) -> None: ...
    @property
    def SecondUpperLimitEnabled(self) -> bool: ...
    @SecondUpperLimitEnabled.setter
    def SecondUpperLimitEnabled(self, value: bool) -> None: ...
    @property
    def SecondUpperLimitExpression(self) -> Expression: ...
    @SecondUpperLimitExpression.setter
    def SecondUpperLimitExpression(self, value: Expression) -> None: ...
    @property
    def SecondUpperLimitRightHandSide(self) -> str: ...
    @SecondUpperLimitRightHandSide.setter
    def SecondUpperLimitRightHandSide(self, value: str) -> None: ...
    @property
    def SplinePointsType(self) -> Positioning.Constraint.SplineType: ...
    @SplinePointsType.setter
    def SplinePointsType(self, value: Positioning.Constraint.SplineType) -> None: ...
    @property
    def Suppressed(self) -> bool: ...
    @Suppressed.setter
    def Suppressed(self, value: bool) -> None: ...
    @property
    def UpperLimitEnabled(self) -> bool: ...
    @UpperLimitEnabled.setter
    def UpperLimitEnabled(self, value: bool) -> None: ...
    @property
    def UpperLimitExpression(self) -> Expression: ...
    @UpperLimitExpression.setter
    def UpperLimitExpression(self, value: Expression) -> None: ...
    @property
    def UpperLimitRightHandSide(self) -> str: ...
    @UpperLimitRightHandSide.setter
    def UpperLimitRightHandSide(self, value: str) -> None: ...


    class Type(enum.Enum):
        Undefined= 0
        Touch= 1
        Concentric= 2
        Fix= 3
        Distance= 4
        Parallel= 5
        Perpendicular= 6
        Center12= 7
        Center22= 8
        Angle= 9
        Fit= 10
        Bond= 11
        OrientAngle= 12
        SplineData= 13
        SplineLength= 14
        LinearPattern= 15
        CircularPattern= 16
        Linear2dPattern= 17
        RadiantPattern= 18
        AlignLock= 19
        CommonOffsetTransform= 20
        Hinge= 21
        Slider= 22
        Cylindrical= 23
        Ball= 24
        Screw= 25
        Gear= 26
        RackPinion= 27
        Cable= 28
    

    class SplineType(enum.Enum):
        ByPoles= 0
        ByPoints= 1
        Invalid= 2
    

    class SolverStatus(enum.Enum):
        NewlyCreated= 0
        Suppressed= 1
        OutOfDate= 2
        OverConstrained= 3
        NotConsistentDims= 4
        NotConsistentOther= 5
        NotConsistentUnknown= 6
        BetweenFixed= 7
        NotSolved= 8
        Solved= 9
        CannotSolve= 10
        Delayed= 11
        IgnoredInArrangement= 12
        InternallyInconsistent= 13
        UnloadedGeometry= 14
        PendingConvertedMc= 15
        ConflictingWithWave= 16
        InconsistentLimits= 17
        BeyondLimits= 18
    

    class Alignment(enum.Enum):
        InferAlign= 0
        CoAlign= 1
        ContraAlign= 2
    

class ComponentPositioner(Positioning.Positioner):
    def __init__(self) -> None: ...
    def BeginMoveComponent(self) -> None: ...
    def EndMoveComponent(self) -> None: ...
    def BeginAssemblyConstraints(self) -> None: ...
    def EndAssemblyConstraints(self) -> None: ...
    def BeginMoveComponentInWorkset(self) -> None: ...
    def EndMoveComponentInWorkset(self) -> None: ...
    def LoadConstraintGeometry(self, constraints: typing.List[Positioning.ComponentConstraint]) -> None: ...
    def SolvePostponedConstraints(self) -> None: ...
    @property
    def DisplayConstraints(self) -> bool: ...
    @DisplayConstraints.setter
    def DisplayConstraints(self, value: bool) -> None: ...
    @property
    def DisplaySuppressedConstraints(self) -> bool: ...
    @DisplaySuppressedConstraints.setter
    def DisplaySuppressedConstraints(self, value: bool) -> None: ...
    @property
    def MoveDumbGeometry(self) -> bool: ...
    @MoveDumbGeometry.setter
    def MoveDumbGeometry(self, value: bool) -> None: ...
    @property
    def PrimaryArrangement(self) -> Assemblies.Arrangement: ...
    @PrimaryArrangement.setter
    def PrimaryArrangement(self, value: Assemblies.Arrangement) -> None: ...


class ComponentNetwork(Positioning.Network):
    def __init__(self) -> None: ...
    @property
    def NetworkArrangementsMode(self) -> Positioning.ComponentNetwork.ArrangementsMode: ...
    @NetworkArrangementsMode.setter
    def NetworkArrangementsMode(self, value: Positioning.ComponentNetwork.ArrangementsMode) -> None: ...
    @property
    def NetworkSolveInWorksetMode(self) -> bool: ...
    @NetworkSolveInWorksetMode.setter
    def NetworkSolveInWorksetMode(self, value: bool) -> None: ...


    class ArrangementsMode(enum.Enum):
        Existing= 0
        InUsed= 1
    

class ComponentConstraintGroupBuilder(Builder):
    def __init__(self) -> None: ...
    def GetContextComponent(self) -> Assemblies.Component: ...
    @property
    def ConstraintCollectionType(self) -> Positioning.ComponentConstraintGroup.ConstraintsCollectionType: ...
    @ConstraintCollectionType.setter
    def ConstraintCollectionType(self, value: Positioning.ComponentConstraintGroup.ConstraintsCollectionType) -> None: ...
    @property
    def ConstraintGroupName(self) -> str: ...
    @ConstraintGroupName.setter
    def ConstraintGroupName(self, value: str) -> None: ...
    @property
    def RememberComponentState(self) -> bool: ...
    @RememberComponentState.setter
    def RememberComponentState(self, value: bool) -> None: ...
    @property
    def SelectedComponentList(self) -> SelectDisplayableObjectList: ...
    @SelectedComponentList.setter
    def SelectedComponentList(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def SelectedConstraintsList(self) -> SelectDisplayableObjectList: ...
    @SelectedConstraintsList.setter
    def SelectedConstraintsList(self, value: SelectDisplayableObjectList) -> None: ...


class ComponentConstraintGroup(NXObject):
    def __init__(self) -> None: ...
    def GetMemberConstraints(self) -> typing.List[Positioning.ComponentConstraint]: ...
    def GetDefiningConstraints(self) -> typing.List[Positioning.ComponentConstraint]: ...
    def SetDefiningConstraints(self, constraints: typing.List[Positioning.ComponentConstraint]) -> None: ...
    def GetDefiningComponents(self) -> typing.List[Assemblies.Component]: ...
    def SetDefiningComponents(self, constraints: typing.List[Assemblies.Component]) -> None: ...
    def GetConstraintCollectionType(self) -> Positioning.ComponentConstraintGroup.ConstraintsCollectionType: ...
    def SetConstraintCollectionType(self, constraintCollectionType: Positioning.ComponentConstraintGroup.ConstraintsCollectionType) -> None: ...
    def GetRememberComponentState(self) -> bool: ...
    def SetRememberComponentState(self, rememberComponentState: bool) -> None: ...
    def UpdateMemberConstraints(self) -> bool: ...


    class ConstraintsCollectionType(enum.Enum):
        BetweenSelectedComponents= 0
        ConnectedToSelectedComponents= 1
    

class ComponentConstraint(Positioning.Constraint):
    def __init__(self) -> None: ...
    def RememberOnComponent(self, component: Assemblies.Component) -> None: ...
    def GetSpecificInArrangement(self, arrangement: Assemblies.Arrangement) -> bool: ...
    def SetSpecificInArrangement(self, arrangement: Assemblies.Arrangement, arrangementSpecific: bool) -> None: ...
    def GetSuppressedInArrangement(self, arrangement: Assemblies.Arrangement) -> bool: ...
    def SetSuppressedInArrangement(self, arrangement: Assemblies.Arrangement, suppressed: bool) -> None: ...
    def GetSharedSuppressed(self) -> bool: ...
    def SetSharedSuppressed(self, suppressed: bool) -> None: ...
    def GetInherited(self) -> bool: ...
    def GetDirectionToFixed(self, component: Assemblies.Component, arrangement: Assemblies.Arrangement) -> Positioning.ComponentConstraint.DirectionToFixed: ...
    def CopyToOverride(self) -> None: ...
    def CopyInheritedToOverride(self) -> Positioning.ComponentConstraint: ...
    def GetSeparateSuppression(self) -> bool: ...
    def SetSeparateSuppression(self, separateSuppression: bool) -> None: ...
    @property
    def ArrangementSpecific(self) -> bool: ...
    @ArrangementSpecific.setter
    def ArrangementSpecific(self, value: bool) -> None: ...


    class DirectionToFixed(enum.Enum):
        Unknown= -1
        Toward= 0
        AwayFrom= 1
        NothingFixed= 2
        Fix= 3
        Suppressed= 4
        IgnoredInArrangement= 5
    

