from .....NXOpen import *
from ....Features import *
from ...ShipDesign import *

import typing
import enum

class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class FaceCharacteristicsBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CharacteristicColor(self) -> NXColor: ...
    @CharacteristicColor.setter
    def CharacteristicColor(self, value: NXColor) -> None: ...
    @property
    def CharacteristicValue(self) -> int: ...
    @CharacteristicValue.setter
    def CharacteristicValue(self, value: int) -> None: ...
    @property
    def SelectFace(self) -> ScCollector: ...
    @SelectFace.setter
    def SelectFace(self, value: ScCollector) -> None: ...


class EvacuationPlanBuilder(Builder):
    def __init__(self) -> None: ...
    def ClearExpressionsData(self) -> None: ...
    def AddExpressionData(self, strTitle: str, strFormular: str) -> None: ...
    @property
    def Angle(self) -> Expression: ...
    @Angle.setter
    def Angle(self, value: Expression) -> None: ...
    @property
    def Color(self) -> int: ...
    @Color.setter
    def Color(self, value: int) -> None: ...
    @property
    def HorizontalFlip(self) -> bool: ...
    @HorizontalFlip.setter
    def HorizontalFlip(self, value: bool) -> None: ...
    @property
    def Origin(self) -> Annotations.OriginBuilder: ...
    @Origin.setter
    def Origin(self, value: Annotations.OriginBuilder) -> None: ...
    @property
    def Pattern(self) -> int: ...
    @Pattern.setter
    def Pattern(self, value: int) -> None: ...
    @property
    def Scale(self) -> Expression: ...
    @Scale.setter
    def Scale(self, value: Expression) -> None: ...
    @property
    def Style(self) -> Annotations.StyleBuilder: ...
    @Style.setter
    def Style(self, value: Annotations.StyleBuilder) -> None: ...
    @property
    def VerticalFlip(self) -> bool: ...
    @VerticalFlip.setter
    def VerticalFlip(self, value: bool) -> None: ...


class DrawingViewItemBuilder(Features.ShipDesign.GeneralArrangement.DrawingItemBuilder):
    def __init__(self) -> None: ...
    @property
    def HorizontalFrameBarPosition(self) -> Features.ShipDesign.GeneralArrangement.DrawingViewItemBuilder.FrameBarPositionType: ...
    @HorizontalFrameBarPosition.setter
    def HorizontalFrameBarPosition(self, value: Features.ShipDesign.GeneralArrangement.DrawingViewItemBuilder.FrameBarPositionType) -> None: ...
    @property
    def ShowFireAndSafetyPlanSymbol(self) -> bool: ...
    @ShowFireAndSafetyPlanSymbol.setter
    def ShowFireAndSafetyPlanSymbol(self, value: bool) -> None: ...
    @property
    def ShowHorizontalFrameBar(self) -> bool: ...
    @ShowHorizontalFrameBar.setter
    def ShowHorizontalFrameBar(self, value: bool) -> None: ...
    @property
    def ShowOpeningFillingLine(self) -> bool: ...
    @ShowOpeningFillingLine.setter
    def ShowOpeningFillingLine(self, value: bool) -> None: ...
    @property
    def ShowOverallDimension(self) -> bool: ...
    @ShowOverallDimension.setter
    def ShowOverallDimension(self, value: bool) -> None: ...
    @property
    def ShowPMILabel(self) -> bool: ...
    @ShowPMILabel.setter
    def ShowPMILabel(self, value: bool) -> None: ...
    @property
    def ShowVerticalFrameBar(self) -> bool: ...
    @ShowVerticalFrameBar.setter
    def ShowVerticalFrameBar(self, value: bool) -> None: ...
    @property
    def VerticalFrameBarPosition(self) -> Features.ShipDesign.GeneralArrangement.DrawingViewItemBuilder.FrameBarPositionType: ...
    @VerticalFrameBarPosition.setter
    def VerticalFrameBarPosition(self, value: Features.ShipDesign.GeneralArrangement.DrawingViewItemBuilder.FrameBarPositionType) -> None: ...


    class FrameBarPositionType(enum.Enum):
        ViewTop= 0
        ViewCenterY= 1
        ViewBottom= 2
        ViewLeft= 3
        ViewCenterX= 4
        ViewRight= 5
    

class DrawingTableItemBuilder(Features.ShipDesign.GeneralArrangement.DrawingItemBuilder):
    def __init__(self) -> None: ...


class DrawingItemBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[Features.ShipDesign.GeneralArrangement.DrawingItemBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: Features.ShipDesign.GeneralArrangement.DrawingItemBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: Features.ShipDesign.GeneralArrangement.DrawingItemBuilder) -> int: ...
    def FindItem(self, index: int) -> Features.ShipDesign.GeneralArrangement.DrawingItemBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: Features.ShipDesign.GeneralArrangement.DrawingItemBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: Features.ShipDesign.GeneralArrangement.DrawingItemBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[Features.ShipDesign.GeneralArrangement.DrawingItemBuilder]: ...
    def SetContents(self, objects: typing.List[Features.ShipDesign.GeneralArrangement.DrawingItemBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: Features.ShipDesign.GeneralArrangement.DrawingItemBuilder, object2: Features.ShipDesign.GeneralArrangement.DrawingItemBuilder) -> None: ...
    def Insert(self, location: int, object: Features.ShipDesign.GeneralArrangement.DrawingItemBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class DrawingItemBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CreateItem(self) -> bool: ...
    @CreateItem.setter
    def CreateItem(self, value: bool) -> None: ...


class DrawingAutomationBuilder(Builder):
    def __init__(self) -> None: ...
    def CreateDrawingViewItemBuilder(self) -> Features.ShipDesign.GeneralArrangement.DrawingViewItemBuilder: ...
    def CreateDrawingTableItemBuilder(self) -> Features.ShipDesign.GeneralArrangement.DrawingTableItemBuilder: ...
    def Find(self, journalIdentifier: str) -> TaggedObject: ...
    @property
    def ViewList(self) -> Features.ShipDesign.GeneralArrangement.DrawingItemBuilderList: ...
    @ViewList.setter
    def ViewList(self, value: Features.ShipDesign.GeneralArrangement.DrawingItemBuilderList) -> None: ...
    @property
    def ViewType(self) -> str: ...
    @ViewType.setter
    def ViewType(self, value: str) -> None: ...


