from ...NXOpen import *

import typing
import enum

class RoutingManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetRoutingManager(self, owner: Session) -> ElectricalRouting.RoutingManager: ...
    def SetActiveWiringComponent(self, rootPart: Part, activeWiringComp: Assemblies.Component) -> None: ...
    def GetWiringComponents(self, rootPart: Assemblies.Component) -> typing.List[Assemblies.Component]: ...
    def Tag(self) -> Tag: ...

    @property
    def BuilderFactory(self) -> ElectricalRouting.BuilderFactory: ...
    @BuilderFactory.setter
    def BuilderFactory(self, value: ElectricalRouting.BuilderFactory) -> None: ...


class BuilderFactory(Utilities.NXRemotableObject):
    def __init__(self, owner: ElectricalRouting.RoutingManager) -> None: ...
    def CreateActiveWiringComponentBuilder(self, part: Part, workOcc: Assemblies.Component) -> ElectricalRouting.ActiveWiringComponentBuilder: ...
    def Tag(self) -> Tag: ...



class ActiveWiringComponentBuilder(Builder):
    def __init__(self) -> None: ...
    @typing.overload
    def CreateWiringComponent(self) -> Assemblies.Component: ...
    @typing.overload
    def CreateWiringComponent(self, componentName: str) -> Assemblies.Component: ...
    def GetPartOccOfWCInDisplayedPart(self, tagToBeMapped: Assemblies.Component) -> Assemblies.Component: ...
    def GetPartOccOfWCInWorkPart(self, tagToBeMapped: Assemblies.Component) -> Assemblies.Component: ...
    @property
    def ActiveWiringComp(self) -> Assemblies.Component: ...
    @ActiveWiringComp.setter
    def ActiveWiringComp(self, value: Assemblies.Component) -> None: ...
    @property
    def SelectPart(self) -> Assemblies.SelectComponent: ...
    @SelectPart.setter
    def SelectPart(self, value: Assemblies.SelectComponent) -> None: ...


