from ....NXOpen import *
from ...Assemblies import *

import typing
import enum

class PropertyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def InterfaceUsageType(self) -> int: ...
    @InterfaceUsageType.setter
    def InterfaceUsageType(self, value: int) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...


class ObjectBuilder(Builder):
    def __init__(self) -> None: ...
    def AddProductInterfaceObject1(self, nxObject: NXObject, name: str, description: str, reverseDirection: bool) -> Assemblies.ProductInterface.InterfaceObject: ...
    def AddProductInterfaceObject2(self, nxObject: NXObject, name: str, description: str, reverseDirection: bool, interfaceUsageType: Assemblies.ProductInterface.InterfaceObject.InterfaceUsageType) -> Assemblies.ProductInterface.InterfaceObject: ...
    def AddProductInterfaceObject3(self, nxObject: NXObject, name: str, description: str, reverseDirection: bool, interfaceUsageType: Assemblies.ProductInterface.InterfaceObject.InterfaceUsageType, isGroupAsPIObject: bool) -> Assemblies.ProductInterface.InterfaceObject: ...
    def EditProductInterfaceObject(self, productInterface: Assemblies.ProductInterface.InterfaceObject, nxObject: NXObject, name: str, description: str, reverseDirection: bool) -> None: ...
    def EditProductInterfaceObject1(self, productInterface: Assemblies.ProductInterface.InterfaceObject, nxObject: NXObject, name: str, description: str, reverseDirection: bool, interfaceUsageType: Assemblies.ProductInterface.InterfaceObject.InterfaceUsageType) -> None: ...
    def GetBuilderVersion(self) -> Assemblies.ProductInterface.ObjectBuilder.BuilderVersion: ...
    def SetBuilderVersion(self, version: Assemblies.ProductInterface.ObjectBuilder.BuilderVersion) -> None: ...
    def AddProductInterfaceObject(self, nxItem: NXObject) -> Assemblies.ProductInterface.InterfaceObject: ...
    def AddProductInterface(self, nxItem: NXObject, alreadyExisted: bool) -> Assemblies.ProductInterface.InterfaceObject: ...
    def RemoveProductInterfaceObject(self, prodIntItem: Assemblies.ProductInterface.InterfaceObject) -> None: ...
    def QueryProductInterfaceObjects(self, part: NXObject) -> typing.List[Assemblies.ProductInterface.InterfaceObject]: ...
    def SetUserComments(self, prodIntItem: Assemblies.ProductInterface.InterfaceObject, userComments: str) -> None: ...
    def UpdateAttributesFromPart(self, part: NXObject) -> None: ...
    @property
    def MateSetting(self) -> Assemblies.ProductInterface.ObjectBuilder.Mate: ...
    @MateSetting.setter
    def MateSetting(self, value: Assemblies.ProductInterface.ObjectBuilder.Mate) -> None: ...
    @property
    def PartGeometryCopy(self) -> Features.PartGeometryCopyBuilder: ...
    @PartGeometryCopy.setter
    def PartGeometryCopy(self, value: Features.PartGeometryCopyBuilder) -> None: ...
    @property
    def WaveSetting(self) -> Assemblies.ProductInterface.ObjectBuilder.Wave: ...
    @WaveSetting.setter
    def WaveSetting(self, value: Assemblies.ProductInterface.ObjectBuilder.Wave) -> None: ...


    class Wave(enum.Enum):
        NoCheck= 0
        Warn= 1
        Prevent= 2
    

    class Mate(enum.Enum):
        NoCheck= 0
        Warn= 1
        Prevent= 2
    

    class BuilderVersion(enum.Enum):
        Original= 0
        One= 1
        Two= 2
        Three= 3
    

class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class InterfaceObject(NXObject):
    def __init__(self) -> None: ...
    def GetProductInterfaceObjectType(self) -> str: ...
    def GetProductInterfaceDefiningEntity(self) -> NXObject: ...
    def GetProductInterfaceObjectStatus(self) -> str: ...
    def SetUserComments(self, userComments: str) -> None: ...
    def GetUserComments(self) -> str: ...
    def RemoveProductInterfaceObject(self) -> None: ...
    def RenameProductInterfaceObject(self, name: str) -> None: ...
    def CheckProductInterfaceObject(self) -> Assemblies.ProductInterface.InterfaceObject.InvalidState: ...
    def FixInvalidProductInterfaceObject(self) -> bool: ...
    def InsertRelatedExpressions(self, relatedExps: typing.List[NXObject]) -> None: ...
    def RemoveRelatedExpression(self, relatedExp: NXObject) -> None: ...
    def RemoveAllRelatedExpressions(self) -> int: ...
    def GetRelatedExpressions(self) -> typing.List[NXObject]: ...
    def GetInterfaceUsageType(self) -> Assemblies.ProductInterface.InterfaceObject.InterfaceUsageType: ...
    def SetInterfaceUsageType(self, usageType: Assemblies.ProductInterface.InterfaceObject.InterfaceUsageType) -> None: ...
    def BreakPIReferencingLinks(self, usageType: Assemblies.ProductInterface.InterfaceObject.InterfaceUsageType) -> None: ...
    def InsertRelatedRequirement(self, relatedReq: Validate.Requirement) -> None: ...
    def RemoveRelatedRequirement(self, relatedReq: Validate.Requirement) -> None: ...
    @property
    def ObjectName(self) -> str: ...
    @ObjectName.setter
    def ObjectName(self, value: str) -> None: ...


    class InvalidState(enum.Enum):
        Valid= 0
        Sleeping= 1
        IncorrectOrphan= 2
        SelfReferenced= 3
    

    class InterfaceUsageType(enum.Enum):
        Unknown= 0
        Output= 1
        Input= 2
        KeyPerformanceInterface= 3
    

class Collection(Utilities.NXRemotableObject):
    def __init__(self, owner: Part) -> None: ...
    def CreateObjectBuilder(self) -> Assemblies.ProductInterface.ObjectBuilder: ...
    def CreateObjectBuilderWithVersion(self, version: int) -> Assemblies.ProductInterface.ObjectBuilder: ...
    def CreateObjectBuilderWithBuilderVersion(self, version: Assemblies.ProductInterface.ObjectBuilder.BuilderVersion) -> Assemblies.ProductInterface.ObjectBuilder: ...
    def CreatePropertyBuilder(self) -> Assemblies.ProductInterface.PropertyBuilder: ...
    def FindObject(self, journalIdentifier: str) -> NXObject: ...
    def GetProductInterfaces(self) -> typing.List[Assemblies.ProductInterface.InterfaceObject]: ...
    def Tag(self) -> Tag: ...



