from ....NXOpen import *
from ...SIM import *

import typing
import enum

class UpdatePostprocessorBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CreateBackup(self) -> bool: ...
    @CreateBackup.setter
    def CreateBackup(self, value: bool) -> None: ...
    @property
    def CurrentPostprocessorVersion(self) -> str: ...
    @CurrentPostprocessorVersion.setter
    def CurrentPostprocessorVersion(self, value: str) -> None: ...
    @property
    def PostRegistryPath(self) -> str: ...
    @PostRegistryPath.setter
    def PostRegistryPath(self, value: str) -> None: ...
    @property
    def UpdatePostprocessor(self) -> SIM.PostConfigurator.UpdatePostprocessorBuilder.UpdatePostprocessorType: ...
    @UpdatePostprocessor.setter
    def UpdatePostprocessor(self, value: SIM.PostConfigurator.UpdatePostprocessorBuilder.UpdatePostprocessorType) -> None: ...
    @property
    def UpdateToVersion(self) -> str: ...
    @UpdateToVersion.setter
    def UpdateToVersion(self, value: str) -> None: ...


    class UpdatePostprocessorType(enum.Enum):
        FromCurrentNXVersion= 0
        FromPostRegistry= 1
        Kinematic= 2
    

class UdeParameterBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[SIM.PostConfigurator.UdeParameterBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: SIM.PostConfigurator.UdeParameterBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: SIM.PostConfigurator.UdeParameterBuilder) -> int: ...
    def FindItem(self, index: int) -> SIM.PostConfigurator.UdeParameterBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: SIM.PostConfigurator.UdeParameterBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: SIM.PostConfigurator.UdeParameterBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[SIM.PostConfigurator.UdeParameterBuilder]: ...
    def SetContents(self, objects: typing.List[SIM.PostConfigurator.UdeParameterBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: SIM.PostConfigurator.UdeParameterBuilder, object2: SIM.PostConfigurator.UdeParameterBuilder) -> None: ...
    def Insert(self, location: int, object: SIM.PostConfigurator.UdeParameterBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class UdeParameterBuilder(Builder):
    def __init__(self) -> None: ...
    def GetEnumerationItems(self) -> str: ...
    def SetEnumerationItems(self, enumerationItems: str) -> None: ...
    def SetGroup(self, parentBuilder: SIM.PostConfigurator.UdeParameterBuilder) -> None: ...
    @property
    def DoubleDefaultValue(self) -> float: ...
    @DoubleDefaultValue.setter
    def DoubleDefaultValue(self, value: float) -> None: ...
    @property
    def EnumerationDefaultValue(self) -> str: ...
    @EnumerationDefaultValue.setter
    def EnumerationDefaultValue(self, value: str) -> None: ...
    @property
    def GroupState(self) -> SIM.PostConfigurator.UdeParameterBuilder.GroupStateType: ...
    @GroupState.setter
    def GroupState(self, value: SIM.PostConfigurator.UdeParameterBuilder.GroupStateType) -> None: ...
    @property
    def IntegerDefaultValue(self) -> int: ...
    @IntegerDefaultValue.setter
    def IntegerDefaultValue(self, value: int) -> None: ...
    @property
    def ItemType(self) -> SIM.PostConfigurator.UdeParameterBuilder.Type: ...
    @ItemType.setter
    def ItemType(self, value: SIM.PostConfigurator.UdeParameterBuilder.Type) -> None: ...
    @property
    def ParameterID(self) -> str: ...
    @ParameterID.setter
    def ParameterID(self, value: str) -> None: ...
    @property
    def ParameterStatus(self) -> SIM.PostConfigurator.UdeParameterBuilder.ParameterStatusType: ...
    @ParameterStatus.setter
    def ParameterStatus(self, value: SIM.PostConfigurator.UdeParameterBuilder.ParameterStatusType) -> None: ...
    @property
    def StringDefaultValue(self) -> str: ...
    @StringDefaultValue.setter
    def StringDefaultValue(self, value: str) -> None: ...
    @property
    def ToggleDefaultValue(self) -> bool: ...
    @ToggleDefaultValue.setter
    def ToggleDefaultValue(self, value: bool) -> None: ...
    @property
    def UILabel(self) -> str: ...
    @UILabel.setter
    def UILabel(self, value: str) -> None: ...


    class Type(enum.Enum):
        Group= 0
        Double= 1
        Integer= 2
        String= 3
        Boolean= 4
        Enumeration= 5
        Vector= 6
        Point= 7
        Bitmap= 8
    

    class ParameterStatusType(enum.Enum):
        None_= 0
        On= 1
        Off= 2
    

    class GroupStateType(enum.Enum):
        Open= 0
        Closed= 1
        End= 2
    

class UdeEditorBuilder(Builder):
    def __init__(self) -> None: ...
    def GetUdeBuilder(self, eventHandlerID: str) -> SIM.PostConfigurator.UdeBuilder: ...
    def AddNewEvent(self) -> SIM.PostConfigurator.UdeBuilder: ...
    def DuplicateEvent(self, udeBuilder: SIM.PostConfigurator.UdeBuilder) -> SIM.PostConfigurator.UdeBuilder: ...
    def RemoveEvent(self, udeBuilder: SIM.PostConfigurator.UdeBuilder) -> None: ...
    def ListEvent(self, udeBuilder: SIM.PostConfigurator.UdeBuilder) -> None: ...
    @property
    def UdeBuilderList(self) -> SIM.PostConfigurator.UdeBuilderList: ...
    @UdeBuilderList.setter
    def UdeBuilderList(self, value: SIM.PostConfigurator.UdeBuilderList) -> None: ...


class UdeBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[SIM.PostConfigurator.UdeBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: SIM.PostConfigurator.UdeBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: SIM.PostConfigurator.UdeBuilder) -> int: ...
    def FindItem(self, index: int) -> SIM.PostConfigurator.UdeBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: SIM.PostConfigurator.UdeBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: SIM.PostConfigurator.UdeBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[SIM.PostConfigurator.UdeBuilder]: ...
    def SetContents(self, objects: typing.List[SIM.PostConfigurator.UdeBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: SIM.PostConfigurator.UdeBuilder, object2: SIM.PostConfigurator.UdeBuilder) -> None: ...
    def Insert(self, location: int, object: SIM.PostConfigurator.UdeBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class UdeBuilder(Builder):
    def __init__(self) -> None: ...
    def AddItem(self, itemBuilder: SIM.PostConfigurator.UdeParameterBuilder) -> None: ...
    def DeleteItem(self, itemBuilder: SIM.PostConfigurator.UdeParameterBuilder) -> None: ...
    def DeleteItems(self) -> None: ...
    def GetUdeParameterBuilder(self, parameterID: str) -> SIM.PostConfigurator.UdeParameterBuilder: ...
    def RenameParameterID(self, itemBuilder: SIM.PostConfigurator.UdeParameterBuilder, oldParameterID: str, newParameterID: str) -> None: ...
    @property
    def EventCategoryDrilling(self) -> bool: ...
    @EventCategoryDrilling.setter
    def EventCategoryDrilling(self, value: bool) -> None: ...
    @property
    def EventCategoryMilling(self) -> bool: ...
    @EventCategoryMilling.setter
    def EventCategoryMilling(self, value: bool) -> None: ...
    @property
    def EventCategoryTurning(self) -> bool: ...
    @EventCategoryTurning.setter
    def EventCategoryTurning(self, value: bool) -> None: ...
    @property
    def EventCategoryWireEDM(self) -> bool: ...
    @EventCategoryWireEDM.setter
    def EventCategoryWireEDM(self, value: bool) -> None: ...
    @property
    def EventDescription(self) -> SIM.PostConfigurator.UdeBuilder.EventDescriptionType: ...
    @EventDescription.setter
    def EventDescription(self, value: SIM.PostConfigurator.UdeBuilder.EventDescriptionType) -> None: ...
    @property
    def EventHelpDescription(self) -> str: ...
    @EventHelpDescription.setter
    def EventHelpDescription(self, value: str) -> None: ...
    @property
    def EventHelpLocation(self) -> str: ...
    @EventHelpLocation.setter
    def EventHelpLocation(self, value: str) -> None: ...
    @property
    def EventID(self) -> str: ...
    @EventID.setter
    def EventID(self, value: str) -> None: ...
    @property
    def EventName(self) -> str: ...
    @EventName.setter
    def EventName(self, value: str) -> None: ...
    @property
    def PostEvent(self) -> str: ...
    @PostEvent.setter
    def PostEvent(self, value: str) -> None: ...
    @property
    def UdeParameterList(self) -> SIM.PostConfigurator.UdeParameterBuilderList: ...
    @UdeParameterList.setter
    def UdeParameterList(self, value: SIM.PostConfigurator.UdeParameterBuilderList) -> None: ...


    class EventDescriptionType(enum.Enum):
        None_= 0
        Specify= 1
    

class ScannerPostBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def BrowseNcFile(self) -> str: ...
    @BrowseNcFile.setter
    def BrowseNcFile(self, value: str) -> None: ...
    @property
    def CreateDirectoryForPostprocessor(self) -> bool: ...
    @CreateDirectoryForPostprocessor.setter
    def CreateDirectoryForPostprocessor(self, value: bool) -> None: ...
    @property
    def PostprocessorName(self) -> str: ...
    @PostprocessorName.setter
    def PostprocessorName(self, value: str) -> None: ...
    @property
    def PostprocessorOutputDirectory(self) -> str: ...
    @PostprocessorOutputDirectory.setter
    def PostprocessorOutputDirectory(self, value: str) -> None: ...


class PostConfiguratorManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def CreateScannerPostBuilder(self) -> SIM.PostConfigurator.ScannerPostBuilder: ...
    def CreateCreationPostBuilder(self) -> SIM.PostConfigurator.CreationPostBuilder: ...
    def CreatePostConfiguratorBuilder(self, postProcessorFilename: str) -> SIM.PostConfigurator.PostConfiguratorBuilder: ...
    def CreateUdeBuilder(self) -> SIM.PostConfigurator.UdeBuilder: ...
    def CreateUdeParameterBuilder(self) -> SIM.PostConfigurator.UdeParameterBuilder: ...
    def CreatePostConfiguratorDebugBuilder(self) -> SIM.PostConfigurator.PostConfiguratorDebugBuilder: ...
    def CreateEncryptPostprocessorFilesBuilder(self, postProcessorFilename: str) -> SIM.PostConfigurator.EncryptPostprocessorFilesBuilder: ...
    def Tag(self) -> Tag: ...



class PostConfiguratorDebugBuilder(Builder):
    def __init__(self) -> None: ...
    def GetTrace(self, type: SIM.PostConfigurator.PostConfiguratorDebugBuilder.TraceType) -> bool: ...
    def SetTrace(self, type: SIM.PostConfigurator.PostConfiguratorDebugBuilder.TraceType, state: bool) -> None: ...
    @property
    def Dump(self) -> SIM.PostConfigurator.PostConfiguratorDebugBuilder.DumpType: ...
    @Dump.setter
    def Dump(self, value: SIM.PostConfigurator.PostConfiguratorDebugBuilder.DumpType) -> None: ...
    @property
    def Output(self) -> SIM.PostConfigurator.PostConfiguratorDebugBuilder.OutputType: ...
    @Output.setter
    def Output(self, value: SIM.PostConfigurator.PostConfiguratorDebugBuilder.OutputType) -> None: ...
    @property
    def OutputToFileName(self) -> str: ...
    @OutputToFileName.setter
    def OutputToFileName(self, value: str) -> None: ...


    class TraceType(enum.Enum):
        CreatePostprocessor= 0
        SelectPostprocessor= 1
    

    class OutputType(enum.Enum):
        Syslog= 0
        ListingWindow= 1
        Xml= 2
        ToFile= 3
    

    class DumpType(enum.Enum):
        None_= 0
        ShowChanges= 1
    

class PostConfiguratorBuilder(Builder):
    def __init__(self) -> None: ...
    def Reset(self) -> None: ...
    def ShowChanges(self) -> None: ...
    def EncryptPostConfiguratorFiles(self, soldToID: str, expirationDate: str) -> None: ...
    def EncryptPostConfiguratorFile(self, sourceFile: str, destFile: str, soldToID: str, expirationDate: str) -> None: ...
    def Save(self) -> None: ...
    def SaveAs(self, postprocessorName: str, outputDirectory: str) -> None: ...
    def CreateCustomCdlFile(self) -> None: ...
    def PostProcess(self, objects: typing.List[CAM.CAMObject], outputFilename: str, showOutputToListingWindow: bool) -> None: ...
    @typing.overload
    def SetPropertyValue(self, chainID: str, configurationObjectID: str, propertyID: str, value: str) -> None: ...
    @typing.overload
    def SetPropertyValue(self, chainID: str, configurationObjectID: str, propertyID: str, value: str) -> None: ...
    @typing.overload
    def SetPropertyValue(self, chainID: str, configurationObjectID: str, propertyID: str, value: int) -> None: ...
    @typing.overload
    def SetPropertyValue(self, chainID: str, configurationObjectID: str, propertyID: str, value: float) -> None: ...
    @typing.overload
    def SetPropertyValue(self, chainID: str, configurationObjectID: str, propertyID: str, firstValue: float, secondValue: float, thirdValue: float) -> None: ...
    def SetPropertyToDefaultValue(self, chainID: str, configurationObjectID: str, propertyID: str) -> None: ...
    def AddProperty(self, chainID: str, configurationObjectID: str, propertyID: str) -> None: ...
    def RemoveProperty(self, chainID: str, configurationObjectID: str, propertyID: str) -> None: ...
    def GetPropertyValue(self, chainID: str, configurationObjectID: str, propertyID: str) -> str: ...
    def GetPropertyDefaultValue(self, chainID: str, configurationObjectID: str, propertyID: str) -> str: ...
    def GetPropertyOptionsValue(self, chainID: str, configurationObjectID: str, propertyID: str) -> str: ...
    def GetPropertyOptionsIdValue(self, chainID: str, configurationObjectID: str, propertyID: str) -> str: ...
    def GetPropertyDescriptionText(self, chainID: str, configurationObjectID: str, propertyID: str) -> str: ...
    def GetPropertyDescriptionImage(self, chainID: str, configurationObjectID: str, propertyID: str) -> str: ...
    def GetPropertyDataType(self, chainID: str, configurationObjectID: str, propertyID: str) -> SIM.PostConfigurator.PostConfiguratorBuilder.PropertyDataType: ...
    def GetPropertyDataFieldType(self, chainID: str, configurationObjectID: str, propertyID: str) -> SIM.PostConfigurator.PostConfiguratorBuilder.PropertyDataFieldType: ...
    def GetPropertyOptionType(self, chainID: str, configurationObjectID: str, propertyID: str) -> SIM.PostConfigurator.PostConfiguratorBuilder.PropertyOptionType: ...
    def GetPropertyAccessType(self, chainID: str, configurationObjectID: str, propertyID: str) -> SIM.PostConfigurator.PostConfiguratorBuilder.PropertyAccessType: ...
    def GetPropertyValueChangedStatus(self, chainID: str, configurationObjectID: str, propertyID: str) -> SIM.PostConfigurator.PostConfiguratorBuilder.PropertyValueChangedStatusType: ...
    def GetPropertyChainIds(self) -> str: ...
    def GetPropertyConfigurationObjectIds(self) -> str: ...
    def GetPropertyIds(self) -> str: ...
    def OpenDocumentation(self) -> None: ...
    def ListPropertyDataInInformationWindow(self, configurationObjectID: str, propertyID: str) -> None: ...
    def CopyPropertyDataToClipboard(self, configurationObjectID: str, propertyID: str) -> None: ...
    def CreateCustomDefFile(self) -> SIM.PostConfigurator.PostConfiguratorBuilder.DefWriterErrorType: ...
    @property
    def DateValue(self) -> DateBuilder: ...
    @DateValue.setter
    def DateValue(self, value: DateBuilder) -> None: ...
    @property
    def DefEditorBuilder(self) -> SIM.PostConfigurator.DefEditorBuilder: ...
    @DefEditorBuilder.setter
    def DefEditorBuilder(self, value: SIM.PostConfigurator.DefEditorBuilder) -> None: ...
    @property
    def LayerManagerBuilder(self) -> SIM.PostConfigurator.LayerManagerBuilder: ...
    @LayerManagerBuilder.setter
    def LayerManagerBuilder(self, value: SIM.PostConfigurator.LayerManagerBuilder) -> None: ...
    @property
    def UdeEditorBuilder(self) -> SIM.PostConfigurator.UdeEditorBuilder: ...
    @UdeEditorBuilder.setter
    def UdeEditorBuilder(self, value: SIM.PostConfigurator.UdeEditorBuilder) -> None: ...
    @property
    def Units(self) -> SIM.PostConfigurator.PostConfiguratorBuilder.UnitsType: ...
    @Units.setter
    def Units(self, value: SIM.PostConfigurator.PostConfiguratorBuilder.UnitsType) -> None: ...
    @property
    def UpdatePostprocessorBuilder(self) -> SIM.PostConfigurator.UpdatePostprocessorBuilder: ...
    @UpdatePostprocessorBuilder.setter
    def UpdatePostprocessorBuilder(self, value: SIM.PostConfigurator.UpdatePostprocessorBuilder) -> None: ...


    class UnitsType(enum.Enum):
        Millimeters= 0
        Inches= 1
        MillimetersAndInches= 2
    

    class PropertyValueChangedStatusType(enum.Enum):
        Unchanged= 0
        Changed= 1
        UnremoveUnchanged= 2
        UnremoveChanged= 3
        UnaddUnchanged= 4
        UnaddChanged= 5
    

    class PropertyOptionType(enum.Enum):
        Unknown= 0
        Value= 1
        Enum= 2
    

    class PropertyDataType(enum.Enum):
        Unknown= 0
        Integer= 1
        Double= 2
        String= 3
        Option= 4
        Vector= 5
        Multistring= 6
        Point= 7
    

    class PropertyDataFieldType(enum.Enum):
        Unknown= 0
        Single= 1
        Option= 2
    

    class PropertyAccessType(enum.Enum):
        No= 0
        Read= 1
        Full= 2
    

    class DefWriterErrorType(enum.Enum):
        NoError= 0
        DirWriteprotectError= 1
        NoCustomerError= 2
        CustomFileExistError= 3
        FileWriteprotectError= 4
        UnknownError= 5
    

class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class LayerManagerBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AddLayerBuilder(self) -> SIM.PostConfigurator.AddLayerBuilder: ...
    @AddLayerBuilder.setter
    def AddLayerBuilder(self, value: SIM.PostConfigurator.AddLayerBuilder) -> None: ...


class EncryptPostprocessorFilesBuilder(Builder):
    def __init__(self) -> None: ...
    def SetEncryptPostprocessorFiles(self, encryptFilename: str) -> None: ...
    def GetEncryptPostprocessorFiles(self) -> str: ...
    def SetSoldToIds(self, soldToIDs: str) -> None: ...
    def GetSoldToIds(self) -> str: ...
    @property
    def ExpirationDate(self) -> str: ...
    @ExpirationDate.setter
    def ExpirationDate(self, value: str) -> None: ...


class DefEditorBuilder(Builder):
    def __init__(self) -> None: ...
    def AddBlockTemplate(self, blockTemplateName: str, blockAddressName: str, blockItemType: typing.List[SIM.PostConfigurator.DefEditorBuilder.BlockItemType], expression: str, addressIndex: int, isOptional: bool, hasNoWordSeparator: bool) -> None: ...
    def DeleteBlockTemplate(self, blockTemplateName: str) -> None: ...
    def AddAddress(self, addressName: str, formatName: str, zeroLimitName: str, forceType: SIM.PostConfigurator.DefEditorBuilder.AddressForceType, leader: str, leaderType: SIM.PostConfigurator.DefEditorBuilder.AddressLeaderType, trailer: str, trailerType: SIM.PostConfigurator.DefEditorBuilder.AddressTrailerType, maxIsDefine: bool, maxLimit: float, maxHandeType: SIM.PostConfigurator.DefEditorBuilder.AddressLimitHandleType, minIsDefine: bool, minLimit: float, minHandeType: SIM.PostConfigurator.DefEditorBuilder.AddressLimitHandleType) -> None: ...
    def AddAddressWithOmit(self, addressName: str, formatName: str, zeroLimitName: str, forceType: SIM.PostConfigurator.DefEditorBuilder.AddressForceType, leader: str, leaderType: SIM.PostConfigurator.DefEditorBuilder.AddressLeaderType, trailer: str, trailerType: SIM.PostConfigurator.DefEditorBuilder.AddressTrailerType, maxIsDefine: bool, maxLimit: float, maxHandeType: SIM.PostConfigurator.DefEditorBuilder.AddressLimitHandleType, minIsDefine: bool, minLimit: float, minHandeType: SIM.PostConfigurator.DefEditorBuilder.AddressLimitHandleType, omit: str) -> None: ...
    def DeleteAddress(self, addressName: str) -> None: ...
    def DeleteBlockAddress(self, blockTemplateName: str, addressName: str) -> None: ...
    def AddBlockAddress(self, blockTemplateName: str, blockAddressName: str, blockItemType: int, expression: str, addressIndex: int, isOptional: bool, hasNoWordSeparator: bool) -> None: ...
    def AddFormat(self, formatName: str, isOutputLeaderPlusSign: bool, isOutputLeadingZeros: bool, isOutputDecimalPoint: bool, isOutputTrailingZeros: bool, visibleDigits: int, visibleDecimals: int, formatType: SIM.PostConfigurator.DefEditorBuilder.FormatType) -> None: ...
    def DeleteFormat(self, formatName: str) -> None: ...
    @property
    def CurrentLayer(self) -> str: ...
    @CurrentLayer.setter
    def CurrentLayer(self, value: str) -> None: ...


    class FormatType(enum.Enum):
        Numeric= 0
        Text= 1
    

    class BlockItemType(enum.Enum):
        Literal= 0
        Address= 1
        TurboAddress= 2
    

    class AddressTrailerType(enum.Enum):
        Literal= 0
        Expression= 1
    

    class AddressLimitHandleType(enum.Enum):
        TruncateValue= 0
        WarnUser= 1
        AbortProcess= 2
    

    class AddressLeaderType(enum.Enum):
        Literal= 0
        Expression= 1
    

    class AddressForceType(enum.Enum):
        On= 0
        Once= 1
        Always= 2
    

class CreationPostBuilder(Builder):
    def __init__(self) -> None: ...
    def GetControllerNames(self) -> str: ...
    def GetManufacturerNames(self) -> str: ...
    def GetMachineNames(self) -> str: ...
    def GetLayerNameValue(self, layerName: str) -> str: ...
    def SetLayerNameValue(self, layerName: str, value: str) -> None: ...
    def GetLayerNames(self, layerName: str) -> str: ...
    @property
    def ControllerName(self) -> str: ...
    @ControllerName.setter
    def ControllerName(self, value: str) -> None: ...
    @property
    def CreateDirectoryForPostprocessor(self) -> bool: ...
    @CreateDirectoryForPostprocessor.setter
    def CreateDirectoryForPostprocessor(self, value: bool) -> None: ...
    @property
    def MachineName(self) -> str: ...
    @MachineName.setter
    def MachineName(self, value: str) -> None: ...
    @property
    def ManufacturerName(self) -> str: ...
    @ManufacturerName.setter
    def ManufacturerName(self, value: str) -> None: ...
    @property
    def PostprocessorName(self) -> str: ...
    @PostprocessorName.setter
    def PostprocessorName(self, value: str) -> None: ...
    @property
    def PostprocessorOutputDirectory(self) -> str: ...
    @PostprocessorOutputDirectory.setter
    def PostprocessorOutputDirectory(self, value: str) -> None: ...


class AddLayerBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CreateDefinitionFile(self) -> bool: ...
    @CreateDefinitionFile.setter
    def CreateDefinitionFile(self, value: bool) -> None: ...
    @property
    def CreateDirectoryForLayer(self) -> bool: ...
    @CreateDirectoryForLayer.setter
    def CreateDirectoryForLayer(self, value: bool) -> None: ...
    @property
    def CreateTclFile(self) -> bool: ...
    @CreateTclFile.setter
    def CreateTclFile(self, value: bool) -> None: ...
    @property
    def CreateUserDefinedEventFile(self) -> bool: ...
    @CreateUserDefinedEventFile.setter
    def CreateUserDefinedEventFile(self, value: bool) -> None: ...
    @property
    def LayerFileName(self) -> str: ...
    @LayerFileName.setter
    def LayerFileName(self, value: str) -> None: ...
    @property
    def LayerName(self) -> str: ...
    @LayerName.setter
    def LayerName(self, value: str) -> None: ...


