from ...NXOpen import *

import typing
import enum

class SelectObjectDimListItemList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[ModlUtils.SelectObjectDimListItem]) -> None: ...
    @typing.overload
    def Append(self, object: ModlUtils.SelectObjectDimListItem) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: ModlUtils.SelectObjectDimListItem) -> int: ...
    def FindItem(self, index: int) -> ModlUtils.SelectObjectDimListItem: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: ModlUtils.SelectObjectDimListItem) -> None: ...
    @typing.overload
    def Erase(self, obj: ModlUtils.SelectObjectDimListItem, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[ModlUtils.SelectObjectDimListItem]: ...
    def SetContents(self, objects: typing.List[ModlUtils.SelectObjectDimListItem]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: ModlUtils.SelectObjectDimListItem, object2: ModlUtils.SelectObjectDimListItem) -> None: ...
    def Insert(self, location: int, object: ModlUtils.SelectObjectDimListItem) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class SelectObjectDimListItemBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[ModlUtils.SelectObjectDimListItemBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: ModlUtils.SelectObjectDimListItemBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: ModlUtils.SelectObjectDimListItemBuilder) -> int: ...
    def FindItem(self, index: int) -> ModlUtils.SelectObjectDimListItemBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: ModlUtils.SelectObjectDimListItemBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: ModlUtils.SelectObjectDimListItemBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[ModlUtils.SelectObjectDimListItemBuilder]: ...
    def SetContents(self, objects: typing.List[ModlUtils.SelectObjectDimListItemBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: ModlUtils.SelectObjectDimListItemBuilder, object2: ModlUtils.SelectObjectDimListItemBuilder) -> None: ...
    def Insert(self, location: int, object: ModlUtils.SelectObjectDimListItemBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class SelectObjectDimListItemBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Dimension(self) -> Expression: ...
    @Dimension.setter
    def Dimension(self, value: Expression) -> None: ...
    @property
    def Selection(self) -> SelectDisplayableObjectList: ...
    @Selection.setter
    def Selection(self, value: SelectDisplayableObjectList) -> None: ...


class SelectObjectDimListItem(Builder):
    def __init__(self) -> None: ...
    @property
    def Dimension(self) -> Expression: ...
    @Dimension.setter
    def Dimension(self, value: Expression) -> None: ...
    @property
    def Selection(self) -> SelectDisplayableObjectList: ...
    @Selection.setter
    def Selection(self, value: SelectDisplayableObjectList) -> None: ...


class SelectObjectDimListBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def CreateSelectObjectDimListItemBuilder(self) -> ModlUtils.SelectObjectDimListItemBuilder: ...
    def Validate(self) -> bool: ...
    @property
    def List(self) -> ModlUtils.SelectObjectDimListItemBuilderList: ...
    @List.setter
    def List(self, value: ModlUtils.SelectObjectDimListItemBuilderList) -> None: ...


class SelectObjectDimList(TaggedObject):
    def __init__(self) -> None: ...
    def CreateSelectObjectDimListItem(self) -> ModlUtils.SelectObjectDimListItem: ...
    def Validate(self) -> bool: ...
    @property
    def List(self) -> ModlUtils.SelectObjectDimListItemList: ...
    @List.setter
    def List(self, value: ModlUtils.SelectObjectDimListItemList) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class EquationEditorBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def EquationString(self) -> str: ...
    @EquationString.setter
    def EquationString(self, value: str) -> None: ...


