from ...NXOpen import *

import typing
import enum

class OrientationByVector(CADCAEPrep.IOrientation):
    def __init__(self) -> None: ...


    class OrientAxis(enum.Enum):
        Y= 2
        Z= 3
    

class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class IOrientation(NXObject):
    def __init__(self) -> None: ...


class IdealizedBeamManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Part) -> None: ...
    def GetSection(self, sectionName: str) -> CADCAEPrep.IBeamSection: ...
    def AddBeamSectionRod(self, sectionName: str, radius: float) -> CADCAEPrep.BeamSectionRod: ...
    def AddBeamSectionBox(self, sectionName: str, width: float, height: float, thicknessTopBottom: float, thicknessSides: float) -> CADCAEPrep.BeamSectionBox: ...
    def AddBeamSectionChan(self, sectionName: str, width: float, height: float, flangeThickness: float, webThickness: float) -> CADCAEPrep.BeamSectionChan: ...
    def AddBeamSectionHexa(self, sectionName: str, sideWidth: float, overallWidth: float, height: float) -> CADCAEPrep.BeamSectionHexa: ...
    def AddBeamSectionT(self, sectionName: str, width: float, height: float, flangeThickness: float, webThickness: float) -> CADCAEPrep.BeamSectionT: ...
    def AddBeamSectionBar(self, sectionName: str, width: float, height: float) -> CADCAEPrep.BeamSectionBar: ...
    def AddBeamSectionI(self, sectionName: str, height: float, widthBottomFlange: float, widthTopFlange: float, thicknessWeb: float, thicknessBottomFlange: float, thicknessTopFlange: float) -> CADCAEPrep.BeamSectionI: ...
    def AddBeamSectionL(self, sectionName: str, lengthVertical: float, lengthHorizontal: float, thicknessVertical: float, thicknessHorizontal: float) -> CADCAEPrep.BeamSectionL: ...
    def AddBeamSectionTube(self, sectionName: str, radiusOutside: float, radiusInside: float) -> CADCAEPrep.BeamSectionTube: ...
    def AddBeamSectionSketch(self, sectionName: str, sketchTag: Sketch) -> CADCAEPrep.BeamSectionSketch: ...
    def AddIdealizedBeam(self, curve: Curve) -> CADCAEPrep.IdealizedBeam: ...
    def GetIdealizedBeam(self, curve: Curve) -> CADCAEPrep.IdealizedBeam: ...
    def Tag(self) -> Tag: ...

    @property
    def IBeamSectionCollection(self) -> CADCAEPrep.IBeamSectionCollection: ...
    @IBeamSectionCollection.setter
    def IBeamSectionCollection(self, value: CADCAEPrep.IBeamSectionCollection) -> None: ...
    @property
    def IdealizedBeamCollection(self) -> CADCAEPrep.IdealizedBeamCollection: ...
    @IdealizedBeamCollection.setter
    def IdealizedBeamCollection(self, value: CADCAEPrep.IdealizedBeamCollection) -> None: ...


class IdealizedBeamCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CADCAEPrep.IdealizedBeam]: ...
    @typing.overload
    def __init__(self, owner: CADCAEPrep.IdealizedBeamManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def Tag(self) -> Tag: ...



class IdealizedBeam(NXObject):
    def __init__(self) -> None: ...
    def GetOrientationByVector(self, orientVect: Vector3d, orientAxis: CADCAEPrep.OrientationByVector.OrientAxis, flipY: bool, flipZ: bool) -> None: ...
    def SetOrientationByVector(self, orientVect: Vector3d, orientAxis: CADCAEPrep.OrientationByVector.OrientAxis, flipY: bool, flipZ: bool) -> None: ...
    @property
    def Curve(self) -> Curve: ...
    @Curve.setter
    def Curve(self, value: Curve) -> None: ...
    @property
    def Material(self) -> PhysicalMaterial: ...
    @Material.setter
    def Material(self, value: PhysicalMaterial) -> None: ...
    @property
    def MeshCollectorPrefix(self) -> str: ...
    @MeshCollectorPrefix.setter
    def MeshCollectorPrefix(self, value: str) -> None: ...
    @property
    def OffsetEnd(self) -> Point2d: ...
    @OffsetEnd.setter
    def OffsetEnd(self, value: Point2d) -> None: ...
    @property
    def OffsetStart(self) -> Point2d: ...
    @OffsetStart.setter
    def OffsetStart(self, value: Point2d) -> None: ...
    @property
    def Section(self) -> CADCAEPrep.IBeamSection: ...
    @Section.setter
    def Section(self, value: CADCAEPrep.IBeamSection) -> None: ...
    @property
    def XOffsetEnd(self) -> float: ...
    @XOffsetEnd.setter
    def XOffsetEnd(self, value: float) -> None: ...
    @property
    def XOffsetStart(self) -> float: ...
    @XOffsetStart.setter
    def XOffsetStart(self, value: float) -> None: ...


class IBeamSectionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CADCAEPrep.IBeamSection]: ...
    @typing.overload
    def __init__(self, owner: CADCAEPrep.IdealizedBeamManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def Tag(self) -> Tag: ...



class IBeamSection(NXObject):
    def __init__(self) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Type(self) -> CADCAEPrep.IBeamSection.Sectiontype: ...
    @Type.setter
    def Type(self, value: CADCAEPrep.IBeamSection.Sectiontype) -> None: ...


    class Sectiontype(enum.Enum):
        Unknown= 0
        Sketch= 100
        Rod= 200
        Tube= 300
        Hexa= 400
        Bar= 500
        Box= 600
        T= 700
        L= 800
        I= 900
        Chan= 1000
    

class BeamSectionTube(CADCAEPrep.IBeamSection):
    def __init__(self) -> None: ...
    def Edit(self, radiusOutside: float, radiusInside: float) -> None: ...
    @property
    def Ri(self) -> float: ...
    @Ri.setter
    def Ri(self, value: float) -> None: ...
    @property
    def Ro(self) -> float: ...
    @Ro.setter
    def Ro(self, value: float) -> None: ...


class BeamSectionT(CADCAEPrep.IBeamSection):
    def __init__(self) -> None: ...
    def Edit(self, width: float, height: float, flangeThickness: float, webThickness: float) -> None: ...
    @property
    def H(self) -> float: ...
    @H.setter
    def H(self, value: float) -> None: ...
    @property
    def Tf(self) -> float: ...
    @Tf.setter
    def Tf(self, value: float) -> None: ...
    @property
    def Tw(self) -> float: ...
    @Tw.setter
    def Tw(self, value: float) -> None: ...
    @property
    def W(self) -> float: ...
    @W.setter
    def W(self, value: float) -> None: ...


class BeamSectionSketch(CADCAEPrep.IBeamSection):
    def __init__(self) -> None: ...
    def Edit(self, sketch: Sketch) -> None: ...
    @property
    def OriginBoundingBoxCenterOffset(self) -> Point2d: ...
    @OriginBoundingBoxCenterOffset.setter
    def OriginBoundingBoxCenterOffset(self, value: Point2d) -> None: ...
    @property
    def Sketch(self) -> Sketch: ...
    @Sketch.setter
    def Sketch(self, value: Sketch) -> None: ...


class BeamSectionRod(CADCAEPrep.IBeamSection):
    def __init__(self) -> None: ...
    def Edit(self, radius: float) -> None: ...
    @property
    def R(self) -> float: ...
    @R.setter
    def R(self, value: float) -> None: ...


class BeamSectionL(CADCAEPrep.IBeamSection):
    def __init__(self) -> None: ...
    def Edit(self, lengthVertical: float, lengthHorizontal: float, thicknessHorizontal: float, thicknessVertical: float) -> None: ...
    @property
    def Lh(self) -> float: ...
    @Lh.setter
    def Lh(self, value: float) -> None: ...
    @property
    def Lv(self) -> float: ...
    @Lv.setter
    def Lv(self, value: float) -> None: ...
    @property
    def Th(self) -> float: ...
    @Th.setter
    def Th(self, value: float) -> None: ...
    @property
    def Tv(self) -> float: ...
    @Tv.setter
    def Tv(self, value: float) -> None: ...


class BeamSectionI(CADCAEPrep.IBeamSection):
    def __init__(self) -> None: ...
    def Edit(self, height: float, widthBottomFlange: float, widthTopFlange: float, thicknessWeb: float, thicknessBottomFlange: float, thicknessTopFlange: float) -> None: ...
    @property
    def H(self) -> float: ...
    @H.setter
    def H(self, value: float) -> None: ...
    @property
    def Tbf(self) -> float: ...
    @Tbf.setter
    def Tbf(self, value: float) -> None: ...
    @property
    def Ttf(self) -> float: ...
    @Ttf.setter
    def Ttf(self, value: float) -> None: ...
    @property
    def Tw(self) -> float: ...
    @Tw.setter
    def Tw(self, value: float) -> None: ...
    @property
    def Wbf(self) -> float: ...
    @Wbf.setter
    def Wbf(self, value: float) -> None: ...
    @property
    def Wtf(self) -> float: ...
    @Wtf.setter
    def Wtf(self, value: float) -> None: ...


class BeamSectionHexa(CADCAEPrep.IBeamSection):
    def __init__(self) -> None: ...
    def Edit(self, sideWidth: float, overallWidth: float, height: float) -> None: ...
    @property
    def H(self) -> float: ...
    @H.setter
    def H(self, value: float) -> None: ...
    @property
    def W(self) -> float: ...
    @W.setter
    def W(self, value: float) -> None: ...
    @property
    def Ws(self) -> float: ...
    @Ws.setter
    def Ws(self, value: float) -> None: ...


class BeamSectionChan(CADCAEPrep.IBeamSection):
    def __init__(self) -> None: ...
    def Edit(self, width: float, height: float, webThickness: float, flangeThickness: float) -> None: ...
    @property
    def H(self) -> float: ...
    @H.setter
    def H(self, value: float) -> None: ...
    @property
    def Tf(self) -> float: ...
    @Tf.setter
    def Tf(self, value: float) -> None: ...
    @property
    def Tw(self) -> float: ...
    @Tw.setter
    def Tw(self, value: float) -> None: ...
    @property
    def W(self) -> float: ...
    @W.setter
    def W(self, value: float) -> None: ...


class BeamSectionBox(CADCAEPrep.IBeamSection):
    def __init__(self) -> None: ...
    def Edit(self, width: float, height: float, thicknessTopBottom: float, thicknessSides: float) -> None: ...
    @property
    def H(self) -> float: ...
    @H.setter
    def H(self, value: float) -> None: ...
    @property
    def Tss(self) -> float: ...
    @Tss.setter
    def Tss(self, value: float) -> None: ...
    @property
    def Ttb(self) -> float: ...
    @Ttb.setter
    def Ttb(self, value: float) -> None: ...
    @property
    def W(self) -> float: ...
    @W.setter
    def W(self, value: float) -> None: ...


class BeamSectionBar(CADCAEPrep.IBeamSection):
    def __init__(self) -> None: ...
    def Edit(self, width: float, height: float) -> None: ...
    @property
    def H(self) -> float: ...
    @H.setter
    def H(self, value: float) -> None: ...
    @property
    def W(self) -> float: ...
    @W.setter
    def W(self, value: float) -> None: ...


