from ...NXOpen import *

import typing
import enum

class Text(Markup.Element):
    def __init__(self) -> None: ...
    def Get2DLocation(self) -> Point2d: ...
    def Set2DLocation(self, location: Point2d) -> None: ...
    @property
    def IncludeLabels(self) -> bool: ...
    @IncludeLabels.setter
    def IncludeLabels(self, value: bool) -> None: ...


    class ScaleOptions(enum.Enum):
        One= 0
        Two= 1
        Three= 2
        Four= 3
        Five= 4
    

class Rectangle(Markup.Element):
    def __init__(self) -> None: ...
    def GetCenterLengthAndWidth(self, center: Point3d, length: float, width: float) -> None: ...
    def SetCenterLengthAndWidth(self, center: Point3d, length: float, width: float) -> None: ...


class Polyline(Markup.Element):
    def __init__(self) -> None: ...
    def GetPoints(self, points: typing.List[Point3d]) -> None: ...
    def SetPoints(self, points: typing.List[Point3d]) -> None: ...
    @property
    def LineType(self) -> Markup.Polyline.LineOption: ...
    @LineType.setter
    def LineType(self, value: Markup.Polyline.LineOption) -> None: ...


    class LineOption(enum.Enum):
        Line= 0
        Spline= 1
    

class Polygon(Markup.Polyline):
    def __init__(self) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MarkupCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Markup.Markup]: ...
    @typing.overload
    def __init__(self, owner: BasePart) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, id: str) -> Markup.Markup: ...
    @typing.overload
    def CreateMarkup(self) -> Markup.Markup: ...
    @typing.overload
    def CreateMarkup(self, markupName: str) -> Markup.Markup: ...
    def MakeActive(self, layer: Markup.Markup) -> None: ...
    def MakeInactive(self, layer: Markup.Markup) -> None: ...
    def GetActive(self) -> Markup.Markup: ...
    def CreateMarkupBuilder(self, layer: Markup.Markup) -> Markup.MarkupBuilder: ...
    def Tag(self) -> Tag: ...



class MarkupBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Active(self) -> bool: ...
    @Active.setter
    def Active(self, value: bool) -> None: ...
    @property
    def CaptureView(self) -> bool: ...
    @CaptureView.setter
    def CaptureView(self, value: bool) -> None: ...
    @property
    def MarkupName(self) -> str: ...
    @MarkupName.setter
    def MarkupName(self, value: str) -> None: ...


class Markup(DisplayableObject):
    def __init__(self) -> None: ...
    def GetElements(self) -> typing.List[Markup.Element]: ...
    def HideElements(self) -> None: ...
    def ShowElements(self) -> None: ...
    def HasCapturedView(self) -> bool: ...
    def CaptureView(self) -> None: ...
    def ApplyView(self) -> None: ...
    def DeleteView(self) -> None: ...
    def IsActive(self) -> bool: ...
    @property
    def Elements(self) -> Markup.ElementCollection: ...
    @Elements.setter
    def Elements(self, value: Markup.ElementCollection) -> None: ...


class Line(Markup.Element):
    def __init__(self) -> None: ...
    def GetEndpoints(self, startPoint: Point3d, endPoint: Point3d) -> None: ...
    def SetEndpoints(self, startPoint: Point3d, endPoint: Point3d) -> None: ...


class InsetImage(Markup.Element):
    def __init__(self) -> None: ...


class Icon(Markup.Element):
    def __init__(self) -> None: ...
    @property
    def IconName(self) -> str: ...
    @IconName.setter
    def IconName(self, value: str) -> None: ...
    @property
    def IconSize(self) -> Markup.Icon.Size: ...
    @IconSize.setter
    def IconSize(self, value: Markup.Icon.Size) -> None: ...


    class Size(enum.Enum):
        ExtraSmall= 0
        Small= 1
        Medium= 2
        Large= 3
    

class Freehand(Markup.Element):
    def __init__(self) -> None: ...
    def GetPoints(self, points: typing.List[Point3d]) -> None: ...
    def SetPoints(self, points: typing.List[Point3d]) -> None: ...


class Ellipse(Markup.Element):
    def __init__(self) -> None: ...
    def GetCenterAndRadius(self, center: Point3d, majorRadius: float, minorRadius: float) -> None: ...
    def SetCenterAndRadius(self, center: Point3d, majorRadius: float, minorRadius: float) -> None: ...


class ElementCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Markup.Element]: ...
    @typing.overload
    def __init__(self, owner: Markup.Markup) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, id: str) -> Markup.Element: ...
    @typing.overload
    def CreateCircle(self, center: Point3d, radius: float) -> Markup.Circle: ...
    @typing.overload
    def CreateCircle(self, center: Point2d, radius: float) -> Markup.Circle: ...
    @typing.overload
    def CreateCircle(self, anchorPoint: Point3d, center: Point3d, radius: float) -> Markup.Circle: ...
    @typing.overload
    def CreateCircle(self, anchorPoint: Point3d, center: Point2d, radius: float) -> Markup.Circle: ...
    @typing.overload
    def CreateEllipse(self, center: Point3d, major: float, minor: float) -> Markup.Ellipse: ...
    @typing.overload
    def CreateEllipse(self, center: Point2d, major: float, minor: float) -> Markup.Ellipse: ...
    @typing.overload
    def CreateEllipse(self, anchorPoint: Point3d, center: Point3d, major: float, minor: float) -> Markup.Ellipse: ...
    @typing.overload
    def CreateEllipse(self, anchorPoint: Point3d, center: Point2d, major: float, minor: float) -> Markup.Ellipse: ...
    @typing.overload
    def CreateRectangle(self, center: Point3d, length: float, width: float) -> Markup.Rectangle: ...
    @typing.overload
    def CreateRectangle(self, center: Point2d, length: float, width: float) -> Markup.Rectangle: ...
    @typing.overload
    def CreateRectangle(self, anchorPoint: Point3d, center: Point3d, length: float, width: float) -> Markup.Rectangle: ...
    @typing.overload
    def CreateRectangle(self, anchorPoint: Point3d, center: Point2d, length: float, width: float) -> Markup.Rectangle: ...
    @typing.overload
    def CreatePolyline(self, points: typing.List[Point3d]) -> Markup.Polyline: ...
    @typing.overload
    def CreatePolyline(self, points: typing.List[Point2d]) -> Markup.Polyline: ...
    @typing.overload
    def CreatePolyline(self, anchorPoint: Point3d, points: typing.List[Point3d]) -> Markup.Polyline: ...
    @typing.overload
    def CreatePolyline(self, anchorPoint: Point3d, points: typing.List[Point2d]) -> Markup.Polyline: ...
    @typing.overload
    def CreatePolygon(self, points: typing.List[Point3d]) -> Markup.Polygon: ...
    @typing.overload
    def CreatePolygon(self, points: typing.List[Point2d]) -> Markup.Polygon: ...
    @typing.overload
    def CreatePolygon(self, anchorPoint: Point3d, points: typing.List[Point3d]) -> Markup.Polygon: ...
    @typing.overload
    def CreatePolygon(self, anchorPoint: Point3d, points: typing.List[Point2d]) -> Markup.Polygon: ...
    @typing.overload
    def CreateFreehand(self, points: typing.List[Point3d]) -> Markup.Freehand: ...
    @typing.overload
    def CreateFreehand(self, points: typing.List[Point2d]) -> Markup.Freehand: ...
    @typing.overload
    def CreateFreehand(self, anchorPoint: Point3d, points: typing.List[Point3d]) -> Markup.Freehand: ...
    @typing.overload
    def CreateFreehand(self, anchorPoint: Point3d, points: typing.List[Point2d]) -> Markup.Freehand: ...
    def CreateFloatLine(self, startPoint: Point3d, endPoint: Point3d) -> Markup.Line: ...
    def CreateAnchoredLine(self, anchorPoint: Point3d, startPoint: Point3d, endPoint: Point3d) -> Markup.Line: ...
    @typing.overload
    def CreateText(self, position: Point3d, textContent: str) -> Markup.Text: ...
    @typing.overload
    def CreateText(self, position: Point2d, textContent: str) -> Markup.Text: ...
    @typing.overload
    def CreateIcon(self, position: Point3d, iconName: str, size: Markup.Icon.Size) -> Markup.Icon: ...
    @typing.overload
    def CreateIcon(self, position: Point2d, iconName: str, size: Markup.Icon.Size) -> Markup.Icon: ...
    @typing.overload
    def CreateIcon(self, anchorPoint: Point3d, position: Point3d, iconName: str, size: Markup.Icon.Size) -> Markup.Icon: ...
    @typing.overload
    def CreateIcon(self, anchorPoint: Point3d, position: Point2d, iconName: str, size: Markup.Icon.Size) -> Markup.Icon: ...
    def CreateInsetImage(self, position: Point3d, filename: str) -> Markup.InsetImage: ...
    def CreateElementBuilder(self, annotation: Markup.Element) -> Markup.ElementBuilder: ...
    def CreateEditElementDisplayBuilder(self, objects: typing.List[Markup.Element]) -> Markup.EditElementDisplayBuilder: ...
    def Tag(self) -> Tag: ...



class ElementBuilder(Builder):
    def __init__(self) -> None: ...
    def GetComment(self) -> str: ...
    def SetComment(self, comment: str) -> None: ...
    def GetEllipseSize(self, majorRadius: float, minorRadius: float) -> None: ...
    def SetEllipseSize(self, majorRadius: float, minorRadius: float) -> None: ...
    def SetFreehandShape(self, controlPoints: typing.List[Point3d]) -> None: ...
    def GetRectangleSize(self, length: float, width: float) -> None: ...
    def SetRectangleSize(self, length: float, width: float) -> None: ...
    def GetTextContent(self) -> str: ...
    def SetTextContent(self, comment: str) -> None: ...
    @property
    def CircleSize(self) -> float: ...
    @CircleSize.setter
    def CircleSize(self, value: float) -> None: ...
    @property
    def EnableBackground(self) -> bool: ...
    @EnableBackground.setter
    def EnableBackground(self, value: bool) -> None: ...
    @property
    def Geometries(self) -> SelectDisplayableObjectList: ...
    @Geometries.setter
    def Geometries(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def IconName(self) -> str: ...
    @IconName.setter
    def IconName(self, value: str) -> None: ...
    @property
    def LeaderLineFont(self) -> DisplayableObject.ObjectFont: ...
    @LeaderLineFont.setter
    def LeaderLineFont(self, value: DisplayableObject.ObjectFont) -> None: ...
    @property
    def LeaderLineWidth(self) -> DisplayableObject.ObjectWidth: ...
    @LeaderLineWidth.setter
    def LeaderLineWidth(self, value: DisplayableObject.ObjectWidth) -> None: ...
    @property
    def LineColor(self) -> NXColor: ...
    @LineColor.setter
    def LineColor(self, value: NXColor) -> None: ...
    @property
    def LineFont(self) -> DisplayableObject.ObjectFont: ...
    @LineFont.setter
    def LineFont(self, value: DisplayableObject.ObjectFont) -> None: ...
    @property
    def LineWidth(self) -> DisplayableObject.ObjectWidth: ...
    @LineWidth.setter
    def LineWidth(self, value: DisplayableObject.ObjectWidth) -> None: ...
    @property
    def Location(self) -> Point3d: ...
    @Location.setter
    def Location(self, value: Point3d) -> None: ...
    @property
    def PinToScreen(self) -> bool: ...
    @PinToScreen.setter
    def PinToScreen(self, value: bool) -> None: ...
    @property
    def Style(self) -> Markup.ElementBuilder.Styles: ...
    @Style.setter
    def Style(self, value: Markup.ElementBuilder.Styles) -> None: ...
    @property
    def TerminatingObjects(self) -> SelectDisplayableObjectList: ...
    @TerminatingObjects.setter
    def TerminatingObjects(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def TextFont(self) -> str: ...
    @TextFont.setter
    def TextFont(self, value: str) -> None: ...
    @property
    def TextFontStyle(self) -> Features.TextBuilder.FontStyleOptions: ...
    @TextFontStyle.setter
    def TextFontStyle(self, value: Features.TextBuilder.FontStyleOptions) -> None: ...
    @property
    def TextScale(self) -> Markup.Text.ScaleOptions: ...
    @TextScale.setter
    def TextScale(self, value: Markup.Text.ScaleOptions) -> None: ...


    class Styles(enum.Enum):
        Freehand= 0
        Text= 1
        Circle= 2
        Ellipse= 3
        Rectangle= 4
        Icon= 5
        Polyline= 6
        Polygon= 7
        Line= 8
        InsetImage= 9
    

class Element(DisplayableObject):
    def __init__(self) -> None: ...
    def GetLocation(self) -> Point3d: ...
    @typing.overload
    def SetLocation(self, location: Point3d) -> None: ...
    @typing.overload
    def SetLocation(self, location: Point2d) -> None: ...
    def GetAnchorPoint(self) -> Point3d: ...
    def SetAnchorPoint(self, anchorPoint: Point3d) -> None: ...
    def GetAnchorObjects(self) -> typing.List[DisplayableObject]: ...
    def SetAnchorObjects(self, anchorObjs: typing.List[DisplayableObject]) -> None: ...
    def GetTerminatingObjects(self) -> typing.List[DisplayableObject]: ...
    def SetTerminatingObjects(self, terminatingObjs: typing.List[DisplayableObject]) -> None: ...
    def GetParentMarkup(self) -> Markup.Markup: ...
    @property
    def Comment(self) -> str: ...
    @Comment.setter
    def Comment(self, value: str) -> None: ...
    @property
    def PinToScreen(self) -> bool: ...
    @PinToScreen.setter
    def PinToScreen(self, value: bool) -> None: ...


class EditElementDisplayBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def EnableBackground(self) -> bool: ...
    @EnableBackground.setter
    def EnableBackground(self, value: bool) -> None: ...
    @property
    def LineColor(self) -> int: ...
    @LineColor.setter
    def LineColor(self, value: int) -> None: ...
    @property
    def LineFont(self) -> DisplayableObject.ObjectFont: ...
    @LineFont.setter
    def LineFont(self, value: DisplayableObject.ObjectFont) -> None: ...
    @property
    def LineWidth(self) -> DisplayableObject.ObjectWidth: ...
    @LineWidth.setter
    def LineWidth(self, value: DisplayableObject.ObjectWidth) -> None: ...
    @property
    def TextFont(self) -> str: ...
    @TextFont.setter
    def TextFont(self, value: str) -> None: ...
    @property
    def TextFontStyle(self) -> Features.TextBuilder.FontStyleOptions: ...
    @TextFontStyle.setter
    def TextFontStyle(self, value: Features.TextBuilder.FontStyleOptions) -> None: ...
    @property
    def TextScale(self) -> Markup.Text.ScaleOptions: ...
    @TextScale.setter
    def TextScale(self, value: Markup.Text.ScaleOptions) -> None: ...


class Circle(Markup.Element):
    def __init__(self) -> None: ...
    def GetCenterAndRadius(self, center: Point3d, radius: float) -> None: ...
    def SetCenterAndRadius(self, center: Point3d, radius: float) -> None: ...


