from ....NXOpen import *
from ...Features import *

import typing
import enum

class TransformCageData(Builder):
    def __init__(self) -> None: ...
    def ResetFallOffToLinear(self) -> None: ...
    @property
    def CageManipulator(self) -> Features.Subdivision.CageManipulatorData: ...
    @CageManipulator.setter
    def CageManipulator(self, value: Features.Subdivision.CageManipulatorData) -> None: ...
    @property
    def CanMoveToolOnly(self) -> bool: ...
    @CanMoveToolOnly.setter
    def CanMoveToolOnly(self, value: bool) -> None: ...
    @property
    def CanRelocateToolToSelection(self) -> bool: ...
    @CanRelocateToolToSelection.setter
    def CanRelocateToolToSelection(self, value: bool) -> None: ...
    @property
    def CanReorientToolToSelection(self) -> bool: ...
    @CanReorientToolToSelection.setter
    def CanReorientToolToSelection(self, value: bool) -> None: ...
    @property
    def FallOffFactor(self) -> float: ...
    @FallOffFactor.setter
    def FallOffFactor(self, value: float) -> None: ...
    @property
    def FallOffMethod(self) -> Features.Subdivision.TransformCageData.FallOffMethodType: ...
    @FallOffMethod.setter
    def FallOffMethod(self, value: Features.Subdivision.TransformCageData.FallOffMethodType) -> None: ...
    @property
    def FallOffObjects(self) -> Features.Subdivision.SelectCageObjectData: ...
    @FallOffObjects.setter
    def FallOffObjects(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def MovementMethod(self) -> Features.Subdivision.TransformCageData.MovementMethodType: ...
    @MovementMethod.setter
    def MovementMethod(self, value: Features.Subdivision.TransformCageData.MovementMethodType) -> None: ...
    @property
    def MovementPlane(self) -> Plane: ...
    @MovementPlane.setter
    def MovementPlane(self, value: Plane) -> None: ...
    @property
    def MovementVector(self) -> Direction: ...
    @MovementVector.setter
    def MovementVector(self, value: Direction) -> None: ...
    @property
    def ScalingMethod(self) -> Features.Subdivision.TransformCageData.ScalingMethodType: ...
    @ScalingMethod.setter
    def ScalingMethod(self, value: Features.Subdivision.TransformCageData.ScalingMethodType) -> None: ...
    @property
    def TransformationMethod(self) -> Features.Subdivision.TransformCageData.TransformationMethodType: ...
    @TransformationMethod.setter
    def TransformationMethod(self, value: Features.Subdivision.TransformCageData.TransformationMethodType) -> None: ...
    @property
    def WCSOption(self) -> Features.Subdivision.TransformCageData.WCSOptionType: ...
    @WCSOption.setter
    def WCSOption(self, value: Features.Subdivision.TransformCageData.WCSOptionType) -> None: ...


    class WCSOptionType(enum.Enum):
        InferredAxis= 0
        X= 1
        Y= 2
        Z= 3
        YZ= 4
        XZ= 5
        XY= 6
    

    class TransformationMethodType(enum.Enum):
        Drag= 0
        Transform= 1
    

    class ScalingMethodType(enum.Enum):
        Linear= 0
        Planar= 1
        Uniform= 2
    

    class MovementMethodType(enum.Enum):
        WCS= 0
        View= 1
        Vector= 2
        Plane= 3
        Normal= 4
        Edge= 5
    

    class FallOffMethodType(enum.Enum):
        None_= 0
        Selected= 1
        All= 2
    

class SubdivisionTubeBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CrossSection(self) -> int: ...
    @CrossSection.setter
    def CrossSection(self, value: int) -> None: ...
    @property
    def EndCaps(self) -> Features.Subdivision.SubdivisionTubeBuilder.EndCapsType: ...
    @EndCaps.setter
    def EndCaps(self, value: Features.Subdivision.SubdivisionTubeBuilder.EndCapsType) -> None: ...
    @property
    def FalloffDistance(self) -> Expression: ...
    @FalloffDistance.setter
    def FalloffDistance(self, value: Expression) -> None: ...
    @property
    def GraphStructureObject(self) -> Features.Subdivision.SelectCageObjectData: ...
    @GraphStructureObject.setter
    def GraphStructureObject(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def NodeSize(self) -> Expression: ...
    @NodeSize.setter
    def NodeSize(self, value: Expression) -> None: ...
    @property
    def NumberOfSegments(self) -> int: ...
    @NumberOfSegments.setter
    def NumberOfSegments(self, value: int) -> None: ...
    @property
    def PathObject(self) -> Features.Subdivision.SelectCageObjectData: ...
    @PathObject.setter
    def PathObject(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def Rod(self) -> int: ...
    @Rod.setter
    def Rod(self, value: int) -> None: ...
    @property
    def RodSize(self) -> Expression: ...
    @RodSize.setter
    def RodSize(self, value: Expression) -> None: ...
    @property
    def Size(self) -> Expression: ...
    @Size.setter
    def Size(self, value: Expression) -> None: ...
    @property
    def Type(self) -> Features.Subdivision.SubdivisionTubeBuilder.Types: ...
    @Type.setter
    def Type(self, value: Features.Subdivision.SubdivisionTubeBuilder.Types) -> None: ...


    class Types(enum.Enum):
        SinglePath= 0
        BranchedPath= 1
    

    class EndCapsType(enum.Enum):
        None_= 0
        Flat= 1
        Round= 2
    

class SubdivisionSweepBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CanSew(self) -> bool: ...
    @CanSew.setter
    def CanSew(self, value: bool) -> None: ...
    @property
    def Continuity(self) -> Features.Subdivision.SubdivisionSweepBuilder.ContinuityType: ...
    @Continuity.setter
    def Continuity(self, value: Features.Subdivision.SubdivisionSweepBuilder.ContinuityType) -> None: ...
    @property
    def Guides(self) -> Features.Subdivision.CageSectionDataList: ...
    @Guides.setter
    def Guides(self, value: Features.Subdivision.CageSectionDataList) -> None: ...
    @property
    def Sections(self) -> Features.Subdivision.CageSectionDataList: ...
    @Sections.setter
    def Sections(self, value: Features.Subdivision.CageSectionDataList) -> None: ...


    class ContinuityType(enum.Enum):
        Smooth= 0
        Sharp= 1
    

class SubdivisionSubdivideFaceBuilder(Builder):
    def __init__(self) -> None: ...
    def Subdivide(self) -> None: ...
    @property
    def FacesToSubdivide(self) -> Features.Subdivision.SelectCageObjectData: ...
    @FacesToSubdivide.setter
    def FacesToSubdivide(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def Scale(self) -> Expression: ...
    @Scale.setter
    def Scale(self, value: Expression) -> None: ...


class SubdivisionSplitFaceBuilder(Builder):
    def __init__(self) -> None: ...
    def AddSplitPoint(self, location: Point3d, object: DisplayableObject) -> None: ...
    def ClearSplitPoints(self) -> None: ...
    def UpdateSplitPositions(self, splitLineIndex: int, positions: typing.List[Point3d]) -> None: ...
    @property
    def FacesToSplit(self) -> Features.Subdivision.SelectCageObjectData: ...
    @FacesToSplit.setter
    def FacesToSplit(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def Number(self) -> int: ...
    @Number.setter
    def Number(self, value: int) -> None: ...
    @property
    def ReferenceEdge(self) -> Features.Subdivision.SelectCageObjectData: ...
    @ReferenceEdge.setter
    def ReferenceEdge(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def Type(self) -> Features.Subdivision.SubdivisionSplitFaceBuilder.Types: ...
    @Type.setter
    def Type(self, value: Features.Subdivision.SubdivisionSplitFaceBuilder.Types) -> None: ...


    class Types(enum.Enum):
        Uniform= 0
        ThroughLines= 1
    

class SubdivisionSewCageBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def SelectedEdges1(self) -> Features.Subdivision.SelectCageObjectData: ...
    @SelectedEdges1.setter
    def SelectedEdges1(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def SelectedEdges2(self) -> Features.Subdivision.SelectCageObjectData: ...
    @SelectedEdges2.setter
    def SelectedEdges2(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...


class SubdivisionSetWeightBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def TargetObject(self) -> Features.Subdivision.SelectCageObjectData: ...
    @TargetObject.setter
    def TargetObject(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def WeightPercent(self) -> int: ...
    @WeightPercent.setter
    def WeightPercent(self, value: int) -> None: ...


class SubdivisionSetContinuityBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def ContinuityType(self) -> Features.Subdivision.SubdivisionSetContinuityBuilder.ContinuityTypes: ...
    @ContinuityType.setter
    def ContinuityType(self, value: Features.Subdivision.SubdivisionSetContinuityBuilder.ContinuityTypes) -> None: ...
    @property
    def TargetObject(self) -> Features.Subdivision.SelectCageObjectData: ...
    @TargetObject.setter
    def TargetObject(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...


    class ContinuityTypes(enum.Enum):
        Smooth= 0
        Sharp= 1
    

class SubdivisionRevolveBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AxisPoint(self) -> SelectNXObject: ...
    @AxisPoint.setter
    def AxisPoint(self, value: SelectNXObject) -> None: ...
    @property
    def AxisVector(self) -> Direction: ...
    @AxisVector.setter
    def AxisVector(self, value: Direction) -> None: ...
    @property
    def CanSew(self) -> bool: ...
    @CanSew.setter
    def CanSew(self, value: bool) -> None: ...
    @property
    def Continuity(self) -> Features.Subdivision.SubdivisionRevolveBuilder.ContinuityType: ...
    @Continuity.setter
    def Continuity(self, value: Features.Subdivision.SubdivisionRevolveBuilder.ContinuityType) -> None: ...
    @property
    def EndAngle(self) -> Expression: ...
    @EndAngle.setter
    def EndAngle(self, value: Expression) -> None: ...
    @property
    def NumOfSegments(self) -> int: ...
    @NumOfSegments.setter
    def NumOfSegments(self, value: int) -> None: ...
    @property
    def SectionObject(self) -> Features.Subdivision.SelectCageObjectData: ...
    @SectionObject.setter
    def SectionObject(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def StartAngle(self) -> Expression: ...
    @StartAngle.setter
    def StartAngle(self, value: Expression) -> None: ...


    class ContinuityType(enum.Enum):
        Smooth= 0
        Sharp= 1
    

class SubdivisionProjectCageBuilderEx(Builder):
    def __init__(self) -> None: ...
    def OnTargetDynamicPlane(self) -> None: ...
    def OnTargetPlane(self) -> None: ...
    def OnTargetAxis(self) -> None: ...
    @property
    def Mode(self) -> Features.Subdivision.SubdivisionProjectCageBuilderEx.ModeOptions: ...
    @Mode.setter
    def Mode(self, value: Features.Subdivision.SubdivisionProjectCageBuilderEx.ModeOptions) -> None: ...
    @property
    def ObjectsToProject(self) -> Features.Subdivision.SelectCageObjectData: ...
    @ObjectsToProject.setter
    def ObjectsToProject(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def ProjectBothSides(self) -> bool: ...
    @ProjectBothSides.setter
    def ProjectBothSides(self, value: bool) -> None: ...
    @property
    def ProjectionDirectionType(self) -> Features.Subdivision.SubdivisionProjectCageBuilderEx.ProjectionDirectionTypes: ...
    @ProjectionDirectionType.setter
    def ProjectionDirectionType(self, value: Features.Subdivision.SubdivisionProjectCageBuilderEx.ProjectionDirectionTypes) -> None: ...
    @property
    def ProjectionVector(self) -> Direction: ...
    @ProjectionVector.setter
    def ProjectionVector(self, value: Direction) -> None: ...
    @property
    def TargetAxis(self) -> Axis: ...
    @TargetAxis.setter
    def TargetAxis(self, value: Axis) -> None: ...
    @property
    def TargetCageObjects(self) -> Features.Subdivision.SelectCageObjectData: ...
    @TargetCageObjects.setter
    def TargetCageObjects(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def TargetCurves(self) -> SelectDisplayableObjectList: ...
    @TargetCurves.setter
    def TargetCurves(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def TargetDynamicPlane(self) -> CoordinateSystem: ...
    @TargetDynamicPlane.setter
    def TargetDynamicPlane(self, value: CoordinateSystem) -> None: ...
    @property
    def TargetFaces(self) -> SelectDisplayableObjectList: ...
    @TargetFaces.setter
    def TargetFaces(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def TargetPlane(self) -> Plane: ...
    @TargetPlane.setter
    def TargetPlane(self, value: Plane) -> None: ...
    @property
    def TargetType(self) -> Features.Subdivision.SubdivisionProjectCageBuilderEx.TargetTypes: ...
    @TargetType.setter
    def TargetType(self, value: Features.Subdivision.SubdivisionProjectCageBuilderEx.TargetTypes) -> None: ...
    @property
    def Type(self) -> Features.Subdivision.SubdivisionProjectCageBuilderEx.Types: ...
    @Type.setter
    def Type(self, value: Features.Subdivision.SubdivisionProjectCageBuilderEx.Types) -> None: ...


    class Types(enum.Enum):
        ToTarget= 0
        ToAverage= 1
        AlignNormal= 2
    

    class TargetTypes(enum.Enum):
        InferredPlane= 0
        InferredAxis= 1
        DynamicPlane= 2
        Plane= 3
        Axis= 4
        Curve= 5
        Face= 6
    

    class ProjectionDirectionTypes(enum.Enum):
        AlongNormal= 0
        AlongVector= 1
    

    class ModeOptions(enum.Enum):
        Linear= 0
        Planar= 1
    

class SubdivisionProjectCageBuilder(Builder):
    def __init__(self) -> None: ...
    def OnTargetPlane(self) -> None: ...
    def OnTargetDynamicPlane(self) -> None: ...
    @property
    def Mode(self) -> Features.Subdivision.SubdivisionProjectCageBuilder.ModeOptions: ...
    @Mode.setter
    def Mode(self, value: Features.Subdivision.SubdivisionProjectCageBuilder.ModeOptions) -> None: ...
    @property
    def ObjectsToProject(self) -> Features.Subdivision.SelectCageObjectData: ...
    @ObjectsToProject.setter
    def ObjectsToProject(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def Target(self) -> SelectDisplayableObject: ...
    @Target.setter
    def Target(self, value: SelectDisplayableObject) -> None: ...
    @property
    def TargetCageObjects(self) -> Features.Subdivision.SelectCageObjectData: ...
    @TargetCageObjects.setter
    def TargetCageObjects(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def TargetDynamicPlane(self) -> CoordinateSystem: ...
    @TargetDynamicPlane.setter
    def TargetDynamicPlane(self, value: CoordinateSystem) -> None: ...
    @property
    def TargetPlane(self) -> Plane: ...
    @TargetPlane.setter
    def TargetPlane(self, value: Plane) -> None: ...
    @property
    def TargetType(self) -> Features.Subdivision.SubdivisionProjectCageBuilder.TargetTypes: ...
    @TargetType.setter
    def TargetType(self, value: Features.Subdivision.SubdivisionProjectCageBuilder.TargetTypes) -> None: ...
    @property
    def Type(self) -> Features.Subdivision.SubdivisionProjectCageBuilder.Types: ...
    @Type.setter
    def Type(self, value: Features.Subdivision.SubdivisionProjectCageBuilder.Types) -> None: ...


    class Types(enum.Enum):
        ToTarget= 0
        ToAverage= 1
        AlignNormal= 2
    

    class TargetTypes(enum.Enum):
        InferredPlane= 0
        InferredAxis= 1
        YcZcPlane= 2
        XcZcPlane= 3
        XcYcPlane= 4
        XcAxis= 5
        YcAxis= 6
        ZcAxis= 7
        Object= 8
        Plane= 9
        DynamicPlane= 10
    

    class ModeOptions(enum.Enum):
        Linear= 0
        Planar= 1
    

class SubdivisionPrimitiveShapeBuilderEx(Builder):
    def __init__(self) -> None: ...
    def UpdateMesh(self) -> None: ...
    @property
    def CircularSegments(self) -> int: ...
    @CircularSegments.setter
    def CircularSegments(self, value: int) -> None: ...
    @property
    def Height(self) -> Expression: ...
    @Height.setter
    def Height(self, value: Expression) -> None: ...
    @property
    def HeightZ(self) -> Expression: ...
    @HeightZ.setter
    def HeightZ(self, value: Expression) -> None: ...
    @property
    def InnerSize(self) -> Expression: ...
    @InnerSize.setter
    def InnerSize(self, value: Expression) -> None: ...
    @property
    def LengthX(self) -> Expression: ...
    @LengthX.setter
    def LengthX(self, value: Expression) -> None: ...
    @property
    def LinearSegments(self) -> int: ...
    @LinearSegments.setter
    def LinearSegments(self, value: int) -> None: ...
    @property
    def Origin(self) -> Point: ...
    @Origin.setter
    def Origin(self, value: Point) -> None: ...
    @property
    def OuterSize(self) -> Expression: ...
    @OuterSize.setter
    def OuterSize(self, value: Expression) -> None: ...
    @property
    def RadialSegments(self) -> int: ...
    @RadialSegments.setter
    def RadialSegments(self, value: int) -> None: ...
    @property
    def Size(self) -> Expression: ...
    @Size.setter
    def Size(self, value: Expression) -> None: ...
    @property
    def SphereSubdivisionLevelOption(self) -> Features.Subdivision.SubdivisionPrimitiveShapeBuilderEx.SphereSubdivisionLevel: ...
    @SphereSubdivisionLevelOption.setter
    def SphereSubdivisionLevelOption(self, value: Features.Subdivision.SubdivisionPrimitiveShapeBuilderEx.SphereSubdivisionLevel) -> None: ...
    @property
    def Transformer(self) -> GeometricUtilities.TransformerData: ...
    @Transformer.setter
    def Transformer(self, value: GeometricUtilities.TransformerData) -> None: ...
    @property
    def Type(self) -> Features.Subdivision.SubdivisionPrimitiveShapeBuilderEx.Types: ...
    @Type.setter
    def Type(self, value: Features.Subdivision.SubdivisionPrimitiveShapeBuilderEx.Types) -> None: ...
    @property
    def WidthY(self) -> Expression: ...
    @WidthY.setter
    def WidthY(self, value: Expression) -> None: ...
    @property
    def XSegments(self) -> int: ...
    @XSegments.setter
    def XSegments(self, value: int) -> None: ...
    @property
    def YSegments(self) -> int: ...
    @YSegments.setter
    def YSegments(self, value: int) -> None: ...
    @property
    def ZSegments(self) -> int: ...
    @ZSegments.setter
    def ZSegments(self, value: int) -> None: ...


    class Types(enum.Enum):
        Sphere= 0
        Cylinder= 1
        Block= 2
        Circle= 3
        Rectangle= 4
        Torus= 5
    

    class SphereSubdivisionLevel(enum.Enum):
        Base= 0
        First= 1
        Second= 2
    

class SubdivisionPrimitiveShapeBuilder(Builder):
    def __init__(self) -> None: ...
    def UpdateMesh(self) -> None: ...
    @property
    def CircularSegments(self) -> int: ...
    @CircularSegments.setter
    def CircularSegments(self, value: int) -> None: ...
    @property
    def Height(self) -> Expression: ...
    @Height.setter
    def Height(self, value: Expression) -> None: ...
    @property
    def HeightZ(self) -> Expression: ...
    @HeightZ.setter
    def HeightZ(self, value: Expression) -> None: ...
    @property
    def InnerSize(self) -> Expression: ...
    @InnerSize.setter
    def InnerSize(self, value: Expression) -> None: ...
    @property
    def LengthX(self) -> Expression: ...
    @LengthX.setter
    def LengthX(self, value: Expression) -> None: ...
    @property
    def Origin(self) -> Point: ...
    @Origin.setter
    def Origin(self, value: Point) -> None: ...
    @property
    def OuterSize(self) -> Expression: ...
    @OuterSize.setter
    def OuterSize(self, value: Expression) -> None: ...
    @property
    def RadialSegments(self) -> int: ...
    @RadialSegments.setter
    def RadialSegments(self, value: int) -> None: ...
    @property
    def Size(self) -> Expression: ...
    @Size.setter
    def Size(self, value: Expression) -> None: ...
    @property
    def Transformer(self) -> GeometricUtilities.TransformerData: ...
    @Transformer.setter
    def Transformer(self, value: GeometricUtilities.TransformerData) -> None: ...
    @property
    def Type(self) -> Features.Subdivision.SubdivisionPrimitiveShapeBuilder.Types: ...
    @Type.setter
    def Type(self, value: Features.Subdivision.SubdivisionPrimitiveShapeBuilder.Types) -> None: ...
    @property
    def WidthY(self) -> Expression: ...
    @WidthY.setter
    def WidthY(self, value: Expression) -> None: ...


    class Types(enum.Enum):
        Sphere= 0
        Cylinder= 1
        Block= 2
        Circle= 3
        Rectangle= 4
        Torus= 5
    

class SubdivisionMergeFaceBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def FacesToMerge(self) -> Features.Subdivision.SelectCageObjectData: ...
    @FacesToMerge.setter
    def FacesToMerge(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...


class SubdivisionLoftBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CanSew(self) -> bool: ...
    @CanSew.setter
    def CanSew(self, value: bool) -> None: ...
    @property
    def Continuity(self) -> Features.Subdivision.SubdivisionLoftBuilder.ContinuityType: ...
    @Continuity.setter
    def Continuity(self, value: Features.Subdivision.SubdivisionLoftBuilder.ContinuityType) -> None: ...
    @property
    def IsClosed(self) -> bool: ...
    @IsClosed.setter
    def IsClosed(self, value: bool) -> None: ...
    @property
    def NumberOfSegments(self) -> int: ...
    @NumberOfSegments.setter
    def NumberOfSegments(self, value: int) -> None: ...
    @property
    def Sections(self) -> Features.Subdivision.CageSectionDataList: ...
    @Sections.setter
    def Sections(self, value: Features.Subdivision.CageSectionDataList) -> None: ...


    class ContinuityType(enum.Enum):
        Smooth= 0
        Sharp= 1
    

class SubdivisionFillBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CanConnectSymmetrically(self) -> bool: ...
    @CanConnectSymmetrically.setter
    def CanConnectSymmetrically(self, value: bool) -> None: ...
    @property
    def Continuity(self) -> Features.Subdivision.SubdivisionFillBuilder.ContinuityType: ...
    @Continuity.setter
    def Continuity(self, value: Features.Subdivision.SubdivisionFillBuilder.ContinuityType) -> None: ...
    @property
    def SelectedEdges(self) -> Features.Subdivision.SelectCageObjectData: ...
    @SelectedEdges.setter
    def SelectedEdges(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...


    class ContinuityType(enum.Enum):
        Smooth= 0
        Sharp= 1
    

class SubdivisionExtrudeCageBuilder(Builder):
    def __init__(self) -> None: ...
    def Extrude(self) -> None: ...
    @property
    def CanMoveToolOnly(self) -> bool: ...
    @CanMoveToolOnly.setter
    def CanMoveToolOnly(self, value: bool) -> None: ...
    @property
    def CanRelocateToolToSelection(self) -> bool: ...
    @CanRelocateToolToSelection.setter
    def CanRelocateToolToSelection(self, value: bool) -> None: ...
    @property
    def CanReorientToolToSelection(self) -> bool: ...
    @CanReorientToolToSelection.setter
    def CanReorientToolToSelection(self, value: bool) -> None: ...
    @property
    def Continuity(self) -> Features.Subdivision.SubdivisionExtrudeCageBuilder.ContinuityType: ...
    @Continuity.setter
    def Continuity(self, value: Features.Subdivision.SubdivisionExtrudeCageBuilder.ContinuityType) -> None: ...
    @property
    def DirectionOption(self) -> Features.Subdivision.SubdivisionExtrudeCageBuilder.DirectionType: ...
    @DirectionOption.setter
    def DirectionOption(self, value: Features.Subdivision.SubdivisionExtrudeCageBuilder.DirectionType) -> None: ...
    @property
    def Distance(self) -> Expression: ...
    @Distance.setter
    def Distance(self, value: Expression) -> None: ...
    @property
    def NumberOfSegments(self) -> int: ...
    @NumberOfSegments.setter
    def NumberOfSegments(self, value: int) -> None: ...
    @property
    def ScalingMethod(self) -> Features.Subdivision.SubdivisionExtrudeCageBuilder.ScalingMethodType: ...
    @ScalingMethod.setter
    def ScalingMethod(self, value: Features.Subdivision.SubdivisionExtrudeCageBuilder.ScalingMethodType) -> None: ...
    @property
    def SelectionObject(self) -> Features.Subdivision.SelectCageObjectData: ...
    @SelectionObject.setter
    def SelectionObject(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def TransformationMethod(self) -> Features.Subdivision.SubdivisionExtrudeCageBuilder.TransformationMethodType: ...
    @TransformationMethod.setter
    def TransformationMethod(self, value: Features.Subdivision.SubdivisionExtrudeCageBuilder.TransformationMethodType) -> None: ...
    @property
    def Transformer(self) -> GeometricUtilities.TransformerData: ...
    @Transformer.setter
    def Transformer(self, value: GeometricUtilities.TransformerData) -> None: ...
    @property
    def Vector(self) -> Direction: ...
    @Vector.setter
    def Vector(self, value: Direction) -> None: ...


    class TransformationMethodType(enum.Enum):
        DragLinear= 0
        Transform= 1
    

    class ScalingMethodType(enum.Enum):
        Linear= 0
        Planar= 1
        Uniform= 2
    

    class DirectionType(enum.Enum):
        Inferred= 0
        Vector= 1
        Perpendicular= 2
    

    class ContinuityType(enum.Enum):
        Smooth= 0
        Sharp= 1
    

class SubdivisionDeleteObjectBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Objects(self) -> Features.Subdivision.SelectCageObjectData: ...
    @Objects.setter
    def Objects(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...


class SubdivisionDeleteFaceBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def FaceToDelete(self) -> Features.Subdivision.SelectCageObjectData: ...
    @FaceToDelete.setter
    def FaceToDelete(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...


class SubdivisionDeleteCageBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def SelectCageObject(self) -> Features.Subdivision.SelectCageObjectData: ...
    @SelectCageObject.setter
    def SelectCageObject(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...


class SubdivisionConnectCageBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CageEdgeToEdit(self) -> Features.Subdivision.SelectCageObjectData: ...
    @CageEdgeToEdit.setter
    def CageEdgeToEdit(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def ContinuityType(self) -> Features.Subdivision.SubdivisionConnectCageBuilder.ContinuityTypes: ...
    @ContinuityType.setter
    def ContinuityType(self, value: Features.Subdivision.SubdivisionConnectCageBuilder.ContinuityTypes) -> None: ...
    @property
    def ExternalReference(self) -> Section: ...
    @ExternalReference.setter
    def ExternalReference(self, value: Section) -> None: ...


    class ContinuityTypes(enum.Enum):
        Smooth= 0
        Sharp= 1
    

class SubdivisionBridgeFaceBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Continuity(self) -> Features.Subdivision.SubdivisionBridgeFaceBuilder.ContinuityType: ...
    @Continuity.setter
    def Continuity(self, value: Features.Subdivision.SubdivisionBridgeFaceBuilder.ContinuityType) -> None: ...
    @property
    def FaceSet1(self) -> Features.Subdivision.SelectCageObjectData: ...
    @FaceSet1.setter
    def FaceSet1(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def FaceSet2(self) -> Features.Subdivision.SelectCageObjectData: ...
    @FaceSet2.setter
    def FaceSet2(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def NumSegments(self) -> int: ...
    @NumSegments.setter
    def NumSegments(self, value: int) -> None: ...


    class ContinuityType(enum.Enum):
        Smooth= 0
        Sharp= 1
    

class SubdivisionBodyCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Features.Subdivision.SubdivisionBody]: ...
    @typing.overload
    def __init__(self, owner: Part) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateSubdivisionPrimitiveShapeBuilder(self) -> Features.Subdivision.SubdivisionPrimitiveShapeBuilder: ...
    def CreateSubdivisionPrimitiveShapeBuilderEx(self) -> Features.Subdivision.SubdivisionPrimitiveShapeBuilderEx: ...
    def CreateSubdivisionExtrudeCageBuilder(self) -> Features.Subdivision.SubdivisionExtrudeCageBuilder: ...
    def CreateSubdivisionSetWeightBuilder(self) -> Features.Subdivision.SubdivisionSetWeightBuilder: ...
    def CreateSubdivisionSetContinuityBuilder(self) -> Features.Subdivision.SubdivisionSetContinuityBuilder: ...
    def CreateSubdivisionDeleteFaceBuilder(self) -> Features.Subdivision.SubdivisionDeleteFaceBuilder: ...
    def CreateTransformCageData(self) -> Features.Subdivision.TransformCageData: ...
    def CreateSubdivisionFillBuilder(self) -> Features.Subdivision.SubdivisionFillBuilder: ...
    def CreateSubdivisionBridgeFaceBuilder(self) -> Features.Subdivision.SubdivisionBridgeFaceBuilder: ...
    def CreateStartSymmetricModelingBuilder(self) -> Features.Subdivision.StartSymmetricModelingBuilder: ...
    def StopSymmetricModeling(self) -> None: ...
    def CreateSubdivisionProjectCageBuilder(self) -> Features.Subdivision.SubdivisionProjectCageBuilder: ...
    def CreateSubdivisionProjectCageBuilderEx(self) -> Features.Subdivision.SubdivisionProjectCageBuilderEx: ...
    def CreateSubdivisionMergeFaceBuilder(self) -> Features.Subdivision.SubdivisionMergeFaceBuilder: ...
    def CreateSubdivisionSplitFaceBuilder(self) -> Features.Subdivision.SubdivisionSplitFaceBuilder: ...
    def CreateSubdivisionSubdivideFaceBuilder(self) -> Features.Subdivision.SubdivisionSubdivideFaceBuilder: ...
    def CreateImportSubdivisionGeometryBuilder(self) -> Features.Subdivision.ImportSubdivisionGeometryBuilder: ...
    def CreateCagePolylineBuilder(self, polyline: Polyline) -> Features.Subdivision.CagePolylineBuilder: ...
    def CreateExtractCagePolylineBuilder(self) -> Features.Subdivision.ExtractCagePolylineBuilder: ...
    def CreateSubdivisionRevolveBuilder(self) -> Features.Subdivision.SubdivisionRevolveBuilder: ...
    def CreateSubdivisionTubeBuilder(self) -> Features.Subdivision.SubdivisionTubeBuilder: ...
    def CreateCopyCageBuilder(self) -> Features.Subdivision.CopyCageBuilder: ...
    def CreateEmptyCageSectionBuilder(self) -> Features.Subdivision.CageSectionData: ...
    def CreateSubdivisionLoftBuilder(self) -> Features.Subdivision.SubdivisionLoftBuilder: ...
    def CreateSubdivisionSweepBuilder(self) -> Features.Subdivision.SubdivisionSweepBuilder: ...
    def CreateSubdivisionSewCageBuilder(self) -> Features.Subdivision.SubdivisionSewCageBuilder: ...
    def CreateSubdivisionDeleteCageBuilder(self) -> Features.Subdivision.SubdivisionDeleteCageBuilder: ...
    def CreateSplitSubdivisionBodyBuilder(self) -> Features.Subdivision.SplitSubdivisionBodyBuilder: ...
    def CreateMergeSubdivisionBodiesBuilder(self) -> Features.Subdivision.MergeSubdivisionBodiesBuilder: ...
    def CreateCopyCageData(self) -> Features.Subdivision.CopyCageData: ...
    def CreatePasteCageData(self) -> Features.Subdivision.PasteCageData: ...
    def CreateDefineWorkRegionBuilder(self) -> Features.Subdivision.DefineWorkRegionBuilder: ...
    def CreateMirrorCageBuilder(self) -> Features.Subdivision.MirrorCageBuilder: ...
    def CreateOffsetCageBuilder(self) -> Features.Subdivision.OffsetCageBuilder: ...
    def CreateSubdivisionDeleteObjectBuilder(self) -> Features.Subdivision.SubdivisionDeleteObjectBuilder: ...
    def CreateDeleteConstraintBuilder(self) -> Features.Subdivision.DeleteConstraintBuilder: ...
    def CreateSubdivisionConnectCageBuilder(self) -> Features.Subdivision.SubdivisionConnectCageBuilder: ...
    def CreateExportSubdivisionGeometryBuilder(self) -> Features.Subdivision.ExportSubdivisionGeometryBuilder: ...
    def CreateDrawCageData(self) -> Features.Subdivision.DrawCageData: ...
    def CreateSectionTubeData(self) -> Features.Subdivision.SectionTubeData: ...
    def CreateCageFromFacetBodyBuilder(self) -> Features.Subdivision.CageFromFacetBodyBuilder: ...
    def Tag(self) -> Tag: ...



class SubdivisionBody(Features.BodyFeature):
    def __init__(self) -> None: ...


class StartSymmetricModelingBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def EdgesToProject(self) -> Features.Subdivision.SelectCageObjectData: ...
    @EdgesToProject.setter
    def EdgesToProject(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def MirrorProcedureOptions(self) -> Features.Subdivision.StartSymmetricModelingBuilder.MirrorProcedureOption: ...
    @MirrorProcedureOptions.setter
    def MirrorProcedureOptions(self, value: Features.Subdivision.StartSymmetricModelingBuilder.MirrorProcedureOption) -> None: ...
    @property
    def Plane(self) -> Plane: ...
    @Plane.setter
    def Plane(self, value: Plane) -> None: ...
    @property
    def SwitchSide(self) -> bool: ...
    @SwitchSide.setter
    def SwitchSide(self, value: bool) -> None: ...


    class MirrorProcedureOption(enum.Enum):
        CutBody= 0
        ProjectEdge= 1
    

class SplitSubdivisionBodyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def InputBodyOption(self) -> Features.Subdivision.SplitSubdivisionBodyBuilder.InputBodyOptions: ...
    @InputBodyOption.setter
    def InputBodyOption(self, value: Features.Subdivision.SplitSubdivisionBodyBuilder.InputBodyOptions) -> None: ...
    @property
    def SubdivisionBodiesToSplit(self) -> Features.Subdivision.SelectSubdivisionBodyList: ...
    @SubdivisionBodiesToSplit.setter
    def SubdivisionBodiesToSplit(self, value: Features.Subdivision.SelectSubdivisionBodyList) -> None: ...


    class InputBodyOptions(enum.Enum):
        Keep= 0
        Hide= 1
        Delete= 2
    

class SelectSubdivisionBodyList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Add(self, object: Features.Subdivision.SubdivisionBody) -> bool: ...
    @typing.overload
    def Add(self, objects: typing.List[Features.Subdivision.SubdivisionBody]) -> bool: ...
    @typing.overload
    def Add(self, inputSelectionMethod: SelectionMethod) -> bool: ...
    @typing.overload
    def Add(self, selection: Features.Subdivision.SubdivisionBody, view: View, point: Point3d) -> bool: ...
    @typing.overload
    def Remove(self, object: Features.Subdivision.SubdivisionBody) -> bool: ...
    @typing.overload
    def Remove(self, object: Features.Subdivision.SubdivisionBody, view: View) -> bool: ...
    @typing.overload
    def Remove(self, snapType: InferSnapType.SnapType, selection1: Features.Subdivision.SubdivisionBody, view1: View, point1: Point3d, selection2: Features.Subdivision.SubdivisionBody, view2: View, point2: Point3d) -> bool: ...
    def RemoveArray(self, objects: typing.List[Features.Subdivision.SubdivisionBody]) -> bool: ...
    @typing.overload
    def Remove(self, inputSelectionMethod: SelectionMethod) -> bool: ...
    def Clear(self) -> None: ...
    def Contains(self, object: Features.Subdivision.SubdivisionBody) -> bool: ...
    def SetArray(self, objects: typing.List[Features.Subdivision.SubdivisionBody]) -> None: ...
    def GetArray(self) -> typing.List[Features.Subdivision.SubdivisionBody]: ...
    def GetSelectObjectArray(self) -> typing.List[SelectObject]: ...
    @typing.overload
    def Add(self, snapType: InferSnapType.SnapType, selection1: Features.Subdivision.SubdivisionBody, view1: View, point1: Point3d, selection2: Features.Subdivision.SubdivisionBody, view2: View, point2: Point3d) -> bool: ...
    @typing.overload
    def Add(self, selection: Features.Subdivision.SubdivisionBody, caeSubType: CaeObjectType.CaeSubType, caeSubId: int) -> bool: ...
    def Validate(self) -> bool: ...
    @property
    def DuplicatesAllowed(self) -> bool: ...
    @DuplicatesAllowed.setter
    def DuplicatesAllowed(self, value: bool) -> None: ...
    @property
    def Size(self) -> int: ...
    @Size.setter
    def Size(self, value: int) -> None: ...


class SelectCageObjectData(TaggedObject):
    def __init__(self) -> None: ...
    def ClearAndAdd(self, objects: typing.List[NXObject], view: View, point: Point3d) -> None: ...
    def SetCursorLocation(self, point: Point3d) -> None: ...
    def SetViewDirection(self, direction: Vector3d) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def CanDeselectObjectsAutomatically(self) -> bool: ...
    @CanDeselectObjectsAutomatically.setter
    def CanDeselectObjectsAutomatically(self, value: bool) -> None: ...
    @property
    def SelectionList(self) -> SelectDisplayableObjectList: ...
    @SelectionList.setter
    def SelectionList(self, value: SelectDisplayableObjectList) -> None: ...


class SectionTubeData(Builder):
    def __init__(self) -> None: ...
    def AddSection(self, selectionData: Features.Subdivision.SectionTubeData.SelectionData) -> None: ...
    def RefitSection(self) -> None: ...
    @property
    def Segments(self) -> int: ...
    @Segments.setter
    def Segments(self, value: int) -> None: ...
    @property
    def Transformer(self) -> GeometricUtilities.TransformerData: ...
    @Transformer.setter
    def Transformer(self, value: GeometricUtilities.TransformerData) -> None: ...


    class SectionTubeDataSelectionData():
        @property
        def SnappedObject(self) -> NXObject: ...
        @SnappedObject.setter
        def SnappedObject(self, value: NXObject) -> None: ...
        @property
        def IsSnapped(self) -> bool: ...
        @IsSnapped.setter
        def IsSnapped(self, value: bool) -> None: ...
        @property
        def SnappedPosition(self) -> Point3d: ...
        @SnappedPosition.setter
        def SnappedPosition(self, value: Point3d) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, SnappedObject: NXObject, IsSnapped: bool, SnappedPosition: Point3d) -> None: ...
    

    class SectionTubeData_SelectionData():
        @property
        def snappedObject(self) -> Tag: ...
        @snappedObject.setter
        def snappedObject(self, value: Tag) -> None: ...
        @property
        def isSnapped(self) -> bool: ...
        @isSnapped.setter
        def isSnapped(self, value: bool) -> None: ...
        @property
        def snappedPosition(self) -> Point3d: ...
        @snappedPosition.setter
        def snappedPosition(self, value: Point3d) -> None: ...
    

class PasteCageData(Builder):
    def __init__(self) -> None: ...
    @property
    def CanMoveToolOnly(self) -> bool: ...
    @CanMoveToolOnly.setter
    def CanMoveToolOnly(self, value: bool) -> None: ...
    @property
    def Transformer(self) -> GeometricUtilities.TransformerData: ...
    @Transformer.setter
    def Transformer(self, value: GeometricUtilities.TransformerData) -> None: ...


class OffsetCageBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CanReverseOffsetDirection(self) -> bool: ...
    @CanReverseOffsetDirection.setter
    def CanReverseOffsetDirection(self, value: bool) -> None: ...
    @property
    def NumberOfCopies(self) -> int: ...
    @NumberOfCopies.setter
    def NumberOfCopies(self, value: int) -> None: ...
    @property
    def Objects(self) -> Features.Subdivision.SelectCageObjectData: ...
    @Objects.setter
    def Objects(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def OffsetDistance(self) -> Expression: ...
    @OffsetDistance.setter
    def OffsetDistance(self, value: Expression) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MirrorCageBuilder(Builder):
    def __init__(self) -> None: ...
    def UpdateOnMirrorPlane(self) -> None: ...
    @property
    def MirrorPlane(self) -> Plane: ...
    @MirrorPlane.setter
    def MirrorPlane(self, value: Plane) -> None: ...
    @property
    def Objects(self) -> Features.Subdivision.SelectCageObjectData: ...
    @Objects.setter
    def Objects(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...


class MergeSubdivisionBodiesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def InputBodyOption(self) -> Features.Subdivision.MergeSubdivisionBodiesBuilder.InputBodyOptions: ...
    @InputBodyOption.setter
    def InputBodyOption(self, value: Features.Subdivision.MergeSubdivisionBodiesBuilder.InputBodyOptions) -> None: ...
    @property
    def SubdivisionBodiesToMerge(self) -> Features.Subdivision.SelectSubdivisionBodyList: ...
    @SubdivisionBodiesToMerge.setter
    def SubdivisionBodiesToMerge(self, value: Features.Subdivision.SelectSubdivisionBodyList) -> None: ...


    class InputBodyOptions(enum.Enum):
        Keep= 0
        Hide= 1
        Delete= 2
    

class ImportSubdivisionGeometryBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CanCreateSingleFeature(self) -> bool: ...
    @CanCreateSingleFeature.setter
    def CanCreateSingleFeature(self, value: bool) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...


class ExtractCagePolylineBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CurveToExtract(self) -> ScCollector: ...
    @CurveToExtract.setter
    def CurveToExtract(self, value: ScCollector) -> None: ...
    @property
    def InputCurveOptions(self) -> Features.Subdivision.ExtractCagePolylineBuilder.InputCurveOption: ...
    @InputCurveOptions.setter
    def InputCurveOptions(self, value: Features.Subdivision.ExtractCagePolylineBuilder.InputCurveOption) -> None: ...
    @property
    def NumberOfSegments(self) -> int: ...
    @NumberOfSegments.setter
    def NumberOfSegments(self, value: int) -> None: ...


    class InputCurveOption(enum.Enum):
        Keep= 0
        Hide= 1
        Delete= 2
    

class ExportSubdivisionGeometryBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def FeatureSet(self) -> Features.SelectFeatureList: ...
    @FeatureSet.setter
    def FeatureSet(self, value: Features.SelectFeatureList) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...


class DrawCageData(Builder):
    def __init__(self) -> None: ...
    def AddVertex(self, selectionData: Features.Subdivision.DrawCageData.SelectionData) -> None: ...
    def ClosePolygon(self) -> None: ...
    def ResetStartPoint(self) -> None: ...
    @property
    def CageManipulator(self) -> Features.Subdivision.CageManipulatorData: ...
    @CageManipulator.setter
    def CageManipulator(self, value: Features.Subdivision.CageManipulatorData) -> None: ...
    @property
    def FaceShape(self) -> Features.Subdivision.DrawCageData.FaceShapeType: ...
    @FaceShape.setter
    def FaceShape(self, value: Features.Subdivision.DrawCageData.FaceShapeType) -> None: ...


    class DrawCageDataSelectionData():
        @property
        def SnappedObject(self) -> NXObject: ...
        @SnappedObject.setter
        def SnappedObject(self, value: NXObject) -> None: ...
        @property
        def SnappedPosition(self) -> Point3d: ...
        @SnappedPosition.setter
        def SnappedPosition(self, value: Point3d) -> None: ...
        @property
        def IsInferringPaused(self) -> bool: ...
        @IsInferringPaused.setter
        def IsInferringPaused(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, SnappedObject: NXObject, SnappedPosition: Point3d, IsInferringPaused: bool) -> None: ...
    

    class FaceShapeType(enum.Enum):
        Quad= 0
        Polygon= 1
    

    class DrawCageData_SelectionData():
        @property
        def snappedObject(self) -> Tag: ...
        @snappedObject.setter
        def snappedObject(self, value: Tag) -> None: ...
        @property
        def snappedPosition(self) -> Point3d: ...
        @snappedPosition.setter
        def snappedPosition(self, value: Point3d) -> None: ...
        @property
        def isInferringPaused(self) -> bool: ...
        @isInferringPaused.setter
        def isInferringPaused(self, value: bool) -> None: ...
    

class DeleteConstraintBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Objects(self) -> Features.Subdivision.SelectCageObjectData: ...
    @Objects.setter
    def Objects(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...


class DefineWorkRegionBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def FrozenColor(self) -> NXColor: ...
    @FrozenColor.setter
    def FrozenColor(self, value: NXColor) -> None: ...
    @property
    def FrozenRegionDefinitionMethod(self) -> Features.Subdivision.DefineWorkRegionBuilder.FrozenRegionDefinitionMethods: ...
    @FrozenRegionDefinitionMethod.setter
    def FrozenRegionDefinitionMethod(self, value: Features.Subdivision.DefineWorkRegionBuilder.FrozenRegionDefinitionMethods) -> None: ...
    @property
    def WorkRegionDefinitionMethod(self) -> Features.Subdivision.DefineWorkRegionBuilder.WorkRegionDefinitionMethods: ...
    @WorkRegionDefinitionMethod.setter
    def WorkRegionDefinitionMethod(self, value: Features.Subdivision.DefineWorkRegionBuilder.WorkRegionDefinitionMethods) -> None: ...
    @property
    def WorkRegionObjects(self) -> Features.Subdivision.SelectCageObjectData: ...
    @WorkRegionObjects.setter
    def WorkRegionObjects(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...


    class WorkRegionDefinitionMethods(enum.Enum):
        All= 0
        Selected= 1
    

    class FrozenRegionDefinitionMethods(enum.Enum):
        Hidden= 0
        Colored= 1
    

class CopyCageData(Builder):
    def __init__(self) -> None: ...
    def GetObjects(self) -> typing.List[NXObject]: ...
    def SetObjects(self, objects: typing.List[NXObject]) -> None: ...


class CopyCageBuilder(Builder):
    def __init__(self) -> None: ...
    def ResetTransformerToCentroidOfSelection(self) -> None: ...
    def SetTransformerToObject(self, selectionData: Features.Subdivision.CageManipulatorData.ObjectSelectionData) -> None: ...
    @property
    def CanMoveToolOnly(self) -> bool: ...
    @CanMoveToolOnly.setter
    def CanMoveToolOnly(self, value: bool) -> None: ...
    @property
    def CanRelocateToolToSelection(self) -> bool: ...
    @CanRelocateToolToSelection.setter
    def CanRelocateToolToSelection(self, value: bool) -> None: ...
    @property
    def CanReorientToolToSelection(self) -> bool: ...
    @CanReorientToolToSelection.setter
    def CanReorientToolToSelection(self, value: bool) -> None: ...
    @property
    def NumberOfCopies(self) -> int: ...
    @NumberOfCopies.setter
    def NumberOfCopies(self, value: int) -> None: ...
    @property
    def Objects(self) -> Features.Subdivision.SelectCageObjectData: ...
    @Objects.setter
    def Objects(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...
    @property
    def Transformer(self) -> GeometricUtilities.TransformerData: ...
    @Transformer.setter
    def Transformer(self, value: GeometricUtilities.TransformerData) -> None: ...


class CageSectionDataList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[Features.Subdivision.CageSectionData]) -> None: ...
    @typing.overload
    def Append(self, object: Features.Subdivision.CageSectionData) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: Features.Subdivision.CageSectionData) -> int: ...
    def FindItem(self, index: int) -> Features.Subdivision.CageSectionData: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: Features.Subdivision.CageSectionData) -> None: ...
    @typing.overload
    def Erase(self, obj: Features.Subdivision.CageSectionData, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[Features.Subdivision.CageSectionData]: ...
    def SetContents(self, objects: typing.List[Features.Subdivision.CageSectionData]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: Features.Subdivision.CageSectionData, object2: Features.Subdivision.CageSectionData) -> None: ...
    def Insert(self, location: int, object: Features.Subdivision.CageSectionData) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class CageSectionData(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def CanReverseDirection(self) -> bool: ...
    @CanReverseDirection.setter
    def CanReverseDirection(self, value: bool) -> None: ...
    @property
    def SelectionObject(self) -> Features.Subdivision.SelectCageObjectData: ...
    @SelectionObject.setter
    def SelectionObject(self, value: Features.Subdivision.SelectCageObjectData) -> None: ...


class CagePolylineBuilder(Features.PolylineBuilder):
    def __init__(self) -> None: ...


class CageManipulatorData(Features.Subdivision.SelectCageObjectData):
    def __init__(self) -> None: ...
    def PrepareToMove(self, moveData: Features.Subdivision.CageManipulatorData.ObjectMoveData) -> None: ...
    @typing.overload
    def Move(self, moveToPoint: Point3d, isSnapGesture: bool) -> None: ...
    @typing.overload
    def Move(self, moveToPoint: Point3d, point: Point, isSnapGesture: bool) -> None: ...
    def EndMove(self) -> None: ...
    def StepMove(self, step: float) -> None: ...
    def ResetTransformerToCentroidOfSelection(self) -> None: ...
    def SetTransformerToObject(self, selectionData: Features.Subdivision.CageManipulatorData.ObjectSelectionData) -> None: ...
    @property
    def Transformer(self) -> GeometricUtilities.TransformerData: ...
    @Transformer.setter
    def Transformer(self, value: GeometricUtilities.TransformerData) -> None: ...


    class CageManipulatorDataObjectSelectionData():
        @property
        def SelectedObject(self) -> NXObject: ...
        @SelectedObject.setter
        def SelectedObject(self, value: NXObject) -> None: ...
        @property
        def SelectionPosition(self) -> Point3d: ...
        @SelectionPosition.setter
        def SelectionPosition(self, value: Point3d) -> None: ...
        @property
        def ViewDirection(self) -> Vector3d: ...
        @ViewDirection.setter
        def ViewDirection(self, value: Vector3d) -> None: ...
        @property
        def IsSnappedPosition(self) -> bool: ...
        @IsSnappedPosition.setter
        def IsSnappedPosition(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
    

    class CageManipulatorDataObjectMoveData():
        @property
        def DraggedObject(self) -> NXObject: ...
        @DraggedObject.setter
        def DraggedObject(self, value: NXObject) -> None: ...
        @property
        def BeginDragCursorPosition(self) -> Point3d: ...
        @BeginDragCursorPosition.setter
        def BeginDragCursorPosition(self, value: Point3d) -> None: ...
        @property
        def BeginDragObjectPosition(self) -> Point3d: ...
        @BeginDragObjectPosition.setter
        def BeginDragObjectPosition(self, value: Point3d) -> None: ...
        @property
        def View(self) -> View: ...
        @View.setter
        def View(self, value: View) -> None: ...
        @property
        def MicropositioningScale(self) -> float: ...
        @MicropositioningScale.setter
        def MicropositioningScale(self, value: float) -> None: ...
        @property
        def ViewDirection(self) -> Vector3d: ...
        @ViewDirection.setter
        def ViewDirection(self, value: Vector3d) -> None: ...
        def ToString(self) -> str: ...
    

    class CageManipulatorData_ObjectSelectionData():
        @property
        def selectedObject(self) -> Tag: ...
        @selectedObject.setter
        def selectedObject(self, value: Tag) -> None: ...
        @property
        def selectionPosition(self) -> Point3d: ...
        @selectionPosition.setter
        def selectionPosition(self, value: Point3d) -> None: ...
        @property
        def viewDirection(self) -> Vector3d: ...
        @viewDirection.setter
        def viewDirection(self, value: Vector3d) -> None: ...
        @property
        def isSnappedPosition(self) -> bool: ...
        @isSnappedPosition.setter
        def isSnappedPosition(self, value: bool) -> None: ...
    

    class CageManipulatorData_ObjectMoveData():
        @property
        def draggedObject(self) -> Tag: ...
        @draggedObject.setter
        def draggedObject(self, value: Tag) -> None: ...
        @property
        def beginDragCursorPosition(self) -> Point3d: ...
        @beginDragCursorPosition.setter
        def beginDragCursorPosition(self, value: Point3d) -> None: ...
        @property
        def beginDragObjectPosition(self) -> Point3d: ...
        @beginDragObjectPosition.setter
        def beginDragObjectPosition(self, value: Point3d) -> None: ...
        @property
        def view(self) -> Tag: ...
        @view.setter
        def view(self, value: Tag) -> None: ...
        @property
        def micropositioningScale(self) -> float: ...
        @micropositioningScale.setter
        def micropositioningScale(self, value: float) -> None: ...
        @property
        def viewDirection(self) -> Vector3d: ...
        @viewDirection.setter
        def viewDirection(self, value: Vector3d) -> None: ...
    

class CageFromFacetBodyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AverageSize(self) -> Expression: ...
    @AverageSize.setter
    def AverageSize(self, value: Expression) -> None: ...
    @property
    def FacetRegion(self) -> FacetCollector: ...
    @FacetRegion.setter
    def FacetRegion(self, value: FacetCollector) -> None: ...
    @property
    def ShowDeviationPlot(self) -> bool: ...
    @ShowDeviationPlot.setter
    def ShowDeviationPlot(self, value: bool) -> None: ...


