from ...NXOpen import *

import typing
import enum

class SmashComponentBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Components(self) -> Layout2d.SelectComponentList: ...
    @Components.setter
    def Components(self, value: Layout2d.SelectComponentList) -> None: ...


class SelectComponentList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Add(self, object: Layout2d.Component) -> bool: ...
    @typing.overload
    def Add(self, objects: typing.List[Layout2d.Component]) -> bool: ...
    @typing.overload
    def Add(self, inputSelectionMethod: SelectionMethod) -> bool: ...
    @typing.overload
    def Add(self, selection: Layout2d.Component, view: View, point: Point3d) -> bool: ...
    @typing.overload
    def Remove(self, object: Layout2d.Component) -> bool: ...
    @typing.overload
    def Remove(self, object: Layout2d.Component, view: View) -> bool: ...
    @typing.overload
    def Remove(self, snapType: InferSnapType.SnapType, selection1: Layout2d.Component, view1: View, point1: Point3d, selection2: Layout2d.Component, view2: View, point2: Point3d) -> bool: ...
    def RemoveArray(self, objects: typing.List[Layout2d.Component]) -> bool: ...
    @typing.overload
    def Remove(self, inputSelectionMethod: SelectionMethod) -> bool: ...
    def Clear(self) -> None: ...
    def Contains(self, object: Layout2d.Component) -> bool: ...
    def SetArray(self, objects: typing.List[Layout2d.Component]) -> None: ...
    def GetArray(self) -> typing.List[Layout2d.Component]: ...
    def GetSelectObjectArray(self) -> typing.List[SelectObject]: ...
    @typing.overload
    def Add(self, snapType: InferSnapType.SnapType, selection1: Layout2d.Component, view1: View, point1: Point3d, selection2: Layout2d.Component, view2: View, point2: Point3d) -> bool: ...
    @typing.overload
    def Add(self, selection: Layout2d.Component, caeSubType: CaeObjectType.CaeSubType, caeSubId: int) -> bool: ...
    def Validate(self) -> bool: ...
    @property
    def DuplicatesAllowed(self) -> bool: ...
    @DuplicatesAllowed.setter
    def DuplicatesAllowed(self, value: bool) -> None: ...
    @property
    def Size(self) -> int: ...
    @Size.setter
    def Size(self, value: int) -> None: ...


class SelectComponent(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def SetValue(self, selection: Layout2d.Component, view: View, point: Point3d) -> None: ...
    @typing.overload
    def GetValue(self, selection: Layout2d.Component, view: View, point: Point3d) -> None: ...
    @typing.overload
    def SetValue(self, snapType: InferSnapType.SnapType, selection1: Layout2d.Component, view1: View, point1: Point3d, selection2: Layout2d.Component, view2: View, point2: Point3d) -> None: ...
    @typing.overload
    def GetValue(self, snapType: InferSnapType.SnapType, selection1: Layout2d.Component, view1: View, point1: Point3d, selection2: Layout2d.Component, view2: View, point2: Point3d) -> None: ...
    @typing.overload
    def SetValue(self, selection: Layout2d.Component, caeSubType: CaeObjectType.CaeSubType, caeSubId: int) -> None: ...
    @typing.overload
    def GetValue(self, caeSubType: CaeObjectType.CaeSubType, caeSubId: int) -> Layout2d.Component: ...
    def Validate(self) -> bool: ...
    @property
    def Value(self) -> Layout2d.Component: ...
    @Value.setter
    def Value(self, value: Layout2d.Component) -> None: ...


class ReplaceComponentBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Components(self) -> Layout2d.SelectComponentList: ...
    @Components.setter
    def Components(self, value: Layout2d.SelectComponentList) -> None: ...
    @property
    def Location(self) -> Layout2d.Layout2dDefinitionLocation: ...
    @Location.setter
    def Location(self, value: Layout2d.Layout2dDefinitionLocation) -> None: ...
    @property
    def Path(self) -> str: ...
    @Path.setter
    def Path(self, value: str) -> None: ...
    @property
    def ReplaceAll(self) -> bool: ...
    @ReplaceAll.setter
    def ReplaceAll(self, value: bool) -> None: ...


class ReparentComponentBuilder(Builder):
    def __init__(self) -> None: ...
    def AddComponents(self, components: typing.List[Layout2d.Component]) -> None: ...
    @property
    def Components(self) -> Layout2d.SelectComponentList: ...
    @Components.setter
    def Components(self, value: Layout2d.SelectComponentList) -> None: ...
    @property
    def CreateCopy(self) -> bool: ...
    @CreateCopy.setter
    def CreateCopy(self, value: bool) -> None: ...
    @property
    def Target(self) -> DisplayableObject: ...
    @Target.setter
    def Target(self, value: DisplayableObject) -> None: ...


class PublishComponentBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def DestinationPath(self) -> str: ...
    @DestinationPath.setter
    def DestinationPath(self, value: str) -> None: ...
    @property
    def IsFolder(self) -> bool: ...
    @IsFolder.setter
    def IsFolder(self, value: bool) -> None: ...
    @property
    def Location(self) -> Layout2d.Layout2dDefinitionLocation: ...
    @Location.setter
    def Location(self, value: Layout2d.Layout2dDefinitionLocation) -> None: ...
    @property
    def OriginPath(self) -> str: ...
    @OriginPath.setter
    def OriginPath(self, value: str) -> None: ...


class NewComponentBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Owner(self) -> NXObject: ...
    @Owner.setter
    def Owner(self, value: NXObject) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MakeComponentUniqueBuilder(Builder):
    def __init__(self) -> None: ...
    def SetPath(self, path: str) -> None: ...
    def SetLocation(self, locationType: Layout2d.Layout2dDefinitionLocation) -> None: ...
    @property
    def Component(self) -> Layout2d.SelectComponent: ...
    @Component.setter
    def Component(self, value: Layout2d.SelectComponent) -> None: ...
    @property
    def ComponentName(self) -> Layout2d.ComponentNameBuilder: ...
    @ComponentName.setter
    def ComponentName(self, value: Layout2d.ComponentNameBuilder) -> None: ...
    @property
    def ImageCapture(self) -> Gateway.ImageCaptureBuilder: ...
    @ImageCapture.setter
    def ImageCapture(self, value: Gateway.ImageCaptureBuilder) -> None: ...
    @property
    def ImageName(self) -> str: ...
    @ImageName.setter
    def ImageName(self, value: str) -> None: ...


class LocalDefinitionFolderCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Layout2d.LocalDefinitionFolder]: ...
    @typing.overload
    def __init__(self, owner: Part) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateLocalDefinitionFolderBuilder(self, currentFolder: Layout2d.LocalDefinitionFolder) -> Layout2d.LocalDefinitionFolderBuilder: ...
    def FindObject(self, name: str) -> Layout2d.LocalDefinitionFolder: ...
    def Tag(self) -> Tag: ...



class LocalDefinitionFolderBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def FolderName(self) -> str: ...
    @FolderName.setter
    def FolderName(self, value: str) -> None: ...
    @property
    def Parent(self) -> Layout2d.LocalDefinitionFolder: ...
    @Parent.setter
    def Parent(self, value: Layout2d.LocalDefinitionFolder) -> None: ...


class LocalDefinitionFolder(NXObject):
    def __init__(self) -> None: ...


class LayoutDrawingSheetCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Layout2d.LayoutDrawingSheet]: ...
    @typing.overload
    def __init__(self, owner: Part) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> Layout2d.LayoutDrawingSheet: ...
    def CreateLayoutDrawingSheetBuilder(self, layoutDrawingSheet: Layout2d.LayoutDrawingSheet) -> Layout2d.LayoutDrawingSheetBuilder: ...
    def InsertSheet(self, name: str, units: Drawings.DrawingSheet.Unit, numerator: float, denominator: float, projectionAngle: Drawings.DrawingSheet.ProjectionAngleType) -> Layout2d.LayoutDrawingSheet: ...
    def CreateConvertSheetToLayoutBuilder(self) -> Layout2d.ConvertSheetToLayoutBuilder: ...
    def CreateConvertLayoutToSheetBuilder(self) -> Layout2d.ConvertLayoutToSheetBuilder: ...
    def Tag(self) -> Tag: ...

    @property
    def CurrentDrawingSheet(self) -> Layout2d.LayoutDrawingSheet: ...
    @CurrentDrawingSheet.setter
    def CurrentDrawingSheet(self, value: Layout2d.LayoutDrawingSheet) -> None: ...


class LayoutDrawingSheetBuilder(Drawings.DrawingSheetBuilder):
    def __init__(self) -> None: ...


class LayoutDrawingSheet(Drawings.DrawingSheet):
    def __init__(self) -> None: ...


class Layout2dDefinitionStatus(enum.Enum):
    Unknown= 0
    Synced= 1
    NotSynced= 2
    Missing= 3


class Layout2dDefinitionLocation(enum.Enum):
    Unspecified= 0
    Local= 1
    Native= 2
    TcEng= 3


class Layout2dComponentMemberType(enum.Enum):
    None_= 0
    SketchGeometryNonReference= 1
    SketchGeometryReference= 2
    SketchGeometry= 3
    SketchDimension= 4
    SketchConstraint= 8
    Sketch= 16
    Component= 32
    DraftingDimension= 64
    Dimension= 68
    DraftingAnnotationNonDimension= 128
    DraftingAnnotation= 192
    Annotation= 196
    MiscOthers= 256
    Misc= 448
    ExemptRelationsSet= 512
    All= 1023


class InsertComponentBuilder(Builder):
    def __init__(self) -> None: ...
    def SetPath(self, path: str) -> None: ...
    def SetLocation(self, locationType: Layout2d.Layout2dDefinitionLocation) -> None: ...
    @property
    def Angle(self) -> float: ...
    @Angle.setter
    def Angle(self, value: float) -> None: ...
    @property
    def Settings(self) -> Layout2d.ComponentSettingsBlockBuilder: ...
    @Settings.setter
    def Settings(self, value: Layout2d.ComponentSettingsBlockBuilder) -> None: ...
    @property
    def Sketch(self) -> Sketch: ...
    @Sketch.setter
    def Sketch(self, value: Sketch) -> None: ...
    @property
    def SpecifyPoint(self) -> Point3d: ...
    @SpecifyPoint.setter
    def SpecifyPoint(self, value: Point3d) -> None: ...


class InheritDisplayAttributesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Components(self) -> Layout2d.SelectComponentList: ...
    @Components.setter
    def Components(self, value: Layout2d.SelectComponentList) -> None: ...
    @property
    def Direction(self) -> Layout2d.InheritDisplayAttributesBuilder.InheritDirection: ...
    @Direction.setter
    def Direction(self, value: Layout2d.InheritDisplayAttributesBuilder.InheritDirection) -> None: ...


    class InheritDirection(enum.Enum):
        DefinitionToComponent= 0
        ComponentToDefinition= 1
    

class GeneralPreferencesBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def ShowLayoutOrigin(self) -> bool: ...
    @ShowLayoutOrigin.setter
    def ShowLayoutOrigin(self, value: bool) -> None: ...


class ExportComponentHierarchyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def ChildComponentsForComponents(self) -> bool: ...
    @ChildComponentsForComponents.setter
    def ChildComponentsForComponents(self, value: bool) -> None: ...
    @property
    def ChildComponentsForDefinitions(self) -> bool: ...
    @ChildComponentsForDefinitions.setter
    def ChildComponentsForDefinitions(self, value: bool) -> None: ...
    @property
    def Contents(self) -> bool: ...
    @Contents.setter
    def Contents(self, value: bool) -> None: ...
    @property
    def DefinitionReferenceProperties(self) -> bool: ...
    @DefinitionReferenceProperties.setter
    def DefinitionReferenceProperties(self, value: bool) -> None: ...
    @property
    def Definitions(self) -> bool: ...
    @Definitions.setter
    def Definitions(self, value: bool) -> None: ...
    @property
    def OutputFileName(self) -> str: ...
    @OutputFileName.setter
    def OutputFileName(self, value: str) -> None: ...
    @property
    def Selection(self) -> SelectDisplayableObjectList: ...
    @Selection.setter
    def Selection(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def SoftwareProperties(self) -> bool: ...
    @SoftwareProperties.setter
    def SoftwareProperties(self, value: bool) -> None: ...


class EditComponentSettingsBuilder(Drafting.BaseEditSettingsBuilder):
    def __init__(self) -> None: ...
    def InheritSettingsFromSelectedObject(self, selectedObject: NXObject) -> None: ...
    def InheritSettingsFromCustomerDefault(self) -> None: ...
    def InheritSettingsFromPreferences(self) -> None: ...
    @property
    def ComponentSettings(self) -> Layout2d.ComponentSettingsBlockBuilder: ...
    @ComponentSettings.setter
    def ComponentSettings(self, value: Layout2d.ComponentSettingsBlockBuilder) -> None: ...


class DefineComponentBuilder(Builder):
    def __init__(self) -> None: ...
    def IsValidActiveSetMember(self, object: DisplayableObject) -> bool: ...
    def SetPath(self, path: str) -> None: ...
    def SetLocation(self, locationType: Layout2d.Layout2dDefinitionLocation) -> None: ...
    @property
    def ActiveSet(self) -> ScCollector: ...
    @ActiveSet.setter
    def ActiveSet(self, value: ScCollector) -> None: ...
    @property
    def ActiveSetScope(self) -> Layout2d.ActiveSetScope: ...
    @ActiveSetScope.setter
    def ActiveSetScope(self, value: Layout2d.ActiveSetScope) -> None: ...
    @property
    def AnchorPoint(self) -> Point: ...
    @AnchorPoint.setter
    def AnchorPoint(self, value: Point) -> None: ...
    @property
    def ComponentName(self) -> Layout2d.ComponentNameBuilder: ...
    @ComponentName.setter
    def ComponentName(self, value: Layout2d.ComponentNameBuilder) -> None: ...
    @property
    def Contents(self) -> SelectNXObjectList: ...
    @Contents.setter
    def Contents(self, value: SelectNXObjectList) -> None: ...
    @property
    def ImageCapture(self) -> Gateway.ImageCaptureBuilder: ...
    @ImageCapture.setter
    def ImageCapture(self, value: Gateway.ImageCaptureBuilder) -> None: ...
    @property
    def ImageName(self) -> str: ...
    @ImageName.setter
    def ImageName(self, value: str) -> None: ...


class DefineComponentAnchorPointBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AnchorPoint(self) -> Point: ...
    @AnchorPoint.setter
    def AnchorPoint(self, value: Point) -> None: ...


class CreateComponentFrom3DSettingsBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def InheritSettingsFromCustomerDefault(self) -> None: ...
    def InheritSettingsFromPreferences(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def ActiveSetScope(self) -> Layout2d.ActiveSetScope: ...
    @ActiveSetScope.setter
    def ActiveSetScope(self, value: Layout2d.ActiveSetScope) -> None: ...
    @property
    def AutomaticallyStartInsert2DComponentCommand(self) -> bool: ...
    @AutomaticallyStartInsert2DComponentCommand.setter
    def AutomaticallyStartInsert2DComponentCommand(self, value: bool) -> None: ...
    @property
    def Color(self) -> int: ...
    @Color.setter
    def Color(self, value: int) -> None: ...
    @property
    def ColorOption(self) -> Display.DynamicSectionTypes.CurveColorOption: ...
    @ColorOption.setter
    def ColorOption(self, value: Display.DynamicSectionTypes.CurveColorOption) -> None: ...
    @property
    def CreateSingle2DComponentDefinition(self) -> bool: ...
    @CreateSingle2DComponentDefinition.setter
    def CreateSingle2DComponentDefinition(self, value: bool) -> None: ...


class CreateComponentFrom3DBuilder(Display.DynamicSectionBuilder):
    def __init__(self) -> None: ...
    def SetSourcePart(self, part: Part) -> None: ...
    def GetSourcePart(self) -> Part: ...
    def SetProjectionPlane(self, origin: Point3d, yAxis: Vector3d, zAxis: Vector3d) -> None: ...
    def GetProjectionPlane(self, origin: Point3d, orientation: Matrix3x3) -> None: ...
    @property
    def ComponentName(self) -> str: ...
    @ComponentName.setter
    def ComponentName(self, value: str) -> None: ...
    @property
    def Method(self) -> Layout2d.CreateComponentFrom3DBuilder.CreateMethod: ...
    @Method.setter
    def Method(self, value: Layout2d.CreateComponentFrom3DBuilder.CreateMethod) -> None: ...
    @property
    def SelectedObjects(self) -> SelectTaggedObjectList: ...
    @SelectedObjects.setter
    def SelectedObjects(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def Settings(self) -> Layout2d.CreateComponentFrom3DSettingsBuilder: ...
    @Settings.setter
    def Settings(self, value: Layout2d.CreateComponentFrom3DSettingsBuilder) -> None: ...


    class CreateMethod(enum.Enum):
        Section= 0
        Plane= 1
    

class ConvertSheetToLayoutBuilder(Layout2d.LayoutDrawingSheetBuilder):
    def __init__(self) -> None: ...
    @property
    def SelectSheetView(self) -> SelectView: ...
    @SelectSheetView.setter
    def SelectSheetView(self, value: SelectView) -> None: ...


class ConvertLayoutToSheetBuilder(Builder):
    def __init__(self) -> None: ...
    def GetScale(self, numerator: float, denominator: float) -> None: ...
    def SetScale(self, numerator: float, denominator: float) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Number(self) -> str: ...
    @Number.setter
    def Number(self, value: str) -> None: ...
    @property
    def ProjectionAngleType(self) -> Layout2d.ConvertLayoutToSheetBuilder.SheetProjectionAngleType: ...
    @ProjectionAngleType.setter
    def ProjectionAngleType(self, value: Layout2d.ConvertLayoutToSheetBuilder.SheetProjectionAngleType) -> None: ...
    @property
    def Revision(self) -> str: ...
    @Revision.setter
    def Revision(self, value: str) -> None: ...
    @property
    def SecondaryNumber(self) -> str: ...
    @SecondaryNumber.setter
    def SecondaryNumber(self, value: str) -> None: ...
    @property
    def SelectLayoutSheetView(self) -> SelectView: ...
    @SelectLayoutSheetView.setter
    def SelectLayoutSheetView(self, value: SelectView) -> None: ...


    class SheetProjectionAngleType(enum.Enum):
        First= 0
        Third= 1
    

class ComponentSettingsBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def AutomaticUpdate(self) -> bool: ...
    @AutomaticUpdate.setter
    def AutomaticUpdate(self, value: bool) -> None: ...
    @property
    def KeepEditedPartsOpen(self) -> bool: ...
    @KeepEditedPartsOpen.setter
    def KeepEditedPartsOpen(self, value: bool) -> None: ...
    @property
    def ShowAnnotations(self) -> bool: ...
    @ShowAnnotations.setter
    def ShowAnnotations(self, value: bool) -> None: ...
    @property
    def ShowDimensions(self) -> bool: ...
    @ShowDimensions.setter
    def ShowDimensions(self, value: bool) -> None: ...
    @property
    def ShowReferenceGeometry(self) -> bool: ...
    @ShowReferenceGeometry.setter
    def ShowReferenceGeometry(self, value: bool) -> None: ...


class ComponentSettingsBlockBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def InheritSettingsFromSelectedObject(self, selectedObject: NXObject) -> None: ...
    def InheritSettingsFromCustomerDefault(self) -> None: ...
    def InheritSettingsFromPreferences(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def ComponentSettings(self) -> Layout2d.ComponentSettingsBuilder: ...
    @ComponentSettings.setter
    def ComponentSettings(self, value: Layout2d.ComponentSettingsBuilder) -> None: ...


class ComponentNameBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def SetPartOperationBuilder(self, partOperationBuilder: PDM.PartOperationCreateBuilder) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def Location(self) -> Layout2d.Layout2dDefinitionLocation: ...
    @Location.setter
    def Location(self, value: Layout2d.Layout2dDefinitionLocation) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def PartName(self) -> str: ...
    @PartName.setter
    def PartName(self, value: str) -> None: ...


class ComponentDefinitionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Layout2d.LocalDefinitionFolder]: ...
    @typing.overload
    def __init__(self, owner: Part) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, sid: str) -> Layout2d.ComponentDefinition: ...
    def Rename(self, location: Layout2d.Layout2dDefinitionLocation, definitionPath: str, newName: str) -> None: ...
    def Delete(self, location: Layout2d.Layout2dDefinitionLocation, definitionPath: str) -> None: ...
    def UpdateImage(self, location: Layout2d.Layout2dDefinitionLocation, definitionPath: str, imagePath: str) -> None: ...
    def SetAutomaticPreview(self, location: Layout2d.Layout2dDefinitionLocation, definitionPath: str, isAutomatic: bool) -> None: ...
    def Update(self, location: Layout2d.Layout2dDefinitionLocation, definitionPath: str) -> None: ...
    def RefreshAllReferences(self) -> None: ...
    def Tag(self) -> Tag: ...



class ComponentDefinition(NXObject):
    def __init__(self) -> None: ...
    def Rename(self, definitionPath: str, newName: str) -> None: ...
    def Delete(self, definitionPath: str) -> None: ...
    def UpdateImage(self, definitionPath: str, imagePath: str) -> None: ...
    def GetMembers(self, memberType: Layout2d.Layout2dComponentMemberType, members: typing.List[DisplayableObject]) -> None: ...


class ComponentCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Layout2d.Component]: ...
    @typing.overload
    def __init__(self, owner: Part) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> Layout2d.Component: ...
    def CreateDefineComponentBuilder(self, component: Layout2d.Component) -> Layout2d.DefineComponentBuilder: ...
    def CreateInsertComponentBuilder(self) -> Layout2d.InsertComponentBuilder: ...
    def CreateReplaceComponentBuilder(self) -> Layout2d.ReplaceComponentBuilder: ...
    def CreateSmashComponentBuilder(self) -> Layout2d.SmashComponentBuilder: ...
    def CreateMakeComponentUniqueBuilder(self) -> Layout2d.MakeComponentUniqueBuilder: ...
    def CreateDefineComponentAnchorPointBuilder(self) -> Layout2d.DefineComponentAnchorPointBuilder: ...
    def CreatePublishComponentBuilder(self) -> Layout2d.PublishComponentBuilder: ...
    def CreateNewComponentBuilder(self) -> Layout2d.NewComponentBuilder: ...
    def DeleteComponents(self, components: typing.List[Layout2d.Component]) -> None: ...
    def IsComponentMember(self, disObject: DisplayableObject) -> bool: ...
    def CreateAssemblyFromLayout2dBuilder(self) -> Layout2d.AssemblyFromLayout2dBuilder: ...
    def CreateReparentComponentBuilder(self) -> Layout2d.ReparentComponentBuilder: ...
    def UpdateComponents(self, components: typing.List[Layout2d.Component]) -> None: ...
    def UpdateComponentHierarchy(self, components: typing.List[Layout2d.Component]) -> None: ...
    def CreateComponentFrom3dBuilder(self, myView: View) -> Layout2d.CreateComponentFrom3DBuilder: ...
    def CreateExportComponentHierarchyBuilder(self) -> Layout2d.ExportComponentHierarchyBuilder: ...
    def CreateAssociativeAssemblyBuilder(self) -> Layout2d.AssociativeAssemblyBuilder: ...
    def CreateInheritDisplayAttributesBuilder(self) -> Layout2d.InheritDisplayAttributesBuilder: ...
    def CreateComponentActiveSetBuilder(self) -> Layout2d.ComponentActiveSetBuilder: ...
    def Tag(self) -> Tag: ...

    @property
    def OrderManagers(self) -> Drawings.OrderManager: ...
    @OrderManagers.setter
    def OrderManagers(self, value: Drawings.OrderManager) -> None: ...


class ComponentActiveSetBuilder(Builder):
    def __init__(self) -> None: ...
    def IsValidActiveSetMember(self, objectTag: DisplayableObject) -> bool: ...
    @property
    def ActiveSet(self) -> ScCollector: ...
    @ActiveSet.setter
    def ActiveSet(self, value: ScCollector) -> None: ...
    @property
    def ActiveSetScope(self) -> Layout2d.ActiveSetScope: ...
    @ActiveSetScope.setter
    def ActiveSetScope(self, value: Layout2d.ActiveSetScope) -> None: ...


class Component(DisplayableObject):
    def __init__(self) -> None: ...
    def Activate(self) -> None: ...
    def Deactivate(self) -> None: ...
    def Update(self) -> None: ...
    def ExitActivate(self) -> None: ...
    def GetMembers(self, memberType: Layout2d.Layout2dComponentMemberType, members: typing.List[DisplayableObject]) -> None: ...
    def Transform(self, rotation: Matrix3x3, translation: Vector3d) -> None: ...
    def SetTransform(self, rotation: Matrix3x3, translation: Vector3d) -> None: ...
    def GetTransform(self, rotation: Matrix3x3, translation: Vector3d) -> None: ...
    def AddExistingCurves(self, curves: typing.List[DisplayableObject]) -> None: ...
    def GetDefinition(self) -> Layout2d.ComponentDefinition: ...
    def GetAnchorPoint(self, anchorPoint: Point3d) -> bool: ...
    def GetDefinitionName(self) -> str: ...
    def GetDefinitionPath(self) -> str: ...
    def GetDefinitionLocation(self) -> Layout2d.Layout2dDefinitionLocation: ...
    def ActivateInIsolation(self) -> Sketch: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> None: ...
    @property
    def LockUpdateStatus(self) -> bool: ...
    @LockUpdateStatus.setter
    def LockUpdateStatus(self, value: bool) -> None: ...
    @property
    def UpgradeUponActivation(self) -> bool: ...
    @UpgradeUponActivation.setter
    def UpgradeUponActivation(self, value: bool) -> None: ...


class AssociativeAssemblyBuilder(Builder):
    def __init__(self) -> None: ...
    def GetAssemblyRelations(self) -> typing.List[Layout2d.AssemblyRelation]: ...
    def ResetAssemblyRelations(self) -> None: ...
    @property
    def Direction(self) -> Layout2d.AssociativeAssemblyBuilder.UpdateDirection: ...
    @Direction.setter
    def Direction(self, value: Layout2d.AssociativeAssemblyBuilder.UpdateDirection) -> None: ...


    class UpdateDirection(enum.Enum):
        LayoutToAssembly= 0
        AssemblyToLayout= 1
    

class AssemblyRelation(NXObject):
    def __init__(self) -> None: ...
    def GetPrototypeInferred(self) -> bool: ...
    @property
    def Associative(self) -> bool: ...
    @Associative.setter
    def Associative(self, value: bool) -> None: ...
    @property
    def PrototypeFileSpec(self) -> str: ...
    @PrototypeFileSpec.setter
    def PrototypeFileSpec(self, value: str) -> None: ...
    @property
    def SyncContent(self) -> bool: ...
    @SyncContent.setter
    def SyncContent(self, value: bool) -> None: ...
    @property
    def SyncStructure(self) -> bool: ...
    @SyncStructure.setter
    def SyncStructure(self, value: bool) -> None: ...


class AssemblyFromLayout2dBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AssemblyPart(self) -> Part: ...
    @AssemblyPart.setter
    def AssemblyPart(self, value: Part) -> None: ...
    @property
    def Layout2dObject(self) -> SelectDisplayableObject: ...
    @Layout2dObject.setter
    def Layout2dObject(self, value: SelectDisplayableObject) -> None: ...
    @property
    def Settings(self) -> Layout2d.AssemblyCreationSettingsBuilder: ...
    @Settings.setter
    def Settings(self, value: Layout2d.AssemblyCreationSettingsBuilder) -> None: ...


class AssemblyCreationSettingsBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def InheritSettingsFromCustomerDefault(self) -> None: ...
    def InheritSettingsFromPreferences(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def AutomaticallyStartModelingApplication(self) -> bool: ...
    @AutomaticallyStartModelingApplication.setter
    def AutomaticallyStartModelingApplication(self, value: bool) -> None: ...
    @property
    def Transfer2dComponentAnnotation(self) -> bool: ...
    @Transfer2dComponentAnnotation.setter
    def Transfer2dComponentAnnotation(self, value: bool) -> None: ...
    @property
    def TransferTopLevelSketchAnnotation(self) -> bool: ...
    @TransferTopLevelSketchAnnotation.setter
    def TransferTopLevelSketchAnnotation(self, value: bool) -> None: ...


class ActiveSetScope(enum.Enum):
    NoMembers= 0
    SelectMembers= 1
    AllMembers= 2


