from ...NXOpen import *

import typing
import enum

class TemplateBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AreaItemType(self) -> str: ...
    @AreaItemType.setter
    def AreaItemType(self, value: str) -> None: ...
    @property
    def AreaTemplate(self) -> int: ...
    @AreaTemplate.setter
    def AreaTemplate(self, value: int) -> None: ...
    @property
    def AssemblyItemType(self) -> str: ...
    @AssemblyItemType.setter
    def AssemblyItemType(self, value: str) -> None: ...
    @property
    def AssemblyTemplate(self) -> int: ...
    @AssemblyTemplate.setter
    def AssemblyTemplate(self, value: int) -> None: ...
    @property
    def BoardItemType(self) -> str: ...
    @BoardItemType.setter
    def BoardItemType(self, value: str) -> None: ...
    @property
    def BoardTemplate(self) -> int: ...
    @BoardTemplate.setter
    def BoardTemplate(self, value: int) -> None: ...
    @property
    def ComponentItemType(self) -> str: ...
    @ComponentItemType.setter
    def ComponentItemType(self, value: str) -> None: ...
    @property
    def ComponentTemplate(self) -> int: ...
    @ComponentTemplate.setter
    def ComponentTemplate(self, value: int) -> None: ...
    @property
    def FemItemType(self) -> str: ...
    @FemItemType.setter
    def FemItemType(self, value: str) -> None: ...
    @property
    def FemTemplate(self) -> int: ...
    @FemTemplate.setter
    def FemTemplate(self, value: int) -> None: ...
    @property
    def SimItemType(self) -> str: ...
    @SimItemType.setter
    def SimItemType(self, value: str) -> None: ...
    @property
    def SimTemplate(self) -> int: ...
    @SimTemplate.setter
    def SimTemplate(self, value: int) -> None: ...
    @property
    def SubAssemblyItemType(self) -> str: ...
    @SubAssemblyItemType.setter
    def SubAssemblyItemType(self, value: str) -> None: ...
    @property
    def SubAssemblyTemplate(self) -> int: ...
    @SubAssemblyTemplate.setter
    def SubAssemblyTemplate(self, value: int) -> None: ...


class ReportBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def ReportType(self) -> PcbExchange.ReportBuilder.TypeEnum: ...
    @ReportType.setter
    def ReportType(self, value: PcbExchange.ReportBuilder.TypeEnum) -> None: ...


    class TypeEnum(enum.Enum):
        Validation= 0
        LightweightValidation= 1
        Component= 2
        ThermalDatabase= 3
    

class PreferencesBuilder(Builder):
    def __init__(self) -> None: ...
    def GetMcadEntityFilter(self) -> PcbExchange.EntityFilter: ...
    def SetMcadEntityFilter(self, filter: PcbExchange.EntityFilter) -> None: ...
    def GetEcadEntityFilter(self) -> PcbExchange.EntityFilter: ...
    def SetEcadEntityFilter(self, filter: PcbExchange.EntityFilter) -> None: ...
    def GetAreaMapping(self) -> PcbExchange.AreaMapping: ...
    def SetAreaMapping(self, areaMapping: PcbExchange.AreaMapping) -> None: ...
    def GetMailRecipients(self) -> str: ...
    def SetMailRecipients(self, mMailRecipients: str) -> None: ...
    @property
    def AreaNamePrefix(self) -> str: ...
    @AreaNamePrefix.setter
    def AreaNamePrefix(self, value: str) -> None: ...
    @property
    def AreaNameSuffix(self) -> str: ...
    @AreaNameSuffix.setter
    def AreaNameSuffix(self, value: str) -> None: ...
    @property
    def AreasAsAssemblyComponents(self) -> bool: ...
    @AreasAsAssemblyComponents.setter
    def AreasAsAssemblyComponents(self, value: bool) -> None: ...
    @property
    def AssociateAreaBodies(self) -> bool: ...
    @AssociateAreaBodies.setter
    def AssociateAreaBodies(self, value: bool) -> None: ...
    @property
    def AssociateComponentBodies(self) -> bool: ...
    @AssociateComponentBodies.setter
    def AssociateComponentBodies(self, value: bool) -> None: ...
    @property
    def AutomaticallySaveAllCreatedParts(self) -> bool: ...
    @AutomaticallySaveAllCreatedParts.setter
    def AutomaticallySaveAllCreatedParts(self, value: bool) -> None: ...
    @property
    def BoardAsAssemblyComponent(self) -> bool: ...
    @BoardAsAssemblyComponent.setter
    def BoardAsAssemblyComponent(self, value: bool) -> None: ...
    @property
    def BoardColor(self) -> NXColor: ...
    @BoardColor.setter
    def BoardColor(self, value: NXColor) -> None: ...
    @property
    def BoardDefaultPlatingThickness(self) -> Expression: ...
    @BoardDefaultPlatingThickness.setter
    def BoardDefaultPlatingThickness(self, value: Expression) -> None: ...
    @property
    def BoardDefaultThickness(self) -> Expression: ...
    @BoardDefaultThickness.setter
    def BoardDefaultThickness(self, value: Expression) -> None: ...
    @property
    def BoardDefaultTraceThickness(self) -> Expression: ...
    @BoardDefaultTraceThickness.setter
    def BoardDefaultTraceThickness(self, value: Expression) -> None: ...
    @property
    def BoardElementColor(self) -> NXColor: ...
    @BoardElementColor.setter
    def BoardElementColor(self, value: NXColor) -> None: ...
    @property
    def BoardElementSize(self) -> Expression: ...
    @BoardElementSize.setter
    def BoardElementSize(self, value: Expression) -> None: ...
    @property
    def BoardLayer(self) -> int: ...
    @BoardLayer.setter
    def BoardLayer(self, value: int) -> None: ...
    @property
    def BoardNamePrefix(self) -> str: ...
    @BoardNamePrefix.setter
    def BoardNamePrefix(self, value: str) -> None: ...
    @property
    def BoardNameSuffix(self) -> str: ...
    @BoardNameSuffix.setter
    def BoardNameSuffix(self, value: str) -> None: ...
    @property
    def BoardThickness(self) -> Expression: ...
    @BoardThickness.setter
    def BoardThickness(self, value: Expression) -> None: ...
    @property
    def BoardThicknessSource(self) -> PcbExchange.PreferencesBuilder.BoardThicknessSourceTypeName: ...
    @BoardThicknessSource.setter
    def BoardThicknessSource(self, value: PcbExchange.PreferencesBuilder.BoardThicknessSourceTypeName) -> None: ...
    @property
    def BoardTranslucency(self) -> int: ...
    @BoardTranslucency.setter
    def BoardTranslucency(self, value: int) -> None: ...
    @property
    def BrowseEcadFilesFromDir(self) -> str: ...
    @BrowseEcadFilesFromDir.setter
    def BrowseEcadFilesFromDir(self, value: str) -> None: ...
    @property
    def ComparePrimaryPinLocations(self) -> bool: ...
    @ComparePrimaryPinLocations.setter
    def ComparePrimaryPinLocations(self, value: bool) -> None: ...
    @property
    def ComponentLoadOptions(self) -> PcbExchange.PreferencesBuilder.ComponentLoadOptionsTypeName: ...
    @ComponentLoadOptions.setter
    def ComponentLoadOptions(self, value: PcbExchange.PreferencesBuilder.ComponentLoadOptionsTypeName) -> None: ...
    @property
    def ComponentNamePrefix(self) -> str: ...
    @ComponentNamePrefix.setter
    def ComponentNamePrefix(self, value: str) -> None: ...
    @property
    def ComponentNameSuffix(self) -> str: ...
    @ComponentNameSuffix.setter
    def ComponentNameSuffix(self, value: str) -> None: ...
    @property
    def ComponentXMLFileBrowse(self) -> str: ...
    @ComponentXMLFileBrowse.setter
    def ComponentXMLFileBrowse(self, value: str) -> None: ...
    @property
    def ComponentsCaseMaterial(self) -> int: ...
    @ComponentsCaseMaterial.setter
    def ComponentsCaseMaterial(self, value: int) -> None: ...
    @property
    def ComponentsColor(self) -> NXColor: ...
    @ComponentsColor.setter
    def ComponentsColor(self, value: NXColor) -> None: ...
    @property
    def ComponentsConnectionToBoard(self) -> PcbExchange.PreferencesBuilder.ComponentsConnectionToBoardTypeName: ...
    @ComponentsConnectionToBoard.setter
    def ComponentsConnectionToBoard(self, value: PcbExchange.PreferencesBuilder.ComponentsConnectionToBoardTypeName) -> None: ...
    @property
    def ComponentsDefaultHeight(self) -> Expression: ...
    @ComponentsDefaultHeight.setter
    def ComponentsDefaultHeight(self, value: Expression) -> None: ...
    @property
    def ComponentsDefaultMass(self) -> Expression: ...
    @ComponentsDefaultMass.setter
    def ComponentsDefaultMass(self, value: Expression) -> None: ...
    @property
    def ComponentsDissipation(self) -> Expression: ...
    @ComponentsDissipation.setter
    def ComponentsDissipation(self, value: Expression) -> None: ...
    @property
    def ComponentsElementColor(self) -> NXColor: ...
    @ComponentsElementColor.setter
    def ComponentsElementColor(self, value: NXColor) -> None: ...
    @property
    def ComponentsElementSizeOptions(self) -> PcbExchange.PreferencesBuilder.ComponentsElementSizeOptionsTypeName: ...
    @ComponentsElementSizeOptions.setter
    def ComponentsElementSizeOptions(self, value: PcbExchange.PreferencesBuilder.ComponentsElementSizeOptionsTypeName) -> None: ...
    @property
    def ComponentsElementSizeValue(self) -> Expression: ...
    @ComponentsElementSizeValue.setter
    def ComponentsElementSizeValue(self, value: Expression) -> None: ...
    @property
    def ComponentsElementThicknessOptions(self) -> PcbExchange.PreferencesBuilder.ComponentsElementThicknessOptionsTypeName: ...
    @ComponentsElementThicknessOptions.setter
    def ComponentsElementThicknessOptions(self, value: PcbExchange.PreferencesBuilder.ComponentsElementThicknessOptionsTypeName) -> None: ...
    @property
    def ComponentsElementThicknessValue(self) -> Expression: ...
    @ComponentsElementThicknessValue.setter
    def ComponentsElementThicknessValue(self, value: Expression) -> None: ...
    @property
    def ComponentsHeightFrom(self) -> PcbExchange.PreferencesBuilder.ComponentsHeightFromTypeName: ...
    @ComponentsHeightFrom.setter
    def ComponentsHeightFrom(self, value: PcbExchange.PreferencesBuilder.ComponentsHeightFromTypeName) -> None: ...
    @property
    def ComponentsJunctionCapacitance(self) -> Expression: ...
    @ComponentsJunctionCapacitance.setter
    def ComponentsJunctionCapacitance(self, value: Expression) -> None: ...
    @property
    def ComponentsJunctionCapacity(self) -> Expression: ...
    @ComponentsJunctionCapacity.setter
    def ComponentsJunctionCapacity(self, value: Expression) -> None: ...
    @property
    def ComponentsMaterialFrom(self) -> PcbExchange.PreferencesBuilder.ComponentsMaterialFromTypeName: ...
    @ComponentsMaterialFrom.setter
    def ComponentsMaterialFrom(self, value: PcbExchange.PreferencesBuilder.ComponentsMaterialFromTypeName) -> None: ...
    @property
    def ComponentsModel(self) -> PcbExchange.PreferencesBuilder.ComponentsModelTypeName: ...
    @ComponentsModel.setter
    def ComponentsModel(self, value: PcbExchange.PreferencesBuilder.ComponentsModelTypeName) -> None: ...
    @property
    def ComponentsThetaCB(self) -> Expression: ...
    @ComponentsThetaCB.setter
    def ComponentsThetaCB(self, value: Expression) -> None: ...
    @property
    def ComponentsThetaJB(self) -> Expression: ...
    @ComponentsThetaJB.setter
    def ComponentsThetaJB(self, value: Expression) -> None: ...
    @property
    def ComponentsThetaJC(self) -> Expression: ...
    @ComponentsThetaJC.setter
    def ComponentsThetaJC(self, value: Expression) -> None: ...
    @property
    def ComponentsTmax(self) -> Expression: ...
    @ComponentsTmax.setter
    def ComponentsTmax(self, value: Expression) -> None: ...
    @property
    def ComponentsTmaxCase(self) -> Expression: ...
    @ComponentsTmaxCase.setter
    def ComponentsTmaxCase(self, value: Expression) -> None: ...
    @property
    def ComponentsTmaxJunction(self) -> Expression: ...
    @ComponentsTmaxJunction.setter
    def ComponentsTmaxJunction(self, value: Expression) -> None: ...
    @property
    def ComponentsTranslucency(self) -> int: ...
    @ComponentsTranslucency.setter
    def ComponentsTranslucency(self, value: int) -> None: ...
    @property
    def ConnectComponentsToPads(self) -> bool: ...
    @ConnectComponentsToPads.setter
    def ConnectComponentsToPads(self, value: bool) -> None: ...
    @property
    def CreateNewComponentInDir(self) -> str: ...
    @CreateNewComponentInDir.setter
    def CreateNewComponentInDir(self, value: str) -> None: ...
    @property
    def CreateNewComponentsIn(self) -> PcbExchange.PreferencesBuilder.CreateNewComponentsInTypeName: ...
    @CreateNewComponentsIn.setter
    def CreateNewComponentsIn(self, value: PcbExchange.PreferencesBuilder.CreateNewComponentsInTypeName) -> None: ...
    @property
    def DefaultPcaName(self) -> PcbExchange.PreferencesBuilder.DefaultPcaNameTypeName: ...
    @DefaultPcaName.setter
    def DefaultPcaName(self, value: PcbExchange.PreferencesBuilder.DefaultPcaNameTypeName) -> None: ...
    @property
    def EcadFilePostProcessor(self) -> str: ...
    @EcadFilePostProcessor.setter
    def EcadFilePostProcessor(self, value: str) -> None: ...
    @property
    def EcadFilePreProcessor(self) -> str: ...
    @EcadFilePreProcessor.setter
    def EcadFilePreProcessor(self, value: str) -> None: ...
    @property
    def EcadFloatTolerance(self) -> Expression: ...
    @EcadFloatTolerance.setter
    def EcadFloatTolerance(self, value: Expression) -> None: ...
    @property
    def EdmdDir(self) -> str: ...
    @EdmdDir.setter
    def EdmdDir(self, value: str) -> None: ...
    @property
    def ElementColorForStructuralAnalysis(self) -> NXColor: ...
    @ElementColorForStructuralAnalysis.setter
    def ElementColorForStructuralAnalysis(self, value: NXColor) -> None: ...
    @property
    def ElementSizeForStructuralAnalysis(self) -> Expression: ...
    @ElementSizeForStructuralAnalysis.setter
    def ElementSizeForStructuralAnalysis(self, value: Expression) -> None: ...
    @property
    def ElementTypeForStructuralAnalysis(self) -> PcbExchange.PreferencesBuilder.ElementTypeForStructuralAnalysisTypeName: ...
    @ElementTypeForStructuralAnalysis.setter
    def ElementTypeForStructuralAnalysis(self, value: PcbExchange.PreferencesBuilder.ElementTypeForStructuralAnalysisTypeName) -> None: ...
    @property
    def ErrorChecking(self) -> bool: ...
    @ErrorChecking.setter
    def ErrorChecking(self, value: bool) -> None: ...
    @property
    def ExportBends(self) -> bool: ...
    @ExportBends.setter
    def ExportBends(self, value: bool) -> None: ...
    @property
    def FilterEcadToggle(self) -> bool: ...
    @FilterEcadToggle.setter
    def FilterEcadToggle(self, value: bool) -> None: ...
    @property
    def FilterMcadToggle(self) -> bool: ...
    @FilterMcadToggle.setter
    def FilterMcadToggle(self, value: bool) -> None: ...
    @property
    def GenericMaxNumber(self) -> int: ...
    @GenericMaxNumber.setter
    def GenericMaxNumber(self, value: int) -> None: ...
    @property
    def GenericNamePrefix(self) -> str: ...
    @GenericNamePrefix.setter
    def GenericNamePrefix(self, value: str) -> None: ...
    @property
    def GenericNameSuffix(self) -> str: ...
    @GenericNameSuffix.setter
    def GenericNameSuffix(self, value: str) -> None: ...
    @property
    def GroupEntityComponentsBy(self) -> PcbExchange.PreferencesBuilder.GroupEntityComponentsByTypeName: ...
    @GroupEntityComponentsBy.setter
    def GroupEntityComponentsBy(self, value: PcbExchange.PreferencesBuilder.GroupEntityComponentsByTypeName) -> None: ...
    @property
    def GroupPads(self) -> bool: ...
    @GroupPads.setter
    def GroupPads(self, value: bool) -> None: ...
    @property
    def HolesDefaultDiameter(self) -> Expression: ...
    @HolesDefaultDiameter.setter
    def HolesDefaultDiameter(self, value: Expression) -> None: ...
    @property
    def IdfFloatPrecision(self) -> int: ...
    @IdfFloatPrecision.setter
    def IdfFloatPrecision(self, value: int) -> None: ...
    @property
    def IdfFloatWidth(self) -> int: ...
    @IdfFloatWidth.setter
    def IdfFloatWidth(self, value: int) -> None: ...
    @property
    def ImportBends(self) -> bool: ...
    @ImportBends.setter
    def ImportBends(self, value: bool) -> None: ...
    @property
    def ImportExportFlexBent(self) -> PcbExchange.PreferencesBuilder.ImportExportFlexBentType: ...
    @ImportExportFlexBent.setter
    def ImportExportFlexBent(self, value: PcbExchange.PreferencesBuilder.ImportExportFlexBentType) -> None: ...
    @property
    def ImportGenericMenu(self) -> PcbExchange.PreferencesBuilder.ImportGenericMenuTypeName: ...
    @ImportGenericMenu.setter
    def ImportGenericMenu(self, value: PcbExchange.PreferencesBuilder.ImportGenericMenuTypeName) -> None: ...
    @property
    def ImportGenericToggle(self) -> bool: ...
    @ImportGenericToggle.setter
    def ImportGenericToggle(self, value: bool) -> None: ...
    @property
    def ImportMaskMenu(self) -> PcbExchange.PreferencesBuilder.ImportMaskMenuTypeName: ...
    @ImportMaskMenu.setter
    def ImportMaskMenu(self, value: PcbExchange.PreferencesBuilder.ImportMaskMenuTypeName) -> None: ...
    @property
    def ImportMaskToggle(self) -> bool: ...
    @ImportMaskToggle.setter
    def ImportMaskToggle(self, value: bool) -> None: ...
    @property
    def ImportPadMenu(self) -> PcbExchange.PreferencesBuilder.ImportPadMenuTypeName: ...
    @ImportPadMenu.setter
    def ImportPadMenu(self, value: PcbExchange.PreferencesBuilder.ImportPadMenuTypeName) -> None: ...
    @property
    def ImportPadToggle(self) -> bool: ...
    @ImportPadToggle.setter
    def ImportPadToggle(self, value: bool) -> None: ...
    @property
    def ImportPasteMaskMenu(self) -> PcbExchange.PreferencesBuilder.ImportMaskMenuTypeName: ...
    @ImportPasteMaskMenu.setter
    def ImportPasteMaskMenu(self, value: PcbExchange.PreferencesBuilder.ImportMaskMenuTypeName) -> None: ...
    @property
    def ImportPasteMaskToggle(self) -> bool: ...
    @ImportPasteMaskToggle.setter
    def ImportPasteMaskToggle(self, value: bool) -> None: ...
    @property
    def ImportTraceMenu(self) -> PcbExchange.PreferencesBuilder.ImportTraceMenuTypeName: ...
    @ImportTraceMenu.setter
    def ImportTraceMenu(self, value: PcbExchange.PreferencesBuilder.ImportTraceMenuTypeName) -> None: ...
    @property
    def ImportTraceToggle(self) -> bool: ...
    @ImportTraceToggle.setter
    def ImportTraceToggle(self, value: bool) -> None: ...
    @property
    def InternalLayers(self) -> bool: ...
    @InternalLayers.setter
    def InternalLayers(self, value: bool) -> None: ...
    @property
    def KeepInColor(self) -> NXColor: ...
    @KeepInColor.setter
    def KeepInColor(self, value: NXColor) -> None: ...
    @property
    def KeepInLayer(self) -> int: ...
    @KeepInLayer.setter
    def KeepInLayer(self, value: int) -> None: ...
    @property
    def KeepInTranslucency(self) -> int: ...
    @KeepInTranslucency.setter
    def KeepInTranslucency(self, value: int) -> None: ...
    @property
    def KeepOutColor(self) -> NXColor: ...
    @KeepOutColor.setter
    def KeepOutColor(self, value: NXColor) -> None: ...
    @property
    def KeepOutLayer(self) -> int: ...
    @KeepOutLayer.setter
    def KeepOutLayer(self, value: int) -> None: ...
    @property
    def KeepOutTranslucency(self) -> int: ...
    @KeepOutTranslucency.setter
    def KeepOutTranslucency(self, value: int) -> None: ...
    @property
    def MailNotify(self) -> bool: ...
    @MailNotify.setter
    def MailNotify(self, value: bool) -> None: ...
    @property
    def MailProtocol(self) -> PcbExchange.PreferencesBuilder.MailProtocolTypeName: ...
    @MailProtocol.setter
    def MailProtocol(self, value: PcbExchange.PreferencesBuilder.MailProtocolTypeName) -> None: ...
    @property
    def MaskMaxNumber(self) -> int: ...
    @MaskMaxNumber.setter
    def MaskMaxNumber(self, value: int) -> None: ...
    @property
    def MaskNamePrefix(self) -> str: ...
    @MaskNamePrefix.setter
    def MaskNamePrefix(self, value: str) -> None: ...
    @property
    def MaskNameSuffix(self) -> str: ...
    @MaskNameSuffix.setter
    def MaskNameSuffix(self, value: str) -> None: ...
    @property
    def MergeTracesAndPads(self) -> bool: ...
    @MergeTracesAndPads.setter
    def MergeTracesAndPads(self, value: bool) -> None: ...
    @property
    def ModelForStructuralAnalysis(self) -> PcbExchange.PreferencesBuilder.ModelForStructuralAnalysisTypeName: ...
    @ModelForStructuralAnalysis.setter
    def ModelForStructuralAnalysis(self, value: PcbExchange.PreferencesBuilder.ModelForStructuralAnalysisTypeName) -> None: ...
    @property
    def ModelForThermalAnalysis(self) -> PcbExchange.PreferencesBuilder.ModelForThermalAnalysisTypeName: ...
    @ModelForThermalAnalysis.setter
    def ModelForThermalAnalysis(self, value: PcbExchange.PreferencesBuilder.ModelForThermalAnalysisTypeName) -> None: ...
    @property
    def MonitorEDMDToggle(self) -> bool: ...
    @MonitorEDMDToggle.setter
    def MonitorEDMDToggle(self, value: bool) -> None: ...
    @property
    def Negative(self) -> bool: ...
    @Negative.setter
    def Negative(self, value: bool) -> None: ...
    @property
    def OtherColor(self) -> NXColor: ...
    @OtherColor.setter
    def OtherColor(self, value: NXColor) -> None: ...
    @property
    def OtherLayer(self) -> int: ...
    @OtherLayer.setter
    def OtherLayer(self, value: int) -> None: ...
    @property
    def OtherTranslucency(self) -> int: ...
    @OtherTranslucency.setter
    def OtherTranslucency(self, value: int) -> None: ...
    @property
    def PadMaxNumber(self) -> int: ...
    @PadMaxNumber.setter
    def PadMaxNumber(self, value: int) -> None: ...
    @property
    def PadNamePrefix(self) -> str: ...
    @PadNamePrefix.setter
    def PadNamePrefix(self, value: str) -> None: ...
    @property
    def PadNameSuffix(self) -> str: ...
    @PadNameSuffix.setter
    def PadNameSuffix(self, value: str) -> None: ...
    @property
    def PasteMaskMaxNumber(self) -> int: ...
    @PasteMaskMaxNumber.setter
    def PasteMaskMaxNumber(self, value: int) -> None: ...
    @property
    def PasteMaskNamePrefix(self) -> str: ...
    @PasteMaskNamePrefix.setter
    def PasteMaskNamePrefix(self, value: str) -> None: ...
    @property
    def PasteMaskNameSuffix(self) -> str: ...
    @PasteMaskNameSuffix.setter
    def PasteMaskNameSuffix(self, value: str) -> None: ...
    @property
    def PcaNamePrefix(self) -> str: ...
    @PcaNamePrefix.setter
    def PcaNamePrefix(self, value: str) -> None: ...
    @property
    def PcaNameSuffix(self) -> str: ...
    @PcaNameSuffix.setter
    def PcaNameSuffix(self, value: str) -> None: ...
    @property
    def ProjectView(self) -> str: ...
    @ProjectView.setter
    def ProjectView(self, value: str) -> None: ...
    @property
    def ProjectViewToggle(self) -> bool: ...
    @ProjectViewToggle.setter
    def ProjectViewToggle(self, value: bool) -> None: ...
    @property
    def ReadWriteDir(self) -> str: ...
    @ReadWriteDir.setter
    def ReadWriteDir(self, value: str) -> None: ...
    @property
    def ResistorModel(self) -> PcbExchange.PreferencesBuilder.ResistorModelTypeName: ...
    @ResistorModel.setter
    def ResistorModel(self, value: PcbExchange.PreferencesBuilder.ResistorModelTypeName) -> None: ...
    @property
    def SettingsSource(self) -> PcbExchange.PreferencesBuilder.SettingsSourceTypeName: ...
    @SettingsSource.setter
    def SettingsSource(self, value: PcbExchange.PreferencesBuilder.SettingsSourceTypeName) -> None: ...
    @property
    def SpecifiedSettingsFolder(self) -> str: ...
    @SpecifiedSettingsFolder.setter
    def SpecifiedSettingsFolder(self, value: str) -> None: ...
    @property
    def SpecifyNewCompDir(self) -> str: ...
    @SpecifyNewCompDir.setter
    def SpecifyNewCompDir(self, value: str) -> None: ...
    @property
    def StructuralAlgorithm(self) -> PcbExchange.PreferencesBuilder.StructuralAlgorithmTypeName: ...
    @StructuralAlgorithm.setter
    def StructuralAlgorithm(self, value: PcbExchange.PreferencesBuilder.StructuralAlgorithmTypeName) -> None: ...
    @property
    def ThermalAlgorithm(self) -> PcbExchange.PreferencesBuilder.ThermalAlgorithmTypeName: ...
    @ThermalAlgorithm.setter
    def ThermalAlgorithm(self, value: PcbExchange.PreferencesBuilder.ThermalAlgorithmTypeName) -> None: ...
    @property
    def ThicknessForStructuralAnalysis(self) -> Expression: ...
    @ThicknessForStructuralAnalysis.setter
    def ThicknessForStructuralAnalysis(self, value: Expression) -> None: ...
    @property
    def ThicknessSourceForStructuralAnalysis(self) -> PcbExchange.PreferencesBuilder.ThicknessSourceForStructuralAnalysisTypeName: ...
    @ThicknessSourceForStructuralAnalysis.setter
    def ThicknessSourceForStructuralAnalysis(self, value: PcbExchange.PreferencesBuilder.ThicknessSourceForStructuralAnalysisTypeName) -> None: ...
    @property
    def TraceMaxNumber(self) -> int: ...
    @TraceMaxNumber.setter
    def TraceMaxNumber(self, value: int) -> None: ...
    @property
    def TraceNamePrefix(self) -> str: ...
    @TraceNamePrefix.setter
    def TraceNamePrefix(self, value: str) -> None: ...
    @property
    def TraceNameSuffix(self) -> str: ...
    @TraceNameSuffix.setter
    def TraceNameSuffix(self, value: str) -> None: ...


    class ThicknessSourceForStructuralAnalysisTypeName(enum.Enum):
        FromPart= 0
        Specify= 1
    

    class ThermalAlgorithmTypeName(enum.Enum):
        Discretized= 0
        Equivalent= 1
    

    class StructuralAlgorithmTypeName(enum.Enum):
        Equivalent= 0
    

    class SettingsSourceTypeName(enum.Enum):
        IniFiles= 0
        SpecifiedSettingsFolder= 1
        CustomerDefaults= 2
    

    class ResistorModelTypeName(enum.Enum):
        None_= 0
        DissipationOnly= 1
        ThetaCB= 2
        ThetaJCJB= 3
        ThetaJCCB= 4
    

    class ModelForThermalAnalysisTypeName(enum.Enum):
        SingleLayer= 0
        TopAndBottom= 1
        MultiLayer= 2
        Solid= 3
    

    class ModelForStructuralAnalysisTypeName(enum.Enum):
        SingleLayer= 0
        MultiLayer= 1
    

    class MailProtocolTypeName(enum.Enum):
        Mapi= 0
        Smtp= 1
    

    class ImportTraceMenuTypeName(enum.Enum):
        Curves= 0
        Sheets= 1
        Bodies= 2
    

    class ImportPadMenuTypeName(enum.Enum):
        Curves= 0
        Sheets= 1
        Bodies= 2
    

    class ImportMaskMenuTypeName(enum.Enum):
        Curves= 0
        Sheets= 1
        Bodies= 2
    

    class ImportGenericMenuTypeName(enum.Enum):
        Curves= 0
        Sheets= 1
        Bodies= 2
    

    class ImportExportFlexBentType(enum.Enum):
        No= 0
        ExportOnly= 1
        ImportAndExport= 2
    

    class GroupEntityComponentsByTypeName(enum.Enum):
        None_= 0
        Type= 1
        Layer= 2
    

    class ElementTypeForStructuralAnalysisTypeName(enum.Enum):
        Ctria3= 0
        Cquad4= 1
        Ctria6= 2
        Cquad8= 3
    

    class DefaultPcaNameTypeName(enum.Enum):
        CurrentNXModel= 0
        ECADModelName= 1
        SpecifyAtImport= 2
    

    class CreateNewComponentsInTypeName(enum.Enum):
        DirectoryOfECADFiles= 0
        DirectoryOfNXParts= 1
        Specify= 2
    

    class ComponentsModelTypeName(enum.Enum):
        ZeroResistor= 0
        OneResistor= 1
        TwoResistor= 2
        None_= 3
    

    class ComponentsMaterialFromTypeName(enum.Enum):
        Pcb= 0
        Nx= 1
    

    class ComponentsHeightFromTypeName(enum.Enum):
        FootprintDefinition= 0
        PartDefinition= 1
    

    class ComponentsElementThicknessOptionsTypeName(enum.Enum):
        Null= 0
        Specify= 1
    

    class ComponentsElementSizeOptionsTypeName(enum.Enum):
        Auto= 0
        Specify= 1
    

    class ComponentsConnectionToBoardTypeName(enum.Enum):
        Rbe2= 0
        Rbe3= 1
    

    class ComponentLoadOptionsTypeName(enum.Enum):
        LoadAndCreateAssemblyComponents= 0
        CreateBodiesOnly= 1
        LoadAssemblyComponentsCreateBodies= 2
    

    class BoardThicknessSourceTypeName(enum.Enum):
        FromPart= 0
        Specify= 1
    

class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class Manager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetManager(self, owner: Session) -> PcbExchange.Manager: ...
    def CreateBoardAttributesBuilder(self, part: NXObject) -> PcbExchange.BoardAttributesBuilder: ...
    def CreateComponentAttributesBuilder(self, part: NXObject) -> PcbExchange.ComponentAttributesBuilder: ...
    def CreateHoleAttributesBuilder(self, part: NXObject) -> PcbExchange.HoleAttributesBuilder: ...
    def CreateAreaAttributesBuilder(self, part: NXObject) -> PcbExchange.AreaAttributesBuilder: ...
    def CreateEcadImportBuilder(self, part: NXObject) -> PcbExchange.EcadImportBuilder: ...
    def CreateEcadExportBuilder(self, part: NXObject) -> PcbExchange.EcadExportBuilder: ...
    def CreateCompareAndUpdateBuilder(self, part: NXObject) -> PcbExchange.CompareAndUpdateBuilder: ...
    def CreateIdxImportBuilder(self, part: NXObject) -> PcbExchange.IdxImportBuilder: ...
    def CreateIdxExportBuilder(self, part: NXObject) -> PcbExchange.IdxExportBuilder: ...
    def CreateIdxCompareBuilder(self, part: NXObject) -> PcbExchange.IdxCompareBuilder: ...
    def CreateBoardPropertiesBuilder(self, part: NXObject) -> PcbExchange.BoardPropertiesBuilder: ...
    def CreateEntityFilterBuilder(self, part: NXObject, entityFilter: PcbExchange.EntityFilter) -> PcbExchange.EntityFilterBuilder: ...
    @typing.overload
    def CreateDesignRuleBuilder(self, part: NXObject) -> PcbExchange.DesignRuleBuilder: ...
    @typing.overload
    def CreateDesignRuleBuilder(self, ruleToEdit: PcbExchange.DesignRule) -> PcbExchange.DesignRuleBuilder: ...
    def CreateDesignValidator(self, part: NXObject) -> PcbExchange.DesignValidator: ...
    def CreateEcadPanelImportBuilder(self, part: NXObject) -> PcbExchange.EcadPanelImportBuilder: ...
    def CreateExternalDataImportBuilder(self, part: NXObject) -> PcbExchange.ExternalDataImportBuilder: ...
    def ReplaceWithLibraryComponent(self, components: typing.List[NXObject]) -> None: ...
    def CreateReportBuilder(self, part: NXObject) -> PcbExchange.ReportBuilder: ...
    def CreatePreferencesBuilder(self, part: NXObject) -> PcbExchange.PreferencesBuilder: ...
    def CreateIncrementalImportBuilder(self, part: NXObject) -> PcbExchange.IncrementalImportBuilder: ...
    def TagModelAsBaseline(self) -> None: ...
    def CreateIncrementalExportBuilder(self, part: NXObject) -> PcbExchange.IncrementalExportBuilder: ...
    def CreateIncrementalChange(self) -> PcbExchange.IncrementalChange: ...
    def CreateAreaMappingBuilder(self, part: NXObject, areaMapping: PcbExchange.AreaMapping) -> PcbExchange.AreaMappingBuilder: ...
    def CreateAdvancedConductivityBuilder(self, part: NXObject) -> PcbExchange.AdvancedConductivityBuilder: ...
    def CreateTemplateBuilder(self, part: NXObject) -> PcbExchange.TemplateBuilder: ...
    def PrintPcbxAssembly(self, validateLayers: bool, validateBoard: bool, validateComponents: bool, validateAreas: bool, validateHoles: bool, validateTraces: bool, validatePads: bool, validateSymbols: bool, validateTestPoints: bool, validateDrawing: bool, validateMasks: bool, validateGenericShapes: bool, validateNets: bool, validateVariants: bool) -> None: ...
    def PrepareSmartDiffFiles(self, fileName: str, masterFile: str, diffFile: str) -> None: ...
    def PrintPreferences(self, fileName: str) -> None: ...
    def CreateComponentPlacementOutlineBuilder(self, part: NXObject) -> PcbExchange.ComponentPlacementOutlineBuilder: ...
    def SuspendNavigatorUpdate(self) -> None: ...
    def ResumeNavigatorUpdate(self, refreshNavigator: bool) -> None: ...
    def Tag(self) -> Tag: ...



class IncrementalImportBuilder(Builder):
    def __init__(self) -> None: ...
    def AcceptAll(self) -> None: ...
    def RejectAll(self) -> None: ...
    def AcknowledgeAll(self) -> None: ...
    def IgnoreAll(self) -> None: ...
    def AcknowledgeResponse(self, id: str) -> None: ...
    def IgnoreResponse(self, id: str) -> None: ...
    def AcceptChange(self, id: str) -> None: ...
    def RejectChange(self, id: str) -> None: ...
    def RejectBoardChange(self, id: str) -> None: ...
    def AcceptBoardChange(self, id: str) -> None: ...
    def AddNewComment(self, id: str, comment: str) -> None: ...
    def PreviewChanges(self) -> None: ...
    def UnhighlightAll(self) -> None: ...
    def ReadImportFile(self) -> None: ...
    def SetExistingPart(self) -> DisplayableObject: ...
    def SetBoardUpdated(self, updated: bool) -> None: ...
    def CancelIncrementReview(self) -> None: ...
    def ClearProcessedIncrementalGroupVec(self) -> None: ...
    @property
    def Filename(self) -> str: ...
    @Filename.setter
    def Filename(self, value: str) -> None: ...
    @property
    def Output(self) -> str: ...
    @Output.setter
    def Output(self, value: str) -> None: ...


class IncrementalExportBuilder(Builder):
    def __init__(self) -> None: ...
    def GetIncrementalChanges(self) -> typing.List[PcbExchange.IncrementalChange]: ...
    def SetIncrementalChanges(self, changes: typing.List[PcbExchange.IncrementalChange]) -> None: ...
    def RunPreExportIncrementalHook(self) -> None: ...
    @property
    def CloneAssembly(self) -> bool: ...
    @CloneAssembly.setter
    def CloneAssembly(self, value: bool) -> None: ...
    @property
    def FileFormat(self) -> PcbExchange.IncrementalExportBuilder.FormatEnum: ...
    @FileFormat.setter
    def FileFormat(self, value: PcbExchange.IncrementalExportBuilder.FormatEnum) -> None: ...
    @property
    def FileNote(self) -> str: ...
    @FileNote.setter
    def FileNote(self, value: str) -> None: ...
    @property
    def Output(self) -> str: ...
    @Output.setter
    def Output(self, value: str) -> None: ...
    @property
    def SelectedObjects(self) -> SelectNXObjectList: ...
    @SelectedObjects.setter
    def SelectedObjects(self, value: SelectNXObjectList) -> None: ...
    @property
    def TargetLocation(self) -> PcbExchange.IncrementalExportBuilder.TargetLocationEnum: ...
    @TargetLocation.setter
    def TargetLocation(self, value: PcbExchange.IncrementalExportBuilder.TargetLocationEnum) -> None: ...
    @property
    def UseCloneSelection(self) -> bool: ...
    @UseCloneSelection.setter
    def UseCloneSelection(self, value: bool) -> None: ...


    class TargetLocationEnum(enum.Enum):
        Os= 0
        TeamcenterCS= 1
    

    class FormatEnum(enum.Enum):
        Idx2= 0
        Idx3= 1
    

class IncrementalChange(TaggedObject):
    def __init__(self) -> None: ...
    def GetAttributes(self, names: str) -> str: ...
    @property
    def Accepted(self) -> bool: ...
    @Accepted.setter
    def Accepted(self, value: bool) -> None: ...
    @property
    def Comments(self) -> str: ...
    @Comments.setter
    def Comments(self, value: str) -> None: ...
    @property
    def Transaction(self) -> str: ...
    @Transaction.setter
    def Transaction(self, value: str) -> None: ...


class IdxImportBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AssemblyName(self) -> str: ...
    @AssemblyName.setter
    def AssemblyName(self, value: str) -> None: ...
    @property
    def AssemblyNumber(self) -> str: ...
    @AssemblyNumber.setter
    def AssemblyNumber(self, value: str) -> None: ...
    @property
    def AssemblyRevision(self) -> str: ...
    @AssemblyRevision.setter
    def AssemblyRevision(self, value: str) -> None: ...
    @property
    def BaselineFile(self) -> str: ...
    @BaselineFile.setter
    def BaselineFile(self, value: str) -> None: ...
    @property
    def CollaborationDir(self) -> str: ...
    @CollaborationDir.setter
    def CollaborationDir(self, value: str) -> None: ...
    @property
    def IdxDataFrom(self) -> PcbExchange.IdxImportBuilder.DataLocation: ...
    @IdxDataFrom.setter
    def IdxDataFrom(self, value: PcbExchange.IdxImportBuilder.DataLocation) -> None: ...
    @property
    def IdxNumber(self) -> str: ...
    @IdxNumber.setter
    def IdxNumber(self, value: str) -> None: ...
    @property
    def IdxRevision(self) -> str: ...
    @IdxRevision.setter
    def IdxRevision(self, value: str) -> None: ...
    @property
    def OutputPartFile(self) -> str: ...
    @OutputPartFile.setter
    def OutputPartFile(self, value: str) -> None: ...
    @property
    def UseCurrentPart(self) -> bool: ...
    @UseCurrentPart.setter
    def UseCurrentPart(self, value: bool) -> None: ...
    @property
    def UseExistComp(self) -> bool: ...
    @UseExistComp.setter
    def UseExistComp(self, value: bool) -> None: ...


    class DataLocation(enum.Enum):
        Local= 0
        TeamcenterDS= 1
        TeamcenterCS= 2
    

class IdxExportBuilder(Builder):
    def __init__(self) -> None: ...
    def RunPreExportBaselineHook(self) -> None: ...
    @property
    def BaselineFile(self) -> str: ...
    @BaselineFile.setter
    def BaselineFile(self, value: str) -> None: ...
    @property
    def BaselineLocation(self) -> PcbExchange.IdxExportBuilder.IdxLocationEnum: ...
    @BaselineLocation.setter
    def BaselineLocation(self, value: PcbExchange.IdxExportBuilder.IdxLocationEnum) -> None: ...
    @property
    def BaselineNumber(self) -> str: ...
    @BaselineNumber.setter
    def BaselineNumber(self, value: str) -> None: ...
    @property
    def BaselineRevision(self) -> str: ...
    @BaselineRevision.setter
    def BaselineRevision(self, value: str) -> None: ...
    @property
    def CloneAssembly(self) -> bool: ...
    @CloneAssembly.setter
    def CloneAssembly(self, value: bool) -> None: ...
    @property
    def FileFormat(self) -> PcbExchange.IdxExportBuilder.FileFormatEnum: ...
    @FileFormat.setter
    def FileFormat(self, value: PcbExchange.IdxExportBuilder.FileFormatEnum) -> None: ...
    @property
    def FileNote(self) -> str: ...
    @FileNote.setter
    def FileNote(self, value: str) -> None: ...
    @property
    def FileUnits(self) -> PcbExchange.IdxExportBuilder.ExportUnitsEnum: ...
    @FileUnits.setter
    def FileUnits(self, value: PcbExchange.IdxExportBuilder.ExportUnitsEnum) -> None: ...
    @property
    def SelectedObjects(self) -> SelectNXObjectList: ...
    @SelectedObjects.setter
    def SelectedObjects(self, value: SelectNXObjectList) -> None: ...
    @property
    def ShowLog(self) -> bool: ...
    @ShowLog.setter
    def ShowLog(self, value: bool) -> None: ...
    @property
    def TagModel(self) -> bool: ...
    @TagModel.setter
    def TagModel(self, value: bool) -> None: ...
    @property
    def UseCloneSelection(self) -> bool: ...
    @UseCloneSelection.setter
    def UseCloneSelection(self, value: bool) -> None: ...
    @property
    def UseCurrentWorkPart(self) -> bool: ...
    @UseCurrentWorkPart.setter
    def UseCurrentWorkPart(self, value: bool) -> None: ...


    class IdxLocationEnum(enum.Enum):
        Os= 0
        TeamcenterDS= 1
        TeamcenterCS= 2
    

    class FileFormatEnum(enum.Enum):
        Idx2= 0
        Idx3= 1
    

    class ExportUnitsEnum(enum.Enum):
        Mm= 0
        Thou= 1
    

class IdxCompareBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def SourceFile(self) -> str: ...
    @SourceFile.setter
    def SourceFile(self, value: str) -> None: ...
    @property
    def SourceType(self) -> PcbExchange.IdxCompareBuilder.SourceTypeEnum: ...
    @SourceType.setter
    def SourceType(self, value: PcbExchange.IdxCompareBuilder.SourceTypeEnum) -> None: ...
    @property
    def TargetFile(self) -> str: ...
    @TargetFile.setter
    def TargetFile(self, value: str) -> None: ...


    class SourceTypeEnum(enum.Enum):
        Nx= 0
        Idx= 1
    

class HoleAttributesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AssociatedPart(self) -> PcbExchange.HoleAttributesBuilder.AssociatedPartEnum: ...
    @AssociatedPart.setter
    def AssociatedPart(self, value: PcbExchange.HoleAttributesBuilder.AssociatedPartEnum) -> None: ...
    @property
    def Features(self) -> Features.SelectFeatureList: ...
    @Features.setter
    def Features(self, value: Features.SelectFeatureList) -> None: ...
    @property
    def HoleType(self) -> PcbExchange.HoleAttributesBuilder.TypeEnum: ...
    @HoleType.setter
    def HoleType(self, value: PcbExchange.HoleAttributesBuilder.TypeEnum) -> None: ...
    @property
    def Owner(self) -> PcbExchange.HoleAttributesBuilder.OwnerEnum: ...
    @Owner.setter
    def Owner(self, value: PcbExchange.HoleAttributesBuilder.OwnerEnum) -> None: ...
    @property
    def PlatingStyle(self) -> PcbExchange.HoleAttributesBuilder.PlatingStyleEnum: ...
    @PlatingStyle.setter
    def PlatingStyle(self, value: PcbExchange.HoleAttributesBuilder.PlatingStyleEnum) -> None: ...
    @property
    def SpecifiedPart(self) -> str: ...
    @SpecifiedPart.setter
    def SpecifiedPart(self, value: str) -> None: ...


    class TypeEnum(enum.Enum):
        Pin= 1
        Via= 2
        Mounting= 3
        Tool= 4
        Other= 5
    

    class PlatingStyleEnum(enum.Enum):
        PlatedThru= 1
        NonPlatedThru= 2
    

    class OwnerEnum(enum.Enum):
        Mcad= 1
        Ecad= 2
        Unowned= 3
    

    class AssociatedPartEnum(enum.Enum):
        Board= 1
        Norefdes= 2
        Specify= 3
    

class ExternalDataImportBuilder(Builder):
    def __init__(self) -> None: ...
    def QueryEntities(self) -> None: ...
    def GetLayerNames(self) -> str: ...
    def GetLayerImported(self, name: str) -> PcbExchange.ExternalDataImportBuilder.JaPcbExternalDataImportBuilderImportoption: ...
    def SetLayerImported(self, name: str, importOption: PcbExchange.ExternalDataImportBuilder.JaPcbExternalDataImportBuilderImportoption) -> None: ...
    def GetNetNames(self) -> str: ...
    def GetNetImported(self, name: str) -> PcbExchange.ExternalDataImportBuilder.JaPcbExternalDataImportBuilderImportoption: ...
    def SetNetImported(self, name: str, importOption: PcbExchange.ExternalDataImportBuilder.JaPcbExternalDataImportBuilderImportoption) -> None: ...
    def GetPadstackNames(self) -> str: ...
    def GetPadstackImported(self, name: str) -> PcbExchange.ExternalDataImportBuilder.JaPcbExternalDataImportBuilderImportoption: ...
    def SetPadstackImported(self, name: str, importOption: PcbExchange.ExternalDataImportBuilder.JaPcbExternalDataImportBuilderImportoption) -> None: ...
    def GetPadstackPart(self, name: str) -> str: ...
    def SetPadstackPart(self, name: str, part: str) -> None: ...
    @property
    def Filename(self) -> str: ...
    @Filename.setter
    def Filename(self, value: str) -> None: ...
    @property
    def NetsFilterString(self) -> str: ...
    @NetsFilterString.setter
    def NetsFilterString(self, value: str) -> None: ...
    @property
    def NetsFilterStringEnabled(self) -> bool: ...
    @NetsFilterStringEnabled.setter
    def NetsFilterStringEnabled(self, value: bool) -> None: ...
    @property
    def ShowLog(self) -> bool: ...
    @ShowLog.setter
    def ShowLog(self, value: bool) -> None: ...


    class JaPcbExternalDataImportBuilderImportoption(enum.Enum):
        Import= 0
        DoNotImport= 1
    

class ExtdataUpdator(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetExtdataUpdator(self, owner: Session) -> PcbExchange.ExtdataUpdator: ...
    def Read(self, fName: str, layerNames: str) -> str: ...
    def Update(self, fName: str, layerNames: str, netNames: str, bTextualFilter: bool, textualFilterStr: str) -> None: ...
    def Tag(self) -> Tag: ...



class EntityFilterBuilder(Builder):
    def __init__(self) -> None: ...
    def SetUserDefiniedFilters(self, filters: str) -> None: ...
    @property
    def ComponentMaxHeight(self) -> float: ...
    @ComponentMaxHeight.setter
    def ComponentMaxHeight(self, value: float) -> None: ...
    @property
    def ComponentMaxSize(self) -> float: ...
    @ComponentMaxSize.setter
    def ComponentMaxSize(self, value: float) -> None: ...
    @property
    def ComponentMinHeight(self) -> float: ...
    @ComponentMinHeight.setter
    def ComponentMinHeight(self, value: float) -> None: ...
    @property
    def ComponentMinSize(self) -> float: ...
    @ComponentMinSize.setter
    def ComponentMinSize(self, value: float) -> None: ...
    @property
    def HoleMaxDiameter(self) -> float: ...
    @HoleMaxDiameter.setter
    def HoleMaxDiameter(self, value: float) -> None: ...
    @property
    def HoleMaxSize(self) -> float: ...
    @HoleMaxSize.setter
    def HoleMaxSize(self, value: float) -> None: ...
    @property
    def HoleMinDiameter(self) -> float: ...
    @HoleMinDiameter.setter
    def HoleMinDiameter(self, value: float) -> None: ...
    @property
    def HoleMinSize(self) -> float: ...
    @HoleMinSize.setter
    def HoleMinSize(self, value: float) -> None: ...
    @property
    def LengthUnits(self) -> PcbExchange.EntityFilterBuilder.LengthUnitsEnum: ...
    @LengthUnits.setter
    def LengthUnits(self, value: PcbExchange.EntityFilterBuilder.LengthUnitsEnum) -> None: ...
    @property
    def RemoveBlindBuriedViaHoles(self) -> bool: ...
    @RemoveBlindBuriedViaHoles.setter
    def RemoveBlindBuriedViaHoles(self, value: bool) -> None: ...
    @property
    def RemoveComponentsWithHeight(self) -> bool: ...
    @RemoveComponentsWithHeight.setter
    def RemoveComponentsWithHeight(self, value: bool) -> None: ...
    @property
    def RemoveComponentsWithSize(self) -> bool: ...
    @RemoveComponentsWithSize.setter
    def RemoveComponentsWithSize(self, value: bool) -> None: ...
    @property
    def RemoveEcadComponents(self) -> bool: ...
    @RemoveEcadComponents.setter
    def RemoveEcadComponents(self, value: bool) -> None: ...
    @property
    def RemoveHolesWithDiameter(self) -> bool: ...
    @RemoveHolesWithDiameter.setter
    def RemoveHolesWithDiameter(self, value: bool) -> None: ...
    @property
    def RemoveHolesWithSize(self) -> bool: ...
    @RemoveHolesWithSize.setter
    def RemoveHolesWithSize(self, value: bool) -> None: ...
    @property
    def RemoveMcadComponents(self) -> bool: ...
    @RemoveMcadComponents.setter
    def RemoveMcadComponents(self, value: bool) -> None: ...
    @property
    def RemoveMountingHoles(self) -> bool: ...
    @RemoveMountingHoles.setter
    def RemoveMountingHoles(self, value: bool) -> None: ...
    @property
    def RemoveOtherHoles(self) -> bool: ...
    @RemoveOtherHoles.setter
    def RemoveOtherHoles(self, value: bool) -> None: ...
    @property
    def RemoveOtherKeepoutAreas(self) -> bool: ...
    @RemoveOtherKeepoutAreas.setter
    def RemoveOtherKeepoutAreas(self, value: bool) -> None: ...
    @property
    def RemovePinHoles(self) -> bool: ...
    @RemovePinHoles.setter
    def RemovePinHoles(self, value: bool) -> None: ...
    @property
    def RemovePlacedComponents(self) -> bool: ...
    @RemovePlacedComponents.setter
    def RemovePlacedComponents(self, value: bool) -> None: ...
    @property
    def RemovePlacementGroupKeepinAreas(self) -> bool: ...
    @RemovePlacementGroupKeepinAreas.setter
    def RemovePlacementGroupKeepinAreas(self, value: bool) -> None: ...
    @property
    def RemovePlacementKeepinAreas(self) -> bool: ...
    @RemovePlacementKeepinAreas.setter
    def RemovePlacementKeepinAreas(self, value: bool) -> None: ...
    @property
    def RemovePlacementKeepoutAreas(self) -> bool: ...
    @RemovePlacementKeepoutAreas.setter
    def RemovePlacementKeepoutAreas(self, value: bool) -> None: ...
    @property
    def RemoveRoutingKeepinAreas(self) -> bool: ...
    @RemoveRoutingKeepinAreas.setter
    def RemoveRoutingKeepinAreas(self, value: bool) -> None: ...
    @property
    def RemoveRoutingKeepoutAreas(self) -> bool: ...
    @RemoveRoutingKeepoutAreas.setter
    def RemoveRoutingKeepoutAreas(self, value: bool) -> None: ...
    @property
    def RemoveToolingHoles(self) -> bool: ...
    @RemoveToolingHoles.setter
    def RemoveToolingHoles(self, value: bool) -> None: ...
    @property
    def RemoveUnplacedComponents(self) -> bool: ...
    @RemoveUnplacedComponents.setter
    def RemoveUnplacedComponents(self, value: bool) -> None: ...
    @property
    def RemoveViaHoles(self) -> bool: ...
    @RemoveViaHoles.setter
    def RemoveViaHoles(self, value: bool) -> None: ...
    @property
    def RemoveViaKeepoutAreas(self) -> bool: ...
    @RemoveViaKeepoutAreas.setter
    def RemoveViaKeepoutAreas(self, value: bool) -> None: ...


    class LengthUnitsEnum(enum.Enum):
        Millimeters= 0
        Inches= 1
    

class EntityFilter(NXObject):
    def __init__(self) -> None: ...


class EntityCategory(enum.Enum):
    Component= 0
    Board= 1
    Mechanical= 2
    KeepOut= 3
    Copper= 4


class EcadPanelImportBuilder(Builder):
    def __init__(self) -> None: ...
    def GetOutputParts(self) -> str: ...
    def SetOutputParts(self, outputsParts: str) -> None: ...
    def GetOutputNames(self) -> str: ...
    def SetOutputNames(self, outputsNames: str) -> None: ...
    def PrepareOdbFolder(self) -> str: ...
    def GetEntityFilter(self) -> PcbExchange.EntityFilter: ...
    def SetEntityFilter(self, filter: PcbExchange.EntityFilter) -> None: ...
    @property
    def Breakaway(self) -> bool: ...
    @Breakaway.setter
    def Breakaway(self, value: bool) -> None: ...
    @property
    def IsPanelFolder(self) -> bool: ...
    @IsPanelFolder.setter
    def IsPanelFolder(self, value: bool) -> None: ...
    @property
    def OptimizationMethod(self) -> PcbExchange.EcadPanelImportBuilder.OptimizationMethodOptions: ...
    @OptimizationMethod.setter
    def OptimizationMethod(self, value: PcbExchange.EcadPanelImportBuilder.OptimizationMethodOptions) -> None: ...
    @property
    def PanelFile(self) -> str: ...
    @PanelFile.setter
    def PanelFile(self, value: str) -> None: ...
    @property
    def PanelFolder(self) -> str: ...
    @PanelFolder.setter
    def PanelFolder(self, value: str) -> None: ...
    @property
    def PanelLocation(self) -> PcbExchange.EcadPanelImportBuilder.PanelLocationEnum: ...
    @PanelLocation.setter
    def PanelLocation(self, value: PcbExchange.EcadPanelImportBuilder.PanelLocationEnum) -> None: ...
    @property
    def ShowLog(self) -> bool: ...
    @ShowLog.setter
    def ShowLog(self, value: bool) -> None: ...
    @property
    def SolderMasks(self) -> bool: ...
    @SolderMasks.setter
    def SolderMasks(self, value: bool) -> None: ...
    @property
    def TcItemNumber(self) -> str: ...
    @TcItemNumber.setter
    def TcItemNumber(self, value: str) -> None: ...
    @property
    def TcItemRevision(self) -> str: ...
    @TcItemRevision.setter
    def TcItemRevision(self, value: str) -> None: ...
    @property
    def Thieving(self) -> PcbExchange.EcadPanelImportBuilder.ThievingOptions: ...
    @Thieving.setter
    def Thieving(self, value: PcbExchange.EcadPanelImportBuilder.ThievingOptions) -> None: ...
    @property
    def UseCurrentWorkPart(self) -> bool: ...
    @UseCurrentWorkPart.setter
    def UseCurrentWorkPart(self, value: bool) -> None: ...
    @property
    def UseEntityFilter(self) -> bool: ...
    @UseEntityFilter.setter
    def UseEntityFilter(self, value: bool) -> None: ...


    class ThievingOptions(enum.Enum):
        None_= 0
        Curve= 1
        SolidBody= 2
    

    class PanelLocationEnum(enum.Enum):
        Os= 0
        Tc= 1
    

    class OptimizationMethodOptions(enum.Enum):
        None_= 0
        Pattern= 1
    

class EcadImportBuilder(Builder):
    def __init__(self) -> None: ...
    def GetEntityFilter(self) -> PcbExchange.EntityFilter: ...
    def SetEntityFilter(self, filter: PcbExchange.EntityFilter) -> None: ...
    @property
    def BoardFile(self) -> str: ...
    @BoardFile.setter
    def BoardFile(self, value: str) -> None: ...
    @property
    def BoardFolder(self) -> str: ...
    @BoardFolder.setter
    def BoardFolder(self, value: str) -> None: ...
    @property
    def BoardThickness(self) -> Expression: ...
    @BoardThickness.setter
    def BoardThickness(self, value: Expression) -> None: ...
    @property
    def EcadLocation(self) -> PcbExchange.EcadImportBuilder.EcadLocationEnum: ...
    @EcadLocation.setter
    def EcadLocation(self, value: PcbExchange.EcadImportBuilder.EcadLocationEnum) -> None: ...
    @property
    def EcadNumber(self) -> str: ...
    @EcadNumber.setter
    def EcadNumber(self, value: str) -> None: ...
    @property
    def EcadRevision(self) -> str: ...
    @EcadRevision.setter
    def EcadRevision(self, value: str) -> None: ...
    @property
    def ImportOption(self) -> PcbExchange.EcadImportBuilder.ImportOptionEnum: ...
    @ImportOption.setter
    def ImportOption(self, value: PcbExchange.EcadImportBuilder.ImportOptionEnum) -> None: ...
    @property
    def IsOdbFolder(self) -> bool: ...
    @IsOdbFolder.setter
    def IsOdbFolder(self, value: bool) -> None: ...
    @property
    def LibraryFile(self) -> str: ...
    @LibraryFile.setter
    def LibraryFile(self, value: str) -> None: ...
    @property
    def OnlyUseExistingComponents(self) -> bool: ...
    @OnlyUseExistingComponents.setter
    def OnlyUseExistingComponents(self, value: bool) -> None: ...
    @property
    def OutputPart(self) -> str: ...
    @OutputPart.setter
    def OutputPart(self, value: str) -> None: ...
    @property
    def OverrideBoardThickness(self) -> bool: ...
    @OverrideBoardThickness.setter
    def OverrideBoardThickness(self, value: bool) -> None: ...
    @property
    def PartName(self) -> str: ...
    @PartName.setter
    def PartName(self, value: str) -> None: ...
    @property
    def PartNumber(self) -> str: ...
    @PartNumber.setter
    def PartNumber(self, value: str) -> None: ...
    @property
    def PartRevision(self) -> str: ...
    @PartRevision.setter
    def PartRevision(self, value: str) -> None: ...
    @property
    def ShowLog(self) -> bool: ...
    @ShowLog.setter
    def ShowLog(self, value: bool) -> None: ...
    @property
    def UseCurrentWorkPart(self) -> bool: ...
    @UseCurrentWorkPart.setter
    def UseCurrentWorkPart(self, value: bool) -> None: ...
    @property
    def UseEntityFilter(self) -> bool: ...
    @UseEntityFilter.setter
    def UseEntityFilter(self, value: bool) -> None: ...


    class ImportOptionEnum(enum.Enum):
        All= 0
        BoardOnly= 1
    

    class EcadLocationEnum(enum.Enum):
        Os= 0
        Tc= 1
    

class EcadExportBuilder(Builder):
    def __init__(self) -> None: ...
    def GetEntityFilter(self) -> PcbExchange.EntityFilter: ...
    def SetEntityFilter(self, filter: PcbExchange.EntityFilter) -> None: ...
    def GetAreaMapping(self) -> PcbExchange.AreaMapping: ...
    def SetAreaMapping(self, areaMapping: PcbExchange.AreaMapping) -> None: ...
    def RunPreExportEcadHook(self) -> None: ...
    @property
    def BoardFile(self) -> str: ...
    @BoardFile.setter
    def BoardFile(self, value: str) -> None: ...
    @property
    def BoardOnly(self) -> bool: ...
    @BoardOnly.setter
    def BoardOnly(self, value: bool) -> None: ...
    @property
    def EcadLocation(self) -> PcbExchange.EcadExportBuilder.EcadLocationEnum: ...
    @EcadLocation.setter
    def EcadLocation(self, value: PcbExchange.EcadExportBuilder.EcadLocationEnum) -> None: ...
    @property
    def EcadNumber(self) -> str: ...
    @EcadNumber.setter
    def EcadNumber(self, value: str) -> None: ...
    @property
    def EcadRevision(self) -> str: ...
    @EcadRevision.setter
    def EcadRevision(self, value: str) -> None: ...
    @property
    def FileFormat(self) -> PcbExchange.EcadExportBuilder.FileFormatEnum: ...
    @FileFormat.setter
    def FileFormat(self, value: PcbExchange.EcadExportBuilder.FileFormatEnum) -> None: ...
    @property
    def FileUnits(self) -> PcbExchange.EcadExportBuilder.ExportUnitsEnum: ...
    @FileUnits.setter
    def FileUnits(self, value: PcbExchange.EcadExportBuilder.ExportUnitsEnum) -> None: ...
    @property
    def LibraryFile(self) -> str: ...
    @LibraryFile.setter
    def LibraryFile(self, value: str) -> None: ...
    @property
    def ShowLog(self) -> bool: ...
    @ShowLog.setter
    def ShowLog(self, value: bool) -> None: ...
    @property
    def UseCurrentWorkPart(self) -> bool: ...
    @UseCurrentWorkPart.setter
    def UseCurrentWorkPart(self, value: bool) -> None: ...
    @property
    def UseEntityFilter(self) -> bool: ...
    @UseEntityFilter.setter
    def UseEntityFilter(self, value: bool) -> None: ...


    class FileFormatEnum(enum.Enum):
        Idf2= 0
        Idf3= 1
        Idf4= 2
        Zbmb= 3
        Zpcb= 4
        Idx2= 5
        Idx3= 6
    

    class ExportUnitsEnum(enum.Enum):
        Mm= 0
        Thou= 1
    

    class EcadLocationEnum(enum.Enum):
        Os= 0
        Tc= 1
    

class DesignValidator(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def GetInterferences(self) -> typing.List[PcbExchange.DesignInterference]: ...
    def PerformAnalysis(self) -> None: ...
    def ResetAnalysis(self) -> None: ...
    def ExportInterferences(self, filename: str) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def InterferenceCount(self) -> int: ...
    @InterferenceCount.setter
    def InterferenceCount(self, value: int) -> None: ...


class DesignRuleType(enum.Enum):
    Ortho= 0
    Distance= 1
    EdgeToEdge= 2


class DesignRuleSeverity(enum.Enum):
    Minimum= 0
    Optimal= 1


class DesignRuleMargin(enum.Enum):
    OrthoXY= 0
    OrthoZ= 1
    Xyz= 2
    LongToLong= 3
    ShortToShort= 4
    LongToShort= 5
    ShortToLong= 6
    Z= 7


class DesignRuleBuilder(Builder):
    def __init__(self) -> None: ...
    def GetEntityType(self, filterIndex: int) -> PcbExchange.EntityCategory: ...
    def SetEntityType(self, filterIndex: int, entityType: PcbExchange.EntityCategory) -> None: ...
    def GetComponentFilter(self, filterIndex: int) -> PcbExchange.DesignRuleBuilder.ComponentFilter: ...
    def SetComponentFilter(self, filterIndex: int, componentFilter: PcbExchange.DesignRuleBuilder.ComponentFilter) -> None: ...
    def GetFilterData(self, filterIndex: int) -> str: ...
    @typing.overload
    def SetFilterData(self, filterIndex: int, data: str) -> None: ...
    @typing.overload
    def SetFilterData(self, filterIndex: int, data: str) -> None: ...
    def GetBoardSide(self, filterIndex: int) -> PcbExchange.BoardSide: ...
    def SetBoardSide(self, filterIndex: int, side: PcbExchange.BoardSide) -> None: ...
    def GetConductiveLayerSide(self, filterIndex: int) -> PcbExchange.ConductiveLayerSide: ...
    def SetConductiveLayerSide(self, filterIndex: int, side: PcbExchange.ConductiveLayerSide) -> None: ...
    def GetClearance(self, direction: PcbExchange.DesignRuleMargin) -> float: ...
    def SetClearance(self, direction: PcbExchange.DesignRuleMargin, clearance: float) -> None: ...
    @property
    def ConstraintType(self) -> PcbExchange.DesignRuleType: ...
    @ConstraintType.setter
    def ConstraintType(self, value: PcbExchange.DesignRuleType) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Severity(self) -> PcbExchange.DesignRuleSeverity: ...
    @Severity.setter
    def Severity(self, value: PcbExchange.DesignRuleSeverity) -> None: ...


    class ComponentFilter(enum.Enum):
        Any= 0
        ByPackage= 1
        ByOwner= 2
        ByRefDes= 3
        ByPartNumber= 4
        ByCompType= 5
        ByPartName= 6
        ByAreaName= 7
        ByAreaSubtype= 8
        ByAreaOwner= 9
        ByAreaLayer= 10
        Specify= 11
        ByNetName= 12
        ByPackageClearanceType= 13
    

class DesignRule(TaggedObject):
    def __init__(self) -> None: ...
    def IncreasePriority(self) -> PcbExchange.DesignRule: ...
    def DecreasePriority(self) -> PcbExchange.DesignRule: ...
    def Destroy(self) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...


class DesignInterference(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def Rule(self) -> PcbExchange.DesignRule: ...
    @Rule.setter
    def Rule(self, value: PcbExchange.DesignRule) -> None: ...
    @property
    def RuleName(self) -> str: ...
    @RuleName.setter
    def RuleName(self, value: str) -> None: ...


class ConductiveLayerSide(enum.Enum):
    All= 0
    Top= 1
    Bottom= 2
    Outer= 3
    Inner= 4


class ComponentPlacementOutlineBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Sketch(self) -> SelectTaggedObjectList: ...
    @Sketch.setter
    def Sketch(self, value: SelectTaggedObjectList) -> None: ...


class ComponentAttributesBuilder(Builder):
    def __init__(self) -> None: ...
    def GetPackageClearanceTypes(self) -> str: ...
    def SetPackageClearanceTypes(self, data: str) -> None: ...
    @property
    def Components(self) -> SelectNXObjectList: ...
    @Components.setter
    def Components(self, value: SelectNXObjectList) -> None: ...
    @property
    def PackageClearanceTypesModification(self) -> bool: ...
    @PackageClearanceTypesModification.setter
    def PackageClearanceTypesModification(self, value: bool) -> None: ...
    @property
    def PackageName(self) -> str: ...
    @PackageName.setter
    def PackageName(self, value: str) -> None: ...
    @property
    def PackageNameModification(self) -> bool: ...
    @PackageNameModification.setter
    def PackageNameModification(self, value: bool) -> None: ...
    @property
    def PartNumber(self) -> str: ...
    @PartNumber.setter
    def PartNumber(self, value: str) -> None: ...
    @property
    def PartNumberModification(self) -> bool: ...
    @PartNumberModification.setter
    def PartNumberModification(self, value: bool) -> None: ...
    @property
    def PlacementOwner(self) -> PcbExchange.ComponentAttributesBuilder.PlacementOwnerEnum: ...
    @PlacementOwner.setter
    def PlacementOwner(self, value: PcbExchange.ComponentAttributesBuilder.PlacementOwnerEnum) -> None: ...
    @property
    def ReferenceDesignator(self) -> str: ...
    @ReferenceDesignator.setter
    def ReferenceDesignator(self, value: str) -> None: ...
    @property
    def ReferenceDesignatorModification(self) -> bool: ...
    @ReferenceDesignatorModification.setter
    def ReferenceDesignatorModification(self, value: bool) -> None: ...


    class PlacementOwnerEnum(enum.Enum):
        Mcad= 0
        Ecad= 1
        Placed= 2
        Unplaced= 3
    

class CompareAndUpdateBuilder(Builder):
    def __init__(self) -> None: ...
    def Compare(self) -> None: ...
    def SetUpdateOption(self, resDef: str, status: bool) -> None: ...
    def PreviewChanges(self) -> None: ...
    def UnhighlightAll(self) -> None: ...
    @property
    def AssemblyUpdateOptions(self) -> PcbExchange.CompareAndUpdateBuilder.AssemblyUpdateEnum: ...
    @AssemblyUpdateOptions.setter
    def AssemblyUpdateOptions(self, value: PcbExchange.CompareAndUpdateBuilder.AssemblyUpdateEnum) -> None: ...
    @property
    def BoardFile(self) -> str: ...
    @BoardFile.setter
    def BoardFile(self, value: str) -> None: ...
    @property
    def BoardFolder(self) -> str: ...
    @BoardFolder.setter
    def BoardFolder(self, value: str) -> None: ...
    @property
    def BoardThickness(self) -> Expression: ...
    @BoardThickness.setter
    def BoardThickness(self, value: Expression) -> None: ...
    @property
    def BoardUpdateOptions(self) -> PcbExchange.CompareAndUpdateBuilder.BoardUpdateEnum: ...
    @BoardUpdateOptions.setter
    def BoardUpdateOptions(self, value: PcbExchange.CompareAndUpdateBuilder.BoardUpdateEnum) -> None: ...
    @property
    def CompareOptions(self) -> PcbExchange.CompareAndUpdateBuilder.CompareEnum: ...
    @CompareOptions.setter
    def CompareOptions(self, value: PcbExchange.CompareAndUpdateBuilder.CompareEnum) -> None: ...
    @property
    def ECADEntityFilter(self) -> PcbExchange.EntityFilter: ...
    @ECADEntityFilter.setter
    def ECADEntityFilter(self, value: PcbExchange.EntityFilter) -> None: ...
    @property
    def FilterEcadModel(self) -> bool: ...
    @FilterEcadModel.setter
    def FilterEcadModel(self, value: bool) -> None: ...
    @property
    def FilterNxModel(self) -> bool: ...
    @FilterNxModel.setter
    def FilterNxModel(self, value: bool) -> None: ...
    @property
    def FromOdbFolder(self) -> bool: ...
    @FromOdbFolder.setter
    def FromOdbFolder(self, value: bool) -> None: ...
    @property
    def LibraryFile(self) -> str: ...
    @LibraryFile.setter
    def LibraryFile(self, value: str) -> None: ...
    @property
    def NXEntityFilter(self) -> PcbExchange.EntityFilter: ...
    @NXEntityFilter.setter
    def NXEntityFilter(self, value: PcbExchange.EntityFilter) -> None: ...
    @property
    def OnlyUseExistingComponents(self) -> bool: ...
    @OnlyUseExistingComponents.setter
    def OnlyUseExistingComponents(self, value: bool) -> None: ...
    @property
    def OverrideBoardThickness(self) -> bool: ...
    @OverrideBoardThickness.setter
    def OverrideBoardThickness(self, value: bool) -> None: ...
    @property
    def ShowLog(self) -> bool: ...
    @ShowLog.setter
    def ShowLog(self, value: bool) -> None: ...


    class CompareEnum(enum.Enum):
        All= 0
        BoardOnly= 1
    

    class BoardUpdateEnum(enum.Enum):
        All= 0
        None_= 1
    

    class AssemblyUpdateEnum(enum.Enum):
        All= 0
        None_= 1
        Specify= 2
    

class BoardSide(enum.Enum):
    Both= 0
    Top= 1
    Bottom= 2


class BoardPropertiesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AdvancedOptionsFromFile(self) -> bool: ...
    @AdvancedOptionsFromFile.setter
    def AdvancedOptionsFromFile(self, value: bool) -> None: ...
    @property
    def AdvancedOptionsFromPart(self) -> bool: ...
    @AdvancedOptionsFromPart.setter
    def AdvancedOptionsFromPart(self, value: bool) -> None: ...
    @property
    def BoardPropertyFile(self) -> str: ...
    @BoardPropertyFile.setter
    def BoardPropertyFile(self, value: str) -> None: ...
    @property
    def BoardStackup(self) -> PcbExchange.BoardPropertiesBuilder.BoardStackupOption: ...
    @BoardStackup.setter
    def BoardStackup(self, value: PcbExchange.BoardPropertiesBuilder.BoardStackupOption) -> None: ...
    @property
    def BoardStackupFile(self) -> str: ...
    @BoardStackupFile.setter
    def BoardStackupFile(self, value: str) -> None: ...
    @property
    def BoardStackupODBFolder(self) -> str: ...
    @BoardStackupODBFolder.setter
    def BoardStackupODBFolder(self, value: str) -> None: ...
    @property
    def CalculationPointsPrecision(self) -> int: ...
    @CalculationPointsPrecision.setter
    def CalculationPointsPrecision(self, value: int) -> None: ...
    @property
    def DefaultHolePlatingThickness(self) -> Expression: ...
    @DefaultHolePlatingThickness.setter
    def DefaultHolePlatingThickness(self, value: Expression) -> None: ...
    @property
    def DielectricNxMaterial(self) -> int: ...
    @DielectricNxMaterial.setter
    def DielectricNxMaterial(self, value: int) -> None: ...
    @property
    def DielectricPcbMaterial(self) -> int: ...
    @DielectricPcbMaterial.setter
    def DielectricPcbMaterial(self, value: int) -> None: ...
    @property
    def MaterialsFrom(self) -> PcbExchange.BoardPropertiesBuilder.MaterialsFromOption: ...
    @MaterialsFrom.setter
    def MaterialsFrom(self, value: PcbExchange.BoardPropertiesBuilder.MaterialsFromOption) -> None: ...
    @property
    def NumberOfCalculationPoints(self) -> int: ...
    @NumberOfCalculationPoints.setter
    def NumberOfCalculationPoints(self, value: int) -> None: ...
    @property
    def ReadViasFromFile(self) -> bool: ...
    @ReadViasFromFile.setter
    def ReadViasFromFile(self, value: bool) -> None: ...
    @property
    def StructuralAlgorithm(self) -> PcbExchange.BoardPropertiesBuilder.StructuralAlgorithmOption: ...
    @StructuralAlgorithm.setter
    def StructuralAlgorithm(self, value: PcbExchange.BoardPropertiesBuilder.StructuralAlgorithmOption) -> None: ...
    @property
    def ThermalAlgorithm(self) -> PcbExchange.BoardPropertiesBuilder.ThermalAlgorithmOption: ...
    @ThermalAlgorithm.setter
    def ThermalAlgorithm(self, value: PcbExchange.BoardPropertiesBuilder.ThermalAlgorithmOption) -> None: ...
    @property
    def TraceNxMaterial(self) -> int: ...
    @TraceNxMaterial.setter
    def TraceNxMaterial(self, value: int) -> None: ...
    @property
    def TracePcbMaterial(self) -> int: ...
    @TracePcbMaterial.setter
    def TracePcbMaterial(self, value: int) -> None: ...
    @property
    def ViaNxMaterial(self) -> int: ...
    @ViaNxMaterial.setter
    def ViaNxMaterial(self, value: int) -> None: ...
    @property
    def ViaPcbMaterial(self) -> int: ...
    @ViaPcbMaterial.setter
    def ViaPcbMaterial(self, value: int) -> None: ...
    @property
    def ViewCalculationReport(self) -> bool: ...
    @ViewCalculationReport.setter
    def ViewCalculationReport(self, value: bool) -> None: ...


    class ThermalAlgorithmOption(enum.Enum):
        Discretized= 0
        Equivalent= 1
    

    class StructuralAlgorithmOption(enum.Enum):
        Equivalent= 0
    

    class MaterialsFromOption(enum.Enum):
        PCBMaterialLibrary= 0
        NXMaterialLibrary= 1
    

    class BoardStackupOption(enum.Enum):
        FromPart= 0
        FromFile= 1
        FromODB= 2
    

class BoardAttributesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def BoardFeature(self) -> SelectBody: ...
    @BoardFeature.setter
    def BoardFeature(self, value: SelectBody) -> None: ...
    @property
    def CsysSelection(self) -> Features.SelectDatumCsys: ...
    @CsysSelection.setter
    def CsysSelection(self, value: Features.SelectDatumCsys) -> None: ...
    @property
    def Owner(self) -> PcbExchange.BoardAttributesBuilder.OwnerEnum: ...
    @Owner.setter
    def Owner(self, value: PcbExchange.BoardAttributesBuilder.OwnerEnum) -> None: ...
    @property
    def Part(self) -> str: ...
    @Part.setter
    def Part(self, value: str) -> None: ...
    @property
    def Revision(self) -> int: ...
    @Revision.setter
    def Revision(self, value: int) -> None: ...


    class OwnerEnum(enum.Enum):
        Unowned= 0
        Mcad= 1
        Ecad= 2
    

class AttributeRemover(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetAttributeRemover(self, owner: Session) -> PcbExchange.AttributeRemover: ...
    def RemoveAttributes(self, action: PcbExchange.AttributeRemover.Option, objTags: typing.List[TaggedObject]) -> None: ...
    def Tag(self) -> Tag: ...



    class Option(enum.Enum):
        Board= 0
        Components= 1
        Areas= 2
        Holes= 3
        Traces= 4
        Pads= 5
        All= 6
    

class AreaMappingBuilder(Builder):
    def __init__(self) -> None: ...
    def SetKeepinAreas(self, keepinAreaList: str) -> None: ...
    def SetKeepoutAreas(self, keepoutAreaList: str) -> None: ...
    def SetOtherAreas(self, otherAreaList: str) -> None: ...
    def SetCopperAreas(self, copperAreaList: str) -> None: ...
    def PrintMapping(self) -> None: ...


class AreaMapping(NXObject):
    def __init__(self) -> None: ...


class AreaAttributesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AreaType(self) -> PcbExchange.AreaAttributesBuilder.TypeEnum: ...
    @AreaType.setter
    def AreaType(self, value: PcbExchange.AreaAttributesBuilder.TypeEnum) -> None: ...
    @property
    def Color(self) -> int: ...
    @Color.setter
    def Color(self, value: int) -> None: ...
    @property
    def Height(self) -> Expression: ...
    @Height.setter
    def Height(self, value: Expression) -> None: ...
    @property
    def InvertedVolume(self) -> bool: ...
    @InvertedVolume.setter
    def InvertedVolume(self, value: bool) -> None: ...
    @property
    def Layer(self) -> PcbExchange.AreaAttributesBuilder.LayerEnum: ...
    @Layer.setter
    def Layer(self, value: PcbExchange.AreaAttributesBuilder.LayerEnum) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Objects(self) -> SelectNXObjectList: ...
    @Objects.setter
    def Objects(self, value: SelectNXObjectList) -> None: ...
    @property
    def Owner(self) -> PcbExchange.AreaAttributesBuilder.OwnerEnum: ...
    @Owner.setter
    def Owner(self, value: PcbExchange.AreaAttributesBuilder.OwnerEnum) -> None: ...
    @property
    def Subtype(self) -> str: ...
    @Subtype.setter
    def Subtype(self, value: str) -> None: ...


    class TypeEnum(enum.Enum):
        Keepout= 0
        Keepin= 1
        Other= 2
        Copper= 3
    

    class OwnerEnum(enum.Enum):
        Unowned= 0
        Mcad= 1
        Ecad= 2
    

    class LayerEnum(enum.Enum):
        Current= 0
        Both= 1
        Inner= 2
        All= 3
    

class AdvancedConductivityBuilder(Builder):
    def __init__(self) -> None: ...
    def GetTextualFilter(self) -> bool: ...
    def SetTextualFilter(self, filter: bool) -> None: ...
    def GetNetsToFilterString(self) -> str: ...
    def SetNetsToFilterString(self, nets: str) -> None: ...
    def GetNetsList(self, nets: str) -> None: ...
    def SetNetsList(self, nets: str) -> None: ...
    def GetPadstacks(self, padstacks: str) -> None: ...
    def SetPadstacks(self, nets: str) -> None: ...
    def GetTypes(self, types: int) -> None: ...
    def SetTypes(self, types: int) -> None: ...
    def GetDiameters(self, diameters: float) -> None: ...
    def SetDiameters(self, diameters: float) -> None: ...
    def GetStartLayers(self, startLayers: int) -> None: ...
    def SetStartLayers(self, startLayers: int) -> None: ...
    def GetEndLayers(self, endLayers: int) -> None: ...
    def SetEndLayers(self, endLayers: int) -> None: ...
    def GetT(self, t: int) -> None: ...
    def SetT(self, t: int) -> None: ...
    def GetHolesCounts(self, holesCounts: int) -> None: ...
    def SetHolesCounts(self, holesCounts: int) -> None: ...
    def GetPlatingThicknesses(self, platingThicknesses: float) -> None: ...
    def SetPlatingThicknesses(self, platingThicknesses: float) -> None: ...
    def GetPlatingMaterials(self, platingMaterials: int) -> None: ...
    def SetPlatingMaterials(self, platingMaterials: int) -> None: ...
    def GetFilled(self, bFilleds: bool) -> None: ...
    def SetFilled(self, bFilleds: int) -> None: ...
    def GetFillMaterials(self, fillMaterials: int) -> None: ...
    def SetFillMaterials(self, fillMaterials: int) -> None: ...


