from ...NXOpen import *

import typing
import enum

class SpecifyRuleBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Note(self) -> Annotations.Note: ...
    @Note.setter
    def Note(self, value: Annotations.Note) -> None: ...
    @property
    def Rule(self) -> str: ...
    @Rule.setter
    def Rule(self, value: str) -> None: ...


class SmashDrawingViewBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def SelectView(self) -> Drawings.SelectDraftingView: ...
    @SelectView.setter
    def SelectView(self, value: Drawings.SelectDraftingView) -> None: ...


class SettingsManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Part) -> None: ...
    def CreatePreferencesBuilder(self) -> Drafting.PreferencesBuilder: ...
    def CreateAnnotationEditSettingsBuilder(self, objects: typing.List[DisplayableObject]) -> Annotations.EditSettingsBuilder: ...
    def CreateDrawingEditSectionLineSettingsBuilder(self, sectionLines: typing.List[Drawings.SectionLine]) -> Drawings.EditSectionLineSettingsBuilder: ...
    def CreateDrawingEditViewSettingsBuilder(self, views: typing.List[View]) -> Drawings.EditViewSettingsBuilder: ...
    def CreateLayout2dEditComponentSettingsBuilder(self, components: typing.List[Layout2d.Component]) -> Layout2d.EditComponentSettingsBuilder: ...
    def CreateDrawingEditViewLabelSettingsBuilder(self, viewLabels: typing.List[DisplayableObject]) -> Drawings.EditViewLabelSettingsBuilder: ...
    def CreateTableEditSettingsBuilder(self, objects: typing.List[DisplayableObject]) -> Annotations.TableEditSettingsBuilder: ...
    def ProcessForMutipleObjectsSettings(self, editSettingsBuilders: typing.List[Drafting.BaseEditSettingsBuilder]) -> None: ...
    def ProcessForMultipleObjectsSettings(self, editSettingsBuilders: typing.List[Drafting.BaseEditSettingsBuilder]) -> None: ...
    @typing.overload
    def CreateTableRowSortingBuilder(self, objects: typing.List[DisplayableObject]) -> Annotations.TableRowSortingBuilder: ...
    @typing.overload
    def CreateTableRowSortingBuilder(self, tableObject: Annotations.Table) -> Annotations.TableRowSortingBuilder: ...
    def Tag(self) -> Tag: ...



class RulesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def DimensionRule(self) -> str: ...
    @DimensionRule.setter
    def DimensionRule(self, value: str) -> None: ...
    @property
    def NoteRule(self) -> str: ...
    @NoteRule.setter
    def NoteRule(self, value: str) -> None: ...
    @property
    def SymbolRule(self) -> str: ...
    @SymbolRule.setter
    def SymbolRule(self, value: str) -> None: ...


class PrimaryContentItemBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[Drafting.PrimaryContentItemBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: Drafting.PrimaryContentItemBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: Drafting.PrimaryContentItemBuilder) -> int: ...
    def FindItem(self, index: int) -> Drafting.PrimaryContentItemBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: Drafting.PrimaryContentItemBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: Drafting.PrimaryContentItemBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[Drafting.PrimaryContentItemBuilder]: ...
    def SetContents(self, objects: typing.List[Drafting.PrimaryContentItemBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: Drafting.PrimaryContentItemBuilder, object2: Drafting.PrimaryContentItemBuilder) -> None: ...
    def Insert(self, location: int, object: Drafting.PrimaryContentItemBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class PrimaryContentItemBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def Content(self) -> Assemblies.SelectComponentList: ...
    @Content.setter
    def Content(self, value: Assemblies.SelectComponentList) -> None: ...
    @property
    def GeometryTemplate(self) -> str: ...
    @GeometryTemplate.setter
    def GeometryTemplate(self, value: str) -> None: ...


class PreferencesBuilder(Builder):
    def __init__(self) -> None: ...
    def InheritSettingsFromSelectedObjects(self, selectedObject: NXObject) -> None: ...
    def InheritSettingsFromCustomerDefault(self) -> None: ...
    def InheritSettingsFromPreferences(self) -> None: ...
    @property
    def AnnotationOriginAlignment(self) -> Annotations.OriginAlignmentBuilder: ...
    @AnnotationOriginAlignment.setter
    def AnnotationOriginAlignment(self, value: Annotations.OriginAlignmentBuilder) -> None: ...
    @property
    def AnnotationStyle(self) -> Annotations.StyleBuilder: ...
    @AnnotationStyle.setter
    def AnnotationStyle(self, value: Annotations.StyleBuilder) -> None: ...
    @property
    def AssemblyCreationSettingsBuilder(self) -> Layout2d.AssemblyCreationSettingsBuilder: ...
    @AssemblyCreationSettingsBuilder.setter
    def AssemblyCreationSettingsBuilder(self, value: Layout2d.AssemblyCreationSettingsBuilder) -> None: ...
    @property
    def AutomationBooklet(self) -> Drawings.AutomationBookletBuilder: ...
    @AutomationBooklet.setter
    def AutomationBooklet(self, value: Drawings.AutomationBookletBuilder) -> None: ...
    @property
    def AutomationRule(self) -> Drafting.AutomationRuleBuilder: ...
    @AutomationRule.setter
    def AutomationRule(self, value: Drafting.AutomationRuleBuilder) -> None: ...
    @property
    def AutomationTemplateRegion(self) -> Drawings.AutomationTemplateRegionBuilder: ...
    @AutomationTemplateRegion.setter
    def AutomationTemplateRegion(self, value: Drawings.AutomationTemplateRegionBuilder) -> None: ...
    @property
    def BendTable(self) -> Annotations.BendTableSettingsBuilder: ...
    @BendTable.setter
    def BendTable(self, value: Annotations.BendTableSettingsBuilder) -> None: ...
    @property
    def BorderAndZoneStyle(self) -> Drawings.BorderAndZoneStyleBuilder: ...
    @BorderAndZoneStyle.setter
    def BorderAndZoneStyle(self, value: Drawings.BorderAndZoneStyleBuilder) -> None: ...
    @property
    def CommonWorkflow(self) -> Annotations.CommonWorkflowBuilder: ...
    @CommonWorkflow.setter
    def CommonWorkflow(self, value: Annotations.CommonWorkflowBuilder) -> None: ...
    @property
    def Component2dSettings(self) -> Layout2d.ComponentSettingsBlockBuilder: ...
    @Component2dSettings.setter
    def Component2dSettings(self, value: Layout2d.ComponentSettingsBlockBuilder) -> None: ...
    @property
    def CreateComponentFrom3DSettingsBuilder(self) -> Layout2d.CreateComponentFrom3DSettingsBuilder: ...
    @CreateComponentFrom3DSettingsBuilder.setter
    def CreateComponentFrom3DSettingsBuilder(self, value: Layout2d.CreateComponentFrom3DSettingsBuilder) -> None: ...
    @property
    def DimensionOriginAlignment(self) -> Annotations.OriginAlignmentBuilder: ...
    @DimensionOriginAlignment.setter
    def DimensionOriginAlignment(self, value: Annotations.OriginAlignmentBuilder) -> None: ...
    @property
    def DimensionWorkflow(self) -> Annotations.DimensionWorkflowBuilder: ...
    @DimensionWorkflow.setter
    def DimensionWorkflow(self, value: Annotations.DimensionWorkflowBuilder) -> None: ...
    @property
    def DrawingFormatTitle(self) -> Annotations.DrawingFormatTitleBuilder: ...
    @DrawingFormatTitle.setter
    def DrawingFormatTitle(self, value: Annotations.DrawingFormatTitleBuilder) -> None: ...
    @property
    def DrawingFormatsheet(self) -> Drawings.DrawingFormatSheetBuilder: ...
    @DrawingFormatsheet.setter
    def DrawingFormatsheet(self, value: Drawings.DrawingFormatSheetBuilder) -> None: ...
    @property
    def FramebarGeneral(self) -> Annotations.ShipDraftingFramebarGeneralBuilder: ...
    @FramebarGeneral.setter
    def FramebarGeneral(self, value: Annotations.ShipDraftingFramebarGeneralBuilder) -> None: ...
    @property
    def GeneralLayoutPreferencesBuilder(self) -> Layout2d.GeneralPreferencesBuilder: ...
    @GeneralLayoutPreferencesBuilder.setter
    def GeneralLayoutPreferencesBuilder(self, value: Layout2d.GeneralPreferencesBuilder) -> None: ...
    @property
    def HoleTableContent(self) -> Annotations.HoleTableSettingsContentBuilder: ...
    @HoleTableContent.setter
    def HoleTableContent(self, value: Annotations.HoleTableSettingsContentBuilder) -> None: ...
    @property
    def HoleTableFormat(self) -> Annotations.HoleTableSettingsFormatBuilder: ...
    @HoleTableFormat.setter
    def HoleTableFormat(self, value: Annotations.HoleTableSettingsFormatBuilder) -> None: ...
    @property
    def HoleTableHoleFilters(self) -> Annotations.HoleTableSettingsHoleFiltersBuilder: ...
    @HoleTableHoleFilters.setter
    def HoleTableHoleFilters(self, value: Annotations.HoleTableSettingsHoleFiltersBuilder) -> None: ...
    @property
    def HoleTableLabel(self) -> Annotations.HoleTableSettingsLabelBuilder: ...
    @HoleTableLabel.setter
    def HoleTableLabel(self, value: Annotations.HoleTableSettingsLabelBuilder) -> None: ...
    @property
    def HoleTableWorkflow(self) -> Annotations.HoleTableSettingsWorkflowBuilder: ...
    @HoleTableWorkflow.setter
    def HoleTableWorkflow(self, value: Annotations.HoleTableSettingsWorkflowBuilder) -> None: ...
    @property
    def PartFamilyTable(self) -> Annotations.PartFamilyTableSettingsBuilder: ...
    @PartFamilyTable.setter
    def PartFamilyTable(self, value: Annotations.PartFamilyTableSettingsBuilder) -> None: ...
    @property
    def PartsList(self) -> Annotations.PartsListBuilder: ...
    @PartsList.setter
    def PartsList(self, value: Annotations.PartsListBuilder) -> None: ...
    @property
    def RetainedAnnotations(self) -> Annotations.RetainedAnnotationsBuilder: ...
    @RetainedAnnotations.setter
    def RetainedAnnotations(self, value: Annotations.RetainedAnnotationsBuilder) -> None: ...
    @property
    def SymbolWorkflow(self) -> Annotations.SymbolWorkflowBuilder: ...
    @SymbolWorkflow.setter
    def SymbolWorkflow(self, value: Annotations.SymbolWorkflowBuilder) -> None: ...
    @property
    def TableCellStyle(self) -> Annotations.TableCellStyleBuilder: ...
    @TableCellStyle.setter
    def TableCellStyle(self, value: Annotations.TableCellStyleBuilder) -> None: ...
    @property
    def TableOriginAlignment(self) -> Annotations.OriginAlignmentBuilder: ...
    @TableOriginAlignment.setter
    def TableOriginAlignment(self, value: Annotations.OriginAlignmentBuilder) -> None: ...
    @property
    def TableSection(self) -> Annotations.TableSectionStyleBuilder: ...
    @TableSection.setter
    def TableSection(self, value: Annotations.TableSectionStyleBuilder) -> None: ...
    @property
    def TabularNoteStyle(self) -> Annotations.TabularNoteStyleBuilder: ...
    @TabularNoteStyle.setter
    def TabularNoteStyle(self, value: Annotations.TabularNoteStyleBuilder) -> None: ...
    @property
    def TrackDrawingChangesGeneral(self) -> Drawings.TrackDrawingChangesGeneralBuilder: ...
    @TrackDrawingChangesGeneral.setter
    def TrackDrawingChangesGeneral(self, value: Drawings.TrackDrawingChangesGeneralBuilder) -> None: ...
    @property
    def TrackDrawingChangesReportFilter(self) -> Drawings.TrackDrawingChangesReportFilterBuilder: ...
    @TrackDrawingChangesReportFilter.setter
    def TrackDrawingChangesReportFilter(self, value: Drawings.TrackDrawingChangesReportFilterBuilder) -> None: ...
    @property
    def ViewBreak(self) -> Drawings.ViewBreakBuilder: ...
    @ViewBreak.setter
    def ViewBreak(self, value: Drawings.ViewBreakBuilder) -> None: ...
    @property
    def ViewDetailLabel(self) -> Drawings.ViewDetailLabelBuilder: ...
    @ViewDetailLabel.setter
    def ViewDetailLabel(self, value: Drawings.ViewDetailLabelBuilder) -> None: ...
    @property
    def ViewLabel(self) -> Drawings.ViewLabelBuilder: ...
    @ViewLabel.setter
    def ViewLabel(self, value: Drawings.ViewLabelBuilder) -> None: ...
    @property
    def ViewProjectedLabel(self) -> Drawings.ViewProjectedLabelBuilder: ...
    @ViewProjectedLabel.setter
    def ViewProjectedLabel(self, value: Drawings.ViewProjectedLabelBuilder) -> None: ...
    @property
    def ViewSectionLabel(self) -> Drawings.ViewSectionLabelBuilder: ...
    @ViewSectionLabel.setter
    def ViewSectionLabel(self, value: Drawings.ViewSectionLabelBuilder) -> None: ...
    @property
    def ViewSectionLine(self) -> Drawings.ViewSectionLineBuilder: ...
    @ViewSectionLine.setter
    def ViewSectionLine(self, value: Drawings.ViewSectionLineBuilder) -> None: ...
    @property
    def ViewStyle(self) -> Drawings.ViewStyleBuilder: ...
    @ViewStyle.setter
    def ViewStyle(self, value: Drawings.ViewStyleBuilder) -> None: ...
    @property
    def ViewWorkflow(self) -> Drawings.ViewWorkflowBuilder: ...
    @ViewWorkflow.setter
    def ViewWorkflow(self, value: Drawings.ViewWorkflowBuilder) -> None: ...
    @property
    def VisualDrawingCompare(self) -> Drawings.VisualDrawingComparePrefsBuilder: ...
    @VisualDrawingCompare.setter
    def VisualDrawingCompare(self, value: Drawings.VisualDrawingComparePrefsBuilder) -> None: ...
    @property
    def Workflow(self) -> Drawings.GeneralWorkFlowBuilder: ...
    @Workflow.setter
    def Workflow(self, value: Drawings.GeneralWorkFlowBuilder) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MoveToDrawingViewBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def SelectObjects(self) -> SelectTaggedObjectList: ...
    @SelectObjects.setter
    def SelectObjects(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def SelectPoint(self) -> Point: ...
    @SelectPoint.setter
    def SelectPoint(self, value: Point) -> None: ...
    @property
    def TwoDOrientation(self) -> Drawings.View2dOrientBuilder: ...
    @TwoDOrientation.setter
    def TwoDOrientation(self, value: Drawings.View2dOrientBuilder) -> None: ...
    @property
    def ViewScale(self) -> Drawings.ViewScaleBuilder: ...
    @ViewScale.setter
    def ViewScale(self, value: Drawings.ViewScaleBuilder) -> None: ...
    @property
    def ViewStyle(self) -> Drawings.ViewStyleBuilder: ...
    @ViewStyle.setter
    def ViewStyle(self, value: Drawings.ViewStyleBuilder) -> None: ...
    @property
    def XCoordinate(self) -> float: ...
    @XCoordinate.setter
    def XCoordinate(self, value: float) -> None: ...
    @property
    def YCoordinate(self) -> float: ...
    @YCoordinate.setter
    def YCoordinate(self, value: float) -> None: ...


class DrawingCreationWizardBuilder(Builder):
    def __init__(self) -> None: ...
    def GetSummary(self) -> str: ...
    def SetSummary(self, summary: str) -> None: ...
    def SetObjectCreateBuilder(self, objectCreateBuilder: PDM.ObjectCreateBuilder) -> None: ...
    @property
    def ApplyTemplateToAll(self) -> bool: ...
    @ApplyTemplateToAll.setter
    def ApplyTemplateToAll(self, value: bool) -> None: ...
    @property
    def Attributes(self) -> Drafting.AttributeItemBuilderList: ...
    @Attributes.setter
    def Attributes(self, value: Drafting.AttributeItemBuilderList) -> None: ...
    @property
    def DetailID(self) -> str: ...
    @DetailID.setter
    def DetailID(self, value: str) -> None: ...
    @property
    def Discipline(self) -> str: ...
    @Discipline.setter
    def Discipline(self, value: str) -> None: ...
    @property
    def DrawingStyle(self) -> str: ...
    @DrawingStyle.setter
    def DrawingStyle(self, value: str) -> None: ...
    @property
    def ExcludedContent(self) -> Assemblies.SelectComponentList: ...
    @ExcludedContent.setter
    def ExcludedContent(self, value: Assemblies.SelectComponentList) -> None: ...
    @property
    def Folder(self) -> str: ...
    @Folder.setter
    def Folder(self, value: str) -> None: ...
    @property
    def IntroductoryTemplate(self) -> str: ...
    @IntroductoryTemplate.setter
    def IntroductoryTemplate(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Number(self) -> str: ...
    @Number.setter
    def Number(self, value: str) -> None: ...
    @property
    def PrimaryContent(self) -> Drafting.PrimaryContentItemBuilderList: ...
    @PrimaryContent.setter
    def PrimaryContent(self, value: Drafting.PrimaryContentItemBuilderList) -> None: ...
    @property
    def References(self) -> SelectNXObjectList: ...
    @References.setter
    def References(self, value: SelectNXObjectList) -> None: ...
    @property
    def Revision(self) -> str: ...
    @Revision.setter
    def Revision(self, value: str) -> None: ...
    @property
    def SecondaryContent(self) -> Assemblies.SelectComponentList: ...
    @SecondaryContent.setter
    def SecondaryContent(self, value: Assemblies.SelectComponentList) -> None: ...


class DrawingAutomationWizard(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def Builder(self) -> Drafting.DrawingCreationWizardBuilder: ...
    @Builder.setter
    def Builder(self, value: Drafting.DrawingCreationWizardBuilder) -> None: ...
    @property
    def ContinueProcessing(self) -> bool: ...
    @ContinueProcessing.setter
    def ContinueProcessing(self, value: bool) -> None: ...
    @property
    def ErrorCode(self) -> int: ...
    @ErrorCode.setter
    def ErrorCode(self, value: int) -> None: ...
    @property
    def Part(self) -> Part: ...
    @Part.setter
    def Part(self, value: Part) -> None: ...


class DraftingApplicationManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Part) -> None: ...
    def CreateCutCopyPasteBuilder(self) -> Drafting.CutCopyPasteBuilder: ...
    def CreateMoveToDrawingViewBuilder(self) -> Drafting.MoveToDrawingViewBuilder: ...
    def CreateSmashDrawingViewBuilder(self) -> Drafting.SmashDrawingViewBuilder: ...
    def Tag(self) -> Tag: ...

    @property
    def TitleBlocks(self) -> Annotations.TitleBlockCollection: ...
    @TitleBlocks.setter
    def TitleBlocks(self, value: Annotations.TitleBlockCollection) -> None: ...


class DistributeAnnotationsBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Views(self) -> Drawings.SelectDraftingViewList: ...
    @Views.setter
    def Views(self, value: Drawings.SelectDraftingViewList) -> None: ...


class CutCopyPasteLeaderBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def SetMoveOnCommit(self, rot: Matrix3x3, trans: Vector3d) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def DestinationView(self) -> View: ...
    @DestinationView.setter
    def DestinationView(self, value: View) -> None: ...
    @property
    def IsLeaderSelection(self) -> bool: ...
    @IsLeaderSelection.setter
    def IsLeaderSelection(self, value: bool) -> None: ...
    @property
    def LeaderSelection(self) -> SelectTaggedObject: ...
    @LeaderSelection.setter
    def LeaderSelection(self, value: SelectTaggedObject) -> None: ...
    @property
    def ReassociateLeader(self) -> bool: ...
    @ReassociateLeader.setter
    def ReassociateLeader(self, value: bool) -> None: ...
    @property
    def Selection(self) -> SelectTaggedObject: ...
    @Selection.setter
    def Selection(self, value: SelectTaggedObject) -> None: ...


class CutCopyPasteBuilder(Builder):
    def __init__(self) -> None: ...
    def GetDefaultToPoint(self) -> Point3d: ...
    def SetDefaultToPoint(self, dropLocation: Point3d) -> None: ...
    def SetMoveOnCommit(self, rot: Matrix3x3, trans: Vector3d) -> None: ...
    def InitPaste(self) -> None: ...
    @property
    def CutCopyPasteLeader(self) -> Drafting.CutCopyPasteLeaderBuilder: ...
    @CutCopyPasteLeader.setter
    def CutCopyPasteLeader(self, value: Drafting.CutCopyPasteLeaderBuilder) -> None: ...
    @property
    def DestinationView(self) -> View: ...
    @DestinationView.setter
    def DestinationView(self, value: View) -> None: ...
    @property
    def ObjectsToCopy(self) -> SelectTaggedObjectList: ...
    @ObjectsToCopy.setter
    def ObjectsToCopy(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def Originals(self) -> Drafting.CutCopyPasteBuilder.TypeOperation: ...
    @Originals.setter
    def Originals(self, value: Drafting.CutCopyPasteBuilder.TypeOperation) -> None: ...
    @property
    def OutputObjects(self) -> SelectTaggedObjectList: ...
    @OutputObjects.setter
    def OutputObjects(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def PasteType(self) -> Drafting.CutCopyPasteBuilder.TypePaste: ...
    @PasteType.setter
    def PasteType(self, value: Drafting.CutCopyPasteBuilder.TypePaste) -> None: ...
    @property
    def PlaneToRestrictMotion(self) -> Plane: ...
    @PlaneToRestrictMotion.setter
    def PlaneToRestrictMotion(self, value: Plane) -> None: ...
    @property
    def Transform(self) -> GeometricUtilities.ModlMotion: ...
    @Transform.setter
    def Transform(self, value: GeometricUtilities.ModlMotion) -> None: ...


    class TypePaste(enum.Enum):
        Transform= 0
        Tracking= 1
    

    class TypeOperation(enum.Enum):
        Copy= 0
        Cut= 1
    

class BaseEditSettingsBuilder(Builder):
    def __init__(self) -> None: ...


class AutomationRuleBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def GetRulesList(self) -> str: ...
    def SetRulesList(self, rules: str) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def AllowInsideGeometry(self) -> bool: ...
    @AllowInsideGeometry.setter
    def AllowInsideGeometry(self, value: bool) -> None: ...
    @property
    def EqualDimensionTolerance(self) -> float: ...
    @EqualDimensionTolerance.setter
    def EqualDimensionTolerance(self, value: float) -> None: ...
    @property
    def HideFeetAndInchMarks(self) -> bool: ...
    @HideFeetAndInchMarks.setter
    def HideFeetAndInchMarks(self, value: bool) -> None: ...
    @property
    def Increment(self) -> float: ...
    @Increment.setter
    def Increment(self, value: float) -> None: ...
    @property
    def LowerThreshold(self) -> float: ...
    @LowerThreshold.setter
    def LowerThreshold(self, value: float) -> None: ...
    @property
    def MaximumGapToGeometry(self) -> float: ...
    @MaximumGapToGeometry.setter
    def MaximumGapToGeometry(self, value: float) -> None: ...
    @property
    def MinimumGapBetweenAnnotations(self) -> float: ...
    @MinimumGapBetweenAnnotations.setter
    def MinimumGapBetweenAnnotations(self, value: float) -> None: ...
    @property
    def MinimumGapToGeometry(self) -> float: ...
    @MinimumGapToGeometry.setter
    def MinimumGapToGeometry(self, value: float) -> None: ...
    @property
    def ReferenceGeometryGapTolerance(self) -> float: ...
    @ReferenceGeometryGapTolerance.setter
    def ReferenceGeometryGapTolerance(self, value: float) -> None: ...
    @property
    def RoundFeetAndInches(self) -> bool: ...
    @RoundFeetAndInches.setter
    def RoundFeetAndInches(self, value: bool) -> None: ...
    @property
    def UseFeetInchesAndFraction(self) -> bool: ...
    @UseFeetInchesAndFraction.setter
    def UseFeetInchesAndFraction(self, value: bool) -> None: ...


class AutomationPreferencesBuilder(Builder):
    def __init__(self) -> None: ...
    def GetRulesList(self) -> str: ...
    def SetRulesList(self, rules: str) -> None: ...
    @property
    def AllowFeetInchFractionForDimensionGreaterThan(self) -> bool: ...
    @AllowFeetInchFractionForDimensionGreaterThan.setter
    def AllowFeetInchFractionForDimensionGreaterThan(self, value: bool) -> None: ...
    @property
    def AllowInchFractionToNearest(self) -> bool: ...
    @AllowInchFractionToNearest.setter
    def AllowInchFractionToNearest(self, value: bool) -> None: ...
    @property
    def AnnotationInsideGeometry(self) -> bool: ...
    @AnnotationInsideGeometry.setter
    def AnnotationInsideGeometry(self, value: bool) -> None: ...
    @property
    def DisplayRegion(self) -> bool: ...
    @DisplayRegion.setter
    def DisplayRegion(self, value: bool) -> None: ...
    @property
    def DisplayRegionLabel(self) -> bool: ...
    @DisplayRegionLabel.setter
    def DisplayRegionLabel(self, value: bool) -> None: ...
    @property
    def DistanceBetweenAnnotations(self) -> float: ...
    @DistanceBetweenAnnotations.setter
    def DistanceBetweenAnnotations(self, value: float) -> None: ...
    @property
    def EqualDimensionCompareTolerance(self) -> float: ...
    @EqualDimensionCompareTolerance.setter
    def EqualDimensionCompareTolerance(self, value: float) -> None: ...
    @property
    def FeetInchFractionForDimensionGreaterThan(self) -> float: ...
    @FeetInchFractionForDimensionGreaterThan.setter
    def FeetInchFractionForDimensionGreaterThan(self, value: float) -> None: ...
    @property
    def HideFeetInchMark(self) -> bool: ...
    @HideFeetInchMark.setter
    def HideFeetInchMark(self, value: bool) -> None: ...
    @property
    def InchFractionToNearest(self) -> float: ...
    @InchFractionToNearest.setter
    def InchFractionToNearest(self, value: float) -> None: ...
    @property
    def MaximumDistanceToGeometry(self) -> float: ...
    @MaximumDistanceToGeometry.setter
    def MaximumDistanceToGeometry(self, value: float) -> None: ...
    @property
    def MinimumDistanceToGeometry(self) -> float: ...
    @MinimumDistanceToGeometry.setter
    def MinimumDistanceToGeometry(self, value: float) -> None: ...
    @property
    def ReferenceGeometrySearchDistance(self) -> float: ...
    @ReferenceGeometrySearchDistance.setter
    def ReferenceGeometrySearchDistance(self, value: float) -> None: ...
    @property
    def RegionColor(self) -> NXColor: ...
    @RegionColor.setter
    def RegionColor(self, value: NXColor) -> None: ...
    @property
    def RegionFont(self) -> Preferences.PartDrafting.FontType: ...
    @RegionFont.setter
    def RegionFont(self, value: Preferences.PartDrafting.FontType) -> None: ...
    @property
    def RegionWidth(self) -> Preferences.PartDrafting.WidthType: ...
    @RegionWidth.setter
    def RegionWidth(self, value: Preferences.PartDrafting.WidthType) -> None: ...
    @property
    def SecondaryContentHiddenLineColor(self) -> NXColor: ...
    @SecondaryContentHiddenLineColor.setter
    def SecondaryContentHiddenLineColor(self, value: NXColor) -> None: ...
    @property
    def SecondaryContentHiddenLineFont(self) -> Preferences.PartDrafting.FontType: ...
    @SecondaryContentHiddenLineFont.setter
    def SecondaryContentHiddenLineFont(self, value: Preferences.PartDrafting.FontType) -> None: ...
    @property
    def SecondaryContentHiddenLineWidth(self) -> Preferences.PartDrafting.WidthType: ...
    @SecondaryContentHiddenLineWidth.setter
    def SecondaryContentHiddenLineWidth(self, value: Preferences.PartDrafting.WidthType) -> None: ...
    @property
    def SecondaryContentVisibleLineColor(self) -> NXColor: ...
    @SecondaryContentVisibleLineColor.setter
    def SecondaryContentVisibleLineColor(self, value: NXColor) -> None: ...
    @property
    def SecondaryContentVisibleLineFont(self) -> Preferences.PartDrafting.FontType: ...
    @SecondaryContentVisibleLineFont.setter
    def SecondaryContentVisibleLineFont(self, value: Preferences.PartDrafting.FontType) -> None: ...
    @property
    def SecondaryContentVisibleLineWidth(self) -> Preferences.PartDrafting.WidthType: ...
    @SecondaryContentVisibleLineWidth.setter
    def SecondaryContentVisibleLineWidth(self, value: Preferences.PartDrafting.WidthType) -> None: ...


class AutomationManager(Utilities.NXRemotableObject):
    def __init__(self, owner: DraftingManager) -> None: ...
    def CreatePrimaryContentItemBuilder(self) -> Drafting.PrimaryContentItemBuilder: ...
    def CreateAttributeItemBuilder(self) -> Drafting.AttributeItemBuilder: ...
    def CreateDrawingCreationWizardBuilder(self, isEditing: bool) -> Drafting.DrawingCreationWizardBuilder: ...
    def CreateDrawingCreationWizardBuilderFromRule(self, className: str) -> Drafting.DrawingCreationWizardBuilder: ...
    def CreatePreferencesBuilder(self) -> Drafting.AutomationPreferencesBuilder: ...
    def CreateAnnotateViewsBuilder(self) -> Drafting.AnnotateViewsBuilder: ...
    def CreateRulesBuilder(self) -> Drafting.RulesBuilder: ...
    def CreateSpecifyRuleBuilder(self) -> Drafting.SpecifyRuleBuilder: ...
    def CreateDistributeAnnotationsBuilder(self) -> Drafting.DistributeAnnotationsBuilder: ...
    def GetRemainingPartsOfBooklet(self, remainingParts: typing.List[Part], remainingPartFileSpecs: str) -> None: ...
    def Tag(self) -> Tag: ...

    @property
    def DrawingRegions(self) -> Drawings.DrawingRegionCollection: ...
    @DrawingRegions.setter
    def DrawingRegions(self, value: Drawings.DrawingRegionCollection) -> None: ...


class AttributeItemBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[Drafting.AttributeItemBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: Drafting.AttributeItemBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: Drafting.AttributeItemBuilder) -> int: ...
    def FindItem(self, index: int) -> Drafting.AttributeItemBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: Drafting.AttributeItemBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: Drafting.AttributeItemBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[Drafting.AttributeItemBuilder]: ...
    def SetContents(self, objects: typing.List[Drafting.AttributeItemBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: Drafting.AttributeItemBuilder, object2: Drafting.AttributeItemBuilder) -> None: ...
    def Insert(self, location: int, object: Drafting.AttributeItemBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class AttributeItemBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> None: ...
    @property
    def Value(self) -> str: ...
    @Value.setter
    def Value(self, value: str) -> None: ...


class AnnotateViewsBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def ExistingAutomaticAnnotationOption(self) -> Drafting.AnnotateViewsBuilder.ExistingAutomaticAnnotation: ...
    @ExistingAutomaticAnnotationOption.setter
    def ExistingAutomaticAnnotationOption(self, value: Drafting.AnnotateViewsBuilder.ExistingAutomaticAnnotation) -> None: ...
    @property
    def Views(self) -> Drawings.SelectDraftingViewList: ...
    @Views.setter
    def Views(self, value: Drawings.SelectDraftingViewList) -> None: ...


    class ExistingAutomaticAnnotation(enum.Enum):
        Delete= 0
        Preserve= 1
    

