from ...NXOpen import *

import typing
import enum

class CheckerDataStatus(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetAvailableCheckerStatus(self) -> str: ...
    def Tag(self) -> Tag: ...



class CheckerData(Utilities.NXRemotableObject):
    def __init__(self, owner: BasePart) -> None: ...
    def GetCheckerData(self) -> str: ...
    def GetSummaryOfFeatures(self) -> str: ...
    def Tag(self) -> Tag: ...



class CadInfoManager(Utilities.NXRemotableObject):
    def __init__(self, owner: BasePart) -> None: ...
    def GetCreationDate(self) -> str: ...
    def GetCreatedBy(self) -> str: ...
    def GetLastModificationDate(self) -> str: ...
    def GetLastModifiedBy(self) -> str: ...
    def GetPartType(self) -> str: ...
    def GetCvfForPart(self, bGenerateCvfFiles: bool, psCvfStream: str, geometryCvfStream: str) -> None: ...
    def GetPersistentIdForPart(self, componentTag: TaggedObject) -> str: ...
    def GetPLLinkForPart(self) -> str: ...
    def GetPartInformation(self) -> MendixReporting.CadInfoManager.PartInformation: ...
    def Tag(self) -> Tag: ...



    class CadInfoManagerPartInformation():
        @property
        def PartHasUdf(self) -> bool: ...
        @PartHasUdf.setter
        def PartHasUdf(self, value: bool) -> None: ...
        @property
        def PartHasPosIndepWaveLink(self) -> bool: ...
        @PartHasPosIndepWaveLink.setter
        def PartHasPosIndepWaveLink(self, value: bool) -> None: ...
        @property
        def PartHasPosDepWaveLink(self) -> bool: ...
        @PartHasPosDepWaveLink.setter
        def PartHasPosDepWaveLink(self, value: bool) -> None: ...
        @property
        def PartHasInterpartExpression(self) -> bool: ...
        @PartHasInterpartExpression.setter
        def PartHasInterpartExpression(self, value: bool) -> None: ...
        @property
        def PartHasInterpartReferences(self) -> bool: ...
        @PartHasInterpartReferences.setter
        def PartHasInterpartReferences(self, value: bool) -> None: ...
        @property
        def PartHasProductInterface(self) -> bool: ...
        @PartHasProductInterface.setter
        def PartHasProductInterface(self, value: bool) -> None: ...
        @property
        def PartHasBrokenLinks(self) -> bool: ...
        @PartHasBrokenLinks.setter
        def PartHasBrokenLinks(self, value: bool) -> None: ...
        @property
        def PartHasAnyComponents(self) -> bool: ...
        @PartHasAnyComponents.setter
        def PartHasAnyComponents(self, value: bool) -> None: ...
        @property
        def PartHasGeometryOverrides(self) -> bool: ...
        @PartHasGeometryOverrides.setter
        def PartHasGeometryOverrides(self, value: bool) -> None: ...
        @property
        def PartHasPositionOverrides(self) -> bool: ...
        @PartHasPositionOverrides.setter
        def PartHasPositionOverrides(self, value: bool) -> None: ...
        @property
        def PartHasReferenceComponents(self) -> bool: ...
        @PartHasReferenceComponents.setter
        def PartHasReferenceComponents(self, value: bool) -> None: ...
        @property
        def PartHasSupressedComponents(self) -> bool: ...
        @PartHasSupressedComponents.setter
        def PartHasSupressedComponents(self, value: bool) -> None: ...
        @property
        def PartHasRestructuredComponents(self) -> bool: ...
        @PartHasRestructuredComponents.setter
        def PartHasRestructuredComponents(self, value: bool) -> None: ...
        @property
        def PartHasNonmasterComponent(self) -> bool: ...
        @PartHasNonmasterComponent.setter
        def PartHasNonmasterComponent(self, value: bool) -> None: ...
        @property
        def PartHasMultipleArrangements(self) -> bool: ...
        @PartHasMultipleArrangements.setter
        def PartHasMultipleArrangements(self, value: bool) -> None: ...
        @property
        def PartHasAltrepMetaData(self) -> bool: ...
        @PartHasAltrepMetaData.setter
        def PartHasAltrepMetaData(self, value: bool) -> None: ...
        @property
        def PartHasOffcenterComponents(self) -> bool: ...
        @PartHasOffcenterComponents.setter
        def PartHasOffcenterComponents(self, value: bool) -> None: ...
        @property
        def PartHasPartsList(self) -> bool: ...
        @PartHasPartsList.setter
        def PartHasPartsList(self, value: bool) -> None: ...
        @property
        def PartHasConstraint(self) -> bool: ...
        @PartHasConstraint.setter
        def PartHasConstraint(self, value: bool) -> None: ...
        @property
        def PartIsDrawing(self) -> bool: ...
        @PartIsDrawing.setter
        def PartIsDrawing(self, value: bool) -> None: ...
        @property
        def PartHasCaeData(self) -> bool: ...
        @PartHasCaeData.setter
        def PartHasCaeData(self, value: bool) -> None: ...
        @property
        def PartHasCamData(self) -> bool: ...
        @PartHasCamData.setter
        def PartHasCamData(self, value: bool) -> None: ...
        @property
        def PartIsPartFamilyMember(self) -> bool: ...
        @PartIsPartFamilyMember.setter
        def PartIsPartFamilyMember(self, value: bool) -> None: ...
        @property
        def PartIsPartFamilyTemplate(self) -> bool: ...
        @PartIsPartFamilyTemplate.setter
        def PartIsPartFamilyTemplate(self, value: bool) -> None: ...
        @property
        def PartIsPart(self) -> bool: ...
        @PartIsPart.setter
        def PartIsPart(self, value: bool) -> None: ...
        @property
        def PartHasMeasurableAttribute(self) -> bool: ...
        @PartHasMeasurableAttribute.setter
        def PartHasMeasurableAttribute(self, value: bool) -> None: ...
        @property
        def PartHasBody(self) -> bool: ...
        @PartHasBody.setter
        def PartHasBody(self, value: bool) -> None: ...
        @property
        def PartHasSuppressionOverride(self) -> bool: ...
        @PartHasSuppressionOverride.setter
        def PartHasSuppressionOverride(self, value: bool) -> None: ...
        @property
        def PartHasVisStructureStream(self) -> bool: ...
        @PartHasVisStructureStream.setter
        def PartHasVisStructureStream(self, value: bool) -> None: ...
        @property
        def PartHasVisRmStream(self) -> bool: ...
        @PartHasVisRmStream.setter
        def PartHasVisRmStream(self, value: bool) -> None: ...
        @property
        def PartPartUnits(self) -> bool: ...
        @PartPartUnits.setter
        def PartPartUnits(self, value: bool) -> None: ...
        @property
        def PartHasSheetMetalData(self) -> bool: ...
        @PartHasSheetMetalData.setter
        def PartHasSheetMetalData(self, value: bool) -> None: ...
        @property
        def PartIsRoutingPart(self) -> bool: ...
        @PartIsRoutingPart.setter
        def PartIsRoutingPart(self, value: bool) -> None: ...
        @property
        def PartIsRouteSystemAssembly(self) -> bool: ...
        @PartIsRouteSystemAssembly.setter
        def PartIsRouteSystemAssembly(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
    

