from ....NXOpen import *
from ...CAE import *

import typing
import enum

class VelocityImpactParameters(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def DropHeight(self) -> Expression: ...
    @DropHeight.setter
    def DropHeight(self, value: Expression) -> None: ...
    @property
    def PulseDuration(self) -> Expression: ...
    @PulseDuration.setter
    def PulseDuration(self, value: Expression) -> None: ...
    @property
    def StartPosition(self) -> CAE.ResponseSimulation.VelocityImpactParameters.StartPositionType: ...
    @StartPosition.setter
    def StartPosition(self, value: CAE.ResponseSimulation.VelocityImpactParameters.StartPositionType) -> None: ...
    @property
    def TimeStep(self) -> Expression: ...
    @TimeStep.setter
    def TimeStep(self, value: Expression) -> None: ...
    @property
    def Velocity(self) -> Expression: ...
    @Velocity.setter
    def Velocity(self, value: Expression) -> None: ...


    class StartPositionType(enum.Enum):
        AtDrop= 0
        BeforeImpact= 1
        AtImpact= 2
    

class VelocityImpactExcitationBuilder(CAE.ResponseSimulation.ExcitationBuilder):
    def __init__(self) -> None: ...
    @property
    def ImpactDirection(self) -> CAE.ResponseSimulation.VelocityImpactDirection: ...
    @ImpactDirection.setter
    def ImpactDirection(self, value: CAE.ResponseSimulation.VelocityImpactDirection) -> None: ...
    @property
    def ImpactMethod(self) -> CAE.ResponseSimulation.VelocityImpactExcitationBuilder.ImpactMethodType: ...
    @ImpactMethod.setter
    def ImpactMethod(self, value: CAE.ResponseSimulation.VelocityImpactExcitationBuilder.ImpactMethodType) -> None: ...
    @property
    def ImpactParameters(self) -> CAE.ResponseSimulation.VelocityImpactParameters: ...
    @ImpactParameters.setter
    def ImpactParameters(self, value: CAE.ResponseSimulation.VelocityImpactParameters) -> None: ...


    class ImpactMethodType(enum.Enum):
        ConstantVelocity= 0
        DropImpact= 1
    

class VelocityImpactExcitation(CAE.ResponseSimulation.Excitation):
    def __init__(self) -> None: ...


class VelocityImpactDirection(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def DirectionOption(self) -> CAE.ResponseSimulation.VelocityImpactDirection.DirectionType: ...
    @DirectionOption.setter
    def DirectionOption(self, value: CAE.ResponseSimulation.VelocityImpactDirection.DirectionType) -> None: ...
    @property
    def NodalComponent(self) -> CAE.ResponseSimulation.VelocityImpactDirection.NodalComponentType: ...
    @NodalComponent.setter
    def NodalComponent(self, value: CAE.ResponseSimulation.VelocityImpactDirection.NodalComponentType) -> None: ...
    @property
    def ReverseDirection(self) -> bool: ...
    @ReverseDirection.setter
    def ReverseDirection(self, value: bool) -> None: ...
    @property
    def UserDefinedDirection(self) -> Direction: ...
    @UserDefinedDirection.setter
    def UserDefinedDirection(self, value: Direction) -> None: ...


    class NodalComponentType(enum.Enum):
        Dof1= 0
        Dof2= 1
        Dof3= 2
    

    class DirectionType(enum.Enum):
        NodalComponent= 0
        UserDefined= 1
    

class TransmissibilityEvaluationSettingBuilder(CAE.ResponseSimulation.ModalResultsEvaluationSettingBuilder):
    def __init__(self) -> None: ...
    @property
    def InputMotionType(self) -> CAE.ResponseSimulation.TransmissibilityEvaluationSettingBuilder.MotionType: ...
    @InputMotionType.setter
    def InputMotionType(self, value: CAE.ResponseSimulation.TransmissibilityEvaluationSettingBuilder.MotionType) -> None: ...


    class MotionType(enum.Enum):
        Displacement= 0
        Velocity= 1
        Acceleration= 2
    

class TransmissibilityEvaluationSetting(CAE.ResponseSimulation.ModalResultsEvaluationSetting):
    def __init__(self) -> None: ...


class TranslationalNodalFunctionExcitationBuilder(CAE.ResponseSimulation.NodalFunctionExcitationBuilder):
    def __init__(self) -> None: ...
    @property
    def EnableUserDefinedDirection(self) -> bool: ...
    @EnableUserDefinedDirection.setter
    def EnableUserDefinedDirection(self, value: bool) -> None: ...
    @property
    def EnableUserDefinedRotation(self) -> bool: ...
    @EnableUserDefinedRotation.setter
    def EnableUserDefinedRotation(self, value: bool) -> None: ...
    @property
    def FunctionComponentX(self) -> CAE.ResponseSimulation.FunctionComponentData: ...
    @FunctionComponentX.setter
    def FunctionComponentX(self, value: CAE.ResponseSimulation.FunctionComponentData) -> None: ...
    @property
    def FunctionComponentY(self) -> CAE.ResponseSimulation.FunctionComponentData: ...
    @FunctionComponentY.setter
    def FunctionComponentY(self, value: CAE.ResponseSimulation.FunctionComponentData) -> None: ...
    @property
    def FunctionComponentZ(self) -> CAE.ResponseSimulation.FunctionComponentData: ...
    @FunctionComponentZ.setter
    def FunctionComponentZ(self, value: CAE.ResponseSimulation.FunctionComponentData) -> None: ...
    @property
    def RotationAxis(self) -> CAE.ResponseSimulation.TranslationalNodalFunctionExcitationBuilder.RotationAxisType: ...
    @RotationAxis.setter
    def RotationAxis(self, value: CAE.ResponseSimulation.TranslationalNodalFunctionExcitationBuilder.RotationAxisType) -> None: ...
    @property
    def UserDefinedDirection(self) -> Direction: ...
    @UserDefinedDirection.setter
    def UserDefinedDirection(self, value: Direction) -> None: ...
    @property
    def UserDefinedFunction(self) -> CAE.ResponseSimulation.FunctionComponentData: ...
    @UserDefinedFunction.setter
    def UserDefinedFunction(self, value: CAE.ResponseSimulation.FunctionComponentData) -> None: ...


    class RotationAxisType(enum.Enum):
        X= 0
        Y= 1
        Z= 2
    

class TranslationalNodalFunctionExcitation(CAE.ResponseSimulation.NodalFunctionExcitation):
    def __init__(self) -> None: ...


class TranslationalDDAMExcitationBuilder(CAE.ResponseSimulation.DDAMExcitationBuilder):
    def __init__(self) -> None: ...


class TranslationalDDAMExcitation(CAE.ResponseSimulation.DDAMExcitation):
    def __init__(self) -> None: ...


class StrengthStressOption(enum.Enum):
    ElementMaximum= 0
    NodeOnElement= 1


class StrengthStressMaterialDefinitionMethod(enum.Enum):
    UltimateSafety= 0
    YieldSafety= 1


class StrengthStressCriteria(enum.Enum):
    VonMises= 0
    MaxPrinciple= 1
    MinPrinciple= 2


class StrengthResultsEvaluationSettingBuilder(CAE.ResponseSimulation.DynamicResultEvaluationSettingBuilder):
    def __init__(self) -> None: ...
    def GetDestinationElements(self) -> typing.List[CAE.FEElement]: ...
    def SetDestinationElements(self, destinationElement: typing.List[CAE.FEElement]) -> None: ...
    @property
    def CombinationOptionsBuilder(self) -> CAE.ResponseSimulation.CombinationEvaluationOptions: ...
    @CombinationOptionsBuilder.setter
    def CombinationOptionsBuilder(self, value: CAE.ResponseSimulation.CombinationEvaluationOptions) -> None: ...
    @property
    def DataLocation(self) -> CAE.ResponseSimulation.DataLocation: ...
    @DataLocation.setter
    def DataLocation(self, value: CAE.ResponseSimulation.DataLocation) -> None: ...
    @property
    def MaterialDefinitionType(self) -> CAE.ResponseSimulation.StrengthStressMaterialDefinitionMethod: ...
    @MaterialDefinitionType.setter
    def MaterialDefinitionType(self, value: CAE.ResponseSimulation.StrengthStressMaterialDefinitionMethod) -> None: ...
    @property
    def MaterialOverrideOption(self) -> bool: ...
    @MaterialOverrideOption.setter
    def MaterialOverrideOption(self, value: bool) -> None: ...
    @property
    def MaterialSafetyFactor(self) -> float: ...
    @MaterialSafetyFactor.setter
    def MaterialSafetyFactor(self, value: float) -> None: ...
    @property
    def StandardDeviation(self) -> float: ...
    @StandardDeviation.setter
    def StandardDeviation(self, value: float) -> None: ...
    @property
    def StressCriteriaType(self) -> CAE.ResponseSimulation.StrengthStressCriteria: ...
    @StressCriteriaType.setter
    def StressCriteriaType(self, value: CAE.ResponseSimulation.StrengthStressCriteria) -> None: ...
    @property
    def StressOptionType(self) -> CAE.ResponseSimulation.StrengthStressOption: ...
    @StressOptionType.setter
    def StressOptionType(self, value: CAE.ResponseSimulation.StrengthStressOption) -> None: ...


class StrengthResultsEvaluationSetting(CAE.ResponseSimulation.DynamicResultEvaluationSetting):
    def __init__(self) -> None: ...


class StrainGageType(enum.Enum):
    UniAxial= 0
    BiAxial= 1
    Rosette45DegreeIncrement= 2
    Rosette60DegreeIncrement= 3


class StrainGageShellElementFaceType(enum.Enum):
    Top= 0
    Botton= 1


class StrainGageResult(enum.Enum):
    Strain= 0
    Stress= 1


class StrainGagePlacementType(enum.Enum):
    Node= 0
    ElementFaceCenter= 1


class StrainGageOrientationPlane(enum.Enum):
    FacePlane= 0
    Csys= 1


class StrainGageEvaluationSettingBuilder(CAE.ResponseSimulation.FunctionEvaluationSettingBuilder):
    def __init__(self) -> None: ...
    @property
    def DataComponent(self) -> CAE.ResponseSimulation.DirectionDataComponent: ...
    @DataComponent.setter
    def DataComponent(self, value: CAE.ResponseSimulation.DirectionDataComponent) -> None: ...
    @property
    def StrainGage(self) -> SelectDisplayableObjectList: ...
    @StrainGage.setter
    def StrainGage(self, value: SelectDisplayableObjectList) -> None: ...


class StrainGageEvaluationSetting(CAE.ResponseSimulation.DynamicResultEvaluationSetting):
    def __init__(self) -> None: ...


class StrainGageCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.ResponseSimulation.StrainGage]: ...
    @typing.overload
    def __init__(self, owner: CAE.ResponseSimulation.Manager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateStrainGageBuilder(self, strainGage: CAE.ResponseSimulation.StrainGage) -> CAE.ResponseSimulation.StrainGageBuilder: ...
    def FindObject(self, name: str) -> CAE.ResponseSimulation.StrainGage: ...
    def Tag(self) -> Tag: ...



class StrainGageBuilder(CAE.ResponseSimulation.BaseBuilder):
    def __init__(self) -> None: ...
    @property
    def Csys(self) -> SmartObject: ...
    @Csys.setter
    def Csys(self, value: SmartObject) -> None: ...
    @property
    def GageType(self) -> CAE.ResponseSimulation.StrainGageType: ...
    @GageType.setter
    def GageType(self, value: CAE.ResponseSimulation.StrainGageType) -> None: ...
    @property
    def Placement(self) -> CAE.ResponseSimulation.StrainGagePlacementType: ...
    @Placement.setter
    def Placement(self, value: CAE.ResponseSimulation.StrainGagePlacementType) -> None: ...
    @property
    def Plane(self) -> CAE.ResponseSimulation.StrainGageOrientationPlane: ...
    @Plane.setter
    def Plane(self, value: CAE.ResponseSimulation.StrainGageOrientationPlane) -> None: ...
    @property
    def ResultType(self) -> CAE.ResponseSimulation.StrainGageResult: ...
    @ResultType.setter
    def ResultType(self, value: CAE.ResponseSimulation.StrainGageResult) -> None: ...
    @property
    def RotationAngle(self) -> Expression: ...
    @RotationAngle.setter
    def RotationAngle(self, value: Expression) -> None: ...
    @property
    def SelectedElementFaces(self) -> CAE.SelectFEElemFaceList: ...
    @SelectedElementFaces.setter
    def SelectedElementFaces(self, value: CAE.SelectFEElemFaceList) -> None: ...
    @property
    def SelectedNode(self) -> CAE.SelectFENodeList: ...
    @SelectedNode.setter
    def SelectedNode(self, value: CAE.SelectFENodeList) -> None: ...
    @property
    def ShellElementFace(self) -> CAE.ResponseSimulation.StrainGageShellElementFaceType: ...
    @ShellElementFace.setter
    def ShellElementFace(self, value: CAE.ResponseSimulation.StrainGageShellElementFaceType) -> None: ...


class StrainGage(DisplayableObject):
    def __init__(self) -> None: ...
    def GetDisplayAttribute(self) -> CAE.ResponseSimulation.RSDisplayObject: ...


class StaticLoadExcitationBuilder(CAE.ResponseSimulation.ExcitationBuilder):
    def __init__(self) -> None: ...
    @property
    def ExcitationFunction(self) -> CAE.ResponseSimulation.FunctionComponentData: ...
    @ExcitationFunction.setter
    def ExcitationFunction(self, value: CAE.ResponseSimulation.FunctionComponentData) -> None: ...


class StaticLoadExcitation(CAE.ResponseSimulation.Excitation):
    def __init__(self) -> None: ...


class SolutionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.ResponseSimulation.Solution]: ...
    @typing.overload
    def __init__(self, owner: CAE.ResponseSimulation.Manager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateSolutionBuilder(self, raSolution: CAE.ResponseSimulation.Solution) -> CAE.ResponseSimulation.SolutionBuilder: ...
    def CloneSolution(self, oldSolution: CAE.ResponseSimulation.Solution, suggestedName: str) -> CAE.ResponseSimulation.Solution: ...
    def FindObject(self, solutionName: str) -> CAE.ResponseSimulation.Solution: ...
    def Tag(self) -> Tag: ...

    @property
    def ActiveSolution(self) -> CAE.ResponseSimulation.Solution: ...
    @ActiveSolution.setter
    def ActiveSolution(self, value: CAE.ResponseSimulation.Solution) -> None: ...


class SolutionBuilder(CAE.ResponseSimulation.BaseBuilder):
    def __init__(self) -> None: ...
    @property
    def Attributes(self) -> CAE.ResponseSimulation.SolutionAttributes: ...
    @Attributes.setter
    def Attributes(self, value: CAE.ResponseSimulation.SolutionAttributes) -> None: ...
    @property
    def ImportedEefFile(self) -> str: ...
    @ImportedEefFile.setter
    def ImportedEefFile(self, value: str) -> None: ...
    @property
    def ReferencedSolution(self) -> CAE.SimSolution: ...
    @ReferencedSolution.setter
    def ReferencedSolution(self, value: CAE.SimSolution) -> None: ...
    @property
    def ScratchDir(self) -> str: ...
    @ScratchDir.setter
    def ScratchDir(self, value: str) -> None: ...
    @property
    def UseNastranResultDir(self) -> bool: ...
    @UseNastranResultDir.setter
    def UseNastranResultDir(self, value: bool) -> None: ...
    @property
    def UseScratchDir(self) -> bool: ...
    @UseScratchDir.setter
    def UseScratchDir(self, value: bool) -> None: ...


class SolutionAttributes(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def RigidBodyToleranceExp(self) -> Expression: ...
    @RigidBodyToleranceExp.setter
    def RigidBodyToleranceExp(self, value: Expression) -> None: ...


class Solution(NXObject):
    def __init__(self) -> None: ...
    def GetSolutionName(self) -> str: ...
    def SetSolutionName(self, solutionName: str, renameResultFile: bool) -> None: ...
    def Destroy(self, deleteResultFile: bool) -> None: ...
    def GetModalProperties(self) -> CAE.ResponseSimulation.ModalProperties: ...
    def GetEvaluationParameters(self) -> CAE.ResponseSimulation.EvaluationParameters: ...
    def GetEvents(self) -> typing.List[CAE.ResponseSimulation.RSEvent]: ...
    def ImportEvent(self, eventDefinitionFile: str, suggestedName: str) -> CAE.ResponseSimulation.RSEvent: ...
    def CloneEvent(self, sourceEvent: CAE.ResponseSimulation.RSEvent, suggestedName: str) -> CAE.ResponseSimulation.RSEvent: ...
    def GetResultFileName(self) -> str: ...
    def EvaluateFrf(self, evaluationSetting: CAE.ResponseSimulation.FrfEvaluationSetting) -> None: ...
    def EvaluateTransmissibility(self, evaluationSetting: CAE.ResponseSimulation.TransmissibilityEvaluationSetting) -> None: ...
    def CloneSensor(self, sourceSensor: CAE.ResponseSimulation.Sensor, suggestedName: str) -> CAE.ResponseSimulation.Sensor: ...
    def CloneStrainGage(self, sourceGage: CAE.ResponseSimulation.StrainGage, suggestedName: str) -> CAE.ResponseSimulation.StrainGage: ...
    def CheckObsoleteStatus(self) -> None: ...
    @property
    def ActiveEvent(self) -> CAE.ResponseSimulation.RSEvent: ...
    @ActiveEvent.setter
    def ActiveEvent(self, value: CAE.ResponseSimulation.RSEvent) -> None: ...


class ShellElementEvaluationLocation(enum.Enum):
    Top= 0
    Middle= 1
    Bottom= 2


class SensorType(enum.Enum):
    Component= 0
    Direction= 1
    Normal= 2


class SensorResultType(enum.Enum):
    Displacement= 0
    Velocity= 1
    Acceleration= 2
    ReactionForce= 3


class SensorEvaluationSettingBuilder(CAE.ResponseSimulation.FunctionEvaluationSettingBuilder):
    def __init__(self) -> None: ...
    @property
    def Sensor(self) -> SelectDisplayableObjectList: ...
    @Sensor.setter
    def Sensor(self, value: SelectDisplayableObjectList) -> None: ...


class SensorEvaluationSetting(CAE.ResponseSimulation.DynamicResultEvaluationSetting):
    def __init__(self) -> None: ...


class SensorCoordinateType(enum.Enum):
    NodalCs= 0
    GlobalCs= 1


class SensorCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.ResponseSimulation.Sensor]: ...
    @typing.overload
    def __init__(self, owner: CAE.ResponseSimulation.Manager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateSensorBuilder(self, rsSensor: CAE.ResponseSimulation.Sensor) -> CAE.ResponseSimulation.SensorBuilder: ...
    def DeleteSensor(self, rsSensor: CAE.ResponseSimulation.Sensor) -> None: ...
    def FindObject(self, name: str) -> CAE.ResponseSimulation.Sensor: ...
    def Tag(self) -> Tag: ...



class SensorBuilder(CAE.ResponseSimulation.BaseBuilder):
    def __init__(self) -> None: ...
    def GetSelectedNodes(self) -> typing.List[CAE.FENode]: ...
    def SetSelectedNodes(self, destinationNodes: typing.List[CAE.FENode]) -> None: ...
    @property
    def ReverseNormalDirection(self) -> bool: ...
    @ReverseNormalDirection.setter
    def ReverseNormalDirection(self, value: bool) -> None: ...
    @property
    def SensorCoordinateType(self) -> CAE.ResponseSimulation.SensorCoordinateType: ...
    @SensorCoordinateType.setter
    def SensorCoordinateType(self, value: CAE.ResponseSimulation.SensorCoordinateType) -> None: ...
    @property
    def SensorDirectionX(self) -> bool: ...
    @SensorDirectionX.setter
    def SensorDirectionX(self, value: bool) -> None: ...
    @property
    def SensorDirectionY(self) -> bool: ...
    @SensorDirectionY.setter
    def SensorDirectionY(self, value: bool) -> None: ...
    @property
    def SensorDirectionZ(self) -> bool: ...
    @SensorDirectionZ.setter
    def SensorDirectionZ(self, value: bool) -> None: ...
    @property
    def SensorResultType(self) -> CAE.ResponseSimulation.SensorResultType: ...
    @SensorResultType.setter
    def SensorResultType(self, value: CAE.ResponseSimulation.SensorResultType) -> None: ...
    @property
    def SensorRotationX(self) -> bool: ...
    @SensorRotationX.setter
    def SensorRotationX(self, value: bool) -> None: ...
    @property
    def SensorRotationY(self) -> bool: ...
    @SensorRotationY.setter
    def SensorRotationY(self, value: bool) -> None: ...
    @property
    def SensorRotationZ(self) -> bool: ...
    @SensorRotationZ.setter
    def SensorRotationZ(self, value: bool) -> None: ...
    @property
    def SensorType(self) -> CAE.ResponseSimulation.SensorType: ...
    @SensorType.setter
    def SensorType(self, value: CAE.ResponseSimulation.SensorType) -> None: ...
    @property
    def SensorVector(self) -> Direction: ...
    @SensorVector.setter
    def SensorVector(self, value: Direction) -> None: ...


class Sensor(DisplayableObject):
    def __init__(self) -> None: ...
    def GetDisplayAttribute(self) -> CAE.ResponseSimulation.RSDisplayObject: ...


class RSEventSolverParameters(TaggedObject):
    def __init__(self) -> None: ...
    def GetDdamCoefficient(self, coefficientType: CAE.ResponseSimulation.RSEventSolverParameters.DdamCoefficientType) -> float: ...
    def SetDdamCoefficient(self, coefficientType: CAE.ResponseSimulation.RSEventSolverParameters.DdamCoefficientType, coefficient: float) -> None: ...
    @property
    def DdamCoefficientA(self) -> float: ...
    @DdamCoefficientA.setter
    def DdamCoefficientA(self, value: float) -> None: ...
    @property
    def DdamCoefficientV(self) -> float: ...
    @DdamCoefficientV.setter
    def DdamCoefficientV(self, value: float) -> None: ...


    class DdamCoefficientType(enum.Enum):
        Af= 0
        Vf= 1
        Aa= 2
        Ab= 3
        Ac= 4
        Ad= 5
        Va= 6
        Vb= 7
        Vc= 8
    

class RSEventParameters(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def ConfidenceLevel(self) -> float: ...
    @ConfidenceLevel.setter
    def ConfidenceLevel(self, value: float) -> None: ...
    @property
    def ConfidenceLevelOption(self) -> CAE.ResponseSimulation.RSEvent.ConfidenceLevelOption: ...
    @ConfidenceLevelOption.setter
    def ConfidenceLevelOption(self, value: CAE.ResponseSimulation.RSEvent.ConfidenceLevelOption) -> None: ...
    @property
    def FrequencyOutputRequestObject(self) -> CAE.ModelingObjectPropertyTable: ...
    @FrequencyOutputRequestObject.setter
    def FrequencyOutputRequestObject(self, value: CAE.ModelingObjectPropertyTable) -> None: ...
    @property
    def OutputRequestObject(self) -> CAE.ModelingObjectPropertyTable: ...
    @OutputRequestObject.setter
    def OutputRequestObject(self, value: CAE.ModelingObjectPropertyTable) -> None: ...
    @property
    def RandomOutputRequestObject(self) -> CAE.ModelingObjectPropertyTable: ...
    @RandomOutputRequestObject.setter
    def RandomOutputRequestObject(self, value: CAE.ModelingObjectPropertyTable) -> None: ...
    @property
    def ReferenceType(self) -> CAE.ResponseSimulation.RSEvent.ReferenceType: ...
    @ReferenceType.setter
    def ReferenceType(self, value: CAE.ResponseSimulation.RSEvent.ReferenceType) -> None: ...
    @property
    def SineOutputRequestObject(self) -> CAE.ModelingObjectPropertyTable: ...
    @SineOutputRequestObject.setter
    def SineOutputRequestObject(self, value: CAE.ModelingObjectPropertyTable) -> None: ...
    @property
    def StandardDeviation(self) -> float: ...
    @StandardDeviation.setter
    def StandardDeviation(self, value: float) -> None: ...
    @property
    def StaticContributions(self) -> bool: ...
    @StaticContributions.setter
    def StaticContributions(self, value: bool) -> None: ...


class RSEventOutputSetting(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def FemGeometrySaveOption(self) -> bool: ...
    @FemGeometrySaveOption.setter
    def FemGeometrySaveOption(self, value: bool) -> None: ...


class RSEventCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.ResponseSimulation.RSEvent]: ...
    @typing.overload
    def __init__(self, owner: CAE.ResponseSimulation.Manager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateEventBuilder(self, raEvent: CAE.ResponseSimulation.RSEvent) -> CAE.ResponseSimulation.RSEventBuilder: ...
    def DeleteEvent(self, raEvent: CAE.ResponseSimulation.RSEvent) -> None: ...
    def FindObject(self, name: str) -> CAE.ResponseSimulation.RSEvent: ...
    def Tag(self) -> Tag: ...



class RSEventBuilder(CAE.ResponseSimulation.BaseBuilder):
    def __init__(self) -> None: ...
    @property
    def Attributes(self) -> CAE.ResponseSimulation.RSEventAttributes: ...
    @Attributes.setter
    def Attributes(self, value: CAE.ResponseSimulation.RSEventAttributes) -> None: ...
    @property
    def EventParameters(self) -> CAE.ResponseSimulation.RSEventParameters: ...
    @EventParameters.setter
    def EventParameters(self, value: CAE.ResponseSimulation.RSEventParameters) -> None: ...
    @property
    def EventType(self) -> CAE.ResponseSimulation.RSEvent.Type: ...
    @EventType.setter
    def EventType(self, value: CAE.ResponseSimulation.RSEvent.Type) -> None: ...
    @property
    def InitialConditions(self) -> CAE.ResponseSimulation.InitialConditions: ...
    @InitialConditions.setter
    def InitialConditions(self, value: CAE.ResponseSimulation.InitialConditions) -> None: ...
    @property
    def OutputSetting(self) -> CAE.ResponseSimulation.RSEventOutputSetting: ...
    @OutputSetting.setter
    def OutputSetting(self, value: CAE.ResponseSimulation.RSEventOutputSetting) -> None: ...
    @property
    def ResponseSimulationSolution(self) -> CAE.ResponseSimulation.Solution: ...
    @ResponseSimulationSolution.setter
    def ResponseSimulationSolution(self, value: CAE.ResponseSimulation.Solution) -> None: ...


class RSEventAttributes(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def AnalysisType(self) -> CAE.ResponseSimulation.RSEvent.AnalysisType: ...
    @AnalysisType.setter
    def AnalysisType(self, value: CAE.ResponseSimulation.RSEvent.AnalysisType) -> None: ...
    @property
    def CoefficientDefinitionMethod(self) -> CAE.ResponseSimulation.DDAMExcitation.CoefficientDefinitionType: ...
    @CoefficientDefinitionMethod.setter
    def CoefficientDefinitionMethod(self, value: CAE.ResponseSimulation.DDAMExcitation.CoefficientDefinitionType) -> None: ...
    @property
    def CoefficientFile(self) -> str: ...
    @CoefficientFile.setter
    def CoefficientFile(self, value: str) -> None: ...
    @property
    def Duration(self) -> float: ...
    @Duration.setter
    def Duration(self, value: float) -> None: ...
    @property
    def DurationOption(self) -> CAE.ResponseSimulation.RSEvent.DurationOption: ...
    @DurationOption.setter
    def DurationOption(self, value: CAE.ResponseSimulation.RSEvent.DurationOption) -> None: ...
    @property
    def FastRmsMethod(self) -> bool: ...
    @FastRmsMethod.setter
    def FastRmsMethod(self, value: bool) -> None: ...
    @property
    def Formulation(self) -> CAE.ResponseSimulation.RSEvent.DdamFormulationType: ...
    @Formulation.setter
    def Formulation(self, value: CAE.ResponseSimulation.RSEvent.DdamFormulationType) -> None: ...
    @property
    def InterpolationMethod(self) -> CAE.ResponseSimulation.InterpolationMethod: ...
    @InterpolationMethod.setter
    def InterpolationMethod(self, value: CAE.ResponseSimulation.InterpolationMethod) -> None: ...
    @property
    def MinimumGValue(self) -> float: ...
    @MinimumGValue.setter
    def MinimumGValue(self, value: float) -> None: ...
    @property
    def MountingType(self) -> CAE.ResponseSimulation.DDAMExcitation.MountingType: ...
    @MountingType.setter
    def MountingType(self, value: CAE.ResponseSimulation.DDAMExcitation.MountingType) -> None: ...
    @property
    def ResponseType(self) -> CAE.ResponseSimulation.DDAMExcitation.ResponseType: ...
    @ResponseType.setter
    def ResponseType(self, value: CAE.ResponseSimulation.DDAMExcitation.ResponseType) -> None: ...
    @property
    def ShipType(self) -> CAE.ResponseSimulation.DDAMExcitation.ShipType: ...
    @ShipType.setter
    def ShipType(self, value: CAE.ResponseSimulation.DDAMExcitation.ShipType) -> None: ...
    @property
    def Spacing(self) -> CAE.ResponseSimulation.RSEvent.SpacingType: ...
    @Spacing.setter
    def Spacing(self, value: CAE.ResponseSimulation.RSEvent.SpacingType) -> None: ...
    @property
    def SpectralLines(self) -> int: ...
    @SpectralLines.setter
    def SpectralLines(self, value: int) -> None: ...


class RSEvent(NXObject):
    def __init__(self) -> None: ...
    def GetSolverParameters(self) -> CAE.ResponseSimulation.RSEventSolverParameters: ...
    def GetCalculateStaticOffset(self) -> bool: ...
    def SetCalculateStaticOffset(self, calculateStaticOffset: bool) -> None: ...
    def GetEventName(self) -> str: ...
    def SetEventName(self, eventName: str, renameResultFile: bool) -> None: ...
    def Destroy(self, deleteResultFile: bool) -> None: ...
    def GetExcitations(self) -> typing.List[CAE.ResponseSimulation.Excitation]: ...
    def GetResultFileName(self, resultFileType: CAE.ResponseSimulation.RSEvent.ResultFileType) -> str: ...
    def Export(self, eventDefinitionFile: str) -> None: ...
    def EvaluateModalFunctionResponse(self) -> None: ...
    def EvaluateNodalFunctionResponse(self, evaluationSetting: CAE.ResponseSimulation.NodalFunctionEvaluationSetting) -> None: ...
    def EvaluateElementalFunctionResponse(self, evaluationSetting: CAE.ResponseSimulation.ElementalFunctionEvaluationSetting) -> None: ...
    def EvaluateCsd(self, evaluationSetting: CAE.ResponseSimulation.CsdEvaluationSetting) -> None: ...
    def EvaluateModalResponse(self) -> None: ...
    def EvaluateResponseResults(self, evaluationSetting: CAE.ResponseSimulation.ResponseResultsEvaluationSetting) -> None: ...
    def EvaluateStrengthResults(self, evaluationSetting: CAE.ResponseSimulation.StrengthResultsEvaluationSetting) -> None: ...
    def EvaluatePeakValueResults(self, evaluationSetting: CAE.ResponseSimulation.PeakValueEvaluationSetting) -> None: ...
    def EvaluateRmsResults(self, evaluationSetting: CAE.ResponseSimulation.RmsResultsEvaluationSetting) -> None: ...
    def EvaluateLcrResults(self, evaluationSetting: CAE.ResponseSimulation.LcrResultsEvaluationSetting) -> None: ...
    @typing.overload
    def EvaluateSensorResponse(self) -> None: ...
    @typing.overload
    def EvaluateSensorResponse(self, evaluationSetting: CAE.ResponseSimulation.SensorEvaluationSetting) -> None: ...
    def EvaluateStrainGageResponse(self, evaluationSetting: CAE.ResponseSimulation.StrainGageEvaluationSetting) -> None: ...
    def RbeEventSolve(self, runInBackground: bool) -> int: ...
    def BaseExcitationEventSolve(self, runInBackground: bool) -> int: ...
    def RbeEventWriteInputFile(self) -> None: ...
    def BaseExcitationEventWriteInputFile(self) -> None: ...
    def RbeEventWriteBatchFile(self) -> None: ...
    def BaseExcitationEventWriteBatchFile(self) -> None: ...
    def CheckObsoleteStatus(self) -> None: ...
    def DeleteResultFiles(self, resultFileType: CAE.ResponseSimulation.RSEvent.ResultFileType) -> None: ...
    def LoadFunctionResults(self) -> bool: ...


    class Type(enum.Enum):
        Transient= 0
        Frequency= 1
        Random= 2
        ResponseSpectrum= 3
        Ddam= 4
        Static= 5
        RandomBaseExcitation= 6
        SineBaseExcitation= 7
    

    class SpacingType(enum.Enum):
        Even= 0
        Uneven= 1
    

    class ResultFileType(enum.Enum):
        ModalResponse= 0
        FunctionResponse= 1
        DynamicResponse= 2
        ContourFunctionResponse= 3
    

    class ReferenceType(enum.Enum):
        Relative= 0
        Absolute= 1
    

    class DurationOption(enum.Enum):
        ExcitationFunction= 0
        UserDefined= 1
    

    class DdamFormulationType(enum.Enum):
        Standard= 0
        UserDefined= 1
    

    class ConfidenceLevelOption(enum.Enum):
        UserDefined= 0
        StandardDeviations= 1
        Rms= 2
    

    class AnalysisType(enum.Enum):
        ModeAcceleration= 0
        ModeDisplacement= 1
    

class RSDisplayObject(NXObject):
    def __init__(self) -> None: ...
    @property
    def DisplayName(self) -> bool: ...
    @DisplayName.setter
    def DisplayName(self, value: bool) -> None: ...
    @property
    def Scale(self) -> Expression: ...
    @Scale.setter
    def Scale(self, value: Expression) -> None: ...


class RotationalNodalFunctionExcitationBuilder(CAE.ResponseSimulation.NodalFunctionExcitationBuilder):
    def __init__(self) -> None: ...
    @property
    def FunctionComponentRx(self) -> CAE.ResponseSimulation.FunctionComponentData: ...
    @FunctionComponentRx.setter
    def FunctionComponentRx(self, value: CAE.ResponseSimulation.FunctionComponentData) -> None: ...
    @property
    def FunctionComponentRy(self) -> CAE.ResponseSimulation.FunctionComponentData: ...
    @FunctionComponentRy.setter
    def FunctionComponentRy(self, value: CAE.ResponseSimulation.FunctionComponentData) -> None: ...
    @property
    def FunctionComponentRz(self) -> CAE.ResponseSimulation.FunctionComponentData: ...
    @FunctionComponentRz.setter
    def FunctionComponentRz(self, value: CAE.ResponseSimulation.FunctionComponentData) -> None: ...


class RotationalNodalFunctionExcitation(CAE.ResponseSimulation.NodalFunctionExcitation):
    def __init__(self) -> None: ...


class RotationalDDAMExcitationBuilder(CAE.ResponseSimulation.DDAMExcitationBuilder):
    def __init__(self) -> None: ...


class RotationalDDAMExcitation(CAE.ResponseSimulation.DDAMExcitation):
    def __init__(self) -> None: ...


class RmsResultsEvaluationSettingBuilder(CAE.ResponseSimulation.PrlResultsEvaluationSettingBuilder):
    def __init__(self) -> None: ...
    @property
    def EvaluationMethod(self) -> CAE.ResponseSimulation.RmsLcrEvaluationMethod: ...
    @EvaluationMethod.setter
    def EvaluationMethod(self, value: CAE.ResponseSimulation.RmsLcrEvaluationMethod) -> None: ...
    @property
    def UserDefinedDirection(self) -> Direction: ...
    @UserDefinedDirection.setter
    def UserDefinedDirection(self, value: Direction) -> None: ...
    @property
    def UsingUserDefinedDirection(self) -> bool: ...
    @UsingUserDefinedDirection.setter
    def UsingUserDefinedDirection(self, value: bool) -> None: ...


class RmsResultsEvaluationSetting(CAE.ResponseSimulation.PrlResultsEvaluationSetting):
    def __init__(self) -> None: ...


class RmsLcrEvaluationMethod(enum.Enum):
    SmallNumberItems= 0
    LargeNumberItems= 1
    AutomaticSelection= 2


class ResponseResultsEvaluationSettingBuilder(CAE.ResponseSimulation.DynamicResultEvaluationSettingBuilder):
    def __init__(self) -> None: ...
    def GetDestinationNodes(self) -> typing.List[CAE.FENode]: ...
    def SetDestinationNodes(self, destinationNodes: typing.List[CAE.FENode]) -> None: ...
    def GetDestinationElements(self) -> typing.List[CAE.FEElement]: ...
    def SetDestinationElements(self, destinationElement: typing.List[CAE.FEElement]) -> None: ...
    def GetOutputOptions(self) -> typing.List[CAE.ResponseSimulation.EvaluationResultType]: ...
    def SetOutputOptions(self, outputOptions: typing.List[CAE.ResponseSimulation.EvaluationResultType]) -> None: ...
    def GetPointsValueList(self) -> float: ...
    def SetPointsValueList(self, pointsValueList: float) -> None: ...
    @property
    def DecimationOrder(self) -> int: ...
    @DecimationOrder.setter
    def DecimationOrder(self, value: int) -> None: ...
    @property
    def EndPoint(self) -> float: ...
    @EndPoint.setter
    def EndPoint(self, value: float) -> None: ...
    @property
    def PointValue(self) -> float: ...
    @PointValue.setter
    def PointValue(self, value: float) -> None: ...
    @property
    def ResponseDomainDefinitionOption(self) -> CAE.ResponseSimulation.ResponseDomainDefinitionMethod: ...
    @ResponseDomainDefinitionOption.setter
    def ResponseDomainDefinitionOption(self, value: CAE.ResponseSimulation.ResponseDomainDefinitionMethod) -> None: ...
    @property
    def SpringForceEvaluationFromDisplacement(self) -> bool: ...
    @SpringForceEvaluationFromDisplacement.setter
    def SpringForceEvaluationFromDisplacement(self, value: bool) -> None: ...
    @property
    def StartPoint(self) -> float: ...
    @StartPoint.setter
    def StartPoint(self, value: float) -> None: ...


class ResponseResultsEvaluationSetting(CAE.ResponseSimulation.DynamicResultEvaluationSetting):
    def __init__(self) -> None: ...


class ResponseDomainDefinitionMethod(enum.Enum):
    StartEndPoint= 0
    KeyIn= 1
    NaturalFrequency= 2


class PrlResultsEvaluationSettingBuilder(CAE.ResponseSimulation.DynamicResultEvaluationSettingBuilder):
    def __init__(self) -> None: ...
    def GetOutputNodes(self) -> typing.List[CAE.FENode]: ...
    def SetOutputNodes(self, destinationNodes: typing.List[CAE.FENode]) -> None: ...
    def GetOutputElements(self) -> typing.List[CAE.FEElement]: ...
    def SetOutputElements(self, destinationElements: typing.List[CAE.FEElement]) -> None: ...
    def GetDataComponents(self) -> typing.List[CAE.ResponseSimulation.DirectionDataComponent]: ...
    def SetDataComponents(self, dataComponent: typing.List[CAE.ResponseSimulation.DirectionDataComponent]) -> None: ...
    @property
    def CoordinateSystem(self) -> CAE.ResponseSimulation.CoordinateSystem: ...
    @CoordinateSystem.setter
    def CoordinateSystem(self, value: CAE.ResponseSimulation.CoordinateSystem) -> None: ...
    @property
    def ObservationNode(self) -> CAE.FENode: ...
    @ObservationNode.setter
    def ObservationNode(self, value: CAE.FENode) -> None: ...
    @property
    def Relative(self) -> bool: ...
    @Relative.setter
    def Relative(self, value: bool) -> None: ...
    @property
    def ResultType(self) -> CAE.ResponseSimulation.EvaluationResultType: ...
    @ResultType.setter
    def ResultType(self, value: CAE.ResponseSimulation.EvaluationResultType) -> None: ...
    @property
    def SpringForceEvaluationFromDisplacement(self) -> bool: ...
    @SpringForceEvaluationFromDisplacement.setter
    def SpringForceEvaluationFromDisplacement(self, value: bool) -> None: ...


class PrlResultsEvaluationSetting(CAE.ResponseSimulation.DynamicResultEvaluationSetting):
    def __init__(self) -> None: ...


class PhysicalDampingSettings(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def PhysicalHystereticScalingFactor(self) -> float: ...
    @PhysicalHystereticScalingFactor.setter
    def PhysicalHystereticScalingFactor(self, value: float) -> None: ...
    @property
    def PhysicalViscousScalingFactor(self) -> float: ...
    @PhysicalViscousScalingFactor.setter
    def PhysicalViscousScalingFactor(self, value: float) -> None: ...
    @property
    def UsingPhysicalHysteretic(self) -> bool: ...
    @UsingPhysicalHysteretic.setter
    def UsingPhysicalHysteretic(self, value: bool) -> None: ...
    @property
    def UsingPhysicalViscous(self) -> bool: ...
    @UsingPhysicalViscous.setter
    def UsingPhysicalViscous(self, value: bool) -> None: ...


class PeakValueEvaluationSettingBuilder(CAE.ResponseSimulation.PrlResultsEvaluationSettingBuilder):
    def __init__(self) -> None: ...
    @property
    def CombinationOptions(self) -> CAE.ResponseSimulation.CombinationEvaluationOptions: ...
    @CombinationOptions.setter
    def CombinationOptions(self, value: CAE.ResponseSimulation.CombinationEvaluationOptions) -> None: ...


class PeakValueEvaluationSetting(CAE.ResponseSimulation.PrlResultsEvaluationSetting):
    def __init__(self) -> None: ...


class ObjectLabel(TaggedObject):
    def __init__(self) -> None: ...
    def GetDescriptions(self) -> str: ...
    def SetDescriptions(self, description: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...


class NormalMode(NXObject):
    def __init__(self) -> None: ...
    def GetModeId(self) -> int: ...
    def GetFrequency(self) -> float: ...
    def GetStiffeness(self) -> float: ...
    def GetMass(self) -> float: ...
    def GetXMass(self) -> float: ...
    def GetYMass(self) -> float: ...
    def GetZMass(self) -> float: ...
    def GetRxMass(self) -> float: ...
    def GetRyMass(self) -> float: ...
    def GetRzMass(self) -> float: ...
    def GetPhysicalViscous(self) -> float: ...
    def GetPhysicalHysteretic(self) -> float: ...
    @property
    def Active(self) -> bool: ...
    @Active.setter
    def Active(self, value: bool) -> None: ...
    @property
    def Hysteretic(self) -> float: ...
    @Hysteretic.setter
    def Hysteretic(self, value: float) -> None: ...
    @property
    def Viscous(self) -> float: ...
    @Viscous.setter
    def Viscous(self, value: float) -> None: ...


class NodalFunctionExcitationBuilder(CAE.ResponseSimulation.ExcitationBuilder):
    def __init__(self) -> None: ...
    @property
    def FrequencyRangeLowerBound(self) -> float: ...
    @FrequencyRangeLowerBound.setter
    def FrequencyRangeLowerBound(self, value: float) -> None: ...
    @property
    def FrequencyRangeUpperBound(self) -> float: ...
    @FrequencyRangeUpperBound.setter
    def FrequencyRangeUpperBound(self, value: float) -> None: ...
    @property
    def InheritFrequencyRangeFromFunction(self) -> bool: ...
    @InheritFrequencyRangeFromFunction.setter
    def InheritFrequencyRangeFromFunction(self, value: bool) -> None: ...
    @property
    def InitialAccelerationX(self) -> Expression: ...
    @InitialAccelerationX.setter
    def InitialAccelerationX(self, value: Expression) -> None: ...
    @property
    def InitialAccelerationY(self) -> Expression: ...
    @InitialAccelerationY.setter
    def InitialAccelerationY(self, value: Expression) -> None: ...
    @property
    def InitialAccelerationZ(self) -> Expression: ...
    @InitialAccelerationZ.setter
    def InitialAccelerationZ(self, value: Expression) -> None: ...
    @property
    def InitialDisplacementX(self) -> Expression: ...
    @InitialDisplacementX.setter
    def InitialDisplacementX(self, value: Expression) -> None: ...
    @property
    def InitialDisplacementY(self) -> Expression: ...
    @InitialDisplacementY.setter
    def InitialDisplacementY(self, value: Expression) -> None: ...
    @property
    def InitialDisplacementZ(self) -> Expression: ...
    @InitialDisplacementZ.setter
    def InitialDisplacementZ(self, value: Expression) -> None: ...
    @property
    def InitialUserDefDirAcceleration(self) -> Expression: ...
    @InitialUserDefDirAcceleration.setter
    def InitialUserDefDirAcceleration(self, value: Expression) -> None: ...
    @property
    def InitialUserDefDirDisplacement(self) -> Expression: ...
    @InitialUserDefDirDisplacement.setter
    def InitialUserDefDirDisplacement(self, value: Expression) -> None: ...
    @property
    def InitialUserDefDirVelocity(self) -> Expression: ...
    @InitialUserDefDirVelocity.setter
    def InitialUserDefDirVelocity(self, value: Expression) -> None: ...
    @property
    def InitialVelocityX(self) -> Expression: ...
    @InitialVelocityX.setter
    def InitialVelocityX(self, value: Expression) -> None: ...
    @property
    def InitialVelocityY(self) -> Expression: ...
    @InitialVelocityY.setter
    def InitialVelocityY(self, value: Expression) -> None: ...
    @property
    def InitialVelocityZ(self) -> Expression: ...
    @InitialVelocityZ.setter
    def InitialVelocityZ(self, value: Expression) -> None: ...
    @property
    def UserSpecifiedInitialExcitationConditionsToggle(self) -> bool: ...
    @UserSpecifiedInitialExcitationConditionsToggle.setter
    def UserSpecifiedInitialExcitationConditionsToggle(self, value: bool) -> None: ...


class NodalFunctionExcitation(CAE.ResponseSimulation.Excitation):
    def __init__(self) -> None: ...


    class Type(enum.Enum):
        NodalForce= 0
        EnforcedMotion= 1
    

class NodalFunctionEvaluationSettingBuilder(CAE.ResponseSimulation.FunctionEvaluationSettingBuilder):
    def __init__(self) -> None: ...
    def GetDestinationNodes(self) -> typing.List[CAE.FENode]: ...
    def SetDestinationNodes(self, destinationNodes: typing.List[CAE.FENode]) -> None: ...
    @property
    def BeamDataLocation(self) -> CAE.ResponseSimulation.NodalFunctionEvalBeamLocation: ...
    @BeamDataLocation.setter
    def BeamDataLocation(self, value: CAE.ResponseSimulation.NodalFunctionEvalBeamLocation) -> None: ...
    @property
    def CoordinateSystem(self) -> CAE.ResponseSimulation.CoordinateSystem: ...
    @CoordinateSystem.setter
    def CoordinateSystem(self, value: CAE.ResponseSimulation.CoordinateSystem) -> None: ...
    @property
    def DataComponent(self) -> CAE.ResponseSimulation.DirectionDataComponent: ...
    @DataComponent.setter
    def DataComponent(self, value: CAE.ResponseSimulation.DirectionDataComponent) -> None: ...
    @property
    def RelativeNode(self) -> CAE.FENode: ...
    @RelativeNode.setter
    def RelativeNode(self, value: CAE.FENode) -> None: ...
    @property
    def ShellDataLocation(self) -> CAE.ResponseSimulation.NodalFunctionEvalShellLocation: ...
    @ShellDataLocation.setter
    def ShellDataLocation(self, value: CAE.ResponseSimulation.NodalFunctionEvalShellLocation) -> None: ...
    @property
    def UserDefinedDirection(self) -> Direction: ...
    @UserDefinedDirection.setter
    def UserDefinedDirection(self, value: Direction) -> None: ...
    @property
    def UsingUserDefinedDirection(self) -> CAE.ResponseSimulation.NodalFunctionEvalRequest: ...
    @UsingUserDefinedDirection.setter
    def UsingUserDefinedDirection(self, value: CAE.ResponseSimulation.NodalFunctionEvalRequest) -> None: ...


class NodalFunctionEvaluationSetting(CAE.ResponseSimulation.FunctionEvaluationSetting):
    def __init__(self) -> None: ...


class NodalFunctionEvalShellLocation(enum.Enum):
    Top= 0
    Middle= 1
    Bottom= 2
    All= 3


class NodalFunctionEvalRequest(enum.Enum):
    UserDefinedDirection= 0
    DataComponent= 1


class NodalFunctionEvalBeamLocation(enum.Enum):
    C= 0
    D= 1
    E= 2
    F= 3
    All= 4


class NodalAveragingOption(enum.Enum):
    Shells= 0
    Solids= 1


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class ModeInitialData(NXObject):
    def __init__(self) -> None: ...
    def GetModeId(self) -> int: ...
    @property
    def InitialDisplacement(self) -> float: ...
    @InitialDisplacement.setter
    def InitialDisplacement(self, value: float) -> None: ...
    @property
    def InitialVelocity(self) -> float: ...
    @InitialVelocity.setter
    def InitialVelocity(self, value: float) -> None: ...


class ModalResultsEvaluationSettingBuilder(CAE.ResponseSimulation.FunctionEvaluationSettingBuilder):
    def __init__(self) -> None: ...
    def GetOutputNodes(self) -> typing.List[CAE.FENode]: ...
    def SetOutputNodes(self, destinationNode: typing.List[CAE.FENode]) -> None: ...
    def GetOutputElements(self) -> typing.List[CAE.FEElement]: ...
    def SetOutputElements(self, destinationElements: typing.List[CAE.FEElement]) -> None: ...
    @property
    def DataLocation(self) -> CAE.ResponseSimulation.DataLocation: ...
    @DataLocation.setter
    def DataLocation(self, value: CAE.ResponseSimulation.DataLocation) -> None: ...
    @property
    def EvaluationProperty(self) -> CAE.ResponseSimulation.FrequencyDefinition: ...
    @EvaluationProperty.setter
    def EvaluationProperty(self, value: CAE.ResponseSimulation.FrequencyDefinition) -> None: ...
    @property
    def InputDirection(self) -> CAE.ResponseSimulation.DirectionDataComponent: ...
    @InputDirection.setter
    def InputDirection(self, value: CAE.ResponseSimulation.DirectionDataComponent) -> None: ...
    @property
    def InputNode(self) -> CAE.FENode: ...
    @InputNode.setter
    def InputNode(self, value: CAE.FENode) -> None: ...
    @property
    def ObservationNode(self) -> CAE.FENode: ...
    @ObservationNode.setter
    def ObservationNode(self, value: CAE.FENode) -> None: ...
    @property
    def OutputRequest(self) -> CAE.ResponseSimulation.DirectionDataComponent: ...
    @OutputRequest.setter
    def OutputRequest(self, value: CAE.ResponseSimulation.DirectionDataComponent) -> None: ...


class ModalResultsEvaluationSetting(CAE.ResponseSimulation.FunctionEvaluationSetting):
    def __init__(self) -> None: ...


class ModalProperties(NXObject):
    def __init__(self) -> None: ...
    def GetNormalModeCount(self) -> int: ...
    def GetConstrainModeCount(self) -> int: ...
    def GetAttachmentModeCount(self) -> int: ...
    def GetNormalModeById(self, modeId: int) -> CAE.ResponseSimulation.NormalMode: ...
    def GetNormalModes(self) -> typing.List[CAE.ResponseSimulation.NormalMode]: ...
    def Activate(self, activate: bool) -> None: ...
    def DeactivateModesBelowLimit(self, limit: float) -> None: ...
    def SetDampingFactors(self, viscousDamping: float, hystereticDamping: float) -> None: ...
    def SetRayleighDamping(self, alphaFactor: float, beltaFactor: float) -> None: ...
    def GetPhysicalDampingSettings(self) -> CAE.ResponseSimulation.PhysicalDampingSettings: ...


class Manager(Utilities.NXRemotableObject):
    def __init__(self, owner: CAE.SimSimulation) -> None: ...
    def Tag(self) -> Tag: ...

    @property
    def Solutions(self) -> CAE.ResponseSimulation.SolutionCollection: ...
    @Solutions.setter
    def Solutions(self, value: CAE.ResponseSimulation.SolutionCollection) -> None: ...
    @property
    def Events(self) -> CAE.ResponseSimulation.RSEventCollection: ...
    @Events.setter
    def Events(self, value: CAE.ResponseSimulation.RSEventCollection) -> None: ...
    @property
    def Excitations(self) -> CAE.ResponseSimulation.ExcitationCollection: ...
    @Excitations.setter
    def Excitations(self, value: CAE.ResponseSimulation.ExcitationCollection) -> None: ...
    @property
    def EvaluationSettingManager(self) -> CAE.ResponseSimulation.EvaluationSettingManager: ...
    @EvaluationSettingManager.setter
    def EvaluationSettingManager(self, value: CAE.ResponseSimulation.EvaluationSettingManager) -> None: ...
    @property
    def Sensors(self) -> CAE.ResponseSimulation.SensorCollection: ...
    @Sensors.setter
    def Sensors(self, value: CAE.ResponseSimulation.SensorCollection) -> None: ...
    @property
    def StrainGages(self) -> CAE.ResponseSimulation.StrainGageCollection: ...
    @StrainGages.setter
    def StrainGages(self, value: CAE.ResponseSimulation.StrainGageCollection) -> None: ...


class LcrResultsEvaluationSettingBuilder(CAE.ResponseSimulation.RmsResultsEvaluationSettingBuilder):
    def __init__(self) -> None: ...
    @property
    def CrossingLevel(self) -> float: ...
    @CrossingLevel.setter
    def CrossingLevel(self, value: float) -> None: ...
    @property
    def CrossingLevelExpression(self) -> Expression: ...
    @CrossingLevelExpression.setter
    def CrossingLevelExpression(self, value: Expression) -> None: ...


class LcrResultsEvaluationSetting(CAE.ResponseSimulation.RmsResultsEvaluationSetting):
    def __init__(self) -> None: ...


class InterpolationMethod(enum.Enum):
    LogLog= 0
    LinearLinear= 1
    LinearLog= 2
    LogLinear= 3


class InitialConditions(NXObject):
    def __init__(self) -> None: ...
    def GetCustomizedInitialDataById(self, modeId: int) -> CAE.ResponseSimulation.ModeInitialData: ...
    def GetAllCustomizedInitialData(self) -> typing.List[CAE.ResponseSimulation.ModeInitialData]: ...
    @property
    def EntryMethodOption(self) -> CAE.ResponseSimulation.InitialConditions.EntryMethod: ...
    @EntryMethodOption.setter
    def EntryMethodOption(self, value: CAE.ResponseSimulation.InitialConditions.EntryMethod) -> None: ...
    @property
    def ExistingEefFile(self) -> str: ...
    @ExistingEefFile.setter
    def ExistingEefFile(self, value: str) -> None: ...
    @property
    def InitialConditionType(self) -> CAE.ResponseSimulation.InitialConditions.Type: ...
    @InitialConditionType.setter
    def InitialConditionType(self, value: CAE.ResponseSimulation.InitialConditions.Type) -> None: ...


    class Type(enum.Enum):
        QuasiStatic= 0
        Zero= 1
        UserDefined= 2
    

    class EntryMethod(enum.Enum):
        ManualData= 0
        FromEef= 1
    

class FunctionEvaluationSettingBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def OutputSettings(self) -> CAE.ResponseSimulation.FunctionEvaluationOutputSettings: ...
    @OutputSettings.setter
    def OutputSettings(self, value: CAE.ResponseSimulation.FunctionEvaluationOutputSettings) -> None: ...
    @property
    def ResultType(self) -> CAE.ResponseSimulation.EvaluationResultType: ...
    @ResultType.setter
    def ResultType(self, value: CAE.ResponseSimulation.EvaluationResultType) -> None: ...


class FunctionEvaluationSetting(CAE.ResponseSimulation.EvaluationSetting):
    def __init__(self) -> None: ...


class FunctionEvaluationOutputSettings(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def RecordPrefix(self) -> str: ...
    @RecordPrefix.setter
    def RecordPrefix(self, value: str) -> None: ...
    @property
    def ShowPlot(self) -> bool: ...
    @ShowPlot.setter
    def ShowPlot(self, value: bool) -> None: ...
    @property
    def StoreOption(self) -> bool: ...
    @StoreOption.setter
    def StoreOption(self, value: bool) -> None: ...


class FunctionComponentData(TaggedObject):
    def __init__(self) -> None: ...
    def GetComponentType(self) -> CAE.ResponseSimulation.Excitation.Component: ...
    @property
    def Enable(self) -> bool: ...
    @Enable.setter
    def Enable(self, value: bool) -> None: ...
    @property
    def Function(self) -> CAE.Function: ...
    @Function.setter
    def Function(self, value: CAE.Function) -> None: ...
    @property
    def PhaseAngle(self) -> float: ...
    @PhaseAngle.setter
    def PhaseAngle(self, value: float) -> None: ...
    @property
    def ScalarFactor(self) -> float: ...
    @ScalarFactor.setter
    def ScalarFactor(self, value: float) -> None: ...


class FrfEvaluationSettingBuilder(CAE.ResponseSimulation.ModalResultsEvaluationSettingBuilder):
    def __init__(self) -> None: ...


class FrfEvaluationSetting(CAE.ResponseSimulation.ModalResultsEvaluationSetting):
    def __init__(self) -> None: ...


class FrequencyDefinition(TaggedObject):
    def __init__(self) -> None: ...
    def GetFrequencies(self) -> float: ...
    def SetFrequencies(self, frequencies: float) -> None: ...
    @property
    def ContributorNumber(self) -> int: ...
    @ContributorNumber.setter
    def ContributorNumber(self, value: int) -> None: ...
    @property
    def EndValue(self) -> float: ...
    @EndValue.setter
    def EndValue(self, value: float) -> None: ...
    @property
    def EvaluationType(self) -> CAE.ResponseSimulation.FrequencyDefinition.Definition: ...
    @EvaluationType.setter
    def EvaluationType(self, value: CAE.ResponseSimulation.FrequencyDefinition.Definition) -> None: ...
    @property
    def GenerateMaximumContributors(self) -> bool: ...
    @GenerateMaximumContributors.setter
    def GenerateMaximumContributors(self, value: bool) -> None: ...
    @property
    def InterpolationMethodOption(self) -> CAE.ResponseSimulation.FrequencyDefinition.InterpolationMethod: ...
    @InterpolationMethodOption.setter
    def InterpolationMethodOption(self, value: CAE.ResponseSimulation.FrequencyDefinition.InterpolationMethod) -> None: ...
    @property
    def NormalizeResults(self) -> bool: ...
    @NormalizeResults.setter
    def NormalizeResults(self, value: bool) -> None: ...
    @property
    def SpectralLine(self) -> int: ...
    @SpectralLine.setter
    def SpectralLine(self, value: int) -> None: ...
    @property
    def StartValue(self) -> float: ...
    @StartValue.setter
    def StartValue(self, value: float) -> None: ...


    class InterpolationMethod(enum.Enum):
        LogLog= 0
        LogLinear= 1
        LinearLinear= 2
    

    class Definition(enum.Enum):
        Range= 0
        ModalContribution= 1
    

class ExcitationLocationDefinition(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def ExcitationLocation(self) -> SelectObject: ...
    @ExcitationLocation.setter
    def ExcitationLocation(self, value: SelectObject) -> None: ...
    @property
    def ExcitationLocationId(self) -> int: ...
    @ExcitationLocationId.setter
    def ExcitationLocationId(self, value: int) -> None: ...
    @property
    def ExcitationLocationType(self) -> CAE.ResponseSimulation.ExcitationBuilder.ExcitationLocationType: ...
    @ExcitationLocationType.setter
    def ExcitationLocationType(self, value: CAE.ResponseSimulation.ExcitationBuilder.ExcitationLocationType) -> None: ...
    @property
    def ExcitationLocationlist(self) -> SelectTaggedObjectList: ...
    @ExcitationLocationlist.setter
    def ExcitationLocationlist(self, value: SelectTaggedObjectList) -> None: ...


class ExcitationCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.ResponseSimulation.Excitation]: ...
    @typing.overload
    def __init__(self, owner: CAE.ResponseSimulation.Manager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateTranslationalNodalFunctionExcitationBuilder(self, excitation: CAE.ResponseSimulation.TranslationalNodalFunctionExcitation) -> CAE.ResponseSimulation.TranslationalNodalFunctionExcitationBuilder: ...
    def CreateRotationalNodalFunctionExcitationBuilder(self, excitation: CAE.ResponseSimulation.RotationalNodalFunctionExcitation) -> CAE.ResponseSimulation.RotationalNodalFunctionExcitationBuilder: ...
    def CreateDistributedLoadExcitationBuilder(self, excitation: CAE.ResponseSimulation.DistributedLoadExcitation) -> CAE.ResponseSimulation.DistributedLoadExcitationBuilder: ...
    def CreateDdamExcitationBuilder(self, excitation: CAE.ResponseSimulation.DDAMExcitation) -> CAE.ResponseSimulation.DDAMExcitationBuilder: ...
    def CreateTranslationalDdamExcitationBuilder(self, excitation: CAE.ResponseSimulation.DDAMExcitation) -> CAE.ResponseSimulation.DDAMExcitationBuilder: ...
    def CreateRotationalDdamExcitationBuilder(self, excitation: CAE.ResponseSimulation.DDAMExcitation) -> CAE.ResponseSimulation.DDAMExcitationBuilder: ...
    def CreateCsdExcitationBuilder(self, excitation: CAE.ResponseSimulation.CSDExcitation) -> CAE.ResponseSimulation.CSDExcitationBuilder: ...
    def CreateVelocityImpactExcitationBuilder(self, excitation: CAE.ResponseSimulation.VelocityImpactExcitation) -> CAE.ResponseSimulation.VelocityImpactExcitationBuilder: ...
    def CreateStaticLoadExcitationBuilder(self, excitation: CAE.ResponseSimulation.StaticLoadExcitation) -> CAE.ResponseSimulation.StaticLoadExcitationBuilder: ...
    def DeleteExcitation(self, excitation: CAE.ResponseSimulation.Excitation) -> None: ...
    def FindObject(self, name: str) -> CAE.ResponseSimulation.Excitation: ...
    def Tag(self) -> Tag: ...



class ExcitationBuilder(CAE.ResponseSimulation.BaseBuilder):
    def __init__(self) -> None: ...
    @property
    def DynamicEvent(self) -> CAE.ResponseSimulation.RSEvent: ...
    @DynamicEvent.setter
    def DynamicEvent(self, value: CAE.ResponseSimulation.RSEvent) -> None: ...
    @property
    def ExcitationLocationDefinition(self) -> CAE.ResponseSimulation.ExcitationLocationDefinition: ...
    @ExcitationLocationDefinition.setter
    def ExcitationLocationDefinition(self, value: CAE.ResponseSimulation.ExcitationLocationDefinition) -> None: ...


    class ExcitationLocationType(enum.Enum):
        StaticLoad= -2
        DistributedLoad= -1
        NodalForce= 0
        EnforcedMotion= 1
    

class Excitation(NXObject):
    def __init__(self) -> None: ...
    def Destroy(self) -> None: ...
    @property
    def ExcitationName(self) -> str: ...
    @ExcitationName.setter
    def ExcitationName(self, value: str) -> None: ...


    class Component(enum.Enum):
        DistributedLoad= -1
        X= 0
        Y= 1
        Z= 2
        Rx= 3
        Ry= 4
        Rz= 5
        UserDefined= 6
    

class EvaluationSettingManager(Utilities.NXRemotableObject):
    def __init__(self, owner: CAE.ResponseSimulation.Manager) -> None: ...
    def CreateFrfEvaluationSettingBuilder(self, setting: CAE.ResponseSimulation.FrfEvaluationSetting) -> CAE.ResponseSimulation.FrfEvaluationSettingBuilder: ...
    def CreateCsdEvaluationSettingBuilder(self, setting: CAE.ResponseSimulation.CsdEvaluationSetting) -> CAE.ResponseSimulation.CsdEvaluationSettingBuilder: ...
    def CreateTransmissibilityEvaluationSettingBuilder(self, setting: CAE.ResponseSimulation.TransmissibilityEvaluationSetting) -> CAE.ResponseSimulation.TransmissibilityEvaluationSettingBuilder: ...
    def CreateNodalFunctionEvaluationSettingBuilder(self, setting: CAE.ResponseSimulation.NodalFunctionEvaluationSetting) -> CAE.ResponseSimulation.NodalFunctionEvaluationSettingBuilder: ...
    def CreateElementalFunctionEvaluationSettingBuilder(self, setting: CAE.ResponseSimulation.ElementalFunctionEvaluationSetting) -> CAE.ResponseSimulation.ElementalFunctionEvaluationSettingBuilder: ...
    def CreateResponseResultsEvaluationSettingBuilder(self, setting: CAE.ResponseSimulation.ResponseResultsEvaluationSetting) -> CAE.ResponseSimulation.ResponseResultsEvaluationSettingBuilder: ...
    def CreateStrengthResultsEvaluationSettingBuilder(self, setting: CAE.ResponseSimulation.StrengthResultsEvaluationSetting) -> CAE.ResponseSimulation.StrengthResultsEvaluationSettingBuilder: ...
    def CreatePeakValueEvaluationSettingBuilder(self, setting: CAE.ResponseSimulation.PeakValueEvaluationSetting) -> CAE.ResponseSimulation.PeakValueEvaluationSettingBuilder: ...
    def CreateRmsResultsEvaluationSettingBuilder(self, setting: CAE.ResponseSimulation.RmsResultsEvaluationSetting) -> CAE.ResponseSimulation.RmsResultsEvaluationSettingBuilder: ...
    def CreateLcrResultsEvaluationSettingBuilder(self, setting: CAE.ResponseSimulation.LcrResultsEvaluationSetting) -> CAE.ResponseSimulation.LcrResultsEvaluationSettingBuilder: ...
    def CreateStrainGageEvaluationSettingBuilder(self, setting: CAE.ResponseSimulation.StrainGageEvaluationSetting) -> CAE.ResponseSimulation.StrainGageEvaluationSettingBuilder: ...
    def CreateSensorEvaluationSettingBuilder(self, setting: CAE.ResponseSimulation.SensorEvaluationSetting) -> CAE.ResponseSimulation.SensorEvaluationSettingBuilder: ...
    def Tag(self) -> Tag: ...



class EvaluationSettingBuilder(Builder):
    def __init__(self) -> None: ...


class EvaluationSetting(NXObject):
    def __init__(self) -> None: ...
    def Destroy(self) -> None: ...


class EvaluationResultType(enum.Enum):
    Receptance= 0
    Mobility= 1
    Inertance= 2
    Displacement= 3
    Velocity= 4
    Acceleration= 5
    Stress= 6
    Strain= 7
    StrainEnergy= 8
    ShellResultant= 9
    ElementForce= 10
    BeamElementForce= 11
    ShellStressResultant= 12
    ReactionForce= 13


class EvaluationParameters(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def HypermatrixBufferSize(self) -> int: ...
    @HypermatrixBufferSize.setter
    def HypermatrixBufferSize(self, value: int) -> None: ...
    @property
    def IntegrationMethod(self) -> CAE.ResponseSimulation.EvaluationParameters.AnalysisIntegrationMethod: ...
    @IntegrationMethod.setter
    def IntegrationMethod(self, value: CAE.ResponseSimulation.EvaluationParameters.AnalysisIntegrationMethod) -> None: ...
    @property
    def MaxArraySize(self) -> int: ...
    @MaxArraySize.setter
    def MaxArraySize(self, value: int) -> None: ...
    @property
    def MinDampingStatus(self) -> bool: ...
    @MinDampingStatus.setter
    def MinDampingStatus(self, value: bool) -> None: ...
    @property
    def ZeroMeanCorrection(self) -> bool: ...
    @ZeroMeanCorrection.setter
    def ZeroMeanCorrection(self, value: bool) -> None: ...


    class AnalysisIntegrationMethod(enum.Enum):
        DuhameldIntegral= 0
        NewmarkBeta= 1
    

class ElementLocation(enum.Enum):
    Both= 0
    Centroid= 1
    Corners= 2


class ElementalFunctionEvaluationSettingBuilder(CAE.ResponseSimulation.FunctionEvaluationSettingBuilder):
    def __init__(self) -> None: ...
    def GetDestinationElements(self) -> typing.List[CAE.FEElement]: ...
    def SetDestinationElements(self, destinationElement: typing.List[CAE.FEElement]) -> None: ...
    @property
    def BeamDataLocation(self) -> CAE.ResponseSimulation.ElementalFunctionEvalBeamLocation: ...
    @BeamDataLocation.setter
    def BeamDataLocation(self, value: CAE.ResponseSimulation.ElementalFunctionEvalBeamLocation) -> None: ...
    @property
    def CoordinateSystem(self) -> CAE.ResponseSimulation.CoordinateSystem: ...
    @CoordinateSystem.setter
    def CoordinateSystem(self, value: CAE.ResponseSimulation.CoordinateSystem) -> None: ...
    @property
    def DataComponent(self) -> CAE.ResponseSimulation.DirectionDataComponent: ...
    @DataComponent.setter
    def DataComponent(self, value: CAE.ResponseSimulation.DirectionDataComponent) -> None: ...
    @property
    def ElementLocation(self) -> CAE.ResponseSimulation.ElementLocation: ...
    @ElementLocation.setter
    def ElementLocation(self, value: CAE.ResponseSimulation.ElementLocation) -> None: ...
    @property
    def ShellEvaluationLocation(self) -> CAE.ResponseSimulation.ShellElementEvaluationLocation: ...
    @ShellEvaluationLocation.setter
    def ShellEvaluationLocation(self, value: CAE.ResponseSimulation.ShellElementEvaluationLocation) -> None: ...
    @property
    def SpringForceEvaluationFromDisplacement(self) -> bool: ...
    @SpringForceEvaluationFromDisplacement.setter
    def SpringForceEvaluationFromDisplacement(self, value: bool) -> None: ...


class ElementalFunctionEvaluationSetting(CAE.ResponseSimulation.FunctionEvaluationSetting):
    def __init__(self) -> None: ...


class ElementalFunctionEvalBeamLocation(enum.Enum):
    C= 0
    D= 1
    E= 2
    F= 3


class DynamicResultEvaluationSettingBuilder(Builder):
    def __init__(self) -> None: ...
    def GetDescriptionString(self) -> str: ...
    def SetDescriptionString(self, description: str) -> None: ...
    def GetResponseResultNameString(self) -> str: ...
    def SetResponseResultNameString(self, responseResultName: str) -> None: ...


class DynamicResultEvaluationSetting(CAE.ResponseSimulation.EvaluationSetting):
    def __init__(self) -> None: ...


class DynamicEvaluationOutputSettings(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def PreviewOption(self) -> bool: ...
    @PreviewOption.setter
    def PreviewOption(self, value: bool) -> None: ...
    @property
    def RecordPrefix(self) -> str: ...
    @RecordPrefix.setter
    def RecordPrefix(self, value: str) -> None: ...


class DistributedLoadExcitationBuilder(CAE.ResponseSimulation.ExcitationBuilder):
    def __init__(self) -> None: ...
    @property
    def ExcitationFunction(self) -> CAE.ResponseSimulation.FunctionComponentData: ...
    @ExcitationFunction.setter
    def ExcitationFunction(self, value: CAE.ResponseSimulation.FunctionComponentData) -> None: ...


class DistributedLoadExcitation(CAE.ResponseSimulation.Excitation):
    def __init__(self) -> None: ...


class DirectionDataComponent(enum.Enum):
    X= 0
    Y= 1
    Z= 2
    Rx= 3
    Ry= 4
    Rz= 5
    Xx= 6
    Yy= 7
    Zz= 8
    Xy= 9
    Xz= 10
    Yz= 11
    Ax= 12
    Sy= 13
    Sz= 14
    Tx= 15
    Byy= 16
    Bz= 17
    Fxx= 18
    Fyy= 19
    Fzz= 20
    Fxy= 21
    Mx= 22
    My= 23
    Mz= 24
    Mxy= 25
    Mxz= 26
    Myz= 27
    Vx= 28
    Vy= 29
    TranslationalMagnitude= 30
    Vonmises= 31
    MaxPrincipal= 32
    MinPrincipal= 33
    MaxShear= 34
    AllNormals= 35
    AllTranslational= 36
    AllForces= 37
    AllDirections= 38
    AllDataComponents= 39
    All= 40
    AllXyPlane= 41
    Leg1= 42
    Leg2= 43
    Leg3= 44
    AllLegs= 45


class DDAMExcitationBuilder(CAE.ResponseSimulation.ExcitationBuilder):
    def __init__(self) -> None: ...
    def SetComponentStatus(self, component: CAE.ResponseSimulation.Excitation.Component, enable: bool) -> None: ...
    def GetComponentStatus(self, component: CAE.ResponseSimulation.Excitation.Component) -> bool: ...
    @property
    def LoadingType(self) -> CAE.ResponseSimulation.DDAMExcitation.LoadingType: ...
    @LoadingType.setter
    def LoadingType(self, value: CAE.ResponseSimulation.DDAMExcitation.LoadingType) -> None: ...
    @property
    def ResponseType(self) -> CAE.ResponseSimulation.DDAMExcitation.ResponseType: ...
    @ResponseType.setter
    def ResponseType(self, value: CAE.ResponseSimulation.DDAMExcitation.ResponseType) -> None: ...


class DDAMExcitation(CAE.ResponseSimulation.Excitation):
    def __init__(self) -> None: ...


    class ShipType(enum.Enum):
        Surface= 0
        Submarine= 1
    

    class ResponseType(enum.Enum):
        Elastic= 0
        ElasticPlastic= 1
    

    class MountingType(enum.Enum):
        Hull= 0
        Duck= 1
        ShellPlating= 2
    

    class LoadingType(enum.Enum):
        Vertical= 0
        Athwartship= 1
        ForeAndAft= 2
    

    class CoefficientDefinitionType(enum.Enum):
        ByFile= 0
        InputManually= 1
    

class DDAMComponentData(TaggedObject):
    def __init__(self) -> None: ...
    def GetComponentType(self) -> CAE.ResponseSimulation.Excitation.Component: ...
    def GetEnable(self) -> bool: ...
    @property
    def LoadingTypeOption(self) -> CAE.ResponseSimulation.DDAMComponentData.LoadingType: ...
    @LoadingTypeOption.setter
    def LoadingTypeOption(self, value: CAE.ResponseSimulation.DDAMComponentData.LoadingType) -> None: ...
    @property
    def ResponseTypeOption(self) -> CAE.ResponseSimulation.DDAMComponentData.ResponseType: ...
    @ResponseTypeOption.setter
    def ResponseTypeOption(self, value: CAE.ResponseSimulation.DDAMComponentData.ResponseType) -> None: ...


    class ResponseType(enum.Enum):
        Elastic= 0
        ElasticPlastic= 1
    

    class LoadingType(enum.Enum):
        Vertical= 0
        Athwartship= 1
        ForeAndAft= 2
    

class DataLocation(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def BeamLocation(self) -> CAE.ResponseSimulation.DataLocation.Beam: ...
    @BeamLocation.setter
    def BeamLocation(self, value: CAE.ResponseSimulation.DataLocation.Beam) -> None: ...
    @property
    def ElementLocation(self) -> CAE.ResponseSimulation.DataLocation.Element: ...
    @ElementLocation.setter
    def ElementLocation(self, value: CAE.ResponseSimulation.DataLocation.Element) -> None: ...
    @property
    def LayerSelection(self) -> int: ...
    @LayerSelection.setter
    def LayerSelection(self, value: int) -> None: ...
    @property
    def ShellLocation(self) -> CAE.ResponseSimulation.DataLocation.Shell: ...
    @ShellLocation.setter
    def ShellLocation(self, value: CAE.ResponseSimulation.DataLocation.Shell) -> None: ...


    class Shell(enum.Enum):
        Top= 0
        Bottom= 1
        Middle= 2
    

    class Element(enum.Enum):
        Both= 0
        Centroid= 1
        Corners= 2
    

    class Beam(enum.Enum):
        C= 0
        D= 1
        E= 2
        F= 3
    

class CSDExcitationBuilder(CAE.ResponseSimulation.ExcitationBuilder):
    def __init__(self) -> None: ...
    def GetFromFunction(self, componentType: CAE.ResponseSimulation.Excitation.Component) -> CAE.ResponseSimulation.Excitation: ...
    def SetFromFunction(self, fromExcitation: CAE.ResponseSimulation.Excitation, componentType: CAE.ResponseSimulation.Excitation.Component) -> None: ...
    def GetToFunction(self, componentType: CAE.ResponseSimulation.Excitation.Component) -> CAE.ResponseSimulation.Excitation: ...
    def SetToFunction(self, toExcitation: CAE.ResponseSimulation.Excitation, componentType: CAE.ResponseSimulation.Excitation.Component) -> None: ...
    @property
    def CorrelationType(self) -> CAE.ResponseSimulation.CSDExcitation.CorrelationType: ...
    @CorrelationType.setter
    def CorrelationType(self, value: CAE.ResponseSimulation.CSDExcitation.CorrelationType) -> None: ...
    @property
    def CorrelationValue(self) -> float: ...
    @CorrelationValue.setter
    def CorrelationValue(self, value: float) -> None: ...


class CSDExcitation(CAE.ResponseSimulation.Excitation):
    def __init__(self) -> None: ...


    class CorrelationType(enum.Enum):
        PhaseAngle= 0
        TimeDelay= 1
    

class CsdEvaluationSettingBuilder(CAE.ResponseSimulation.FunctionEvaluationSettingBuilder):
    def __init__(self) -> None: ...
    def GetResponseNodes(self) -> typing.List[CAE.FENode]: ...
    def SetResponseNodes(self, responseNode: typing.List[CAE.FENode]) -> None: ...
    def GetResponseElements(self) -> typing.List[CAE.FEElement]: ...
    def SetResponseElements(self, responseElements: typing.List[CAE.FEElement]) -> None: ...
    @property
    def ReferenceCoordinateSystem(self) -> CAE.ResponseSimulation.CoordinateSystem: ...
    @ReferenceCoordinateSystem.setter
    def ReferenceCoordinateSystem(self, value: CAE.ResponseSimulation.CoordinateSystem) -> None: ...
    @property
    def ReferenceDataLocation(self) -> CAE.ResponseSimulation.DataLocation: ...
    @ReferenceDataLocation.setter
    def ReferenceDataLocation(self, value: CAE.ResponseSimulation.DataLocation) -> None: ...
    @property
    def ReferenceElement(self) -> CAE.FEElement: ...
    @ReferenceElement.setter
    def ReferenceElement(self, value: CAE.FEElement) -> None: ...
    @property
    def ReferenceElementDataComponent(self) -> CAE.ResponseSimulation.DirectionDataComponent: ...
    @ReferenceElementDataComponent.setter
    def ReferenceElementDataComponent(self, value: CAE.ResponseSimulation.DirectionDataComponent) -> None: ...
    @property
    def ReferenceNode(self) -> CAE.FENode: ...
    @ReferenceNode.setter
    def ReferenceNode(self, value: CAE.FENode) -> None: ...
    @property
    def ReferenceNodeDataComponent(self) -> CAE.ResponseSimulation.DirectionDataComponent: ...
    @ReferenceNodeDataComponent.setter
    def ReferenceNodeDataComponent(self, value: CAE.ResponseSimulation.DirectionDataComponent) -> None: ...
    @property
    def ReferenceUserDefinedDirection(self) -> Direction: ...
    @ReferenceUserDefinedDirection.setter
    def ReferenceUserDefinedDirection(self, value: Direction) -> None: ...
    @property
    def ReferenceUsingUserDefinedDirection(self) -> CAE.ResponseSimulation.NodalFunctionEvalRequest: ...
    @ReferenceUsingUserDefinedDirection.setter
    def ReferenceUsingUserDefinedDirection(self, value: CAE.ResponseSimulation.NodalFunctionEvalRequest) -> None: ...
    @property
    def ResponseCoordinateSystem(self) -> CAE.ResponseSimulation.CoordinateSystem: ...
    @ResponseCoordinateSystem.setter
    def ResponseCoordinateSystem(self, value: CAE.ResponseSimulation.CoordinateSystem) -> None: ...
    @property
    def ResponseDataLocation(self) -> CAE.ResponseSimulation.DataLocation: ...
    @ResponseDataLocation.setter
    def ResponseDataLocation(self, value: CAE.ResponseSimulation.DataLocation) -> None: ...
    @property
    def ResponseElementDataComponent(self) -> CAE.ResponseSimulation.DirectionDataComponent: ...
    @ResponseElementDataComponent.setter
    def ResponseElementDataComponent(self, value: CAE.ResponseSimulation.DirectionDataComponent) -> None: ...
    @property
    def ResponseNodeDataComponent(self) -> CAE.ResponseSimulation.DirectionDataComponent: ...
    @ResponseNodeDataComponent.setter
    def ResponseNodeDataComponent(self, value: CAE.ResponseSimulation.DirectionDataComponent) -> None: ...
    @property
    def ResponseUserDefinedDirection(self) -> Direction: ...
    @ResponseUserDefinedDirection.setter
    def ResponseUserDefinedDirection(self, value: Direction) -> None: ...
    @property
    def ResponseUsingUserDefinedDirection(self) -> CAE.ResponseSimulation.NodalFunctionEvalRequest: ...
    @ResponseUsingUserDefinedDirection.setter
    def ResponseUsingUserDefinedDirection(self, value: CAE.ResponseSimulation.NodalFunctionEvalRequest) -> None: ...


class CsdEvaluationSetting(CAE.ResponseSimulation.FunctionEvaluationSetting):
    def __init__(self) -> None: ...


class CoordinateSystem(enum.Enum):
    Nodal= 0
    Global= 1
    Elemental= 2
    Material= 3


class CombinationEvaluationOptions(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def CombinationMethod(self) -> CAE.ResponseSimulation.CombinationEvaluationOptions.MultipleExcitationCombinationMethod: ...
    @CombinationMethod.setter
    def CombinationMethod(self, value: CAE.ResponseSimulation.CombinationEvaluationOptions.MultipleExcitationCombinationMethod) -> None: ...
    @property
    def EvaluationMethodOption(self) -> CAE.ResponseSimulation.CombinationEvaluationOptions.EvaluationMethod: ...
    @EvaluationMethodOption.setter
    def EvaluationMethodOption(self, value: CAE.ResponseSimulation.CombinationEvaluationOptions.EvaluationMethod) -> None: ...
    @property
    def NeighboringFactor(self) -> float: ...
    @NeighboringFactor.setter
    def NeighboringFactor(self, value: float) -> None: ...
    @property
    def TimeDuration(self) -> float: ...
    @TimeDuration.setter
    def TimeDuration(self, value: float) -> None: ...


    class MultipleExcitationCombinationMethod(enum.Enum):
        Abs= 0
        Srs= 1
    

    class EvaluationMethod(enum.Enum):
        Abs= 0
        Srss= 1
        Nrl= 2
        Cqc= 3
        NqcDoubleSum= 4
    

class BaseBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def ObjectLabel(self) -> CAE.ResponseSimulation.ObjectLabel: ...
    @ObjectLabel.setter
    def ObjectLabel(self, value: CAE.ResponseSimulation.ObjectLabel) -> None: ...


