from ...NXOpen import *

import typing
import enum

class XmlComparator(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def CompareXmlFiles(self, workXmlFile: str, masterXmlFile: str, compareOptions: Validate.XmlComparator.Options) -> Validate.XmlComparator.Result: ...
    def Tag(self) -> Tag: ...



    class Result(enum.Enum):
        Identical= 0
        Different= 1
    

    class XmlComparatorOptions():
        @property
        def FilterFile(self) -> str: ...
        @FilterFile.setter
        def FilterFile(self, value: str) -> None: ...
        @property
        def ReportFile(self) -> str: ...
        @ReportFile.setter
        def ReportFile(self, value: str) -> None: ...
        @property
        def LogFile(self) -> str: ...
        @LogFile.setter
        def LogFile(self, value: str) -> None: ...
        @property
        def IgnoreNamespaces(self) -> bool: ...
        @IgnoreNamespaces.setter
        def IgnoreNamespaces(self, value: bool) -> None: ...
        @property
        def IgnoreUnmatchedNodes(self) -> bool: ...
        @IgnoreUnmatchedNodes.setter
        def IgnoreUnmatchedNodes(self, value: bool) -> None: ...
        @property
        def IgnoreComments(self) -> bool: ...
        @IgnoreComments.setter
        def IgnoreComments(self, value: bool) -> None: ...
        @property
        def IgnoreCdata(self) -> bool: ...
        @IgnoreCdata.setter
        def IgnoreCdata(self, value: bool) -> None: ...
        @property
        def IgnorePI(self) -> bool: ...
        @IgnorePI.setter
        def IgnorePI(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
    

    class XmlComparator_Options():
        @property
        def filterFile(self) -> int: ...
        @filterFile.setter
        def filterFile(self, value: int) -> None: ...
        @property
        def reportFile(self) -> int: ...
        @reportFile.setter
        def reportFile(self, value: int) -> None: ...
        @property
        def logFile(self) -> int: ...
        @logFile.setter
        def logFile(self, value: int) -> None: ...
        @property
        def ignoreNamespaces(self) -> bool: ...
        @ignoreNamespaces.setter
        def ignoreNamespaces(self, value: bool) -> None: ...
        @property
        def ignoreUnmatchedNodes(self) -> bool: ...
        @ignoreUnmatchedNodes.setter
        def ignoreUnmatchedNodes(self, value: bool) -> None: ...
        @property
        def ignoreComments(self) -> bool: ...
        @ignoreComments.setter
        def ignoreComments(self, value: bool) -> None: ...
        @property
        def ignoreCdata(self) -> bool: ...
        @ignoreCdata.setter
        def ignoreCdata(self, value: bool) -> None: ...
        @property
        def ignorePI(self) -> bool: ...
        @ignorePI.setter
        def ignorePI(self, value: bool) -> None: ...
    

class ValidatorOptions(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def AutoDisplayResults(self) -> Validate.ValidatorOptions.ResultsDisplayModeTypes: ...
    @AutoDisplayResults.setter
    def AutoDisplayResults(self, value: Validate.ValidatorOptions.ResultsDisplayModeTypes) -> None: ...
    @property
    def ExcludeNonOwnerParts(self) -> bool: ...
    @ExcludeNonOwnerParts.setter
    def ExcludeNonOwnerParts(self, value: bool) -> None: ...
    @property
    def ExcludeReadonlyParts(self) -> bool: ...
    @ExcludeReadonlyParts.setter
    def ExcludeReadonlyParts(self, value: bool) -> None: ...
    @property
    def GenerateCheckFlag(self) -> bool: ...
    @GenerateCheckFlag.setter
    def GenerateCheckFlag(self, value: bool) -> None: ...
    @property
    def GenerateLogFile(self) -> bool: ...
    @GenerateLogFile.setter
    def GenerateLogFile(self, value: bool) -> None: ...
    @property
    def LogFileDirectory(self) -> str: ...
    @LogFileDirectory.setter
    def LogFileDirectory(self, value: str) -> None: ...
    @property
    def LogFileMode(self) -> Validate.ValidatorOptions.LogModeTypes: ...
    @LogFileMode.setter
    def LogFileMode(self, value: Validate.ValidatorOptions.LogModeTypes) -> None: ...
    @property
    def ResultsAutoUpdate(self) -> bool: ...
    @ResultsAutoUpdate.setter
    def ResultsAutoUpdate(self, value: bool) -> None: ...
    @property
    def SavePartFile(self) -> Validate.ValidatorOptions.SaveModeTypes: ...
    @SavePartFile.setter
    def SavePartFile(self, value: Validate.ValidatorOptions.SaveModeTypes) -> None: ...
    @property
    def SaveResultInPart(self) -> bool: ...
    @SaveResultInPart.setter
    def SaveResultInPart(self, value: bool) -> None: ...
    @property
    def SaveResultInTeamcenter(self) -> Validate.ValidatorOptions.SaveModeTypes: ...
    @SaveResultInTeamcenter.setter
    def SaveResultInTeamcenter(self, value: Validate.ValidatorOptions.SaveModeTypes) -> None: ...
    @property
    def SkipChecking(self) -> bool: ...
    @SkipChecking.setter
    def SkipChecking(self, value: bool) -> None: ...
    @property
    def SkipCheckingDontLoadPart(self) -> bool: ...
    @SkipCheckingDontLoadPart.setter
    def SkipCheckingDontLoadPart(self, value: bool) -> None: ...
    @property
    def SkipOverriddenResultOption(self) -> bool: ...
    @SkipOverriddenResultOption.setter
    def SkipOverriddenResultOption(self, value: bool) -> None: ...
    @property
    def StopOnError(self) -> bool: ...
    @StopOnError.setter
    def StopOnError(self, value: bool) -> None: ...
    @property
    def StopOnWarning(self) -> bool: ...
    @StopOnWarning.setter
    def StopOnWarning(self, value: bool) -> None: ...
    @property
    def TreatWarningAsFail(self) -> bool: ...
    @TreatWarningAsFail.setter
    def TreatWarningAsFail(self, value: bool) -> None: ...


    class SaveModeTypes(enum.Enum):
        DoNotSave= 0
        SaveIfPassed= 1
        AlwaysSave= 2
    

    class ResultsDisplayModeTypes(enum.Enum):
        AlwaysDisplay= 0
        DisplayIfNotPass= 1
        DoNotDisplay= 2
    

    class LogModeTypes(enum.Enum):
        LogPerSession= 0
        LogPerPart= 1
    

class Validator(TaggedObject):
    def __init__(self) -> None: ...
    def Commit(self) -> Validation.Result: ...
    def GetLastErrorListFromCommit(self) -> ErrorList: ...
    @typing.overload
    def AppendPartNode(self, fileName: str) -> None: ...
    @typing.overload
    def AppendPartNode(self, partObject: Part) -> None: ...
    @typing.overload
    def AppendPartNodes(self, fileNames: str) -> None: ...
    @typing.overload
    def AppendPartNodes(self, partObject: typing.List[Part]) -> None: ...
    def ErasePartNode(self, index: int) -> None: ...
    def ClearPartNodes(self) -> None: ...
    def FindPartNode(self, index: int) -> Validate.PartNode: ...
    def GetPartNodes(self, partNodes: typing.List[Validate.PartNode]) -> None: ...
    def AppendCheckerNode(self, className: str) -> None: ...
    def AppendCheckerNodes(self, classNames: str) -> None: ...
    def EraseCheckerNode(self, delNdx: int) -> None: ...
    def ClearCheckerNodes(self) -> None: ...
    def FindCheckerNode(self, index: int) -> Validate.CheckerNode: ...
    def GetCheckerNodes(self, checkerNode: typing.List[Validate.CheckerNode]) -> None: ...
    @property
    def ValidatorOptions(self) -> Validate.ValidatorOptions: ...
    @ValidatorOptions.setter
    def ValidatorOptions(self, value: Validate.ValidatorOptions) -> None: ...


class ValidationManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def CreateValidator(self, name: str) -> Validate.Validator: ...
    def CreateParser(self, name: str) -> Validate.Parser: ...
    def FindValidator(self, name: str, validators: typing.List[Validate.Validator]) -> None: ...
    def DeleteValidator(self, validator: Validate.Validator) -> None: ...
    def DeleteParser(self, parser: Validate.Parser) -> None: ...
    def FindParser(self, name: str, parsers: typing.List[Validate.Parser]) -> None: ...
    @typing.overload
    def DefineParameter(self, parameterID: str, parameterValue: int, options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    @typing.overload
    def DefineParameter(self, parameterID: str, parameterValue: int, options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    @typing.overload
    def DefineParameter(self, parameterID: str, parameterValue: bool, options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    @typing.overload
    def DefineParameter(self, parameterID: str, parameterValue: bool, options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    @typing.overload
    def DefineParameter(self, parameterID: str, parameterValue: float, options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    @typing.overload
    def DefineParameter(self, parameterID: str, parameterValue: float, options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    @typing.overload
    def DefineParameter(self, parameterID: str, parameterValue: str, options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    @typing.overload
    def DefineParameter(self, parameterID: str, parameterValue: str, options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    @typing.overload
    def DefineParameter(self, parameterID: str, parameterValue: Point3d, options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    @typing.overload
    def DefineParameter(self, parameterID: str, parameterValue: typing.List[Point3d], options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    @typing.overload
    def DefineParameter(self, parameterID: str, parameterValue: Vector3d, options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    @typing.overload
    def DefineParameter(self, parameterID: str, parameterValue: typing.List[Vector3d], options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    def DefineNXObjectParameter(self, parameterID: str, parameterValue: NXObject, options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    def DefineNXObjectParameters(self, parameterID: str, parameterValue: typing.List[NXObject], options: Validate.ValidationManager.ParameterOptions) -> Validate.Parameter: ...
    def CreateCheckerDefinition(self, classID: str, displayName: str, category: str, parameters: typing.List[Validate.Parameter], doCheck: Validate.ValidationManager.DoCheckHandler) -> Validate.CheckerDefinition: ...
    def DeleteCheckerDefinition(self, checkerDefinition: Validate.CheckerDefinition) -> None: ...
    def Tag(self) -> Tag: ...



    class ValidationManagerParameterOptions():
        @property
        def Label(self) -> str: ...
        @Label.setter
        def Label(self, value: str) -> None: ...
        @property
        def Group(self) -> str: ...
        @Group.setter
        def Group(self, value: str) -> None: ...
        @property
        def Modifiable(self) -> bool: ...
        @Modifiable.setter
        def Modifiable(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, Label: str, Group: str, Modifiable: bool) -> None: ...
    

    

    

    class ValidationManager_ParameterOptions():
        @property
        def label(self) -> int: ...
        @label.setter
        def label(self, value: int) -> None: ...
        @property
        def group(self) -> int: ...
        @group.setter
        def group(self, value: int) -> None: ...
        @property
        def modifiable(self) -> bool: ...
        @modifiable.setter
        def modifiable(self, value: bool) -> None: ...
    

    

class SelectionAndPlacementBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def GetTargets(self) -> typing.List[TaggedObject]: ...
    def SetTargets(self, targets: typing.List[TaggedObject]) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def DrawOrientation(self) -> Matrix3x3: ...
    @DrawOrientation.setter
    def DrawOrientation(self, value: Matrix3x3) -> None: ...
    @property
    def DrawOrigin(self) -> Point3d: ...
    @DrawOrigin.setter
    def DrawOrigin(self, value: Point3d) -> None: ...


class ResultObject(NXObject):
    def __init__(self) -> None: ...
    def CreateOverrideBuilder(self, overrideRequest: Validate.Override) -> Validate.OverrideBuilder: ...
    def DeleteOverride(self) -> None: ...
    def AskAttribute(self, name: str) -> NXObject.AttributeInformation: ...
    def AskAttributes(self, name: str, attributes: typing.List[NXObject.AttributeInformation]) -> None: ...
    @property
    def CategoryName(self) -> str: ...
    @CategoryName.setter
    def CategoryName(self, value: str) -> None: ...
    @property
    def ClassName(self) -> str: ...
    @ClassName.setter
    def ClassName(self, value: str) -> None: ...
    @property
    def Disabled(self) -> bool: ...
    @Disabled.setter
    def Disabled(self, value: bool) -> None: ...
    @property
    def Object(self) -> NXObject: ...
    @Object.setter
    def Object(self, value: NXObject) -> None: ...
    @property
    def OutOfDate(self) -> bool: ...
    @OutOfDate.setter
    def OutOfDate(self, value: bool) -> None: ...
    @property
    def Override(self) -> Validate.Override: ...
    @Override.setter
    def Override(self, value: Validate.Override) -> None: ...
    @property
    def Status(self) -> Validation.Result: ...
    @Status.setter
    def Status(self, value: Validation.Result) -> None: ...
    @property
    def TotalObjectsCount(self) -> int: ...
    @TotalObjectsCount.setter
    def TotalObjectsCount(self, value: int) -> None: ...
    @property
    def Type(self) -> Validate.ResultObject.ResultTypes: ...
    @Type.setter
    def Type(self, value: Validate.ResultObject.ResultTypes) -> None: ...


    class ResultTypes(enum.Enum):
        Part= 0
        Profile= 1
        Test= 2
        Object= 3
        ObjectSet= 4
    

class RequirementCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Validate.Requirement]: ...
    @typing.overload
    def __init__(self, owner: BasePart) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateRequirementBuilder(self, requirement: Validate.Requirement) -> Validate.RequirementBuilder: ...
    def FindObject(self, id: str) -> Validate.Requirement: ...
    def LoadFromExternalSource(self, sourceType: Validate.RequirementCollection.SourceTypeOptions, source: str, revision: str, project: str) -> None: ...
    def RefreshFromExternalSource(self, requirementTags: typing.List[Validate.Requirement]) -> None: ...
    def Tag(self) -> Tag: ...

    @property
    def RevisionRule(self) -> str: ...
    @RevisionRule.setter
    def RevisionRule(self, value: str) -> None: ...


    class SourceTypeOptions(enum.Enum):
        LocalFile= 0
        TeamcenterFile= 1
        Teamcenter= 2
        MeasurableAttribute= 3
    

class RequirementCheckCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Validate.RequirementCheck]: ...
    @typing.overload
    def __init__(self, owner: BasePart) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateRequirementCheck(self) -> Validate.RequirementCheck: ...
    def Tag(self) -> Tag: ...



class RequirementCheck(Validation):
    def __init__(self) -> None: ...
    def SetFormula(self, formula: str) -> None: ...
    @property
    def CheckName(self) -> str: ...
    @CheckName.setter
    def CheckName(self, value: str) -> None: ...
    @property
    def Formula(self) -> str: ...
    @Formula.setter
    def Formula(self, value: str) -> None: ...
    @property
    def ParentRequirement(self) -> Validate.Requirement: ...
    @ParentRequirement.setter
    def ParentRequirement(self, value: Validate.Requirement) -> None: ...
    @property
    def SaveResultsToTeamcenterOption(self) -> Validate.RequirementCheck.SaveResultsToTeamcenterOptions: ...
    @SaveResultsToTeamcenterOption.setter
    def SaveResultsToTeamcenterOption(self, value: Validate.RequirementCheck.SaveResultsToTeamcenterOptions) -> None: ...


    class SaveResultsToTeamcenterOptions(enum.Enum):
        DoNotSave= 0
        SaveIfPassed= 1
        AlwaysSave= 2
    

class RequirementBuilder(Builder):
    def __init__(self) -> None: ...
    def GetValidValues(self) -> str: ...
    def SetValidValues(self, validValues: str) -> None: ...
    def GetRequirementDescription(self) -> str: ...
    def SetRequirementDescription(self, requirementDescription: str) -> None: ...
    @property
    def DataTypeOption(self) -> Validate.RequirementBuilder.DataTypeOptions: ...
    @DataTypeOption.setter
    def DataTypeOption(self, value: Validate.RequirementBuilder.DataTypeOptions) -> None: ...
    @property
    def DefinitionMethodOption(self) -> Validate.RequirementBuilder.DefinitionMethodOptions: ...
    @DefinitionMethodOption.setter
    def DefinitionMethodOption(self, value: Validate.RequirementBuilder.DefinitionMethodOptions) -> None: ...
    @property
    def DoubleSidedMaximumValue(self) -> str: ...
    @DoubleSidedMaximumValue.setter
    def DoubleSidedMaximumValue(self, value: str) -> None: ...
    @property
    def DoubleSidedMinimumValue(self) -> str: ...
    @DoubleSidedMinimumValue.setter
    def DoubleSidedMinimumValue(self, value: str) -> None: ...
    @property
    def Formula(self) -> str: ...
    @Formula.setter
    def Formula(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def RelationalOperatorOption(self) -> Validate.RequirementBuilder.RelationalOperatorOptions: ...
    @RelationalOperatorOption.setter
    def RelationalOperatorOption(self, value: Validate.RequirementBuilder.RelationalOperatorOptions) -> None: ...
    @property
    def RelationalOperatorOptionOnMaximumValue(self) -> Validate.RequirementBuilder.RelationalOperatorOptions: ...
    @RelationalOperatorOptionOnMaximumValue.setter
    def RelationalOperatorOptionOnMaximumValue(self, value: Validate.RequirementBuilder.RelationalOperatorOptions) -> None: ...
    @property
    def RelationalOperatorOptionOnMinimumValue(self) -> Validate.RequirementBuilder.RelationalOperatorOptions: ...
    @RelationalOperatorOptionOnMinimumValue.setter
    def RelationalOperatorOptionOnMinimumValue(self, value: Validate.RequirementBuilder.RelationalOperatorOptions) -> None: ...
    @property
    def RequirementTolerance(self) -> float: ...
    @RequirementTolerance.setter
    def RequirementTolerance(self, value: float) -> None: ...
    @property
    def RequirementTypeOption(self) -> Validate.RequirementBuilder.RequirementTypeOptions: ...
    @RequirementTypeOption.setter
    def RequirementTypeOption(self, value: Validate.RequirementBuilder.RequirementTypeOptions) -> None: ...
    @property
    def SeverityOption(self) -> Validate.RequirementBuilder.SeverityOptions: ...
    @SeverityOption.setter
    def SeverityOption(self, value: Validate.RequirementBuilder.SeverityOptions) -> None: ...
    @property
    def SingleSidedValue(self) -> str: ...
    @SingleSidedValue.setter
    def SingleSidedValue(self, value: str) -> None: ...


    class SeverityOptions(enum.Enum):
        Error= 0
        Warning= 1
        Information= 2
    

    class RequirementTypeOptions(enum.Enum):
        ValidationLimit= 0
        DesignLimit= 1
    

    class RelationalOperatorOptions(enum.Enum):
        Equal= 0
        NotEqual= 1
        LessThan= 2
        LessThanOrEqual= 3
        GreaterThan= 4
        GreaterThanOrEqual= 5
    

    class DefinitionMethodOptions(enum.Enum):
        SingleSidedComparison= 0
        DoubleSidedComparison= 1
        SetOfValues= 2
        Formula= 3
    

    class DataTypeOptions(enum.Enum):
        Number= 0
        String= 1
        Boolean= 2
        Integer= 3
        Point= 4
    

class Requirement(NXObject):
    def __init__(self) -> None: ...
    def NewCheck(self, name: str, formula: str) -> Validate.RequirementCheck: ...
    def Delete(self) -> None: ...
    def RefreshFromExternalSource(self) -> None: ...


class PorosityAnalysisResult(Validate.AnalysisResult):
    def __init__(self) -> None: ...


class PersistentResultCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Validate.PersistentResult]: ...
    @typing.overload
    def __init__(self, owner: BasePart) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def Tag(self) -> Tag: ...



class PersistentResult(NXObject):
    def __init__(self) -> None: ...
    def AddTrackingObjects(self, key: str, objects: typing.List[TaggedObject]) -> None: ...
    def GetTrackingObjects(self, key: str) -> typing.List[TaggedObject]: ...
    @property
    def CheckerClassId(self) -> str: ...
    @CheckerClassId.setter
    def CheckerClassId(self, value: str) -> None: ...
    @property
    def ErrorLevel(self) -> Validation.Result: ...
    @ErrorLevel.setter
    def ErrorLevel(self, value: Validation.Result) -> None: ...
    @property
    def UpToDateStatus(self) -> bool: ...
    @UpToDateStatus.setter
    def UpToDateStatus(self, value: bool) -> None: ...


class PBFPrintTimeParameter(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def HatchSpacing(self) -> Expression: ...
    @HatchSpacing.setter
    def HatchSpacing(self, value: Expression) -> None: ...
    @property
    def IslandLength(self) -> Expression: ...
    @IslandLength.setter
    def IslandLength(self, value: Expression) -> None: ...
    @property
    def LayerThickness(self) -> Expression: ...
    @LayerThickness.setter
    def LayerThickness(self, value: Expression) -> None: ...
    @property
    def RecoatingTime(self) -> Expression: ...
    @RecoatingTime.setter
    def RecoatingTime(self, value: Expression) -> None: ...
    @property
    def SkyWritingTime(self) -> Expression: ...
    @SkyWritingTime.setter
    def SkyWritingTime(self, value: Expression) -> None: ...
    @property
    def TravelSpeed(self) -> Expression: ...
    @TravelSpeed.setter
    def TravelSpeed(self, value: Expression) -> None: ...


class PartOrientationAnalysisResult(Validate.AnalysisResult):
    def __init__(self) -> None: ...
    def GetNumOfOptimumOrientations(self) -> int: ...
    def GetOptimumOrientation(self, optimumOrientationIndex: int, origin: Point3d, orientation: Vector3d, checkerValues: typing.List[Validate.PartOrientationAnalysisResult.CheckerValues]) -> None: ...
    def GetMinimumOrientation(self, checkerIndex: Validate.PartOrientationAnalysisResult.CheckerIndex, origin: Point3d, orientation: Vector3d, checkerValues: typing.List[Validate.PartOrientationAnalysisResult.CheckerValues]) -> None: ...


    class PartOrientationAnalysisResultCheckerValues():
        @property
        def MCheckerIndex(self) -> Validate.PartOrientationAnalysisResult.CheckerIndex: ...
        @MCheckerIndex.setter
        def MCheckerIndex(self, value: Validate.PartOrientationAnalysisResult.CheckerIndex) -> None: ...
        @property
        def MCheckerMinValue(self) -> float: ...
        @MCheckerMinValue.setter
        def MCheckerMinValue(self, value: float) -> None: ...
        @property
        def MCheckerValue(self) -> float: ...
        @MCheckerValue.setter
        def MCheckerValue(self, value: float) -> None: ...
        @property
        def MCheckerMaxValue(self) -> float: ...
        @MCheckerMaxValue.setter
        def MCheckerMaxValue(self, value: float) -> None: ...
        def ToString(self) -> str: ...
    

    class CheckerIndex(enum.Enum):
        Minimum= 0
        SurfaceArea= 0
        SupportVolume= 1
        PrintTime= 2
        Overheat= 3
        Maximum= 4
    

class PartNode(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...
    @property
    def PartObject(self) -> Part: ...
    @PartObject.setter
    def PartObject(self, value: Part) -> None: ...


class Parser(TaggedObject):
    def __init__(self) -> None: ...
    def Commit(self) -> None: ...
    def GetPartResultObjects(self, partResultObject: typing.List[Validate.ResultObject]) -> None: ...
    @typing.overload
    def GetProfileResultObjects(self, profileResultObject: typing.List[Validate.ResultObject]) -> None: ...
    @typing.overload
    def GetProfileResultObjects(self, resultObject: Validate.ResultObject, profileResultObject: typing.List[Validate.ResultObject]) -> None: ...
    @typing.overload
    def GetTestResultObjects(self, testResultObject: typing.List[Validate.ResultObject]) -> None: ...
    @typing.overload
    def GetTestResultObjects(self, resultObject: Validate.ResultObject, testResultObject: typing.List[Validate.ResultObject]) -> None: ...
    def GetObjectSetResultObjects(self, resultObject: Validate.ResultObject, objectSetResultObject: typing.List[Validate.ResultObject]) -> None: ...
    def GetObjectResultObjects(self, resultObject: Validate.ResultObject, objectResultObject: typing.List[Validate.ResultObject]) -> None: ...
    def DeleteResultObject(self, resultObject: Validate.ResultObject) -> ErrorList: ...
    def DeleteResult(self, resultObject: Validate.ResultObject) -> int: ...
    def ClearResultObjects(self) -> None: ...
    @property
    def DataSource(self) -> Validate.Parser.DataSourceTypes: ...
    @DataSource.setter
    def DataSource(self, value: Validate.Parser.DataSourceTypes) -> None: ...
    @property
    def MaxDisplayObjects(self) -> int: ...
    @MaxDisplayObjects.setter
    def MaxDisplayObjects(self, value: int) -> None: ...


    class DataSourceTypes(enum.Enum):
        MostRecentRun= 0
        ResultFromPart= 1
        ResultFromTeamcenter= 2
        ResultFromNXChecks= 3
        ResultFromLogFile= 4
    

class Parameter(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def IsList(self) -> bool: ...
    def GetBooleanValue(self) -> bool: ...
    def GetBooleanValues(self) -> bool: ...
    def SetBooleanValue(self, data: bool) -> None: ...
    def SetBooleanValues(self, data: bool) -> None: ...
    def GetIntValue(self) -> int: ...
    def GetIntValues(self) -> int: ...
    def SetIntValue(self, data: int) -> None: ...
    def SetIntValues(self, data: int) -> None: ...
    def GetDoubleValue(self) -> float: ...
    def GetDoubleValues(self) -> float: ...
    def SetDoubleValue(self, data: float) -> None: ...
    def SetDoubleValues(self, data: float) -> None: ...
    def GetStringValue(self) -> str: ...
    def GetStringValues(self) -> str: ...
    def SetStringValue(self, data: str) -> None: ...
    def SetStringValues(self, data: str) -> None: ...
    def GetPoint3dValue(self) -> Point3d: ...
    def GetPoint3dValues(self) -> typing.List[Point3d]: ...
    def SetPoint3dValue(self, data: Point3d) -> None: ...
    def SetPoint3dValues(self, data: typing.List[Point3d]) -> None: ...
    def GetVector3dValue(self) -> Vector3d: ...
    def GetVector3dValues(self) -> typing.List[Vector3d]: ...
    def SetVector3dValue(self, data: Vector3d) -> None: ...
    def SetVector3dValues(self, data: typing.List[Vector3d]) -> None: ...
    def GetNXObjectValue(self) -> NXObject: ...
    def GetNXObjectValues(self) -> typing.List[NXObject]: ...
    def SetNXObjectValue(self, data: NXObject) -> None: ...
    def SetNXObjectValues(self, data: typing.List[NXObject]) -> None: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> None: ...
    @property
    def Type(self) -> RuleManager.RuleType: ...
    @Type.setter
    def Type(self, value: RuleManager.RuleType) -> None: ...


class OverrideBuilder(Builder):
    def __init__(self) -> None: ...
    def GetDetailReason(self) -> str: ...
    def SetDetailReason(self, detailReason: str) -> None: ...
    def GetDecisionComments(self) -> str: ...
    def SetDecisionComments(self, decisionComments: str) -> None: ...
    @property
    def Category(self) -> str: ...
    @Category.setter
    def Category(self, value: str) -> None: ...
    @property
    def DecisionAction(self) -> Validate.OverrideBuilder.DecisionActions: ...
    @DecisionAction.setter
    def DecisionAction(self, value: Validate.OverrideBuilder.DecisionActions) -> None: ...
    @property
    def DecisionUser(self) -> str: ...
    @DecisionUser.setter
    def DecisionUser(self, value: str) -> None: ...
    @property
    def Reason(self) -> str: ...
    @Reason.setter
    def Reason(self, value: str) -> None: ...
    @property
    def RequestType(self) -> Validate.OverrideBuilder.RequestTypes: ...
    @RequestType.setter
    def RequestType(self, value: Validate.OverrideBuilder.RequestTypes) -> None: ...
    @property
    def ToState(self) -> Validate.OverrideBuilder.ToStates: ...
    @ToState.setter
    def ToState(self, value: Validate.OverrideBuilder.ToStates) -> None: ...


    class ToStates(enum.Enum):
        Passed= 0
        Failed= 1
    

    class RequestTypes(enum.Enum):
        Permanent= 0
        Temporary= 1
    

    class DecisionActions(enum.Enum):
        Approved= 0
        Rejected= 1
        Pending= 2
    

class Override(NXObject):
    def __init__(self) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MJFPrintTimeParameter(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def LayerPrintTime(self) -> Expression: ...
    @LayerPrintTime.setter
    def LayerPrintTime(self, value: Expression) -> None: ...
    @property
    def LayerThickness(self) -> Expression: ...
    @LayerThickness.setter
    def LayerThickness(self, value: Expression) -> None: ...


class Logger(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def LogResult(self, result: Validation.Result, message: str) -> None: ...
    @typing.overload
    def LogNXObject(self, result: Validation.Result, anObject: NXObject) -> None: ...
    @typing.overload
    def LogNXObject(self, result: Validation.Result, anObject: NXObject, message: str) -> None: ...
    @typing.overload
    def LogNXObject(self, result: Validation.Result, anObject: NXObject, message: str, objectName: str, referencePoints: typing.List[Point3d], referenceVectors: typing.List[Vector3d]) -> None: ...
    def LogNXObjectSet(self, name: str, message: str) -> Validate.Logger: ...
    def LogBooleanAttribute(self, title: str, booleanValue: bool) -> None: ...
    def LogIntegerAttribute(self, title: str, integerValue: int) -> None: ...
    def LogRealAttribute(self, title: str, realValue: float) -> None: ...
    def LogStringAttribute(self, title: str, stringValue: str) -> None: ...
    def LogBooleanAttributes(self, title: str, attrs: bool) -> None: ...
    def LogIntegerAttributes(self, title: str, attrs: int) -> None: ...
    def LogRealAttributes(self, title: str, attrs: float) -> None: ...
    def LogStringAttributes(self, title: str, attrs: str) -> None: ...


class LinkedParameterReqDialogBuilder(Builder):
    def __init__(self) -> None: ...
    def AppendMeasurableAttribute(self, logicalItemId: str, logicalItemRevId: str, mesAttrName: str, mesAttrRevId: str) -> None: ...


class KeyPerformanceInterfaceCollection(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetKeyPerformanceInterfaceCollection(self, owner: Session) -> Validate.KeyPerformanceInterfaceCollection: ...
    def CreateLinkedParameterRequirementsBuilder(self, part: Part) -> Validate.LinkedParameterReqDialogBuilder: ...
    def RefreshLinkedParameterRequirements(self, part: Part, requirementTags: typing.List[Validate.Requirement], refreshToLatest: bool) -> None: ...
    def Tag(self) -> Tag: ...



class FDMPrintTimeParameter(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def LayerThickness(self) -> Expression: ...
    @LayerThickness.setter
    def LayerThickness(self, value: Expression) -> None: ...
    @property
    def NozzleDiameter(self) -> Expression: ...
    @NozzleDiameter.setter
    def NozzleDiameter(self, value: Expression) -> None: ...
    @property
    def TravelSpeed(self) -> Expression: ...
    @TravelSpeed.setter
    def TravelSpeed(self, value: Expression) -> None: ...


class CheckWhollyEnclosedVolumeBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AutomaticUpdate(self) -> bool: ...
    @AutomaticUpdate.setter
    def AutomaticUpdate(self, value: bool) -> None: ...
    @property
    def DisplayResolutionBuilder(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @DisplayResolutionBuilder.setter
    def DisplayResolutionBuilder(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def PreviewState(self) -> bool: ...
    @PreviewState.setter
    def PreviewState(self, value: bool) -> None: ...
    @property
    def SelectionAndPlacement(self) -> Validate.SelectionAndPlacementBuilder: ...
    @SelectionAndPlacement.setter
    def SelectionAndPlacement(self, value: Validate.SelectionAndPlacementBuilder) -> None: ...
    @property
    def WhollyEnclosedVolumeColor(self) -> NXColor: ...
    @WhollyEnclosedVolumeColor.setter
    def WhollyEnclosedVolumeColor(self, value: NXColor) -> None: ...


class CheckTrappedSupportsBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Angle(self) -> float: ...
    @Angle.setter
    def Angle(self, value: float) -> None: ...
    @property
    def AutomaticUpdate(self) -> bool: ...
    @AutomaticUpdate.setter
    def AutomaticUpdate(self, value: bool) -> None: ...
    @property
    def DisplayResolutionBuilder(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @DisplayResolutionBuilder.setter
    def DisplayResolutionBuilder(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def NonTrappedSupportAreasColor(self) -> NXColor: ...
    @NonTrappedSupportAreasColor.setter
    def NonTrappedSupportAreasColor(self, value: NXColor) -> None: ...
    @property
    def PreviewState(self) -> bool: ...
    @PreviewState.setter
    def PreviewState(self, value: bool) -> None: ...
    @property
    def SelectionAndPlacement(self) -> Validate.SelectionAndPlacementBuilder: ...
    @SelectionAndPlacement.setter
    def SelectionAndPlacement(self, value: Validate.SelectionAndPlacementBuilder) -> None: ...
    @property
    def ShowOnlyFailArea(self) -> bool: ...
    @ShowOnlyFailArea.setter
    def ShowOnlyFailArea(self, value: bool) -> None: ...
    @property
    def TrappedArea(self) -> float: ...
    @TrappedArea.setter
    def TrappedArea(self, value: float) -> None: ...
    @property
    def TrappedSupportAreasColor(self) -> NXColor: ...
    @TrappedSupportAreasColor.setter
    def TrappedSupportAreasColor(self, value: NXColor) -> None: ...


class CheckThermalDistortionBuilder(Builder):
    def __init__(self) -> None: ...
    def Update(self) -> None: ...
    def CheckJobStatus(self) -> None: ...
    def CreatePrintCsys(self) -> None: ...
    def OrientPartToMinimumThermalDistortion(self) -> None: ...
    @property
    def BuildPlateTemperature(self) -> Expression: ...
    @BuildPlateTemperature.setter
    def BuildPlateTemperature(self, value: Expression) -> None: ...
    @property
    def BuildPlateThickness(self) -> Expression: ...
    @BuildPlateThickness.setter
    def BuildPlateThickness(self, value: Expression) -> None: ...
    @property
    def CheckerCreationTime(self) -> str: ...
    @CheckerCreationTime.setter
    def CheckerCreationTime(self, value: str) -> None: ...
    @property
    def CriticalAngle(self) -> Expression: ...
    @CriticalAngle.setter
    def CriticalAngle(self, value: Expression) -> None: ...
    @property
    def DisplayResolutionBuilder(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @DisplayResolutionBuilder.setter
    def DisplayResolutionBuilder(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def ElementSize(self) -> Expression: ...
    @ElementSize.setter
    def ElementSize(self, value: Expression) -> None: ...
    @property
    def FilePathKey(self) -> str: ...
    @FilePathKey.setter
    def FilePathKey(self, value: str) -> None: ...
    @property
    def JobID(self) -> str: ...
    @JobID.setter
    def JobID(self, value: str) -> None: ...
    @property
    def JobStatus(self) -> Validate.CheckThermalDistortionBuilder.JobStatusType: ...
    @JobStatus.setter
    def JobStatus(self, value: Validate.CheckThermalDistortionBuilder.JobStatusType) -> None: ...
    @property
    def LayerThickness(self) -> Expression: ...
    @LayerThickness.setter
    def LayerThickness(self, value: Expression) -> None: ...
    @property
    def MaterialEnum(self) -> int: ...
    @MaterialEnum.setter
    def MaterialEnum(self, value: int) -> None: ...
    @property
    def NumberOfLasers(self) -> Expression: ...
    @NumberOfLasers.setter
    def NumberOfLasers(self, value: Expression) -> None: ...
    @property
    def PartMaterial(self) -> str: ...
    @PartMaterial.setter
    def PartMaterial(self, value: str) -> None: ...
    @property
    def PrinterDiameter(self) -> Expression: ...
    @PrinterDiameter.setter
    def PrinterDiameter(self, value: Expression) -> None: ...
    @property
    def PrinterHeight(self) -> Expression: ...
    @PrinterHeight.setter
    def PrinterHeight(self, value: Expression) -> None: ...
    @property
    def PrinterLength(self) -> Expression: ...
    @PrinterLength.setter
    def PrinterLength(self, value: Expression) -> None: ...
    @property
    def PrinterName(self) -> str: ...
    @PrinterName.setter
    def PrinterName(self, value: str) -> None: ...
    @property
    def PrinterShape(self) -> Validate.CheckThermalDistortionBuilder.PrinterShapeTypes: ...
    @PrinterShape.setter
    def PrinterShape(self, value: Validate.CheckThermalDistortionBuilder.PrinterShapeTypes) -> None: ...
    @property
    def PrinterWidth(self) -> Expression: ...
    @PrinterWidth.setter
    def PrinterWidth(self, value: Expression) -> None: ...
    @property
    def SelectionAndPlacement(self) -> Validate.SelectionAndPlacementBuilder: ...
    @SelectionAndPlacement.setter
    def SelectionAndPlacement(self, value: Validate.SelectionAndPlacementBuilder) -> None: ...
    @property
    def StressRelief(self) -> bool: ...
    @StressRelief.setter
    def StressRelief(self, value: bool) -> None: ...
    @property
    def UserID(self) -> str: ...
    @UserID.setter
    def UserID(self, value: str) -> None: ...


    class PrinterShapeTypes(enum.Enum):
        Block= 0
        Cylinder= 1
    

    class JobStatusType(enum.Enum):
        Queued= 0
        Processing= 1
        Completed= 2
        Error= 3
        Unknown= 4
    

class CheckPrintTimeBuilder(Builder):
    def __init__(self) -> None: ...
    def Update(self) -> None: ...
    @property
    def AutomaticUpdate(self) -> bool: ...
    @AutomaticUpdate.setter
    def AutomaticUpdate(self, value: bool) -> None: ...
    @property
    def FDMPrintTimeParameter(self) -> Validate.FDMPrintTimeParameter: ...
    @FDMPrintTimeParameter.setter
    def FDMPrintTimeParameter(self, value: Validate.FDMPrintTimeParameter) -> None: ...
    @property
    def MJFPrintTimeParameter(self) -> Validate.MJFPrintTimeParameter: ...
    @MJFPrintTimeParameter.setter
    def MJFPrintTimeParameter(self, value: Validate.MJFPrintTimeParameter) -> None: ...
    @property
    def PBFPrintTimeParameter(self) -> Validate.PBFPrintTimeParameter: ...
    @PBFPrintTimeParameter.setter
    def PBFPrintTimeParameter(self, value: Validate.PBFPrintTimeParameter) -> None: ...
    @property
    def PrintTime(self) -> float: ...
    @PrintTime.setter
    def PrintTime(self, value: float) -> None: ...
    @property
    def Printer(self) -> Validate.CheckPrintTimeBuilder.PrinterType: ...
    @Printer.setter
    def Printer(self, value: Validate.CheckPrintTimeBuilder.PrinterType) -> None: ...
    @property
    def SelectionAndPlacement(self) -> Validate.SelectionAndPlacementBuilder: ...
    @SelectionAndPlacement.setter
    def SelectionAndPlacement(self, value: Validate.SelectionAndPlacementBuilder) -> None: ...


    class PrinterType(enum.Enum):
        PowderBedFusion= 0
        MultiJetFusion= 1
        FusedDepositionModeling= 2
    

class CheckPorosityBuilder(Builder):
    def __init__(self) -> None: ...
    def RemoveColorLegend(self) -> None: ...
    def MakeColorLegend(self) -> None: ...
    def AddGeometricConstraintPoint(self, face: Face, point: Point) -> None: ...
    def SetGeometricConstraintPoint(self, face: Face, point: Point) -> None: ...
    def DeleteGeometricConstraintPoint(self, point: Point) -> None: ...
    def ClearGeometricConstraintPoints(self) -> None: ...
    @property
    def AboveLimit(self) -> float: ...
    @AboveLimit.setter
    def AboveLimit(self, value: float) -> None: ...
    @property
    def AboveTarget(self) -> float: ...
    @AboveTarget.setter
    def AboveTarget(self, value: float) -> None: ...
    @property
    def AutomaticUpdate(self) -> bool: ...
    @AutomaticUpdate.setter
    def AutomaticUpdate(self, value: bool) -> None: ...
    @property
    def Average(self) -> float: ...
    @Average.setter
    def Average(self, value: float) -> None: ...
    @property
    def BelowLimit(self) -> float: ...
    @BelowLimit.setter
    def BelowLimit(self, value: float) -> None: ...
    @property
    def BelowTarget(self) -> float: ...
    @BelowTarget.setter
    def BelowTarget(self, value: float) -> None: ...
    @property
    def ColorMapDisplayOptionType(self) -> Validate.CheckPorosityBuilder.ColorMapDisplayOptionTypes: ...
    @ColorMapDisplayOptionType.setter
    def ColorMapDisplayOptionType(self, value: Validate.CheckPorosityBuilder.ColorMapDisplayOptionTypes) -> None: ...
    @property
    def GeometricConstraintDataManager(self) -> Features.GeometricConstraintDataManager: ...
    @GeometricConstraintDataManager.setter
    def GeometricConstraintDataManager(self, value: Features.GeometricConstraintDataManager) -> None: ...
    @property
    def Maximum(self) -> float: ...
    @Maximum.setter
    def Maximum(self, value: float) -> None: ...
    @property
    def MaximumPorosity(self) -> float: ...
    @MaximumPorosity.setter
    def MaximumPorosity(self, value: float) -> None: ...
    @property
    def Median(self) -> float: ...
    @Median.setter
    def Median(self, value: float) -> None: ...
    @property
    def Minimum(self) -> float: ...
    @Minimum.setter
    def Minimum(self, value: float) -> None: ...
    @property
    def MinimumPorosity(self) -> float: ...
    @MinimumPorosity.setter
    def MinimumPorosity(self, value: float) -> None: ...
    @property
    def PreviewState(self) -> bool: ...
    @PreviewState.setter
    def PreviewState(self, value: bool) -> None: ...
    @property
    def SelectionAndPlacement(self) -> Validate.SelectionAndPlacementBuilder: ...
    @SelectionAndPlacement.setter
    def SelectionAndPlacement(self, value: Validate.SelectionAndPlacementBuilder) -> None: ...
    @property
    def TargetPorosity(self) -> float: ...
    @TargetPorosity.setter
    def TargetPorosity(self, value: float) -> None: ...
    @property
    def VoxelSize(self) -> Expression: ...
    @VoxelSize.setter
    def VoxelSize(self, value: Expression) -> None: ...
    @property
    def WithinLimit(self) -> float: ...
    @WithinLimit.setter
    def WithinLimit(self, value: float) -> None: ...


    class ColorMapDisplayOptionTypes(enum.Enum):
        All= 0
        WithinLimits= 1
        OutsideLimits= 2
        AboveTarget= 3
        BelowTarget= 4
    

class CheckPartOrientationBuilder(Builder):
    def __init__(self) -> None: ...
    def CalculateCheck(self, checkerValues: typing.List[Validate.PartOrientationAnalysisResult.CheckerValues]) -> None: ...
    def StartCalculation(self) -> None: ...
    def OrientToMinimum(self, checkerIndex: Validate.PartOrientationAnalysisResult.CheckerIndex) -> None: ...
    def GetNumOfOptimumOrientations(self) -> int: ...
    def OptimumSolution(self, orientationIndex: int) -> None: ...
    def GetOptimumOrientation(self, optimumOrientationIndex: int, origin: Point3d, orientation: Vector3d, checkerValues: typing.List[Validate.PartOrientationAnalysisResult.CheckerValues]) -> None: ...
    def GetMinimumOrientation(self, checkerIndex: Validate.PartOrientationAnalysisResult.CheckerIndex, origin: Point3d, orientation: Vector3d, checkerValues: typing.List[Validate.PartOrientationAnalysisResult.CheckerValues]) -> None: ...
    def RemoveAllSolutions(self) -> None: ...
    def GetPartOrientationResult(self) -> Validate.PartOrientationAnalysisResult: ...
    @property
    def Accuracy(self) -> Validate.CheckPartOrientationBuilder.AccuracyLevel: ...
    @Accuracy.setter
    def Accuracy(self, value: Validate.CheckPartOrientationBuilder.AccuracyLevel) -> None: ...
    @property
    def FDMPrintTimeParameter(self) -> Validate.FDMPrintTimeParameter: ...
    @FDMPrintTimeParameter.setter
    def FDMPrintTimeParameter(self, value: Validate.FDMPrintTimeParameter) -> None: ...
    @property
    def MJFPrintTimeParameter(self) -> Validate.MJFPrintTimeParameter: ...
    @MJFPrintTimeParameter.setter
    def MJFPrintTimeParameter(self, value: Validate.MJFPrintTimeParameter) -> None: ...
    @property
    def MaxOverhangAngleForOverHeating(self) -> Expression: ...
    @MaxOverhangAngleForOverHeating.setter
    def MaxOverhangAngleForOverHeating(self, value: Expression) -> None: ...
    @property
    def MaxOverhangAngleForVolume(self) -> Expression: ...
    @MaxOverhangAngleForVolume.setter
    def MaxOverhangAngleForVolume(self, value: Expression) -> None: ...
    @property
    def PBFPrintTimeParameter(self) -> Validate.PBFPrintTimeParameter: ...
    @PBFPrintTimeParameter.setter
    def PBFPrintTimeParameter(self, value: Validate.PBFPrintTimeParameter) -> None: ...
    @property
    def Printer(self) -> Validate.CheckPrintTimeBuilder.PrinterType: ...
    @Printer.setter
    def Printer(self, value: Validate.CheckPrintTimeBuilder.PrinterType) -> None: ...
    @property
    def SelectionAndPlacement(self) -> Validate.SelectionAndPlacementBuilder: ...
    @SelectionAndPlacement.setter
    def SelectionAndPlacement(self, value: Validate.SelectionAndPlacementBuilder) -> None: ...
    @property
    def ValidateOverheating(self) -> bool: ...
    @ValidateOverheating.setter
    def ValidateOverheating(self, value: bool) -> None: ...
    @property
    def ValidatePrintTime(self) -> bool: ...
    @ValidatePrintTime.setter
    def ValidatePrintTime(self, value: bool) -> None: ...
    @property
    def ValidateSupportVolume(self) -> bool: ...
    @ValidateSupportVolume.setter
    def ValidateSupportVolume(self, value: bool) -> None: ...
    @property
    def ValidateSurfaceArea(self) -> bool: ...
    @ValidateSurfaceArea.setter
    def ValidateSurfaceArea(self, value: bool) -> None: ...
    @property
    def WeightOverheating(self) -> int: ...
    @WeightOverheating.setter
    def WeightOverheating(self, value: int) -> None: ...
    @property
    def WeightPrintTime(self) -> int: ...
    @WeightPrintTime.setter
    def WeightPrintTime(self, value: int) -> None: ...
    @property
    def WeightSupportVolume(self) -> int: ...
    @WeightSupportVolume.setter
    def WeightSupportVolume(self, value: int) -> None: ...
    @property
    def WeightSurfaceArea(self) -> int: ...
    @WeightSurfaceArea.setter
    def WeightSurfaceArea(self, value: int) -> None: ...


    class AccuracyLevel(enum.Enum):
        Coarse= 1
        Low= 2
        Medium= 3
        High= 4
        VeryHigh= 5
    

class CheckOverheatingBuilder(Builder):
    def __init__(self) -> None: ...
    def Update(self) -> None: ...
    @property
    def AutomaticUpdate(self) -> bool: ...
    @AutomaticUpdate.setter
    def AutomaticUpdate(self, value: bool) -> None: ...
    @property
    def DisplayResolution(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @DisplayResolution.setter
    def DisplayResolution(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def MaximumOverhangAngle(self) -> Expression: ...
    @MaximumOverhangAngle.setter
    def MaximumOverhangAngle(self, value: Expression) -> None: ...
    @property
    def NonOverheatingColor(self) -> NXColor: ...
    @NonOverheatingColor.setter
    def NonOverheatingColor(self, value: NXColor) -> None: ...
    @property
    def OverheatingArea(self) -> float: ...
    @OverheatingArea.setter
    def OverheatingArea(self, value: float) -> None: ...
    @property
    def OverheatingColor(self) -> NXColor: ...
    @OverheatingColor.setter
    def OverheatingColor(self, value: NXColor) -> None: ...
    @property
    def SelectionAndPlacement(self) -> Validate.SelectionAndPlacementBuilder: ...
    @SelectionAndPlacement.setter
    def SelectionAndPlacement(self, value: Validate.SelectionAndPlacementBuilder) -> None: ...
    @property
    def ShowOnlyOverheatingAreas(self) -> bool: ...
    @ShowOnlyOverheatingAreas.setter
    def ShowOnlyOverheatingAreas(self, value: bool) -> None: ...


class CheckModelWithinPrintableVolumeBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AutomaticUpdate(self) -> bool: ...
    @AutomaticUpdate.setter
    def AutomaticUpdate(self, value: bool) -> None: ...
    @property
    def CloseToPrintableVolumeColor(self) -> NXColor: ...
    @CloseToPrintableVolumeColor.setter
    def CloseToPrintableVolumeColor(self, value: NXColor) -> None: ...
    @property
    def DisplayResolutionBuilder(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @DisplayResolutionBuilder.setter
    def DisplayResolutionBuilder(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def DistanceTolerance(self) -> float: ...
    @DistanceTolerance.setter
    def DistanceTolerance(self, value: float) -> None: ...
    @property
    def OutOfPrintableVolumeColor(self) -> NXColor: ...
    @OutOfPrintableVolumeColor.setter
    def OutOfPrintableVolumeColor(self, value: NXColor) -> None: ...
    @property
    def PreviewState(self) -> bool: ...
    @PreviewState.setter
    def PreviewState(self, value: bool) -> None: ...
    @property
    def PrinterDiameter(self) -> float: ...
    @PrinterDiameter.setter
    def PrinterDiameter(self, value: float) -> None: ...
    @property
    def PrinterHeight(self) -> float: ...
    @PrinterHeight.setter
    def PrinterHeight(self, value: float) -> None: ...
    @property
    def PrinterLength(self) -> float: ...
    @PrinterLength.setter
    def PrinterLength(self, value: float) -> None: ...
    @property
    def PrinterName(self) -> str: ...
    @PrinterName.setter
    def PrinterName(self, value: str) -> None: ...
    @property
    def PrinterOrientation(self) -> Matrix3x3: ...
    @PrinterOrientation.setter
    def PrinterOrientation(self, value: Matrix3x3) -> None: ...
    @property
    def PrinterOrigin(self) -> Point3d: ...
    @PrinterOrigin.setter
    def PrinterOrigin(self, value: Point3d) -> None: ...
    @property
    def PrinterShapeType(self) -> Validate.CheckModelWithinPrintableVolumeBuilder.PrinterShapeTypes: ...
    @PrinterShapeType.setter
    def PrinterShapeType(self, value: Validate.CheckModelWithinPrintableVolumeBuilder.PrinterShapeTypes) -> None: ...
    @property
    def PrinterWidth(self) -> float: ...
    @PrinterWidth.setter
    def PrinterWidth(self, value: float) -> None: ...
    @property
    def SelectionAndPlacement(self) -> Validate.SelectionAndPlacementBuilder: ...
    @SelectionAndPlacement.setter
    def SelectionAndPlacement(self, value: Validate.SelectionAndPlacementBuilder) -> None: ...
    @property
    def ShowType(self) -> Validate.CheckModelWithinPrintableVolumeBuilder.ShowTypes: ...
    @ShowType.setter
    def ShowType(self, value: Validate.CheckModelWithinPrintableVolumeBuilder.ShowTypes) -> None: ...
    @property
    def WithinPrintableVolumeColor(self) -> NXColor: ...
    @WithinPrintableVolumeColor.setter
    def WithinPrintableVolumeColor(self, value: NXColor) -> None: ...


    class ShowTypes(enum.Enum):
        Printer= 0
        Product= 1
        Both= 2
    

    class PrinterShapeTypes(enum.Enum):
        Block= 0
        Cylinder= 1
    

class CheckMinimumWallThicknessBuilder(Builder):
    def __init__(self) -> None: ...
    def GetDynamicResult(self, selectedFace: Face, dynamicPnt: Point3d, thickness: float, direction: Vector3d, closestPnt: Point3d) -> bool: ...
    @property
    def AutomaticUpdate(self) -> bool: ...
    @AutomaticUpdate.setter
    def AutomaticUpdate(self, value: bool) -> None: ...
    @property
    def DisplayResolutionBuilder(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @DisplayResolutionBuilder.setter
    def DisplayResolutionBuilder(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def FailureArea(self) -> float: ...
    @FailureArea.setter
    def FailureArea(self, value: float) -> None: ...
    @property
    def LessThanMinThicknessColor(self) -> NXColor: ...
    @LessThanMinThicknessColor.setter
    def LessThanMinThicknessColor(self, value: NXColor) -> None: ...
    @property
    def MoreThanMinThicknessColor(self) -> NXColor: ...
    @MoreThanMinThicknessColor.setter
    def MoreThanMinThicknessColor(self, value: NXColor) -> None: ...
    @property
    def PreviewState(self) -> bool: ...
    @PreviewState.setter
    def PreviewState(self, value: bool) -> None: ...
    @property
    def SelectionAndPlacement(self) -> Validate.SelectionAndPlacementBuilder: ...
    @SelectionAndPlacement.setter
    def SelectionAndPlacement(self, value: Validate.SelectionAndPlacementBuilder) -> None: ...
    @property
    def ShowOnlyFailArea(self) -> bool: ...
    @ShowOnlyFailArea.setter
    def ShowOnlyFailArea(self, value: bool) -> None: ...
    @property
    def Thickness(self) -> float: ...
    @Thickness.setter
    def Thickness(self, value: float) -> None: ...


class CheckMinimumRadiusBuilder(Builder):
    def __init__(self) -> None: ...
    def GetDynamicResult(self, selectedFace: Face, dynamicPnt: Point3d) -> float: ...
    @property
    def AutomaticUpdate(self) -> bool: ...
    @AutomaticUpdate.setter
    def AutomaticUpdate(self, value: bool) -> None: ...
    @property
    def CurvatureType(self) -> Validate.CheckMinimumRadiusBuilder.CurvatureTypes: ...
    @CurvatureType.setter
    def CurvatureType(self, value: Validate.CheckMinimumRadiusBuilder.CurvatureTypes) -> None: ...
    @property
    def DisplayResolutionBuilder(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @DisplayResolutionBuilder.setter
    def DisplayResolutionBuilder(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def ExcludeConvex(self) -> bool: ...
    @ExcludeConvex.setter
    def ExcludeConvex(self, value: bool) -> None: ...
    @property
    def FailureArea(self) -> float: ...
    @FailureArea.setter
    def FailureArea(self, value: float) -> None: ...
    @property
    def LessThanMinimumRadiusColor(self) -> NXColor: ...
    @LessThanMinimumRadiusColor.setter
    def LessThanMinimumRadiusColor(self, value: NXColor) -> None: ...
    @property
    def MinimumRadius(self) -> float: ...
    @MinimumRadius.setter
    def MinimumRadius(self, value: float) -> None: ...
    @property
    def MoreThanMinimumRadiusColor(self) -> NXColor: ...
    @MoreThanMinimumRadiusColor.setter
    def MoreThanMinimumRadiusColor(self, value: NXColor) -> None: ...
    @property
    def PreviewState(self) -> bool: ...
    @PreviewState.setter
    def PreviewState(self, value: bool) -> None: ...
    @property
    def SelectionAndPlacement(self) -> Validate.SelectionAndPlacementBuilder: ...
    @SelectionAndPlacement.setter
    def SelectionAndPlacement(self, value: Validate.SelectionAndPlacementBuilder) -> None: ...
    @property
    def ShowOnlyFailArea(self) -> bool: ...
    @ShowOnlyFailArea.setter
    def ShowOnlyFailArea(self, value: bool) -> None: ...


    class CurvatureTypes(enum.Enum):
        Radius= 0
        Sectional= 1
    

class CheckMaximumOverhangAngleBuilder(Builder):
    def __init__(self) -> None: ...
    def GetTargets(self) -> typing.List[Body]: ...
    def SetTargets(self, targets: typing.List[Body]) -> None: ...
    def Update(self) -> None: ...
    @property
    def Angle(self) -> float: ...
    @Angle.setter
    def Angle(self, value: float) -> None: ...
    @property
    def AutomaticUpdate(self) -> bool: ...
    @AutomaticUpdate.setter
    def AutomaticUpdate(self, value: bool) -> None: ...
    @property
    def DisplayResolutionBuilder(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @DisplayResolutionBuilder.setter
    def DisplayResolutionBuilder(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def DrawOrientation(self) -> Matrix3x3: ...
    @DrawOrientation.setter
    def DrawOrientation(self, value: Matrix3x3) -> None: ...
    @property
    def DrawOrigin(self) -> Point3d: ...
    @DrawOrigin.setter
    def DrawOrigin(self, value: Point3d) -> None: ...
    @property
    def ExceedExtendToleranceColor(self) -> NXColor: ...
    @ExceedExtendToleranceColor.setter
    def ExceedExtendToleranceColor(self, value: NXColor) -> None: ...
    @property
    def ExtendedAngularTolerance(self) -> float: ...
    @ExtendedAngularTolerance.setter
    def ExtendedAngularTolerance(self, value: float) -> None: ...
    @property
    def LessThanMaxAngleColor(self) -> NXColor: ...
    @LessThanMaxAngleColor.setter
    def LessThanMaxAngleColor(self, value: NXColor) -> None: ...
    @property
    def MoreThanMaxAngleColor(self) -> NXColor: ...
    @MoreThanMaxAngleColor.setter
    def MoreThanMaxAngleColor(self, value: NXColor) -> None: ...
    @property
    def OverhangArea(self) -> float: ...
    @OverhangArea.setter
    def OverhangArea(self, value: float) -> None: ...
    @property
    def PreviewState(self) -> bool: ...
    @PreviewState.setter
    def PreviewState(self, value: bool) -> None: ...
    @property
    def SelectionAndPlacement(self) -> Validate.SelectionAndPlacementBuilder: ...
    @SelectionAndPlacement.setter
    def SelectionAndPlacement(self, value: Validate.SelectionAndPlacementBuilder) -> None: ...
    @property
    def ShowOnlyExceedingOverhangAngles(self) -> bool: ...
    @ShowOnlyExceedingOverhangAngles.setter
    def ShowOnlyExceedingOverhangAngles(self, value: bool) -> None: ...
    @property
    def ShowOnlyFailArea(self) -> bool: ...
    @ShowOnlyFailArea.setter
    def ShowOnlyFailArea(self, value: bool) -> None: ...


class CheckerNode(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def GetChildCheckerInstanceNames(self) -> str: ...
    def GetChildCheckerEnabledFlags(self, childCheckerInstances: str) -> bool: ...
    def SetChildCheckerEnabledFlags(self, childCheckerInstances: str, enableFlags: bool) -> None: ...
    def GetChildCheckerEnabledFlag(self, childCheckerInstance: str) -> bool: ...
    def SetChildCheckerEnabledFlag(self, childCheckerInstance: str, enableFlag: bool) -> None: ...
    def GetParameter(self, parameterTitle: str) -> Validate.Parameter: ...
    def GetParameters(self) -> typing.List[Validate.Parameter]: ...
    def AskLogger(self) -> Validate.Logger: ...
    @property
    def AttributeCustomizedFormulas(self) -> str: ...
    @AttributeCustomizedFormulas.setter
    def AttributeCustomizedFormulas(self, value: str) -> None: ...
    @property
    def ClassName(self) -> str: ...
    @ClassName.setter
    def ClassName(self, value: str) -> None: ...


class CheckerDefinition(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def SetDocumentationHandler(self, document: Validate.CheckerDefinition.DocumentationHandler) -> None: ...
    def SetCustomizationHandler(self, customize: Validate.CheckerDefinition.CustomizationHandler) -> None: ...


    

    

    

    

    

    

class CheckChannelRatioBuilder(Builder):
    def __init__(self) -> None: ...
    def GetTableData(self, tableData: typing.List[Validate.CheckChannelRatioBuilder.TableData]) -> None: ...
    def SetTableData(self, tableData: typing.List[Validate.CheckChannelRatioBuilder.TableData]) -> None: ...
    def GetFaces(self) -> typing.List[Face]: ...
    def SetFaces(self, faces: typing.List[Face]) -> None: ...
    def GetBodies(self) -> typing.List[Body]: ...
    def SetBodies(self, bodies: typing.List[Body]) -> None: ...
    def SetNeedRegenerateFacets(self, needRegenerateFacets: bool) -> None: ...
    @property
    def AutomaticUpdate(self) -> bool: ...
    @AutomaticUpdate.setter
    def AutomaticUpdate(self, value: bool) -> None: ...
    @property
    def DisplayResolution(self) -> GeometricUtilities.DisplayResolutionBuilder: ...
    @DisplayResolution.setter
    def DisplayResolution(self, value: GeometricUtilities.DisplayResolutionBuilder) -> None: ...
    @property
    def FailedSegmentsColor(self) -> NXColor: ...
    @FailedSegmentsColor.setter
    def FailedSegmentsColor(self, value: NXColor) -> None: ...
    @property
    def MaximumWidth(self) -> float: ...
    @MaximumWidth.setter
    def MaximumWidth(self, value: float) -> None: ...
    @property
    def MinimumRatio(self) -> float: ...
    @MinimumRatio.setter
    def MinimumRatio(self, value: float) -> None: ...
    @property
    def Orientation(self) -> Matrix3x3: ...
    @Orientation.setter
    def Orientation(self, value: Matrix3x3) -> None: ...
    @property
    def Origin(self) -> Point3d: ...
    @Origin.setter
    def Origin(self, value: Point3d) -> None: ...
    @property
    def PassedSegmentsColor(self) -> NXColor: ...
    @PassedSegmentsColor.setter
    def PassedSegmentsColor(self, value: NXColor) -> None: ...
    @property
    def PreviewState(self) -> bool: ...
    @PreviewState.setter
    def PreviewState(self, value: bool) -> None: ...
    @property
    def SegmentLength(self) -> float: ...
    @SegmentLength.setter
    def SegmentLength(self, value: float) -> None: ...
    @property
    def ShowOnlyFailedSegments(self) -> bool: ...
    @ShowOnlyFailedSegments.setter
    def ShowOnlyFailedSegments(self, value: bool) -> None: ...


    class CheckChannelRatioBuilderTableData():
        @property
        def Angle(self) -> float: ...
        @Angle.setter
        def Angle(self, value: float) -> None: ...
        @property
        def MinimumDiameter(self) -> float: ...
        @MinimumDiameter.setter
        def MinimumDiameter(self, value: float) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, Angle: float, MinimumDiameter: float) -> None: ...
    

class AnalysisResultCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Validate.AnalysisResult]: ...
    @typing.overload
    def __init__(self, owner: BasePart) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateCheckMaximumOverhangAngleBuilder(self, persistentResult: Validate.AnalysisResult) -> Validate.CheckMaximumOverhangAngleBuilder: ...
    def CreateCheckMinimumRadiusBuilder(self, persistentResult: Validate.AnalysisResult) -> Validate.CheckMinimumRadiusBuilder: ...
    def CreateCheckMinimumWallThicknessBuilder(self, persistentResult: Validate.AnalysisResult) -> Validate.CheckMinimumWallThicknessBuilder: ...
    def CreateCheckTrappedSupportsBuilder(self, persistentResult: Validate.AnalysisResult) -> Validate.CheckTrappedSupportsBuilder: ...
    def CreateCheckModelWithinPrintableVolumeBuilder(self, persistentResult: Validate.AnalysisResult) -> Validate.CheckModelWithinPrintableVolumeBuilder: ...
    def CreateCheckWhollyEnclosedVolumeBuilder(self, persistentResult: Validate.AnalysisResult) -> Validate.CheckWhollyEnclosedVolumeBuilder: ...
    def EvaluateAll(self, analysisResults: typing.List[Validate.AnalysisResult]) -> None: ...
    def DeactivateAll(self, analysisResults: typing.List[Validate.AnalysisResult]) -> None: ...
    def FindAllAnalysisResults(self) -> typing.List[Validate.AnalysisResult]: ...
    def FindObject(self, sid: str) -> Validate.AnalysisResult: ...
    def CreateCheckPrintTimeBuilder(self, persistentResult: Validate.AnalysisResult) -> Validate.CheckPrintTimeBuilder: ...
    def CreateCheckOverheatingBuilder(self, persistentResult: Validate.AnalysisResult) -> Validate.CheckOverheatingBuilder: ...
    def CreateCheckPartOrientationBuilder(self, persistentResult: Validate.PartOrientationAnalysisResult) -> Validate.CheckPartOrientationBuilder: ...
    def FindAllAnalysisResultsOfType(self, analysisType: Validate.AnalysisResultCollection.AnalysisResultType) -> typing.List[Validate.AnalysisResult]: ...
    def GetAnalysisResultValue(self, persistentResult: Validate.AnalysisResult) -> float: ...
    def CreateCheckPorosityBuilder(self, persistentResult: Validate.AnalysisResult) -> Validate.CheckPorosityBuilder: ...
    def CreateCheckChannelRatioBuilder(self, persistentResult: Validate.AnalysisResult) -> Validate.CheckChannelRatioBuilder: ...
    def CreateCheckThermalDistortionBuilder(self, persistentResult: Validate.AnalysisResult) -> Validate.CheckThermalDistortionBuilder: ...
    def Tag(self) -> Tag: ...



    class AnalysisResultType(enum.Enum):
        MaximumOverhangAngle= 0
        PrintTime= 1
        Overheating= 2
    

class AnalysisResult(Validate.PersistentResult):
    def __init__(self) -> None: ...
    def Evaluate(self) -> None: ...
    def Deactivate(self) -> None: ...
    def Activate(self) -> None: ...
    @property
    def ActiveStatus(self) -> bool: ...
    @ActiveStatus.setter
    def ActiveStatus(self, value: bool) -> None: ...


