from ....NXOpen import *
from ...Features import *

import typing
import enum

class ProjectStructureNode(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def GetChildNodes(self, childNodes: typing.List[Features.Industry.ProjectStructureNode]) -> None: ...
    @property
    def Checked(self) -> bool: ...
    @Checked.setter
    def Checked(self, value: bool) -> None: ...
    @property
    def CreateAsRootPart(self) -> bool: ...
    @CreateAsRootPart.setter
    def CreateAsRootPart(self, value: bool) -> None: ...
    @property
    def SelectedSpecialization(self) -> str: ...
    @SelectedSpecialization.setter
    def SelectedSpecialization(self, value: str) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


