from ....NXOpen import *
from ...Features import *

import typing
import enum

class TrimBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def BoundaryObjects(self) -> SelectCurveList: ...
    @BoundaryObjects.setter
    def BoundaryObjects(self, value: SelectCurveList) -> None: ...
    @property
    def ExtendBound(self) -> bool: ...
    @ExtendBound.setter
    def ExtendBound(self, value: bool) -> None: ...
    @property
    def Point(self) -> SelectDisplayableObject: ...
    @Point.setter
    def Point(self, value: SelectDisplayableObject) -> None: ...
    @property
    def Targets(self) -> GeometricUtilities.CrayonSelectionData: ...
    @Targets.setter
    def Targets(self, value: GeometricUtilities.CrayonSelectionData) -> None: ...


class TransformData(Builder):
    def __init__(self) -> None: ...
    @property
    def CanMoveToolOnly(self) -> bool: ...
    @CanMoveToolOnly.setter
    def CanMoveToolOnly(self, value: bool) -> None: ...
    @property
    def CanRelocateToolToSelection(self) -> bool: ...
    @CanRelocateToolToSelection.setter
    def CanRelocateToolToSelection(self, value: bool) -> None: ...
    @property
    def CanReorientToolToSelection(self) -> bool: ...
    @CanReorientToolToSelection.setter
    def CanReorientToolToSelection(self, value: bool) -> None: ...
    @property
    def NumberOfCopies(self) -> int: ...
    @NumberOfCopies.setter
    def NumberOfCopies(self, value: int) -> None: ...
    @property
    def ObjectsToTransform(self) -> SelectNXObjectList: ...
    @ObjectsToTransform.setter
    def ObjectsToTransform(self, value: SelectNXObjectList) -> None: ...
    @property
    def ResultOption(self) -> Features.DrawShapes.TransformData.ResultOptions: ...
    @ResultOption.setter
    def ResultOption(self, value: Features.DrawShapes.TransformData.ResultOptions) -> None: ...
    @property
    def Scaling(self) -> Features.DrawShapes.TransformData.ScalingOptions: ...
    @Scaling.setter
    def Scaling(self, value: Features.DrawShapes.TransformData.ScalingOptions) -> None: ...
    @property
    def Transformer(self) -> GeometricUtilities.TransformerData: ...
    @Transformer.setter
    def Transformer(self, value: GeometricUtilities.TransformerData) -> None: ...


    class ScalingOptions(enum.Enum):
        Linear= 0
        Planar= 1
        Uniform= 2
    

    class ResultOptions(enum.Enum):
        MoveOriginal= 0
        CopyOriginal= 1
    

class StartSymmetryModeBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CreateSymmetricCopiesOfExistingCurves(self) -> bool: ...
    @CreateSymmetricCopiesOfExistingCurves.setter
    def CreateSymmetricCopiesOfExistingCurves(self, value: bool) -> None: ...
    @property
    def Plane(self) -> Plane: ...
    @Plane.setter
    def Plane(self, value: Plane) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MirrorData(Builder):
    def __init__(self) -> None: ...
    @property
    def Objects(self) -> SelectCurveList: ...
    @Objects.setter
    def Objects(self, value: SelectCurveList) -> None: ...
    @property
    def Plane(self) -> Plane: ...
    @Plane.setter
    def Plane(self, value: Plane) -> None: ...


class ExtendBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def BoundaryObjects(self) -> SelectCurveList: ...
    @BoundaryObjects.setter
    def BoundaryObjects(self, value: SelectCurveList) -> None: ...
    @property
    def ExtendBound(self) -> bool: ...
    @ExtendBound.setter
    def ExtendBound(self, value: bool) -> None: ...
    @property
    def Targets(self) -> GeometricUtilities.CrayonSelectionData: ...
    @Targets.setter
    def Targets(self, value: GeometricUtilities.CrayonSelectionData) -> None: ...


class EraseBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def StrokeGesture(self) -> GeometricUtilities.StrokeGestureData: ...
    @StrokeGesture.setter
    def StrokeGesture(self, value: GeometricUtilities.StrokeGestureData) -> None: ...
    @property
    def Thickness(self) -> float: ...
    @Thickness.setter
    def Thickness(self, value: float) -> None: ...


class EditDisplayBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Color(self) -> NXColor: ...
    @Color.setter
    def Color(self, value: NXColor) -> None: ...
    @property
    def Objects(self) -> SelectCurveList: ...
    @Objects.setter
    def Objects(self, value: SelectCurveList) -> None: ...
    @property
    def Thickness(self) -> DisplayableObject.ObjectWidth: ...
    @Thickness.setter
    def Thickness(self, value: DisplayableObject.ObjectWidth) -> None: ...


class EditCurveBuilder(Builder):
    def __init__(self) -> None: ...
    def EvaluateCurve(self) -> None: ...
    @property
    def CircleDefinitionOptions(self) -> Features.DrawShapes.EditCurveBuilder.CircleDefinitionOption: ...
    @CircleDefinitionOptions.setter
    def CircleDefinitionOptions(self, value: Features.DrawShapes.EditCurveBuilder.CircleDefinitionOption) -> None: ...
    @property
    def ConstraintManager(self) -> Features.GeometricConstraintDataManager: ...
    @ConstraintManager.setter
    def ConstraintManager(self, value: Features.GeometricConstraintDataManager) -> None: ...
    @property
    def IsClosed(self) -> bool: ...
    @IsClosed.setter
    def IsClosed(self, value: bool) -> None: ...
    @property
    def PointNumber(self) -> int: ...
    @PointNumber.setter
    def PointNumber(self, value: int) -> None: ...
    @property
    def Radius(self) -> Expression: ...
    @Radius.setter
    def Radius(self, value: Expression) -> None: ...


    class CircleDefinitionOption(enum.Enum):
        ThreePoints= 0
        CenterandRadius= 1
    

class DrawStrokeData(Builder):
    def __init__(self) -> None: ...
    @property
    def CanDrawOnNearestFace(self) -> bool: ...
    @CanDrawOnNearestFace.setter
    def CanDrawOnNearestFace(self, value: bool) -> None: ...
    @property
    def Color(self) -> NXColor: ...
    @Color.setter
    def Color(self, value: NXColor) -> None: ...
    @property
    def StrokeGesture(self) -> GeometricUtilities.StrokeGestureData: ...
    @StrokeGesture.setter
    def StrokeGesture(self, value: GeometricUtilities.StrokeGestureData) -> None: ...
    @property
    def Thickness(self) -> DisplayableObject.ObjectWidth: ...
    @Thickness.setter
    def Thickness(self, value: DisplayableObject.ObjectWidth) -> None: ...


class DrawShapeData(Builder):
    def __init__(self) -> None: ...
    @property
    def Associative(self) -> bool: ...
    @Associative.setter
    def Associative(self, value: bool) -> None: ...
    @property
    def CoordinateSystem(self) -> CoordinateSystem: ...
    @CoordinateSystem.setter
    def CoordinateSystem(self, value: CoordinateSystem) -> None: ...
    @property
    def DrawingBaseType(self) -> Features.DrawShapes.DrawShapeData.DrawingBaseTypes: ...
    @DrawingBaseType.setter
    def DrawingBaseType(self, value: Features.DrawShapes.DrawShapeData.DrawingBaseTypes) -> None: ...
    @property
    def Faces(self) -> ScCollector: ...
    @Faces.setter
    def Faces(self, value: ScCollector) -> None: ...


    class DrawingBaseTypes(enum.Enum):
        Faces= 0
        Plane= 1
    

class DrawShapeCollection(Utilities.NXRemotableObject):
    def __init__(self, owner: Features.FreeformCurveCollection) -> None: ...
    def CreateDrawShapeData(self) -> Features.DrawShapes.DrawShapeData: ...
    def CreateDrawStrokeData(self) -> Features.DrawShapes.DrawStrokeData: ...
    def CreateDrawCurveData(self) -> Features.DrawShapes.DrawCurveData: ...
    def CreateCurveFromStrokeData(self) -> Features.DrawShapes.CurveFromStrokeData: ...
    def CreateEditCurveBuilder(self, curveToEdit: Curve) -> Features.DrawShapes.EditCurveBuilder: ...
    def CreateEditDisplayBuilder(self) -> Features.DrawShapes.EditDisplayBuilder: ...
    def CreateStartSymmetryModeBuilder(self) -> Features.DrawShapes.StartSymmetryModeBuilder: ...
    def StopSymmetryMode(self) -> bool: ...
    def CreateDeleteData(self) -> Features.DrawShapes.DeleteData: ...
    def CreateMirrorData(self) -> Features.DrawShapes.MirrorData: ...
    def CreateTrimBuilder(self) -> Features.DrawShapes.TrimBuilder: ...
    def CreateExtendBuilder(self) -> Features.DrawShapes.ExtendBuilder: ...
    def CreateEraseBuilder(self) -> Features.DrawShapes.EraseBuilder: ...
    def CreateTransformData(self) -> Features.DrawShapes.TransformData: ...
    def Tag(self) -> Tag: ...



class DrawCurveData(Builder):
    def __init__(self) -> None: ...
    def SetOverSketchTolerance(self, overSketchTolerance: float) -> None: ...
    @property
    def CanCreatePrimitives(self) -> bool: ...
    @CanCreatePrimitives.setter
    def CanCreatePrimitives(self, value: bool) -> None: ...
    @property
    def CanDrawOnNearestFace(self) -> bool: ...
    @CanDrawOnNearestFace.setter
    def CanDrawOnNearestFace(self, value: bool) -> None: ...
    @property
    def Color(self) -> NXColor: ...
    @Color.setter
    def Color(self, value: NXColor) -> None: ...
    @property
    def DetectionSensitivity(self) -> Features.DrawShapes.DrawCurveData.DetectionSensitivityOption: ...
    @DetectionSensitivity.setter
    def DetectionSensitivity(self, value: Features.DrawShapes.DrawCurveData.DetectionSensitivityOption) -> None: ...
    @property
    def OversketchExistingCurves(self) -> bool: ...
    @OversketchExistingCurves.setter
    def OversketchExistingCurves(self, value: bool) -> None: ...
    @property
    def Snapping(self) -> Features.DrawShapes.DrawCurveData.SnappingOption: ...
    @Snapping.setter
    def Snapping(self, value: Features.DrawShapes.DrawCurveData.SnappingOption) -> None: ...
    @property
    def StrokeGesture(self) -> GeometricUtilities.StrokeGestureData: ...
    @StrokeGesture.setter
    def StrokeGesture(self, value: GeometricUtilities.StrokeGestureData) -> None: ...
    @property
    def Thickness(self) -> DisplayableObject.ObjectWidth: ...
    @Thickness.setter
    def Thickness(self, value: DisplayableObject.ObjectWidth) -> None: ...


    class SnappingOption(enum.Enum):
        None_= 0
        CurveEndPoints= 1
        IsoparametricGrid= 2
    

    class DetectionSensitivityOption(enum.Enum):
        Low= 0
        Standard= 1
        High= 2
    

class DeleteData(Builder):
    def __init__(self) -> None: ...
    @property
    def Objects(self) -> SelectCurveList: ...
    @Objects.setter
    def Objects(self, value: SelectCurveList) -> None: ...


class CurveFromStrokeData(Builder):
    def __init__(self) -> None: ...
    def SetMergeTolerance(self, mergeTolerance: float) -> None: ...
    @property
    def CanCreatePrimitives(self) -> bool: ...
    @CanCreatePrimitives.setter
    def CanCreatePrimitives(self, value: bool) -> None: ...
    @property
    def CanMergeConnectedStrokes(self) -> bool: ...
    @CanMergeConnectedStrokes.setter
    def CanMergeConnectedStrokes(self, value: bool) -> None: ...
    @property
    def DetectionSensitivity(self) -> Features.DrawShapes.CurveFromStrokeData.DetectionSensitivityOption: ...
    @DetectionSensitivity.setter
    def DetectionSensitivity(self, value: Features.DrawShapes.CurveFromStrokeData.DetectionSensitivityOption) -> None: ...
    @property
    def Strokes(self) -> SelectDisplayableObjectList: ...
    @Strokes.setter
    def Strokes(self, value: SelectDisplayableObjectList) -> None: ...


    class DetectionSensitivityOption(enum.Enum):
        Low= 0
        Standard= 1
        High= 2
    

