from ...NXOpen import *

import typing
import enum

class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class FlatPatternSettings(TaggedObject):
    def __init__(self) -> None: ...
    def GetFlatPatternObjectTypeDisplay(self, objectType: SheetMetal.FlatPatternSettings.FlatPatternObjectType) -> SheetMetal.FlatPatternSettings.FlatPatternObjectTypeDisplay: ...
    def SetFlatPatternObjectTypeDisplay(self, objectType: SheetMetal.FlatPatternSettings.FlatPatternObjectType, displayData: SheetMetal.FlatPatternSettings.FlatPatternObjectTypeDisplay) -> None: ...
    def GetFlatPatternCalloutTypeDisplay(self, calloutType: str) -> SheetMetal.FlatPatternSettings.FlatPatternCalloutTypeDisplay: ...
    def SetFlatPatternCalloutTypeDisplay(self, calloutType: str, displayData: SheetMetal.FlatPatternSettings.FlatPatternCalloutTypeDisplay) -> None: ...
    def GetFlatPatternAllObjectTypeDisplay(self, displayData: typing.List[SheetMetal.FlatPatternSettings.FlatPatternObjectTypeDisplay]) -> None: ...
    def GetFlatPatternAllCalloutTypeDisplay(self, displayData: typing.List[SheetMetal.FlatPatternSettings.FlatPatternCalloutTypeDisplay]) -> None: ...


    class FlatPatternSettingsFlatPatternObjectTypeDisplay():
        @property
        def Type(self) -> SheetMetal.FlatPatternSettings.FlatPatternObjectType: ...
        @Type.setter
        def Type(self, value: SheetMetal.FlatPatternSettings.FlatPatternObjectType) -> None: ...
        @property
        def IsEnabled(self) -> int: ...
        @IsEnabled.setter
        def IsEnabled(self, value: int) -> None: ...
        @property
        def Color(self) -> NXColor: ...
        @Color.setter
        def Color(self, value: NXColor) -> None: ...
        @property
        def Font(self) -> ViewDependentDisplayManager.Font: ...
        @Font.setter
        def Font(self, value: ViewDependentDisplayManager.Font) -> None: ...
        @property
        def Width(self) -> ViewDependentDisplayManager.Width: ...
        @Width.setter
        def Width(self, value: ViewDependentDisplayManager.Width) -> None: ...
        def ToString(self) -> str: ...
    

    class FlatPatternObjectType(enum.Enum):
        BendCenterLine= 0
        BendUpCenterLine= 1
        BendDownCenterLine= 2
        BendTangentLine= 3
        OuterMoldLine= 4
        InnerMoldLine= 5
        ExteriorCurves= 6
        InteriorCurves= 7
        InteriorCutoutCurves= 8
        InteriorFeatureCurves= 9
        LighteningHoleCenter= 10
        JoggleLine= 11
        AddedTopGeometry= 12
        AddedBottomGeometry= 13
        ToolMarker= 14
        Hole= 15
        Centermark= 16
    

    class FlatPatternSettingsFlatPatternCalloutTypeDisplay():
        @property
        def Type(self) -> str: ...
        @Type.setter
        def Type(self, value: str) -> None: ...
        @property
        def IsEnabled(self) -> int: ...
        @IsEnabled.setter
        def IsEnabled(self, value: int) -> None: ...
        @property
        def Name(self) -> str: ...
        @Name.setter
        def Name(self, value: str) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, Type: str, IsEnabled: int, Name: str) -> None: ...
    

    class FlatPatternSettings_FlatPatternObjectTypeDisplay():
        @property
        def type(self) -> SheetMetal.FlatPatternSettings.FlatPatternObjectType: ...
        @type.setter
        def type(self, value: SheetMetal.FlatPatternSettings.FlatPatternObjectType) -> None: ...
        @property
        def is_enabled(self) -> int: ...
        @is_enabled.setter
        def is_enabled(self, value: int) -> None: ...
        @property
        def color(self) -> int: ...
        @color.setter
        def color(self, value: int) -> None: ...
        @property
        def font(self) -> ViewDependentDisplayManager.Font: ...
        @font.setter
        def font(self, value: ViewDependentDisplayManager.Font) -> None: ...
        @property
        def width(self) -> ViewDependentDisplayManager.Width: ...
        @width.setter
        def width(self, value: ViewDependentDisplayManager.Width) -> None: ...
    

    class FlatPatternSettings_FlatPatternCalloutTypeDisplay():
        @property
        def type(self) -> int: ...
        @type.setter
        def type(self, value: int) -> None: ...
        @property
        def is_enabled(self) -> int: ...
        @is_enabled.setter
        def is_enabled(self, value: int) -> None: ...
        @property
        def name(self) -> int: ...
        @name.setter
        def name(self, value: int) -> None: ...
    

