from ...NXOpen import *

import typing
import enum

class UpdateFormboardBuilder(Builder):
    def __init__(self) -> None: ...
    def GetHarnessPart(self) -> Part: ...
    def SetHarnessPart(self, harnessPart: Part) -> None: ...
    def SetHarnesses(self, harnesses: typing.List[Routing.Electrical.HarnessDevice]) -> None: ...
    def FindMapping(self) -> None: ...
    def DetermineDiscrepancies(self) -> None: ...
    def GetNumberOfDiscrepancies(self) -> int: ...
    def GetDiscrepancy(self, index: int) -> Formboard.UpdateDiscrepancy: ...
    def RemoveBendsOfRadialBends(self) -> None: ...
    def CreateBendsOfRadialBends(self) -> None: ...
    @property
    def LengthOptions(self) -> Formboard.LayoutLengthOptions: ...
    @LengthOptions.setter
    def LengthOptions(self, value: Formboard.LayoutLengthOptions) -> None: ...


class UpdateDiscrepancy(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def DiscrepancyObjectType(self) -> Formboard.UpdateDiscrepancy.ObjectType: ...
    @DiscrepancyObjectType.setter
    def DiscrepancyObjectType(self, value: Formboard.UpdateDiscrepancy.ObjectType) -> None: ...
    @property
    def DiscrepancyType(self) -> Formboard.UpdateDiscrepancy.Type: ...
    @DiscrepancyType.setter
    def DiscrepancyType(self, value: Formboard.UpdateDiscrepancy.Type) -> None: ...
    @property
    def FormboardObject(self) -> NXObject: ...
    @FormboardObject.setter
    def FormboardObject(self, value: NXObject) -> None: ...
    @property
    def HarnessObject(self) -> NXObject: ...
    @HarnessObject.setter
    def HarnessObject(self, value: NXObject) -> None: ...


    class Type(enum.Enum):
        Unknown= 0
        Missing= 1
        Extra= 2
        Modified= 3
    

    class ObjectType(enum.Enum):
        Unknown= 0
        Rcp= 1
        Segment= 2
        Clip= 3
        Component= 4
        Harness= 5
        Wire= 6
        Cable= 7
        Shield= 8
        Connector= 9
        Device= 10
        Overstock= 11
        Fillerstock= 12
        FittingOverstock= 13
    

class ShapeSegmentBuilder(Builder):
    def __init__(self) -> None: ...
    def ChangeType(self, newType: int) -> None: ...
    def NewSegment(self, newSegment: Routing.ISegment) -> None: ...
    def UpdateLineAngleVec(self, newDir: Vector3d) -> None: ...
    def GetLineData(self, anchorSeg: Routing.ISegment, anchorRcp: Routing.ControlPoint, angle: float) -> None: ...
    def CreateNewRadialBend(self, firstPivot: Point3d, firstBendMethod: int, firstBendValue: float, secondPivot: Point3d, secondBendMethod: int, secondBendValue: float) -> None: ...
    def AddRadialPivot(self, pivotLocation: Point3d, bendMethod: int, bendValue: float) -> None: ...
    def RemoveRadialPivot(self, pivotIndex: int) -> None: ...
    def UpdateRadialPivot(self, pivotIndex: int, newLocation: Point3d, newBendMethod: int, newBendValue: float) -> None: ...
    def CreateNewSpline(self, anchorLocation: Point3d, firstPoint: Point3d, secondPoint: Point3d) -> None: ...
    def RemoveSplinePoint(self, pointIndex: int) -> None: ...
    def AddSplinePoint(self, pointLocation: Point3d) -> int: ...
    def UpdateSplinePoint(self, pointIndex: int, pointLocation: Point3d, inDrag: bool) -> None: ...
    def CommitCurrentOperation(self) -> None: ...
    def SwapAnchorEnd(self) -> None: ...
    def SetActiveView(self, view: TaggedObject) -> None: ...


class PathLengthAnnotationBuilder(Builder):
    def __init__(self) -> None: ...
    def SetPathLengthAnnotationEndPoints(self, firstEndPoint: Point, secondEndPoint: Point) -> None: ...
    def CreatePointsAtRcps(self, firstEndRcp: Routing.ControlPoint, secondEndRcp: Routing.ControlPoint) -> None: ...
    @property
    def ExpressionName(self) -> str: ...
    @ExpressionName.setter
    def ExpressionName(self, value: str) -> None: ...
    @property
    def FirstEndPoint(self) -> Point: ...
    @FirstEndPoint.setter
    def FirstEndPoint(self, value: Point) -> None: ...
    @property
    def Leader(self) -> Annotations.LeaderBuilder: ...
    @Leader.setter
    def Leader(self, value: Annotations.LeaderBuilder) -> None: ...
    @property
    def Origin(self) -> Annotations.OriginBuilder: ...
    @Origin.setter
    def Origin(self, value: Annotations.OriginBuilder) -> None: ...
    @property
    def RouteObjectCollector(self) -> Routing.RouteObjectCollector: ...
    @RouteObjectCollector.setter
    def RouteObjectCollector(self, value: Routing.RouteObjectCollector) -> None: ...
    @property
    def SecondEndPoint(self) -> Point: ...
    @SecondEndPoint.setter
    def SecondEndPoint(self, value: Point) -> None: ...
    @property
    def ShowLeadersToggle(self) -> bool: ...
    @ShowLeadersToggle.setter
    def ShowLeadersToggle(self, value: bool) -> None: ...
    @property
    def Style(self) -> Annotations.StyleBuilder: ...
    @Style.setter
    def Style(self, value: Annotations.StyleBuilder) -> None: ...
    @property
    def Text(self) -> Annotations.TextWithEditControlsBuilder: ...
    @Text.setter
    def Text(self, value: Annotations.TextWithEditControlsBuilder) -> None: ...
    @property
    def Type(self) -> Formboard.PathLengthAnnotationBuilder.Types: ...
    @Type.setter
    def Type(self, value: Formboard.PathLengthAnnotationBuilder.Types) -> None: ...


    class Types(enum.Enum):
        PointsOnCurves= 0
        RoutingPathLength= 1
    

class OrientBranchBuilder(Builder):
    def __init__(self) -> None: ...
    def UpdateRotationAngle(self, angle: float) -> None: ...
    def StartDrag(self) -> None: ...
    def StopDrag(self) -> None: ...
    def InitializeFromSegment(self) -> None: ...
    def SetBranchSeedObject(self, segmentTag: Routing.ISegment) -> None: ...
    def UnSuppressConstraints(self) -> None: ...
    @property
    def BranchAngleType(self) -> Formboard.OrientBranchBuilder.BranchAngleMethod: ...
    @BranchAngleType.setter
    def BranchAngleType(self, value: Formboard.OrientBranchBuilder.BranchAngleMethod) -> None: ...
    @property
    def FromPoint(self) -> Point: ...
    @FromPoint.setter
    def FromPoint(self, value: Point) -> None: ...
    @property
    def FromVector(self) -> Direction: ...
    @FromVector.setter
    def FromVector(self, value: Direction) -> None: ...
    @property
    def RefRotationAngle(self) -> Expression: ...
    @RefRotationAngle.setter
    def RefRotationAngle(self, value: Expression) -> None: ...
    @property
    def ReferenceVector(self) -> Direction: ...
    @ReferenceVector.setter
    def ReferenceVector(self, value: Direction) -> None: ...
    @property
    def RotationAngle(self) -> Expression: ...
    @RotationAngle.setter
    def RotationAngle(self, value: Expression) -> None: ...
    @property
    def SelectBranch(self) -> Routing.RouteObjectCollector: ...
    @SelectBranch.setter
    def SelectBranch(self, value: Routing.RouteObjectCollector) -> None: ...
    @property
    def ToPoint(self) -> Point: ...
    @ToPoint.setter
    def ToPoint(self, value: Point) -> None: ...
    @property
    def ToVector(self) -> Direction: ...
    @ToVector.setter
    def ToVector(self, value: Direction) -> None: ...


    class BranchAngleMethod(enum.Enum):
        AnglefromReferenceVector= 0
        Angle= 1
        AlignAxisToVector= 2
        TwoPoints= 3
    

class ObjectAttributeReferenceBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AnnotLeader(self) -> Annotations.LeaderBuilder: ...
    @AnnotLeader.setter
    def AnnotLeader(self, value: Annotations.LeaderBuilder) -> None: ...
    @property
    def CompOrigin(self) -> Annotations.OriginBuilder: ...
    @CompOrigin.setter
    def CompOrigin(self, value: Annotations.OriginBuilder) -> None: ...
    @property
    def EnumType(self) -> Formboard.ObjectAttributeReferenceBuilder.LeaderType: ...
    @EnumType.setter
    def EnumType(self, value: Formboard.ObjectAttributeReferenceBuilder.LeaderType) -> None: ...
    @property
    def ObjectSelection(self) -> SelectNXObject: ...
    @ObjectSelection.setter
    def ObjectSelection(self, value: SelectNXObject) -> None: ...


    class LeaderType(enum.Enum):
        None_= 0
        SingleLocation= 1
        StartandEndLocations= 2
    

class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class LayoutLengthOptions(Builder):
    def __init__(self) -> None: ...
    @property
    def NetlistLengthIncrement(self) -> Expression: ...
    @NetlistLengthIncrement.setter
    def NetlistLengthIncrement(self, value: Expression) -> None: ...
    @property
    def NetlistRoundingMethod(self) -> Formboard.LayoutLengthOptions.RoundingMethod: ...
    @NetlistRoundingMethod.setter
    def NetlistRoundingMethod(self, value: Formboard.LayoutLengthOptions.RoundingMethod) -> None: ...
    @property
    def OverstockLengthIncrement(self) -> Expression: ...
    @OverstockLengthIncrement.setter
    def OverstockLengthIncrement(self, value: Expression) -> None: ...
    @property
    def OverstockRoundingMethod(self) -> Formboard.LayoutLengthOptions.RoundingMethod: ...
    @OverstockRoundingMethod.setter
    def OverstockRoundingMethod(self, value: Formboard.LayoutLengthOptions.RoundingMethod) -> None: ...
    @property
    def SegmentLengthIncrement(self) -> Expression: ...
    @SegmentLengthIncrement.setter
    def SegmentLengthIncrement(self, value: Expression) -> None: ...
    @property
    def SegmentRoundingMethod(self) -> Formboard.LayoutLengthOptions.RoundingMethod: ...
    @SegmentRoundingMethod.setter
    def SegmentRoundingMethod(self, value: Formboard.LayoutLengthOptions.RoundingMethod) -> None: ...


    class RoundingMethod(enum.Enum):
        Exact= 0
        Nearest= 1
        UpToNearest= 2
        DownToNearest= 3
    

class FormboardManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    def IsFormboard(self) -> bool: ...
    def StoreHarnessesToFlatten(self, harnesses: typing.List[Routing.Electrical.HarnessDevice]) -> None: ...
    def AddPartAs3dHarness(self, harnessPart: Part) -> None: ...
    def CreateLayoutBuilder(self) -> Formboard.FormboardLayoutBuilder: ...
    def CreateOrientBranchBuilder(self) -> Formboard.OrientBranchBuilder: ...
    def CreateFlipComponentBuilder(self) -> Formboard.FlipComponentBuilder: ...
    def CreateShapeSegmentBuilder(self, segment: Routing.ISegment) -> Formboard.ShapeSegmentBuilder: ...
    def CreateFaceAnnotationBuilder(self) -> Formboard.FaceAnnotationBuilder: ...
    def CreateObjectAttributeReferenceBuilder(self) -> Formboard.ObjectAttributeReferenceBuilder: ...
    def CreatePathLengthAnnotationBuilder(self, annotation: Annotations.Annotation) -> Formboard.PathLengthAnnotationBuilder: ...
    def CreateUpdateFormboardBuilder(self) -> Formboard.UpdateFormboardBuilder: ...
    def GetFmbdPlaneConstraints(self, fmbdPlane: NXObject, constraints: typing.List[Positioning.ComponentConstraint]) -> None: ...
    def ShowFormboardConstraints(self) -> None: ...
    def HideFormboardConstraints(self) -> None: ...
    def CalculateLegacyComponentClocking(self, component1: Assemblies.Component, component2: Assemblies.Component, displayStyle: Formboard.FormboardManager.LegacyComponentOrientationDisplayStyle, rotationVector: Vector3d, clockingAngle: float, confidenceLevel: Formboard.FormboardManager.LegacyComponentOrientationConfidenceLevel) -> None: ...
    def Tag(self) -> Tag: ...



    class LegacyComponentOrientationDisplayStyle(enum.Enum):
        NoDisplay= 0
        DisplayCurveNormals= 1
        DisplaySurface= 2
        DisplayAll= 3
    

    class LegacyComponentOrientationConfidenceLevel(enum.Enum):
        High= 0
        Medium= 1
        Low= 2
    

class FormboardLayoutBuilder(Builder):
    def __init__(self) -> None: ...
    def CreateDefaultGeometry(self) -> None: ...
    def UpdateLayout(self) -> None: ...
    def TranslateToNewOrigin(self) -> None: ...
    @property
    def BranchAngleMethod(self) -> Formboard.FormboardLayoutBuilder.BranchAngle: ...
    @BranchAngleMethod.setter
    def BranchAngleMethod(self, value: Formboard.FormboardLayoutBuilder.BranchAngle) -> None: ...
    @property
    def BranchShapeType(self) -> Formboard.FormboardLayoutBuilder.BranchShape: ...
    @BranchShapeType.setter
    def BranchShapeType(self, value: Formboard.FormboardLayoutBuilder.BranchShape) -> None: ...
    @property
    def LengthOptions(self) -> Formboard.LayoutLengthOptions: ...
    @LengthOptions.setter
    def LengthOptions(self, value: Formboard.LayoutLengthOptions) -> None: ...
    @property
    def MainRunEndSelection(self) -> Routing.SelectControlPoint: ...
    @MainRunEndSelection.setter
    def MainRunEndSelection(self, value: Routing.SelectControlPoint) -> None: ...
    @property
    def MainRunMethod(self) -> Formboard.FormboardLayoutBuilder.MainRunType: ...
    @MainRunMethod.setter
    def MainRunMethod(self, value: Formboard.FormboardLayoutBuilder.MainRunType) -> None: ...
    @property
    def MainRunOrigin(self) -> Point: ...
    @MainRunOrigin.setter
    def MainRunOrigin(self, value: Point) -> None: ...
    @property
    def MainRunStartSelection(self) -> Routing.SelectControlPoint: ...
    @MainRunStartSelection.setter
    def MainRunStartSelection(self, value: Routing.SelectControlPoint) -> None: ...
    @property
    def MaximumRandomAngle(self) -> Expression: ...
    @MaximumRandomAngle.setter
    def MaximumRandomAngle(self, value: Expression) -> None: ...
    @property
    def MinimumRandomAngle(self) -> Expression: ...
    @MinimumRandomAngle.setter
    def MinimumRandomAngle(self, value: Expression) -> None: ...
    @property
    def PrimaryStandardAngle(self) -> Expression: ...
    @PrimaryStandardAngle.setter
    def PrimaryStandardAngle(self, value: Expression) -> None: ...
    @property
    def ReverseMainRun(self) -> bool: ...
    @ReverseMainRun.setter
    def ReverseMainRun(self, value: bool) -> None: ...
    @property
    def SecondaryStandardAngle(self) -> Expression: ...
    @SecondaryStandardAngle.setter
    def SecondaryStandardAngle(self, value: Expression) -> None: ...
    @property
    def TertiaryStandardAngle(self) -> Expression: ...
    @TertiaryStandardAngle.setter
    def TertiaryStandardAngle(self, value: Expression) -> None: ...


    class MainRunType(enum.Enum):
        Longest= 0
        Thickest= 1
        UserSelection= 2
    

    class BranchShape(enum.Enum):
        Straight= 0
        Angled= 1
    

    class BranchAngle(enum.Enum):
        AsDesigned= 0
        StandardAngles= 1
        MaximumAngles= 2
        RandomAngles= 3
    

class FlipComponentBuilder(Builder):
    def __init__(self) -> None: ...
    def StartDrag(self) -> None: ...
    def StopDrag(self) -> None: ...
    def InitializeFromComponent(self) -> None: ...
    def FlipComponent(self) -> None: ...
    def CreateDatumAxis(self) -> typing.List[NXObject]: ...
    def SetRotationAngle(self, angle: float) -> None: ...
    @property
    def AxisTypeEnum(self) -> Formboard.FlipComponentBuilder.AxisType: ...
    @AxisTypeEnum.setter
    def AxisTypeEnum(self, value: Formboard.FlipComponentBuilder.AxisType) -> None: ...
    @property
    def CompSel(self) -> SelectNXObject: ...
    @CompSel.setter
    def CompSel(self, value: SelectNXObject) -> None: ...
    @property
    def CustomAxis(self) -> Axis: ...
    @CustomAxis.setter
    def CustomAxis(self, value: Axis) -> None: ...
    @property
    def PathAxisSel(self) -> SelectNXObject: ...
    @PathAxisSel.setter
    def PathAxisSel(self, value: SelectNXObject) -> None: ...


    class AxisType(enum.Enum):
        PathLocations= 0
        Custom= 1
    

class FaceAnnotationBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CgmflBrsr(self) -> str: ...
    @CgmflBrsr.setter
    def CgmflBrsr(self, value: str) -> None: ...
    @property
    def CompSel(self) -> SelectNXObject: ...
    @CompSel.setter
    def CompSel(self, value: SelectNXObject) -> None: ...
    @property
    def DestEnum(self) -> Formboard.FaceAnnotationBuilder.DrwDestination: ...
    @DestEnum.setter
    def DestEnum(self, value: Formboard.FaceAnnotationBuilder.DrwDestination) -> None: ...
    @property
    def PntOrigin(self) -> Point: ...
    @PntOrigin.setter
    def PntOrigin(self, value: Point) -> None: ...
    @property
    def StrAnnot(self) -> str: ...
    @StrAnnot.setter
    def StrAnnot(self, value: str) -> None: ...
    @property
    def StrAnnotFileName(self) -> str: ...
    @StrAnnotFileName.setter
    def StrAnnotFileName(self, value: str) -> None: ...
    @property
    def TogBlank(self) -> bool: ...
    @TogBlank.setter
    def TogBlank(self, value: bool) -> None: ...
    @property
    def Type(self) -> Formboard.FaceAnnotationBuilder.Types: ...
    @Type.setter
    def Type(self, value: Formboard.FaceAnnotationBuilder.Types) -> None: ...


    class Types(enum.Enum):
        ComponentAttribute= 0
        CgmFileSelection= 1
        PatternFileSelection= 2
    

    class DrwDestination(enum.Enum):
        DrawingSheet= 0
        Model= 1
    

