from ....NXOpen import *
from ...GeometricUtilities import *

import typing
import enum

class UVParameterizationBuilder(Builder):
    def __init__(self) -> None: ...
    def Evaluate(self) -> None: ...
    @property
    def Faces(self) -> ScCollector: ...
    @Faces.setter
    def Faces(self, value: ScCollector) -> None: ...
    @property
    def NumberOfGridLines(self) -> int: ...
    @NumberOfGridLines.setter
    def NumberOfGridLines(self, value: int) -> None: ...
    @property
    def OuterBoundarySeedEdge(self) -> SelectEdge: ...
    @OuterBoundarySeedEdge.setter
    def OuterBoundarySeedEdge(self, value: SelectEdge) -> None: ...
    @property
    def RipEdges(self) -> Section: ...
    @RipEdges.setter
    def RipEdges(self, value: Section) -> None: ...
    @property
    def TessellationResolution(self) -> GeometricUtilities.UVMapping.UVParameterizationBuilder.TessellationResolutions: ...
    @TessellationResolution.setter
    def TessellationResolution(self, value: GeometricUtilities.UVMapping.UVParameterizationBuilder.TessellationResolutions) -> None: ...
    @property
    def Type(self) -> GeometricUtilities.UVMapping.UVParameterizationBuilder.ParameterizationTypes: ...
    @Type.setter
    def Type(self, value: GeometricUtilities.UVMapping.UVParameterizationBuilder.ParameterizationTypes) -> None: ...
    @property
    def UDirectionCurve(self) -> SelectTaggedObject: ...
    @UDirectionCurve.setter
    def UDirectionCurve(self, value: SelectTaggedObject) -> None: ...


    class TessellationResolutions(enum.Enum):
        Coarse= 0
        Standard= 1
        Fine= 2
        ExtraFine= 3
    

    class ParameterizationTypes(enum.Enum):
        ShapePreserving= 0
        LengthPreserving= 1
    

class UVMeshManipulatorData(GeometricUtilities.UVMapping.SelectUVMeshObjectData):
    def __init__(self) -> None: ...
    def SetTransformerToObject(self, selectionData: GeometricUtilities.UVMapping.UVMeshManipulatorData.ObjectSelectionData) -> None: ...
    def SetUAxisDirection(self, canAlignToUDirection: bool) -> None: ...
    def SetVAxisDirection(self, canAlignToVDirection: bool) -> None: ...
    @property
    def Transformer(self) -> GeometricUtilities.TransformerData: ...
    @Transformer.setter
    def Transformer(self, value: GeometricUtilities.TransformerData) -> None: ...


    class UVMeshManipulatorDataObjectSelectionData():
        @property
        def SelectedObject(self) -> NXObject: ...
        @SelectedObject.setter
        def SelectedObject(self, value: NXObject) -> None: ...
        @property
        def SelectionPosition(self) -> Point3d: ...
        @SelectionPosition.setter
        def SelectionPosition(self, value: Point3d) -> None: ...
        @property
        def ViewDirection(self) -> Vector3d: ...
        @ViewDirection.setter
        def ViewDirection(self, value: Vector3d) -> None: ...
        @property
        def IsSnappedPosition(self) -> bool: ...
        @IsSnappedPosition.setter
        def IsSnappedPosition(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
    

    class UVMeshManipulatorData_ObjectSelectionData():
        @property
        def selectedObject(self) -> Tag: ...
        @selectedObject.setter
        def selectedObject(self, value: Tag) -> None: ...
        @property
        def selectionPosition(self) -> Point3d: ...
        @selectionPosition.setter
        def selectionPosition(self, value: Point3d) -> None: ...
        @property
        def viewDirection(self) -> Vector3d: ...
        @viewDirection.setter
        def viewDirection(self, value: Vector3d) -> None: ...
        @property
        def isSnappedPosition(self) -> bool: ...
        @isSnappedPosition.setter
        def isSnappedPosition(self, value: bool) -> None: ...
    

class UVMappingCollection(Utilities.NXRemotableObject):
    def __init__(self, owner: Part) -> None: ...
    def CreateUVParameterizationBuilder(self) -> GeometricUtilities.UVMapping.UVParameterizationBuilder: ...
    def CreateTransformUVParameterizationData(self) -> GeometricUtilities.UVMapping.TransformUVParameterizationData: ...
    def CreateReverseUVParameterizationData(self) -> GeometricUtilities.UVMapping.ReverseUVParameterizationData: ...
    def CreateMakeSymmetricParameterizationData(self) -> GeometricUtilities.UVMapping.MakeSymmetricParameterizationData: ...
    def Tag(self) -> Tag: ...



class TransformUVParameterizationData(Builder):
    def __init__(self) -> None: ...
    def Update(self) -> None: ...
    @property
    def CanMoveToolOnly(self) -> bool: ...
    @CanMoveToolOnly.setter
    def CanMoveToolOnly(self, value: bool) -> None: ...
    @property
    def CanRelocateToolToSelection(self) -> bool: ...
    @CanRelocateToolToSelection.setter
    def CanRelocateToolToSelection(self, value: bool) -> None: ...
    @property
    def CanReorientToolToSelection(self) -> bool: ...
    @CanReorientToolToSelection.setter
    def CanReorientToolToSelection(self, value: bool) -> None: ...
    @property
    def CanScaleUniformly(self) -> bool: ...
    @CanScaleUniformly.setter
    def CanScaleUniformly(self, value: bool) -> None: ...
    @property
    def UVMeshManipulator(self) -> GeometricUtilities.UVMapping.UVMeshManipulatorData: ...
    @UVMeshManipulator.setter
    def UVMeshManipulator(self, value: GeometricUtilities.UVMapping.UVMeshManipulatorData) -> None: ...


class SelectUVMeshObjectData(TaggedObject):
    def __init__(self) -> None: ...
    def ClearAndAdd(self, objects: typing.List[NXObject], view: View, point: Point3d) -> None: ...
    def SetCursorLocation(self, point: Point3d) -> None: ...
    def SetViewDirection(self, direction: Vector3d) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def SelectionList(self) -> SelectDisplayableObjectList: ...
    @SelectionList.setter
    def SelectionList(self, value: SelectDisplayableObjectList) -> None: ...


class ReverseUVParameterizationData(Builder):
    def __init__(self) -> None: ...
    @property
    def CanReverseU(self) -> bool: ...
    @CanReverseU.setter
    def CanReverseU(self, value: bool) -> None: ...
    @property
    def CanReverseV(self) -> bool: ...
    @CanReverseV.setter
    def CanReverseV(self, value: bool) -> None: ...
    @property
    def Patches(self) -> SelectDisplayableObjectList: ...
    @Patches.setter
    def Patches(self, value: SelectDisplayableObjectList) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MakeSymmetricParameterizationData(Builder):
    def __init__(self) -> None: ...
    @property
    def Point(self) -> Point: ...
    @Point.setter
    def Point(self, value: Point) -> None: ...
    @property
    def ReverseDirection(self) -> bool: ...
    @ReverseDirection.setter
    def ReverseDirection(self, value: bool) -> None: ...
    @property
    def Type(self) -> GeometricUtilities.UVMapping.MakeSymmetricParameterizationData.Types: ...
    @Type.setter
    def Type(self, value: GeometricUtilities.UVMapping.MakeSymmetricParameterizationData.Types) -> None: ...
    @property
    def UVPatches(self) -> SelectNXObject: ...
    @UVPatches.setter
    def UVPatches(self, value: SelectNXObject) -> None: ...


    class Types(enum.Enum):
        SymmetryInU= 0
        SymmetryInV= 1
    

