from . import SaveManagement
from ...NXOpen import *

import typing
import enum

class WebAppSession(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def CreateCustomWebAppMenuHandler(self) -> PDM.CustomWebAppMenuHandler: ...
    def Open(self, databaseObjects: typing.List[PDM.DatabaseObject]) -> None: ...
    def ShowSummary(self, uid: str, objType: str, classId: str) -> None: ...
    def OpenProductContext(self, uid: str, loadStatus: PartLoadStatus) -> BasePart: ...
    def ShapeSearch(self, uid: str, part: BasePart, classId: str) -> None: ...
    def Tag(self) -> Tag: ...



class VariantRulesConfigurationBuilder(Builder):
    def __init__(self) -> None: ...
    def GetVariantRulesForProductAssembly(self, contextId: str, revId: str) -> str: ...
    def GetVariantRulesSelectedForConfiguration(self, contextIds: str, variantRules: str) -> None: ...
    def AddVariantRulesToConfigure(self, contextIds: str, variantRules: str) -> None: ...


class VariantConfigurationBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def AskAvailableVariantRules(self, contextId: str, revId: str) -> str: ...
    def GetVariantRuleTableInformation(self, contextIds: str, variantRules: str) -> None: ...
    def RemoveVariantRule(self, contextId: str, variantRule: str) -> None: ...
    def AddMultipleVariantRules(self, contextIds: str, variantRules: str) -> None: ...
    def Validate(self) -> bool: ...


class TracelinkQuery(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def GetTracelinkRelationsXml(self) -> str: ...


class TcinUtils(Utilities.NXRemotableObject):
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    def ConvertLegacyDesignControlElements(self, designControlElements: typing.List[Assemblies.Component], legacyDCEIds: str, newDesignFeatureIds: str) -> None: ...
    def CreateVariantExpressions(self, parts: typing.List[Part]) -> None: ...
    def CreatePCAExpressions(self, parts: typing.List[Part]) -> None: ...
    def Tag(self) -> Tag: ...



class SoaQuery(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def AddFieldDescription(self, searchVar: PDM.PdmSearch, type: PDM.PdmSoaqueryNxmgrfielddatatype, name: str, attrName: str, defaultValue: str, logicalOperation: str, mathOperation: str, lov: PDM.ListOfValues) -> None: ...


class SmartSaveObject(NXObject):
    def __init__(self) -> None: ...
    def GetModificationReason(self) -> str: ...
    def IsFrozenByStatus(self) -> bool: ...
    def IsModifiable(self) -> bool: ...
    def HasAddContentPrivilege(self) -> bool: ...
    def HasRemoveContentPrivilege(self) -> bool: ...
    def IsNonMaster(self) -> bool: ...
    def IsMajorRevisable(self) -> bool: ...
    def IsReleased(self) -> bool: ...
    def IsCheckedOutByAnotherUser(self) -> bool: ...
    def IsExplicitCheckOutNeeded(self) -> bool: ...
    def IsDisplayedOnTheSaveDialog(self) -> bool: ...
    def SetAsDisplayedOnTheSaveDialog(self, markDisplayedOnDialog: bool) -> None: ...
    def GetCurrentOperationType(self) -> PDM.SmartSaveObject.OperationType: ...
    def SetCurrentOperationType(self, newOperationType: PDM.SmartSaveObject.OperationType) -> None: ...
    def GetValidOperationTypes(self) -> typing.List[PDM.SmartSaveObject.OperationType]: ...
    def GetTeamcenterObjectType(self) -> str: ...
    def SetValidOperationTypes(self, newValidOperationTypes: typing.List[PDM.SmartSaveObject.OperationType]) -> None: ...
    def GetEffectivityFormula(self) -> str: ...
    def SetEffectivityFormula(self, effectivityFormula: str, effectivityDisplayString: str) -> None: ...


    class OperationType(enum.Enum):
        None_= -1
        Create= 0
        Revise= 1
        SaveAs= 2
        Save= 3
        Delete= 4
    

class SmartSaveContext(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def SetWorkObjectToRootObjectMap(self, workObjects: typing.List[TaggedObject], rootObjects: typing.List[TaggedObject]) -> None: ...
    def GetWorkObjectToRootObjectMap(self, workObjects: typing.List[TaggedObject], rootObjects: typing.List[TaggedObject]) -> None: ...
    def GetSaveType(self) -> PDM.SmartSaveBuilder.SaveType: ...


class SmartSaveBuilder(Builder):
    def __init__(self) -> None: ...
    def GetSmartSaveObjects(self, smartSaveObjects: typing.List[PDM.SmartSaveObject]) -> None: ...
    def OnOperationTypeChanged(self, smartSaveObjects: typing.List[PDM.SmartSaveObject], operationType: AttributePropertiesBuilder.OperationType) -> None: ...
    def GetOperationFailures(self) -> ErrorList: ...
    def ClearValidationFailures(self) -> None: ...
    def UpdateSmartSaveObjectsOnBuilder(self) -> None: ...
    def CanPerformDefaultSave(self) -> bool: ...
    def ValidateSmartSaveObjects(self) -> None: ...
    def CreateSpecificationsForSmartSaveObjects(self, smartSaveObjects: typing.List[PDM.SmartSaveObject]) -> None: ...
    def GetErrorMessageHandler(self, refresh: bool) -> PDM.ErrorMessageHandler: ...
    def AssignRemoveProjects(self, smartSaveObjects: typing.List[PDM.SmartSaveObject], projectNames: str, assignmentStates: typing.List[Session.ProjectAssignmentState]) -> None: ...
    def GetAssociatedChangeNoticeNames(self, smartSaveObjects: typing.List[PDM.SmartSaveObject]) -> str: ...
    def GetAlternateIDManager(self, logicalObject: PDM.LogicalObject) -> PDM.AlternateIdManager: ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList: ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList: ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject: ...
    @property
    def DebugDumpEnabled(self) -> bool: ...
    @DebugDumpEnabled.setter
    def DebugDumpEnabled(self, value: bool) -> None: ...
    @property
    def UseNewSortForDebug(self) -> bool: ...
    @UseNewSortForDebug.setter
    def UseNewSortForDebug(self, value: bool) -> None: ...


    class SaveType(enum.Enum):
        Save= 0
        SaveAll= 1
        SavePreciseAssembly= 2
        SaveWorkPartOnly= 3
        SaveAndClose= 4
        SaveDesignElements= 5
        ForceSaveAll= 6
    

    class DialogType(enum.Enum):
        Save= 0
        StageModelSaveAs= 1
        DesignSessionSaveAs= 2
    

class SheetRevision(PDM.ConditionalElementRevision):
    def __init__(self) -> None: ...


class SessionSettings(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def GetGroups(self) -> str: ...
    def GetRoles(self) -> str: ...
    def GetVolumes(self) -> str: ...
    def GetLocalVolumes(self) -> str: ...
    def GetLocationCodes(self) -> str: ...
    def GetProjects(self) -> str: ...
    def Apply(self) -> None: ...
    def FreeResource(self) -> None: ...
    def DumpValidationInfo(self, logFileName: str) -> None: ...
    def ApplyAndRefresh(self) -> None: ...
    @property
    def AdministrationBypass(self) -> bool: ...
    @AdministrationBypass.setter
    def AdministrationBypass(self, value: bool) -> None: ...
    @property
    def AdministrationLogging(self) -> bool: ...
    @AdministrationLogging.setter
    def AdministrationLogging(self, value: bool) -> None: ...
    @property
    def ApplicationLogging(self) -> bool: ...
    @ApplicationLogging.setter
    def ApplicationLogging(self, value: bool) -> None: ...
    @property
    def Group(self) -> str: ...
    @Group.setter
    def Group(self, value: str) -> None: ...
    @property
    def IsAdministrator(self) -> bool: ...
    @IsAdministrator.setter
    def IsAdministrator(self, value: bool) -> None: ...
    @property
    def Journaling(self) -> bool: ...
    @Journaling.setter
    def Journaling(self, value: bool) -> None: ...
    @property
    def LocalVolume(self) -> str: ...
    @LocalVolume.setter
    def LocalVolume(self, value: str) -> None: ...
    @property
    def LocationCode(self) -> str: ...
    @LocationCode.setter
    def LocationCode(self, value: str) -> None: ...
    @property
    def Project(self) -> str: ...
    @Project.setter
    def Project(self, value: str) -> None: ...
    @property
    def Role(self) -> str: ...
    @Role.setter
    def Role(self, value: str) -> None: ...
    @property
    def SecurityLogging(self) -> bool: ...
    @SecurityLogging.setter
    def SecurityLogging(self, value: bool) -> None: ...
    @property
    def Volume(self) -> str: ...
    @Volume.setter
    def Volume(self, value: str) -> None: ...


class SearchResult(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def GetResultObjectNames(self) -> str: ...
    def GetResultItemIds(self) -> str: ...
    def GetResultMfkIds(self) -> str: ...
    def GetResultObjectTypes(self) -> str: ...


class SaveAsReviseObserver(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[PDM.SaveAsReviseCallbackData]: ...
    @typing.overload
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def AddPrecopyoperationCallback(self, precopyoperationCb: PDM.SaveAsReviseObserver.PrecopyoperationCb) -> int: ...
    def RemovePrecopyoperationCallback(self, id: int) -> None: ...
    def AddPostcopyoperationCallback(self, postcopyoperationCb: PDM.SaveAsReviseObserver.PostcopyoperationCb) -> int: ...
    def RemovePostcopyoperationCallback(self, id: int) -> None: ...
    def Tag(self) -> Tag: ...



    

    

    

    

    

    

class SaveAsReviseCallbackData(TaggedObject):
    def __init__(self) -> None: ...
    def GetSourceObjects(self, sourceObjects: typing.List[TaggedObject]) -> int: ...
    def GetCopiedObjects(self, sourceObjects: TaggedObject, copiedObjects: typing.List[TaggedObject]) -> None: ...


class RequirementUtils(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def NewTracelinkQuery(self) -> PDM.TracelinkQuery: ...
    def CreateTraceLinks(self, requirementItemNumbers: str, requirementRevisions: str, parts: str) -> None: ...
    def RemoveTraceLinks(self, requirementItemNumbers: str, requirementRevisions: str, parts: str) -> None: ...
    def Tag(self) -> Tag: ...



class PortArtifact(NXObject):
    def __init__(self) -> None: ...


class PersistentSettings(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def GetGroups(self) -> str: ...
    def GetVolumes(self) -> str: ...
    def Apply(self) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def Group(self) -> str: ...
    @Group.setter
    def Group(self, value: str) -> None: ...
    @property
    def Volume(self) -> str: ...
    @Volume.setter
    def Volume(self, value: str) -> None: ...


class PendingComponentsManager(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def GetComponents(self) -> str: ...
    def GetComponentPartFileName(self, handle: str) -> str: ...
    def ComponentHasPosition(self, handle: str) -> bool: ...
    def DeleteComponent(self, handle: str) -> None: ...
    def AddComponent(self, handle: str, loadStatus: PartLoadStatus) -> Assemblies.Component: ...
    def AddNgcComponent(self, handle: str, loadStatus: PartLoadStatus) -> Assemblies.Component: ...
    def FreeResource(self) -> None: ...


class PdmSoaqueryNxmgrfielddatatype(enum.Enum):
    Char= 2001
    Date= 2002
    Double= 2003
    Float= 2004
    Int= 2005
    Bool= 2006
    Short= 2007
    String= 2008
    Reference= 2009
    UntypedReference= 2010
    ExternalReference= 2011


class PdmSession(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetTcserverSettings(self, connectString: str, discriminator: str) -> None: ...
    def GetSsoSettings(self, isSsoEnabled: bool, ssoServerUrl: str, ssoAppID: str) -> None: ...
    def SetDefaultFolder(self, defaultFolderSpec: str) -> None: ...
    def NewFileManagement(self) -> PDM.FileManagement: ...
    def NewCaeFileContainer(self) -> PDM.CAEFileContainer: ...
    def CreateCopyOperationBuilder(self, operation: PDM.PartOperationBuilder.OperationType) -> PDM.PartOperationCopyBuilder: ...
    def CreateCreateOperationBuilder(self, operation: PDM.PartOperationBuilder.OperationType) -> PDM.PartOperationCreateBuilder: ...
    def CreateOperationBuilder(self, operation: PDM.PartOperationBuilder.OperationType) -> PDM.PartOperationBuilder: ...
    def CreateObjectCreateBuilder(self, tcTypes: str, baseTCTypes: str) -> PDM.ObjectCreateBuilder: ...
    def CreateMakeUniqueOperationBuilder(self, part: BasePart) -> PDM.PartOperationMakeUniqueBuilder: ...
    def CreateImportOperationBuilder(self) -> PDM.PartOperationImportBuilder: ...
    def CreatePartOperationAttributePropertiesBuilder(self, objects: typing.List[NXObject]) -> PDM.PartOperationAttributePropertiesBuilder: ...
    def CreatePartOperationValidationPropertiesBuilder(self, objects: typing.List[NXObject]) -> AttributePropertiesBuilder: ...
    def GetDatabaseObjectManager(self) -> PDM.DatabaseObjectManager: ...
    def CreateSmartSaveBuilder(self, saveType: PDM.SmartSaveBuilder.SaveType) -> PDM.SmartSaveBuilder: ...
    def CreateSmartSaveContext(self, saveType: PDM.SmartSaveBuilder.SaveType) -> PDM.SmartSaveContext: ...
    def CreateSmartSaveContextWithDialogType(self, dialogType: PDM.SmartSaveBuilder.DialogType, saveType: PDM.SmartSaveBuilder.SaveType) -> PDM.SmartSaveContext: ...
    def CreateSmartSaveBuilderWithContext(self, smartSaveContext: PDM.SmartSaveContext) -> PDM.SmartSaveBuilder: ...
    def CreateExportWorksetForReferenceBuilder(self, workset: BasePart) -> PDM.ExportWorksetForReferenceBuilder: ...
    def SetActiveEngineeringChangeNotice(self, part: NXObject, ecnMFKId: str, ecnRevsionId: str) -> None: ...
    def SetNativeMode(self, enable: bool, rereadTemplateInformation: bool) -> None: ...
    def CreateExternalFileReferenceListBuilder(self, objects: typing.List[NXObject]) -> PDM.ExternalFileReferenceListBuilder: ...
    def GetCheckedoutStatusOfAllObjectsInSession(self, checkedOutObjects: typing.List[NXObject], uncheckedOutObjects: typing.List[NXObject]) -> None: ...
    def CreateFolder(self, newFolderName: str, parentFolderName: str) -> None: ...
    def GetItemTypes(self) -> str: ...
    def GetUserName(self) -> str: ...
    def GetUserGroup(self) -> str: ...
    def GetUserRole(self) -> str: ...
    def ExportFromTeamcenterCreate(self, part: TaggedObject) -> PDM.ExportFromTeamcenter: ...
    def CreatePdmCopyOrEditOperationBuilder(self) -> PDM.PdmCopyOrEditOperationBuilder: ...
    def CreatePdmCopyOrEditOperationAttributePropertiesBuilder(self, objects: typing.List[NXObject]) -> AttributePropertiesBuilder: ...
    def Tag(self) -> Tag: ...

    @property
    def AttributeGroupDescriptions(self) -> PDM.AttributeGroupDescriptionCollection: ...
    @AttributeGroupDescriptions.setter
    def AttributeGroupDescriptions(self, value: PDM.AttributeGroupDescriptionCollection) -> None: ...
    @property
    def PartOperationImportObserver(self) -> PDM.PartOperationImportObserver: ...
    @PartOperationImportObserver.setter
    def PartOperationImportObserver(self, value: PDM.PartOperationImportObserver) -> None: ...
    @property
    def SaveObserver(self) -> PDM.SaveManagement.SaveObserver: ...
    @SaveObserver.setter
    def SaveObserver(self, value: PDM.SaveManagement.SaveObserver) -> None: ...
    @property
    def SaveAsReviseObserver(self) -> PDM.SaveAsReviseObserver: ...
    @SaveAsReviseObserver.setter
    def SaveAsReviseObserver(self, value: PDM.SaveAsReviseObserver) -> None: ...
    @property
    def TcinUtils(self) -> PDM.TcinUtils: ...
    @TcinUtils.setter
    def TcinUtils(self, value: PDM.TcinUtils) -> None: ...
    @property
    def PartNameGenerator(self) -> PDM.PartNameGenerator: ...
    @PartNameGenerator.setter
    def PartNameGenerator(self, value: PDM.PartNameGenerator) -> None: ...
    @property
    def PartAttributeAssignmentObserver(self) -> PDM.PartAttributeAssignmentObserver: ...
    @PartAttributeAssignmentObserver.setter
    def PartAttributeAssignmentObserver(self, value: PDM.PartAttributeAssignmentObserver) -> None: ...
    @property
    def PdmCopyOrEditOperationObserver(self) -> PDM.PdmCopyOrEditOperationObserver: ...
    @PdmCopyOrEditOperationObserver.setter
    def PdmCopyOrEditOperationObserver(self, value: PDM.PdmCopyOrEditOperationObserver) -> None: ...


class PdmSearchManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def NewPdmSearch(self) -> PDM.PdmSearch: ...
    def NewPdmSoaquery(self) -> PDM.SoaQuery: ...
    def NewPdmSearchresult(self) -> PDM.SearchResult: ...
    def NewPdmListofvalues(self) -> PDM.ListOfValues: ...
    def Tag(self) -> Tag: ...



class PdmSearch(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def Advanced(self, entries: str, values: str) -> PDM.SearchResult: ...
    def Simple(self, searchCriteria: str) -> PDM.SearchResult: ...


class PdmPart(Utilities.NXRemotableObject):
    def __init__(self, owner: BasePart) -> None: ...
    def NewAlternateIdManager(self) -> PDM.AlternateIdManager: ...
    def NewDatabaseAttributeManager(self) -> PDM.DatabaseAttributeManager: ...
    def Checkout(self) -> None: ...
    def AssignPermanentName(self, newFileName: str) -> None: ...
    def SetDefaultFolderForPart(self) -> None: ...
    def CheckoutParts(self, partsToCheckOut: typing.List[BasePart], checkOutInput: PDM.PdmPart.CheckoutInput) -> PDM.OperationErrors: ...
    def CheckinParts(self, partsToCheckIn: typing.List[BasePart], checkInInput: PDM.PdmPart.CheckinInput) -> PDM.OperationErrors: ...
    def SetPreciseStructureOnSave(self, partsToSetPreciseOnSave: typing.List[BasePart]) -> None: ...
    def PublishHdImagesForModelViews(self, imageWidth: int, imageHight: int) -> None: ...
    def GetCheckedoutStatusAndUser(self, isCheckedOut: bool, checkedOutBy: str) -> None: ...
    def ListNonMasters(self, nonMasterFileType: str) -> str: ...
    def IsModifiable(self) -> bool: ...
    def GetOwnerAndGroup(self, owner: str, group: str) -> None: ...
    def GetProjects(self) -> str: ...
    def GetReleaseStatus(self) -> str: ...
    def ApplyVariantExpressions(self, pcaexpressionsInInput: typing.List[PDM.PdmPart.PcaexpressionsInput]) -> None: ...
    def GetRelatedDrawings(self) -> str: ...
    def ClearPreciseStructureOnSave(self, cancelPreciseOnSave: typing.List[BasePart]) -> None: ...
    def Tag(self) -> Tag: ...



    class PdmPartPcaexpressionsInput():
        @property
        def Name(self) -> str: ...
        @Name.setter
        def Name(self, value: str) -> None: ...
        @property
        def Value(self) -> str: ...
        @Value.setter
        def Value(self, value: str) -> None: ...
        @property
        def Unit(self) -> str: ...
        @Unit.setter
        def Unit(self, value: str) -> None: ...
        @property
        def SavedVariants(self) -> str: ...
        @SavedVariants.setter
        def SavedVariants(self, value: str) -> None: ...
        @property
        def Optionfamily(self) -> str: ...
        @Optionfamily.setter
        def Optionfamily(self, value: str) -> None: ...
        @property
        def OptionName(self) -> str: ...
        @OptionName.setter
        def OptionName(self, value: str) -> None: ...
        def ToString(self) -> str: ...
    

    class PdmPartCheckoutInput():
        @property
        def InputComment(self) -> str: ...
        @InputComment.setter
        def InputComment(self, value: str) -> None: ...
        @property
        def InputChangeId(self) -> str: ...
        @InputChangeId.setter
        def InputChangeId(self, value: str) -> None: ...
        @property
        def AllowRemote(self) -> bool: ...
        @AllowRemote.setter
        def AllowRemote(self, value: bool) -> None: ...
        @property
        def ExplicitCheckOut(self) -> bool: ...
        @ExplicitCheckOut.setter
        def ExplicitCheckOut(self, value: bool) -> None: ...
        @property
        def IncludeSecondary(self) -> bool: ...
        @IncludeSecondary.setter
        def IncludeSecondary(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
    

    class PdmPartCheckinInput():
        @property
        def AllowRemote(self) -> bool: ...
        @AllowRemote.setter
        def AllowRemote(self, value: bool) -> None: ...
        @property
        def ExplicitCheckIn(self) -> bool: ...
        @ExplicitCheckIn.setter
        def ExplicitCheckIn(self, value: bool) -> None: ...
        @property
        def IncludeSecondary(self) -> bool: ...
        @IncludeSecondary.setter
        def IncludeSecondary(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, AllowRemote: bool, ExplicitCheckIn: bool, IncludeSecondary: bool) -> None: ...
    

    class PdmPart_PcaexpressionsInput():
        @property
        def name(self) -> int: ...
        @name.setter
        def name(self, value: int) -> None: ...
        @property
        def value(self) -> int: ...
        @value.setter
        def value(self, value: int) -> None: ...
        @property
        def unit(self) -> int: ...
        @unit.setter
        def unit(self, value: int) -> None: ...
        @property
        def savedVariants(self) -> int: ...
        @savedVariants.setter
        def savedVariants(self, value: int) -> None: ...
        @property
        def optionfamily(self) -> int: ...
        @optionfamily.setter
        def optionfamily(self, value: int) -> None: ...
        @property
        def optionName(self) -> int: ...
        @optionName.setter
        def optionName(self, value: int) -> None: ...
    

    class PdmPart_CheckoutInput():
        @property
        def inputComment(self) -> int: ...
        @inputComment.setter
        def inputComment(self, value: int) -> None: ...
        @property
        def inputChangeId(self) -> int: ...
        @inputChangeId.setter
        def inputChangeId(self, value: int) -> None: ...
        @property
        def allowRemote(self) -> bool: ...
        @allowRemote.setter
        def allowRemote(self, value: bool) -> None: ...
        @property
        def explicitCheckOut(self) -> bool: ...
        @explicitCheckOut.setter
        def explicitCheckOut(self, value: bool) -> None: ...
        @property
        def includeSecondary(self) -> bool: ...
        @includeSecondary.setter
        def includeSecondary(self, value: bool) -> None: ...
    

class PdmNavigatorNode(TreeListNode):
    def __init__(self) -> None: ...
    def GetUid(self) -> str: ...
    def GetNodeType(self) -> str: ...


class PdmFile(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def GetFileName(self) -> str: ...
    def GetFileLastModifiedDate(self) -> str: ...
    def GetFileSize(self) -> str: ...


class PdmCopyOrEditOperationObserver(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[PDM.PdmCopyOrEditOperationCallbackData]: ...
    @typing.overload
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def AddInitializeCallback(self, initializeCb: PDM.PdmCopyOrEditOperationObserver.InitializeCallback) -> int: ...
    def RemoveInitializeCallback(self, id: int) -> None: ...
    def AddPreAutoassignCallback(self, preAutoassignCb: PDM.PdmCopyOrEditOperationObserver.PreAutoassignCallback) -> int: ...
    def RemovePreAutoassignCallback(self, id: int) -> None: ...
    def AddPreCommitCallback(self, preCommitCb: PDM.PdmCopyOrEditOperationObserver.PreCommitCallback) -> int: ...
    def RemovePreCommitCallback(self, id: int) -> None: ...
    def AddPostCommitCallback(self, postCommitCb: PDM.PdmCopyOrEditOperationObserver.PostCommitCallback) -> int: ...
    def RemovePostCommitCallback(self, id: int) -> None: ...
    def AddTerminateCallback(self, terminateCb: PDM.PdmCopyOrEditOperationObserver.TerminateCallback) -> int: ...
    def RemoveTerminateCallback(self, id: int) -> None: ...
    def AddPreValidateCallback(self, preValidateCb: PDM.PdmCopyOrEditOperationObserver.PreValidateCallback) -> int: ...
    def RemovePreValidateCallback(self, id: int) -> None: ...
    def Tag(self) -> Tag: ...



    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

class PdmCopyOrEditOperationObject(NXObject):
    def __init__(self) -> None: ...
    def GetCurrentPrimaryLogicalObject(self) -> PDM.LogicalObject: ...
    def GetSecondaryLogicalObjects(self, secondaryLogicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    def GetInitialName(self) -> str: ...
    def GetFinalName(self) -> str: ...


class PdmCopyOrEditOperationCallbackData(TaggedObject):
    def __init__(self) -> None: ...
    def GetBuilder(self) -> PDM.PdmCopyOrEditOperationBuilder: ...


class PdmCopyOrEditOperationBuilder(PDM.PartOperationBuilder):
    def __init__(self) -> None: ...
    def AddParts(self, parts: str, errorMsgs: str) -> None: ...
    def AddPartsUsingCloneLogFile(self, logFilePath: str, errorMsgs: str) -> None: ...
    def ExecuteDryRun(self) -> None: ...
    def ValidateOperationObjects(self) -> None: ...
    def SetLoadOption(self, loadOption: LoadOptions.ManagedModeLoadMethod) -> None: ...
    def SetConfigurationContextUsingRevRule(self, setDefault: bool, revisionRuleName: str) -> int: ...
    def GetDefaultProjectInformation(self, projectNames: str, assignmentStates: typing.List[Session.ProjectAssignmentState]) -> None: ...
    def SetDefaultProjectInformation(self, projectNames: str, assignmentStates: typing.List[Session.ProjectAssignmentState]) -> None: ...
    def UpdateTeamcenterInformation(self, objects: typing.List[NXObject]) -> None: ...
    def ResetAttributes(self, objects: typing.List[NXObject]) -> None: ...
    def CreateOrUpdatePdmCopyOrEditOperationObjects(self, doUpdate: bool, copyOperationObjects: typing.List[PDM.PdmCopyOrEditOperationObject]) -> None: ...
    def GetPdmCopyOrEditOperationObjects(self, copyOperationObjects: typing.List[PDM.PdmCopyOrEditOperationObject]) -> None: ...
    def GetPdmCopyOrEditOperationObject(self, partFilename: str) -> PDM.PdmCopyOrEditOperationObject: ...
    def SetCloneAction(self, operationObject: PDM.PdmCopyOrEditOperationObject, cloneAction: PDM.PdmCopyOrEditOperationBuilder.CloneAction, modifiedLogicalObjects: typing.List[PDM.PdmCopyOrEditOperationObject]) -> None: ...
    def SetReplacePart(self, operationObject: PDM.PdmCopyOrEditOperationObject, replacePartCliSpec: str) -> int: ...
    def SetOverwritePart(self, operationObject: PDM.PdmCopyOrEditOperationObject, transientPartCliSpec: str) -> int: ...
    @property
    def AssignAlternateIds(self) -> bool: ...
    @AssignAlternateIds.setter
    def AssignAlternateIds(self, value: bool) -> None: ...
    @property
    def AssignDefaultChangeNotice(self) -> bool: ...
    @AssignDefaultChangeNotice.setter
    def AssignDefaultChangeNotice(self, value: bool) -> None: ...
    @property
    def AttachLogFile(self) -> bool: ...
    @AttachLogFile.setter
    def AttachLogFile(self, value: bool) -> None: ...
    @property
    def ConversionType(self) -> PDM.PdmCopyOrEditOperationBuilder.ConversionRule: ...
    @ConversionType.setter
    def ConversionType(self, value: PDM.PdmCopyOrEditOperationBuilder.ConversionRule) -> None: ...
    @property
    def CopyAltrep(self) -> bool: ...
    @CopyAltrep.setter
    def CopyAltrep(self, value: bool) -> None: ...
    @property
    def CopyAssociatedFiles(self) -> bool: ...
    @CopyAssociatedFiles.setter
    def CopyAssociatedFiles(self, value: bool) -> None: ...
    @property
    def CopyCaeMotion(self) -> bool: ...
    @CopyCaeMotion.setter
    def CopyCaeMotion(self, value: bool) -> None: ...
    @property
    def CopyCaeRelationOption(self) -> PDM.PdmCopyOrEditOperationBuilder.CaeRelationTraversalOption: ...
    @CopyCaeRelationOption.setter
    def CopyCaeRelationOption(self, value: PDM.PdmCopyOrEditOperationBuilder.CaeRelationTraversalOption) -> None: ...
    @property
    def CopyCaeRelations(self) -> bool: ...
    @CopyCaeRelations.setter
    def CopyCaeRelations(self, value: bool) -> None: ...
    @property
    def CopyDrawingRelations(self) -> bool: ...
    @CopyDrawingRelations.setter
    def CopyDrawingRelations(self, value: bool) -> None: ...
    @property
    def CopyManifestation(self) -> bool: ...
    @CopyManifestation.setter
    def CopyManifestation(self, value: bool) -> None: ...
    @property
    def CopySpecification(self) -> bool: ...
    @CopySpecification.setter
    def CopySpecification(self, value: bool) -> None: ...
    @property
    def DefaultAction(self) -> PDM.PdmCopyOrEditOperationBuilder.CloneAction: ...
    @DefaultAction.setter
    def DefaultAction(self, value: PDM.PdmCopyOrEditOperationBuilder.CloneAction) -> None: ...
    @property
    def DefaultAlternateIdContext(self) -> str: ...
    @DefaultAlternateIdContext.setter
    def DefaultAlternateIdContext(self, value: str) -> None: ...
    @property
    def DefaultAlternateIdType(self) -> str: ...
    @DefaultAlternateIdType.setter
    def DefaultAlternateIdType(self, value: str) -> None: ...
    @property
    def DefaultChangeNotice(self) -> str: ...
    @DefaultChangeNotice.setter
    def DefaultChangeNotice(self, value: str) -> None: ...
    @property
    def DefaultOwningGroup(self) -> str: ...
    @DefaultOwningGroup.setter
    def DefaultOwningGroup(self, value: str) -> None: ...
    @property
    def DefaultOwningUser(self) -> str: ...
    @DefaultOwningUser.setter
    def DefaultOwningUser(self, value: str) -> None: ...
    @property
    def IncludeComponentParts(self) -> bool: ...
    @IncludeComponentParts.setter
    def IncludeComponentParts(self, value: bool) -> None: ...
    @property
    def NumberingSource(self) -> PDM.PdmCopyOrEditOperationBuilder.NumberingSourceOption: ...
    @NumberingSource.setter
    def NumberingSource(self, value: PDM.PdmCopyOrEditOperationBuilder.NumberingSourceOption) -> None: ...
    @property
    def OutputLogFile(self) -> str: ...
    @OutputLogFile.setter
    def OutputLogFile(self, value: str) -> None: ...
    @property
    def PrefixStr(self) -> str: ...
    @PrefixStr.setter
    def PrefixStr(self, value: str) -> None: ...
    @property
    def RenumberStr(self) -> str: ...
    @RenumberStr.setter
    def RenumberStr(self, value: str) -> None: ...
    @property
    def ReplaceWithStr(self) -> str: ...
    @ReplaceWithStr.setter
    def ReplaceWithStr(self, value: str) -> None: ...
    @property
    def RetainOwnership(self) -> bool: ...
    @RetainOwnership.setter
    def RetainOwnership(self, value: bool) -> None: ...
    @property
    def StringToReplace(self) -> str: ...
    @StringToReplace.setter
    def StringToReplace(self, value: str) -> None: ...
    @property
    def SuffixStr(self) -> str: ...
    @SuffixStr.setter
    def SuffixStr(self, value: str) -> None: ...


    class NumberingSourceOption(enum.Enum):
        AutoGenerate= 0
        NamingRule= 1
        UserName= 2
    

    class ConversionRule(enum.Enum):
        WithPrefix= 0
        WithSuffix= 1
        WithReplaceString= 2
        WithRenumber= 3
        MixedRule= 4
    

    class CloneAction(enum.Enum):
        Clone= 0
        Retain= 1
        Revise= 2
        Replace= 3
        Overwrite= 4
    

    class CaeRelationTraversalOption(enum.Enum):
        SimFemIdeal= 0
        FemIdeal= 1
        Ideal= 2
        None_= 3
    

class PdmCopyOrEditOperationAttributePropertiesBuilder(AttributePropertiesBuilder):
    def __init__(self) -> None: ...


class PartOperationValidationPropertiesBuilder(AttributePropertiesBuilder):
    def __init__(self) -> None: ...
    def GetValidationRuleSetBrowseOption(self) -> PDM.PartOperationImportBuilder.ValidationRuleSetFileBrowseOption: ...
    def SetValidationRuleSetBrowseOption(self, validationRuleSetBrowseOption: PDM.PartOperationImportBuilder.ValidationRuleSetFileBrowseOption) -> None: ...
    def GetValidationRuleSetFile(self) -> str: ...
    def SetValidationRuleSetFile(self, filename: str) -> None: ...
    def GetValidationTreatWarningAsPass(self) -> bool: ...
    def SetValidationTreatWarningAsPass(self, validationTreatWarningAsPass: bool) -> None: ...
    def GetValidationTreatOutdatedAsPass(self) -> bool: ...
    def SetValidationTreatOutdatedAsPass(self, validationTreatOutdatedAsPass: bool) -> None: ...


class PartOperationMakeUniqueBuilder(PDM.PartOperationCopyBuilder):
    def __init__(self) -> None: ...
    @property
    def SelectedComponents(self) -> SelectDisplayableObjectList: ...
    @SelectedComponents.setter
    def SelectedComponents(self, value: SelectDisplayableObjectList) -> None: ...


class PartOperationImportObserver(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[PDM.PartOperationImportCallbackData]: ...
    @typing.overload
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def AddInitializeCallback(self, initializeCb: PDM.PartOperationImportObserver.InitializeCb) -> int: ...
    def RemoveInitializeCallback(self, id: int) -> None: ...
    def AddPreAutoassignCallback(self, preAutoassignCb: PDM.PartOperationImportObserver.PreAutoassignCb) -> int: ...
    def RemovePreAutoassignCallback(self, id: int) -> None: ...
    def AddPreCommitCallback(self, preCommitCb: PDM.PartOperationImportObserver.PreCommitCb) -> int: ...
    def RemovePreCommitCallback(self, id: int) -> None: ...
    def AddPostCommitCallback(self, postCommitCb: PDM.PartOperationImportObserver.PostCommitCb) -> int: ...
    def RemovePostCommitCallback(self, id: int) -> None: ...
    def AddTerminateCallback(self, terminateCb: PDM.PartOperationImportObserver.TerminateCb) -> int: ...
    def RemoveTerminateCallback(self, id: int) -> None: ...
    def AddPreValidateCallback(self, preValidateCb: PDM.PartOperationImportObserver.PreValidateCb) -> int: ...
    def RemovePreValidateCallback(self, id: int) -> None: ...
    def Tag(self) -> Tag: ...



    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

class PartOperationImportCallbackData(TaggedObject):
    def __init__(self) -> None: ...
    def GetLogicalObjects(self, logicalObjects: typing.List[PDM.NativePartLogicalObject]) -> None: ...
    @property
    def ImportBuilder(self) -> PDM.PartOperationImportBuilder: ...
    @ImportBuilder.setter
    def ImportBuilder(self, value: PDM.PartOperationImportBuilder) -> None: ...


class PartOperationImportBuilder(PDM.PartOperationBuilder):
    def __init__(self) -> None: ...
    def AddParts(self, parts: str, errorMsgs: str) -> None: ...
    def AddPartsUsingLogFile(self, logFilePath: str, errorMsgs: str) -> None: ...
    def AddPartsFromFolder(self, folderPath: str, errorMsgs: str) -> None: ...
    def GetUpdatedLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    def GetLogicalObjectForPart(self, partFilename: str) -> PDM.LogicalObject: ...
    def ResetAttributes(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    def ExecuteDryRun(self) -> None: ...
    def GetDefaultProjectInformation(self, projectNames: str, assignmentStates: typing.List[Session.ProjectAssignmentState]) -> None: ...
    def SetDefaultProjectInformation(self, projectNames: str, assignmentStates: typing.List[Session.ProjectAssignmentState]) -> None: ...
    def GetDfaFiles(self, dfaFiles: str) -> None: ...
    def SetDfaFiles(self, dfaFiles: str) -> None: ...
    def RemoveDfaFile(self, filename: str) -> None: ...
    def SetExistingPartAttributes(self, logicalObject: PDM.LogicalObject, existingPartCliSpec: str) -> None: ...
    def ValidateLogicalObjects(self) -> None: ...
    def UpdateTeamcenterInformation(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    def OnCancel(self) -> None: ...
    def GetExternalFileObjects(self, logicalObject: PDM.LogicalObject, objects: typing.List[NXObject]) -> None: ...
    @property
    def AddCAENonMastersToImport(self) -> bool: ...
    @AddCAENonMastersToImport.setter
    def AddCAENonMastersToImport(self, value: bool) -> None: ...
    @property
    def AddDfaMixins(self) -> bool: ...
    @AddDfaMixins.setter
    def AddDfaMixins(self, value: bool) -> None: ...
    @property
    def AssignAlternateIds(self) -> bool: ...
    @AssignAlternateIds.setter
    def AssignAlternateIds(self, value: bool) -> None: ...
    @property
    def AssociatedFilesRootDirectory(self) -> str: ...
    @AssociatedFilesRootDirectory.setter
    def AssociatedFilesRootDirectory(self, value: str) -> None: ...
    @property
    def CheckedoutCommentNotMatchError(self) -> bool: ...
    @CheckedoutCommentNotMatchError.setter
    def CheckedoutCommentNotMatchError(self, value: bool) -> None: ...
    @property
    def CheckoutComment(self) -> str: ...
    @CheckoutComment.setter
    def CheckoutComment(self, value: str) -> None: ...
    @property
    def CheckoutOption(self) -> PDM.PartOperationImportBuilder.CheckoutOptionType: ...
    @CheckoutOption.setter
    def CheckoutOption(self, value: PDM.PartOperationImportBuilder.CheckoutOptionType) -> None: ...
    @property
    def ConversionType(self) -> PDM.PartOperationImportBuilder.ConversionRule: ...
    @ConversionType.setter
    def ConversionType(self, value: PDM.PartOperationImportBuilder.ConversionRule) -> None: ...
    @property
    def DefaultAction(self) -> PDM.PartOperationImportBuilder.ExistingPartAction: ...
    @DefaultAction.setter
    def DefaultAction(self, value: PDM.PartOperationImportBuilder.ExistingPartAction) -> None: ...
    @property
    def DefaultAlternateIdContext(self) -> str: ...
    @DefaultAlternateIdContext.setter
    def DefaultAlternateIdContext(self, value: str) -> None: ...
    @property
    def DefaultAlternateIdType(self) -> str: ...
    @DefaultAlternateIdType.setter
    def DefaultAlternateIdType(self, value: str) -> None: ...
    @property
    def DefaultChangeNotice(self) -> str: ...
    @DefaultChangeNotice.setter
    def DefaultChangeNotice(self, value: str) -> None: ...
    @property
    def DefaultDescription(self) -> str: ...
    @DefaultDescription.setter
    def DefaultDescription(self, value: str) -> None: ...
    @property
    def DefaultItemType(self) -> str: ...
    @DefaultItemType.setter
    def DefaultItemType(self, value: str) -> None: ...
    @property
    def DefaultName(self) -> str: ...
    @DefaultName.setter
    def DefaultName(self, value: str) -> None: ...
    @property
    def DefaultOwningGroup(self) -> str: ...
    @DefaultOwningGroup.setter
    def DefaultOwningGroup(self, value: str) -> None: ...
    @property
    def DefaultOwningUser(self) -> str: ...
    @DefaultOwningUser.setter
    def DefaultOwningUser(self, value: str) -> None: ...
    @property
    def IncludeComponentParts(self) -> bool: ...
    @IncludeComponentParts.setter
    def IncludeComponentParts(self, value: bool) -> None: ...
    @property
    def IncludeDependentParts(self) -> bool: ...
    @IncludeDependentParts.setter
    def IncludeDependentParts(self, value: bool) -> None: ...
    @property
    def NotCheckedoutError(self) -> bool: ...
    @NotCheckedoutError.setter
    def NotCheckedoutError(self, value: bool) -> None: ...
    @property
    def NumberAttr(self) -> str: ...
    @NumberAttr.setter
    def NumberAttr(self, value: str) -> None: ...
    @property
    def NumberingSource(self) -> PDM.PartOperationImportBuilder.NumberingSourceOption: ...
    @NumberingSource.setter
    def NumberingSource(self, value: PDM.PartOperationImportBuilder.NumberingSourceOption) -> None: ...
    @property
    def OutputLogFile(self) -> str: ...
    @OutputLogFile.setter
    def OutputLogFile(self, value: str) -> None: ...
    @property
    def PrefixStr(self) -> str: ...
    @PrefixStr.setter
    def PrefixStr(self, value: str) -> None: ...
    @property
    def ProductInterfaces(self) -> bool: ...
    @ProductInterfaces.setter
    def ProductInterfaces(self, value: bool) -> None: ...
    @property
    def PublishJTData(self) -> bool: ...
    @PublishJTData.setter
    def PublishJTData(self, value: bool) -> None: ...
    @property
    def PublishOptionalInfo(self) -> bool: ...
    @PublishOptionalInfo.setter
    def PublishOptionalInfo(self, value: bool) -> None: ...
    @property
    def ReplaceWithStr(self) -> str: ...
    @ReplaceWithStr.setter
    def ReplaceWithStr(self, value: str) -> None: ...
    @property
    def RevisionAttr(self) -> str: ...
    @RevisionAttr.setter
    def RevisionAttr(self, value: str) -> None: ...
    @property
    def StringToReplace(self) -> str: ...
    @StringToReplace.setter
    def StringToReplace(self, value: str) -> None: ...
    @property
    def SuffixStr(self) -> str: ...
    @SuffixStr.setter
    def SuffixStr(self, value: str) -> None: ...
    @property
    def SyncArrangements(self) -> bool: ...
    @SyncArrangements.setter
    def SyncArrangements(self, value: bool) -> None: ...
    @property
    def UseItemTypeFromPartFile(self) -> bool: ...
    @UseItemTypeFromPartFile.setter
    def UseItemTypeFromPartFile(self, value: bool) -> None: ...
    @property
    def ValidationAbortImportOnFail(self) -> bool: ...
    @ValidationAbortImportOnFail.setter
    def ValidationAbortImportOnFail(self, value: bool) -> None: ...
    @property
    def ValidationMode(self) -> PDM.PartOperationImportBuilder.Validation: ...
    @ValidationMode.setter
    def ValidationMode(self, value: PDM.PartOperationImportBuilder.Validation) -> None: ...
    @property
    def ValidationRuleSetBrowseOption(self) -> PDM.PartOperationImportBuilder.ValidationRuleSetFileBrowseOption: ...
    @ValidationRuleSetBrowseOption.setter
    def ValidationRuleSetBrowseOption(self, value: PDM.PartOperationImportBuilder.ValidationRuleSetFileBrowseOption) -> None: ...
    @property
    def ValidationRuleSetFile(self) -> str: ...
    @ValidationRuleSetFile.setter
    def ValidationRuleSetFile(self, value: str) -> None: ...
    @property
    def ValidationTreatOutdatedAsPass(self) -> bool: ...
    @ValidationTreatOutdatedAsPass.setter
    def ValidationTreatOutdatedAsPass(self, value: bool) -> None: ...
    @property
    def ValidationTreatWarningAsPass(self) -> bool: ...
    @ValidationTreatWarningAsPass.setter
    def ValidationTreatWarningAsPass(self, value: bool) -> None: ...


    class ValidationRuleSetFileBrowseOption(enum.Enum):
        Native= 0
        Teamcenter= 1
    

    class Validation(enum.Enum):
        Off= 0
        ImportFromPart= 1
        RunValidation= 2
        RunValidationHybrid= 3
        Default= 4
    

    class NumberingSourceOption(enum.Enum):
        PartIDGenerator= 0
        OSFilename= 1
        Attribute= 2
    

    class ExistingPartAction(enum.Enum):
        Overwrite= 0
        UseExisting= 1
        NewRevision= 2
        Default= 3
    

    class ConversionRule(enum.Enum):
        AsID= 0
        AsIDandRevision= 1
        WithPrefix= 2
        WithSuffix= 3
        WithReplaceString= 4
    

    class CheckoutOptionType(enum.Enum):
        Checkin= 0
        Checkout= 1
        NoChange= 2
    

class PartOperationCreateBuilder(PDM.PartOperationBuilder):
    def __init__(self) -> None: ...
    def SetItemType(self, itemType: str) -> None: ...
    def SetModelType(self, modelType: str) -> None: ...
    def SetMasterPart(self, masterPart: BasePart) -> None: ...
    def GetOperationSubType(self) -> PDM.PartOperationCreateBuilder.OperationSubType: ...
    def SetOperationSubType(self, operatioSubType: PDM.PartOperationCreateBuilder.OperationSubType) -> None: ...
    def SetAddMaster(self, addMaster: bool) -> None: ...
    def SetPartsToRename(self, partsToRename: typing.List[BasePart]) -> None: ...
    def GetAddMaster(self) -> bool: ...
    def SetPartSpecToOpen(self, partSpecToOpen: str) -> None: ...
    def CreateLogicalObjectsUsingSeedPart(self, seedPartName: str, numOfPartsToCreate: int, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...


    class OperationSubType(enum.Enum):
        FromTemplate= 0
        SelectTemplate= 1
        Rename= 2
        CreateSpecification= 3
        RenameNativePartInTc= 4
    

class PartOperationCopyBuilder(PDM.PartOperationBuilder):
    def __init__(self) -> None: ...
    def SetSelectedPartsToCopy(self, selectedParts: typing.List[BasePart], failedParts: typing.List[BasePart]) -> None: ...
    def AddRelatedPartsToCopy(self, basePart: BasePart, relatedParts: typing.List[BasePart], relatedPartsReasons: str, operation: PDM.PartOperationBuilder.OperationType) -> None: ...
    def CreateNonMasterListForCopyLogicalObject(self, logicalObject: PDM.LogicalObject) -> None: ...
    def GetNonMasterListForCopyLogicalObject(self, logicalObject: PDM.LogicalObject) -> str: ...
    def IsNonMasterForLogicalObjectBeingCopied(self, logicalObject: PDM.LogicalObject, partName: str) -> bool: ...
    def GetCopyNonMasterPartsOption(self, logicalObject: PDM.LogicalObject) -> PDM.PartOperationCopyBuilder.CopyNonMasterParts: ...
    def SetCopyNonMasterPartsOption(self, logicalObject: PDM.LogicalObject, saveOption: PDM.PartOperationCopyBuilder.CopyNonMasterParts) -> None: ...
    def SetSelectedNonMasterToCopy(self, logicalObject: PDM.LogicalObject, partName: str) -> None: ...
    def EditNonMasterToCopyName(self, logicalObject: PDM.LogicalObject, oldName: str, newName: str) -> bool: ...
    def GetOperationSubType(self) -> PDM.PartOperationCopyBuilder.OperationSubType: ...
    def SetOperationSubType(self, operationSubType: PDM.PartOperationCopyBuilder.OperationSubType) -> None: ...
    def GetSourcePartFromLogicalObject(self, logicalObject: PDM.LogicalObject) -> Part: ...
    @property
    def DependentFilesToCopyOption(self) -> PDM.PartOperationCopyBuilder.CopyDependentFiles: ...
    @DependentFilesToCopyOption.setter
    def DependentFilesToCopyOption(self, value: PDM.PartOperationCopyBuilder.CopyDependentFiles) -> None: ...
    @property
    def ReplaceAllComponentsInSession(self) -> bool: ...
    @ReplaceAllComponentsInSession.setter
    def ReplaceAllComponentsInSession(self, value: bool) -> None: ...


    class OperationSubType(enum.Enum):
        Default= 0
        MakeUnique= 1
    

    class CopyNonMasterParts(enum.Enum):
        All= 0
        None_= 1
    

    class CopyDependentFiles(enum.Enum):
        All= 0
        None_= 1
    

class PartOperationBuilder(Builder):
    def __init__(self) -> None: ...
    def CreateLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    def GetDialogOperation(self) -> PDM.PartOperationBuilder.OperationType: ...
    def SetDialogOperation(self, dialogOperation: PDM.PartOperationBuilder.OperationType) -> None: ...
    def GetOperationFailures(self) -> ErrorList: ...
    def GetAlternateIDManager(self, logicalObject: PDM.LogicalObject) -> PDM.AlternateIdManager: ...
    def CreateSpecificationsForLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    def ValidateLogicalObjectsToCommit(self) -> None: ...
    def SetSelectedParts(self, selectedParts: typing.List[BasePart], failedParts: typing.List[BasePart]) -> None: ...
    def AddRelatedPartToOperate(self, basePart: BasePart, relatedParts: typing.List[BasePart], relatedPartsReasons: str, operation: PDM.PartOperationBuilder.OperationType) -> None: ...
    def CreateNonMasterListForLogicalObject(self, logicalObject: PDM.LogicalObject) -> None: ...
    def SetNonMasterSaveAsOption(self, logicalObject: PDM.LogicalObject, saveOption: PDM.PartOperationBuilder.NonMasterSaveAs) -> None: ...
    def SetSelectedNonMasterToSaveAs(self, logicalObject: PDM.LogicalObject, partName: str) -> None: ...
    def GetNonMasterList(self, logicalObject: PDM.LogicalObject) -> str: ...
    def IsNonMasterBeingCopied(self, logicalObject: PDM.LogicalObject, partName: str) -> bool: ...
    def GetNonMasterCopyOption(self, logicalObject: PDM.LogicalObject) -> PDM.PartOperationBuilder.NonMasterSaveAs: ...
    def EditNonMasterName(self, logicalObject: PDM.LogicalObject, oldName: str, newName: str) -> bool: ...
    def ClearWarnings(self) -> None: ...
    def GetErrorMessageHandler(self, refresh: bool) -> PDM.ErrorMessageHandler: ...
    def GetCreatedParts(self, commitedParts: typing.List[BasePart]) -> None: ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList: ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList: ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject: ...
    @property
    def DefaultDestinationFolder(self) -> str: ...
    @DefaultDestinationFolder.setter
    def DefaultDestinationFolder(self, value: str) -> None: ...
    @property
    def DependentFileSaveAsOption(self) -> PDM.PartOperationBuilder.DependentFileSaveAs: ...
    @DependentFileSaveAsOption.setter
    def DependentFileSaveAsOption(self, value: PDM.PartOperationBuilder.DependentFileSaveAs) -> None: ...
    @property
    def ReplaceAllComponents(self) -> bool: ...
    @ReplaceAllComponents.setter
    def ReplaceAllComponents(self, value: bool) -> None: ...


    class OperationType(enum.Enum):
        SaveAs= 0
        Revise= 1
        Create= 2
        Import= 3
        Clone= 4
    

    class NonMasterSaveAs(enum.Enum):
        All= 0
        None_= 1
    

    class DependentFileSaveAs(enum.Enum):
        All= 0
        None_= 1
    

class PartOperationAttributePropertiesBuilder(AttributePropertiesBuilder):
    def __init__(self) -> None: ...
    def CreateOrModifyAttribute(self) -> bool: ...
    @property
    def ReferenceObject(self) -> PDM.LogicalObject: ...
    @ReferenceObject.setter
    def ReferenceObject(self, value: PDM.LogicalObject) -> None: ...


class PartNameGenerator(Utilities.NXRemotableObject):
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    def AutoAssignPartParametersForCreate(self, inputInfoPtr: PDM.PartNameGenerator.PartAssignInputInfo) -> str: ...
    def Tag(self) -> Tag: ...



    class PartNameGeneratorPartAssignInputInfo():
        @property
        def ItemType(self) -> str: ...
        @ItemType.setter
        def ItemType(self, value: str) -> None: ...
        @property
        def ModelType(self) -> str: ...
        @ModelType.setter
        def ModelType(self, value: str) -> None: ...
        @property
        def BasePartNumber(self) -> str: ...
        @BasePartNumber.setter
        def BasePartNumber(self, value: str) -> None: ...
        @property
        def BasePartRevision(self) -> str: ...
        @BasePartRevision.setter
        def BasePartRevision(self, value: str) -> None: ...
        @property
        def BasePartName(self) -> str: ...
        @BasePartName.setter
        def BasePartName(self, value: str) -> None: ...
        @property
        def GenerateNextItemId(self) -> bool: ...
        @GenerateNextItemId.setter
        def GenerateNextItemId(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
    

    class PartNameGenerator_PartAssignInputInfo():
        @property
        def itemType(self) -> int: ...
        @itemType.setter
        def itemType(self, value: int) -> None: ...
        @property
        def modelType(self) -> int: ...
        @modelType.setter
        def modelType(self, value: int) -> None: ...
        @property
        def basePartNumber(self) -> int: ...
        @basePartNumber.setter
        def basePartNumber(self, value: int) -> None: ...
        @property
        def basePartRevision(self) -> int: ...
        @basePartRevision.setter
        def basePartRevision(self, value: int) -> None: ...
        @property
        def basePartName(self) -> int: ...
        @basePartName.setter
        def basePartName(self, value: int) -> None: ...
        @property
        def generateNextItemId(self) -> bool: ...
        @generateNextItemId.setter
        def generateNextItemId(self, value: bool) -> None: ...
    

class PartManager(Utilities.NXRemotableObject):
    def __init__(self, owner: PartCollection) -> None: ...
    def NewPartFromTemplateBuilder(self) -> PDM.PartFromTemplateBuilder: ...
    def NewPartFromPartBuilder(self) -> PDM.PartFromPartBuilder: ...
    def NewPendingComponentsManager(self, part: BasePart) -> PDM.PendingComponentsManager: ...
    def GetCaeCloneManager(self, part: BasePart) -> PDM.CaeCloneManager: ...
    def Tag(self) -> Tag: ...



class PartFromTemplateBuilder(PDM.PartBuilder):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def SetSeedPart(self, seedName: str) -> None: ...
    @typing.overload
    def Commit(self) -> BasePart: ...
    @typing.overload
    def Commit(self, setAsDisplayPart: bool) -> BasePart: ...


class PartFromPartBuilder(PDM.PartBuilder):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def CreateNonmasterList(self) -> None: ...
    def GetNonmasterList(self) -> str: ...
    def GetNonmasterToSaveAs(self, partName: str) -> bool: ...
    def SetNonmasterToSaveAs(self, partName: str, doSaveAs: bool) -> None: ...
    def EditNonmasterNameToSaveAs(self, oldName: str, newName: str) -> bool: ...
    def Commit(self) -> None: ...
    @property
    def DependentFileSaveAsOption(self) -> PDM.PartFromPartBuilder.FileSaveAs: ...
    @DependentFileSaveAsOption.setter
    def DependentFileSaveAsOption(self, value: PDM.PartFromPartBuilder.FileSaveAs) -> None: ...
    @property
    def NonmasterSaveAsOption(self) -> PDM.PartFromPartBuilder.FileSaveAs: ...
    @NonmasterSaveAsOption.setter
    def NonmasterSaveAsOption(self, value: PDM.PartFromPartBuilder.FileSaveAs) -> None: ...


    class FileSaveAs(enum.Enum):
        Some= 0
        All= 1
        None_= 2
    

class PartFamilyTreatment(enum.Enum):
    TreatAsLostPart= 0
    TurnIntoNormalPart= 1


class PartCreationObjectAttributePropertiesBuilder(AttributePropertiesBaseBuilder):
    def __init__(self) -> None: ...


class PartCreationObject(NXObject):
    def __init__(self) -> None: ...
    def CreateAttributePropertiesBuilder(self) -> PDM.PartCreationObjectAttributePropertiesBuilder: ...


class PartBuilder(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def CreatePartSpec(self, partType: str, partNumber: str, partRevision: str, partFileType: str, partFileName: str) -> None: ...
    def NewDatabaseAttributeManager(self) -> PDM.DatabaseAttributeManager: ...
    def CreatePartCreationObject(self) -> PDM.PartCreationObject: ...
    def NewAlternateIdManager(self) -> PDM.AlternateIdManager: ...
    @typing.overload
    def AssignPartNumber(self, partType: str) -> str: ...
    @typing.overload
    def AssignPartRevision(self) -> str: ...
    @typing.overload
    def AssignPartFileName(self, partFileType: str) -> str: ...
    @typing.overload
    def AssignPartNumber(self, oldPartNumber: str, partType: str) -> PDM.PartBuilder.PartNumberData: ...
    @typing.overload
    def AssignPartRevision(self, overload: int) -> PDM.PartBuilder.PartRevisionData: ...
    @typing.overload
    def AssignPartFileName(self, partNumber: str, partRevision: str, partFileNameType: str, oldPartFileName: str) -> PDM.PartBuilder.PartFileNameData: ...
    def SetAssignPartNumber(self, partNumber: str) -> None: ...
    def SetAssignPartType(self, partType: str) -> None: ...
    def SetContextOperation(self, operation: PDM.PartBuilder.Operation) -> None: ...


    class PartBuilderPartRevisionData():
        @property
        def PartRevision(self) -> str: ...
        @PartRevision.setter
        def PartRevision(self, value: str) -> None: ...
        @property
        def PartRevisionModifiable(self) -> bool: ...
        @PartRevisionModifiable.setter
        def PartRevisionModifiable(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, PartRevision: str, PartRevisionModifiable: bool) -> None: ...
    

    class PartBuilderPartNumberData():
        @property
        def PartName(self) -> str: ...
        @PartName.setter
        def PartName(self, value: str) -> None: ...
        @property
        def PartNameModifiable(self) -> bool: ...
        @PartNameModifiable.setter
        def PartNameModifiable(self, value: bool) -> None: ...
        @property
        def PartDescription(self) -> str: ...
        @PartDescription.setter
        def PartDescription(self, value: str) -> None: ...
        @property
        def PartDescriptionModifiable(self) -> bool: ...
        @PartDescriptionModifiable.setter
        def PartDescriptionModifiable(self, value: bool) -> None: ...
        @property
        def PartNumber(self) -> str: ...
        @PartNumber.setter
        def PartNumber(self, value: str) -> None: ...
        @property
        def PartNumberModifiable(self) -> bool: ...
        @PartNumberModifiable.setter
        def PartNumberModifiable(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
    

    class PartBuilderPartFileNameData():
        @property
        def PartFileName(self) -> str: ...
        @PartFileName.setter
        def PartFileName(self, value: str) -> None: ...
        @property
        def PartFileNameModifiable(self) -> bool: ...
        @PartFileNameModifiable.setter
        def PartFileNameModifiable(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, PartFileName: str, PartFileNameModifiable: bool) -> None: ...
    

    class Operation(enum.Enum):
        ExportPartNew= 0
        AssemblyDiagram= 1
        AssemblyCreateNewComponent= 2
        Default= 3
    

    class PartBuilder_PartRevisionData():
        @property
        def part_revision(self) -> int: ...
        @part_revision.setter
        def part_revision(self, value: int) -> None: ...
        @property
        def part_revision_modifiable(self) -> bool: ...
        @part_revision_modifiable.setter
        def part_revision_modifiable(self, value: bool) -> None: ...
    

    class PartBuilder_PartNumberData():
        @property
        def part_name(self) -> int: ...
        @part_name.setter
        def part_name(self, value: int) -> None: ...
        @property
        def part_name_modifiable(self) -> bool: ...
        @part_name_modifiable.setter
        def part_name_modifiable(self, value: bool) -> None: ...
        @property
        def part_description(self) -> int: ...
        @part_description.setter
        def part_description(self, value: int) -> None: ...
        @property
        def part_description_modifiable(self) -> bool: ...
        @part_description_modifiable.setter
        def part_description_modifiable(self, value: bool) -> None: ...
        @property
        def part_number(self) -> int: ...
        @part_number.setter
        def part_number(self, value: int) -> None: ...
        @property
        def part_number_modifiable(self) -> bool: ...
        @part_number_modifiable.setter
        def part_number_modifiable(self, value: bool) -> None: ...
    

    class PartBuilder_PartFileNameData():
        @property
        def part_file_name(self) -> int: ...
        @part_file_name.setter
        def part_file_name(self, value: int) -> None: ...
        @property
        def part_file_name_modifiable(self) -> bool: ...
        @part_file_name_modifiable.setter
        def part_file_name_modifiable(self, value: bool) -> None: ...
    

class PartAttributeAssignmentObserverCallbackData(TaggedObject):
    def __init__(self) -> None: ...
    def GetLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...


class PartAttributeAssignmentObserver(Utilities.NXRemotableObject):
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    def RegisterUserDefinedFunction(self, handler: PDM.PartAttributeAssignmentObserver.UserFunctionHandler) -> int: ...
    def UnRegisterUserDefinedFunction(self, id: int) -> None: ...
    def Tag(self) -> Tag: ...



    

    

    

class OrderedElementGroup(NXObject):
    def __init__(self) -> None: ...


class OperationErrors(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...


class ObjectCreateBuilder(Builder):
    def __init__(self) -> None: ...
    def SetTypes(self, tcTypes: str, baseTCTypes: str) -> None: ...
    def CreateLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    def GetAttributeHolderObjects(self, attributeHolderObjects: typing.List[PDM.GenericObjectAttributeHolder]) -> None: ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList: ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList: ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject: ...
    @property
    def DefaultDestinationFolder(self) -> str: ...
    @DefaultDestinationFolder.setter
    def DefaultDestinationFolder(self, value: str) -> None: ...


class NonMasterData(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def CreateNonMasterListForLogicalObject(self, logicalObject: PDM.LogicalObject) -> None: ...
    def GetNonMasterListForCopyLogicalObject(self, logicalObject: PDM.LogicalObject) -> str: ...
    def IsNonMasterForLogicalObjectBeingCopied(self, logicalObject: PDM.LogicalObject, partName: str) -> bool: ...
    def GetCopyNonMasterPartsOption(self, logicalObject: PDM.LogicalObject) -> PDM.NonMasterData.CopyNonMasterPartsOption: ...
    def SetNonMasterSaveAsOption(self, logicalObject: PDM.LogicalObject, saveOption: PDM.NonMasterData.CopyNonMasterPartsOption) -> None: ...
    def SetSelectedNonMasterToCopy(self, logicalObject: PDM.LogicalObject, partName: str) -> None: ...
    def EditNonMasterToCopyName(self, logicalObject: PDM.LogicalObject, oldName: str, newName: str) -> bool: ...


    class CopyNonMasterPartsOption(enum.Enum):
        All= 0
        None_= 1
    

class NativePartLogicalObject(PDM.LogicalObject):
    def __init__(self) -> None: ...
    def GetInitialName(self) -> str: ...
    def GetFinalName(self) -> str: ...
    def IsPartNameAutoAssigned(self) -> bool: ...
    def IsCandidateForImport(self) -> bool: ...
    def GetExistingPartAction(self) -> PDM.PartOperationImportBuilder.ExistingPartAction: ...
    def SetExistingPartAction(self, existingPartAction: PDM.PartOperationImportBuilder.ExistingPartAction) -> None: ...
    def GetValidationMode(self) -> PDM.PartOperationImportBuilder.Validation: ...
    def SetValidationMode(self, validationMode: PDM.PartOperationImportBuilder.Validation) -> None: ...
    def GetValidationRuleSetFileBrowseOption(self) -> PDM.PartOperationImportBuilder.ValidationRuleSetFileBrowseOption: ...
    def SetValidationRuleSetFileBrowseOption(self, browseOption: PDM.PartOperationImportBuilder.ValidationRuleSetFileBrowseOption) -> None: ...


class NamingTechniqueOption(enum.Enum):
    AutoTranslate= 0
    NamingRule= 1
    AutoTranslateWithAlternateID= 2
    UserName= 3
    AutoGenerate= 4
    Default= 5


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class ModelElementRevision(NXObject):
    def __init__(self) -> None: ...
    def GetMemberPartitions(self) -> typing.List[Assemblies.Partition]: ...
    def GetOverridePart(self) -> Part: ...
    def IsExcludedFromSpatialSearch(self) -> bool: ...
    def SetExcludeFromSpatialSearch(self, excludeFromSpatialSearch: bool) -> None: ...
    def GetPositionStatus(self) -> PDM.ModelElementRevision.PositioningStatus: ...
    def IsAbsolutelyPositioned(self) -> bool: ...
    def GetPositioningGroups(self) -> typing.List[Assemblies.PositioningGroup]: ...
    def IsMemberOfPositioningGroup(self) -> bool: ...
    def Create(self, attributeGroupDescription: PDM.AttributeGroupDescription) -> PDM.AttributeGroup: ...
    @typing.overload
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup]) -> PDM.AttributeGroupReviseBuilder: ...
    def GetAttributeGroups(self) -> typing.List[PDM.AttributeGroup]: ...
    def GetAttributeGroupDescriptions(self) -> typing.List[PDM.AttributeGroupDescription]: ...
    @typing.overload
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup], keepOriginal: bool, saveAsActionType: PDM.AttributeGroupReviseBuilder.SaveAsActionType) -> PDM.AttributeGroupReviseBuilder: ...
    @property
    def EffectivityFormula(self) -> str: ...
    @EffectivityFormula.setter
    def EffectivityFormula(self, value: str) -> None: ...
    @property
    def OwningCollaborativeDesign(self) -> CollaborativeDesign: ...
    @OwningCollaborativeDesign.setter
    def OwningCollaborativeDesign(self, value: CollaborativeDesign) -> None: ...


    class PositioningStatus(enum.Enum):
        AbsolutelyPositioned= 0
        OutOfDate= 1
        UpToDate= 2
        Unknown= 3
    

class ModelElement(NXObject):
    def __init__(self) -> None: ...
    def GetMemberPartitions(self) -> typing.List[Assemblies.Partition]: ...
    def Create(self, attributeGroupDescription: PDM.AttributeGroupDescription) -> PDM.AttributeGroup: ...
    @typing.overload
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup]) -> PDM.AttributeGroupReviseBuilder: ...
    def GetAttributeGroups(self) -> typing.List[PDM.AttributeGroup]: ...
    def GetAttributeGroupDescriptions(self) -> typing.List[PDM.AttributeGroupDescription]: ...
    @typing.overload
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup], keepOriginal: bool, saveAsActionType: PDM.AttributeGroupReviseBuilder.SaveAsActionType) -> PDM.AttributeGroupReviseBuilder: ...
    @property
    def OwningCollaborativeDesign(self) -> CollaborativeDesign: ...
    @OwningCollaborativeDesign.setter
    def OwningCollaborativeDesign(self, value: CollaborativeDesign) -> None: ...


class LogicalObject(NXObject):
    def __init__(self) -> None: ...


class LogicalElementRevision(PDM.ConditionalElementRevision):
    def __init__(self) -> None: ...


class ListOfValues(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...


class ICloneOperation(TaggedObject):
    def __init__(self) -> None: ...
    def AddPart(self, partName: str) -> None: ...
    def AddAssembly(self, assemblyName: str) -> PartLoadStatus: ...
    def LoadFromLogFile(self, logFileName: str, namingFailures: AssyCloneNamingFailures, logFileFailures: AssyCloneLogFileFailures, loadStatus: PartLoadStatus) -> None: ...
    def Destroy(self) -> None: ...
    def ApplyDefaultsAndExecute(self, skipExecute: bool, namingFailures: AssyCloneNamingFailures, namingWarnings: AssyCloneNamingFailures) -> None: ...
    def TerminateOperation(self) -> None: ...
    def SetNamingTechnique(self, namingTechnique: PDM.NamingTechniqueOption) -> None: ...
    def SetDefaultAction(self, defaultAction: PDM.ExistingPartAction) -> None: ...
    def SetPrefixString(self, prefixStr: str) -> None: ...
    def SetSuffixString(self, suffixStr: str) -> None: ...
    def ReplaceString(self, baseString: str, newString: str) -> None: ...
    def RenameString(self, renameStr: str) -> None: ...
    def SetOutputLogFile(self, logFileName: str) -> None: ...
    def AttachLogFileToAssociatedFiles(self, attachLogFileToAssociatedFiles: bool) -> None: ...
    def SetCloneRelatedCae(self, cloneRelatedCae: PDM.CloneRelatedCae) -> None: ...
    def SetCloneRelatedDrawings(self, cloneRelatedDrawings: bool) -> None: ...
    def CopyAssociatedFiles(self, copyAssociatedFiles: bool) -> None: ...
    def CopyRelations(self, relationTypes: str, copyRelations: bool) -> None: ...
    def AssignCompDisposition(self, objectToBeCloned: PDM.AssyCloneCompDisp, action: PDM.ExistingPartAction, cascadeDispositions: bool, cascadedComponentDispositions: typing.List[PDM.AssyCloneCompDisp], conflictingComponentDispositions: typing.List[PDM.AssyCloneCompDisp]) -> None: ...
    def AssignCloneNaming(self, objectToBeCloned: PDM.AssyCloneCompDisp, namingTechnique: PDM.NamingTechniqueOption, finalName: str) -> int: ...
    def FetchObjects(self, objectsToBeCloned: typing.List[PDM.AssyCloneCompDisp]) -> None: ...
    def SetDryRun(self, isDryRun: bool) -> None: ...
    def SetFinalName(self, objectToBeCloned: PDM.AssyCloneCompDisp, finalName: str, allowDuplicates: bool) -> None: ...
    def SetConfigurationContextUsingRevRule(self, setDefault: bool, revisionRuleName: str) -> int: ...
    def SetLoadOption(self, loadOption: LoadOptions.ManagedModeLoadMethod) -> None: ...
    def InitCloneLog(self, logFileName: str) -> None: ...
    def ReprocessNonComponentReferences(self) -> None: ...
    def ApplyCICODefaults(self) -> AssyCloneNamingFailures: ...
    def PerformPreCommit(self) -> None: ...
    def PerformPostCommit(self) -> None: ...
    def AddApplicationRelatedParts(self) -> None: ...
    def SetPartFamilyTreatment(self, partFamilyTreatment: PDM.PartFamilyTreatment) -> None: ...
    def SetCloneExcludeReferenceOnly(self, excludeReferenceOnly: bool) -> None: ...
    def SetCloneExcludeNGC(self, excludeNGC: bool) -> None: ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList: ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList: ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject: ...


class IAttributeGroupOwner():
    def Create(self, attributeGroupDescription: PDM.AttributeGroupDescription) -> PDM.AttributeGroup: ...
    @typing.overload
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup]) -> PDM.AttributeGroupReviseBuilder: ...
    def GetAttributeGroups(self) -> typing.List[PDM.AttributeGroup]: ...
    def GetAttributeGroupDescriptions(self) -> typing.List[PDM.AttributeGroupDescription]: ...
    @typing.overload
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup], keepOriginal: bool, saveAsActionType: PDM.AttributeGroupReviseBuilder.SaveAsActionType) -> PDM.AttributeGroupReviseBuilder: ...


class GenericObjectAttributeHolder(NXObject):
    def __init__(self) -> None: ...


class FindCriteria(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def SetCriteria(self, queryName: str, entries: str, values: str) -> None: ...
    def GetCriteria(self, queryName: str, entries: str, values: str) -> None: ...


class FileManagement(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def ImportFiles(self, itemIds: str, itemRevisionIds: str, datasetNames: str, datasetTypeNames: str, datasetRelationTypeNames: str, importDirectoryNames: str) -> int: ...
    def ExportFiles(self, itemIds: str, itemRevisionIds: str, datasetNames: str, datasetTypeNames: str, datasetRelationTypeNames: str, baseDirectoryNames: str, toolNames: str, exportDirectoryNames: str) -> int: ...
    def GetAssociatedFiles(self, parts: typing.List[BasePart], fileTypesToExclude: typing.List[PDM.FileManagement.FileType]) -> typing.List[PDM.PdmFile]: ...
    def DownloadAssociatedFiles(self, parts: typing.List[BasePart], files: typing.List[PDM.PdmFile]) -> None: ...
    def ImportFilesAndCreateDatasets(self, itemIds: str, itemRevisionIds: str, datasetNames: str, datasetTypeNames: str, datasetRelationTypeNames: str, datasetToolNames: str, fileType: bool, namedReferenceNames: str, importFileNames: str, importFileDirectoryNames: str) -> int: ...
    @typing.overload
    def ExportNamedReferences(self, itemId: str, itemRevisionId: str, datasetName: str, datasetTypeName: str, datasetRelationTypeName: str, datasetNamedReference: str, exportDirectoryName: str, namedReferences: str) -> None: ...
    @typing.overload
    def ExportNamedReferences(self, itemIds: str, itemRevisionIds: str, datasetNames: str, datasetTypeNames: str, datasetRelationTypeNames: str, datasetNamedReferences: str, exportDirectoryName: str, numNamedReferences: int, namedReferences: str) -> int: ...
    def SaveAttachedFiles(self, associatedObject: typing.List[NXObject], associationTypeName: str, datasetTypeName: str, datasetName: str, numDatasetPropertyInput: int, datasetPropertyNames: str, datasetPropertyValues: str, ownershipToMatchForNewDataset: typing.List[NXObject], fileVolumeToStore: typing.List[PDM.PdmFile], toolUsed: str, datasetDescription: str, alwaysCreateNewDataset: bool, createNewDatasetVersion: bool, refreshInSessionLoadedLMD: bool, numNamedReferencesPerInput: int, namedReferenceName: str, isText: bool, filePath: str, logicalFileName: str, allowReplace: bool, outputFiles: bool, files: typing.List[PDM.PdmFile]) -> int: ...
    def DeleteAttachedFiles(self, associatedObject: typing.List[NXObject], associationTypeName: str, datasetTypeName: str, datasetName: str, namedReferenceName: str, isText: str, logicalFileName: str, keepEmptyDataset: bool) -> int: ...
    def DeleteExistingAttachedFiles(self, files: typing.List[PDM.PdmFile], keepEmptyDataset: bool) -> int: ...
    def GetAttachedFiles(self, associatedObject: typing.List[NXObject], associationTypeName: str, datasetTypeName: str, datasetName: str, namedReferenceName: str, isText: str, logicalFileName: str, exportDirectoryName: str, numOutputFiles: int, files: typing.List[PDM.PdmFile]) -> int: ...


    class FileType(enum.Enum):
        CmmDmi= 0
        CpdFeaturePart= 1
        CpdGeometryOverride= 2
        DirectModel= 3
        Excel= 4
        ExcelX= 5
        Image= 6
        Jpeg= 7
        NxDesignatorAssignmentsFile= 8
        NxAttachedPart= 9
        NxPart= 10
        NxPosBin= 11
        NxleSymbolXml= 12
        NxleSymbolPreview= 13
        Preview2d= 14
        Preview3d= 15
        QafBinary= 16
        QafText= 17
        RoutePipeRun= 18
        RoutePipeSpec= 19
        RoutePipeRunAttachment= 20
        Text= 21
        Tif= 22
        TrushapeData= 23
        ValidationRuleSet= 24
    

class ExternalFileReferenceListBuilder(Builder):
    def __init__(self) -> None: ...
    def GetExternalFileObjects(self, objects: typing.List[NXObject]) -> None: ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList: ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList: ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject: ...


class ExportWorksetForReferenceBuilder(Builder):
    def __init__(self) -> None: ...
    def GetObjects(self, objects: typing.List[NXObject]) -> None: ...
    def ValidateObjects(self) -> ErrorList: ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList: ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList: ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject: ...
    @property
    def DestinationFolder(self) -> str: ...
    @DestinationFolder.setter
    def DestinationFolder(self, value: str) -> None: ...


class ExportFromTeamcenter(PDM.ICloneOperation):
    def __init__(self) -> None: ...
    def SetDefaultDirectory(self, directoryName: str) -> None: ...
    def SetAssociatedFilesRootDir(self, rootDirName: str) -> None: ...
    def SetAssociatedFilesDir(self, objectToBeCloned: PDM.AssyCloneCompDisp, directoryName: str) -> None: ...
    def SetExternalFiles(self, setExternalFiles: bool) -> None: ...
    def CreateZipFileOfExportedParts(self, zipFilePath: str, overwrite: bool) -> int: ...
    def SetDefaultCheckOutData(self, checkoutComment: str) -> None: ...
    def SetCheckOutData(self, objectToBeCloned: PDM.AssyCloneCompDisp, checkoutComment: str) -> int: ...
    def SetAddDfaMixins(self, isAddDfaMixins: bool) -> None: ...
    def SetExportDfaWithPart(self, isExportDfaWithPart: bool) -> None: ...
    def AddDFAFile(self, dfaFile: str) -> None: ...
    def ExportDFAFiles(self, dfaFiles: str, defDir: str, doMixins: bool) -> None: ...
    def SetIdentifierDisplayRule(self, displayRule: str) -> None: ...


class ExistingPartAction(enum.Enum):
    Overwrite= 0
    UseExisting= 1
    Exclude= 2
    Clone= 3
    Retain= 4
    Default= 5


class ErrorMessageHandler(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def GetErrorList(self) -> ErrorList: ...
    def GetErrorMessages(self) -> str: ...
    def GetWarningMessages(self) -> str: ...


class ElementGroup(PDM.ConditionalElementRevision):
    def __init__(self) -> None: ...


class EffectivityTableRow(NXObject):
    def __init__(self) -> None: ...


class EffectivityTableBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def GetEffectivityRows(self, effectivityRows: typing.List[PDM.EffectivityTableRow]) -> None: ...
    def CreateNewEffectivityRow(self) -> PDM.EffectivityTableRow: ...
    def AddEffectivityRow(self, effectivityRow: PDM.EffectivityTableRow) -> None: ...
    def RemoveEffectivityRows(self, effectivityRows: typing.List[PDM.EffectivityTableRow]) -> None: ...
    def UpdateBuilderDetails(self, cd: CollaborativeDesign, validationBasisFormula: str, effectivityFormulae: str) -> None: ...
    def Commit(self) -> None: ...
    def Validate(self) -> bool: ...


class EffectivityAttributePropertiesBuilder(Builder):
    def __init__(self) -> None: ...
    def Delete(self, object: NXObject) -> None: ...
    def CreateAttribute(self) -> bool: ...
    def SetAttributeObjects(self, objects: typing.List[NXObject]) -> None: ...
    @property
    def Category(self) -> str: ...
    @Category.setter
    def Category(self, value: str) -> None: ...
    @property
    def DisplayValue(self) -> str: ...
    @DisplayValue.setter
    def DisplayValue(self, value: str) -> None: ...
    @property
    def EffectivityTableBuilder(self) -> PDM.EffectivityTableBuilder: ...
    @EffectivityTableBuilder.setter
    def EffectivityTableBuilder(self, value: PDM.EffectivityTableBuilder) -> None: ...
    @property
    def SelectedObjects(self) -> SelectNXObjectList: ...
    @SelectedObjects.setter
    def SelectedObjects(self, value: SelectNXObjectList) -> None: ...
    @property
    def StringValue(self) -> str: ...
    @StringValue.setter
    def StringValue(self, value: str) -> None: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> None: ...


class DesignSubordinateRevision(PDM.ModelElementRevision):
    def __init__(self) -> None: ...
    @property
    def DesignPart(self) -> Part: ...
    @DesignPart.setter
    def DesignPart(self, value: Part) -> None: ...
    @property
    def Modified(self) -> bool: ...
    @Modified.setter
    def Modified(self, value: bool) -> None: ...
    @property
    def RootDesignElementRevision(self) -> PDM.DesignElementRevision: ...
    @RootDesignElementRevision.setter
    def RootDesignElementRevision(self, value: PDM.DesignElementRevision) -> None: ...


class DesignFeatureRevision(PDM.ModelElementRevision):
    def __init__(self) -> None: ...


class DesignElementRevision(PDM.ModelElementRevision):
    def __init__(self) -> None: ...
    def GetTransform(self, positionInMeters: Point3d) -> Matrix3x3: ...
    def GetDesignSubordinateRevisions(self) -> typing.List[PDM.DesignSubordinateRevision]: ...
    @property
    def Category(self) -> PDM.DesignElementRevision.DesignElementCategory: ...
    @Category.setter
    def Category(self, value: PDM.DesignElementRevision.DesignElementCategory) -> None: ...
    @property
    def DesignPart(self) -> Part: ...
    @DesignPart.setter
    def DesignPart(self, value: Part) -> None: ...
    @property
    def Modified(self) -> bool: ...
    @Modified.setter
    def Modified(self, value: bool) -> None: ...


    class DesignElementCategory(enum.Enum):
        Shape= 0
        Reuse= 1
        Promissory= 2
        DesignControlElement= 3
    

class DBEntityProxyCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[PDM.DBEntityProxy]: ...
    @typing.overload
    def __init__(self, owner: Part) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindProxy(self, journalIdentifier: str) -> NXObject: ...
    def CreateDbEntityProxy(self, title: str, index: int, context: TaggedObject, attributeOwner: TaggedObject) -> PDM.DBEntityProxy: ...
    def Tag(self) -> Tag: ...



class DBEntityProxy(NXObject):
    def __init__(self) -> None: ...


class DatabaseObjects(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def SetDatabaseObjects(self, databaseObjects: typing.List[PDM.DatabaseObject]) -> None: ...
    def GetDatabaseObjects(self) -> typing.List[PDM.DatabaseObject]: ...
    def Append(self, databaseObjects: typing.List[PDM.DatabaseObjects]) -> None: ...


class DatabaseObjectManager(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def NewFindcriteria(self, nCriteria: int) -> typing.List[PDM.FindCriteria]: ...
    def NewDatabaseobjects(self) -> PDM.DatabaseObjects: ...
    def FindObjects(self, findCriterias: typing.List[PDM.FindCriteria]) -> typing.List[PDM.DatabaseObjects]: ...
    def GetDatabaseObjectFromAppSessionUid(self, uId: str) -> PDM.DatabaseObject: ...
    def FindDesignSessionObjects(self, designSessionParamNames: str, designSessionParamValues: str) -> PDM.DatabaseObject: ...


class DatabaseObject(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...


class DatabaseAttributeManager(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def SetAttribute(self, attributeTitle: str, attributeValue: str) -> None: ...
    def GetAttribute(self, attributeTitle: str) -> str: ...
    def StoreAttributes(self) -> None: ...
    def RefreshAttributes(self) -> None: ...
    def LoadAttributes(self, reload: bool) -> None: ...
    def LoadAttributesRecursively(self, reload: bool) -> None: ...


class CustomWebAppMenuHandler(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def RegisterCustomWebAppInvokedCallback(self, webappCb: PDM.CustomWebAppMenuHandler.CustomWebAppInvokedCallback) -> None: ...
    def GetSelectedUids(self, uids: str) -> None: ...
    def GetCommandName(self) -> str: ...


    

    

    

class CrossSheetReference(PDM.ModelElement):
    def __init__(self) -> None: ...


class ConversionRule(enum.Enum):
    WithPrefix= 0
    WithSuffix= 1
    WithReplaceString= 2
    WithRename= 3


class ConnectionElementRevision(PDM.ConditionalElementRevision):
    def __init__(self) -> None: ...


class ConfigurationManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def CreateConfigurationContextBuilder(self) -> PDM.ConfigurationContextBuilder: ...
    def CreateEffectivityAttributePropertiesBuilder(self, part: BasePart, objects: typing.List[NXObject]) -> PDM.EffectivityAttributePropertiesBuilder: ...
    def CreateVariantRulesConfigurationBuilder(self, part: BasePart) -> PDM.VariantRulesConfigurationBuilder: ...
    def Tag(self) -> Tag: ...



class ConfigurationContextBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CollaborativeDesign(self) -> CollaborativeDesign: ...
    @CollaborativeDesign.setter
    def CollaborativeDesign(self, value: CollaborativeDesign) -> None: ...
    @property
    def ConfigDetail(self) -> PDM.ConfigurationContextBuilder.ConfigurationDetail: ...
    @ConfigDetail.setter
    def ConfigDetail(self, value: PDM.ConfigurationContextBuilder.ConfigurationDetail) -> None: ...
    @property
    def ConfigMode(self) -> PDM.ConfigurationContextBuilder.ConfigContextMode: ...
    @ConfigMode.setter
    def ConfigMode(self, value: PDM.ConfigurationContextBuilder.ConfigContextMode) -> None: ...
    @property
    def ConfigType(self) -> PDM.ConfigurationContextBuilder.ConfigContextType: ...
    @ConfigType.setter
    def ConfigType(self, value: PDM.ConfigurationContextBuilder.ConfigContextType) -> None: ...
    @property
    def ContentDefinition(self) -> ContentDefinition: ...
    @ContentDefinition.setter
    def ContentDefinition(self, value: ContentDefinition) -> None: ...
    @property
    def EffectivityTable(self) -> PDM.EffectivityTableBuilder: ...
    @EffectivityTable.setter
    def EffectivityTable(self, value: PDM.EffectivityTableBuilder) -> None: ...
    @property
    def OverrideFolder(self) -> str: ...
    @OverrideFolder.setter
    def OverrideFolder(self, value: str) -> None: ...
    @property
    def RevisionRule(self) -> str: ...
    @RevisionRule.setter
    def RevisionRule(self, value: str) -> None: ...
    @property
    def VariantConfiguration(self) -> PDM.VariantConfigurationBuilder: ...
    @VariantConfiguration.setter
    def VariantConfiguration(self, value: PDM.VariantConfigurationBuilder) -> None: ...


    class ConfigurationDetail(enum.Enum):
        LoadfromTeamcenter= 0
        DefineinNX= 1
    

    class ConfigContextType(enum.Enum):
        AsSaved= 0
        PushedfromTeamcenter= 1
        DefineorLoadContext= 2
    

    class ConfigContextMode(enum.Enum):
        Nx4gd= 0
        Assemblies= 1
    

class ConditionalElementRevision(PDM.ModelElement):
    def __init__(self) -> None: ...
    @property
    def EffectivityFormula(self) -> str: ...
    @EffectivityFormula.setter
    def EffectivityFormula(self, value: str) -> None: ...


class CloneRelatedCae(enum.Enum):
    SimFemIdeal= 0
    FemIdeal= 1
    Ideal= 2
    None_= 3


class CAEFileContainer(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def GetOwningPart(self) -> str: ...
    def SetOwningPart(self, partspec: str) -> None: ...
    def AddFile(self, datasetname: str, filename: str) -> None: ...
    def DeleteFile(self, datasetname: str, filename: str) -> None: ...
    def DoUpload(self) -> None: ...


class CaeCloneManager(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def GetPartBuilderForClone(self, option: PDM.CaeCloneManager.CloneOption) -> PDM.PartFromPartBuilder: ...
    def SetIncludeMaster(self, value: bool) -> None: ...
    def GetContainer(self, option: PDM.CaeCloneManager.CloneOption) -> str: ...
    def SetContainer(self, option: PDM.CaeCloneManager.CloneOption, container: str) -> None: ...
    def CommitClone(self) -> None: ...


    class CloneOption(enum.Enum):
        None_= -1
        Sim= 0
        Fem= 1
        Ideal= 2
        Master= 3
    

class AttributeGroupReviseBuilder(Builder):
    def __init__(self) -> None: ...
    def GetRevisedAttributeGroups(self) -> typing.List[PDM.AttributeGroup]: ...
    def GetOperationErrors(self) -> PDM.OperationErrors: ...
    def GetOperationFailures(self) -> ErrorList: ...
    def GetLogicalObjects(self) -> typing.List[PDM.LogicalObject]: ...


    class SaveAsActionType(enum.Enum):
        NewRevision= 0
        NewAttributeGroup= 1
    

class AttributeGroupDescriptionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[PDM.AttributeGroupDescription]: ...
    @typing.overload
    def __init__(self, owner: PDM.PdmSession) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> PDM.AttributeGroupDescription: ...
    def Tag(self) -> Tag: ...



class AttributeGroupDescription(NXObject):
    def __init__(self) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> None: ...
    @property
    def MaximumNumberOfAttributeGroupsAllowed(self) -> int: ...
    @MaximumNumberOfAttributeGroupsAllowed.setter
    def MaximumNumberOfAttributeGroupsAllowed(self, value: int) -> None: ...
    @property
    def MinimumNumberOfAttributeGroupsAllowed(self) -> int: ...
    @MinimumNumberOfAttributeGroupsAllowed.setter
    def MinimumNumberOfAttributeGroupsAllowed(self, value: int) -> None: ...


class AttributeGroupCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[PDM.AttributeGroup]: ...
    @typing.overload
    def __init__(self, owner: CollaborativeDesign) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> PDM.AttributeGroup: ...
    def Tag(self) -> Tag: ...



class AttributeGroup(NXObject):
    def __init__(self) -> None: ...
    def GetReferencingAttributeGroupOwners(self) -> typing.List[PDM.IAttributeGroupOwner]: ...
    def DetachAttributeGroup(self, attributeGroupOwner: PDM.IAttributeGroupOwner) -> None: ...
    def Create(self, attributeGroupDescription: PDM.AttributeGroupDescription) -> PDM.AttributeGroup: ...
    @typing.overload
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup]) -> PDM.AttributeGroupReviseBuilder: ...
    def GetAttributeGroups(self) -> typing.List[PDM.AttributeGroup]: ...
    def GetAttributeGroupDescriptions(self) -> typing.List[PDM.AttributeGroupDescription]: ...
    @typing.overload
    def CreateAttributeGroupReviseBuilder(self, attributeGroups: typing.List[PDM.AttributeGroup], keepOriginal: bool, saveAsActionType: PDM.AttributeGroupReviseBuilder.SaveAsActionType) -> PDM.AttributeGroupReviseBuilder: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> None: ...


class AssyCloneCompDisp(NXObject):
    def __init__(self) -> None: ...


class AlternateIdManager(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def SetContext(self, context: str) -> None: ...
    def GetContext(self) -> str: ...
    def GetAllContexts(self) -> str: ...
    def SetIdType(self, idType: str) -> None: ...
    def GetIdType(self) -> str: ...
    def GetAllIdTypes(self, context: str) -> str: ...
    def SetAlternateItemId(self, alternateItemId: str) -> None: ...
    def AssignAlternateId(self, alternateItemId: str, alternateRevId: str) -> None: ...
    def GetAlternateItemId(self) -> str: ...
    def SetAlternateRevId(self, alternateRevId: str) -> None: ...
    def AssignAlternateRevId(self) -> str: ...
    def GetAlternateRevId(self) -> str: ...
    def SetAlternateName(self, alternateName: str) -> None: ...
    def GetAlternateName(self) -> str: ...
    def SetAlternateDescription(self, alternateDescription: str) -> None: ...
    def GetAlternateDescription(self) -> str: ...
    def SetAlternateIdAsDefaultIndentifier(self, alternateIdAsDefaultIndentifier: bool) -> None: ...
    def GetAlternateIdAsDefaultIndentifier(self) -> bool: ...
    def SetAlternateIdInformation(self, context: str, idType: str, alternateItemId: str, alternateRevId: str, alternateName: str, alternateDescription: str, alternateIdAsDefaultIndentifier: bool) -> None: ...
    def CreateAlternateIdInformation(self) -> None: ...
    def AssignAlternateIds(self, context: str, idType: str) -> PDM.AlternateIdManager.AlternateIdsData: ...
    def AssignAlternateRevision(self) -> PDM.AlternateIdManager.AssignAlternateRevData: ...


    class AlternateIdManagerAssignAlternateRevData():
        @property
        def AlternateRevId(self) -> str: ...
        @AlternateRevId.setter
        def AlternateRevId(self, value: str) -> None: ...
        @property
        def Modifiable(self) -> bool: ...
        @Modifiable.setter
        def Modifiable(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, AlternateRevId: str, Modifiable: bool) -> None: ...
    

    class AlternateIdManagerAlternateIdsData():
        @property
        def AlternateItemId(self) -> str: ...
        @AlternateItemId.setter
        def AlternateItemId(self, value: str) -> None: ...
        @property
        def AlternateRevId(self) -> str: ...
        @AlternateRevId.setter
        def AlternateRevId(self, value: str) -> None: ...
        @property
        def AlternateName(self) -> str: ...
        @AlternateName.setter
        def AlternateName(self, value: str) -> None: ...
        @property
        def AlternateDescription(self) -> str: ...
        @AlternateDescription.setter
        def AlternateDescription(self, value: str) -> None: ...
        @property
        def Modifiable(self) -> bool: ...
        @Modifiable.setter
        def Modifiable(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
    

    class AlternateIdManager_AssignAlternateRevData():
        @property
        def alternate_rev_id(self) -> int: ...
        @alternate_rev_id.setter
        def alternate_rev_id(self, value: int) -> None: ...
        @property
        def modifiable(self) -> bool: ...
        @modifiable.setter
        def modifiable(self, value: bool) -> None: ...
    

    class AlternateIdManager_AlternateIdsData():
        @property
        def alternate_item_id(self) -> int: ...
        @alternate_item_id.setter
        def alternate_item_id(self, value: int) -> None: ...
        @property
        def alternate_rev_id(self) -> int: ...
        @alternate_rev_id.setter
        def alternate_rev_id(self, value: int) -> None: ...
        @property
        def alternate_name(self) -> int: ...
        @alternate_name.setter
        def alternate_name(self, value: int) -> None: ...
        @property
        def alternate_description(self) -> int: ...
        @alternate_description.setter
        def alternate_description(self, value: int) -> None: ...
        @property
        def modifiable(self) -> bool: ...
        @modifiable.setter
        def modifiable(self, value: bool) -> None: ...
    

