from ....NXOpen import *
from ...CAE import *

import typing
import enum

class WrongSupportSequenceResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...


class UniversalConnectionSynthesisResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    def GetRepresentedConnections(self) -> typing.List[CAE.Connections.IConnection]: ...
    @property
    def Characteristic(self) -> str: ...
    @Characteristic.setter
    def Characteristic(self, value: str) -> None: ...
    @property
    def Count(self) -> int: ...
    @Count.setter
    def Count(self, value: int) -> None: ...


class SupportSequenceCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class Result(NXObject):
    def __init__(self) -> None: ...
    def GetSubResults(self, subResults: typing.List[CAE.QualityAudit.Result]) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def Outdated(self) -> bool: ...
    @Outdated.setter
    def Outdated(self, value: bool) -> None: ...
    @property
    def OwningAction(self) -> CAE.QualityAudit.Action: ...
    @OwningAction.setter
    def OwningAction(self, value: CAE.QualityAudit.Action) -> None: ...


class ProjectionCheckSettings(CAE.QualityAudit.ActionSettings):
    def __init__(self) -> None: ...
    def GetThresholdByConnectionType(self, connectionType: CAE.Connections.ConnectionType) -> Expression: ...
    @property
    def Threshold(self) -> Expression: ...
    @Threshold.setter
    def Threshold(self, value: Expression) -> None: ...


class ObjectLevelProjectionCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class ObjectLevelLengthRatioRangeResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...
    @property
    def Ratio(self) -> float: ...
    @Ratio.setter
    def Ratio(self, value: float) -> None: ...
    @property
    def Thickness1(self) -> float: ...
    @Thickness1.setter
    def Thickness1(self, value: float) -> None: ...
    @property
    def Thickness2(self) -> float: ...
    @Thickness2.setter
    def Thickness2(self, value: float) -> None: ...


class ObjectLevelLengthRatioRangeCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class ObjectLevelLengthRangeResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def Length(self) -> float: ...
    @Length.setter
    def Length(self, value: float) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...


class ObjectLevelLengthRangeCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class ObjectLevelFlatnessResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def Distance(self) -> float: ...
    @Distance.setter
    def Distance(self, value: float) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...
    @property
    def Point(self) -> Point3d: ...
    @Point.setter
    def Point(self, value: Point3d) -> None: ...
    @property
    def ResultEntity(self) -> TaggedObject: ...
    @ResultEntity.setter
    def ResultEntity(self, value: TaggedObject) -> None: ...


class ObjectLevelFlatnessCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class ObjectLevelFailedProjectionToleranceResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...
    @property
    def OffendingDistance(self) -> float: ...
    @OffendingDistance.setter
    def OffendingDistance(self, value: float) -> None: ...


class ObjectLevelFailedProjectionResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...


class ObjectLevelCorrectedProjectionResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...


class ObjectLevelConnectionAngleResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Angle(self) -> float: ...
    @Angle.setter
    def Angle(self, value: float) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...


class ObjectLevelConnectionAngleCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class NonModeledConnectionResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MinimumDistanceSettings(CAE.QualityAudit.ActionSettings):
    def __init__(self) -> None: ...
    def GetMinimumDistanceByConnectionType(self, connectionType: CAE.Connections.ConnectionType) -> Expression: ...
    @property
    def MinimumDistance(self) -> Expression: ...
    @MinimumDistance.setter
    def MinimumDistance(self, value: Expression) -> None: ...


class MeshSubResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    def GetMesh(self) -> CAE.Mesh: ...
    def GetMeshes(self) -> typing.List[CAE.Mesh]: ...


class MeshLevelProjectionCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class MeshLevelLengthRatioRangeResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...
    @property
    def Ratio(self) -> float: ...
    @Ratio.setter
    def Ratio(self, value: float) -> None: ...
    @property
    def Thickness1(self) -> float: ...
    @Thickness1.setter
    def Thickness1(self, value: float) -> None: ...
    @property
    def Thickness2(self) -> float: ...
    @Thickness2.setter
    def Thickness2(self, value: float) -> None: ...


class MeshLevelLengthRatioRangeCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class MeshLevelLengthRangeResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def Length(self) -> float: ...
    @Length.setter
    def Length(self, value: float) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...


class MeshLevelLengthRangeCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class MeshLevelFlatnessResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def Distance(self) -> float: ...
    @Distance.setter
    def Distance(self, value: float) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...
    @property
    def Point(self) -> Point3d: ...
    @Point.setter
    def Point(self, value: Point3d) -> None: ...
    @property
    def ResultEntity(self) -> TaggedObject: ...
    @ResultEntity.setter
    def ResultEntity(self, value: TaggedObject) -> None: ...


class MeshLevelFlatnessCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class MeshLevelFailedProjectionToleranceResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...
    @property
    def OffendingDistance(self) -> float: ...
    @OffendingDistance.setter
    def OffendingDistance(self, value: float) -> None: ...


class MeshLevelFailedProjectionResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...


class MeshLevelFailedElementCreationResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...


class MeshLevelConnectionAngleResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Angle(self) -> float: ...
    @Angle.setter
    def Angle(self, value: float) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...


class MeshLevelConnectionAngleCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class MeshConnectivity(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class MergedNodesWithMeshesResult(CAE.QualityAudit.MergedNodesResult):
    def __init__(self) -> None: ...
    def GetMeshes(self) -> typing.List[CAE.Mesh]: ...


class MergedNodesWithComponentsResult(CAE.QualityAudit.MergedNodesResult):
    def __init__(self) -> None: ...
    def GetComponents(self) -> typing.List[Assemblies.Component]: ...


class MergedNodesResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    def GetNodes(self) -> typing.List[CAE.FENode]: ...


class MaximumAngleSettings(CAE.QualityAudit.ActionSettings):
    def __init__(self) -> None: ...
    def GetMaximumAngleByConnectionType(self, connectionType: CAE.Connections.ConnectionType) -> Expression: ...
    @property
    def MaximumAngle(self) -> Expression: ...
    @MaximumAngle.setter
    def MaximumAngle(self, value: Expression) -> None: ...


class ManualElementsWithMeshesResult(CAE.QualityAudit.ManualElementsResult):
    def __init__(self) -> None: ...
    def GetMeshes(self) -> typing.List[CAE.Mesh]: ...


class ManualElementsWithComponentsResult(CAE.QualityAudit.ManualElementsResult):
    def __init__(self) -> None: ...
    def GetComponents(self) -> typing.List[Assemblies.Component]: ...


class ManualElementsResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    def GetElements(self) -> typing.List[CAE.FEElement]: ...


class Manager(Utilities.NXRemotableObject):
    def __init__(self, owner: CAE.CaeSession) -> None: ...
    def FindObject(self, journalIdentifier: str) -> INXObject: ...
    def PerformActions(self, inputActions: typing.List[CAE.QualityAudit.Action], pObjects: typing.List[NXObject]) -> None: ...
    def ExportResults(self, actionsToExport: typing.List[CAE.QualityAudit.Action], resultsFIle: str) -> None: ...
    def Tag(self) -> Tag: ...

    @property
    def ActionList(self) -> CAE.QualityAudit.ActionList: ...
    @ActionList.setter
    def ActionList(self, value: CAE.QualityAudit.ActionList) -> None: ...
    @property
    def CurrentActionType(self) -> CAE.QualityAudit.Manager.ActionType: ...
    @CurrentActionType.setter
    def CurrentActionType(self, value: CAE.QualityAudit.Manager.ActionType) -> None: ...
    @property
    def InputList(self) -> CAE.QualityAudit.InputList: ...
    @InputList.setter
    def InputList(self, value: CAE.QualityAudit.InputList) -> None: ...
    @property
    def UseInputListForSynthesis(self) -> bool: ...
    @UseInputListForSynthesis.setter
    def UseInputListForSynthesis(self, value: bool) -> None: ...


    class ActionType(enum.Enum):
        Global= 0
        Connection= 1
    

class ListNonModeledConnectionsResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...


class ListNonModeledConnections(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class ListConnectionsResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> TaggedObject: ...
    @Connection.setter
    def Connection(self, value: TaggedObject) -> None: ...


class ListConnections(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class LengthRatioRangeSettings(CAE.QualityAudit.ActionSettings):
    def __init__(self) -> None: ...
    def GetMinimumRatioByConnectionType(self, connectionType: CAE.Connections.ConnectionType) -> Expression: ...
    def GetMaximumRatioByConnectionType(self, connectionType: CAE.Connections.ConnectionType) -> Expression: ...
    @property
    def MaximumRatio(self) -> Expression: ...
    @MaximumRatio.setter
    def MaximumRatio(self, value: Expression) -> None: ...
    @property
    def MinimumRatio(self) -> Expression: ...
    @MinimumRatio.setter
    def MinimumRatio(self, value: Expression) -> None: ...


class LengthRangeSettings(CAE.QualityAudit.ActionSettings):
    def __init__(self) -> None: ...
    def GetMinimumDistanceByConnectionType(self, connectionType: CAE.Connections.ConnectionType) -> Expression: ...
    def GetMaximumDistanceByConnectionType(self, connectionType: CAE.Connections.ConnectionType) -> Expression: ...
    @property
    def MaximumDistance(self) -> Expression: ...
    @MaximumDistance.setter
    def MaximumDistance(self, value: Expression) -> None: ...
    @property
    def MinimumDistance(self) -> Expression: ...
    @MinimumDistance.setter
    def MinimumDistance(self, value: Expression) -> None: ...


class InputList(NXObject):
    def __init__(self) -> None: ...
    def GetAllObjects(self) -> typing.List[NXObject]: ...
    def SelectAll(self) -> None: ...
    def DeselectAll(self) -> None: ...
    def Select(self, obj: NXObject) -> None: ...
    def Deselect(self, obj: NXObject) -> None: ...
    def IsSelected(self, obj: NXObject) -> bool: ...
    def GetSelectedObjects(self) -> typing.List[NXObject]: ...


class IConnectedMeshes():
    def GetMeshes(self) -> typing.List[CAE.Mesh]: ...


class IConnectedComponents():
    def GetComponents(self) -> typing.List[Assemblies.Component]: ...


class FreeEdgeDistanceResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    def GetClosestConnectionPoint(self) -> Point3d: ...
    @property
    def CaeEdge(self) -> CAE.CAEEdge: ...
    @CaeEdge.setter
    def CaeEdge(self, value: CAE.CAEEdge) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex(self) -> int: ...
    @CoordinateIndex.setter
    def CoordinateIndex(self, value: int) -> None: ...
    @property
    def DefinitionIndex(self) -> int: ...
    @DefinitionIndex.setter
    def DefinitionIndex(self, value: int) -> None: ...
    @property
    def Distance(self) -> float: ...
    @Distance.setter
    def Distance(self, value: float) -> None: ...
    @property
    def EdgePoint(self) -> Point3d: ...
    @EdgePoint.setter
    def EdgePoint(self, value: Point3d) -> None: ...
    @property
    def FeElementEdge(self) -> CAE.FEElemEdge: ...
    @FeElementEdge.setter
    def FeElementEdge(self, value: CAE.FEElemEdge) -> None: ...
    @property
    def FlangeIndex(self) -> int: ...
    @FlangeIndex.setter
    def FlangeIndex(self, value: int) -> None: ...
    @property
    def LocationIndex(self) -> int: ...
    @LocationIndex.setter
    def LocationIndex(self, value: int) -> None: ...


class FreeEdgeDistanceCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class FlatnessSettings(CAE.QualityAudit.ActionSettings):
    def __init__(self) -> None: ...
    @property
    def ClosestPointFlag(self) -> bool: ...
    @ClosestPointFlag.setter
    def ClosestPointFlag(self, value: bool) -> None: ...
    @property
    def Height(self) -> Expression: ...
    @Height.setter
    def Height(self, value: Expression) -> None: ...
    @property
    def Radius(self) -> Expression: ...
    @Radius.setter
    def Radius(self, value: Expression) -> None: ...


class ConnectionWithMeshesResult(CAE.QualityAudit.ConnectionResult):
    def __init__(self) -> None: ...
    def GetMeshes(self) -> typing.List[CAE.Mesh]: ...


class ConnectionWithComponentsResult(CAE.QualityAudit.ConnectionResult):
    def __init__(self) -> None: ...
    def GetComponents(self) -> typing.List[Assemblies.Component]: ...


class ConnectionSynthesis(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class ConnectionResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> TaggedObject: ...
    @Connection.setter
    def Connection(self, value: TaggedObject) -> None: ...
    @property
    def Femodel(self) -> CAE.FEModelOccurrence: ...
    @Femodel.setter
    def Femodel(self, value: CAE.FEModelOccurrence) -> None: ...


class ConnectionPointsDistanceResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection(self) -> CAE.Connections.IConnection: ...
    @Connection.setter
    def Connection(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex1(self) -> int: ...
    @CoordinateIndex1.setter
    def CoordinateIndex1(self, value: int) -> None: ...
    @property
    def CoordinateIndex2(self) -> int: ...
    @CoordinateIndex2.setter
    def CoordinateIndex2(self, value: int) -> None: ...
    @property
    def DefinitionIndex1(self) -> int: ...
    @DefinitionIndex1.setter
    def DefinitionIndex1(self, value: int) -> None: ...
    @property
    def DefinitionIndex2(self) -> int: ...
    @DefinitionIndex2.setter
    def DefinitionIndex2(self, value: int) -> None: ...
    @property
    def Distance(self) -> float: ...
    @Distance.setter
    def Distance(self, value: float) -> None: ...
    @property
    def LocationIndex1(self) -> int: ...
    @LocationIndex1.setter
    def LocationIndex1(self, value: int) -> None: ...
    @property
    def LocationIndex2(self) -> int: ...
    @LocationIndex2.setter
    def LocationIndex2(self, value: int) -> None: ...


class ConnectionPointsDistanceCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class ConnectionDistanceResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    @property
    def Connection1(self) -> CAE.Connections.IConnection: ...
    @Connection1.setter
    def Connection1(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def Connection2(self) -> CAE.Connections.IConnection: ...
    @Connection2.setter
    def Connection2(self, value: CAE.Connections.IConnection) -> None: ...
    @property
    def CoordinateIndex1(self) -> int: ...
    @CoordinateIndex1.setter
    def CoordinateIndex1(self, value: int) -> None: ...
    @property
    def CoordinateIndex2(self) -> int: ...
    @CoordinateIndex2.setter
    def CoordinateIndex2(self, value: int) -> None: ...
    @property
    def Coordinates1(self) -> Point3d: ...
    @Coordinates1.setter
    def Coordinates1(self, value: Point3d) -> None: ...
    @property
    def Coordinates2(self) -> Point3d: ...
    @Coordinates2.setter
    def Coordinates2(self, value: Point3d) -> None: ...
    @property
    def DefinitionIndex1(self) -> int: ...
    @DefinitionIndex1.setter
    def DefinitionIndex1(self, value: int) -> None: ...
    @property
    def DefinitionIndex2(self) -> int: ...
    @DefinitionIndex2.setter
    def DefinitionIndex2(self, value: int) -> None: ...
    @property
    def Distance(self) -> float: ...
    @Distance.setter
    def Distance(self, value: float) -> None: ...
    @property
    def LocationIndex1(self) -> int: ...
    @LocationIndex1.setter
    def LocationIndex1(self, value: int) -> None: ...
    @property
    def LocationIndex2(self) -> int: ...
    @LocationIndex2.setter
    def LocationIndex2(self, value: int) -> None: ...


class ConnectionDistanceCheck(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class ConnectedMeshesGroupResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    def GetMeshes(self) -> typing.List[CAE.Mesh]: ...


class ConnectedComponentsGroupResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    def GetComponents(self) -> typing.List[Assemblies.Component]: ...


class ComponentSubResult(CAE.QualityAudit.Result):
    def __init__(self) -> None: ...
    def GetComponent(self) -> Assemblies.Component: ...
    def GetComponents(self) -> typing.List[Assemblies.Component]: ...


class ComponentConnectivity(CAE.QualityAudit.Action):
    def __init__(self) -> None: ...


class ActionSettings(NXObject):
    def __init__(self) -> None: ...
    def ResetToDefaults(self) -> None: ...
    def GetSupportedConnectionTypes(self) -> typing.List[CAE.Connections.ConnectionType]: ...
    def AllowOverride(self, connectionType: CAE.Connections.ConnectionType, allowOverride: bool) -> None: ...
    def CanOverride(self, connectionType: CAE.Connections.ConnectionType) -> bool: ...
    @property
    def Action(self) -> CAE.QualityAudit.Action: ...
    @Action.setter
    def Action(self, value: CAE.QualityAudit.Action) -> None: ...


class ActionList(NXObject):
    def __init__(self) -> None: ...
    def GetAction(self, id: CAE.QualityAudit.Action.Id) -> CAE.QualityAudit.Action: ...
    def SelectAll(self) -> None: ...
    def DeselectAll(self) -> None: ...
    def IsSelected(self, pAction: CAE.QualityAudit.Action) -> bool: ...
    def Select(self, pAction: CAE.QualityAudit.Action) -> None: ...
    def Deselect(self, pAction: CAE.QualityAudit.Action) -> None: ...
    def GetSelectedActions(self) -> typing.List[CAE.QualityAudit.Action]: ...
    def LoadActionSettings(self, actionConfigFile: str) -> None: ...
    def SaveActionSettings(self, actionConfigFile: str) -> None: ...


class Action(NXObject):
    def __init__(self) -> None: ...
    def Perform(self, objects: typing.List[NXObject]) -> None: ...
    def GetResults(self) -> typing.List[CAE.QualityAudit.Result]: ...
    def ExportResults(self, resultsFIle: str) -> None: ...
    @property
    def ActionId(self) -> CAE.QualityAudit.Action.Id: ...
    @ActionId.setter
    def ActionId(self, value: CAE.QualityAudit.Action.Id) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def Settings(self) -> CAE.QualityAudit.ActionSettings: ...
    @Settings.setter
    def Settings(self, value: CAE.QualityAudit.ActionSettings) -> None: ...


    class Id(enum.Enum):
        AllConnectionsList= 0
        NonModeledConnectionsList= 1
        SubAssemblyComponentCheck= 2
        SubAssemblyMeshCheck= 3
        ObjectLevelProjectionCheck= 4
        MeshLevelProjectionCheck= 5
        DistanceBetweenConnectionPointsCheck= 6
        DistanceBetweenConnectionsCheck= 7
        FreeEdgeDistanceCheck= 8
        TargetSequenceCheck= 9
        ObjectLevelLengthCheck= 10
        MeshLevelLengthCheck= 11
        ObjectLevelLengthRatioCheck= 12
        MeshLevelLengthRatioCheck= 13
        ObjectLevelConnectionAngleCheck= 14
        MeshLevelConnectionAngleCheck= 15
        ObjectLevelFlatnessCheck= 16
        MeshLevelFlatnessCheck= 17
        ConnectionSynthesis= 18
    

