from ...NXOpen import *

import typing
import enum

class PartUtils(Utilities.NXRemotableObject):
    def __init__(self, owner: CloudDM.DataManager) -> None: ...
    def GetDocumentIdentifier(self, inputPart: Part) -> CloudDM.DocumentIdentifier: ...
    def SaveAs(self, inputPart: Part, newFileName: str, newDesignInfo: CloudDM.NewPartBuilder) -> PartSaveStatus: ...
    def CheckoutParts(self, partsToCheckOut: typing.List[Part]) -> None: ...
    def CheckinParts(self, partsToCheckIn: typing.List[Part]) -> None: ...
    def FreezeParts(self, partsToFreeze: typing.List[Part]) -> None: ...
    def GetRelatedDrawings(self, inputPart: Part) -> typing.List[CloudDM.DocumentIdentifier]: ...
    def Tag(self) -> Tag: ...



class PartOperationObject(NXObject):
    def __init__(self) -> None: ...


class PartOperationBuilder(Builder):
    def __init__(self) -> None: ...
    def SetOperationType(self, optype: CloudDM.PartOperationBuilder.OperationType) -> None: ...
    def GetOperationType(self) -> CloudDM.PartOperationBuilder.OperationType: ...
    def SetSourceParts(self, sourceParts: typing.List[BasePart]) -> None: ...
    def CreatePartOperationObjects(self, partOperationObjects: typing.List[CloudDM.PartOperationObject], errorMsgs: str, status: int) -> None: ...
    def ValidatePartOperationObjects(self) -> None: ...
    def SetTargetPath(self, targetPath: str) -> None: ...
    def GetOperationFailures(self) -> ErrorList: ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList: ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList: ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject: ...


    class OperationType(enum.Enum):
        CreateSpecification= 0
        NamePart= 1
        MakeUnique= 2
        Revise= 3
        SaveAs= 4
        Mirror= 5
        Max= 6
    

class NewPartBuilder(Builder):
    def __init__(self) -> None: ...
    def AutoAssignDesignNumber(self) -> None: ...
    def SynchronizeAttributes(self) -> None: ...
    def SetTemplatePartContext(self, templatePartContext: CloudDM.NewPartBuilder.TemplatePartContextinfo) -> None: ...
    @property
    def AttributeHolder(self) -> NXObject: ...
    @AttributeHolder.setter
    def AttributeHolder(self, value: NXObject) -> None: ...
    @property
    def DesignDescription(self) -> str: ...
    @DesignDescription.setter
    def DesignDescription(self, value: str) -> None: ...
    @property
    def DesignName(self) -> str: ...
    @DesignName.setter
    def DesignName(self, value: str) -> None: ...
    @property
    def DesignNumber(self) -> str: ...
    @DesignNumber.setter
    def DesignNumber(self, value: str) -> None: ...
    @property
    def DesignRevision(self) -> str: ...
    @DesignRevision.setter
    def DesignRevision(self, value: str) -> None: ...
    @property
    def Folder(self) -> str: ...
    @Folder.setter
    def Folder(self, value: str) -> None: ...
    @property
    def Project(self) -> str: ...
    @Project.setter
    def Project(self, value: str) -> None: ...
    @property
    def TemplatePart(self) -> str: ...
    @TemplatePart.setter
    def TemplatePart(self, value: str) -> None: ...


    class NewPartBuilderTemplatePartContextinfo():
        @property
        def CollaborationSpaceId(self) -> str: ...
        @CollaborationSpaceId.setter
        def CollaborationSpaceId(self, value: str) -> None: ...
        @property
        def ContainerId(self) -> str: ...
        @ContainerId.setter
        def ContainerId(self, value: str) -> None: ...
        @property
        def ContainerType(self) -> str: ...
        @ContainerType.setter
        def ContainerType(self, value: str) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, CollaborationSpaceId: str, ContainerId: str, ContainerType: str) -> None: ...
    

    class NewPartBuilder_TemplatePartContextinfo():
        @property
        def collaborationSpaceId(self) -> int: ...
        @collaborationSpaceId.setter
        def collaborationSpaceId(self, value: int) -> None: ...
        @property
        def containerId(self) -> int: ...
        @containerId.setter
        def containerId(self, value: int) -> None: ...
        @property
        def containerType(self) -> int: ...
        @containerType.setter
        def containerType(self, value: int) -> None: ...
    

class NewPartAttributeHolder(NXObject):
    def __init__(self) -> None: ...


class FileManagement(Utilities.NXRemotableObject):
    def __init__(self, owner: CloudDM.DataManager) -> None: ...
    def GetAssociatedDocumentList(self, inputPart: BasePart) -> typing.List[CloudDM.DocumentIdentifier]: ...
    def DownloadAssociatedDocuments(self, inputPart: BasePart, documents: typing.List[CloudDM.DocumentIdentifier]) -> None: ...
    def GetAssociatedFileListForUpload(self, inputPart: BasePart) -> typing.List[CloudDM.FileManagement.FileInfo]: ...
    def UploadAssociatedDocuments(self, inputPart: BasePart, fileList: typing.List[CloudDM.FileManagement.FileInfo]) -> None: ...
    def Tag(self) -> Tag: ...



    class FileManagementFileInfo():
        @property
        def FilePath(self) -> str: ...
        @FilePath.setter
        def FilePath(self, value: str) -> None: ...
        @property
        def FileType(self) -> str: ...
        @FileType.setter
        def FileType(self, value: str) -> None: ...
        @property
        def IsText(self) -> bool: ...
        @IsText.setter
        def IsText(self, value: bool) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, FilePath: str, FileType: str, IsText: bool) -> None: ...
    

    class FileManagement_FileInfo():
        @property
        def filePath(self) -> int: ...
        @filePath.setter
        def filePath(self, value: int) -> None: ...
        @property
        def fileType(self) -> int: ...
        @fileType.setter
        def fileType(self, value: int) -> None: ...
        @property
        def isText(self) -> bool: ...
        @isText.setter
        def isText(self, value: bool) -> None: ...
    

class DocumentIdentifier(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def DateModified(self) -> str: ...
    @DateModified.setter
    def DateModified(self, value: str) -> None: ...
    @property
    def DocumentUrn(self) -> str: ...
    @DocumentUrn.setter
    def DocumentUrn(self, value: str) -> None: ...
    @property
    def LockInfo(self) -> CloudDM.DocumentIdentifier.LockInformation: ...
    @LockInfo.setter
    def LockInfo(self, value: CloudDM.DocumentIdentifier.LockInformation) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Owner(self) -> str: ...
    @Owner.setter
    def Owner(self, value: str) -> None: ...
    @property
    def RevisionUrn(self) -> str: ...
    @RevisionUrn.setter
    def RevisionUrn(self, value: str) -> None: ...


    class DocumentIdentifierLockInformation():
        @property
        def LockedAt(self) -> str: ...
        @LockedAt.setter
        def LockedAt(self, value: str) -> None: ...
        @property
        def LockExpires(self) -> str: ...
        @LockExpires.setter
        def LockExpires(self, value: str) -> None: ...
        @property
        def LockedBy(self) -> str: ...
        @LockedBy.setter
        def LockedBy(self, value: str) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, LockedAt: str, LockExpires: str, LockedBy: str) -> None: ...
    

    class DocumentIdentifier_LockInformation():
        @property
        def lockedAt(self) -> int: ...
        @lockedAt.setter
        def lockedAt(self, value: int) -> None: ...
        @property
        def lockExpires(self) -> int: ...
        @lockExpires.setter
        def lockExpires(self, value: int) -> None: ...
        @property
        def lockedBy(self) -> int: ...
        @lockedBy.setter
        def lockedBy(self, value: int) -> None: ...
    

class DataManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetDataManager(self, owner: Session) -> CloudDM.DataManager: ...
    def GetCheckedoutStatusOfAllObjectsInSession(self, checkedOutObjects: typing.List[NXObject], uncheckedOutObjects: typing.List[NXObject]) -> None: ...
    def CreatePartOperationBuilder(self, operation: CloudDM.PartOperationBuilder.OperationType) -> CloudDM.PartOperationBuilder: ...
    def Tag(self) -> Tag: ...

    @property
    def FileManagement(self) -> CloudDM.FileManagement: ...
    @FileManagement.setter
    def FileManagement(self, value: CloudDM.FileManagement) -> None: ...
    @property
    def PartUtils(self) -> CloudDM.PartUtils: ...
    @PartUtils.setter
    def PartUtils(self, value: CloudDM.PartUtils) -> None: ...


    class DataManagerImportPartInput():
        @property
        def LocalFileName(self) -> str: ...
        @LocalFileName.setter
        def LocalFileName(self, value: str) -> None: ...
        @property
        def RelativeFilePath(self) -> str: ...
        @RelativeFilePath.setter
        def RelativeFilePath(self, value: str) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, LocalFileName: str, RelativeFilePath: str) -> None: ...
    

    class DataManagerImportPartDesign():
        @property
        def InputPart(self) -> str: ...
        @InputPart.setter
        def InputPart(self, value: str) -> None: ...
        @property
        def RevisionUrn(self) -> str: ...
        @RevisionUrn.setter
        def RevisionUrn(self, value: str) -> None: ...
        @property
        def DownloadTicket(self) -> str: ...
        @DownloadTicket.setter
        def DownloadTicket(self, value: str) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, InputPart: str, RevisionUrn: str, DownloadTicket: str) -> None: ...
    

    class DataManagerContainerInfo():
        @property
        def Name(self) -> str: ...
        @Name.setter
        def Name(self, value: str) -> None: ...
        @property
        def Description(self) -> str: ...
        @Description.setter
        def Description(self, value: str) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, Name: str, Description: str) -> None: ...
    

    class DataManager_ImportPartInput():
        @property
        def localFileName(self) -> int: ...
        @localFileName.setter
        def localFileName(self, value: int) -> None: ...
        @property
        def relativeFilePath(self) -> int: ...
        @relativeFilePath.setter
        def relativeFilePath(self, value: int) -> None: ...
    

    class DataManager_ImportPartDesign():
        @property
        def inputPart(self) -> int: ...
        @inputPart.setter
        def inputPart(self, value: int) -> None: ...
        @property
        def revisionUrn(self) -> int: ...
        @revisionUrn.setter
        def revisionUrn(self, value: int) -> None: ...
        @property
        def downloadTicket(self) -> int: ...
        @downloadTicket.setter
        def downloadTicket(self, value: int) -> None: ...
    

    class DataManager_ContainerInfo():
        @property
        def name(self) -> int: ...
        @name.setter
        def name(self, value: int) -> None: ...
        @property
        def description(self) -> int: ...
        @description.setter
        def description(self, value: int) -> None: ...
    

