from ....NXOpen import *
from ...Features import *

import typing
import enum

class SuperFrameBuilder(Features.StructureDesign.FeatureParmsBuilder):
    def __init__(self) -> None: ...
    def AddAction(self, sourceCurves: typing.List[Curve], actionType: Features.StructureDesign.SuperFrameBuilder.TransformTypes, actionDirection: Vector3d, actionDistance: float) -> None: ...
    def UndoAction(self) -> None: ...
    def CreateCurves(self) -> None: ...
    def CopyCurve(self, curveTag: Curve) -> Curve: ...
    def UpdateCurve(self, curveTag: Curve, startPoint: Point3d, endPoint: Point3d) -> None: ...
    def DeleteCurve(self, curveTag: Curve) -> None: ...
    def ReparentAndDeleteCurve(self, curveTag: Curve) -> None: ...
    @property
    def BoundaryCurve(self) -> ScCollector: ...
    @BoundaryCurve.setter
    def BoundaryCurve(self, value: ScCollector) -> None: ...
    @property
    def Height(self) -> Expression: ...
    @Height.setter
    def Height(self, value: Expression) -> None: ...
    @property
    def InputMode0(self) -> Features.StructureDesign.SuperFrameBuilder.InputModes: ...
    @InputMode0.setter
    def InputMode0(self, value: Features.StructureDesign.SuperFrameBuilder.InputModes) -> None: ...
    @property
    def InputMode1(self) -> Features.StructureDesign.SuperFrameBuilder.InputModes: ...
    @InputMode1.setter
    def InputMode1(self, value: Features.StructureDesign.SuperFrameBuilder.InputModes) -> None: ...
    @property
    def InputMode2(self) -> Features.StructureDesign.SuperFrameBuilder.InputModes: ...
    @InputMode2.setter
    def InputMode2(self, value: Features.StructureDesign.SuperFrameBuilder.InputModes) -> None: ...
    @property
    def Length(self) -> Expression: ...
    @Length.setter
    def Length(self, value: Expression) -> None: ...
    @property
    def Point0(self) -> Point: ...
    @Point0.setter
    def Point0(self, value: Point) -> None: ...
    @property
    def Point0X(self) -> Expression: ...
    @Point0X.setter
    def Point0X(self, value: Expression) -> None: ...
    @property
    def Point0Y(self) -> Expression: ...
    @Point0Y.setter
    def Point0Y(self, value: Expression) -> None: ...
    @property
    def Point0Z(self) -> Expression: ...
    @Point0Z.setter
    def Point0Z(self, value: Expression) -> None: ...
    @property
    def Point1(self) -> Point: ...
    @Point1.setter
    def Point1(self, value: Point) -> None: ...
    @property
    def Point1X(self) -> Expression: ...
    @Point1X.setter
    def Point1X(self, value: Expression) -> None: ...
    @property
    def Point1Y(self) -> Expression: ...
    @Point1Y.setter
    def Point1Y(self, value: Expression) -> None: ...
    @property
    def Point2(self) -> Point: ...
    @Point2.setter
    def Point2(self, value: Point) -> None: ...
    @property
    def Point2Z(self) -> Expression: ...
    @Point2Z.setter
    def Point2Z(self, value: Expression) -> None: ...
    @property
    def SplitCurve(self) -> ScCollector: ...
    @SplitCurve.setter
    def SplitCurve(self, value: ScCollector) -> None: ...
    @property
    def Width(self) -> Expression: ...
    @Width.setter
    def Width(self, value: Expression) -> None: ...


    class TransformTypes(enum.Enum):
        Move= 0
        Copy= 1
        Split= 2
        Delete= 3
        None_= 4
    

    class InputModes(enum.Enum):
        Coordinates= 0
        Parameters= 1
    

    class BaseTypes(enum.Enum):
        None_= 0
        Corners= 1
        Transform= 2
    

class SuperFrame(Features.BodyFeature):
    def __init__(self) -> None: ...


class StiffenerBuilder(Features.FeatureBuilder):
    def __init__(self) -> None: ...
    @property
    def Alignment(self) -> SelectTaggedObjectList: ...
    @Alignment.setter
    def Alignment(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def AttachmentSide(self) -> Features.StructureDesign.StiffenerBuilder.AttachmentSides: ...
    @AttachmentSide.setter
    def AttachmentSide(self, value: Features.StructureDesign.StiffenerBuilder.AttachmentSides) -> None: ...
    @property
    def DepthOffset(self) -> Expression: ...
    @DepthOffset.setter
    def DepthOffset(self, value: Expression) -> None: ...
    @property
    def FillType(self) -> Features.StructureDesign.StiffenerBuilder.FillTypes: ...
    @FillType.setter
    def FillType(self, value: Features.StructureDesign.StiffenerBuilder.FillTypes) -> None: ...
    @property
    def Height(self) -> Expression: ...
    @Height.setter
    def Height(self, value: Expression) -> None: ...
    @property
    def HeightType(self) -> Features.StructureDesign.StiffenerBuilder.HeightTypes: ...
    @HeightType.setter
    def HeightType(self, value: Features.StructureDesign.StiffenerBuilder.HeightTypes) -> None: ...
    @property
    def OffsetDistance(self) -> Expression: ...
    @OffsetDistance.setter
    def OffsetDistance(self, value: Expression) -> None: ...
    @property
    def ReverseOffset(self) -> bool: ...
    @ReverseOffset.setter
    def ReverseOffset(self, value: bool) -> None: ...
    @property
    def SelectObject(self) -> SelectTaggedObject: ...
    @SelectObject.setter
    def SelectObject(self, value: SelectTaggedObject) -> None: ...
    @property
    def StiffenerName(self) -> str: ...
    @StiffenerName.setter
    def StiffenerName(self, value: str) -> None: ...
    @property
    def StockData(self) -> Features.StructureDesign.FeatureSpreadsheetBuilder: ...
    @StockData.setter
    def StockData(self, value: Features.StructureDesign.FeatureSpreadsheetBuilder) -> None: ...
    @property
    def ThicknessDir(self) -> Features.StructureDesign.StiffenerBuilder.ThicknessDirs: ...
    @ThicknessDir.setter
    def ThicknessDir(self, value: Features.StructureDesign.StiffenerBuilder.ThicknessDirs) -> None: ...


    class ThicknessDirs(enum.Enum):
        Upper= 0
        Lower= 1
        Center= 2
    

    class HeightTypes(enum.Enum):
        Default= 0
        Input= 1
    

    class FillTypes(enum.Enum):
        UppperHalf= 0
        LowerHalf= 1
        Full= 2
        MatchedCope= 3
    

    class AttachmentSides(enum.Enum):
        Left= 0
        Right= 1
        Both= 2
    

class Stiffener(Features.BodyFeature):
    def __init__(self) -> None: ...


class SelectCornerList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Add(self, object: Features.StructureDesign.Corner) -> bool: ...
    @typing.overload
    def Add(self, objects: typing.List[Features.StructureDesign.Corner]) -> bool: ...
    @typing.overload
    def Add(self, inputSelectionMethod: SelectionMethod) -> bool: ...
    @typing.overload
    def Add(self, selection: Features.StructureDesign.Corner, view: View, point: Point3d) -> bool: ...
    @typing.overload
    def Remove(self, object: Features.StructureDesign.Corner) -> bool: ...
    @typing.overload
    def Remove(self, object: Features.StructureDesign.Corner, view: View) -> bool: ...
    @typing.overload
    def Remove(self, snapType: InferSnapType.SnapType, selection1: Features.StructureDesign.Corner, view1: View, point1: Point3d, selection2: Features.StructureDesign.Corner, view2: View, point2: Point3d) -> bool: ...
    def RemoveArray(self, objects: typing.List[Features.StructureDesign.Corner]) -> bool: ...
    def Remove(self, inputSelectionMethod: SelectionMethod) -> bool: ...
    def Clear(self) -> None: ...
    def Contains(self, object: Features.StructureDesign.Corner) -> bool: ...
    def SetArray(self, objects: typing.List[Features.StructureDesign.Corner]) -> None: ...
    def GetArray(self) -> typing.List[Features.StructureDesign.Corner]: ...
    def GetSelectObjectArray(self) -> typing.List[SelectObject]: ...
    @typing.overload
    def Add(self, snapType: InferSnapType.SnapType, selection1: Features.StructureDesign.Corner, view1: View, point1: Point3d, selection2: Features.StructureDesign.Corner, view2: View, point2: Point3d) -> bool: ...
    @typing.overload
    def Add(self, selection: Features.StructureDesign.Corner, caeSubType: CaeObjectType.CaeSubType, caeSubId: int) -> bool: ...
    def Validate(self) -> bool: ...
    @property
    def DuplicatesAllowed(self) -> bool: ...
    @DuplicatesAllowed.setter
    def DuplicatesAllowed(self, value: bool) -> None: ...
    @property
    def Size(self) -> int: ...
    @Size.setter
    def Size(self, value: int) -> None: ...


class SelectCorner(TaggedObject):
    def __init__(self) -> None: ...
    def SetValue(self, selection: Features.StructureDesign.Corner, view: View, point: Point3d) -> None: ...
    def GetValue(self, selection: Features.StructureDesign.Corner, view: View, point: Point3d) -> None: ...
    def SetValue(self, snapType: InferSnapType.SnapType, selection1: Features.StructureDesign.Corner, view1: View, point1: Point3d, selection2: Features.StructureDesign.Corner, view2: View, point2: Point3d) -> None: ...
    def GetValue(self, snapType: InferSnapType.SnapType, selection1: Features.StructureDesign.Corner, view1: View, point1: Point3d, selection2: Features.StructureDesign.Corner, view2: View, point2: Point3d) -> None: ...
    def SetValue(self, selection: Features.StructureDesign.Corner, caeSubType: CaeObjectType.CaeSubType, caeSubId: int) -> None: ...
    def GetValue(self, caeSubType: CaeObjectType.CaeSubType, caeSubId: int) -> Features.StructureDesign.Corner: ...
    def Validate(self) -> bool: ...
    @property
    def Value(self) -> Features.StructureDesign.Corner: ...
    @Value.setter
    def Value(self, value: Features.StructureDesign.Corner) -> None: ...


class RuleBuilder(Features.FeatureBuilder):
    def __init__(self) -> None: ...
    @property
    def ButtOption(self) -> Features.StructureDesign.RuleBuilder.ButtOptions: ...
    @ButtOption.setter
    def ButtOption(self, value: Features.StructureDesign.RuleBuilder.ButtOptions) -> None: ...
    @property
    def CopeOption(self) -> Features.StructureDesign.RuleBuilder.CopeOptions: ...
    @CopeOption.setter
    def CopeOption(self, value: Features.StructureDesign.RuleBuilder.CopeOptions) -> None: ...
    @property
    def Cutback(self) -> Expression: ...
    @Cutback.setter
    def Cutback(self, value: Expression) -> None: ...
    @property
    def HorizontalCornerType(self) -> Features.StructureDesign.RuleBuilder.CornerTypes: ...
    @HorizontalCornerType.setter
    def HorizontalCornerType(self, value: Features.StructureDesign.RuleBuilder.CornerTypes) -> None: ...
    @property
    def InnerCornerType(self) -> Features.StructureDesign.RuleBuilder.CornerTypes: ...
    @InnerCornerType.setter
    def InnerCornerType(self, value: Features.StructureDesign.RuleBuilder.CornerTypes) -> None: ...
    @property
    def Placement(self) -> Features.StructureDesign.RuleBuilder.Placements: ...
    @Placement.setter
    def Placement(self, value: Features.StructureDesign.RuleBuilder.Placements) -> None: ...
    @property
    def VerticalCornerType(self) -> Features.StructureDesign.RuleBuilder.CornerTypes: ...
    @VerticalCornerType.setter
    def VerticalCornerType(self, value: Features.StructureDesign.RuleBuilder.CornerTypes) -> None: ...


    class Placements(enum.Enum):
        Inside= 0
        Center= 1
        Outside= 2
    

    class CornerTypes(enum.Enum):
        None_= 0
        Miter= 1
        Butt= 2
        Cope= 3
        MatchedCope= 4
    

    class CopeOptions(enum.Enum):
        CopeShortest= 0
        CopeLongest= 1
    

    class ButtOptions(enum.Enum):
        ButtShortest= 0
        ButtLongest= 1
    

class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MemberPathBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def CoordSystem(self) -> CoordinateSystem: ...
    @CoordSystem.setter
    def CoordSystem(self, value: CoordinateSystem) -> None: ...
    @property
    def PathMethod(self) -> Features.StructureDesign.MemberPathBuilder.MemberPathMethod: ...
    @PathMethod.setter
    def PathMethod(self, value: Features.StructureDesign.MemberPathBuilder.MemberPathMethod) -> None: ...
    @property
    def PathOffset(self) -> Expression: ...
    @PathOffset.setter
    def PathOffset(self, value: Expression) -> None: ...
    @property
    def PathPoint(self) -> Point: ...
    @PathPoint.setter
    def PathPoint(self, value: Point) -> None: ...
    @property
    def SelectFirstMember(self) -> SelectNXObject: ...
    @SelectFirstMember.setter
    def SelectFirstMember(self, value: SelectNXObject) -> None: ...
    @property
    def SelectSecondMember(self) -> SelectNXObject: ...
    @SelectSecondMember.setter
    def SelectSecondMember(self, value: SelectNXObject) -> None: ...


    class MemberPathMethod(enum.Enum):
        Members= 0
        Csys= 1
        Point= 2
    

class MemberBuilder(Features.StructureDesign.FeatureParmsBuilder):
    def __init__(self) -> None: ...
    def FlipX(self) -> None: ...
    def FlipY(self) -> None: ...
    def EvaluateStructurePositionInformation(self, curves: typing.List[NXObject]) -> None: ...
    def SetEditingPreviewCorner(self, corner: Features.StructureDesign.Corner) -> None: ...
    def GetEditingPreviewCorner(self) -> Features.StructureDesign.Corner: ...
    def PrepareBeforeEditingCorner(self, corner: Features.StructureDesign.Corner) -> None: ...
    def CleanAfterEditingCorner(self, corner: Features.StructureDesign.Corner) -> None: ...
    def CreatePreviewBodies(self) -> int: ...
    def DestroyPreviewBodies(self) -> None: ...
    def DestroyPreviewBodyMap(self) -> None: ...
    def SetPreviewbodyChecksumAttribute(self) -> None: ...
    def DeletePreviewCorners(self) -> None: ...
    def ClearCombinedCurveMap(self, curves: typing.List[NXObject]) -> None: ...
    def ClearAllCombinedCurveMap(self) -> None: ...
    def ClearAllAdjustedPath(self) -> None: ...
    @property
    def AlternateOrigin(self) -> int: ...
    @AlternateOrigin.setter
    def AlternateOrigin(self, value: int) -> None: ...
    @property
    def EnableMergeColinearPath(self) -> bool: ...
    @EnableMergeColinearPath.setter
    def EnableMergeColinearPath(self, value: bool) -> None: ...
    @property
    def EndCornerEnd(self) -> Features.StructureDesign.MemberBuilder.EndCornerTypes: ...
    @EndCornerEnd.setter
    def EndCornerEnd(self, value: Features.StructureDesign.MemberBuilder.EndCornerTypes) -> None: ...
    @property
    def EndCornerStart(self) -> Features.StructureDesign.MemberBuilder.EndCornerTypes: ...
    @EndCornerStart.setter
    def EndCornerStart(self, value: Features.StructureDesign.MemberBuilder.EndCornerTypes) -> None: ...
    @property
    def EndLimit(self) -> Expression: ...
    @EndLimit.setter
    def EndLimit(self, value: Expression) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...
    @property
    def MemberPathEnd(self) -> Features.StructureDesign.MemberPathBuilder: ...
    @MemberPathEnd.setter
    def MemberPathEnd(self, value: Features.StructureDesign.MemberPathBuilder) -> None: ...
    @property
    def MemberPathStart(self) -> Features.StructureDesign.MemberPathBuilder: ...
    @MemberPathStart.setter
    def MemberPathStart(self, value: Features.StructureDesign.MemberPathBuilder) -> None: ...
    @property
    def PathGeometry(self) -> Section: ...
    @PathGeometry.setter
    def PathGeometry(self, value: Section) -> None: ...
    @property
    def RotateAngle(self) -> Expression: ...
    @RotateAngle.setter
    def RotateAngle(self, value: Expression) -> None: ...
    @property
    def StartLimit(self) -> Expression: ...
    @StartLimit.setter
    def StartLimit(self, value: Expression) -> None: ...
    @property
    def StockData(self) -> Features.StructureDesign.FeatureSpreadsheetBuilder: ...
    @StockData.setter
    def StockData(self, value: Features.StructureDesign.FeatureSpreadsheetBuilder) -> None: ...
    @property
    def XOffset(self) -> Expression: ...
    @XOffset.setter
    def XOffset(self, value: Expression) -> None: ...
    @property
    def YOffset(self) -> Expression: ...
    @YOffset.setter
    def YOffset(self, value: Expression) -> None: ...


    class EndCornerTypes(enum.Enum):
        None_= 0
        Miter= 1
        Butt= 2
        Cope= 3
        MatchedCope= 4
        SmartExtend= 5
    

class Member(Features.BodyFeature):
    def __init__(self) -> None: ...


class LibraryBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Catalog(self) -> str: ...
    @Catalog.setter
    def Catalog(self, value: str) -> None: ...


class GussetBuilder(Features.FeatureBuilder):
    def __init__(self) -> None: ...
    @property
    def AlignmentType(self) -> Features.StructureDesign.GussetBuilder.AlignmentTypes: ...
    @AlignmentType.setter
    def AlignmentType(self, value: Features.StructureDesign.GussetBuilder.AlignmentTypes) -> None: ...
    @property
    def AngularTolerance(self) -> float: ...
    @AngularTolerance.setter
    def AngularTolerance(self, value: float) -> None: ...
    @property
    def AttachmentOffset(self) -> Expression: ...
    @AttachmentOffset.setter
    def AttachmentOffset(self, value: Expression) -> None: ...
    @property
    def AttachmentPointNormal(self) -> Vector3d: ...
    @AttachmentPointNormal.setter
    def AttachmentPointNormal(self, value: Vector3d) -> None: ...
    @property
    def DistanceTolerance(self) -> float: ...
    @DistanceTolerance.setter
    def DistanceTolerance(self, value: float) -> None: ...
    @property
    def FirstFaceSelect(self) -> ScCollector: ...
    @FirstFaceSelect.setter
    def FirstFaceSelect(self, value: ScCollector) -> None: ...
    @property
    def FlangeData(self) -> Features.StructureDesign.FeatureSpreadsheetBuilder: ...
    @FlangeData.setter
    def FlangeData(self, value: Features.StructureDesign.FeatureSpreadsheetBuilder) -> None: ...
    @property
    def GussetName(self) -> str: ...
    @GussetName.setter
    def GussetName(self, value: str) -> None: ...
    @property
    def OffsetDistance(self) -> Expression: ...
    @OffsetDistance.setter
    def OffsetDistance(self, value: Expression) -> None: ...
    @property
    def OrientVector(self) -> Direction: ...
    @OrientVector.setter
    def OrientVector(self, value: Direction) -> None: ...
    @property
    def PickPointOnAttachment(self) -> Point3d: ...
    @PickPointOnAttachment.setter
    def PickPointOnAttachment(self, value: Point3d) -> None: ...
    @property
    def PickPointOnReinforcement(self) -> Point3d: ...
    @PickPointOnReinforcement.setter
    def PickPointOnReinforcement(self, value: Point3d) -> None: ...
    @property
    def PositionType(self) -> Features.StructureDesign.GussetBuilder.PositionTypes: ...
    @PositionType.setter
    def PositionType(self, value: Features.StructureDesign.GussetBuilder.PositionTypes) -> None: ...
    @property
    def ReinforcementOffset(self) -> Expression: ...
    @ReinforcementOffset.setter
    def ReinforcementOffset(self, value: Expression) -> None: ...
    @property
    def ReinforcementPointNormal(self) -> Vector3d: ...
    @ReinforcementPointNormal.setter
    def ReinforcementPointNormal(self, value: Vector3d) -> None: ...
    @property
    def ReverseAlignEdge(self) -> bool: ...
    @ReverseAlignEdge.setter
    def ReverseAlignEdge(self, value: bool) -> None: ...
    @property
    def ReverseAttachmentOffsetFlange(self) -> bool: ...
    @ReverseAttachmentOffsetFlange.setter
    def ReverseAttachmentOffsetFlange(self, value: bool) -> None: ...
    @property
    def ReverseFirstFace(self) -> bool: ...
    @ReverseFirstFace.setter
    def ReverseFirstFace(self, value: bool) -> None: ...
    @property
    def ReverseFlange(self) -> bool: ...
    @ReverseFlange.setter
    def ReverseFlange(self, value: bool) -> None: ...
    @property
    def ReverseReinforcementOffsetFlange(self) -> bool: ...
    @ReverseReinforcementOffsetFlange.setter
    def ReverseReinforcementOffsetFlange(self, value: bool) -> None: ...
    @property
    def ReverseSecondFace(self) -> bool: ...
    @ReverseSecondFace.setter
    def ReverseSecondFace(self, value: bool) -> None: ...
    @property
    def SecondFaceSelect(self) -> ScCollector: ...
    @SecondFaceSelect.setter
    def SecondFaceSelect(self, value: ScCollector) -> None: ...
    @property
    def ThicknessType(self) -> Features.StructureDesign.GussetBuilder.ThicknessTypes: ...
    @ThicknessType.setter
    def ThicknessType(self, value: Features.StructureDesign.GussetBuilder.ThicknessTypes) -> None: ...


    class ThicknessTypes(enum.Enum):
        BothSides= 0
        InnerSide= 1
        OuterSide= 2
    

    class PositionTypes(enum.Enum):
        Offset= 0
        Center= 1
        AlignToEdge= 2
    

    class AlignmentTypes(enum.Enum):
        GussetPlate= 0
        LappedPlate= 1
    

class Gusset(Features.BodyFeature):
    def __init__(self) -> None: ...


class GrabTabBuilder(Features.FeatureBuilder):
    def __init__(self) -> None: ...
    @property
    def AnchorPoint(self) -> Features.StructureDesign.GrabTabBuilder.AnchorPoints: ...
    @AnchorPoint.setter
    def AnchorPoint(self, value: Features.StructureDesign.GrabTabBuilder.AnchorPoints) -> None: ...
    @property
    def Attachment(self) -> ScCollector: ...
    @Attachment.setter
    def Attachment(self, value: ScCollector) -> None: ...
    @property
    def GrabTabName(self) -> str: ...
    @GrabTabName.setter
    def GrabTabName(self, value: str) -> None: ...
    @property
    def OrientVector(self) -> Direction: ...
    @OrientVector.setter
    def OrientVector(self, value: Direction) -> None: ...
    @property
    def PlaceDirection(self) -> Features.StructureDesign.GrabTabBuilder.PlaceDirections: ...
    @PlaceDirection.setter
    def PlaceDirection(self, value: Features.StructureDesign.GrabTabBuilder.PlaceDirections) -> None: ...
    @property
    def Reference1(self) -> SelectNXObject: ...
    @Reference1.setter
    def Reference1(self, value: SelectNXObject) -> None: ...
    @property
    def Reference1Offset(self) -> Expression: ...
    @Reference1Offset.setter
    def Reference1Offset(self, value: Expression) -> None: ...
    @property
    def Reference1ReverseFlange(self) -> bool: ...
    @Reference1ReverseFlange.setter
    def Reference1ReverseFlange(self, value: bool) -> None: ...
    @property
    def Reference2(self) -> SelectNXObject: ...
    @Reference2.setter
    def Reference2(self, value: SelectNXObject) -> None: ...
    @property
    def Reference2Offset(self) -> Expression: ...
    @Reference2Offset.setter
    def Reference2Offset(self, value: Expression) -> None: ...
    @property
    def Reference2ReverseFlange(self) -> bool: ...
    @Reference2ReverseFlange.setter
    def Reference2ReverseFlange(self, value: bool) -> None: ...
    @property
    def RotateAngle(self) -> Expression: ...
    @RotateAngle.setter
    def RotateAngle(self, value: Expression) -> None: ...
    @property
    def StockData(self) -> Features.StructureDesign.FeatureSpreadsheetBuilder: ...
    @StockData.setter
    def StockData(self, value: Features.StructureDesign.FeatureSpreadsheetBuilder) -> None: ...


    class PlaceDirections(enum.Enum):
        Horizontal= 0
        Vertical= 1
    

    class AnchorPoints(enum.Enum):
        Left= 0
        Center= 1
        Right= 2
    

class GrabTab(Features.BodyFeature):
    def __init__(self) -> None: ...


class FeatureSpreadsheetBuilder(Features.ShipDesign.SteelFeatureSpreadsheetBuilder):
    def __init__(self) -> None: ...


class FeatureParmsBuilder(Features.FeatureBuilder):
    def __init__(self) -> None: ...
    @property
    def AngularTolerance(self) -> float: ...
    @AngularTolerance.setter
    def AngularTolerance(self, value: float) -> None: ...
    @property
    def DistanceTolerance(self) -> float: ...
    @DistanceTolerance.setter
    def DistanceTolerance(self, value: float) -> None: ...


class EndcapBuilder(Features.FeatureBuilder):
    def __init__(self) -> None: ...
    @property
    def Chamfer(self) -> bool: ...
    @Chamfer.setter
    def Chamfer(self, value: bool) -> None: ...
    @property
    def ChamferLength(self) -> Expression: ...
    @ChamferLength.setter
    def ChamferLength(self, value: Expression) -> None: ...
    @property
    def DistanceTolerance(self) -> float: ...
    @DistanceTolerance.setter
    def DistanceTolerance(self, value: float) -> None: ...
    @property
    def EndCapName(self) -> str: ...
    @EndCapName.setter
    def EndCapName(self, value: str) -> None: ...
    @property
    def EnumCornerTreatmentType(self) -> Features.StructureDesign.EndcapBuilder.CornerTreatmentTypes: ...
    @EnumCornerTreatmentType.setter
    def EnumCornerTreatmentType(self, value: Features.StructureDesign.EndcapBuilder.CornerTreatmentTypes) -> None: ...
    @property
    def Member(self) -> ScCollector: ...
    @Member.setter
    def Member(self, value: ScCollector) -> None: ...
    @property
    def Offset(self) -> Expression: ...
    @Offset.setter
    def Offset(self, value: Expression) -> None: ...
    @property
    def OffsetRatio(self) -> float: ...
    @OffsetRatio.setter
    def OffsetRatio(self, value: float) -> None: ...
    @property
    def PlacementType(self) -> Features.StructureDesign.EndcapBuilder.PlacementTypes: ...
    @PlacementType.setter
    def PlacementType(self, value: Features.StructureDesign.EndcapBuilder.PlacementTypes) -> None: ...
    @property
    def PreserveOverallLength(self) -> bool: ...
    @PreserveOverallLength.setter
    def PreserveOverallLength(self, value: bool) -> None: ...
    @property
    def Thickness(self) -> Expression: ...
    @Thickness.setter
    def Thickness(self, value: Expression) -> None: ...


    class PlacementTypes(enum.Enum):
        Inside= 0
        Outside= 1
    

    class CornerTreatmentTypes(enum.Enum):
        None_= 0
        Chamfer= 1
        Fillet= 2
    

class Endcap(Features.BodyFeature):
    def __init__(self) -> None: ...


class EditStructureBuilder(Builder):
    def __init__(self) -> None: ...
    def UpdateReferenceInfomation(self, selStructure: NXObject) -> None: ...
    @property
    def Catalog(self) -> str: ...
    @Catalog.setter
    def Catalog(self, value: str) -> None: ...
    @property
    def Reference(self) -> SelectTaggedObjectList: ...
    @Reference.setter
    def Reference(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def ReferenceOrientation(self) -> Direction: ...
    @ReferenceOrientation.setter
    def ReferenceOrientation(self, value: Direction) -> None: ...
    @property
    def Structure(self) -> SelectTaggedObject: ...
    @Structure.setter
    def Structure(self, value: SelectTaggedObject) -> None: ...


class EditStockBuilder(Features.FeatureBuilder):
    def __init__(self) -> None: ...
    def FlipX(self) -> None: ...
    def FlipY(self) -> None: ...
    def UpdateStockInformation(self, member: NXObject) -> None: ...
    @property
    def AlternateOrigin(self) -> int: ...
    @AlternateOrigin.setter
    def AlternateOrigin(self, value: int) -> None: ...
    @property
    def EnableTransform(self) -> bool: ...
    @EnableTransform.setter
    def EnableTransform(self, value: bool) -> None: ...
    @property
    def EndLimit(self) -> Expression: ...
    @EndLimit.setter
    def EndLimit(self, value: Expression) -> None: ...
    @property
    def Member(self) -> SelectTaggedObjectList: ...
    @Member.setter
    def Member(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def RotateAngle(self) -> Expression: ...
    @RotateAngle.setter
    def RotateAngle(self, value: Expression) -> None: ...
    @property
    def StartLimit(self) -> Expression: ...
    @StartLimit.setter
    def StartLimit(self, value: Expression) -> None: ...
    @property
    def StockData(self) -> Features.StructureDesign.FeatureSpreadsheetBuilder: ...
    @StockData.setter
    def StockData(self, value: Features.StructureDesign.FeatureSpreadsheetBuilder) -> None: ...
    @property
    def XOffset(self) -> Expression: ...
    @XOffset.setter
    def XOffset(self, value: Expression) -> None: ...
    @property
    def YOffset(self) -> Expression: ...
    @YOffset.setter
    def YOffset(self, value: Expression) -> None: ...


class EditCornerBuilder(Features.FeatureBuilder):
    def __init__(self) -> None: ...
    def CreateCorners(self, body: Body, endPoint: Point3d, corners: typing.List[Features.StructureDesign.CornerNodeBuilder]) -> None: ...
    def GetCorners(self, corners: typing.List[Features.StructureDesign.CornerNodeBuilder]) -> None: ...
    def RemoveCorners(self, corners: typing.List[Features.StructureDesign.CornerNodeBuilder]) -> None: ...
    def SetCornerObject(self, corner: Features.StructureDesign.Corner) -> None: ...
    def SetEndCorner(self, iNodeIndex: int, endCorner: Features.StructureDesign.MemberBuilder.EndCornerTypes) -> None: ...
    def SetMemberIndex(self, iNodeIndex: int, iMemberIndex: int) -> None: ...
    def UpdateStockData(self, bOnlyUpdateSize: bool) -> None: ...
    def UpdateCopeMemberStockData(self, iMemberIndex: int, bOnlyUpdateSize: bool) -> None: ...
    def UpdateAllCopeStockData(self) -> None: ...
    def SetInitialStockData(self, bInitial: bool) -> None: ...
    def GetStockDataByMember(self, iMemberIndex: int) -> Features.StructureDesign.FeatureSpreadsheetBuilder: ...
    def SetCurrentStockData(self, stockData: Features.StructureDesign.FeatureSpreadsheetBuilder) -> None: ...
    def ResetStockData(self) -> None: ...
    def SetCutback(self, iMemberIndex: int, usCutback: str) -> None: ...
    def SetCopeMemberIndex(self, iMemberIndex: int, iRefCopeMemberIndex: int) -> None: ...
    def SetParamtersChanged(self, bChanged: bool) -> None: ...
    def ClearReferenceMemberFaceInformation(self, iMemberIndex: int) -> None: ...
    def ClearReferencedMemberInformation(self, iMemberIndex: int) -> None: ...
    def AddReferenceMemberFaceInformation(self, iMemberIndex: int, iRefMemberIndex: int, facePoint: Point3d, faceNormal: Vector3d) -> None: ...
    def SetCopeMemberIndexArray(self, iMemberIndex: int, refCopeMemberIndexArray: int) -> None: ...
    @property
    def Corner(self) -> Features.StructureDesign.SelectCorner: ...
    @Corner.setter
    def Corner(self, value: Features.StructureDesign.SelectCorner) -> None: ...
    @property
    def StockData(self) -> Features.StructureDesign.FeatureSpreadsheetBuilder: ...
    @StockData.setter
    def StockData(self, value: Features.StructureDesign.FeatureSpreadsheetBuilder) -> None: ...


class CreateStructureBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Catalog(self) -> str: ...
    @Catalog.setter
    def Catalog(self, value: str) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...
    @property
    def Reference(self) -> SelectTaggedObjectList: ...
    @Reference.setter
    def Reference(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def ReferenceOrientation(self) -> Direction: ...
    @ReferenceOrientation.setter
    def ReferenceOrientation(self, value: Direction) -> None: ...
    @property
    def StructreRootNode(self) -> ShipDesign.NavigatorNode: ...
    @StructreRootNode.setter
    def StructreRootNode(self, value: ShipDesign.NavigatorNode) -> None: ...
    @property
    def UpOrientation(self) -> Direction: ...
    @UpOrientation.setter
    def UpOrientation(self, value: Direction) -> None: ...


class CornerNodeBuilder(NXObject):
    def __init__(self) -> None: ...
    @property
    def EndCorner(self) -> Features.StructureDesign.MemberBuilder.EndCornerTypes: ...
    @EndCorner.setter
    def EndCorner(self, value: Features.StructureDesign.MemberBuilder.EndCornerTypes) -> None: ...


class Corner(DisplayableObject):
    def __init__(self) -> None: ...


class ContainerBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def SelectStructure(self) -> Part: ...
    @SelectStructure.setter
    def SelectStructure(self, value: Part) -> None: ...


class ConsolidateBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Container(self) -> Part: ...
    @Container.setter
    def Container(self, value: Part) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...
    @property
    def Structures(self) -> SelectTaggedObjectList: ...
    @Structures.setter
    def Structures(self, value: SelectTaggedObjectList) -> None: ...


class BoltedConnectionBuilder(Features.StructureDesign.FeatureParmsBuilder):
    def __init__(self) -> None: ...
    def UpdateStockSectionTypes(self, sectionModified: bool) -> None: ...
    @property
    def AddFasteners(self) -> bool: ...
    @AddFasteners.setter
    def AddFasteners(self, value: bool) -> None: ...
    @property
    def BeamColumnConnectionSubType(self) -> Features.StructureDesign.BoltedConnectionBuilder.BeamColumnConnectionSubTypes: ...
    @BeamColumnConnectionSubType.setter
    def BeamColumnConnectionSubType(self, value: Features.StructureDesign.BoltedConnectionBuilder.BeamColumnConnectionSubTypes) -> None: ...
    @property
    def BodyOne(self) -> ScCollector: ...
    @BodyOne.setter
    def BodyOne(self, value: ScCollector) -> None: ...
    @property
    def BodyTwo(self) -> ScCollector: ...
    @BodyTwo.setter
    def BodyTwo(self, value: ScCollector) -> None: ...
    @property
    def BoltedConnectionName(self) -> str: ...
    @BoltedConnectionName.setter
    def BoltedConnectionName(self, value: str) -> None: ...
    @property
    def ConfigurationName(self) -> str: ...
    @ConfigurationName.setter
    def ConfigurationName(self, value: str) -> None: ...
    @property
    def ConnectionType(self) -> Features.StructureDesign.BoltedConnectionBuilder.ConnectionTypes: ...
    @ConnectionType.setter
    def ConnectionType(self, value: Features.StructureDesign.BoltedConnectionBuilder.ConnectionTypes) -> None: ...
    @property
    def FaceOne(self) -> ScCollector: ...
    @FaceOne.setter
    def FaceOne(self, value: ScCollector) -> None: ...
    @property
    def FaceTwo(self) -> ScCollector: ...
    @FaceTwo.setter
    def FaceTwo(self, value: ScCollector) -> None: ...
    @property
    def SpliceConnectionSubType(self) -> Features.StructureDesign.BoltedConnectionBuilder.SpliceConnectionSubTypes: ...
    @SpliceConnectionSubType.setter
    def SpliceConnectionSubType(self, value: Features.StructureDesign.BoltedConnectionBuilder.SpliceConnectionSubTypes) -> None: ...
    @property
    def StockData(self) -> Features.StructureDesign.FeatureSpreadsheetBuilder: ...
    @StockData.setter
    def StockData(self, value: Features.StructureDesign.FeatureSpreadsheetBuilder) -> None: ...


    class SpliceConnectionSubTypes(enum.Enum):
        End= 0
        Flange= 1
        Web= 2
    

    class ConnectionTypes(enum.Enum):
        Splice= 0
        BeamColumn= 1
    

    class BeamColumnConnectionSubTypes(enum.Enum):
        End= 0
        LPlate= 1
        FlatPlate= 2
    

class BoltedConnection(Features.BodyFeature):
    def __init__(self) -> None: ...


class BeamPreparationBuilder(Features.StructureDesign.FeatureParmsBuilder):
    def __init__(self) -> None: ...
    @property
    def ComponentName(self) -> str: ...
    @ComponentName.setter
    def ComponentName(self, value: str) -> None: ...
    @property
    def NonStructureBodies(self) -> SelectDisplayableObjectList: ...
    @NonStructureBodies.setter
    def NonStructureBodies(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def ShowBodies(self) -> bool: ...
    @ShowBodies.setter
    def ShowBodies(self, value: bool) -> None: ...
    @property
    def StructureComponents(self) -> SelectDisplayableObjectList: ...
    @StructureComponents.setter
    def StructureComponents(self, value: SelectDisplayableObjectList) -> None: ...


class BeamPreparation(Features.BodyFeature):
    def __init__(self) -> None: ...


class BeamCurveBuilder(Features.StructureDesign.FeatureParmsBuilder):
    def __init__(self) -> None: ...


class BeamCurve(Features.BodyFeature):
    def __init__(self) -> None: ...


class AssignWeldingAttributesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def SelectionButtWeldingEdges(self) -> SelectEdgeList: ...
    @SelectionButtWeldingEdges.setter
    def SelectionButtWeldingEdges(self, value: SelectEdgeList) -> None: ...
    @property
    def SelectionCorners(self) -> Features.StructureDesign.SelectCornerList: ...
    @SelectionCorners.setter
    def SelectionCorners(self, value: Features.StructureDesign.SelectCornerList) -> None: ...
    @property
    def SelectionEdgesToBeClear(self) -> SelectEdgeList: ...
    @SelectionEdgesToBeClear.setter
    def SelectionEdgesToBeClear(self, value: SelectEdgeList) -> None: ...
    @property
    def SelectionFilletWeldingEdges(self) -> SelectEdgeList: ...
    @SelectionFilletWeldingEdges.setter
    def SelectionFilletWeldingEdges(self, value: SelectEdgeList) -> None: ...


