from ....NXOpen import *
from ...Routing import *

import typing
import enum

class WireDevice(Routing.Electrical.ElectricalStockDevice):
    def __init__(self) -> None: ...


class SystemDeviceCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Routing.Electrical.SystemDevice]: ...
    @typing.overload
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def CreateSystemDevice(self) -> Routing.Electrical.SystemDevice: ...
    @typing.overload
    def CreateSystemDevice(self, systemName: str) -> Routing.Electrical.SystemDevice: ...
    def GetSystemSingleDevices(self) -> typing.List[Routing.Electrical.SystemDevice]: ...
    def Tag(self) -> Tag: ...



class SystemDevice(Routing.Electrical.HarnessDevice):
    def __init__(self) -> None: ...
    def GetSystemDefinition(self) -> Routing.Electrical.SystemDefinition: ...


class SystemDefinition(Routing.Electrical.HarnessDefinition):
    def __init__(self) -> None: ...


class SplicePositionBuilder(Builder):
    def __init__(self) -> None: ...
    def SetEndRouteNodesOfRouteSection(self, startRouteNode: Routing.ControlPoint, endRouteNode: Routing.ControlPoint) -> None: ...
    def SetDistanceFromAnchorNode(self, distanceForSplicePoint: float) -> None: ...
    def SetTotalCurveLengthOfRouteSection(self, totalLengthOfRouteSection: float) -> None: ...
    @property
    def AdditionalLength(self) -> float: ...
    @AdditionalLength.setter
    def AdditionalLength(self, value: float) -> None: ...
    @property
    def DistanceForSplicePoint(self) -> Expression: ...
    @DistanceForSplicePoint.setter
    def DistanceForSplicePoint(self, value: Expression) -> None: ...
    @property
    def PointOnPath(self) -> Point: ...
    @PointOnPath.setter
    def PointOnPath(self, value: Point) -> None: ...
    @property
    def SpliceName(self) -> str: ...
    @SpliceName.setter
    def SpliceName(self, value: str) -> None: ...
    @property
    def SwitchRouteNode(self) -> bool: ...
    @SwitchRouteNode.setter
    def SwitchRouteNode(self, value: bool) -> None: ...


class SortConnectionsPluginData(TaggedObject):
    def __init__(self) -> None: ...
    def GetStockDevicesToSort(self, stockDevices: typing.List[Routing.Electrical.ElectricalStockDevice]) -> None: ...
    def SetSortedStockDevices(self, stockDevices: typing.List[Routing.Electrical.ElectricalStockDevice]) -> None: ...


class ShieldStockDefinition(Routing.Electrical.CableStockDefinition):
    def __init__(self) -> None: ...


class ShieldDevice(Routing.Electrical.CableDevice):
    def __init__(self) -> None: ...


class ShieldDefinition(Routing.Electrical.CableDefinition):
    def __init__(self) -> None: ...


class PathConnectionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Routing.Electrical.PathConnection]: ...
    @typing.overload
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreatePathConnection(self) -> Routing.Electrical.PathConnection: ...
    def Tag(self) -> Tag: ...



class PathConnection(Routing.Electrical.Connection):
    def __init__(self) -> None: ...


class PathArrangementBuilder(Builder):
    def __init__(self) -> None: ...
    def ClearHarnessData(self) -> None: ...
    def DeletePathArrangement(self) -> None: ...
    def EstablishPathArrangement(self) -> None: ...
    def SetPathArrangementOrigin(self, point: Point3d) -> None: ...
    def InitializeBuilderFromArrangedPort(self, port: Routing.Port) -> None: ...
    @property
    def HarnessPartOccurrence(self) -> Assemblies.Component: ...
    @HarnessPartOccurrence.setter
    def HarnessPartOccurrence(self, value: Assemblies.Component) -> None: ...
    @property
    def PrototypePort(self) -> Routing.Port: ...
    @PrototypePort.setter
    def PrototypePort(self, value: Routing.Port) -> None: ...
    @property
    def PrototypePortPartOccurrence(self) -> Assemblies.Component: ...
    @PrototypePortPartOccurrence.setter
    def PrototypePortPartOccurrence(self, value: Assemblies.Component) -> None: ...
    @property
    def ReferencePort(self) -> TaggedObject: ...
    @ReferencePort.setter
    def ReferencePort(self, value: TaggedObject) -> None: ...


class NonPathConnectionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Routing.Electrical.NonPathConnection]: ...
    @typing.overload
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateNonPathConnection(self) -> Routing.Electrical.NonPathConnection: ...
    def Tag(self) -> Tag: ...



class NonPathConnection(Routing.Electrical.Connection):
    def __init__(self) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class JumperConnectionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Routing.Electrical.JumperConnection]: ...
    @typing.overload
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateJumperConnection(self) -> Routing.Electrical.JumperConnection: ...
    def Tag(self) -> Tag: ...



class JumperConnection(Routing.Electrical.PathConnection):
    def __init__(self) -> None: ...


class HarnessDeviceCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Routing.Electrical.HarnessDevice]: ...
    @typing.overload
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def CreateHarnessDevice(self) -> Routing.Electrical.HarnessDevice: ...
    @typing.overload
    def CreateHarnessDevice(self, harnessName: str) -> Routing.Electrical.HarnessDevice: ...
    def GetHarnessSingleDevices(self) -> typing.List[Routing.Electrical.HarnessDevice]: ...
    def Tag(self) -> Tag: ...



class HarnessDevice(Routing.SingleDevice):
    def __init__(self) -> None: ...
    def GetHarnessDefinition(self) -> Routing.Electrical.HarnessDefinition: ...


class HarnessDefinition(Routing.AssemblyDefinition):
    def __init__(self) -> None: ...
    def GetChildConnections(self) -> typing.List[Routing.Electrical.Connection]: ...


class ElectricalStockDeviceCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Routing.Electrical.ElectricalStockDevice]: ...
    @typing.overload
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def AutoRouteConnections(self, routeLevel: Routing.Electrical.ElectricalStockDevice.RouteLevel, routeSel: Routing.Electrical.ElectricalStockDevice.AutoRouteSel, stockDevices: typing.List[Routing.Electrical.ElectricalStockDevice], errorList: ErrorList) -> int: ...
    def AssignStock(self, stockDevices: typing.List[Routing.Electrical.ElectricalStockDevice], routeType: Routing.Electrical.ElectricalStockDevice.RouteTypes) -> None: ...
    def RemoveStock(self, stockDevices: typing.List[Routing.Electrical.ElectricalStockDevice]) -> typing.List[Routing.Electrical.ElectricalStockDevice]: ...
    def AutoRouteAll(self, routeLevel: Routing.Electrical.ElectricalStockDevice.RouteLevel, routeSel: Routing.Electrical.ElectricalStockDevice.AutoRouteSel, errorList: ErrorList) -> int: ...
    def Unroute(self, stockDevices: typing.List[Routing.Electrical.ElectricalStockDevice]) -> typing.List[Routing.Electrical.ElectricalStockDevice]: ...
    def UnrouteAll(self) -> typing.List[Routing.Electrical.ElectricalStockDevice]: ...
    def GetElectricalStockDevicesInPart(self) -> typing.List[Routing.Electrical.ElectricalStockDevice]: ...
    def Tag(self) -> Tag: ...



class ElectricalStockDevice(Routing.StockDevice):
    def __init__(self) -> None: ...
    def CalculateCutLength(self) -> float: ...
    def FindNearestHarnessDefinition(self) -> Routing.Electrical.HarnessDefinition: ...
    def FindTopmostCableDefinition(self) -> Routing.Electrical.CableDefinition: ...
    def FindFromConnector(self) -> Routing.Electrical.ConnectorDevice: ...
    def FindToConnector(self) -> Routing.Electrical.ConnectorDevice: ...
    def FindNearestHarnessDevice(self) -> Routing.Electrical.HarnessDevice: ...
    def FindImplementedConnection(self) -> Routing.Electrical.Connection: ...
    def HasIntermediateComponents(self) -> bool: ...
    def GetIntermediateComponents(self) -> typing.List[Routing.Electrical.ConnectorDevice]: ...
    def GetIntermediateTerminals(self) -> typing.List[Routing.LogicalTerminal]: ...
    def ManuallyRoute(self, routeLevel: Routing.Electrical.ElectricalStockDevice.RouteLevel, segments: typing.List[Routing.ISegment]) -> None: ...
    def ChangeHarness(self, harnessDevice: Routing.Electrical.HarnessDevice) -> None: ...
    @property
    def ColorName(self) -> str: ...
    @ColorName.setter
    def ColorName(self, value: str) -> None: ...
    @property
    def CutLength(self) -> float: ...
    @CutLength.setter
    def CutLength(self, value: float) -> None: ...
    @property
    def NxColorValue(self) -> int: ...
    @NxColorValue.setter
    def NxColorValue(self, value: int) -> None: ...


    class RouteTypes(enum.Enum):
        DefaultRoute= -1
        AutoRoute= 0
        ManualRoute= 1
    

    class RouteLevel(enum.Enum):
        Pin= 0
        Comp= 1
        Mixed= 2
        Partial= 3
    

    class AutoRouteSel(enum.Enum):
        BundleDiameter= 0
        LeastBundles= 1
        DesignRules= 2
        LeastSegments= 3
        ShortestLength= 4
    

class ElectricalStockDefinition(Routing.StockDefinition):
    def __init__(self) -> None: ...
    @property
    def CrossSectionType(self) -> Routing.Electrical.ElectricalStockDefinition.SectionType: ...
    @CrossSectionType.setter
    def CrossSectionType(self, value: Routing.Electrical.ElectricalStockDefinition.SectionType) -> None: ...
    @property
    def Gauge(self) -> float: ...
    @Gauge.setter
    def Gauge(self, value: float) -> None: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> None: ...
    @property
    def LinearDensity(self) -> float: ...
    @LinearDensity.setter
    def LinearDensity(self, value: float) -> None: ...
    @property
    def MinBendRadius(self) -> float: ...
    @MinBendRadius.setter
    def MinBendRadius(self, value: float) -> None: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> None: ...
    @property
    def WireType(self) -> str: ...
    @WireType.setter
    def WireType(self, value: str) -> None: ...


    class SectionType(enum.Enum):
        Circular= 0
        Rectangular= 1
    

class ElectricalPartDefinitionShadow(Routing.PartDefinitionShadow):
    def __init__(self) -> None: ...


class ElectricalNavigatorFilterCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Routing.Electrical.ElectricalNavigatorFilter]: ...
    @typing.overload
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateFilter(self, name: str, clause: str) -> Routing.Electrical.ElectricalNavigatorFilter: ...
    def GetDisplayFilter(self, type: Routing.Electrical.ElectricalFormat.Type) -> Routing.Electrical.ElectricalNavigatorFilter: ...
    def SetDisplayFilter(self, type: Routing.Electrical.ElectricalFormat.Type, filter: Routing.Electrical.ElectricalNavigatorFilter) -> None: ...
    def Tag(self) -> Tag: ...



class ElectricalNavigatorFilter(NavigatorFilter):
    def __init__(self) -> None: ...


class ElectricalFormatCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Routing.Electrical.ElectricalFormat]: ...
    @typing.overload
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateFormat(self, name: str, type: Routing.Electrical.ElectricalFormat.Type) -> Routing.Electrical.ElectricalFormat: ...
    def GetDisplayFormat(self, type: Routing.Electrical.ElectricalFormat.Type) -> Routing.Electrical.ElectricalFormat: ...
    def SetDisplayFormat(self, type: Routing.Electrical.ElectricalFormat.Type, format: Routing.Electrical.ElectricalFormat) -> None: ...
    def Tag(self) -> Tag: ...



class ElectricalFormat(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def FormatType(self) -> Routing.Electrical.ElectricalFormat.Type: ...
    @FormatType.setter
    def FormatType(self, value: Routing.Electrical.ElectricalFormat.Type) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...


    class Type(enum.Enum):
        Connections= 0
        Components= 1
    

class ElectricalDeviceRelationshipCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Routing.Electrical.ElectricalDeviceRelationship]: ...
    @typing.overload
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateElectricalDeviceRelationship(self) -> Routing.Electrical.ElectricalDeviceRelationship: ...
    def Tag(self) -> Tag: ...



class ElectricalDeviceRelationship(Routing.DeviceRelationship):
    def __init__(self) -> None: ...


class ConnectorDeviceCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Routing.Electrical.ConnectorDevice]: ...
    @typing.overload
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def CreateConnectorDevice(self, connectorType: Routing.Electrical.ConnectorDevice.ComponentType, componentName: str) -> Routing.Electrical.ConnectorDevice: ...
    @typing.overload
    def CreateConnectorDevice(self, harnessDevice: Routing.Electrical.HarnessDevice, equipmentName: str, connectorName: str, connectorType: Routing.Electrical.ConnectorDevice.ComponentType) -> Routing.Electrical.ConnectorDevice: ...
    def GetConnectorSingleDevices(self) -> typing.List[Routing.Electrical.ConnectorDevice]: ...
    def GetEquipmentSingleDevices(self) -> typing.List[Routing.Electrical.ConnectorDevice]: ...
    def AutoAssignConnectors(self, connectors: typing.List[Routing.Electrical.ConnectorDevice]) -> None: ...
    def GetSpliceConnectorDevice(self, spliceName: str) -> Routing.Electrical.ConnectorDevice: ...
    def Tag(self) -> Tag: ...



class ConnectorDevice(Routing.SingleDevice):
    def __init__(self) -> None: ...
    def GetPartDefinition(self) -> Routing.Electrical.ElectricalPartDefinitionShadow: ...
    def SetPartDefinition(self, elecPartDefinitionShadow: Routing.Electrical.ElectricalPartDefinitionShadow) -> None: ...
    def GetTerminals(self) -> typing.List[Routing.LogicalTerminal]: ...
    def RemoveTerminal(self, routeTerminalToRemove: Routing.LogicalTerminal) -> bool: ...
    def GetAssignMethod(self) -> Routing.Electrical.ConnectorDevice.Assign: ...
    def FindNearestHarnessDevice(self) -> Routing.Electrical.HarnessDevice: ...
    def FindNearestCableDevice(self) -> Routing.Electrical.CableDevice: ...
    def IsNxDevice(self, elecHarnessDevice: Routing.Electrical.HarnessDevice) -> bool: ...
    def IsNxConnector(self, elecHarnessDevice: Routing.Electrical.HarnessDevice) -> bool: ...
    def IsUsedInRoutedConnection(self, elecHarnessDevice: Routing.Electrical.HarnessDevice) -> bool: ...
    def UnassignConnector(self) -> None: ...
    def AutomaticallyAssignConnector(self, elecConnectorPartOccurrence: Assemblies.Component) -> None: ...
    def ManuallyAssignConnector(self, elecConnectorPartOccurrence: Assemblies.Component) -> None: ...
    def ManuallyAssignConnectorGroup(self, elecConnectorGroup: Group) -> None: ...
    def FindRoutedStockDevices(self) -> typing.List[Routing.Electrical.ElectricalStockDevice]: ...
    def IsAssigned(self) -> bool: ...
    def FindStockDevices(self) -> typing.List[Routing.Electrical.ElectricalStockDevice]: ...
    def FindConnections(self) -> typing.List[Routing.Electrical.Connection]: ...
    def GetTerminal(self, terminalName: str, createTerminal: bool) -> Routing.LogicalTerminal: ...
    def FindMatchingParts(self) -> typing.List[Routing.CharacteristicList]: ...
    def FindPlacer(self, placerPos: float) -> Routing.Port: ...
    def FindPlacementPort(self, portPosition: Point3d) -> Routing.Port: ...
    def PlaceConnectorOnPort(self, match: Routing.CharacteristicList, placer: Routing.Port) -> Assemblies.Component: ...
    def ProxyAssignConnector(self, proxy: Routing.Port) -> None: ...
    @property
    def ComponentName(self) -> str: ...
    @ComponentName.setter
    def ComponentName(self, value: str) -> None: ...
    @property
    def ConnectorType(self) -> Routing.Electrical.ConnectorDevice.ComponentType: ...
    @ConnectorType.setter
    def ConnectorType(self, value: Routing.Electrical.ConnectorDevice.ComponentType) -> None: ...


    class ComponentType(enum.Enum):
        None_= 0
        Connector= 1
        Splice= 2
        Device= 3
        Other= 4
    

    class Assign(enum.Enum):
        None_= 0
        Auto= 1
        Manual= 2
    

class ConnectionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Routing.Electrical.Connection]: ...
    @typing.overload
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def GetConnections(self) -> typing.List[Routing.Electrical.Connection]: ...
    def Tag(self) -> Tag: ...



class Connection(Routing.LogicalConnection):
    def __init__(self) -> None: ...
    def GetIntermediateTerminals(self) -> typing.List[Routing.LogicalTerminal]: ...
    def ReplaceIntermediateTerminals(self, intermediateTerminals: typing.List[Routing.LogicalTerminal]) -> None: ...
    def AddIntermediateTerminal(self, intermediateTerminal: Routing.LogicalTerminal) -> bool: ...
    def RemoveIntermediateTerminal(self, intermediateTerminal: Routing.LogicalTerminal) -> bool: ...
    def GetRoutingMethod(self) -> str: ...
    def GetRoutedLevel(self) -> str: ...
    def GetRoutedLevelEnum(self) -> Routing.Electrical.Connection.RouteLevel: ...
    def IsRouted(self) -> bool: ...
    def FindNearestParentDevice(self) -> Routing.SingleDevice: ...
    def FindNearestHarnessDevice(self) -> Routing.Electrical.HarnessDevice: ...
    def FindNearestCableDevice(self) -> Routing.Electrical.CableDevice: ...
    def FindFromConnector(self) -> Routing.Electrical.ConnectorDevice: ...
    def FindToConnector(self) -> Routing.Electrical.ConnectorDevice: ...
    def FindPaths(self, routeLevel: Routing.Electrical.Connection.RouteLevel) -> typing.List[Routing.Path]: ...
    def Unroute(self) -> None: ...
    def AutomaticallyRoute(self, routeLevel: Routing.Electrical.Connection.RouteLevel) -> None: ...
    def AssignPath(self, routeLevel: Routing.Electrical.Connection.RouteLevel, path: Routing.Path) -> None: ...
    def IsExternallyRouted(self) -> bool: ...
    @property
    def FromTerminal(self) -> Routing.LogicalTerminal: ...
    @FromTerminal.setter
    def FromTerminal(self, value: Routing.LogicalTerminal) -> None: ...
    @property
    def MaximumPathLength(self) -> float: ...
    @MaximumPathLength.setter
    def MaximumPathLength(self, value: float) -> None: ...
    @property
    def MinimumPathLength(self) -> float: ...
    @MinimumPathLength.setter
    def MinimumPathLength(self, value: float) -> None: ...
    @property
    def PathLengthMultiplier(self) -> str: ...
    @PathLengthMultiplier.setter
    def PathLengthMultiplier(self, value: str) -> None: ...
    @property
    def PathLengthOffset(self) -> str: ...
    @PathLengthOffset.setter
    def PathLengthOffset(self, value: str) -> None: ...
    @property
    def ToTerminal(self) -> Routing.LogicalTerminal: ...
    @ToTerminal.setter
    def ToTerminal(self, value: Routing.LogicalTerminal) -> None: ...


    class RouteLevel(enum.Enum):
        NotRouted= 0
        Pin= 1
        Component= 2
        Mixed= 3
    

class CablewaysLayoutViewCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Routing.Electrical.CablewaysLayoutView]: ...
    @typing.overload
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateLayoutView(self, segment: Curve) -> Routing.Electrical.CablewaysLayoutView: ...
    def Tag(self) -> Tag: ...



class CablewaysLayoutView(NXObject):
    def __init__(self) -> None: ...
    def CondemnLayoutViewEntities(self) -> None: ...
    def UncondemnLayoutViewEntities(self) -> None: ...
    @typing.overload
    def PositionLayoutView(self, orientation: Matrix3x3, origin: Point3d) -> None: ...
    @typing.overload
    def PositionLayoutView(self, toOrientation: Xform) -> None: ...
    def FlipView(self) -> None: ...
    def GetViewDirection(self) -> bool: ...
    def HighlightView(self) -> None: ...
    def UnhighlightView(self) -> None: ...
    def GetViewMatrixAndOrigin(self, orientation: Matrix3x3, origin: Point3d) -> None: ...


class CablewaysLayoutBuilder(Builder):
    def __init__(self) -> None: ...


class CablewaysBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AllowNewCables(self) -> bool: ...
    @AllowNewCables.setter
    def AllowNewCables(self, value: bool) -> None: ...
    @property
    def AllowOverFill(self) -> bool: ...
    @AllowOverFill.setter
    def AllowOverFill(self, value: bool) -> None: ...
    @property
    def CableTrayArea(self) -> Expression: ...
    @CableTrayArea.setter
    def CableTrayArea(self, value: Expression) -> None: ...
    @property
    def CableTrayMaximumHeight(self) -> Expression: ...
    @CableTrayMaximumHeight.setter
    def CableTrayMaximumHeight(self, value: Expression) -> None: ...
    @property
    def CabletrayHeight(self) -> Expression: ...
    @CabletrayHeight.setter
    def CabletrayHeight(self, value: Expression) -> None: ...
    @property
    def CabletrayWidth(self) -> Expression: ...
    @CabletrayWidth.setter
    def CabletrayWidth(self, value: Expression) -> None: ...
    @property
    def FillPercentage(self) -> Expression: ...
    @FillPercentage.setter
    def FillPercentage(self, value: Expression) -> None: ...
    @property
    def RouteObjectCollector(self) -> Routing.RouteObjectCollector: ...
    @RouteObjectCollector.setter
    def RouteObjectCollector(self, value: Routing.RouteObjectCollector) -> None: ...
    @property
    def SpecifiedFillPercentage(self) -> Expression: ...
    @SpecifiedFillPercentage.setter
    def SpecifiedFillPercentage(self, value: Expression) -> None: ...


class CableStockDefinition(Routing.Electrical.ElectricalStockDefinition):
    def __init__(self) -> None: ...
    @property
    def CableLocation(self) -> int: ...
    @CableLocation.setter
    def CableLocation(self, value: int) -> None: ...
    @property
    def CoverThickness(self) -> float: ...
    @CoverThickness.setter
    def CoverThickness(self, value: float) -> None: ...
    @property
    def WireSpacing(self) -> float: ...
    @WireSpacing.setter
    def WireSpacing(self, value: float) -> None: ...


class CableDevice(Routing.Electrical.ElectricalStockDevice):
    def __init__(self) -> None: ...
    def GetAssemblyDefinition(self) -> Routing.Electrical.CableDefinition: ...
    def ImportCablePart(self, partName: str) -> None: ...
    def GetConduitPartNumber(self) -> str: ...
    def SetConduitPartNumber(self, conduitPartNumber: str) -> None: ...


class CableDefinition(Routing.AssemblyDefinition):
    def __init__(self) -> None: ...


class CableConnectionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Routing.Electrical.CableConnection]: ...
    @typing.overload
    def __init__(self, owner: Routing.RouteManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateCableConnection(self) -> Routing.Electrical.CableConnection: ...
    def CreateShieldConnection(self) -> Routing.Electrical.CableConnection: ...
    def Tag(self) -> Tag: ...



class CableConnection(Routing.Electrical.Connection):
    def __init__(self) -> None: ...
    def IsCableRouted(self) -> bool: ...


class AssignProxyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Point(self) -> Point: ...
    @Point.setter
    def Point(self, value: Point) -> None: ...
    @property
    def Vector(self) -> Direction: ...
    @Vector.setter
    def Vector(self, value: Direction) -> None: ...


