from ...NXOpen import *

import typing
import enum

class OptimizationCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Optimization.OptimizationBuilder]: ...
    @typing.overload
    def __init__(self, owner: BasePart) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateOptimizationBuilder(self) -> Optimization.OptimizationBuilder: ...
    def CreateOptimizationAttributeBuilder(self) -> Optimization.OptimizationAttributeBuilder: ...
    def CreateMapleExpBuilder(self) -> Optimization.MapleExpBuilder: ...
    def CreateMathIntegrationExpBuilder(self) -> Optimization.MathIntegrationExpBuilder: ...
    def Tag(self) -> Tag: ...



class OptimizationBuilder(Builder):
    def __init__(self) -> None: ...
    def RunOptimization(self) -> None: ...
    def GetOptimizationObjectives(self) -> typing.List[Optimization.OptimizationBuilder.OptimizationObjective]: ...
    def SetOptimizationObjectives(self, attributeNames: str, attributeObjects: typing.List[NXObject], objectiveTypes: typing.List[Optimization.OptimizationBuilder.OptimizationAttributeType], objectiveTargetValues: float) -> None: ...
    def GetOptimizationVariables(self) -> typing.List[Optimization.OptimizationBuilder.OptimizationVariable]: ...
    def SetOptimizationVariables(self, attributeNames: str, attributeObjects: typing.List[NXObject], variableTypes: typing.List[Optimization.OptimizationBuilder.OptimizationAttributeType], variableLowerLimitValue: float, variableUpperLimitValue: float) -> None: ...
    def GetOptimizationConstraints(self) -> typing.List[Optimization.OptimizationBuilder.OptimizationConstraint]: ...
    def SetOptimizationConstraints(self, attributeNames: str, attributeObjects: typing.List[NXObject], constraintTypes: typing.List[Optimization.OptimizationBuilder.OptimizationAttributeType], constraintLowerLimitValue: float, constraintUpperLimitValue: float, constraintLimitType: typing.List[Optimization.OptimizationBuilder.OptimizationConstraintLimitType]) -> None: ...
    def BuildAllObjectives(self) -> None: ...
    def RemoveAllObjectives(self) -> None: ...
    def BuildAllVariables(self) -> None: ...
    def RemoveAllVariables(self) -> None: ...
    def BuildAllConstraints(self) -> None: ...
    def RemoveAllConstraints(self) -> None: ...
    @property
    def AbsoluteConvergenceCriteria(self) -> float: ...
    @AbsoluteConvergenceCriteria.setter
    def AbsoluteConvergenceCriteria(self, value: float) -> None: ...
    @property
    def AlgorithmType(self) -> Optimization.OptimizationBuilder.OptimizationAlgorithmType: ...
    @AlgorithmType.setter
    def AlgorithmType(self, value: Optimization.OptimizationBuilder.OptimizationAlgorithmType) -> None: ...
    @property
    def ConvergenceSpeedType(self) -> Optimization.OptimizationBuilder.OptimizationConvergenceSpeedType: ...
    @ConvergenceSpeedType.setter
    def ConvergenceSpeedType(self, value: Optimization.OptimizationBuilder.OptimizationConvergenceSpeedType) -> None: ...
    @property
    def IsShowGraph(self) -> bool: ...
    @IsShowGraph.setter
    def IsShowGraph(self, value: bool) -> None: ...
    @property
    def IsUpdateDisp(self) -> bool: ...
    @IsUpdateDisp.setter
    def IsUpdateDisp(self, value: bool) -> None: ...
    @property
    def MaxNumberIteration(self) -> int: ...
    @MaxNumberIteration.setter
    def MaxNumberIteration(self, value: int) -> None: ...
    @property
    def MaxTime(self) -> int: ...
    @MaxTime.setter
    def MaxTime(self, value: int) -> None: ...
    @property
    def OptimizationType(self) -> Optimization.OptimizationBuilder.OptimizationTargetType: ...
    @OptimizationType.setter
    def OptimizationType(self, value: Optimization.OptimizationBuilder.OptimizationTargetType) -> None: ...
    @property
    def RelativeConvergenceCriteria(self) -> float: ...
    @RelativeConvergenceCriteria.setter
    def RelativeConvergenceCriteria(self, value: float) -> None: ...
    @property
    def StudyName(self) -> str: ...
    @StudyName.setter
    def StudyName(self, value: str) -> None: ...


    class OptimizationBuilderOptimizationVariable():
        @property
        def AttributeName(self) -> str: ...
        @AttributeName.setter
        def AttributeName(self, value: str) -> None: ...
        @property
        def AttributeObject(self) -> NXObject: ...
        @AttributeObject.setter
        def AttributeObject(self, value: NXObject) -> None: ...
        @property
        def VariableType(self) -> Optimization.OptimizationBuilder.OptimizationAttributeType: ...
        @VariableType.setter
        def VariableType(self, value: Optimization.OptimizationBuilder.OptimizationAttributeType) -> None: ...
        @property
        def VariableLowerLimitValue(self) -> float: ...
        @VariableLowerLimitValue.setter
        def VariableLowerLimitValue(self, value: float) -> None: ...
        @property
        def VariableUpperLimitValue(self) -> float: ...
        @VariableUpperLimitValue.setter
        def VariableUpperLimitValue(self, value: float) -> None: ...
        def ToString(self) -> str: ...
    

    class OptimizationTargetType(enum.Enum):
        Minimum= 0
        Maximum= 1
        Target= 2
    

    class OptimizationBuilderOptimizationObjective():
        @property
        def AttributeName(self) -> str: ...
        @AttributeName.setter
        def AttributeName(self, value: str) -> None: ...
        @property
        def AttributeObject(self) -> NXObject: ...
        @AttributeObject.setter
        def AttributeObject(self, value: NXObject) -> None: ...
        @property
        def ObjectiveType(self) -> Optimization.OptimizationBuilder.OptimizationAttributeType: ...
        @ObjectiveType.setter
        def ObjectiveType(self, value: Optimization.OptimizationBuilder.OptimizationAttributeType) -> None: ...
        @property
        def ObjectiveTargetValue(self) -> float: ...
        @ObjectiveTargetValue.setter
        def ObjectiveTargetValue(self, value: float) -> None: ...
        def ToString(self) -> str: ...
    

    class OptimizationConvergenceSpeedType(enum.Enum):
        Slow= 0
        Medium= 1
        Fast= 2
        Infinite= 3
    

    class OptimizationConstraintLimitType(enum.Enum):
        Upper= 0
        Lower= 1
    

    class OptimizationBuilderOptimizationConstraint():
        @property
        def AttributeName(self) -> str: ...
        @AttributeName.setter
        def AttributeName(self, value: str) -> None: ...
        @property
        def AttributeObject(self) -> NXObject: ...
        @AttributeObject.setter
        def AttributeObject(self, value: NXObject) -> None: ...
        @property
        def ConstraintType(self) -> Optimization.OptimizationBuilder.OptimizationAttributeType: ...
        @ConstraintType.setter
        def ConstraintType(self, value: Optimization.OptimizationBuilder.OptimizationAttributeType) -> None: ...
        @property
        def ConstraintLowerLimitValue(self) -> float: ...
        @ConstraintLowerLimitValue.setter
        def ConstraintLowerLimitValue(self, value: float) -> None: ...
        @property
        def ConstraintUpperLimitValue(self) -> float: ...
        @ConstraintUpperLimitValue.setter
        def ConstraintUpperLimitValue(self, value: float) -> None: ...
        @property
        def ConstraintLimitType(self) -> Optimization.OptimizationBuilder.OptimizationConstraintLimitType: ...
        @ConstraintLimitType.setter
        def ConstraintLimitType(self, value: Optimization.OptimizationBuilder.OptimizationConstraintLimitType) -> None: ...
        def ToString(self) -> str: ...
    

    class OptimizationAttributeType(enum.Enum):
        Expression= 0
        KFAttribute= 1
        GeometryParameter= 2
    

    class OptimizationAlgorithmType(enum.Enum):
        SimulatedAnnealing= 0
        GlobalSimplex= 1
        Powell= 2
        ConjugateGradient= 3
        Lexicographic= 4
        PatternSwarm= 5
    

    class OptimizationBuilder_OptimizationVariable():
        @property
        def attributeName(self) -> int: ...
        @attributeName.setter
        def attributeName(self, value: int) -> None: ...
        @property
        def attributeObject(self) -> Tag: ...
        @attributeObject.setter
        def attributeObject(self, value: Tag) -> None: ...
        @property
        def variableType(self) -> Optimization.OptimizationBuilder.OptimizationAttributeType: ...
        @variableType.setter
        def variableType(self, value: Optimization.OptimizationBuilder.OptimizationAttributeType) -> None: ...
        @property
        def variableLowerLimitValue(self) -> float: ...
        @variableLowerLimitValue.setter
        def variableLowerLimitValue(self, value: float) -> None: ...
        @property
        def variableUpperLimitValue(self) -> float: ...
        @variableUpperLimitValue.setter
        def variableUpperLimitValue(self, value: float) -> None: ...
    

    class OptimizationBuilder_OptimizationObjective():
        @property
        def attributeName(self) -> int: ...
        @attributeName.setter
        def attributeName(self, value: int) -> None: ...
        @property
        def attributeObject(self) -> Tag: ...
        @attributeObject.setter
        def attributeObject(self, value: Tag) -> None: ...
        @property
        def objectiveType(self) -> Optimization.OptimizationBuilder.OptimizationAttributeType: ...
        @objectiveType.setter
        def objectiveType(self, value: Optimization.OptimizationBuilder.OptimizationAttributeType) -> None: ...
        @property
        def objectiveTargetValue(self) -> float: ...
        @objectiveTargetValue.setter
        def objectiveTargetValue(self, value: float) -> None: ...
    

    class OptimizationBuilder_OptimizationConstraint():
        @property
        def attributeName(self) -> int: ...
        @attributeName.setter
        def attributeName(self, value: int) -> None: ...
        @property
        def attributeObject(self) -> Tag: ...
        @attributeObject.setter
        def attributeObject(self, value: Tag) -> None: ...
        @property
        def constraintType(self) -> Optimization.OptimizationBuilder.OptimizationAttributeType: ...
        @constraintType.setter
        def constraintType(self, value: Optimization.OptimizationBuilder.OptimizationAttributeType) -> None: ...
        @property
        def constraintLowerLimitValue(self) -> float: ...
        @constraintLowerLimitValue.setter
        def constraintLowerLimitValue(self, value: float) -> None: ...
        @property
        def constraintUpperLimitValue(self) -> float: ...
        @constraintUpperLimitValue.setter
        def constraintUpperLimitValue(self, value: float) -> None: ...
        @property
        def constraintLimitType(self) -> Optimization.OptimizationBuilder.OptimizationConstraintLimitType: ...
        @constraintLimitType.setter
        def constraintLimitType(self, value: Optimization.OptimizationBuilder.OptimizationConstraintLimitType) -> None: ...
    

class OptimizationAttributeBuilder(Builder):
    def __init__(self) -> None: ...
    def AdoptObject(self, object: NXObject) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MathIntegrationExpBuilder(Builder):
    def __init__(self) -> None: ...


class MapleExpBuilder(Builder):
    def __init__(self) -> None: ...


class DesignStudyCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Optimization.DesignStudyBuilder]: ...
    @typing.overload
    def __init__(self, owner: BasePart) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateDesignStudyBuilder(self) -> Optimization.DesignStudyBuilder: ...
    def CreateDesignStudyAttributeBuilder(self) -> Optimization.DesignStudyAttributeBuilder: ...
    def Tag(self) -> Tag: ...



class DesignStudyBuilder(Builder):
    def __init__(self) -> None: ...
    def RunDesignStudy(self) -> None: ...
    def GetDesignStudyObjectives(self) -> typing.List[Optimization.DesignStudyBuilder.DesignStudyObjective]: ...
    def SetDesignStudyObjectives(self, attributeNames: str, attributeObjects: typing.List[NXObject], objectiveTypes: typing.List[Optimization.DesignStudyBuilder.DesignStudyAttributeType], warningLowerLimit: float, warningUpperLimit: float, failureLowerLimit: float, failureUpperLimit: float) -> None: ...
    def GetDesignStudyVariables(self) -> typing.List[Optimization.DesignStudyBuilder.DesignStudyVariable]: ...
    def SetDesignStudyVariables(self, attributeNames: str, attributeObjects: typing.List[NXObject], variableTypes: typing.List[Optimization.DesignStudyBuilder.DesignStudyAttributeType], variableLowerLimitValue: float, variableUpperLimitValue: float, distributeType: typing.List[Optimization.DesignStudyBuilder.DesignStudyDistributeType], locationParameter: float, scaleParameter: float, shapeParameter: float, valuesCount: int) -> None: ...
    def BuildAllObjectives(self) -> None: ...
    def RemoveAllObjectives(self) -> None: ...
    def BuildAllVariables(self) -> None: ...
    def RemoveAllVariables(self) -> None: ...
    @property
    def IsShowGraph(self) -> bool: ...
    @IsShowGraph.setter
    def IsShowGraph(self, value: bool) -> None: ...
    @property
    def IsUpdateDisp(self) -> bool: ...
    @IsUpdateDisp.setter
    def IsUpdateDisp(self, value: bool) -> None: ...
    @property
    def StudyName(self) -> str: ...
    @StudyName.setter
    def StudyName(self, value: str) -> None: ...


    class DesignStudyBuilderDesignStudyVariable():
        @property
        def AttributeName(self) -> str: ...
        @AttributeName.setter
        def AttributeName(self, value: str) -> None: ...
        @property
        def AttributeObject(self) -> NXObject: ...
        @AttributeObject.setter
        def AttributeObject(self, value: NXObject) -> None: ...
        @property
        def VariableType(self) -> Optimization.DesignStudyBuilder.DesignStudyAttributeType: ...
        @VariableType.setter
        def VariableType(self, value: Optimization.DesignStudyBuilder.DesignStudyAttributeType) -> None: ...
        @property
        def VariableLowerLimitValue(self) -> float: ...
        @VariableLowerLimitValue.setter
        def VariableLowerLimitValue(self, value: float) -> None: ...
        @property
        def VariableUpperLimitValue(self) -> float: ...
        @VariableUpperLimitValue.setter
        def VariableUpperLimitValue(self, value: float) -> None: ...
        @property
        def DistributeType(self) -> Optimization.DesignStudyBuilder.DesignStudyDistributeType: ...
        @DistributeType.setter
        def DistributeType(self, value: Optimization.DesignStudyBuilder.DesignStudyDistributeType) -> None: ...
        @property
        def LocationParameter(self) -> float: ...
        @LocationParameter.setter
        def LocationParameter(self, value: float) -> None: ...
        @property
        def ScaleParameter(self) -> float: ...
        @ScaleParameter.setter
        def ScaleParameter(self, value: float) -> None: ...
        @property
        def ShapeParameter(self) -> float: ...
        @ShapeParameter.setter
        def ShapeParameter(self, value: float) -> None: ...
        @property
        def ValuesCount(self) -> int: ...
        @ValuesCount.setter
        def ValuesCount(self, value: int) -> None: ...
        def ToString(self) -> str: ...
    

    class DesignStudyBuilderDesignStudyObjective():
        @property
        def AttributeName(self) -> str: ...
        @AttributeName.setter
        def AttributeName(self, value: str) -> None: ...
        @property
        def AttributeObject(self) -> NXObject: ...
        @AttributeObject.setter
        def AttributeObject(self, value: NXObject) -> None: ...
        @property
        def ObjectiveType(self) -> Optimization.DesignStudyBuilder.DesignStudyAttributeType: ...
        @ObjectiveType.setter
        def ObjectiveType(self, value: Optimization.DesignStudyBuilder.DesignStudyAttributeType) -> None: ...
        @property
        def WarningLowerLimit(self) -> float: ...
        @WarningLowerLimit.setter
        def WarningLowerLimit(self, value: float) -> None: ...
        @property
        def WarningUpperLimit(self) -> float: ...
        @WarningUpperLimit.setter
        def WarningUpperLimit(self, value: float) -> None: ...
        @property
        def FailureLowerLimit(self) -> float: ...
        @FailureLowerLimit.setter
        def FailureLowerLimit(self, value: float) -> None: ...
        @property
        def FailureUpperLimit(self) -> float: ...
        @FailureUpperLimit.setter
        def FailureUpperLimit(self, value: float) -> None: ...
        def ToString(self) -> str: ...
    

    class DesignStudyDistributeType(enum.Enum):
        Uniform= 0
        Normal= 1
        Gamma= 2
    

    class DesignStudyConstraintLimitType(enum.Enum):
        Upper= 0
        Lower= 1
    

    class DesignStudyAttributeType(enum.Enum):
        Expression= 0
        KFAttribute= 1
        GeometryParameter= 2
    

    class DesignStudyBuilder_DesignStudyVariable():
        @property
        def attributeName(self) -> int: ...
        @attributeName.setter
        def attributeName(self, value: int) -> None: ...
        @property
        def attributeObject(self) -> Tag: ...
        @attributeObject.setter
        def attributeObject(self, value: Tag) -> None: ...
        @property
        def variableType(self) -> Optimization.DesignStudyBuilder.DesignStudyAttributeType: ...
        @variableType.setter
        def variableType(self, value: Optimization.DesignStudyBuilder.DesignStudyAttributeType) -> None: ...
        @property
        def variableLowerLimitValue(self) -> float: ...
        @variableLowerLimitValue.setter
        def variableLowerLimitValue(self, value: float) -> None: ...
        @property
        def variableUpperLimitValue(self) -> float: ...
        @variableUpperLimitValue.setter
        def variableUpperLimitValue(self, value: float) -> None: ...
        @property
        def distributeType(self) -> Optimization.DesignStudyBuilder.DesignStudyDistributeType: ...
        @distributeType.setter
        def distributeType(self, value: Optimization.DesignStudyBuilder.DesignStudyDistributeType) -> None: ...
        @property
        def locationParameter(self) -> float: ...
        @locationParameter.setter
        def locationParameter(self, value: float) -> None: ...
        @property
        def scaleParameter(self) -> float: ...
        @scaleParameter.setter
        def scaleParameter(self, value: float) -> None: ...
        @property
        def shapeParameter(self) -> float: ...
        @shapeParameter.setter
        def shapeParameter(self, value: float) -> None: ...
        @property
        def valuesCount(self) -> int: ...
        @valuesCount.setter
        def valuesCount(self, value: int) -> None: ...
    

    class DesignStudyBuilder_DesignStudyObjective():
        @property
        def attributeName(self) -> int: ...
        @attributeName.setter
        def attributeName(self, value: int) -> None: ...
        @property
        def attributeObject(self) -> Tag: ...
        @attributeObject.setter
        def attributeObject(self, value: Tag) -> None: ...
        @property
        def objectiveType(self) -> Optimization.DesignStudyBuilder.DesignStudyAttributeType: ...
        @objectiveType.setter
        def objectiveType(self, value: Optimization.DesignStudyBuilder.DesignStudyAttributeType) -> None: ...
        @property
        def warningLowerLimit(self) -> float: ...
        @warningLowerLimit.setter
        def warningLowerLimit(self, value: float) -> None: ...
        @property
        def warningUpperLimit(self) -> float: ...
        @warningUpperLimit.setter
        def warningUpperLimit(self, value: float) -> None: ...
        @property
        def failureLowerLimit(self) -> float: ...
        @failureLowerLimit.setter
        def failureLowerLimit(self, value: float) -> None: ...
        @property
        def failureUpperLimit(self) -> float: ...
        @failureUpperLimit.setter
        def failureUpperLimit(self, value: float) -> None: ...
    

class DesignStudyAttributeBuilder(Builder):
    def __init__(self) -> None: ...
    def AdoptObject(self, object: NXObject) -> None: ...


