from . import PostConfigurator
from ...NXOpen import *

import typing
import enum

class TimeAnalysis(TaggedObject):
    def __init__(self) -> None: ...
    def Start(self) -> None: ...
    def Stop(self) -> None: ...
    def Reset(self) -> None: ...


class Snapshot(NXObject):
    def __init__(self) -> None: ...


class SmkWizardBuilder(Builder):
    def __init__(self) -> None: ...
    def SetArchieveData(self) -> None: ...
    def GetJunctionClassification(self, junctionName: str) -> SIM.SmkWizardBuilder.JunctionClassificationType: ...
    def SetJunctionClassification(self, junctionName: str, jctClass: SIM.SmkWizardBuilder.JunctionClassificationType) -> None: ...
    def GetJunctionOrigin(self, junctionName: str) -> Point3d: ...
    def GetJunctionMatrix(self, junctionName: str) -> Matrix3x3: ...
    def SetJunctionCsys(self, junctionName: str, csys: CartesianCoordinateSystem) -> None: ...
    def AddGeometry(self, componentName: str, geo: NXObject) -> None: ...
    def DeleteGeometry(self, componentName: str, geo: NXObject) -> None: ...
    def SetGeometries(self, componentName: str, geos: typing.List[NXObject]) -> None: ...
    def GetGeometries(self, componentName: str, geos: typing.List[NXObject]) -> None: ...
    def DeleteAllGeometries(self, componentName: str) -> None: ...
    def GetAxisJunctionName(self, axisName: str) -> str: ...
    def SetAxisJunctionName(self, axisName: str, junctionName: str) -> None: ...
    def GetAxisDirection(self, axisName: str) -> SIM.SmkWizardBuilder.AxisDirectionType: ...
    def GetAxisDirectionVector(self, axisName: str, vectorX: float, vectorY: float, vectorZ: float) -> None: ...
    def SetAxisDirection(self, axisName: str, axisDir: SIM.SmkWizardBuilder.AxisDirectionType) -> None: ...
    def GetAxisMotion(self, axisName: str, isNcAxis: bool) -> SIM.SmkWizardBuilder.AxisMotionType: ...
    def SetAxisMotion(self, axisName: str, isNcAxis: bool, type: SIM.SmkWizardBuilder.AxisMotionType) -> None: ...
    def GetAxisNumber(self, axisName: str) -> int: ...
    def SetAxisNumber(self, axisName: str, number: int) -> None: ...
    def GetAxisInitialValue(self, axisName: str) -> float: ...
    def SetAxisInitialValue(self, axisName: str, initialValue: float) -> None: ...
    def GetAxisUpperLimit(self, axisName: str) -> float: ...
    def SetAxisUpperLimit(self, axisName: str, upperValue: float) -> None: ...
    def GetAxisUpperSoftLimit(self, axisName: str) -> float: ...
    def SetAxisUpperSoftLimit(self, axisName: str, upperSoftValue: float) -> None: ...
    def GetAxisLowerLimit(self, axisName: str) -> float: ...
    def SetAxisLowerLimit(self, axisName: str, lowerValue: float) -> None: ...
    def GetAxisLowerSoftLimit(self, axisName: str) -> float: ...
    def SetAxisLowerSoftLimit(self, axisName: str, lowerSoftValue: float) -> None: ...
    def GetAxisMaximumVelocity(self, axisName: str) -> float: ...
    def SetAxisMaximumVelocity(self, axisName: str, value: float) -> None: ...
    def GetAxisMaximumAcceleration(self, axisName: str) -> float: ...
    def SetAxisMaximumAcceleration(self, axisName: str, value: float) -> None: ...
    def GetAxisMaximumDeceleration(self, axisName: str) -> float: ...
    def SetAxisMaximumDeceleration(self, axisName: str, value: float) -> None: ...
    def GetAxisJerkLimit(self, axisName: str) -> float: ...
    def SetAxisJerkLimit(self, axisName: str, value: float) -> None: ...
    def GetAxisJumpVelocity(self, axisName: str) -> float: ...
    def SetAxisJumpVelocity(self, axisName: str, value: float) -> None: ...
    def GetAxisKv(self, axisName: str) -> float: ...
    def SetAxisKv(self, axisName: str, value: float) -> None: ...
    def GetAxisFinePrecision(self, axisName: str) -> float: ...
    def SetAxisFinePrecision(self, axisName: str, value: float) -> None: ...
    def GetAxisCoarsePrecision(self, axisName: str) -> float: ...
    def SetAxisCoarsePrecision(self, axisName: str, value: float) -> None: ...
    def CreateMachineKit(self) -> None: ...
    def AddDeviceTemplateFilePath(self, filePath: str) -> None: ...
    def DeleteDeviceTemplateFilePath(self, index: int, filePath: str) -> None: ...
    def CreatePocketTransformData(self, pocketName: str) -> None: ...
    def SetPocketTransformType(self, pocketName: str, transformType: SIM.SmkWizardBuilder.PocketTransformType) -> None: ...
    def SetPocketTransformTranslateDeltaXC(self, pocketName: str, deltaXC: float) -> None: ...
    def SetPocketTransformTranslateDeltaYC(self, pocketName: str, deltaYC: float) -> None: ...
    def SetPocketTransformTranslateDeltaZC(self, pocketName: str, deltaZC: float) -> None: ...
    def SetPocketTransformTranslateReferencePoint(self, pocketName: str, x: float, y: float, z: float) -> None: ...
    def SetPocketTransformTranslateToPoint(self, pocketName: str, x: float, y: float, z: float) -> None: ...
    def SetPocketTransformRotateLineStartPoint(self, pocketName: str, x: float, y: float, z: float) -> None: ...
    def SetPocketTransformRotateLineEndPoint(self, pocketName: str, x: float, y: float, z: float) -> None: ...
    def SetPocketTransformRotateLinePoint(self, pocketName: str, x: float, y: float, z: float) -> None: ...
    def SetPocketTransformRotateLineVector(self, pocketName: str, i: float, j: float, k: float) -> None: ...
    def SetPocketTransformDivision(self, pocketName: str, division: int) -> None: ...
    def SetPocketTransformNumberOfCopies(self, pocketName: str, numOfCopies: int) -> None: ...
    def SetPocketTransformRotateAngle(self, pocketName: str, angle: float) -> None: ...
    def SetPocketTransformHolderIDReference(self, pocketName: str, reference: int) -> None: ...
    def SetPocketTransformHolderIDIncrement(self, pocketName: str, increment: int) -> None: ...
    def SetPocketTransformCutcomRegisterIncrement(self, pocketName: str, increment: int) -> None: ...
    def SetPocketTransformAdjustRegisterIncrement(self, pocketName: str, increment: int) -> None: ...
    def ClearWizardData(self) -> None: ...
    def ParseTemplates(self) -> None: ...
    def DeleteComponent(self, componentName: str) -> None: ...
    def AddComponent(self, parentCompName: str, componentName: str) -> None: ...
    def RenameComponent(self, componentName: str, newComponentName: str) -> None: ...
    def AddComponentClassification(self, componentName: str, classificationType: SIM.SmkWizardBuilder.ComponentClassificationType) -> None: ...
    def RemoveComponentClassification(self, componentName: str, classificationType: SIM.SmkWizardBuilder.ComponentClassificationType) -> None: ...
    def MoveComponent(self, source: str, target: str) -> None: ...
    def CreateSmkKimChainBuilder(self) -> SIM.KinematicChain: ...
    def CreateSmkKimChannelBuilder(self) -> SIM.KinematicChannelBuilder: ...
    def DeleteJunction(self, jctFullName: str) -> None: ...
    def AddJunction(self, componentName: str, junctionName: str) -> None: ...
    def RenameJunction(self, jctFullName: str, newJunctionName: str) -> None: ...
    def MoveJunctions(self, source: str, target: str) -> None: ...
    def RenameAxis(self, compName: str, oldAxisName: str, newAxisName: str) -> None: ...
    def DeleteAxis(self, compName: str, axisName: str) -> None: ...
    def AddAxis(self, compName: str, axisName: str) -> None: ...
    def MoveAxis(self, source: str, target: str) -> None: ...
    def RenameAxisJunction(self, jctFullName: str, newJunctionName: str) -> None: ...
    def GetDeviceID(self, componentName: str) -> str: ...
    def SetDeviceID(self, componentName: str, deviceId: str) -> None: ...
    def GetHolderID(self, componentName: str) -> str: ...
    def SetHolderID(self, componentName: str, holderId: str) -> None: ...
    def GetCapacity(self, componentName: str) -> int: ...
    def SetCapacity(self, componentName: str, capacity: int) -> None: ...
    def GetAdjustRegister(self, componentName: str) -> int: ...
    def SetAdjustRegister(self, componentName: str, adjustReg: int) -> None: ...
    def GetCutcomRegister(self, componentName: str) -> int: ...
    def SetCutcomRegister(self, componentName: str, cutcomReg: int) -> None: ...
    def GetChannelDevices(self, channelName: str, devices: str) -> None: ...
    def GenerateTransformPockets(self, parentCompName: str, pocketName: str) -> None: ...
    def HasComponent(self, componentName: str) -> bool: ...
    def HasAxis(self, axisName: str) -> bool: ...
    def AskMachineBaseComponent(self) -> str: ...
    def AddDeviceComponent(self, devicePartPath: str, layer: int, transform: Matrix4x4) -> None: ...
    def AddDevicePartOccurrence(self, devicePart: TaggedObject) -> None: ...
    def GetDevicePartMountJunction(self, devicePartPath: str) -> TaggedObject: ...
    def ResetWizard(self) -> None: ...
    @property
    def ArchieveFile(self) -> SIM.SmkWizardBuilder.ArchieveFileType: ...
    @ArchieveFile.setter
    def ArchieveFile(self, value: SIM.SmkWizardBuilder.ArchieveFileType) -> None: ...
    @property
    def ArchieveMachineFilePath(self) -> str: ...
    @ArchieveMachineFilePath.setter
    def ArchieveMachineFilePath(self, value: str) -> None: ...
    @property
    def ArchieveTemplateFilePath(self) -> str: ...
    @ArchieveTemplateFilePath.setter
    def ArchieveTemplateFilePath(self, value: str) -> None: ...
    @property
    def CreateCseDriver(self) -> bool: ...
    @CreateCseDriver.setter
    def CreateCseDriver(self, value: bool) -> None: ...
    @property
    def CreateKitType(self) -> SIM.SmkWizardBuilder.OutputType: ...
    @CreateKitType.setter
    def CreateKitType(self, value: SIM.SmkWizardBuilder.OutputType) -> None: ...
    @property
    def CreatePostprocessor(self) -> bool: ...
    @CreatePostprocessor.setter
    def CreatePostprocessor(self, value: bool) -> None: ...
    @property
    def CreationPostBuilder(self) -> SIM.PostConfigurator.CreationPostBuilder: ...
    @CreationPostBuilder.setter
    def CreationPostBuilder(self, value: SIM.PostConfigurator.CreationPostBuilder) -> None: ...
    @property
    def CseDriverTemplateFile(self) -> str: ...
    @CseDriverTemplateFile.setter
    def CseDriverTemplateFile(self, value: str) -> None: ...
    @property
    def CseDriverTemplateName(self) -> str: ...
    @CseDriverTemplateName.setter
    def CseDriverTemplateName(self, value: str) -> None: ...
    @property
    def DeviceTemplate(self) -> SIM.SmkWizardBuilder.DeviceTemplateType: ...
    @DeviceTemplate.setter
    def DeviceTemplate(self, value: SIM.SmkWizardBuilder.DeviceTemplateType) -> None: ...
    @property
    def DeviceTemplateFilePath(self) -> str: ...
    @DeviceTemplateFilePath.setter
    def DeviceTemplateFilePath(self, value: str) -> None: ...
    @property
    def JunctionCoordinateReferenceType(self) -> SIM.SmkWizardBuilder.CoordinateReferenceType: ...
    @JunctionCoordinateReferenceType.setter
    def JunctionCoordinateReferenceType(self, value: SIM.SmkWizardBuilder.CoordinateReferenceType) -> None: ...
    @property
    def MachineKitDesc(self) -> str: ...
    @MachineKitDesc.setter
    def MachineKitDesc(self, value: str) -> None: ...
    @property
    def MachineKitEditorBuilder(self) -> SIM.SmkMachineKitEditorBuilder: ...
    @MachineKitEditorBuilder.setter
    def MachineKitEditorBuilder(self, value: SIM.SmkMachineKitEditorBuilder) -> None: ...
    @property
    def MachineKitName(self) -> str: ...
    @MachineKitName.setter
    def MachineKitName(self, value: str) -> None: ...
    @property
    def MachineKitType(self) -> SIM.SmkWizardBuilder.MachineType: ...
    @MachineKitType.setter
    def MachineKitType(self, value: SIM.SmkWizardBuilder.MachineType) -> None: ...
    @property
    def MachineTemplate(self) -> str: ...
    @MachineTemplate.setter
    def MachineTemplate(self, value: str) -> None: ...
    @property
    def MachineTemplateFilePath(self) -> str: ...
    @MachineTemplateFilePath.setter
    def MachineTemplateFilePath(self, value: str) -> None: ...
    @property
    def OutputDirectory(self) -> str: ...
    @OutputDirectory.setter
    def OutputDirectory(self, value: str) -> None: ...
    @property
    def SmkKimChainConfigurationBuilder(self) -> SIM.KinematicChainConfiguration: ...
    @SmkKimChainConfigurationBuilder.setter
    def SmkKimChainConfigurationBuilder(self, value: SIM.KinematicChainConfiguration) -> None: ...
    @property
    def SmkKimChannelConfigurationBuilder(self) -> SIM.KinematicChannelConfigurationBuilder: ...
    @SmkKimChannelConfigurationBuilder.setter
    def SmkKimChannelConfigurationBuilder(self, value: SIM.KinematicChannelConfigurationBuilder) -> None: ...


    class RegisterType(enum.Enum):
        SameAsHolderId= 0
        Specify= 1
    

    class PocketTransformType(enum.Enum):
        TranslateDelta= 0
        TranslateToPoint= 1
        RotateTwoPoint= 2
        RotatePointVector= 3
    

    class OutputType(enum.Enum):
        InstalledMachines= 0
        Mtk= 1
    

    class MachineType(enum.Enum):
        Mill= 0
        Turnmill= 1
        Lathe= 2
        Millturn= 3
        Wedm= 4
        Robot= 5
        Generic= 6
    

    class JunctionClassificationType(enum.Enum):
        None_= 0
        ToolMount= 1
        MachineZero= 2
        LatheWpZx= 3
        LatheWpXy= 4
        HeadMount= 5
    

    class DeviceTemplateType(enum.Enum):
        None_= 0
        Specify= 1
    

    class CoordinateReferenceType(enum.Enum):
        Absolute= 0
        MachineZero= 1
    

    class ComponentClassificationType(enum.Enum):
        Turret= 0
        Pocket= 1
        PocketOnHead= 2
        Part= 3
        Workpiece= 4
        AdditiveMaterial= 5
        SetupElement= 6
        LatheSpindle= 7
        ToolCutting= 8
        ToolNonCutting= 9
        Head= 10
    

    class AxisMotionType(enum.Enum):
        Linear= 0
        Rotary= 1
        RotaryUnlimited= 2
        Spindle= 3
    

    class AxisDirectionType(enum.Enum):
        PositiveX= 0
        NegativeX= 1
        PositiveY= 2
        NegativeY= 3
        PositiveZ= 4
        NegativeZ= 5
    

    class ArchieveFileType(enum.Enum):
        None_= 0
        Specify= 1
    

class SmkMachineKitEditorBuilder(Builder):
    def __init__(self) -> None: ...
    def GetIntegerAttribute(self, attributeFullname: str) -> int: ...
    def SetIntegerAttribute(self, attributeFullname: str, value: int) -> None: ...
    def GetEnumAttribute(self, attributeFullname: str, currentValue: str, values: str) -> None: ...
    def SetEnumAttribute(self, attributeFullname: str, value: str) -> None: ...
    def GetDoubleAttribute(self, attributeFullname: str) -> float: ...
    def SetDoubleAttribute(self, attributeFullname: str, value: float) -> None: ...
    def GetStringAttribute(self, attributeFullname: str) -> str: ...
    def SetStringAttribute(self, attributeFullname: str, value: str) -> None: ...
    def SetMultiStringAttribute(self, attributeFullname: str, values: str) -> None: ...
    def GetMultiStringAttribute(self, attributeFullname: str, value: str) -> None: ...
    def DeleteAttribute(self, attributeFullname: str) -> None: ...
    def AddAttribute(self, attributeFullname: str) -> None: ...
    def SetAttributeName(self, attributeFullname: str, newName: str) -> None: ...
    def SetAttributeType(self, attributeFullname: str, type: SIM.SmkMachineKitEditorBuilder.DataType) -> None: ...
    def GetAttributeType(self, attributeFullname: str) -> SIM.SmkMachineKitEditorBuilder.DataType: ...
    def SetAttributeClassification(self, attributeFullname: str, classification: SIM.SmkMachineKitEditorBuilder.DataClassification) -> None: ...
    def GetAttributeClassification(self, attributeFullname: str) -> SIM.SmkMachineKitEditorBuilder.DataClassification: ...
    def SetAttributeVariableName(self, attributeFullname: str, variableName: str) -> None: ...
    def GetAttributeVariableName(self, attributeFullname: str) -> str: ...


    class DataType(enum.Enum):
        String= 0
        Int= 1
        Double= 2
        Enum= 3
        MultiString= 4
    

    class DataClassification(enum.Enum):
        General= 0
        Post= 1
        Sim= 2
        PostAndSim= 3
        Nc= 4
    

class SmkDebugBuilder(Builder):
    def __init__(self) -> None: ...
    def ExportGeometryInformation(self, partFolder: str, outputFile: str) -> None: ...
    @property
    def Dump(self) -> SIM.SmkDebugBuilder.DumpType: ...
    @Dump.setter
    def Dump(self, value: SIM.SmkDebugBuilder.DumpType) -> None: ...
    @property
    def Output(self) -> SIM.SmkDebugBuilder.OutputType: ...
    @Output.setter
    def Output(self, value: SIM.SmkDebugBuilder.OutputType) -> None: ...
    @property
    def OutputFile(self) -> str: ...
    @OutputFile.setter
    def OutputFile(self, value: str) -> None: ...
    @property
    def PartFolder(self) -> str: ...
    @PartFolder.setter
    def PartFolder(self, value: str) -> None: ...


    class OutputType(enum.Enum):
        Syslog= 0
        ListingWindow= 1
        Autotest= 2
        ToFile= 3
    

    class DumpType(enum.Enum):
        None_= 0
        MachineKit= 1
    

class SinumerikCaSimplifyBodiesBuilder(Builder):
    def __init__(self) -> None: ...
    def DoReplace(self) -> None: ...
    @property
    def AddOffset(self) -> Expression: ...
    @AddOffset.setter
    def AddOffset(self, value: Expression) -> None: ...
    @property
    def Associative(self) -> bool: ...
    @Associative.setter
    def Associative(self, value: bool) -> None: ...
    @property
    def CloseGaps(self) -> SIM.SinumerikCaSimplifyBodiesBuilder.CloseGapTypes: ...
    @CloseGaps.setter
    def CloseGaps(self, value: SIM.SinumerikCaSimplifyBodiesBuilder.CloseGapTypes) -> None: ...
    @property
    def CoordSystem(self) -> CoordinateSystem: ...
    @CoordSystem.setter
    def CoordSystem(self, value: CoordinateSystem) -> None: ...
    @property
    def DistanceTolerance(self) -> float: ...
    @DistanceTolerance.setter
    def DistanceTolerance(self, value: float) -> None: ...
    @property
    def ObjectToReplace(self) -> SelectDisplayableObjectList: ...
    @ObjectToReplace.setter
    def ObjectToReplace(self, value: SelectDisplayableObjectList) -> None: ...
    @property
    def PlanesList(self) -> PlaneList: ...
    @PlanesList.setter
    def PlanesList(self, value: PlaneList) -> None: ...
    @property
    def ReplaceWith(self) -> SIM.SinumerikCaSimplifyBodiesBuilder.ObjectToReplaceWithTypes: ...
    @ReplaceWith.setter
    def ReplaceWith(self, value: SIM.SinumerikCaSimplifyBodiesBuilder.ObjectToReplaceWithTypes) -> None: ...
    @property
    def SplitOffset(self) -> Expression: ...
    @SplitOffset.setter
    def SplitOffset(self, value: Expression) -> None: ...


    class ObjectToReplaceWithTypes(enum.Enum):
        Nothing= 0
        ConvexHull= 1
        BoundingSphere= 2
        BoundingBlock= 3
        BoundingCylinder= 4
        InscribedCylinder= 5
    

    class CloseGapTypes(enum.Enum):
        Sharp= 0
        Beveled= 1
        NoOffset= 2
    

class SinumerikCaPlaceholderBuilder(Builder):
    def __init__(self) -> None: ...
    def SelectComponent(self, compName: str) -> None: ...
    def UnselectComponent(self, compName: str) -> None: ...


class SinumerikCaFacetBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def FacetTolerance(self) -> float: ...
    @FacetTolerance.setter
    def FacetTolerance(self, value: float) -> None: ...


class SinumerikCaExportBuilder(Builder):
    def __init__(self) -> None: ...
    def ExportSpf(self, targetNode: str) -> None: ...
    @property
    def ChainElementIndex(self) -> int: ...
    @ChainElementIndex.setter
    def ChainElementIndex(self, value: int) -> None: ...
    @property
    def CollisionPairIndex(self) -> int: ...
    @CollisionPairIndex.setter
    def CollisionPairIndex(self, value: int) -> None: ...
    @property
    def DeleteChainsAtStart(self) -> bool: ...
    @DeleteChainsAtStart.setter
    def DeleteChainsAtStart(self, value: bool) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...
    @property
    def ListOutput(self) -> bool: ...
    @ListOutput.setter
    def ListOutput(self, value: bool) -> None: ...
    @property
    def ProtectionAreaElementIndex(self) -> int: ...
    @ProtectionAreaElementIndex.setter
    def ProtectionAreaElementIndex(self, value: int) -> None: ...
    @property
    def ProtectionAreaIndex(self) -> int: ...
    @ProtectionAreaIndex.setter
    def ProtectionAreaIndex(self, value: int) -> None: ...


class SimDebugBuilder(Builder):
    def __init__(self) -> None: ...
    def GetUiSetting(self, type: SIM.SimDebugBuilder.UiType) -> bool: ...
    def SetUiSetting(self, type: SIM.SimDebugBuilder.UiType, state: bool) -> None: ...
    def GetTrace(self, type: SIM.SimDebugBuilder.TraceType) -> bool: ...
    def SetTrace(self, type: SIM.SimDebugBuilder.TraceType, state: bool) -> None: ...
    @property
    def Driver(self) -> SIM.SimDebugBuilder.DriverType: ...
    @Driver.setter
    def Driver(self, value: SIM.SimDebugBuilder.DriverType) -> None: ...
    @property
    def DumpOutput(self) -> SIM.SimDebugBuilder.OutputType: ...
    @DumpOutput.setter
    def DumpOutput(self, value: SIM.SimDebugBuilder.OutputType) -> None: ...
    @property
    def DumpToFileName(self) -> str: ...
    @DumpToFileName.setter
    def DumpToFileName(self, value: str) -> None: ...
    @property
    def PrintoutTags(self) -> SIM.SimDebugBuilder.PrintoutTagsOrPointersType: ...
    @PrintoutTags.setter
    def PrintoutTags(self, value: SIM.SimDebugBuilder.PrintoutTagsOrPointersType) -> None: ...


    class UiType(enum.Enum):
        DisplayMomEvent= 0
        ShowPartAndTipJunctions= 1
        GenerateSpinningTools= 2
        UseHybridGougeChecker= 3
        UseMtbOldDialogs= 4
        UseFastTicker= 5
        PrintOutTraceSerialNumbers= 6
        PerformanceDisplayDetail= 7
        PerformanceDisplayTime= 8
        PerformanceIndentTime= 9
        PerformanceDisplayData= 10
        DctkWriteCollisionPairs= 11
    

    class TraceType(enum.Enum):
        ButtonDown= 0
        Vcr= 1
        Ipw= 2
        Performance= 3
        Collision= 4
        Gouge= 5
        Highlighting= 6
        Details= 7
        PositionalIsv= 8
        SpinningNonSpinning= 9
        KinematicModel= 10
        Event= 11
        LineServer= 12
        Sync= 13
        ToolPathPicking= 14
        CseMotionData= 15
        CseCallStack= 16
        CseToolEvents= 17
        CseCheckSyntax= 18
        ProcessForce= 19
        Findings= 20
    

    class PrintoutTagsOrPointersType(enum.Enum):
        Boolean= 0
        Value= 1
        Name= 2
    

    class OutputType(enum.Enum):
        Syslog= 0
        ListingWindow= 1
        Autotest= 2
        ToFile= 3
    

    class KinematicModelType(enum.Enum):
        Main= 0
        Simulation= 1
        Driver= 2
    

    class DriverType(enum.Enum):
        Cse= 0
        Mtd= 1
    

class SaveSnapshotBuilder(Builder):
    def __init__(self) -> None: ...
    def SetSnapshotName(self, name: str) -> None: ...
    def SetSetupName(self, name: str) -> None: ...


class NcProgramSource(TaggedObject):
    def __init__(self) -> None: ...
    def AddMainProgram(self, channel: str, file: str) -> SIM.NcProgram: ...
    def CreateMainProgram(self, channel: str, fileName: str) -> SIM.NcProgram: ...
    def AddSubprogram(self, file: str) -> SIM.NcProgram: ...
    def DeleteProgram(self, program: SIM.NcProgram) -> bool: ...
    def GetMainProgram(self, channel: str) -> SIM.NcProgram: ...
    def GetSubprogram(self, programId: str) -> SIM.NcProgram: ...


class NcProgramManagerBuilder(Builder):
    def __init__(self) -> None: ...
    def AddMatchingBreakpoint(self, condition: str) -> None: ...
    def AddBreakpoint(self, program: SIM.NcProgram, lineNumber: int) -> None: ...
    def ActivateBreakpoint(self, program: SIM.NcProgram, lineNumber: int) -> None: ...
    def DeactivateBreakpoint(self, program: SIM.NcProgram, lineNumber: int) -> None: ...
    def DeleteBreakpoint(self, program: SIM.NcProgram, lineNumber: int) -> None: ...
    def GetBreakpoints(self) -> typing.List[SIM.Breakpoint]: ...
    def DeactivateAllBreakpoints(self) -> None: ...
    def ActivateAllBreakpoints(self) -> None: ...
    def DeleteAllBreakpoints(self) -> None: ...
    def GetExternalFileSource(self) -> SIM.NcProgramSource: ...
    def GetSetupSource(self) -> SIM.NcProgramSource: ...
    def GetPostprocessorSource(self) -> SIM.NcProgramSource: ...


class NcProgram(NXObject):
    def __init__(self) -> None: ...
    def AddBreakpoint(self, line: int) -> None: ...
    def InsertBreakpoint(self, line: int) -> SIM.Breakpoint: ...
    def Export(self, file: str) -> None: ...
    def GetLine(self, line: int) -> str: ...
    def PostAllLines(self) -> None: ...


class NcChannelSelectionData(NXObject):
    def __init__(self) -> None: ...
    @typing.overload
    def AssignFile(self, channel: int, file: str) -> None: ...
    @typing.overload
    def AssignFile(self, channel: str, file: str) -> None: ...
    def AssignProgram(self, channel: str, program: SIM.NcProgram) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MachineToolConfiguration(Builder):
    def __init__(self) -> None: ...
    def GetMachineTechnology(self, channelName: str) -> SIM.MachineToolConfiguration.TechnologyTypes: ...
    def SetMachineTechnology(self, channelName: str, technology: SIM.MachineToolConfiguration.TechnologyTypes) -> None: ...
    def GetChannelTcpmSupport(self, channelName: str) -> bool: ...
    def SetChannelTcpmSupport(self, channelName: str, value: bool) -> None: ...
    def GetChannelSwiveling(self, channelName: str) -> SIM.MachineToolConfiguration.SwivelingTypes: ...
    def SetChannelSwiveling(self, channelName: str, value: SIM.MachineToolConfiguration.SwivelingTypes) -> None: ...
    def GetChannelToolAsSubprogram(self, channelName: str) -> bool: ...
    def SetChannelToolAsSubprogram(self, channelName: str, value: bool) -> None: ...
    def GetChannelToolCommand(self, channelName: str) -> str: ...
    def SetChannelToolCommand(self, channelName: str, newToolCommand: str) -> None: ...
    def GetChannelToolPreselect(self, channelName: str) -> str: ...
    def SetChannelToolPreselect(self, channelName: str, newToolPreselect: str) -> None: ...
    def GetLookahead(self, channelName: str) -> int: ...
    def SetLookahead(self, channelName: str, lookAhead: int) -> None: ...
    def GetChannelPlaneMill(self, channelName: str) -> SIM.MachineToolConfiguration.PlaneTypes: ...
    def SetChannelPlaneMill(self, channelName: str, newPlaneMill: SIM.MachineToolConfiguration.PlaneTypes) -> None: ...
    def GetChannelPlaneTurn(self, channelName: str) -> SIM.MachineToolConfiguration.PlaneTypes: ...
    def SetChannelPlaneTurn(self, channelName: str, newPlaneTurn: SIM.MachineToolConfiguration.PlaneTypes) -> None: ...
    def GetToolCarrierSwivelMode(self, channelName: str, carrierName: str) -> int: ...
    def SetToolCarrierSwivelMode(self, channelName: str, carrierName: str, newSwivelingMode: int) -> None: ...
    def GetToolCarrierDirectionSelection(self, channelName: str, carrierName: str) -> int: ...
    def SetToolCarrierDirectionSelection(self, channelName: str, carrierName: str, newDirectionSelection: int) -> None: ...
    def GetToolCarrierRetraction(self, channelName: str, carrierName: str) -> int: ...
    def SetToolCarrierRetraction(self, channelName: str, carrierName: str, newRetraction: int) -> None: ...
    def GetToolCarrierXRetractionPosition(self, channelName: str, carrierName: str) -> float: ...
    def SetToolCarrierXRetractionPosition(self, channelName: str, carrierName: str, newXPosition: float) -> None: ...
    def GetToolCarrierYRetractionPosition(self, channelName: str, carrierName: str) -> float: ...
    def SetToolCarrierYRetractionPosition(self, channelName: str, carrierName: str, newYPosition: float) -> None: ...
    def GetToolCarrierZRetractionPosition(self, channelName: str, carrierName: str) -> float: ...
    def SetToolCarrierZRetractionPosition(self, channelName: str, carrierName: str, newZPosition: float) -> None: ...
    def GetMdynamics(self) -> SIM.MachineToolConfiguration.MdynamicsTypes: ...
    def SetMdynamics(self, newMDynamicsValue: SIM.MachineToolConfiguration.MdynamicsTypes) -> None: ...
    def GetToolRadiusCompensation(self) -> bool: ...
    def SetToolRadiusCompensation(self, newCompensationValue: bool) -> None: ...
    def GetResolutionMm(self) -> float: ...
    def SetResolutionMm(self, newResolutionValue: float) -> None: ...
    def GetResolutionDeg(self) -> float: ...
    def SetResolutionDeg(self, newResolutionValue: float) -> None: ...
    def GetControllerLanguage(self) -> str: ...
    def SetControllerLanguage(self, newLanguage: str) -> None: ...
    def GetControllerVersion(self) -> str: ...
    def SetControllerVersion(self, newVersion: str) -> None: ...
    def GetArchiveControllerType(self) -> int: ...
    def SetArchiveControllerType(self, newArchiveControllerType: int) -> None: ...
    def GetArchiveControllerVersion(self) -> str: ...
    def SetArchiveControllerVersion(self, newArchiveControllerVersion: str) -> None: ...
    def GetUsedUnit(self) -> int: ...
    def SetUsedUnit(self, newUsedUnit: int) -> None: ...
    def GetCircularPrecision(self, channelName: str) -> float: ...
    def SetCircularPrecision(self, channelName: str, newCircularPrecision: float) -> None: ...
    def GetCircularPrecisionFactor(self, channelName: str) -> float: ...
    def SetCircularPrecisionFactor(self, channelName: str, newCircularPrecisionFactor: float) -> None: ...
    def GetDiameterGeoAxisName(self, channelName: str) -> str: ...
    def SetDiameterGeoAxisName(self, channelName: str, newDiameterMode: str) -> None: ...
    @property
    def ControllerLine(self) -> SIM.MachineToolConfiguration.ControllerLines: ...
    @ControllerLine.setter
    def ControllerLine(self, value: SIM.MachineToolConfiguration.ControllerLines) -> None: ...
    @property
    def ControllerType(self) -> str: ...
    @ControllerType.setter
    def ControllerType(self, value: str) -> None: ...
    @property
    def CycleTime(self) -> float: ...
    @CycleTime.setter
    def CycleTime(self, value: float) -> None: ...
    @property
    def MachineName(self) -> str: ...
    @MachineName.setter
    def MachineName(self, value: str) -> None: ...
    @property
    def MachineVendor(self) -> str: ...
    @MachineVendor.setter
    def MachineVendor(self, value: str) -> None: ...
    @property
    def ToolCarrierName(self) -> str: ...
    @ToolCarrierName.setter
    def ToolCarrierName(self, value: str) -> None: ...


    class UnitTypes(enum.Enum):
        Mm= 0
        In= 1
    

    class TechnologyTypes(enum.Enum):
        Mill= 0
        Turn= 1
        Millturn= 2
        None_= 3
    

    class SwivelingTypes(enum.Enum):
        Cycle800= 0
        Transarot= 1
    

    class PlaneTypes(enum.Enum):
        Operator= 0
        G17= 1
        G18= 2
        G19= 3
    

    class MdynamicsTypes(enum.Enum):
        Fiveaxmill= 0
    

    class ControllerLines(enum.Enum):
        Solutionline= 0
        Powerline= 1
    

class MachineLibraryBuilder(Builder):
    def __init__(self) -> None: ...
    def EditMachineLibrary(self, machineName: str, attName: str, value: str) -> None: ...
    def InsertEntryToMachineLibrary(self, selectedMachineName: str) -> str: ...
    def RemoveEntryFromMachineLibrary(self, machineName: str) -> None: ...
    def GetAllMachineNames(self) -> str: ...
    def GetAllAttributeNames(self) -> str: ...
    def GetValue(self, machineName: str, attName: str) -> str: ...


class MachineKitBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def OutputDirectory(self) -> str: ...
    @OutputDirectory.setter
    def OutputDirectory(self, value: str) -> None: ...


class LoadSnapshotBuilder(Builder):
    def __init__(self) -> None: ...
    def GetSnapshot(self, snapshotName: str, setupName: str) -> SIM.Snapshot: ...
    def SetExternalSnapshotSelection(self, snapshotTags: typing.List[SIM.Snapshot], sourceComps: str) -> None: ...
    def GetExternalSnapshots(self) -> typing.List[SIM.Snapshot]: ...
    @property
    def ExternalReference(self) -> str: ...
    @ExternalReference.setter
    def ExternalReference(self, value: str) -> None: ...
    @property
    def RunToSimTime(self) -> bool: ...
    @RunToSimTime.setter
    def RunToSimTime(self, value: bool) -> None: ...
    @property
    def Snapshot(self) -> SIM.Snapshot: ...
    @Snapshot.setter
    def Snapshot(self, value: SIM.Snapshot) -> None: ...


class KinematicSinumerikCaBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def DetailLevel(self) -> int: ...
    @DetailLevel.setter
    def DetailLevel(self, value: int) -> None: ...
    @property
    def MagazineIndex(self) -> int: ...
    @MagazineIndex.setter
    def MagazineIndex(self, value: int) -> None: ...
    @property
    def MagazineLocationIndex(self) -> int: ...
    @MagazineLocationIndex.setter
    def MagazineLocationIndex(self, value: int) -> None: ...
    @property
    def PlcBit(self) -> int: ...
    @PlcBit.setter
    def PlcBit(self, value: int) -> None: ...
    @property
    def PlcInitState(self) -> SIM.KinematicSinumerikCaBuilder.PlcInitStateTypes: ...
    @PlcInitState.setter
    def PlcInitState(self, value: SIM.KinematicSinumerikCaBuilder.PlcInitStateTypes) -> None: ...
    @property
    def PlcUsage(self) -> SIM.KinematicSinumerikCaBuilder.PlcUsageTypes: ...
    @PlcUsage.setter
    def PlcUsage(self, value: SIM.KinematicSinumerikCaBuilder.PlcUsageTypes) -> None: ...
    @property
    def TOIndex(self) -> int: ...
    @TOIndex.setter
    def TOIndex(self, value: int) -> None: ...


    class PlcUsageTypes(enum.Enum):
        CollisionCheck= 0
        Visualize= 1
        All= 2
    

    class PlcInitStateTypes(enum.Enum):
        Active= 0
        Inactive= 1
        Preselect= 2
    

class KinematicModel(NXObject):
    def __init__(self) -> None: ...
    def FindMachineAxis(self, name: str) -> SIM.KinematicAxis: ...
    def SetMachineAxisValue(self, axis: SIM.KinematicAxis, value: float) -> None: ...
    def UpdateMachineDisplay(self) -> None: ...


class KinematicJunctionBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[SIM.KinematicJunctionBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: SIM.KinematicJunctionBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: SIM.KinematicJunctionBuilder) -> int: ...
    def FindItem(self, index: int) -> SIM.KinematicJunctionBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: SIM.KinematicJunctionBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: SIM.KinematicJunctionBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[SIM.KinematicJunctionBuilder]: ...
    def SetContents(self, objects: typing.List[SIM.KinematicJunctionBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: SIM.KinematicJunctionBuilder, object2: SIM.KinematicJunctionBuilder) -> None: ...
    def Insert(self, location: int, object: SIM.KinematicJunctionBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class KinematicJunctionBuilder(Builder):
    def __init__(self) -> None: ...
    def CreateDefaultCsys(self) -> CartesianCoordinateSystem: ...
    def CreateTooltipCsys(self) -> CartesianCoordinateSystem: ...
    def IsMachineZero(self) -> bool: ...
    def IsToolMount(self) -> bool: ...
    def IsToolTip(self) -> bool: ...
    @property
    def Classification(self) -> SIM.KinematicJunctionBuilder.SystemClass: ...
    @Classification.setter
    def Classification(self, value: SIM.KinematicJunctionBuilder.SystemClass) -> None: ...
    @property
    def Csys(self) -> CartesianCoordinateSystem: ...
    @Csys.setter
    def Csys(self, value: CartesianCoordinateSystem) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...


    class SystemClass(enum.Enum):
        None_= 0
        Mount= 1
        MachineZero= 2
        ToolZero= 3
        ToolTip= 4
        LatheWpZx= 5
        LatheWpXy= 6
        RobotBase= 7
        RobotFlange= 8
        PositionerBase= 9
        PositionerTool= 10
    

class KinematicJunction(NXObject):
    def __init__(self) -> None: ...
    @property
    def Matrix(self) -> Matrix3x3: ...
    @Matrix.setter
    def Matrix(self, value: Matrix3x3) -> None: ...
    @property
    def Origin(self) -> Vector3d: ...
    @Origin.setter
    def Origin(self, value: Vector3d) -> None: ...


class KinematicImportMcfBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def IgnoreLimits(self) -> bool: ...
    @IgnoreLimits.setter
    def IgnoreLimits(self, value: bool) -> None: ...
    @property
    def McfPath(self) -> str: ...
    @McfPath.setter
    def McfPath(self, value: str) -> None: ...
    @property
    def ReplaceChannel(self) -> bool: ...
    @ReplaceChannel.setter
    def ReplaceChannel(self, value: bool) -> None: ...


class KinematicConfigurator(NXObject):
    def __init__(self) -> None: ...
    def CreateJunctionBuilder(self, parent: SIM.KinematicComponent, jct: SIM.KinematicJunction) -> SIM.KinematicJunctionBuilder: ...
    def CreateAxisBuilder(self, parent: SIM.KinematicComponent, jct: SIM.KinematicJunction, axis: SIM.KinematicAxis) -> SIM.KinematicAxisBuilder: ...
    def SetName(self, name: str) -> None: ...
    def GetName(self) -> str: ...
    def AddUserClassification(self, userClass: str) -> None: ...
    def DeleteUserClassification(self, userClass: str) -> None: ...
    def RenameUserClassification(self, oldName: str, newName: str) -> None: ...
    def GetUserClassifications(self, uClasses: str) -> None: ...
    def AddHoldingSystem(self, holdSys: str) -> None: ...
    def DeleteHoldingSystem(self, holdSys: str) -> None: ...
    def DeleteAllHoldingSystems(self) -> None: ...
    def RenameHoldingSystem(self, oldName: str, newName: str) -> None: ...
    def GetHoldingSystems(self, holdSys: str) -> None: ...
    def AddChannel(self, channel: str) -> None: ...
    def DeleteChannel(self, channel: str) -> None: ...
    def DeleteAllChannels(self) -> None: ...
    def RenameChannel(self, oldName: str, newName: str) -> None: ...
    def GetChannels(self, channels: str) -> None: ...
    def CreateSpinningClone(self, source: SIM.KinematicComponent, combine: bool) -> SIM.KinematicComponent: ...
    @typing.overload
    def FindComponentsBySystemClass(self, sysclass: int, comps: typing.List[SIM.KinematicComponent]) -> None: ...
    @typing.overload
    def FindComponentsBySystemClass(self, sysclass: SIM.KinematicComponentBuilder.SystemClass, comps: typing.List[SIM.KinematicComponent]) -> None: ...
    @typing.overload
    def FindJunction(self, name: str) -> SIM.KinematicJunction: ...
    @typing.overload
    def FindJunction(self, csys: NXObject) -> SIM.KinematicJunction: ...
    def FindAxis(self, name: str, pComp: SIM.KinematicComponent, pJct: SIM.KinematicJunction) -> SIM.KinematicAxis: ...
    def IsAxisAssignedToChannel(self, axisName: str, channelName: str) -> bool: ...
    def FindParentComponent(self, comp: SIM.KinematicComponent) -> SIM.KinematicComponent: ...
    def FindOwnerOfJunction(self, jct: SIM.KinematicJunction) -> SIM.KinematicComponent: ...
    def DeleteModel(self) -> None: ...
    def ExportModel(self, path: str) -> None: ...
    def ImportModel(self, path: str) -> None: ...
    def ImportMachineSpecificData(self, path: str) -> None: ...
    def EncryptModel(self, soldToIDs: str, expirationDate: str) -> None: ...
    def DeleteComponent(self, comp: SIM.KinematicComponent) -> None: ...
    def DeleteJunction(self, jct: SIM.KinematicJunction) -> None: ...
    def DeleteAxis(self, axis: SIM.KinematicAxis) -> None: ...
    def InsertRootComponent(self, newRoot: SIM.KinematicComponent) -> None: ...
    def DeleteRootComponent(self, oldRoot: SIM.KinematicComponent) -> None: ...
    def GetJunctions(self, junctions: typing.List[SIM.KinematicJunction]) -> None: ...
    def GetJunctionNames(self, junctions: str) -> None: ...
    def GetAxes(self, axes: typing.List[SIM.KinematicAxis]) -> None: ...
    def GetAxisNames(self, axes: str) -> None: ...
    def CreateSimDebugBuilder(self) -> SIM.SimDebugBuilder: ...
    def CreateNcChannelSelectionData(self) -> SIM.NcChannelSelectionData: ...
    @typing.overload
    def CreateIsvControlPanelBuilder(self, driverType: SIM.IsvControlPanelBuilder.VisualizationType, objects: typing.List[CAM.CAMObject]) -> SIM.IsvControlPanelBuilder: ...
    @typing.overload
    def CreateIsvControlPanelBuilder(self, driverType: SIM.IsvControlPanelBuilder.VisualizationType, filename: str) -> SIM.IsvControlPanelBuilder: ...
    @typing.overload
    def CreateIsvControlPanelBuilder(self, driverType: SIM.IsvControlPanelBuilder.VisualizationType, channelData: SIM.NcChannelSelectionData) -> SIM.IsvControlPanelBuilder: ...
    def CreateSimulationOptionsBuilder(self, dialogType: CAM.SimulationOptionsBuilder.DialogType) -> CAM.SimulationOptionsBuilder: ...
    def CreateCollisionPairBuilder(self) -> CAM.CollisionPairBuilder: ...
    def CreateKinematicSinumerikCaBuilder(self, comp: SIM.KinematicComponent) -> SIM.KinematicSinumerikCaBuilder: ...
    def CreateSinumerikCaSimplifyBodiesBuilder(self) -> SIM.SinumerikCaSimplifyBodiesBuilder: ...
    def CreateSinumerikCaExportBuilder(self) -> SIM.SinumerikCaExportBuilder: ...
    def CreateSinumerikCaFacetBuilder(self) -> SIM.SinumerikCaFacetBuilder: ...
    def CreateSinumerikCaPlaceholderBuilder(self) -> SIM.SinumerikCaPlaceholderBuilder: ...
    def CreateConvertFromMcdBuilder(self) -> CAM.ConvertFromMCDBuilder: ...
    def DefineKinematicChains(self) -> SIM.KinematicChainConfiguration: ...
    def CreateKinematicChain(self) -> SIM.KinematicChain: ...
    def CreateChannelConfigurationBuilder(self) -> SIM.KinematicChannelConfigurationBuilder: ...
    def CreateKinematicChannelBuilder(self) -> SIM.KinematicChannelBuilder: ...
    def CreateImportMcfBuilder(self) -> SIM.KinematicImportMcfBuilder: ...
    def CreateArchiveImportBuilder(self) -> SIM.ArchiveImportBuilder: ...
    def CreateMachineToolConfigurationBuilder(self) -> SIM.MachineToolConfiguration: ...
    def ImportNcArchive(self, ncFileName: str, printReport: bool) -> None: ...
    def CopyKinematicModel(self) -> SIM.KinematicModel: ...
    def DeleteKinematicModel(self, kimModel: SIM.KinematicModel) -> None: ...
    def CreateMachineLibraryBuilder(self) -> SIM.MachineLibraryBuilder: ...
    def CreateMachineKitBuilder(self) -> SIM.MachineKitBuilder: ...
    def CreateNcProgramManagerBuilder(self) -> SIM.NcProgramManagerBuilder: ...
    def ExportMachineKitBuilder(self, machineName: str) -> SIM.ExportMachineKitBuilder: ...
    def ImportMachineKitBuilder(self, kitPath: str) -> SIM.ImportMachineKitBuilder: ...
    def CreateSimulationSavesnapshotBuilder(self) -> SIM.SaveSnapshotBuilder: ...
    def CreateSimulationLoadsnapshotBuilder(self) -> SIM.LoadSnapshotBuilder: ...
    def CreateSmkWizardBuilder(self) -> SIM.SmkWizardBuilder: ...
    def CreateSmkMachineKitEditorBuilder(self) -> SIM.SmkMachineKitEditorBuilder: ...
    def CreateSmkMachineKitCreationPostBuilder(self) -> SIM.PostConfigurator.CreationPostBuilder: ...
    def CreateSmkDebugBuilder(self) -> SIM.SmkDebugBuilder: ...
    @property
    def ComponentCollection(self) -> SIM.KinematicComponentCollection: ...
    @ComponentCollection.setter
    def ComponentCollection(self, value: SIM.KinematicComponentCollection) -> None: ...
    @property
    def IsvControlPanelBuilder(self) -> SIM.IsvControlPanelBuilder: ...
    @IsvControlPanelBuilder.setter
    def IsvControlPanelBuilder(self, value: SIM.IsvControlPanelBuilder) -> None: ...


    class UniteTypes(enum.Enum):
        Create= 0
        Unite= 1
    

class KinematicComponentCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[SIM.KinematicComponent]: ...
    @typing.overload
    def __init__(self, owner: SIM.KinematicConfigurator) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, sid: str) -> SIM.KinematicComponent: ...
    def CreateComponentBuilder(self, parent: SIM.KinematicComponent, comp: SIM.KinematicComponent) -> SIM.KinematicComponentBuilder: ...
    def CreateMachineBaseComponentBuilder(self, machine: SIM.KinematicComponent) -> SIM.KinematicComponentBuilder: ...
    def CreateToolBaseComponentBuilder(self, tool: SIM.KinematicComponent) -> SIM.KinematicComponentBuilder: ...
    def CreateHeadBaseComponentBuilder(self, head: SIM.KinematicComponent) -> SIM.KinematicComponentBuilder: ...
    def CreateFacingHeadBaseComponentBuilder(self, head: SIM.KinematicComponent) -> SIM.KinematicComponentBuilder: ...
    def Tag(self) -> Tag: ...



class KinematicComponentBuilder(Builder):
    def __init__(self) -> None: ...
    def SetGeometries(self, geos: typing.List[NXObject]) -> None: ...
    def GetGeometries(self, geos: typing.List[NXObject]) -> None: ...
    def DeleteAllGeometries(self) -> None: ...
    def AddGeometry(self, geo: NXObject) -> None: ...
    def DeleteGeometry(self, geo: NXObject) -> None: ...
    def GetSaveIpw(self) -> bool: ...
    def SetSaveIpw(self, saveIpw: bool) -> None: ...
    def AddSystemClass(self, sysClass: SIM.KinematicComponentBuilder.SystemClass) -> None: ...
    def DeleteSystemClass(self, sysClasses: SIM.KinematicComponentBuilder.SystemClass) -> None: ...
    def GetSystemClasses(self, sysClasses: typing.List[SIM.KinematicComponentBuilder.SystemClass]) -> None: ...
    def DeleteAllSystemClasses(self) -> None: ...
    def IsOfSystemClass(self, sysClass: SIM.KinematicComponentBuilder.SystemClass) -> bool: ...
    def AddUserClassName(self, uclass: str) -> None: ...
    def DeleteUserClassName(self, uclass: str) -> None: ...
    def GetUserClassNames(self) -> str: ...
    def AddChannelName(self, channel: str) -> None: ...
    def DeleteChannelName(self, channel: str) -> None: ...
    def GetChannelNames(self) -> str: ...
    def AddHoldingSystem(self, holdSys: str) -> None: ...
    def DeleteHoldingSystem(self, holdSys: str) -> None: ...
    def GetHoldingSystems(self) -> str: ...
    def RenameUserClass(self, oldName: str, newName: str) -> None: ...
    def RenameHoldingSystem(self, oldName: str, newName: str) -> None: ...
    def RenameChannelName(self, oldName: str, newName: str) -> None: ...
    @property
    def AdjustRegister(self) -> int: ...
    @AdjustRegister.setter
    def AdjustRegister(self, value: int) -> None: ...
    @property
    def AdjustRegisterType(self) -> SIM.KinematicComponentBuilder.RegisterTypes: ...
    @AdjustRegisterType.setter
    def AdjustRegisterType(self, value: SIM.KinematicComponentBuilder.RegisterTypes) -> None: ...
    @property
    def CutcomRegister(self) -> int: ...
    @CutcomRegister.setter
    def CutcomRegister(self, value: int) -> None: ...
    @property
    def CutcomRegisterType(self) -> SIM.KinematicComponentBuilder.RegisterTypes: ...
    @CutcomRegisterType.setter
    def CutcomRegisterType(self, value: SIM.KinematicComponentBuilder.RegisterTypes) -> None: ...
    @property
    def CutterId(self) -> str: ...
    @CutterId.setter
    def CutterId(self, value: str) -> None: ...
    @property
    def DeviceId(self) -> str: ...
    @DeviceId.setter
    def DeviceId(self, value: str) -> None: ...
    @property
    def HolderId(self) -> int: ...
    @HolderId.setter
    def HolderId(self, value: int) -> None: ...
    @property
    def HolderIdString(self) -> str: ...
    @HolderIdString.setter
    def HolderIdString(self, value: str) -> None: ...
    @property
    def JunctionList(self) -> SIM.KinematicJunctionBuilderList: ...
    @JunctionList.setter
    def JunctionList(self, value: SIM.KinematicJunctionBuilderList) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def NumberOfTools(self) -> int: ...
    @NumberOfTools.setter
    def NumberOfTools(self, value: int) -> None: ...
    @property
    def WorkPositionAngle(self) -> float: ...
    @WorkPositionAngle.setter
    def WorkPositionAngle(self, value: float) -> None: ...
    @property
    def WorkPositionAngleType(self) -> SIM.KinematicComponentBuilder.WorkPositionAngleTypes: ...
    @WorkPositionAngleType.setter
    def WorkPositionAngleType(self, value: SIM.KinematicComponentBuilder.WorkPositionAngleTypes) -> None: ...


    class WorkPositionAngleTypes(enum.Enum):
        None_= 0
        SpecifyAngle= 1
    

    class SystemClass(enum.Enum):
        Machine= 0
        Tool= 1
        Turret= 2
        Pocket= 3
        Temporary= 4
        Part= 5
        Workpiece= 6
        SetupElement= 7
        Basic= 8
        LatheSpindle= 9
        PocketOnHead= 10
        ToolCutting= 11
        Spinning= 12
        TempSpinning= 13
        Head= 14
        RobotMountableComponent= 15
        RobotPickAndPlaceComponent= 16
        ToolNonCutting= 17
        FacingHead= 18
        AdditiveMaterial= 19
    

    class RegisterTypes(enum.Enum):
        SameAsPocketId= 0
        Specify= 1
    

class KinematicComponent(NXObject):
    def __init__(self) -> None: ...
    def InsertComponent(self, newChild: SIM.KinematicComponent) -> None: ...
    def DeleteComponent(self, oldChild: SIM.KinematicComponent) -> None: ...
    def InsertJunction(self, junction: SIM.KinematicJunction) -> None: ...
    def DeleteCaConfigProperties(self) -> None: ...
    def GetJunctions(self, junctions: typing.List[SIM.KinematicJunction]) -> None: ...
    def GetAxis(self) -> SIM.KinematicAxis: ...


class KinematicChannelConfigurationBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def KinematicChannels(self) -> SIM.KinematicChannelBuilderList: ...
    @KinematicChannels.setter
    def KinematicChannels(self, value: SIM.KinematicChannelBuilderList) -> None: ...


class KinematicChannelBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[SIM.KinematicChannelBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: SIM.KinematicChannelBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: SIM.KinematicChannelBuilder) -> int: ...
    def FindItem(self, index: int) -> SIM.KinematicChannelBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: SIM.KinematicChannelBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: SIM.KinematicChannelBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[SIM.KinematicChannelBuilder]: ...
    def SetContents(self, objects: typing.List[SIM.KinematicChannelBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: SIM.KinematicChannelBuilder, object2: SIM.KinematicChannelBuilder) -> None: ...
    def Insert(self, location: int, object: SIM.KinematicChannelBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class KinematicChannelBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def GetAssignedAxes(self, assignedAxes: str) -> None: ...
    def SetAssignedAxes(self, assignedAxes: str) -> None: ...
    def SetAssignedAxis(self, axisName: str) -> None: ...
    def SetUnassignedAxis(self, axisName: str) -> None: ...
    def GetReferencedSpindles(self, refSpindles: str) -> None: ...
    def SetReferencedSpindles(self, refSpindles: str) -> None: ...
    def SetReferencedSpindle(self, spindleName: str) -> None: ...
    def SetUnreferencedSpindle(self, spindleName: str) -> None: ...
    def SetReferencedDevice(self, deviceName: str) -> None: ...
    def SetUnreferencedDevice(self, deviceName: str) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def GeometryAxisX(self) -> str: ...
    @GeometryAxisX.setter
    def GeometryAxisX(self, value: str) -> None: ...
    @property
    def GeometryAxisY(self) -> str: ...
    @GeometryAxisY.setter
    def GeometryAxisY(self, value: str) -> None: ...
    @property
    def GeometryAxisZ(self) -> str: ...
    @GeometryAxisZ.setter
    def GeometryAxisZ(self, value: str) -> None: ...
    @property
    def MainSpindle(self) -> str: ...
    @MainSpindle.setter
    def MainSpindle(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...


class KinematicChainList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[SIM.KinematicChain]) -> None: ...
    @typing.overload
    def Append(self, object: SIM.KinematicChain) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: SIM.KinematicChain) -> int: ...
    def FindItem(self, index: int) -> SIM.KinematicChain: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: SIM.KinematicChain) -> None: ...
    @typing.overload
    def Erase(self, obj: SIM.KinematicChain, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[SIM.KinematicChain]: ...
    def SetContents(self, objects: typing.List[SIM.KinematicChain]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: SIM.KinematicChain, object2: SIM.KinematicChain) -> None: ...
    def Insert(self, location: int, object: SIM.KinematicChain) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class KinematicChainConfiguration(Builder):
    def __init__(self) -> None: ...
    @property
    def List(self) -> SIM.KinematicChainList: ...
    @List.setter
    def List(self, value: SIM.KinematicChainList) -> None: ...


class KinematicChain(Builder):
    def __init__(self) -> None: ...
    @property
    def Axial(self) -> str: ...
    @Axial.setter
    def Axial(self, value: str) -> None: ...
    @property
    def CoordinateAxes(self) -> str: ...
    @CoordinateAxes.setter
    def CoordinateAxes(self, value: str) -> None: ...
    @property
    def CoordinatePlane(self) -> SIM.KinematicChain.CoordinatePlaneTypes: ...
    @CoordinatePlane.setter
    def CoordinatePlane(self, value: SIM.KinematicChain.CoordinatePlaneTypes) -> None: ...
    @property
    def Device(self) -> str: ...
    @Device.setter
    def Device(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Radial(self) -> str: ...
    @Radial.setter
    def Radial(self, value: str) -> None: ...
    @property
    def ReferencePointJunction(self) -> str: ...
    @ReferencePointJunction.setter
    def ReferencePointJunction(self, value: str) -> None: ...
    @property
    def Rotary1(self) -> str: ...
    @Rotary1.setter
    def Rotary1(self, value: str) -> None: ...
    @property
    def Rotary2(self) -> str: ...
    @Rotary2.setter
    def Rotary2(self, value: str) -> None: ...
    @property
    def Rotary3(self) -> str: ...
    @Rotary3.setter
    def Rotary3(self, value: str) -> None: ...
    @property
    def Rotary4(self) -> str: ...
    @Rotary4.setter
    def Rotary4(self, value: str) -> None: ...
    @property
    def Rotary5(self) -> str: ...
    @Rotary5.setter
    def Rotary5(self, value: str) -> None: ...
    @property
    def Rotary6(self) -> str: ...
    @Rotary6.setter
    def Rotary6(self, value: str) -> None: ...
    @property
    def Setup(self) -> str: ...
    @Setup.setter
    def Setup(self, value: str) -> None: ...
    @property
    def Type(self) -> SIM.KinematicChain.Types: ...
    @Type.setter
    def Type(self, value: SIM.KinematicChain.Types) -> None: ...
    @property
    def X(self) -> str: ...
    @X.setter
    def X(self, value: str) -> None: ...
    @property
    def Y(self) -> str: ...
    @Y.setter
    def Y(self, value: str) -> None: ...
    @property
    def Z(self) -> str: ...
    @Z.setter
    def Z(self, value: str) -> None: ...


    class Types(enum.Enum):
        Unknown= -1
        Milling= 0
        Turning= 1
        Polar= 2
        Robot= 3
    

    class CoordinatePlaneTypes(enum.Enum):
        Zx= 0
        Xy= 1
    

class KinematicAxisBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CoarsePrecision(self) -> float: ...
    @CoarsePrecision.setter
    def CoarsePrecision(self, value: float) -> None: ...
    @property
    def Direction(self) -> SIM.KinematicAxisBuilder.AxisDirectionType: ...
    @Direction.setter
    def Direction(self, value: SIM.KinematicAxisBuilder.AxisDirectionType) -> None: ...
    @property
    def FinePrecision(self) -> float: ...
    @FinePrecision.setter
    def FinePrecision(self, value: float) -> None: ...
    @property
    def InitialValue(self) -> float: ...
    @InitialValue.setter
    def InitialValue(self, value: float) -> None: ...
    @property
    def JerkLimit(self) -> float: ...
    @JerkLimit.setter
    def JerkLimit(self, value: float) -> None: ...
    @property
    def JumpVelocity(self) -> float: ...
    @JumpVelocity.setter
    def JumpVelocity(self, value: float) -> None: ...
    @property
    def Junction(self) -> SIM.KinematicJunction: ...
    @Junction.setter
    def Junction(self, value: SIM.KinematicJunction) -> None: ...
    @property
    def Kv(self) -> float: ...
    @Kv.setter
    def Kv(self, value: float) -> None: ...
    @property
    def Limit(self) -> bool: ...
    @Limit.setter
    def Limit(self, value: bool) -> None: ...
    @property
    def LowerLimit(self) -> float: ...
    @LowerLimit.setter
    def LowerLimit(self, value: float) -> None: ...
    @property
    def LowerSoftLimit(self) -> float: ...
    @LowerSoftLimit.setter
    def LowerSoftLimit(self, value: float) -> None: ...
    @property
    def MaxAcceleration(self) -> float: ...
    @MaxAcceleration.setter
    def MaxAcceleration(self, value: float) -> None: ...
    @property
    def MaxDeceleration(self) -> float: ...
    @MaxDeceleration.setter
    def MaxDeceleration(self, value: float) -> None: ...
    @property
    def MaximumVelocity(self) -> float: ...
    @MaximumVelocity.setter
    def MaximumVelocity(self, value: float) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Number(self) -> int: ...
    @Number.setter
    def Number(self, value: int) -> None: ...
    @property
    def Type(self) -> SIM.KinematicAxisBuilder.AxisMotionType: ...
    @Type.setter
    def Type(self, value: SIM.KinematicAxisBuilder.AxisMotionType) -> None: ...
    @property
    def UpperLimit(self) -> float: ...
    @UpperLimit.setter
    def UpperLimit(self, value: float) -> None: ...
    @property
    def UpperSoftLimit(self) -> float: ...
    @UpperSoftLimit.setter
    def UpperSoftLimit(self, value: float) -> None: ...


    class AxisMotionType(enum.Enum):
        LinearNcAxis= 0
        RotaryNcAxis= 1
        Linear= 2
        Rotary= 3
        RotaryUnlimitedNcAxis= 4
        SpindleNcAxis= 5
        RotaryUnlimited= 6
        Spindle= 7
    

    class AxisDirectionType(enum.Enum):
        PositiveX= 0
        NegativeX= 1
        PositiveY= 2
        NegativeY= 3
        PositiveZ= 4
        NegativeZ= 5
    

class KinematicAxis(NXObject):
    def __init__(self) -> None: ...


class IsvControlPanelBuilder(Builder):
    def __init__(self) -> None: ...
    def GetVisualization(self) -> SIM.IsvControlPanelBuilder.VisualizationType: ...
    def SetVisualization(self, type: SIM.IsvControlPanelBuilder.VisualizationType) -> None: ...
    def GetShow3dMaterialRemoval(self) -> bool: ...
    def SetShow3dMaterialRemoval(self, state: bool) -> int: ...
    def GetShowToolPath(self) -> bool: ...
    def SetShowToolPath(self, state: bool) -> None: ...
    def GetSingleStep(self) -> SIM.IsvControlPanelBuilder.SingleStepType: ...
    def SetSingleStep(self, type: SIM.IsvControlPanelBuilder.SingleStepType) -> None: ...
    def GetSingleStepMode(self) -> SIM.IsvControlPanelBuilder.SingleStepModeType: ...
    def SetSingleStepMode(self, type: SIM.IsvControlPanelBuilder.SingleStepModeType) -> None: ...
    def PlayToMachineTime(self, machineTime: str) -> None: ...
    def PlayForward(self) -> None: ...
    def PlayBackward(self) -> None: ...
    def SingleStepForward(self) -> None: ...
    def AddIsInHistoryBuffer(self, handler: SIM.IsvControlPanelBuilder.IsInHistoryBufferCb) -> int: ...
    def RemoveIsInHistoryBuffer(self, handlerId: int) -> bool: ...
    def AddVncStatus(self, handler: SIM.IsvControlPanelBuilder.VncStatusCb) -> int: ...
    def RemoveVncStatus(self, handlerId: int) -> bool: ...
    def AddSimStart(self, handler: SIM.IsvControlPanelBuilder.SimStartCb) -> int: ...
    def RemoveSimStart(self, handlerId: int) -> bool: ...
    def AddSimStop(self, handler: SIM.IsvControlPanelBuilder.SimStopCb) -> int: ...
    def RemoveSimStop(self, handlerId: int) -> bool: ...
    def AddSimEnd(self, handler: SIM.IsvControlPanelBuilder.SimEndCb) -> int: ...
    def RemoveSimEnd(self, handlerId: int) -> bool: ...
    def SingleStepBackward(self) -> None: ...
    def StepToNextOperation(self) -> None: ...
    def StepToPreviousOperation(self) -> None: ...
    def SetSpeed(self, simSpeed: int) -> None: ...
    def JumpToMachineTime(self, machineTime: str) -> None: ...
    def JumpToDetailsLine(self, line: int) -> None: ...
    @typing.overload
    def JumpToNcProgramLine(self, line: int) -> None: ...
    @typing.overload
    def JumpToNcProgramLine(self, channelName: str, line: int) -> None: ...
    def SetCurrentProgramLine(self, channelName: str, line: int) -> None: ...
    def GetMachiningTimeAnalysisClock(self, channelName: str) -> SIM.TimeAnalysis: ...
    def ApplySimulationOptions(self) -> None: ...
    def ResetMachine(self) -> None: ...
    def GetDetailCount(self, type: SIM.IsvControlPanelBuilder.DetailType) -> int: ...
    def GetDetail(self, type: SIM.IsvControlPanelBuilder.DetailType, position: int, time: float, description: str, ncLine: int, programName: str, channelName: str) -> bool: ...
    @typing.overload
    def MachineControlResetNc(self) -> None: ...
    @typing.overload
    def MachineControlResetNc(self, channels: str) -> None: ...
    def MachineControlResetPart(self) -> None: ...
    def MachineControlResetMachine(self) -> None: ...
    @typing.overload
    def MachineControlClearAlarm(self) -> None: ...
    @typing.overload
    def MachineControlClearAlarm(self, channels: str) -> None: ...
    def MachineControlShowHmi(self) -> None: ...
    def MachineControlSingleBlockMode(self, enable: bool) -> None: ...
    def MachineControlDryRun(self, enable: bool) -> None: ...
    def MachineControlFeedRateOverride(self, value: int) -> None: ...
    def MachineControlSaveMachineData(self) -> None: ...
    def MachineControlResetMachineData(self) -> None: ...
    def Stop(self) -> None: ...
    def MachineControlGetFeedRateOverrideMaximumValue(self) -> int: ...
    def MachineControlGetCycleTime(self) -> int: ...
    def MachineControlWriteVariable(self, channelName: str, variableName: str, variableValue: str, variableType: str) -> bool: ...
    def MachineControlReadVariable(self, channelName: str, variableName: str, variableValue: str, variableType: str) -> bool: ...
    def MachineControlGetChannels(self) -> str: ...
    @typing.overload
    def MachineControlStopNc(self) -> None: ...
    @typing.overload
    def MachineControlStopNc(self, channels: str) -> None: ...
    @typing.overload
    def MachineControlStartNc(self) -> None: ...
    @typing.overload
    def MachineControlStartNc(self, channels: str) -> None: ...
    def MachineControlBootVnck(self) -> bool: ...
    def MachineControlShutdownVnck(self) -> None: ...
    def SaveSettingsToFile(self, filename: str) -> None: ...
    def ReadSettingsFromFile(self, filename: str) -> None: ...
    def GetPostprocessorFilename(self, definitionFilename: str) -> str: ...
    @typing.overload
    def ShowSnapshot(self, bRunToSimTime: bool, snapshot: SIM.Snapshot) -> None: ...
    @typing.overload
    def ShowSnapshot(self, bRunToSimTime: bool, sourceComp: str, snapshot: SIM.Snapshot) -> None: ...
    def GetCurrentProgram(self, channelName: str, stackLevel: int) -> SIM.NcProgram: ...
    def CheckProgramSyntax(self, programs: typing.List[SIM.NcProgram]) -> None: ...
    @property
    def ActiveChannel(self) -> str: ...
    @ActiveChannel.setter
    def ActiveChannel(self, value: str) -> None: ...
    @property
    def IsInHistoryBuffer(self) -> bool: ...
    @IsInHistoryBuffer.setter
    def IsInHistoryBuffer(self, value: bool) -> None: ...
    @property
    def MachineConfiguratorFilename(self) -> str: ...
    @MachineConfiguratorFilename.setter
    def MachineConfiguratorFilename(self, value: str) -> None: ...
    @property
    def MachineTime(self) -> str: ...
    @MachineTime.setter
    def MachineTime(self, value: str) -> None: ...
    @property
    def SimDebugBuilder(self) -> SIM.SimDebugBuilder: ...
    @SimDebugBuilder.setter
    def SimDebugBuilder(self, value: SIM.SimDebugBuilder) -> None: ...
    @property
    def SimulationLoadSnapshotBuilder(self) -> SIM.LoadSnapshotBuilder: ...
    @SimulationLoadSnapshotBuilder.setter
    def SimulationLoadSnapshotBuilder(self, value: SIM.LoadSnapshotBuilder) -> None: ...
    @property
    def SimulationOptionsBuilder(self) -> CAM.SimulationOptionsBuilder: ...
    @SimulationOptionsBuilder.setter
    def SimulationOptionsBuilder(self, value: CAM.SimulationOptionsBuilder) -> None: ...
    @property
    def SimulationSaveSnapshotBuilder(self) -> SIM.SaveSnapshotBuilder: ...
    @SimulationSaveSnapshotBuilder.setter
    def SimulationSaveSnapshotBuilder(self, value: SIM.SaveSnapshotBuilder) -> None: ...
    @property
    def VncStatus(self) -> SIM.IsvControlPanelBuilder.VncMode: ...
    @VncStatus.setter
    def VncStatus(self, value: SIM.IsvControlPanelBuilder.VncMode) -> None: ...


    

    class VncMode(enum.Enum):
        Error= -1
        Notconnected= 0
        Connected= 1
        Booted= 2
        Configured= 3
        Initialized= 4
        ProgramsLoaded= 5
        Reset= 6
        Stop= 7
        Start= 8
        Run= 9
    

    class VisualizationType(enum.Enum):
        MachineCodeSimulateCse= 0
        MachineCodeSimulateMtd= 1
        ToolPathSimulation= 2
    

    class SingleStepType(enum.Enum):
        Block= 0
        Move= 1
        Event= 2
    

    class SingleStepModeType(enum.Enum):
        StepIn= 0
        StepOver= 1
        StepOut= 2
        DisplayUpdate= 3
    

    

    

    

    

    class DetailType(enum.Enum):
        Info= 0
        Controller= 1
        Limit= 2
        Collision= 3
        Gouge= 4
        Singularity= 5
    

    

    

    

    

    

    

    

    

    

    

class ImportMachineKitBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def OutputDirectory(self) -> str: ...
    @OutputDirectory.setter
    def OutputDirectory(self, value: str) -> None: ...
    @property
    def PrintReport(self) -> bool: ...
    @PrintReport.setter
    def PrintReport(self, value: bool) -> None: ...


class ExportMachineKitBuilder(Builder):
    def __init__(self) -> None: ...
    def GetAllKitPaths(self) -> str: ...
    def AddKitFile(self, directory: str, file: str) -> None: ...
    def AddKitFolder(self, directory: str, folder: str) -> None: ...
    def AddKitDirectory(self, directory: str, subDirectory: str) -> None: ...
    def RenameKitDirectory(self, directory: str, newDirectoryName: str) -> None: ...
    def RemovePathInKit(self, directory: str) -> None: ...
    @property
    def KitName(self) -> str: ...
    @KitName.setter
    def KitName(self, value: str) -> None: ...
    @property
    def OutputDirectory(self) -> str: ...
    @OutputDirectory.setter
    def OutputDirectory(self, value: str) -> None: ...
    @property
    def PrintReport(self) -> bool: ...
    @PrintReport.setter
    def PrintReport(self, value: bool) -> None: ...


class Breakpoint(NXObject):
    def __init__(self) -> None: ...
    def Activate(self) -> None: ...
    def Deactivate(self) -> None: ...
    def Delete(self) -> None: ...
    @property
    def Condition(self) -> str: ...
    @Condition.setter
    def Condition(self, value: str) -> None: ...


class ArchiveImportBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...
    @property
    def ImportCollisionAvoidance(self) -> bool: ...
    @ImportCollisionAvoidance.setter
    def ImportCollisionAvoidance(self, value: bool) -> None: ...


