from ....NXOpen import *
from ...Diagramming import *

import typing
import enum

class ZeroDisplay(enum.Enum):
    Zero= 0
    Dash= 1
    Empty= 2


class TextDirection(enum.Enum):
    Horizontal= 0
    VerticalRightReading= 1
    VerticalLeftReading= 2


class TableSettingsBuilder(Diagramming.BaseTaggedObjectBuilder):
    def __init__(self) -> None: ...
    @property
    def AnchorLocation(self) -> Diagramming.Tables.AnchorLocation: ...
    @AnchorLocation.setter
    def AnchorLocation(self, value: Diagramming.Tables.AnchorLocation) -> None: ...
    @property
    def HeaderLocation(self) -> Diagramming.Tables.HeaderLocation: ...
    @HeaderLocation.setter
    def HeaderLocation(self, value: Diagramming.Tables.HeaderLocation) -> None: ...
    @property
    def HeaderOrientation(self) -> Diagramming.Tables.HeaderOrientation: ...
    @HeaderOrientation.setter
    def HeaderOrientation(self, value: Diagramming.Tables.HeaderOrientation) -> None: ...
    @property
    def ProtectedFlag(self) -> bool: ...
    @ProtectedFlag.setter
    def ProtectedFlag(self, value: bool) -> None: ...


class TableCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.Tables.Table]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateTableBuilder(self, table: Diagramming.Tables.Table) -> Diagramming.Tables.TableBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.Tables.Table: ...
    def Tag(self) -> Tag: ...



class TableBuilder(Diagramming.AnnotationBuilder):
    def __init__(self) -> None: ...
    def GetNumberOfColumns(self) -> int: ...
    def GetNumberOfHeaders(self) -> int: ...
    def GetNumberOfRows(self) -> int: ...
    def InsertHeaders(self, headerIndex: int, numHeaders: int) -> None: ...
    def InsertColumns(self, columnIndex: int, numColumns: int) -> None: ...
    def InsertRows(self, rowIndex: int, numRows: int) -> None: ...
    def RemoveHeaders(self, headerIndex: int, numHeaders: int) -> None: ...
    def RemoveColumns(self, columnIndex: int, numColumns: int) -> None: ...
    def RemoveRows(self, rowIndex: int, numRows: int) -> None: ...
    def GetHeaderCell(self, rowIndex: int, columnIndex: int) -> Diagramming.Tables.CellBuilder: ...
    def GetCell(self, rowIndex: int, columnIndex: int) -> Diagramming.Tables.CellBuilder: ...
    def GetHeader(self, headerIndex: int) -> Diagramming.Tables.CellRangeBuilder: ...
    def GetColumn(self, columnIndex: int) -> Diagramming.Tables.ColumnBuilder: ...
    def GetRow(self, rowIndex: int) -> Diagramming.Tables.RowBuilder: ...
    def GetFillColor(self, color: NXColor, opacity: float) -> None: ...
    def SetFillColor(self, color: NXColor, opacity: float) -> None: ...
    def MergeHeaderCells(self, topRow: int, leftColumn: int, bottomRow: int, rightColumn: int) -> None: ...
    def MergeCells(self, topRow: int, leftColumn: int, bottomRow: int, rightColumn: int) -> None: ...
    def UnMergeHeaderCell(self, rowIndex: int, columnIndex: int) -> None: ...
    def UnMergeCell(self, rowIndex: int, columnIndex: int) -> None: ...
    def Inherit(self, inheritOption: Diagramming.Tables.TableBuilder.InheritOption, annotation: Diagramming.Annotation) -> None: ...
    @property
    def BottomBorder(self) -> Diagramming.RenderingPropertiesBuilder: ...
    @BottomBorder.setter
    def BottomBorder(self, value: Diagramming.RenderingPropertiesBuilder) -> None: ...
    @property
    def CellSettingsBuilder(self) -> Diagramming.Tables.CellSettingsBuilder: ...
    @CellSettingsBuilder.setter
    def CellSettingsBuilder(self, value: Diagramming.Tables.CellSettingsBuilder) -> None: ...
    @property
    def ContinuationDataBuilder(self) -> Diagramming.Tables.ContinuationDataBuilder: ...
    @ContinuationDataBuilder.setter
    def ContinuationDataBuilder(self, value: Diagramming.Tables.ContinuationDataBuilder) -> None: ...
    @property
    def DefaultBottomBorder(self) -> Diagramming.RenderingPropertiesBuilder: ...
    @DefaultBottomBorder.setter
    def DefaultBottomBorder(self, value: Diagramming.RenderingPropertiesBuilder) -> None: ...
    @property
    def DefaultRightBorder(self) -> Diagramming.RenderingPropertiesBuilder: ...
    @DefaultRightBorder.setter
    def DefaultRightBorder(self, value: Diagramming.RenderingPropertiesBuilder) -> None: ...
    @property
    def InitialColumnWidth(self) -> float: ...
    @InitialColumnWidth.setter
    def InitialColumnWidth(self, value: float) -> None: ...
    @property
    def LeftBorder(self) -> Diagramming.RenderingPropertiesBuilder: ...
    @LeftBorder.setter
    def LeftBorder(self, value: Diagramming.RenderingPropertiesBuilder) -> None: ...
    @property
    def Locked(self) -> bool: ...
    @Locked.setter
    def Locked(self, value: bool) -> None: ...
    @property
    def RightBorder(self) -> Diagramming.RenderingPropertiesBuilder: ...
    @RightBorder.setter
    def RightBorder(self, value: Diagramming.RenderingPropertiesBuilder) -> None: ...
    @property
    def TableSettingsBuilder(self) -> Diagramming.Tables.TableSettingsBuilder: ...
    @TableSettingsBuilder.setter
    def TableSettingsBuilder(self, value: Diagramming.Tables.TableSettingsBuilder) -> None: ...
    @property
    def TopBorder(self) -> Diagramming.RenderingPropertiesBuilder: ...
    @TopBorder.setter
    def TopBorder(self, value: Diagramming.RenderingPropertiesBuilder) -> None: ...


    class InheritOption(enum.Enum):
        Preferences= 0
        CustomerDefaults= 1
        Selection= 2
    

class Table(Diagramming.Annotation):
    def __init__(self) -> None: ...
    def GetTitleBlock(self) -> Diagramming.TitleBlock: ...
    def RemoveTitleBlock(self) -> None: ...


class SizingMethod(enum.Enum):
    Auto= 0
    Fixed= 1


class SizedSymbol():
    @property
    def PaddingFromLastSymbol(self) -> float: ...
    @PaddingFromLastSymbol.setter
    def PaddingFromLastSymbol(self, value: float) -> None: ...
    @property
    def Symbol(self) -> TaggedObject: ...
    @Symbol.setter
    def Symbol(self, value: TaggedObject) -> None: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> None: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> None: ...
    def ToString(self) -> str: ...


class RowBuilder(Diagramming.Tables.CellRangeBuilder):
    def __init__(self) -> None: ...
    def SetHeight(self, size: float) -> None: ...


class OverflowBehavior(enum.Enum):
    Wrap= 0
    Truncate= 1
    OverflowBorder= 2
    ShrinkToFit= 3
    Suffix= 4


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class HeaderOrientation(enum.Enum):
    Vertical= 0
    Horizontal= 1


class HeaderLocation(enum.Enum):
    Start= 0
    End= 1


class ContinuationLocation(enum.Enum):
    Up= 0
    Down= 1
    Left= 2
    Right= 3
    NextSheet= 4


class ContinuationDataBuilder(Diagramming.BaseTaggedObjectBuilder):
    def __init__(self) -> None: ...
    @property
    def Location(self) -> Diagramming.Tables.ContinuationLocation: ...
    @Location.setter
    def Location(self, value: Diagramming.Tables.ContinuationLocation) -> None: ...
    @property
    def MaximumSize(self) -> float: ...
    @MaximumSize.setter
    def MaximumSize(self, value: float) -> None: ...
    @property
    def Spacing(self) -> float: ...
    @Spacing.setter
    def Spacing(self, value: float) -> None: ...


class ContentAlignment(enum.Enum):
    TopLeft= 0
    TopCenter= 1
    TopRight= 2
    MiddleLeft= 3
    MiddleCenter= 4
    MiddleRight= 5
    BottomLeft= 6
    BottomCenter= 7
    BottomRight= 8


class ColumnBuilder(Diagramming.Tables.CellRangeBuilder):
    def __init__(self) -> None: ...
    def SetWidth(self, size: float) -> None: ...


class CellSettingsBuilder(Diagramming.BaseTaggedObjectBuilder):
    def __init__(self) -> None: ...
    def GetContentTextStyle(self) -> Diagramming.TextStyleBuilder: ...
    @property
    def ContentAlignment(self) -> Diagramming.Tables.ContentAlignment: ...
    @ContentAlignment.setter
    def ContentAlignment(self, value: Diagramming.Tables.ContentAlignment) -> None: ...
    @property
    def FillColor(self) -> NXColor: ...
    @FillColor.setter
    def FillColor(self, value: NXColor) -> None: ...
    @property
    def FillOpacity(self) -> float: ...
    @FillOpacity.setter
    def FillOpacity(self, value: float) -> None: ...
    @property
    def OverflowBehavior(self) -> Diagramming.Tables.OverflowBehavior: ...
    @OverflowBehavior.setter
    def OverflowBehavior(self, value: Diagramming.Tables.OverflowBehavior) -> None: ...
    @property
    def TextDirection(self) -> Diagramming.Tables.TextDirection: ...
    @TextDirection.setter
    def TextDirection(self, value: Diagramming.Tables.TextDirection) -> None: ...
    @property
    def ZeroDisplay(self) -> Diagramming.Tables.ZeroDisplay: ...
    @ZeroDisplay.setter
    def ZeroDisplay(self, value: Diagramming.Tables.ZeroDisplay) -> None: ...


class CellRangeBuilder(Diagramming.BaseTaggedObjectBuilder):
    def __init__(self) -> None: ...
    @property
    def CanHide(self) -> bool: ...
    @CanHide.setter
    def CanHide(self, value: bool) -> None: ...
    @property
    def Hidden(self) -> bool: ...
    @Hidden.setter
    def Hidden(self, value: bool) -> None: ...
    @property
    def Size(self) -> float: ...
    @Size.setter
    def Size(self, value: float) -> None: ...
    @property
    def SizingMethod(self) -> Diagramming.Tables.SizingMethod: ...
    @SizingMethod.setter
    def SizingMethod(self, value: Diagramming.Tables.SizingMethod) -> None: ...


class CellBuilder(Diagramming.BaseTaggedObjectBuilder):
    def __init__(self) -> None: ...
    def GetCellSettings(self) -> Diagramming.Tables.CellSettingsBuilder: ...
    def SetImageFileLocation(self, fileName: str) -> None: ...
    def DeleteContent(self) -> None: ...
    def GetContent(self) -> typing.List[Diagramming.Tables.SizedSymbol]: ...
    def SetContent(self, symbols: typing.List[Diagramming.Tables.SizedSymbol]) -> None: ...
    def Inherit(self, inheritOption: Diagramming.Tables.CellBuilder.InheritOption, elementToInheritFrom: TaggedObject) -> None: ...
    @property
    def BottomBorder(self) -> Diagramming.RenderingPropertiesBuilder: ...
    @BottomBorder.setter
    def BottomBorder(self, value: Diagramming.RenderingPropertiesBuilder) -> None: ...
    @property
    def FormattedStringBuilder(self) -> Diagramming.FormattedStringBuilder: ...
    @FormattedStringBuilder.setter
    def FormattedStringBuilder(self, value: Diagramming.FormattedStringBuilder) -> None: ...
    @property
    def LeftBorder(self) -> Diagramming.RenderingPropertiesBuilder: ...
    @LeftBorder.setter
    def LeftBorder(self, value: Diagramming.RenderingPropertiesBuilder) -> None: ...
    @property
    def Locked(self) -> bool: ...
    @Locked.setter
    def Locked(self, value: bool) -> None: ...
    @property
    def Padding(self) -> float: ...
    @Padding.setter
    def Padding(self, value: float) -> None: ...
    @property
    def RightBorder(self) -> Diagramming.RenderingPropertiesBuilder: ...
    @RightBorder.setter
    def RightBorder(self, value: Diagramming.RenderingPropertiesBuilder) -> None: ...
    @property
    def Text(self) -> str: ...
    @Text.setter
    def Text(self, value: str) -> None: ...
    @property
    def TopBorder(self) -> Diagramming.RenderingPropertiesBuilder: ...
    @TopBorder.setter
    def TopBorder(self, value: Diagramming.RenderingPropertiesBuilder) -> None: ...


    class InheritOption(enum.Enum):
        Preferences= 0
        CustomerDefaults= 1
        Selection= 2
    

class AnchorLocation(enum.Enum):
    TopLeft= 0
    TopRight= 1
    BottomLeft= 2
    BottomRight= 3


class _SizedSymbol():
    @property
    def paddingFromLastSymbol(self) -> float: ...
    @paddingFromLastSymbol.setter
    def paddingFromLastSymbol(self, value: float) -> None: ...
    @property
    def symbol(self) -> Tag: ...
    @symbol.setter
    def symbol(self, value: Tag) -> None: ...
    @property
    def height(self) -> float: ...
    @height.setter
    def height(self, value: float) -> None: ...
    @property
    def width(self) -> float: ...
    @width.setter
    def width(self, value: float) -> None: ...


