from ...NXOpen import *

import typing
import enum

class RunBuilder(Builder):
    def __init__(self) -> None: ...
    def GetLogicalObject(self) -> PDM.LogicalObject: ...
    def AutoAssignAttributes(self, objects: typing.List[NXObject]) -> ErrorList: ...
    def AutoAssignAttributesWithNamingPattern(self, objects: typing.List[NXObject], properties: typing.List[NXObject]) -> ErrorList: ...
    def CreateAttributeTitleToNamingPatternMap(self, attributeTitles: str, titlePatterns: str) -> NXObject: ...
    @property
    def Discipline(self) -> str: ...
    @Discipline.setter
    def Discipline(self, value: str) -> None: ...
    @property
    def IsUnassigned(self) -> bool: ...
    @IsUnassigned.setter
    def IsUnassigned(self, value: bool) -> None: ...
    @property
    def LineTypePathId(self) -> str: ...
    @LineTypePathId.setter
    def LineTypePathId(self, value: str) -> None: ...
    @property
    def ObjectApplication(self) -> str: ...
    @ObjectApplication.setter
    def ObjectApplication(self, value: str) -> None: ...
    @property
    def PipeSpecPathId(self) -> str: ...
    @PipeSpecPathId.setter
    def PipeSpecPathId(self, value: str) -> None: ...


class Run(PDM.ElementGroup):
    def __init__(self) -> None: ...
    def ReparentBranch(self, destinationRun: PLAS.Run, oldbranch: PDM.OrderedElementGroup) -> PDM.OrderedElementGroup: ...
    def GetBranches(self, branches: typing.List[PDM.OrderedElementGroup]) -> None: ...


class PlasManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Part) -> None: ...
    def CreateRunBuilder(self, run: PLAS.Run) -> PLAS.RunBuilder: ...
    def CreateControlLoopBuilder(self, run: PLAS.Run) -> PLAS.ControlLoopBuilder: ...
    def Tag(self) -> Tag: ...

    @property
    def ActiveControlLoop(self) -> PLAS.Run: ...
    @ActiveControlLoop.setter
    def ActiveControlLoop(self, value: PLAS.Run) -> None: ...
    @property
    def ActiveRun(self) -> PLAS.Run: ...
    @ActiveRun.setter
    def ActiveRun(self, value: PLAS.Run) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class ControlLoopBuilder(PLAS.RunBuilder):
    def __init__(self) -> None: ...
    @property
    def ProcessVariable(self) -> str: ...
    @ProcessVariable.setter
    def ProcessVariable(self, value: str) -> None: ...


class ControlLoop(PLAS.Run):
    def __init__(self) -> None: ...


