from ...NXOpen import *

import typing
import enum

class OnestepUnformCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[BodyDes.OnestepUnformBuilder]: ...
    @typing.overload
    def __init__(self, owner: Part) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateOnestepBuilder(self, onestepunform: Features.Feature) -> BodyDes.OnestepUnformBuilder: ...
    def Tag(self) -> Tag: ...



class OnestepUnformBuilder(Features.FeatureBuilder):
    def __init__(self) -> None: ...
    def Mesh(self) -> None: ...
    def Calculation(self) -> None: ...
    def GetThickness(self, thickness: float) -> None: ...
    def Constructor(self, tOnestepSolverType: int) -> None: ...
    def Destructor(self) -> None: ...
    def GetSolverType(self) -> int: ...
    def SetDrawDirection(self, tdx: int, tdy: int, tdz: int) -> None: ...
    def SetBlankThickness(self, thickness: float) -> None: ...
    def GetRefNode(self) -> int: ...
    def SetSurfaceType(self, tOnestepSolverSurfaceType: int) -> None: ...
    def GetMinNodeID(self) -> int: ...
    def SetNodeIDsOnFreeEdge(self, index: int, nids: int) -> None: ...
    def GetNodeIdsOnFreeEdge(self, index: int, nodeIdentifications: int) -> None: ...
    def GetMeshes(self, vnode: float, constraintId: int, element: int) -> None: ...
    def GetBlankShape(self, nodes: float) -> None: ...
    def GetStrain(self, strains: float) -> None: ...
    def GetStress(self, stress: float) -> None: ...
    def GetSpringbackShape(self, nodes: float) -> None: ...
    def GetTopSurfaceStress(self, nodes: float) -> None: ...
    def GetTopSurfaceStrain(self, nodes: float) -> None: ...
    def GetBottomSurfaceStress(self, nodes: float) -> None: ...
    def GetBottomSurfaceStrain(self, nodes: float) -> None: ...
    def IsResultExist(self) -> None: ...
    def SetBorderInfo(self, edgeTags: typing.List[TaggedObject], nids: int, groupInfo: int) -> None: ...
    def UpdateInputMeshDataToSolver(self) -> None: ...
    def GetBorderLoops(self, index: int, nodeIdentifications: int) -> None: ...
    def OnestepUnformRegisterProjectCallback(self) -> None: ...
    def DisplayProfile(self, readResultFromFeature: bool) -> None: ...
    def CreateSheetBody(self, readResultFromFeature: bool) -> None: ...
    def SetResultThickness(self, thickness: float) -> None: ...
    def SetResultStrain(self, strain: float) -> None: ...
    def SetResultStress(self, stress: float) -> None: ...
    def SetResultSpringBack(self, springback: float) -> None: ...
    def SetResultBlankShape(self, blankshape: float) -> None: ...
    def SetResultNodesIdsOnProfile(self, nids: int) -> None: ...
    def SetResultNodesNumEachProfileCurve(self, indexs: int) -> None: ...
    def SetResultRefNodeId(self, resultRefNodeId: int) -> None: ...
    def SetConstraintInformation(self, noCommonEdges: bool, revisedDirU: int, revisedDirT: int, index: int, constraintType: int, cacNumsUnform: int, cacNumsTarget: int, consCurveFromUnform: typing.List[TaggedObject], consCurveFromTarget: typing.List[TaggedObject], consPointFromUnform: typing.List[Point], consPointFromTarget: typing.List[Point], startPtOfConsCrvsUnform: float, startPtOfConsCrvsTarget: float) -> None: ...
    def SetAdvancedConstraintInformation(self, advancedConstraintPartType: int, blankHolderWithAddendumBinderRegion: typing.List[TaggedObject], blankHolderWithoutAddendumBoundaryOfPart: typing.List[TaggedObject], blankHolderWithAddendumPressure: float, blankHolderWithAddendumForce: float, blankHolderWithoutAddendumTension: float, blankHolderWithoutAddendumForce: float, blankHolderWithoutAddendumForceStrength: float, drawbeadTag: typing.List[TaggedObject], drawbeadTtension: float, drawbeadNtension: float, drawbeadForceStrength: float) -> None: ...
    def GetContactNodeIds(self) -> int: ...
    def SetFacesOnOffsetSheet(self, unfoldBody: Body) -> bool: ...
    def DeleteOffsetSheetBody(self) -> None: ...
    @property
    def BinderRegion(self) -> ScCollector: ...
    @BinderRegion.setter
    def BinderRegion(self, value: ScCollector) -> None: ...
    @property
    def ConstraintType(self) -> BodyDes.OnestepUnformBuilder.Constraint: ...
    @ConstraintType.setter
    def ConstraintType(self, value: BodyDes.OnestepUnformBuilder.Constraint) -> None: ...
    @property
    def ContactPointsTolerance(self) -> float: ...
    @ContactPointsTolerance.setter
    def ContactPointsTolerance(self, value: float) -> None: ...
    @property
    def DrawDirection(self) -> Direction: ...
    @DrawDirection.setter
    def DrawDirection(self, value: Direction) -> None: ...
    @property
    def Force(self) -> float: ...
    @Force.setter
    def Force(self, value: float) -> None: ...
    @property
    def ForceStrength(self) -> float: ...
    @ForceStrength.setter
    def ForceStrength(self, value: float) -> None: ...
    @property
    def InferElementSize(self) -> bool: ...
    @InferElementSize.setter
    def InferElementSize(self, value: bool) -> None: ...
    @property
    def InferThickness(self) -> bool: ...
    @InferThickness.setter
    def InferThickness(self, value: bool) -> None: ...
    @property
    def MatchPointOne(self) -> Point: ...
    @MatchPointOne.setter
    def MatchPointOne(self, value: Point) -> None: ...
    @property
    def MatchPointThree(self) -> Point: ...
    @MatchPointThree.setter
    def MatchPointThree(self, value: Point) -> None: ...
    @property
    def MatchPointTwo(self) -> Point: ...
    @MatchPointTwo.setter
    def MatchPointTwo(self, value: Point) -> None: ...
    @property
    def MaterialPropertyDensity(self) -> float: ...
    @MaterialPropertyDensity.setter
    def MaterialPropertyDensity(self, value: float) -> None: ...
    @property
    def MaterialPropertyE(self) -> float: ...
    @MaterialPropertyE.setter
    def MaterialPropertyE(self, value: float) -> None: ...
    @property
    def MaterialPropertyF(self) -> float: ...
    @MaterialPropertyF.setter
    def MaterialPropertyF(self, value: float) -> None: ...
    @property
    def MaterialPropertyInitialStrain(self) -> float: ...
    @MaterialPropertyInitialStrain.setter
    def MaterialPropertyInitialStrain(self, value: float) -> None: ...
    @property
    def MaterialPropertyK(self) -> float: ...
    @MaterialPropertyK.setter
    def MaterialPropertyK(self, value: float) -> None: ...
    @property
    def MaterialPropertyN(self) -> float: ...
    @MaterialPropertyN.setter
    def MaterialPropertyN(self, value: float) -> None: ...
    @property
    def MaterialPropertyPoisson(self) -> float: ...
    @MaterialPropertyPoisson.setter
    def MaterialPropertyPoisson(self, value: float) -> None: ...
    @property
    def MaterialPropertyR0(self) -> float: ...
    @MaterialPropertyR0.setter
    def MaterialPropertyR0(self, value: float) -> None: ...
    @property
    def MaterialPropertyR45(self) -> float: ...
    @MaterialPropertyR45.setter
    def MaterialPropertyR45(self, value: float) -> None: ...
    @property
    def MaterialPropertyR90(self) -> float: ...
    @MaterialPropertyR90.setter
    def MaterialPropertyR90(self, value: float) -> None: ...
    @property
    def MaterialPropertyYieldStress(self) -> float: ...
    @MaterialPropertyYieldStress.setter
    def MaterialPropertyYieldStress(self, value: float) -> None: ...
    @property
    def MeshAttemptMapping(self) -> bool: ...
    @MeshAttemptMapping.setter
    def MeshAttemptMapping(self, value: bool) -> None: ...
    @property
    def MeshElementSize(self) -> float: ...
    @MeshElementSize.setter
    def MeshElementSize(self, value: float) -> None: ...
    @property
    def MeshElementType(self) -> BodyDes.OnestepUnformBuilder.MeshElement: ...
    @MeshElementType.setter
    def MeshElementType(self, value: BodyDes.OnestepUnformBuilder.MeshElement) -> None: ...
    @property
    def MeshMaxJacobian(self) -> float: ...
    @MeshMaxJacobian.setter
    def MeshMaxJacobian(self, value: float) -> None: ...
    @property
    def MeshMaxWarp(self) -> float: ...
    @MeshMaxWarp.setter
    def MeshMaxWarp(self, value: float) -> None: ...
    @property
    def MeshProcessFillet(self) -> bool: ...
    @MeshProcessFillet.setter
    def MeshProcessFillet(self, value: bool) -> None: ...
    @property
    def MeshSizeVariation(self) -> int: ...
    @MeshSizeVariation.setter
    def MeshSizeVariation(self, value: int) -> None: ...
    @property
    def MeshSmallFeature(self) -> float: ...
    @MeshSmallFeature.setter
    def MeshSmallFeature(self, value: float) -> None: ...
    @property
    def MeshSplitQuad(self) -> bool: ...
    @MeshSplitQuad.setter
    def MeshSplitQuad(self, value: bool) -> None: ...
    @property
    def ObjectType(self) -> BodyDes.OnestepUnformBuilder.Object: ...
    @ObjectType.setter
    def ObjectType(self, value: BodyDes.OnestepUnformBuilder.Object) -> None: ...
    @property
    def PartBoundary(self) -> ScCollector: ...
    @PartBoundary.setter
    def PartBoundary(self, value: ScCollector) -> None: ...
    @property
    def PartType(self) -> BodyDes.OnestepUnformBuilder.Part: ...
    @PartType.setter
    def PartType(self, value: BodyDes.OnestepUnformBuilder.Part) -> None: ...
    @property
    def Pressure(self) -> float: ...
    @Pressure.setter
    def Pressure(self, value: float) -> None: ...
    @property
    def ProcessType(self) -> BodyDes.OnestepUnformBuilder.Process: ...
    @ProcessType.setter
    def ProcessType(self, value: BodyDes.OnestepUnformBuilder.Process) -> None: ...
    @property
    def ReportDisplayFlattenShape(self) -> bool: ...
    @ReportDisplayFlattenShape.setter
    def ReportDisplayFlattenShape(self, value: bool) -> None: ...
    @property
    def ReportDisplaySpringback(self) -> bool: ...
    @ReportDisplaySpringback.setter
    def ReportDisplaySpringback(self, value: bool) -> None: ...
    @property
    def ReportDisplayStrain(self) -> bool: ...
    @ReportDisplayStrain.setter
    def ReportDisplayStrain(self, value: bool) -> None: ...
    @property
    def ReportDisplayStress(self) -> bool: ...
    @ReportDisplayStress.setter
    def ReportDisplayStress(self, value: bool) -> None: ...
    @property
    def ReportDisplayThickness(self) -> bool: ...
    @ReportDisplayThickness.setter
    def ReportDisplayThickness(self, value: bool) -> None: ...
    @property
    def ReportDisplayViewControl(self) -> bool: ...
    @ReportDisplayViewControl.setter
    def ReportDisplayViewControl(self, value: bool) -> None: ...
    @property
    def ReverseSide(self) -> bool: ...
    @ReverseSide.setter
    def ReverseSide(self, value: bool) -> None: ...
    @property
    def SolverConvergencyLevel(self) -> BodyDes.OnestepUnformBuilder.Convergency: ...
    @SolverConvergencyLevel.setter
    def SolverConvergencyLevel(self, value: BodyDes.OnestepUnformBuilder.Convergency) -> None: ...
    @property
    def SolverDisplaySpringbackMode(self) -> BodyDes.OnestepUnformBuilder.DisplaySpringbackMode: ...
    @SolverDisplaySpringbackMode.setter
    def SolverDisplaySpringbackMode(self, value: BodyDes.OnestepUnformBuilder.DisplaySpringbackMode) -> None: ...
    @property
    def SolverDoSpringbackCalculation(self) -> bool: ...
    @SolverDoSpringbackCalculation.setter
    def SolverDoSpringbackCalculation(self, value: bool) -> None: ...
    @property
    def SolverJoinOutputCurves(self) -> bool: ...
    @SolverJoinOutputCurves.setter
    def SolverJoinOutputCurves(self, value: bool) -> None: ...
    @property
    def SolverMaxIterationSteps(self) -> int: ...
    @SolverMaxIterationSteps.setter
    def SolverMaxIterationSteps(self, value: int) -> None: ...
    @property
    def SolverSaveAnalysisResultsIntoFeature(self) -> bool: ...
    @SolverSaveAnalysisResultsIntoFeature.setter
    def SolverSaveAnalysisResultsIntoFeature(self, value: bool) -> None: ...
    @property
    def SurfaceType(self) -> BodyDes.OnestepUnformBuilder.Surface: ...
    @SurfaceType.setter
    def SurfaceType(self, value: BodyDes.OnestepUnformBuilder.Surface) -> None: ...
    @property
    def TargetRegion(self) -> ScCollector: ...
    @TargetRegion.setter
    def TargetRegion(self, value: ScCollector) -> None: ...
    @property
    def Thickness(self) -> float: ...
    @Thickness.setter
    def Thickness(self, value: float) -> None: ...
    @property
    def ThicknessDirection(self) -> Direction: ...
    @ThicknessDirection.setter
    def ThicknessDirection(self, value: Direction) -> None: ...
    @property
    def TrimlinePoint(self) -> Point: ...
    @TrimlinePoint.setter
    def TrimlinePoint(self, value: Point) -> None: ...
    @property
    def UnfoldModeType(self) -> BodyDes.OnestepUnformBuilder.UnfoldMode: ...
    @UnfoldModeType.setter
    def UnfoldModeType(self, value: BodyDes.OnestepUnformBuilder.UnfoldMode) -> None: ...
    @property
    def UnfoldSolid(self) -> Body: ...
    @UnfoldSolid.setter
    def UnfoldSolid(self, value: Body) -> None: ...
    @property
    def UnfoldSolidRegion(self) -> SelectBodyList: ...
    @UnfoldSolidRegion.setter
    def UnfoldSolidRegion(self, value: SelectBodyList) -> None: ...
    @property
    def UnformRegion(self) -> ScCollector: ...
    @UnformRegion.setter
    def UnformRegion(self, value: ScCollector) -> None: ...
    @property
    def UnformSection(self) -> Section: ...
    @UnformSection.setter
    def UnformSection(self, value: Section) -> None: ...


    class UnfoldMode(enum.Enum):
        Complete= 0
        Intermediate= 1
        Trimline= 2
        Unknown= 3
    

    class Surface(enum.Enum):
        Inner= 0
        Middle= 1
        Outer= 2
    

    class Process(enum.Enum):
        EntireUnform= 0
        IntermediateUnform= 1
        AdvancedUnform= 2
        TrimLine= 3
    

    class Part(enum.Enum):
        WithAddendum= 0
        WithoutAddendum= 1
    

    class Object(enum.Enum):
        Solid= 0
        Face= 1
    

    class MeshElement(enum.Enum):
        Triangle= 0
        Quadrate= 1
    

    class DisplaySpringbackMode(enum.Enum):
        Displacement= 0
        Alongx= 1
        Alongy= 2
        Alongz= 3
    

    class Convergency(enum.Enum):
        Low= 0
        Medium= 1
        High= 2
    

    class Constraint(enum.Enum):
        CurveToCurve= 0
        PointToPoint= 1
        CurveAlongCurve= 2
    

class OnestepUnform(Features.Feature):
    def __init__(self) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


