from ....NXOpen import *
from ...Features import *

import typing
import enum

class ProjectSetupBuilder(Builder):
    def __init__(self) -> None: ...
    def AddSharedParts(self, parts: typing.List[Part]) -> None: ...
    def GetRootNode(self) -> Features.Industry.ProjectStructureNode: ...
    @property
    def IsNewStructure(self) -> bool: ...
    @IsNewStructure.setter
    def IsNewStructure(self, value: bool) -> None: ...
    @property
    def IsSaveAsSharePart(self) -> bool: ...
    @IsSaveAsSharePart.setter
    def IsSaveAsSharePart(self, value: bool) -> None: ...
    @property
    def ProjectName(self) -> str: ...
    @ProjectName.setter
    def ProjectName(self, value: str) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


