from ....NXOpen import *
from ...Diagramming import *

import typing
import enum

class RectangleCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.Geometry.Rectangle]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateRectangleBuilder(self, rectangleGeometry: Diagramming.Geometry.Rectangle) -> Diagramming.Geometry.RectangleBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.Geometry.Rectangle: ...
    def Tag(self) -> Tag: ...



class RectangleBuilder(Diagramming.Geometry.BaseGeometryBuilder):
    def __init__(self) -> None: ...
    @property
    def FirstCorner(self) -> Diagramming.LocationBuilder: ...
    @FirstCorner.setter
    def FirstCorner(self, value: Diagramming.LocationBuilder) -> None: ...
    @property
    def SecondCorner(self) -> Diagramming.LocationBuilder: ...
    @SecondCorner.setter
    def SecondCorner(self, value: Diagramming.LocationBuilder) -> None: ...


class Rectangle(Diagramming.Geometry.BaseGeometry):
    def __init__(self) -> None: ...


class PointCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.Geometry.Point]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreatePointBuilder(self, pointGeometry: Diagramming.Geometry.Point) -> Diagramming.Geometry.PointBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.Geometry.Point: ...
    def Tag(self) -> Tag: ...



class PointBuilder(Diagramming.Geometry.BaseGeometryBuilder):
    def __init__(self) -> None: ...
    @property
    def Coordinate(self) -> Diagramming.LocationBuilder: ...
    @Coordinate.setter
    def Coordinate(self, value: Diagramming.LocationBuilder) -> None: ...


class Point(Diagramming.Geometry.BaseGeometry):
    def __init__(self) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class LineCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.Geometry.Line]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateLineBuilder(self, lineGeometry: Diagramming.Geometry.Line) -> Diagramming.Geometry.LineBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.Geometry.Line: ...
    def Tag(self) -> Tag: ...



class LineBuilder(Diagramming.Geometry.BaseGeometryBuilder):
    def __init__(self) -> None: ...
    @property
    def End(self) -> Diagramming.LocationBuilder: ...
    @End.setter
    def End(self, value: Diagramming.LocationBuilder) -> None: ...
    @property
    def Start(self) -> Diagramming.LocationBuilder: ...
    @Start.setter
    def Start(self, value: Diagramming.LocationBuilder) -> None: ...


class Line(Diagramming.Geometry.BaseGeometry):
    def __init__(self) -> None: ...


class BaseGeometryBuilder(Diagramming.SheetElementBuilder):
    def __init__(self) -> None: ...


class BaseGeometry(Diagramming.SheetElement):
    def __init__(self) -> None: ...


class ArcCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.Geometry.Arc]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateArcBuilder(self, arcGeometry: Diagramming.Geometry.Arc) -> Diagramming.Geometry.ArcBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.Geometry.Arc: ...
    def Tag(self) -> Tag: ...



class ArcBuilder(Diagramming.Geometry.BaseGeometryBuilder):
    def __init__(self) -> None: ...
    @property
    def Center(self) -> Diagramming.LocationBuilder: ...
    @Center.setter
    def Center(self, value: Diagramming.LocationBuilder) -> None: ...
    @property
    def EndAngle(self) -> float: ...
    @EndAngle.setter
    def EndAngle(self, value: float) -> None: ...
    @property
    def Radius(self) -> float: ...
    @Radius.setter
    def Radius(self, value: float) -> None: ...
    @property
    def StartAngle(self) -> float: ...
    @StartAngle.setter
    def StartAngle(self, value: float) -> None: ...


class Arc(Diagramming.Geometry.BaseGeometry):
    def __init__(self) -> None: ...


