from ...NXOpen import *

import typing
import enum

class UniteBuilder(Implicit.BooleanBuilder):
    def __init__(self) -> None: ...


class Unite(Implicit.Boolean):
    def __init__(self) -> None: ...


class TorusBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def Associative(self) -> bool: ...
    @Associative.setter
    def Associative(self, value: bool) -> None: ...
    @property
    def CenterAndOrientation(self) -> CartesianCoordinateSystem: ...
    @CenterAndOrientation.setter
    def CenterAndOrientation(self, value: CartesianCoordinateSystem) -> None: ...
    @property
    def InnerDimension(self) -> Expression: ...
    @InnerDimension.setter
    def InnerDimension(self, value: Expression) -> None: ...
    @property
    def OuterDimension(self) -> Expression: ...
    @OuterDimension.setter
    def OuterDimension(self, value: Expression) -> None: ...


class Torus(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class ThickenBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def FacesToThicken(self) -> ScCollector: ...
    @FacesToThicken.setter
    def FacesToThicken(self, value: ScCollector) -> None: ...
    @property
    def Thickness(self) -> Expression: ...
    @Thickness.setter
    def Thickness(self, value: Expression) -> None: ...
    @property
    def ThicknessMethod(self) -> Implicit.ThickenBuilder.ThicknessMethodType: ...
    @ThicknessMethod.setter
    def ThicknessMethod(self, value: Implicit.ThickenBuilder.ThicknessMethodType) -> None: ...
    @property
    def VariableThicknessList(self) -> ModlUtils.SelectObjectDimList: ...
    @VariableThicknessList.setter
    def VariableThicknessList(self, value: ModlUtils.SelectObjectDimList) -> None: ...


    class ThicknessMethodType(enum.Enum):
        Constant= 0
        Variable= 1
    

class Thicken(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class SubtractBuilder(Implicit.BooleanBuilder):
    def __init__(self) -> None: ...


class Subtract(Implicit.Boolean):
    def __init__(self) -> None: ...


class SplitP(Implicit.EquationOperation):
    def __init__(self) -> None: ...


class SphereBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def AssociativeOrigin(self) -> bool: ...
    @AssociativeOrigin.setter
    def AssociativeOrigin(self, value: bool) -> None: ...
    @property
    def CenterPoint(self) -> Point: ...
    @CenterPoint.setter
    def CenterPoint(self, value: Point) -> None: ...
    @property
    def Diameter(self) -> Expression: ...
    @Diameter.setter
    def Diameter(self, value: Expression) -> None: ...


class Sphere(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class ShellBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def AlternateThicknessList(self) -> ExpressionCollectorSetList: ...
    @AlternateThicknessList.setter
    def AlternateThicknessList(self, value: ExpressionCollectorSetList) -> None: ...
    @property
    def BodyToOffset(self) -> ScCollector: ...
    @BodyToOffset.setter
    def BodyToOffset(self, value: ScCollector) -> None: ...
    @property
    def DefaultThicknessDirectionReversed(self) -> bool: ...
    @DefaultThicknessDirectionReversed.setter
    def DefaultThicknessDirectionReversed(self, value: bool) -> None: ...
    @property
    def FacesToOpen(self) -> ScCollector: ...
    @FacesToOpen.setter
    def FacesToOpen(self, value: ScCollector) -> None: ...
    @property
    def Thickness(self) -> Expression: ...
    @Thickness.setter
    def Thickness(self, value: Expression) -> None: ...
    @property
    def TypeOfShell(self) -> Implicit.ShellBuilder.Type: ...
    @TypeOfShell.setter
    def TypeOfShell(self, value: Implicit.ShellBuilder.Type) -> None: ...


    class Type(enum.Enum):
        Closed= 0
        Open= 1
    

class Shell(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class Schwarz(Implicit.EquationOperation):
    def __init__(self) -> None: ...


class Schoen(Implicit.EquationOperation):
    def __init__(self) -> None: ...


class Scherk(Implicit.EquationOperation):
    def __init__(self) -> None: ...


class OperationBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def DisplayVoxel(self) -> bool: ...
    @DisplayVoxel.setter
    def DisplayVoxel(self, value: bool) -> None: ...
    @property
    def UpdateDefaultVoxelSizeBasedOnFirstOperation(self) -> bool: ...
    @UpdateDefaultVoxelSizeBasedOnFirstOperation.setter
    def UpdateDefaultVoxelSizeBasedOnFirstOperation(self, value: bool) -> None: ...
    @property
    def VoxelSizePercent(self) -> Expression: ...
    @VoxelSizePercent.setter
    def VoxelSizePercent(self, value: Expression) -> None: ...


class OffsetBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def BodyToOffset(self) -> ScCollector: ...
    @BodyToOffset.setter
    def BodyToOffset(self, value: ScCollector) -> None: ...
    @property
    def DefaultThicknessDirectionReversed(self) -> bool: ...
    @DefaultThicknessDirectionReversed.setter
    def DefaultThicknessDirectionReversed(self, value: bool) -> None: ...
    @property
    def Thickness(self) -> Expression: ...
    @Thickness.setter
    def Thickness(self, value: Expression) -> None: ...


class Offset(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class Neovius(Implicit.EquationOperation):
    def __init__(self) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class Lidinoid(Implicit.EquationOperation):
    def __init__(self) -> None: ...


class IntersectBuilder(Implicit.BooleanBuilder):
    def __init__(self) -> None: ...


class Intersect(Implicit.Boolean):
    def __init__(self) -> None: ...


class ImportSolidBodyBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def BodiesOrFacesToImport(self) -> ScCollector: ...
    @BodiesOrFacesToImport.setter
    def BodiesOrFacesToImport(self, value: ScCollector) -> None: ...
    @property
    def BodiesToImport(self) -> ScCollector: ...
    @BodiesToImport.setter
    def BodiesToImport(self, value: ScCollector) -> None: ...
    @property
    def HideInputBody(self) -> bool: ...
    @HideInputBody.setter
    def HideInputBody(self, value: bool) -> None: ...


class ImportSolidBody(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class ImplicitOperationCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Implicit.ImplicitOperation]: ...
    @typing.overload
    def __init__(self, owner: BasePart) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateImplicitModelingPreferencesBuilder(self, implicitFeature: Features.Feature) -> Implicit.ImplicitModelingPreferencesBuilder: ...
    def CreateEquationOperationBuilder(self, implicitOperation: Implicit.EquationOperation) -> Implicit.EquationOperationBuilder: ...
    def CreateImportSoildBodyBuilder(self, implicitOperation: Implicit.ImportSolidBody) -> Implicit.ImportSolidBodyBuilder: ...
    def CreateBlockBuilder(self, implicitOperation: Implicit.Block) -> Implicit.BlockBuilder: ...
    def CreateSphereBuilder(self, implicitOperation: Implicit.Sphere) -> Implicit.SphereBuilder: ...
    def CreateTorusBuilder(self, implicitOperation: Implicit.Torus) -> Implicit.TorusBuilder: ...
    def CreateEllipsoidBuilder(self, implicitOperation: Implicit.Ellipsoid) -> Implicit.EllipsoidBuilder: ...
    def CreateGeneralEquationOperationBuilder(self, implicitOperation: Implicit.GeneralEquationOperation) -> Implicit.GeneralEquationOperationBuilder: ...
    def CreateCylinderBuilder(self, implicitOperation: Implicit.Cylinder) -> Implicit.CylinderBuilder: ...
    def CreateConeBuilder(self, implicitOperation: Implicit.Cone) -> Implicit.ConeBuilder: ...
    def CreateShellBuilder(self, implicitOperation: Implicit.Shell) -> Implicit.ShellBuilder: ...
    def CreateIntersectBuilder(self, implicitOperation: Implicit.Intersect) -> Implicit.IntersectBuilder: ...
    def CreateSubtractBuilder(self, implicitOperation: Implicit.Subtract) -> Implicit.SubtractBuilder: ...
    def CreateUniteBuilder(self, implicitOperation: Implicit.Unite) -> Implicit.UniteBuilder: ...
    def CreateThickenBuilder(self, implicitOperation: Implicit.Thicken) -> Implicit.ThickenBuilder: ...
    def CreateCartesianPatternBuilder(self, implicitOperation: Implicit.CartesianPattern) -> Implicit.CartesianPatternBuilder: ...
    def CreateCylindricalPatternBuilder(self, implicitOperation: Implicit.CylindricalPattern) -> Implicit.CylindricalPatternBuilder: ...
    def Tag(self) -> Tag: ...



class ImplicitOperation(NXObject):
    def __init__(self) -> None: ...
    def GetParents(self) -> typing.List[Implicit.ImplicitOperation]: ...
    def GetExpressions(self) -> typing.List[Expression]: ...
    @property
    def Timestamp(self) -> int: ...
    @Timestamp.setter
    def Timestamp(self, value: int) -> None: ...


class ImplicitModelingPreferencesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def ChordalTolerance(self) -> float: ...
    @ChordalTolerance.setter
    def ChordalTolerance(self, value: float) -> None: ...
    @property
    def MaxFacetSize(self) -> Expression: ...
    @MaxFacetSize.setter
    def MaxFacetSize(self, value: Expression) -> None: ...
    @property
    def RemeshFlag(self) -> bool: ...
    @RemeshFlag.setter
    def RemeshFlag(self, value: bool) -> None: ...
    @property
    def VoxelSize(self) -> Expression: ...
    @VoxelSize.setter
    def VoxelSize(self, value: Expression) -> None: ...


class Gyroid(Implicit.EquationOperation):
    def __init__(self) -> None: ...


class GeneralEquationOperationBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def BoundaryBody(self) -> ScCollector: ...
    @BoundaryBody.setter
    def BoundaryBody(self, value: ScCollector) -> None: ...
    @property
    def BoundaryOption(self) -> Implicit.GeneralEquationOperationBuilder.BoundaryOptionsEnum: ...
    @BoundaryOption.setter
    def BoundaryOption(self, value: Implicit.GeneralEquationOperationBuilder.BoundaryOptionsEnum) -> None: ...
    @property
    def LocationAndOrientation(self) -> CoordinateSystem: ...
    @LocationAndOrientation.setter
    def LocationAndOrientation(self, value: CoordinateSystem) -> None: ...
    @property
    def SizeX(self) -> Expression: ...
    @SizeX.setter
    def SizeX(self, value: Expression) -> None: ...
    @property
    def SizeY(self) -> Expression: ...
    @SizeY.setter
    def SizeY(self, value: Expression) -> None: ...
    @property
    def SizeZ(self) -> Expression: ...
    @SizeZ.setter
    def SizeZ(self, value: Expression) -> None: ...
    @property
    def Thickness(self) -> Expression: ...
    @Thickness.setter
    def Thickness(self, value: Expression) -> None: ...
    @property
    def ThicknessFactor(self) -> Expression: ...
    @ThicknessFactor.setter
    def ThicknessFactor(self, value: Expression) -> None: ...
    @property
    def ThicknessMethod(self) -> Implicit.GeneralEquationOperationBuilder.ThicknessMethodType: ...
    @ThicknessMethod.setter
    def ThicknessMethod(self, value: Implicit.GeneralEquationOperationBuilder.ThicknessMethodType) -> None: ...
    @property
    def UniformRange(self) -> bool: ...
    @UniformRange.setter
    def UniformRange(self, value: bool) -> None: ...
    @property
    def UniformSize(self) -> Expression: ...
    @UniformSize.setter
    def UniformSize(self, value: Expression) -> None: ...
    @property
    def UserExpression(self) -> ModlUtils.EquationEditorBuilder: ...
    @UserExpression.setter
    def UserExpression(self, value: ModlUtils.EquationEditorBuilder) -> None: ...


    class ThicknessMethodType(enum.Enum):
        Absolute= 0
        Relative= 1
    

    class BoundaryOptionsEnum(enum.Enum):
        CartesianRange= 0
        BoundaryBody= 1
    

class GeneralEquationOperation(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class EquationOperationBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def BlendFactor(self) -> int: ...
    @BlendFactor.setter
    def BlendFactor(self, value: int) -> None: ...
    @property
    def BoundaryBody(self) -> ScCollector: ...
    @BoundaryBody.setter
    def BoundaryBody(self, value: ScCollector) -> None: ...
    @property
    def BoundaryConditionOption(self) -> Implicit.EquationOperationBuilder.BoundaryConditionOptionType: ...
    @BoundaryConditionOption.setter
    def BoundaryConditionOption(self, value: Implicit.EquationOperationBuilder.BoundaryConditionOptionType) -> None: ...
    @property
    def EdgeLength(self) -> Expression: ...
    @EdgeLength.setter
    def EdgeLength(self, value: Expression) -> None: ...
    @property
    def KFactor(self) -> float: ...
    @KFactor.setter
    def KFactor(self, value: float) -> None: ...
    @property
    def LocationAndOrientation(self) -> CoordinateSystem: ...
    @LocationAndOrientation.setter
    def LocationAndOrientation(self, value: CoordinateSystem) -> None: ...
    @property
    def SizeX(self) -> Expression: ...
    @SizeX.setter
    def SizeX(self, value: Expression) -> None: ...
    @property
    def SizeY(self) -> Expression: ...
    @SizeY.setter
    def SizeY(self, value: Expression) -> None: ...
    @property
    def SizeZ(self) -> Expression: ...
    @SizeZ.setter
    def SizeZ(self, value: Expression) -> None: ...
    @property
    def Thickness(self) -> Expression: ...
    @Thickness.setter
    def Thickness(self, value: Expression) -> None: ...
    @property
    def ThicknessFactor(self) -> Expression: ...
    @ThicknessFactor.setter
    def ThicknessFactor(self, value: Expression) -> None: ...
    @property
    def ThicknessField(self) -> Fields.ScalarFieldWrapper: ...
    @ThicknessField.setter
    def ThicknessField(self, value: Fields.ScalarFieldWrapper) -> None: ...
    @property
    def ThicknessMethod(self) -> Implicit.EquationOperationBuilder.ThicknessMethodType: ...
    @ThicknessMethod.setter
    def ThicknessMethod(self, value: Implicit.EquationOperationBuilder.ThicknessMethodType) -> None: ...
    @property
    def TypeOfEquation(self) -> Implicit.EquationOperationBuilder.EquationType: ...
    @TypeOfEquation.setter
    def TypeOfEquation(self, value: Implicit.EquationOperationBuilder.EquationType) -> None: ...
    @property
    def UniformCubeFlag(self) -> bool: ...
    @UniformCubeFlag.setter
    def UniformCubeFlag(self, value: bool) -> None: ...
    @property
    def VariableThicknessList(self) -> ModlUtils.SelectObjectDimList: ...
    @VariableThicknessList.setter
    def VariableThicknessList(self, value: ModlUtils.SelectObjectDimList) -> None: ...


    class ThicknessMethodType(enum.Enum):
        Absolute= 0
        AbsoluteVariable= 1
        Relative= 2
    

    class EquationType(enum.Enum):
        Gyroid= 0
        Schwarz= 1
        Diamond= 2
        Neovius= 3
        Schoen= 4
        Scherk= 5
        Lidinoid= 6
        SplitP= 7
    

    class BoundaryConditionOptionType(enum.Enum):
        SolidVolume= 0
        VoidVolume= 1
        VoidVolumeAndUnite= 2
    

class EquationOperation(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class EllipsoidBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def Associative(self) -> bool: ...
    @Associative.setter
    def Associative(self, value: bool) -> None: ...
    @property
    def CenterAndOrientation(self) -> CartesianCoordinateSystem: ...
    @CenterAndOrientation.setter
    def CenterAndOrientation(self, value: CartesianCoordinateSystem) -> None: ...
    @property
    def Height(self) -> Expression: ...
    @Height.setter
    def Height(self, value: Expression) -> None: ...
    @property
    def Length(self) -> Expression: ...
    @Length.setter
    def Length(self, value: Expression) -> None: ...
    @property
    def Width(self) -> Expression: ...
    @Width.setter
    def Width(self, value: Expression) -> None: ...


class Ellipsoid(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class Diamond(Implicit.EquationOperation):
    def __init__(self) -> None: ...


class CylindricalPatternBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def CenterAndOrientation(self) -> CartesianCoordinateSystem: ...
    @CenterAndOrientation.setter
    def CenterAndOrientation(self, value: CartesianCoordinateSystem) -> None: ...
    @property
    def Diameter(self) -> Expression: ...
    @Diameter.setter
    def Diameter(self, value: Expression) -> None: ...
    @property
    def Height(self) -> Expression: ...
    @Height.setter
    def Height(self, value: Expression) -> None: ...
    @property
    def NumberOfCellsAroundCircumference(self) -> int: ...
    @NumberOfCellsAroundCircumference.setter
    def NumberOfCellsAroundCircumference(self, value: int) -> None: ...
    @property
    def NumberOfRadialLayers(self) -> int: ...
    @NumberOfRadialLayers.setter
    def NumberOfRadialLayers(self, value: int) -> None: ...
    @property
    def UnitCellBody(self) -> ScCollector: ...
    @UnitCellBody.setter
    def UnitCellBody(self, value: ScCollector) -> None: ...


class CylindricalPattern(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class CylinderBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def Associative(self) -> bool: ...
    @Associative.setter
    def Associative(self, value: bool) -> None: ...
    @property
    def CenterAndOrientation(self) -> CartesianCoordinateSystem: ...
    @CenterAndOrientation.setter
    def CenterAndOrientation(self, value: CartesianCoordinateSystem) -> None: ...
    @property
    def Diameter(self) -> Expression: ...
    @Diameter.setter
    def Diameter(self, value: Expression) -> None: ...
    @property
    def Height(self) -> Expression: ...
    @Height.setter
    def Height(self, value: Expression) -> None: ...


class Cylinder(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class ConeBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def Associative(self) -> bool: ...
    @Associative.setter
    def Associative(self, value: bool) -> None: ...
    @property
    def BaseDiameter(self) -> Expression: ...
    @BaseDiameter.setter
    def BaseDiameter(self, value: Expression) -> None: ...
    @property
    def CenterAndOrientation(self) -> CartesianCoordinateSystem: ...
    @CenterAndOrientation.setter
    def CenterAndOrientation(self, value: CartesianCoordinateSystem) -> None: ...
    @property
    def Height(self) -> Expression: ...
    @Height.setter
    def Height(self, value: Expression) -> None: ...
    @property
    def TopDiameter(self) -> Expression: ...
    @TopDiameter.setter
    def TopDiameter(self, value: Expression) -> None: ...


class Cone(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class CartesianPatternBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def BlendFactor(self) -> int: ...
    @BlendFactor.setter
    def BlendFactor(self, value: int) -> None: ...
    @property
    def BoundaryBody(self) -> ScCollector: ...
    @BoundaryBody.setter
    def BoundaryBody(self, value: ScCollector) -> None: ...
    @property
    def BoundaryConditionOption(self) -> Implicit.CartesianPatternBuilder.BoundaryConditionOptionType: ...
    @BoundaryConditionOption.setter
    def BoundaryConditionOption(self, value: Implicit.CartesianPatternBuilder.BoundaryConditionOptionType) -> None: ...
    @property
    def EdgeLength(self) -> Expression: ...
    @EdgeLength.setter
    def EdgeLength(self, value: Expression) -> None: ...
    @property
    def LocationAndOrientation(self) -> CoordinateSystem: ...
    @LocationAndOrientation.setter
    def LocationAndOrientation(self, value: CoordinateSystem) -> None: ...
    @property
    def SizeX(self) -> Expression: ...
    @SizeX.setter
    def SizeX(self, value: Expression) -> None: ...
    @property
    def SizeY(self) -> Expression: ...
    @SizeY.setter
    def SizeY(self, value: Expression) -> None: ...
    @property
    def SizeZ(self) -> Expression: ...
    @SizeZ.setter
    def SizeZ(self, value: Expression) -> None: ...
    @property
    def UniformCubeFlag(self) -> bool: ...
    @UniformCubeFlag.setter
    def UniformCubeFlag(self, value: bool) -> None: ...
    @property
    def UnitCellBody(self) -> ScCollector: ...
    @UnitCellBody.setter
    def UnitCellBody(self, value: ScCollector) -> None: ...


    class BoundaryConditionOptionType(enum.Enum):
        SolidVolume= 0
        VoidVolume= 1
        VoidVolumeAndUnite= 2
    

class CartesianPattern(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class BooleanBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def BlendFactor(self) -> int: ...
    @BlendFactor.setter
    def BlendFactor(self, value: int) -> None: ...
    @property
    def CreateBlends(self) -> bool: ...
    @CreateBlends.setter
    def CreateBlends(self, value: bool) -> None: ...
    @property
    def KeepTarget(self) -> bool: ...
    @KeepTarget.setter
    def KeepTarget(self, value: bool) -> None: ...
    @property
    def KeepTool(self) -> bool: ...
    @KeepTool.setter
    def KeepTool(self, value: bool) -> None: ...
    @property
    def TargetBody(self) -> ScCollector: ...
    @TargetBody.setter
    def TargetBody(self, value: ScCollector) -> None: ...
    @property
    def ToolBody(self) -> ScCollector: ...
    @ToolBody.setter
    def ToolBody(self, value: ScCollector) -> None: ...


class Boolean(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


class BlockBuilder(Implicit.OperationBuilder):
    def __init__(self) -> None: ...
    @property
    def Associative(self) -> bool: ...
    @Associative.setter
    def Associative(self, value: bool) -> None: ...
    @property
    def Height(self) -> Expression: ...
    @Height.setter
    def Height(self, value: Expression) -> None: ...
    @property
    def Length(self) -> Expression: ...
    @Length.setter
    def Length(self, value: Expression) -> None: ...
    @property
    def OriginAndOrientation(self) -> CartesianCoordinateSystem: ...
    @OriginAndOrientation.setter
    def OriginAndOrientation(self, value: CartesianCoordinateSystem) -> None: ...
    @property
    def Width(self) -> Expression: ...
    @Width.setter
    def Width(self, value: Expression) -> None: ...


class Block(Implicit.ImplicitOperation):
    def __init__(self) -> None: ...


