from ....NXOpen import *
from ...Features import *

import typing
import enum

class ViewXygraphBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def OptimizationConstraint(self) -> Features.TopologyOptimization.OptimizationConstraint: ...
    @OptimizationConstraint.setter
    def OptimizationConstraint(self, value: Features.TopologyOptimization.OptimizationConstraint) -> None: ...
    @property
    def Study(self) -> Features.TopologyOptimization.Study: ...
    @Study.setter
    def Study(self, value: Features.TopologyOptimization.Study) -> None: ...
    @property
    def SubcaseName(self) -> str: ...
    @SubcaseName.setter
    def SubcaseName(self, value: str) -> None: ...
    @property
    def TargetWindowDevice(self) -> int: ...
    @TargetWindowDevice.setter
    def TargetWindowDevice(self, value: int) -> None: ...
    @property
    def XygraphContent(self) -> Features.TopologyOptimization.ViewXygraphBuilder.ContentOption: ...
    @XygraphContent.setter
    def XygraphContent(self, value: Features.TopologyOptimization.ViewXygraphBuilder.ContentOption) -> None: ...


    class ContentOption(enum.Enum):
        OptimizationObjective= 0
        OptimizationConstraint= 1
    

class ViewTabularResultBuilder(Builder):
    def __init__(self) -> None: ...
    def GetStudies(self) -> typing.List[Features.TopologyOptimization.Study]: ...
    def SetStudies(self, studies: typing.List[Features.TopologyOptimization.Study]) -> None: ...
    @property
    def Bodies(self) -> SelectTaggedObjectList: ...
    @Bodies.setter
    def Bodies(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def ReportContent(self) -> Features.TopologyOptimization.ViewTabularResultBuilder.ReportContentOption: ...
    @ReportContent.setter
    def ReportContent(self, value: Features.TopologyOptimization.ViewTabularResultBuilder.ReportContentOption) -> None: ...


    class ReportContentOption(enum.Enum):
        OptimizationObjective= 0
        OptimizationConstraint= 1
        All= 2
    

class ViewContourBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Bodies(self) -> SelectTaggedObjectList: ...
    @Bodies.setter
    def Bodies(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def ColorScaleRangeType(self) -> Features.TopologyOptimization.ViewContourBuilder.ColorScaleRangeOption: ...
    @ColorScaleRangeType.setter
    def ColorScaleRangeType(self, value: Features.TopologyOptimization.ViewContourBuilder.ColorScaleRangeOption) -> None: ...
    @property
    def ContourDisplayStyle(self) -> Features.TopologyOptimization.ViewContourBuilder.ContourDisplayStyleOption: ...
    @ContourDisplayStyle.setter
    def ContourDisplayStyle(self, value: Features.TopologyOptimization.ViewContourBuilder.ContourDisplayStyleOption) -> None: ...
    @property
    def DisplayType(self) -> Features.TopologyOptimization.ViewContourBuilder.DisplayOption: ...
    @DisplayType.setter
    def DisplayType(self, value: Features.TopologyOptimization.ViewContourBuilder.DisplayOption) -> None: ...
    @property
    def FirstStudy(self) -> Features.TopologyOptimization.Study: ...
    @FirstStudy.setter
    def FirstStudy(self, value: Features.TopologyOptimization.Study) -> None: ...
    @property
    def ResultComponentType(self) -> Features.TopologyOptimization.ViewContourBuilder.ResultComponentOption: ...
    @ResultComponentType.setter
    def ResultComponentType(self, value: Features.TopologyOptimization.ViewContourBuilder.ResultComponentOption) -> None: ...
    @property
    def SecondStudy(self) -> Features.TopologyOptimization.Study: ...
    @SecondStudy.setter
    def SecondStudy(self, value: Features.TopologyOptimization.Study) -> None: ...
    @property
    def SubcaseIndexForFirstStudy(self) -> int: ...
    @SubcaseIndexForFirstStudy.setter
    def SubcaseIndexForFirstStudy(self, value: int) -> None: ...
    @property
    def SubcaseIndexForSecondStudy(self) -> int: ...
    @SubcaseIndexForSecondStudy.setter
    def SubcaseIndexForSecondStudy(self, value: int) -> None: ...


    class ResultComponentOption(enum.Enum):
        DisplacementMagnitude= 0
        DisplacementWorstInXYZ= 1
        DisplacementX= 2
        DisplacementY= 3
        DisplacementZ= 4
        DisplacementAll= 5
        StressVonMises= 6
        StressWorstPrincipal= 7
    

    class DisplayOption(enum.Enum):
        Single= 0
        Comparison= 1
    

    class ContourDisplayStyleOption(enum.Enum):
        Smooth= 0
        Banded= 1
    

    class ColorScaleRangeOption(enum.Enum):
        PerView= 0
        CommonAcrossViews= 1
    

class SubcaseManager(Builder):
    def __init__(self) -> None: ...
    def CreateSubcase(self) -> Features.TopologyOptimization.SubcaseItem: ...
    @property
    def SubcaseList(self) -> Features.TopologyOptimization.SubcaseItemList: ...
    @SubcaseList.setter
    def SubcaseList(self, value: Features.TopologyOptimization.SubcaseItemList) -> None: ...


class SubcaseItemList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[Features.TopologyOptimization.SubcaseItem]) -> None: ...
    @typing.overload
    def Append(self, object: Features.TopologyOptimization.SubcaseItem) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: Features.TopologyOptimization.SubcaseItem) -> int: ...
    def FindItem(self, index: int) -> Features.TopologyOptimization.SubcaseItem: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: Features.TopologyOptimization.SubcaseItem) -> None: ...
    @typing.overload
    def Erase(self, obj: Features.TopologyOptimization.SubcaseItem, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[Features.TopologyOptimization.SubcaseItem]: ...
    def SetContents(self, objects: typing.List[Features.TopologyOptimization.SubcaseItem]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: Features.TopologyOptimization.SubcaseItem, object2: Features.TopologyOptimization.SubcaseItem) -> None: ...
    def Insert(self, location: int, object: Features.TopologyOptimization.SubcaseItem) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class SubcaseItem(TaggedObject):
    def __init__(self) -> None: ...
    def AddReference(self, reference: NXObject) -> None: ...
    def RemoveReference(self, reference: NXObject) -> None: ...
    @property
    def IncludedInOptimization(self) -> bool: ...
    @IncludedInOptimization.setter
    def IncludedInOptimization(self, value: bool) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...


    class ItemType(enum.Enum):
        Load= 0
        Constraint= 1
    

class Subcase(Features.TopologyOptimization.Container):
    def __init__(self) -> None: ...
    def AddReference(self, reference: NXObject) -> None: ...
    def RemoveReference(self, reference: NXObject) -> None: ...
    def GetReferences(self, references: typing.List[NXObject]) -> None: ...
    @property
    def IsIncludedInOptimization(self) -> Features.TopologyOptimization.Subcase.IncludeInOptimization: ...
    @IsIncludedInOptimization.setter
    def IsIncludedInOptimization(self, value: Features.TopologyOptimization.Subcase.IncludeInOptimization) -> None: ...


    class IncludeInOptimization(enum.Enum):
        True_= 0
        False_= 1
    

class StudyBuilder(Builder):
    def __init__(self) -> None: ...
    def SetResolutionVoxelSizeByStudyQuality(self, studyQualityFactor: int) -> None: ...
    @property
    def AnalysisType(self) -> Features.TopologyOptimization.StudyBuilder.AnalysisOption: ...
    @AnalysisType.setter
    def AnalysisType(self, value: Features.TopologyOptimization.StudyBuilder.AnalysisOption) -> None: ...
    @property
    def ConstantTemperature(self) -> Expression: ...
    @ConstantTemperature.setter
    def ConstantTemperature(self, value: Expression) -> None: ...
    @property
    def GravityDirection(self) -> Direction: ...
    @GravityDirection.setter
    def GravityDirection(self, value: Direction) -> None: ...
    @property
    def GravityEnabled(self) -> bool: ...
    @GravityEnabled.setter
    def GravityEnabled(self, value: bool) -> None: ...
    @property
    def GravityMagnitude(self) -> Expression: ...
    @GravityMagnitude.setter
    def GravityMagnitude(self, value: Expression) -> None: ...
    @property
    def OptimizationObjectiveType(self) -> Features.TopologyOptimization.StudyBuilder.OptimizationObjectiveOption: ...
    @OptimizationObjectiveType.setter
    def OptimizationObjectiveType(self, value: Features.TopologyOptimization.StudyBuilder.OptimizationObjectiveOption) -> None: ...
    @property
    def ResolutionVoxelSize(self) -> Expression: ...
    @ResolutionVoxelSize.setter
    def ResolutionVoxelSize(self, value: Expression) -> None: ...
    @property
    def StudyName(self) -> str: ...
    @StudyName.setter
    def StudyName(self, value: str) -> None: ...
    @property
    def StudyQuality(self) -> int: ...
    @StudyQuality.setter
    def StudyQuality(self, value: int) -> None: ...


    class OptimizationObjectiveOption(enum.Enum):
        MinimumMass= 0
        MinimumVolume= 1
        MaximumStiffness= 2
        MaximumFirstFlexibleMode= 3
    

    class AnalysisOption(enum.Enum):
        LinearStatics= 0
        NormalModes= 1
    

class Study(Features.TopologyOptimization.Container):
    def __init__(self) -> None: ...
    def RunOptimization(self) -> None: ...
    def AbortOptimizationProcess(self) -> bool: ...
    def RetrieveOptimizationResults(self) -> None: ...
    def DiscardUnretrievedOptimizationResults(self) -> None: ...
    def Unlock(self) -> None: ...
    def GetOptimizedBodies(self) -> typing.List[Body]: ...
    def DiscardOptimizationResults(self) -> None: ...
    def CreateSceneryBodyBuilder(self, topOptSceneryBody: Features.TopologyOptimization.SceneryBody) -> Features.TopologyOptimization.SceneryBodyBuilder: ...
    def GetAllSceneryBodies(self, topOptSceneryBodies: typing.List[Features.TopologyOptimization.SceneryBody]) -> None: ...
    def CreateConnectionBuilder(self, connection: Features.TopologyOptimization.Connection) -> Features.TopologyOptimization.ConnectionBuilder: ...
    def GetAllConnections(self, topOptConnections: typing.List[Features.TopologyOptimization.Connection]) -> None: ...
    def CreateAnalysisConstraintBuilder(self, constraint: Features.TopologyOptimization.AnalysisConstraint) -> Features.TopologyOptimization.AnalysisConstraintBuilder: ...
    def GetAllAnalysisConstraints(self, analysisConstraints: typing.List[Features.TopologyOptimization.AnalysisConstraint]) -> None: ...
    def CreateDesignSpaceBuilder(self, designSpace: Features.TopologyOptimization.DesignSpace) -> Features.TopologyOptimization.DesignSpaceBuilder: ...
    def GetAllDesignSpaces(self, designSpaces: typing.List[Features.TopologyOptimization.DesignSpace]) -> None: ...
    def CreateAnalysisLoadBuilder(self, load: Features.TopologyOptimization.AnalysisLoad) -> Features.TopologyOptimization.AnalysisLoadBuilder: ...
    def GetAllAnalysisLoads(self, analysisLoads: typing.List[Features.TopologyOptimization.AnalysisLoad]) -> None: ...
    def CreateOptimizationConstraintBuilder(self, optConstraint: Features.TopologyOptimization.OptimizationConstraint) -> Features.TopologyOptimization.OptimizationConstraintBuilder: ...
    def CreateSubcaseManager(self) -> Features.TopologyOptimization.SubcaseManager: ...
    def GetAllSubcases(self, subcases: typing.List[Features.TopologyOptimization.Subcase]) -> None: ...
    def CreateConstructionBodyBuilder(self, topOptConstructionBody: Features.TopologyOptimization.ConstructionBody) -> Features.TopologyOptimization.ConstructionBodyBuilder: ...
    def CreateConstructionBodyCollectorBuilder(self, constrBodyCollector: Features.TopologyOptimization.ConstructionBodyCollector) -> Features.TopologyOptimization.ConstructionBodyBuilder: ...
    def CreateShapeConstraintBuilder(self, topOptShapeConstraint: Features.TopologyOptimization.ShapeConstraint) -> Features.TopologyOptimization.ShapeConstraintBuilder: ...
    def CloneSubcase(self, existingSubcase: Features.TopologyOptimization.Subcase) -> Features.TopologyOptimization.Subcase: ...
    def CloneAnalysisLoad(self, existingload: Features.TopologyOptimization.AnalysisLoad) -> Features.TopologyOptimization.AnalysisLoad: ...
    def CloneAnalysisConstraint(self, existingConstraint: Features.TopologyOptimization.AnalysisConstraint) -> Features.TopologyOptimization.AnalysisConstraint: ...
    @property
    def AnalysisType(self) -> Features.TopologyOptimization.StudyBuilder.AnalysisOption: ...
    @AnalysisType.setter
    def AnalysisType(self, value: Features.TopologyOptimization.StudyBuilder.AnalysisOption) -> None: ...
    @property
    def OptimizationObjective(self) -> Features.TopologyOptimization.StudyBuilder.OptimizationObjectiveOption: ...
    @OptimizationObjective.setter
    def OptimizationObjective(self, value: Features.TopologyOptimization.StudyBuilder.OptimizationObjectiveOption) -> None: ...


class ShapeConstraintBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def DesignSpace(self) -> Features.TopologyOptimization.DesignSpace: ...
    @DesignSpace.setter
    def DesignSpace(self, value: Features.TopologyOptimization.DesignSpace) -> None: ...
    @property
    def DraftAngle(self) -> Expression: ...
    @DraftAngle.setter
    def DraftAngle(self, value: Expression) -> None: ...
    @property
    def DraftDrawDirection(self) -> Direction: ...
    @DraftDrawDirection.setter
    def DraftDrawDirection(self, value: Direction) -> None: ...
    @property
    def DraftPartingFace(self) -> ScCollector: ...
    @DraftPartingFace.setter
    def DraftPartingFace(self, value: ScCollector) -> None: ...
    @property
    def DraftPartingObjectOptions(self) -> Features.TopologyOptimization.ShapeConstraintBuilder.DraftPartingObjectType: ...
    @DraftPartingObjectOptions.setter
    def DraftPartingObjectOptions(self, value: Features.TopologyOptimization.ShapeConstraintBuilder.DraftPartingObjectType) -> None: ...
    @property
    def DraftPartingPlane(self) -> Plane: ...
    @DraftPartingPlane.setter
    def DraftPartingPlane(self, value: Plane) -> None: ...
    @property
    def ExtrudeBiDirectionFlag(self) -> bool: ...
    @ExtrudeBiDirectionFlag.setter
    def ExtrudeBiDirectionFlag(self, value: bool) -> None: ...
    @property
    def ExtrudeDirection(self) -> Direction: ...
    @ExtrudeDirection.setter
    def ExtrudeDirection(self, value: Direction) -> None: ...
    @property
    def FirstLimitPlane(self) -> Plane: ...
    @FirstLimitPlane.setter
    def FirstLimitPlane(self, value: Plane) -> None: ...
    @property
    def MaxOverhangAngle(self) -> Features.TopologyOptimization.ShapeConstraintBuilder.MaxOverhangAngleValue: ...
    @MaxOverhangAngle.setter
    def MaxOverhangAngle(self, value: Features.TopologyOptimization.ShapeConstraintBuilder.MaxOverhangAngleValue) -> None: ...
    @property
    def MaximumDiameter(self) -> Expression: ...
    @MaximumDiameter.setter
    def MaximumDiameter(self, value: Expression) -> None: ...
    @property
    def MaximumWallThickness(self) -> Expression: ...
    @MaximumWallThickness.setter
    def MaximumWallThickness(self, value: Expression) -> None: ...
    @property
    def MinimumDiameter(self) -> Expression: ...
    @MinimumDiameter.setter
    def MinimumDiameter(self, value: Expression) -> None: ...
    @property
    def MinimumWallThickness(self) -> Expression: ...
    @MinimumWallThickness.setter
    def MinimumWallThickness(self, value: Expression) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def NumberOfSegments(self) -> int: ...
    @NumberOfSegments.setter
    def NumberOfSegments(self, value: int) -> None: ...
    @property
    def OverhangVector(self) -> Direction: ...
    @OverhangVector.setter
    def OverhangVector(self, value: Direction) -> None: ...
    @property
    def PlanarSymmetryInputMode(self) -> Features.TopologyOptimization.ShapeConstraintBuilder.PlanarSymmetryInputOption: ...
    @PlanarSymmetryInputMode.setter
    def PlanarSymmetryInputMode(self, value: Features.TopologyOptimization.ShapeConstraintBuilder.PlanarSymmetryInputOption) -> None: ...
    @property
    def PlanarSymmetryPlane1(self) -> Plane: ...
    @PlanarSymmetryPlane1.setter
    def PlanarSymmetryPlane1(self, value: Plane) -> None: ...
    @property
    def PlanarSymmetryPlane2(self) -> Plane: ...
    @PlanarSymmetryPlane2.setter
    def PlanarSymmetryPlane2(self, value: Plane) -> None: ...
    @property
    def RotationalSymmetryAxis(self) -> Axis: ...
    @RotationalSymmetryAxis.setter
    def RotationalSymmetryAxis(self, value: Axis) -> None: ...
    @property
    def SecondLimitPlane(self) -> Plane: ...
    @SecondLimitPlane.setter
    def SecondLimitPlane(self, value: Plane) -> None: ...
    @property
    def SegmentLimitHelpAxis(self) -> Axis: ...
    @SegmentLimitHelpAxis.setter
    def SegmentLimitHelpAxis(self, value: Axis) -> None: ...
    @property
    def Type(self) -> Features.TopologyOptimization.ShapeConstraintBuilder.ConstraintType: ...
    @Type.setter
    def Type(self, value: Features.TopologyOptimization.ShapeConstraintBuilder.ConstraintType) -> None: ...
    @property
    def UserSetName(self) -> bool: ...
    @UserSetName.setter
    def UserSetName(self, value: bool) -> None: ...


    class PlanarSymmetryInputOption(enum.Enum):
        Segment= 0
        Whole= 1
    

    class MaxOverhangAngleValue(enum.Enum):
        Degrees27= 0
        Degrees45= 1
        Degrees65= 2
    

    class DraftPartingObjectType(enum.Enum):
        SpecifiedPlane= 0
        SpecifiedFace= 1
        AutomaticFace= 2
    

    class ConstraintType(enum.Enum):
        PlanarSymmetry= 0
        RepeatedRotationalSymmetry= 1
        SegmentalRotationalSymmetry= 2
        ExtrudeAlongVector= 3
        DraftAngle= 4
        MinimumMemberSize= 5
        MaximumMemberSize= 6
        MinimumWallThickness= 7
        MaximumWallThickness= 8
        OverhangingGeometryPrevention= 9
        SelfSupporting= 10
    

class ShapeConstraint(NXObject):
    def __init__(self) -> None: ...


class SceneryBodyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Bodies(self) -> SelectBodyList: ...
    @Bodies.setter
    def Bodies(self, value: SelectBodyList) -> None: ...
    @property
    def Material(self) -> Material: ...
    @Material.setter
    def Material(self, value: Material) -> None: ...
    @property
    def SceneryBodyName(self) -> str: ...
    @SceneryBodyName.setter
    def SceneryBodyName(self, value: str) -> None: ...


class SceneryBody(NXObject):
    def __init__(self) -> None: ...


class PostManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Features.TopologyOptimizationFeature) -> None: ...
    def CreateViewContourBuilder(self) -> Features.TopologyOptimization.ViewContourBuilder: ...
    def ShowContour(self) -> None: ...
    def HideContour(self) -> None: ...
    def CreateViewTabularResultBuilder(self) -> Features.TopologyOptimization.ViewTabularResultBuilder: ...
    def CreateViewXygraphBuilder(self) -> Features.TopologyOptimization.ViewXygraphBuilder: ...
    def IsContourShown(self) -> bool: ...
    def ExportAnimationToGif(self, fileName: str) -> None: ...
    def IsAnimationPlaying(self) -> bool: ...
    def CreateAnimationController(self) -> Features.TopologyOptimization.AnimationController: ...
    def Tag(self) -> Tag: ...



class OptimizationConstraintBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def DesignSpace(self) -> Features.TopologyOptimization.DesignSpace: ...
    @DesignSpace.setter
    def DesignSpace(self, value: Features.TopologyOptimization.DesignSpace) -> None: ...
    @property
    def DisplacementLocation(self) -> Point: ...
    @DisplacementLocation.setter
    def DisplacementLocation(self, value: Point) -> None: ...
    @property
    def DisplacementType(self) -> Features.TopologyOptimization.OptimizationConstraintBuilder.DisplacementOption: ...
    @DisplacementType.setter
    def DisplacementType(self, value: Features.TopologyOptimization.OptimizationConstraintBuilder.DisplacementOption) -> None: ...
    @property
    def DisplacementVector(self) -> Direction: ...
    @DisplacementVector.setter
    def DisplacementVector(self, value: Direction) -> None: ...
    @property
    def FirstFlexibleFrequency(self) -> Expression: ...
    @FirstFlexibleFrequency.setter
    def FirstFlexibleFrequency(self, value: Expression) -> None: ...
    @property
    def Mass(self) -> Expression: ...
    @Mass.setter
    def Mass(self, value: Expression) -> None: ...
    @property
    def MaxDisplacement(self) -> Expression: ...
    @MaxDisplacement.setter
    def MaxDisplacement(self, value: Expression) -> None: ...
    @property
    def MaxFirstFlexFrequency(self) -> Expression: ...
    @MaxFirstFlexFrequency.setter
    def MaxFirstFlexFrequency(self, value: Expression) -> None: ...
    @property
    def MaxPercentOfStress(self) -> Expression: ...
    @MaxPercentOfStress.setter
    def MaxPercentOfStress(self, value: Expression) -> None: ...
    @property
    def MaximumMass(self) -> Expression: ...
    @MaximumMass.setter
    def MaximumMass(self, value: Expression) -> None: ...
    @property
    def MaximumStressType(self) -> Features.TopologyOptimization.OptimizationConstraintBuilder.MaximumStressOption: ...
    @MaximumStressType.setter
    def MaximumStressType(self, value: Features.TopologyOptimization.OptimizationConstraintBuilder.MaximumStressOption) -> None: ...
    @property
    def MinFirstFlexFrequency(self) -> Expression: ...
    @MinFirstFlexFrequency.setter
    def MinFirstFlexFrequency(self, value: Expression) -> None: ...
    @property
    def MinimumMass(self) -> Expression: ...
    @MinimumMass.setter
    def MinimumMass(self, value: Expression) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def SelectFace(self) -> ScCollector: ...
    @SelectFace.setter
    def SelectFace(self, value: ScCollector) -> None: ...
    @property
    def Type(self) -> Features.TopologyOptimization.OptimizationConstraintBuilder.ConstraintType: ...
    @Type.setter
    def Type(self, value: Features.TopologyOptimization.OptimizationConstraintBuilder.ConstraintType) -> None: ...
    @property
    def UserSetName(self) -> bool: ...
    @UserSetName.setter
    def UserSetName(self, value: bool) -> None: ...


    class MaximumStressOption(enum.Enum):
        UltimateTensileStrength= 0
        Yield= 1
    

    class DisplacementOption(enum.Enum):
        AbsoluteMagnitude= 0
        X= 1
        Y= 2
        Z= 3
        AlongVector= 4
    

    class ConstraintType(enum.Enum):
        MassTarget= 0
        MinimumMassLimit= 1
        MaximumMassLimit= 2
        MaximumStressLimit= 3
        MaximumDisplacementLimit= 4
        FirstFlexibleModeTarget= 5
        MinimumFirstFlexibleModeLimit= 6
        MaximumFirstFlexibleModeLimit= 7
    

class OptimizationConstraint(NXObject):
    def __init__(self) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class DesignSpaceBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Material(self) -> Material: ...
    @Material.setter
    def Material(self, value: Material) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def SelectBody(self) -> SelectBody: ...
    @SelectBody.setter
    def SelectBody(self, value: SelectBody) -> None: ...


class DesignSpace(NXObject):
    def __init__(self) -> None: ...
    def CreateConstructionBodyGroup(self, constructionBodies: typing.List[Features.TopologyOptimization.ConstructionBody]) -> Features.TopologyOptimization.ConstructionBodyCollector: ...
    def AddConstraint(self, constraintObjectTag: NXObject) -> None: ...
    def RemoveConstraint(self, constraintObjectTag: NXObject) -> None: ...


class Container(NXObject):
    def __init__(self) -> None: ...
    def GetMembers(self, members: typing.List[NXObject]) -> None: ...
    def Reorder(self, source: NXObject, target: NXObject, type: Features.TopologyOptimization.Container.ReorderType) -> None: ...


    class ReorderType(enum.Enum):
        Before= 0
        After= 1
        Into= 2
    

class ConstructionBodyCollector(NXObject):
    def __init__(self) -> None: ...
    def AddMember(self, bFromCollectorToCollector: bool, constructionBody: Features.TopologyOptimization.ConstructionBody) -> None: ...
    def RemoveMember(self, bFromCollectorToCollector: bool, constructionBody: Features.TopologyOptimization.ConstructionBody) -> None: ...
    def Ungroup(self) -> None: ...


class ConstructionBodyBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def BlendRadius(self) -> Expression: ...
    @BlendRadius.setter
    def BlendRadius(self, value: Expression) -> None: ...
    @property
    def Bodies(self) -> SelectBodyList: ...
    @Bodies.setter
    def Bodies(self, value: SelectBodyList) -> None: ...
    @property
    def BodyCollector(self) -> ScCollector: ...
    @BodyCollector.setter
    def BodyCollector(self, value: ScCollector) -> None: ...
    @property
    def DesignSpace(self) -> Features.TopologyOptimization.DesignSpace: ...
    @DesignSpace.setter
    def DesignSpace(self, value: Features.TopologyOptimization.DesignSpace) -> None: ...
    @property
    def GroupingOption(self) -> Features.TopologyOptimization.ConstructionBodyBuilder.GroupingType: ...
    @GroupingOption.setter
    def GroupingOption(self, value: Features.TopologyOptimization.ConstructionBodyBuilder.GroupingType) -> None: ...
    @property
    def Method(self) -> Features.TopologyOptimization.ConstructionBodyBuilder.MethodOption: ...
    @Method.setter
    def Method(self, value: Features.TopologyOptimization.ConstructionBodyBuilder.MethodOption) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Offset(self) -> Expression: ...
    @Offset.setter
    def Offset(self, value: Expression) -> None: ...
    @property
    def OffsetEdgesType(self) -> Features.TopologyOptimization.ConstructionBodyBuilder.OffsetType: ...
    @OffsetEdgesType.setter
    def OffsetEdgesType(self, value: Features.TopologyOptimization.ConstructionBodyBuilder.OffsetType) -> None: ...
    @property
    def WallThickness(self) -> Expression: ...
    @WallThickness.setter
    def WallThickness(self, value: Expression) -> None: ...


    class OffsetType(enum.Enum):
        None_= 0
        WithRadius= 1
    

    class MethodOption(enum.Enum):
        KeepIn= 0
        KeepOut= 1
        Shell= 2
    

    class GroupingType(enum.Enum):
        Separate= 0
        Collection= 1
    

class ConstructionBody(NXObject):
    def __init__(self) -> None: ...


class ConnectionBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def ConnectionName(self) -> str: ...
    @ConnectionName.setter
    def ConnectionName(self, value: str) -> None: ...
    @property
    def SelectBody1(self) -> SelectBody: ...
    @SelectBody1.setter
    def SelectBody1(self, value: SelectBody) -> None: ...
    @property
    def SelectBody2(self) -> SelectBody: ...
    @SelectBody2.setter
    def SelectBody2(self, value: SelectBody) -> None: ...
    @property
    def SelectFaces1(self) -> ScCollector: ...
    @SelectFaces1.setter
    def SelectFaces1(self, value: ScCollector) -> None: ...
    @property
    def SelectFaces2(self) -> ScCollector: ...
    @SelectFaces2.setter
    def SelectFaces2(self, value: ScCollector) -> None: ...
    @property
    def ShellOffset1(self) -> Expression: ...
    @ShellOffset1.setter
    def ShellOffset1(self, value: Expression) -> None: ...
    @property
    def ShellOffset2(self) -> Expression: ...
    @ShellOffset2.setter
    def ShellOffset2(self, value: Expression) -> None: ...
    @property
    def Type(self) -> Features.TopologyOptimization.ConnectionBuilder.Types: ...
    @Type.setter
    def Type(self, value: Features.TopologyOptimization.ConnectionBuilder.Types) -> None: ...
    @property
    def UserSetName(self) -> bool: ...
    @UserSetName.setter
    def UserSetName(self, value: bool) -> None: ...


    class Types(enum.Enum):
        BodyToBody= 0
        FaceToFace= 1
    

class Connection(NXObject):
    def __init__(self) -> None: ...


class AnimationController(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def AnimateContour(self, animState: Features.TopologyOptimization.AnimationController.State) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def FullCycle(self) -> bool: ...
    @FullCycle.setter
    def FullCycle(self, value: bool) -> None: ...


    class State(enum.Enum):
        Play= 0
        Stop= 1
        Pause= 2
        Next= 3
        Previous= 4
    

class AnalysisLoadBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Acceleration(self) -> Expression: ...
    @Acceleration.setter
    def Acceleration(self, value: Expression) -> None: ...
    @property
    def BearingAngular(self) -> Expression: ...
    @BearingAngular.setter
    def BearingAngular(self, value: Expression) -> None: ...
    @property
    def FaceVector(self) -> Direction: ...
    @FaceVector.setter
    def FaceVector(self, value: Direction) -> None: ...
    @property
    def Force(self) -> Expression: ...
    @Force.setter
    def Force(self, value: Expression) -> None: ...
    @property
    def ForceType(self) -> Features.TopologyOptimization.AnalysisLoadBuilder.AnalysisLoadForceType: ...
    @ForceType.setter
    def ForceType(self, value: Features.TopologyOptimization.AnalysisLoadBuilder.AnalysisLoadForceType) -> None: ...
    @property
    def ForceX(self) -> Expression: ...
    @ForceX.setter
    def ForceX(self, value: Expression) -> None: ...
    @property
    def ForceY(self) -> Expression: ...
    @ForceY.setter
    def ForceY(self, value: Expression) -> None: ...
    @property
    def ForceZ(self) -> Expression: ...
    @ForceZ.setter
    def ForceZ(self, value: Expression) -> None: ...
    @property
    def MaxDisplacement(self) -> Expression: ...
    @MaxDisplacement.setter
    def MaxDisplacement(self, value: Expression) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Pressure(self) -> Expression: ...
    @Pressure.setter
    def Pressure(self, value: Expression) -> None: ...
    @property
    def ReverseBearingLoadDirection(self) -> bool: ...
    @ReverseBearingLoadDirection.setter
    def ReverseBearingLoadDirection(self, value: bool) -> None: ...
    @property
    def ReversePressureDirection(self) -> bool: ...
    @ReversePressureDirection.setter
    def ReversePressureDirection(self, value: bool) -> None: ...
    @property
    def SelectFace(self) -> ScCollector: ...
    @SelectFace.setter
    def SelectFace(self, value: ScCollector) -> None: ...
    @property
    def Torque(self) -> Expression: ...
    @Torque.setter
    def Torque(self, value: Expression) -> None: ...
    @property
    def TorqueAxis(self) -> Axis: ...
    @TorqueAxis.setter
    def TorqueAxis(self, value: Axis) -> None: ...
    @property
    def Type(self) -> Features.TopologyOptimization.AnalysisLoadBuilder.AnalysisLoadType: ...
    @Type.setter
    def Type(self, value: Features.TopologyOptimization.AnalysisLoadBuilder.AnalysisLoadType) -> None: ...
    @property
    def UserSetName(self) -> bool: ...
    @UserSetName.setter
    def UserSetName(self, value: bool) -> None: ...


    class AnalysisLoadType(enum.Enum):
        Force= 0
        BearingLoad= 1
        Pressure= 2
        Torque= 3
        Acceleration= 4
        EnforcedDisplacement= 5
    

    class AnalysisLoadForceType(enum.Enum):
        ByVector= 0
        ByComponent= 1
    

class AnalysisLoad(NXObject):
    def __init__(self) -> None: ...


class AnalysisConstraintBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def LinearSliderVector(self) -> Direction: ...
    @LinearSliderVector.setter
    def LinearSliderVector(self, value: Direction) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def PinnedAxis(self) -> Axis: ...
    @PinnedAxis.setter
    def PinnedAxis(self, value: Axis) -> None: ...
    @property
    def PlanarSliderPlane(self) -> Plane: ...
    @PlanarSliderPlane.setter
    def PlanarSliderPlane(self, value: Plane) -> None: ...
    @property
    def SelectFace(self) -> ScCollector: ...
    @SelectFace.setter
    def SelectFace(self, value: ScCollector) -> None: ...
    @property
    def Type(self) -> Features.TopologyOptimization.AnalysisConstraintBuilder.ConstraintType: ...
    @Type.setter
    def Type(self, value: Features.TopologyOptimization.AnalysisConstraintBuilder.ConstraintType) -> None: ...
    @property
    def UserSetName(self) -> bool: ...
    @UserSetName.setter
    def UserSetName(self, value: bool) -> None: ...


    class ConstraintType(enum.Enum):
        Fixed= 0
        Pinned= 1
        PinnedSlider= 2
        LinearSlider= 3
        PlanarSlider= 4
    

class AnalysisConstraint(NXObject):
    def __init__(self) -> None: ...


