from ....NXOpen import *
from ...CAE import *

import typing
import enum

class TranslateNodesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Csys(self) -> CoordinateSystem: ...
    @Csys.setter
    def Csys(self, value: CoordinateSystem) -> None: ...
    @property
    def DirectionVector(self) -> Direction: ...
    @DirectionVector.setter
    def DirectionVector(self, value: Direction) -> None: ...
    @property
    def Distance(self) -> Expression: ...
    @Distance.setter
    def Distance(self, value: Expression) -> None: ...
    @property
    def Method(self) -> CAE.PenetrationCheck.TranslateNodesBuilder.MethodOptions: ...
    @Method.setter
    def Method(self, value: CAE.PenetrationCheck.TranslateNodesBuilder.MethodOptions) -> None: ...
    @property
    def MoveAdjacentNodes(self) -> bool: ...
    @MoveAdjacentNodes.setter
    def MoveAdjacentNodes(self, value: bool) -> None: ...
    @property
    def NumberOfLayers(self) -> Expression: ...
    @NumberOfLayers.setter
    def NumberOfLayers(self, value: Expression) -> None: ...
    @property
    def PAngle(self) -> Expression: ...
    @PAngle.setter
    def PAngle(self, value: Expression) -> None: ...
    @property
    def PointSource(self) -> Point: ...
    @PointSource.setter
    def PointSource(self, value: Point) -> None: ...
    @property
    def PointTarget(self) -> Point: ...
    @PointTarget.setter
    def PointTarget(self, value: Point) -> None: ...
    @property
    def SelectNodes(self) -> CAE.SelectFENodeList: ...
    @SelectNodes.setter
    def SelectNodes(self, value: CAE.SelectFENodeList) -> None: ...
    @property
    def TAngle(self) -> Expression: ...
    @TAngle.setter
    def TAngle(self, value: Expression) -> None: ...
    @property
    def VectorSource(self) -> Direction: ...
    @VectorSource.setter
    def VectorSource(self, value: Direction) -> None: ...
    @property
    def VectorTarget(self) -> Direction: ...
    @VectorTarget.setter
    def VectorTarget(self, value: Direction) -> None: ...
    @property
    def XDistance(self) -> Expression: ...
    @XDistance.setter
    def XDistance(self, value: Expression) -> None: ...
    @property
    def XScaleFactor(self) -> float: ...
    @XScaleFactor.setter
    def XScaleFactor(self, value: float) -> None: ...
    @property
    def YDistance(self) -> Expression: ...
    @YDistance.setter
    def YDistance(self, value: Expression) -> None: ...
    @property
    def YScaleFactor(self) -> float: ...
    @YScaleFactor.setter
    def YScaleFactor(self, value: float) -> None: ...
    @property
    def ZDistance(self) -> Expression: ...
    @ZDistance.setter
    def ZDistance(self, value: Expression) -> None: ...
    @property
    def ZScaleFactor(self) -> float: ...
    @ZScaleFactor.setter
    def ZScaleFactor(self, value: float) -> None: ...


    class MethodOptions(enum.Enum):
        AlongNodeNormals= 0
        OppositeofNodeNormals= 1
        AlongDirection= 2
        WithOrientation= 3
        PointToPoint= 4
        AlignVectors= 5
        ScaleModel= 6
    

class ResultObject(NXObject):
    def __init__(self) -> None: ...
    def FreezeComponent(self, compToFreeze: int) -> None: ...
    def DeleteResultObject(self) -> None: ...


class ResultList(NXObject):
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> INXObject: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class Manager(Utilities.NXRemotableObject):
    def __init__(self, owner: CAE.CaeSession) -> None: ...
    def FindObject(self, journalIdentifier: str) -> INXObject: ...
    def ClearManager(self, num: int) -> None: ...
    def RefreshResults(self, pObjects: typing.List[CAE.PenetrationCheck.ResultObject]) -> None: ...
    def ResultObjectAutomaticResolve(self, pObjects: typing.List[CAE.PenetrationCheck.ResultObject]) -> None: ...
    def PlotContours(self, viewIndex: int, pObjects: typing.List[CAE.PenetrationCheck.ResultObject]) -> None: ...
    def Tag(self) -> Tag: ...

    @property
    def ActiveSet(self) -> CAE.PenetrationCheck.AnalysisSet: ...
    @ActiveSet.setter
    def ActiveSet(self, value: CAE.PenetrationCheck.AnalysisSet) -> None: ...


class AutomaticResolveBuilder(Builder):
    def __init__(self) -> None: ...
    def ResolveButton(self) -> None: ...
    @property
    def MaxInterference(self) -> Expression: ...
    @MaxInterference.setter
    def MaxInterference(self, value: Expression) -> None: ...
    @property
    def MeshesToFreeze(self) -> SelectNXObjectList: ...
    @MeshesToFreeze.setter
    def MeshesToFreeze(self, value: SelectNXObjectList) -> None: ...
    @property
    def MinInterference(self) -> Expression: ...
    @MinInterference.setter
    def MinInterference(self, value: Expression) -> None: ...
    @property
    def ResolveOptions(self) -> CAE.PenetrationCheck.AutomaticResolveBuilder.ResolveType: ...
    @ResolveOptions.setter
    def ResolveOptions(self, value: CAE.PenetrationCheck.AutomaticResolveBuilder.ResolveType) -> None: ...


    class ResolveType(enum.Enum):
        All= 0
        WithinLimits= 1
    

class AutomaticResolve(DisplayableObject):
    def __init__(self) -> None: ...


class AnalysisSet(NXObject):
    def __init__(self) -> None: ...
    def DeleteSet(self) -> None: ...
    def ChangeActiveSet(self) -> None: ...
    def RunInterferenceCheck(self) -> None: ...
    def PlotContours(self, viewIndex: int) -> None: ...
    def FindObject(self, journalIdentifier: str) -> INXObject: ...
    def Print(self) -> None: ...


class AddSetBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def BoundaryType(self) -> CAE.PenetrationCheck.AddSetBuilder.ThicknessBoundaryType: ...
    @BoundaryType.setter
    def BoundaryType(self, value: CAE.PenetrationCheck.AddSetBuilder.ThicknessBoundaryType) -> None: ...
    @property
    def ElemThickness(self) -> Expression: ...
    @ElemThickness.setter
    def ElemThickness(self, value: Expression) -> None: ...
    @property
    def InterferenceBetween(self) -> CAE.PenetrationCheck.AddSetBuilder.InterferenceBetweenType: ...
    @InterferenceBetween.setter
    def InterferenceBetween(self, value: CAE.PenetrationCheck.AddSetBuilder.InterferenceBetweenType) -> None: ...
    @property
    def InterferenceOption(self) -> CAE.PenetrationCheck.AddSetBuilder.InterferenceType: ...
    @InterferenceOption.setter
    def InterferenceOption(self, value: CAE.PenetrationCheck.AddSetBuilder.InterferenceType) -> None: ...
    @property
    def PenetrationSetName(self) -> str: ...
    @PenetrationSetName.setter
    def PenetrationSetName(self, value: str) -> None: ...
    @property
    def Selection(self) -> SelectNXObjectList: ...
    @Selection.setter
    def Selection(self, value: SelectNXObjectList) -> None: ...
    @property
    def SelectionType(self) -> CAE.PenetrationCheck.AddSetBuilder.SelectionTypeOptions: ...
    @SelectionType.setter
    def SelectionType(self, value: CAE.PenetrationCheck.AddSetBuilder.SelectionTypeOptions) -> None: ...
    @property
    def SelfInterferenceOption(self) -> bool: ...
    @SelfInterferenceOption.setter
    def SelfInterferenceOption(self, value: bool) -> None: ...
    @property
    def ThicknessFactor(self) -> Expression: ...
    @ThicknessFactor.setter
    def ThicknessFactor(self, value: Expression) -> None: ...
    @property
    def ThicknessSource(self) -> CAE.PenetrationCheck.AddSetBuilder.ThicknessSourceType: ...
    @ThicknessSource.setter
    def ThicknessSource(self, value: CAE.PenetrationCheck.AddSetBuilder.ThicknessSourceType) -> None: ...


    class ThicknessSourceType(enum.Enum):
        ElementAssociatedData= 0
        UserDefined= 1
    

    class ThicknessBoundaryType(enum.Enum):
        Sharp= 0
        Round= 1
    

    class SelectionTypeOptions(enum.Enum):
        MeshObjects= 0
        ContactDefinitions= 1
    

    class InterferenceType(enum.Enum):
        All= 0
        Intersections= 1
        Penetrations= 2
    

    class InterferenceBetweenType(enum.Enum):
        MeshCollectorContainers= 0
        Meshes= 1
        ComponentFEMs= 2
    

class AddSet(DisplayableObject):
    def __init__(self) -> None: ...


