from ...NXOpen import *

import typing
import enum

class StructureDesignSession(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def Tag(self) -> Tag: ...

    @property
    def ContextMenu(self) -> StructureDesign.ContextMenu: ...
    @ContextMenu.setter
    def ContextMenu(self, value: StructureDesign.ContextMenu) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class FrameTaskEnvironment(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def Enter(self) -> None: ...
    def Exit(self) -> None: ...
    def SetCancelled(self) -> None: ...
    def Edit(self, feature: Features.StructureDesign.SuperFrame) -> None: ...
    def Tag(self) -> Tag: ...

    @property
    def ActiveFeature(self) -> Features.StructureDesign.SuperFrame: ...
    @ActiveFeature.setter
    def ActiveFeature(self, value: Features.StructureDesign.SuperFrame) -> None: ...
    @property
    def BaseType(self) -> Features.StructureDesign.SuperFrameBuilder.BaseTypes: ...
    @BaseType.setter
    def BaseType(self, value: Features.StructureDesign.SuperFrameBuilder.BaseTypes) -> None: ...
    @property
    def TransformType(self) -> Features.StructureDesign.SuperFrameBuilder.TransformTypes: ...
    @TransformType.setter
    def TransformType(self, value: Features.StructureDesign.SuperFrameBuilder.TransformTypes) -> None: ...


class ContextMenu(Utilities.NXRemotableObject):
    def __init__(self, owner: StructureDesign.StructureDesignSession) -> None: ...
    def UpdateStructure(self, curves: typing.List[NXObject]) -> None: ...
    def PackMemberNodes(self, tgNodes: typing.List[ShipDesign.NavigatorNode], tgStructurePart: BasePart) -> None: ...
    def UnpackMemberNodes(self, tgNodes: typing.List[ShipDesign.NavigatorNode], tgStructurePart: BasePart) -> None: ...
    def RemoveConsolidateList(self, consolidateListNodeTag: ShipDesign.NavigatorNode) -> None: ...
    def RemoveFeaturesInsideEndCapComponents(self, components: typing.List[Assemblies.Component]) -> None: ...
    def RemoveFeaturesInsideMemberComponents(self, components: typing.List[Assemblies.Component]) -> None: ...
    def RemoveFeaturesInsideMountingFeetComponents(self, components: typing.List[Assemblies.Component]) -> None: ...
    def RemoveFeaturesInsideBoltedConnectionComponents(self, components: typing.List[Assemblies.Component]) -> None: ...
    def RemoveFeaturesInsideStiffenerComponents(self, components: typing.List[Assemblies.Component]) -> None: ...
    def Tag(self) -> Tag: ...



