from ....NXOpen import *
from ...CAE import *

import typing
import enum

class XYZFunctionDataAccessor(CAE.Xyplot.IFunctionDataAccessor):
    def __init__(self, ptr: int) -> None: ...
    def AskSectionCount(self) -> int: ...
    def AskSectionDisplayData(self, sectionIndex: int, indenpendent1Values: float, indenpendent2Value: float, dependentValues: float) -> None: ...


class XYPlotManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def PlotRecords(self, plotParameters: CAE.Xyplot.PlotParameters) -> CAE.Xyplot.Plot: ...
    def OverlayRecords(self, overlayParameters: CAE.Xyplot.OverlayParameters) -> CAE.Xyplot.Plot: ...
    def GetCurrentPlot(self, deviceIndex: int, viewIndex: int) -> CAE.Xyplot.Plot: ...
    def ShowNextPlot(self, deviceIndex: int, viewIndex: int) -> None: ...
    def ShowPreviousPlot(self, deviceIndex: int, viewIndex: int) -> None: ...
    def NewPlotParameters(self) -> CAE.Xyplot.PlotParameters: ...
    def NewOverlayParameters(self) -> CAE.Xyplot.OverlayParameters: ...
    def GetAvailableWindowDevices(self) -> int: ...
    def GetWindowDevicesViews(self, windowDevice: int) -> int: ...
    def GetPlots(self, windowDevice: int, view: int) -> typing.List[CAE.Xyplot.Plot]: ...
    def ReturnToModelView(self, view: int) -> None: ...
    def WriteImageToClipBoard(self, deviceIndex: int, viewIndex: int, isUseWhiteBackGround: bool) -> None: ...
    def FindObject(self, journalIdentifier: str) -> CAE.Xyplot.Plot: ...
    def MakeCurrentPlot(self, plot: CAE.Xyplot.Plot) -> None: ...
    def AlignAxesOfPlots(self, part: BasePart) -> None: ...
    def CreateResultAccessor(self, plot: CAE.Xyplot.Plot) -> CAE.Xyplot.ResultAccessor: ...
    def CreateResultAccessorOnCanvas(self, plot: CAE.Xyplot.Plot, canvasIndex: int) -> CAE.Xyplot.ResultAccessor: ...
    def Tag(self) -> Tag: ...

    @property
    def WindowManager(self) -> CAE.Xyplot.WindowManager: ...
    @WindowManager.setter
    def WindowManager(self, value: CAE.Xyplot.WindowManager) -> None: ...
    @property
    def DataExporter(self) -> CAE.Xyplot.DataExporter: ...
    @DataExporter.setter
    def DataExporter(self, value: CAE.Xyplot.DataExporter) -> None: ...
    @property
    def AutotestUtils(self) -> CAE.Xyplot.AutotestUtils: ...
    @AutotestUtils.setter
    def AutotestUtils(self, value: CAE.Xyplot.AutotestUtils) -> None: ...
    @property
    def Preference(self) -> CAE.Xyplot.Preference: ...
    @Preference.setter
    def Preference(self, value: CAE.Xyplot.Preference) -> None: ...
    @property
    def TemplateManager(self) -> CAE.Xyplot.BaseTemplateManager: ...
    @TemplateManager.setter
    def TemplateManager(self, value: CAE.Xyplot.BaseTemplateManager) -> None: ...


class XYFunctionDataAccessor(CAE.Xyplot.IFunctionDataAccessor):
    def __init__(self, ptr: int) -> None: ...
    def AskDisplayData(self, indenpendentValue: float, dependentValue: float) -> None: ...


class WindowManager(Utilities.NXRemotableObject):
    def __init__(self, owner: CAE.Xyplot.XYPlotManager) -> None: ...
    def NewWindow(self) -> int: ...
    def CloseWindow(self, deviceIndex: int) -> None: ...
    def GetWindows(self) -> int: ...
    def GetWindowTitle(self, deviceIndex: int) -> str: ...
    def SetWindowTitle(self, deviceIndex: int, windowTitle: str) -> None: ...
    def Tag(self) -> Tag: ...



class WallDisplayStyles3D(CAE.Xyplot.WallDisplayStyles):
    def __init__(self) -> None: ...
    @property
    def ViewOrientation(self) -> Matrix3x3: ...
    @ViewOrientation.setter
    def ViewOrientation(self, value: Matrix3x3) -> None: ...


class WallDisplayStyles2D(CAE.Xyplot.WallDisplayStyles):
    def __init__(self) -> None: ...
    def GetAngleAxisStyleSetting(self) -> CAE.Xyplot.AngleAxisStyleSetting: ...
    def GetFormulaGridStyle(self) -> CAE.Xyplot.FormulaGridStyle: ...


class WallDisplayStyles(TaggedObject):
    def __init__(self) -> None: ...
    def GetTextStyleSetting(self, textType: CAE.Xyplot.TextType) -> CAE.Xyplot.TextStyleSetting: ...
    def GetLegendTableGroupStyle(self) -> CAE.Xyplot.LegendTableGroupStyle: ...
    def GetCalculationLegendTableStyle(self) -> CAE.Xyplot.LegendTableStyle: ...
    def GetAxisStyle(self, axisDirection: CAE.Xyplot.AxisDirection) -> CAE.Xyplot.IAxisStyle: ...
    @property
    def GridLayoutStyleSetting(self) -> CAE.Xyplot.BaseGridLayoutStyleSetting: ...
    @GridLayoutStyleSetting.setter
    def GridLayoutStyleSetting(self, value: CAE.Xyplot.BaseGridLayoutStyleSetting) -> None: ...
    @property
    def PanStyle(self) -> CAE.Xyplot.PanStyle: ...
    @PanStyle.setter
    def PanStyle(self, value: CAE.Xyplot.PanStyle) -> None: ...
    @property
    def ProbingStyle(self) -> CAE.Xyplot.ProbingStyle: ...
    @ProbingStyle.setter
    def ProbingStyle(self, value: CAE.Xyplot.ProbingStyle) -> None: ...


class VectorStyle2DSetting(CAE.Xyplot.BaseLineStyleSetting):
    def __init__(self) -> None: ...
    def GetVectorColors(self) -> typing.List[NXColor]: ...
    def SetVectorColors(self, vectorColors: typing.List[NXColor]) -> None: ...
    def GetNthVectorColor(self, index: int) -> NXColor: ...
    def SetNthVectorColors(self, index: int, vectorColors: NXColor) -> None: ...
    @property
    def DrawText(self) -> bool: ...
    @DrawText.setter
    def DrawText(self, value: bool) -> None: ...
    @property
    def IsAutoTextCount(self) -> bool: ...
    @IsAutoTextCount.setter
    def IsAutoTextCount(self, value: bool) -> None: ...
    @property
    def MaximumTextCount(self) -> int: ...
    @MaximumTextCount.setter
    def MaximumTextCount(self, value: int) -> None: ...
    @property
    def OverlapTextAndVector(self) -> bool: ...
    @OverlapTextAndVector.setter
    def OverlapTextAndVector(self, value: bool) -> None: ...


class UnknownResultColor(enum.Enum):
    White= 0
    Grey= 1


class TextType(enum.Enum):
    None_= 0
    Title= 1
    Legend= 2
    GraphName= 3
    PageNumber= 4
    Marker= 5
    Note= 6
    ProbingText= 7
    XLabel= 8
    YLabel= 9
    ZLabel= 10
    XNumber= 11
    YNumber= 12
    ZNumber= 13
    ColorAxisLabel= 14
    ColorAxisNumber= 15
    UnknownResultText= 16
    AngleAxisNumber= 17
    AnnotationText= 18
    ArgumentAxisNumber= 19
    BarChartValueText= 20
    LegendTableText= 21
    ResultLegendText= 22
    FormulaGridValueText= 23


class TextStyleSetting(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    @property
    def Alignment(self) -> CAE.Xyplot.TextAlignment: ...
    @Alignment.setter
    def Alignment(self, value: CAE.Xyplot.TextAlignment) -> None: ...
    @property
    def Color(self) -> NXColor: ...
    @Color.setter
    def Color(self, value: NXColor) -> None: ...
    @property
    def Font(self) -> str: ...
    @Font.setter
    def Font(self, value: str) -> None: ...
    @property
    def FontStyle(self) -> Preferences.VisualizationFonts.StyleType: ...
    @FontStyle.setter
    def FontStyle(self, value: Preferences.VisualizationFonts.StyleType) -> None: ...
    @property
    def FontType(self) -> CAE.Xyplot.Fonttype: ...
    @FontType.setter
    def FontType(self, value: CAE.Xyplot.Fonttype) -> None: ...
    @property
    def GlobalSizeScale(self) -> float: ...
    @GlobalSizeScale.setter
    def GlobalSizeScale(self, value: float) -> None: ...
    @property
    def IsGlobalSizeAutoScaled(self) -> bool: ...
    @IsGlobalSizeAutoScaled.setter
    def IsGlobalSizeAutoScaled(self, value: bool) -> None: ...
    @property
    def LeaderStyle(self) -> CAE.Xyplot.LeaderStyle: ...
    @LeaderStyle.setter
    def LeaderStyle(self, value: CAE.Xyplot.LeaderStyle) -> None: ...
    @property
    def NumberFormat(self) -> CAE.NumberFormat: ...
    @NumberFormat.setter
    def NumberFormat(self, value: CAE.NumberFormat) -> None: ...
    @property
    def Orientation(self) -> CAE.Xyplot.TextOrientation: ...
    @Orientation.setter
    def Orientation(self, value: CAE.Xyplot.TextOrientation) -> None: ...
    @property
    def Size(self) -> int: ...
    @Size.setter
    def Size(self, value: int) -> None: ...
    @property
    def TextBoxStyle(self) -> CAE.Xyplot.TextBoxStyleSetting: ...
    @TextBoxStyle.setter
    def TextBoxStyle(self, value: CAE.Xyplot.TextBoxStyleSetting) -> None: ...
    @property
    def UseGlobalFontSetting(self) -> bool: ...
    @UseGlobalFontSetting.setter
    def UseGlobalFontSetting(self, value: bool) -> None: ...
    @property
    def Weight(self) -> Display.TransientText.TextSize: ...
    @Weight.setter
    def Weight(self, value: Display.TransientText.TextSize) -> None: ...
    @property
    def Visibility(self) -> bool: ...
    @Visibility.setter
    def Visibility(self, value: bool) -> None: ...


class TextOrientation(enum.Enum):
    Horizontal= 0
    Upward= 1
    Downward= 2


class TextBoxStyleSetting(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    def GetLineStyle(self) -> CAE.Xyplot.CurveDisplaySettings: ...
    def GetMargin(self, marginOption: CAE.Xyplot.TextBoxMarginOption) -> float: ...
    def SetMargin(self, marginOption: CAE.Xyplot.TextBoxMarginOption, marginValue: float) -> None: ...
    @property
    def Color(self) -> NXColor: ...
    @Color.setter
    def Color(self, value: NXColor) -> None: ...
    @property
    def FillingColor(self) -> NXColor: ...
    @FillingColor.setter
    def FillingColor(self, value: NXColor) -> None: ...
    @property
    def IsFilled(self) -> bool: ...
    @IsFilled.setter
    def IsFilled(self, value: bool) -> None: ...
    @property
    def Visibility(self) -> bool: ...
    @Visibility.setter
    def Visibility(self, value: bool) -> None: ...


class TextBoxMarginOption(enum.Enum):
    Left= 0
    Top= 1
    Right= 2
    Bottom= 3


class TextAlignment(enum.Enum):
    Left= 0
    Center= 1
    Right= 2


class SurfaceStyleSetting(CAE.Xyplot.BaseSymbolStyleSetting):
    def __init__(self) -> None: ...
    @property
    def ColorOption(self) -> CAE.Xyplot.SurfaceColorOption: ...
    @ColorOption.setter
    def ColorOption(self, value: CAE.Xyplot.SurfaceColorOption) -> None: ...
    @property
    def FillingColor(self) -> NXColor: ...
    @FillingColor.setter
    def FillingColor(self, value: NXColor) -> None: ...
    @property
    def OutlineColor(self) -> NXColor: ...
    @OutlineColor.setter
    def OutlineColor(self, value: NXColor) -> None: ...


class SurfaceColorOption(enum.Enum):
    None_= 0
    Hidden= 1
    Shaded= 2


class StackedPlot(CAE.Xyplot.Plot):
    def __init__(self) -> None: ...
    def GetSubplotCount(self) -> int: ...
    def GetPostEnvironmentSettingsOfSubplot(self, plotIndex: int) -> TaggedObject: ...
    def EditRecord(self, nthRecordIdx: int, record: CAE.FTK.BaseRecord) -> None: ...


class SourceDataExportParameters(CAE.Xyplot.DataExportParameters):
    def __init__(self, ptr: int) -> None: ...
    def GetSectionDataIndices(self) -> int: ...
    def SetSectionDataIndices(self, sectionDataIndices: int) -> None: ...
    @property
    def ComplexDataSaveSetting(self) -> CAE.Xyplot.SourceDataExportParameters.ComplextDataSaveOption: ...
    @ComplexDataSaveSetting.setter
    def ComplexDataSaveSetting(self, value: CAE.Xyplot.SourceDataExportParameters.ComplextDataSaveOption) -> None: ...


    class ComplextDataSaveOption(enum.Enum):
        RealImag= 0
        MagPhase= 1
    

class SoundPlayer(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def Play(self) -> None: ...
    def Stop(self) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def Cyclestate(self) -> bool: ...
    @Cyclestate.setter
    def Cyclestate(self, value: bool) -> None: ...


class ScatterStyleSetting(CAE.Xyplot.BaseSymbolStyleSetting):
    def __init__(self) -> None: ...
    @property
    def Color(self) -> NXColor: ...
    @Color.setter
    def Color(self, value: NXColor) -> None: ...


class ResultLegendStyle(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    @property
    def OverflowResultColorOption(self) -> CAE.Xyplot.FlowResultColor: ...
    @OverflowResultColorOption.setter
    def OverflowResultColorOption(self, value: CAE.Xyplot.FlowResultColor) -> None: ...
    @property
    def OverflowResultShadedColor(self) -> NXColor: ...
    @OverflowResultShadedColor.setter
    def OverflowResultShadedColor(self, value: NXColor) -> None: ...
    @property
    def UnderflowResultColorOption(self) -> CAE.Xyplot.FlowResultColor: ...
    @UnderflowResultColorOption.setter
    def UnderflowResultColorOption(self, value: CAE.Xyplot.FlowResultColor) -> None: ...
    @property
    def UnderflowResultShadedColor(self) -> NXColor: ...
    @UnderflowResultShadedColor.setter
    def UnderflowResultShadedColor(self, value: NXColor) -> None: ...
    @property
    def UnknownResultColorOption(self) -> CAE.Xyplot.UnknownResultColor: ...
    @UnknownResultColorOption.setter
    def UnknownResultColorOption(self, value: CAE.Xyplot.UnknownResultColor) -> None: ...
    @property
    def Visibility(self) -> bool: ...
    @Visibility.setter
    def Visibility(self, value: bool) -> None: ...


class ResultAccessor(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def AskFunctionDataAccessorType(self, graphIndex: int, recordIndex: int) -> CAE.Xyplot.FunctionDataAccessor: ...
    def AskXYFunctionDataAccessor(self, graphIndex: int, recordIndex: int) -> CAE.Xyplot.XYFunctionDataAccessor: ...
    def AskArgand3DFunctionDataAccessor(self, graphIndex: int, recordIndex: int) -> CAE.Xyplot.Argand3DFunctionDataAccessor: ...
    def AskXYZFunctionDataAccessor(self, graphIndex: int, recordIndex: int) -> CAE.Xyplot.XYZFunctionDataAccessor: ...
    def AskBarChartFunctionDataAccessor(self, graphIndex: int, recordIndex: int) -> CAE.Xyplot.BarChartFunctionDataAccessor: ...
    def AskMatrixFunctionDataAccessor(self, graphIndex: int, recordIndex: int) -> CAE.Xyplot.MatrixFunctionDataAccessor: ...
    def AskCampbellFunctionDataAccessor(self, graphIndex: int, recordIndex: int) -> CAE.Xyplot.CampbellFunctionDataAccessor: ...
    def AskPostEnvironment(self) -> TaggedObject: ...
    def GetNthGraph(self, graphIdx: int) -> CAE.Xyplot.Graph: ...
    def FreeResource(self) -> None: ...
    @property
    def CanvasIndex(self) -> int: ...
    @CanvasIndex.setter
    def CanvasIndex(self, value: int) -> None: ...
    @property
    def GraphCount(self) -> int: ...
    @GraphCount.setter
    def GraphCount(self, value: int) -> None: ...
    @property
    def OnCanvas(self) -> bool: ...
    @OnCanvas.setter
    def OnCanvas(self, value: bool) -> None: ...
    @property
    def Plot(self) -> CAE.Xyplot.Plot: ...
    @Plot.setter
    def Plot(self, value: CAE.Xyplot.Plot) -> None: ...
    @property
    def RecordCount(self) -> int: ...
    @RecordCount.setter
    def RecordCount(self, value: int) -> None: ...


class ProbingStyle(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    @property
    def HelpLineStyle(self) -> CAE.Xyplot.CurveDisplaySettings: ...
    @HelpLineStyle.setter
    def HelpLineStyle(self, value: CAE.Xyplot.CurveDisplaySettings) -> None: ...
    @property
    def StepLineStyle(self) -> CAE.Xyplot.CurveDisplaySettings: ...
    @StepLineStyle.setter
    def StepLineStyle(self, value: CAE.Xyplot.CurveDisplaySettings) -> None: ...
    @property
    def TextStyle(self) -> CAE.Xyplot.TextStyleSetting: ...
    @TextStyle.setter
    def TextStyle(self, value: CAE.Xyplot.TextStyleSetting) -> None: ...


class Preference(TaggedObject):
    def __init__(self) -> None: ...
    def Save(self) -> None: ...
    @property
    def AfuRecordZValue(self) -> CAE.FTK.DataManager.AfuRecordZValue: ...
    @AfuRecordZValue.setter
    def AfuRecordZValue(self, value: CAE.FTK.DataManager.AfuRecordZValue) -> None: ...
    @property
    def MaximumDisplayableColumnsInMatrix(self) -> int: ...
    @MaximumDisplayableColumnsInMatrix.setter
    def MaximumDisplayableColumnsInMatrix(self, value: int) -> None: ...
    @property
    def MaximumDisplayableRowsInMatrix(self) -> int: ...
    @MaximumDisplayableRowsInMatrix.setter
    def MaximumDisplayableRowsInMatrix(self, value: int) -> None: ...
    @property
    def MaximumSubGraphsInStack(self) -> int: ...
    @MaximumSubGraphsInStack.setter
    def MaximumSubGraphsInStack(self, value: int) -> None: ...
    @property
    def NewWindowSetting(self) -> CAE.Xyplot.Preference.NewWindowChoice: ...
    @NewWindowSetting.setter
    def NewWindowSetting(self, value: CAE.Xyplot.Preference.NewWindowChoice) -> None: ...
    @property
    def TargetWindowSetting(self) -> CAE.Xyplot.Preference.TargetGraphicWindowOption: ...
    @TargetWindowSetting.setter
    def TargetWindowSetting(self, value: CAE.Xyplot.Preference.TargetGraphicWindowOption) -> None: ...


    class TargetGraphicWindowOption(enum.Enum):
        Main= 0
        Separate= 1
        Both= 2
    

    class NewWindowChoice(enum.Enum):
        Prompt= 0
        Always= 1
    

class PointMarker(enum.Enum):
    None_= 0
    Plus= 1
    Dot= 2
    Asterisk= 3
    Circle= 4
    Poundsign= 5
    Cross= 6
    Square= 7
    Triangle= 8
    Diamond= 9
    CenterLine= 10


class PlotType(enum.Enum):
    Plot2D= 0
    Plot2DInStack= 1
    Plot3D= 2
    PlotColorBar= 3
    PlotColorMap= 4
    PlotBarChart= 5
    PlotMatrix2D= 6
    PlotCampbell= 7


class PlotParameters(CAE.Xyplot.BasePlotParameters):
    def __init__(self, ptr: int) -> None: ...
    @property
    def ComplexOption(self) -> int: ...
    @ComplexOption.setter
    def ComplexOption(self, value: int) -> None: ...
    @property
    def IsToCreateStandalonePlot(self) -> bool: ...
    @IsToCreateStandalonePlot.setter
    def IsToCreateStandalonePlot(self, value: bool) -> None: ...
    @property
    def PlotTemplate(self) -> CAE.Xyplot.PlotGraphTemplate: ...
    @PlotTemplate.setter
    def PlotTemplate(self, value: CAE.Xyplot.PlotGraphTemplate) -> None: ...
    @property
    def PlotType(self) -> CAE.Xyplot.PlotType: ...
    @PlotType.setter
    def PlotType(self, value: CAE.Xyplot.PlotType) -> None: ...


class PlotGraphTemplate(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    def ResetToDefault(self) -> None: ...
    def ImportTemplate(self, strXmlFile: str) -> None: ...
    def ExportTemplate(self, strXmlFile: str) -> None: ...
    @property
    def AbscissaCustomMarkerLabel(self) -> str: ...
    @AbscissaCustomMarkerLabel.setter
    def AbscissaCustomMarkerLabel(self, value: str) -> None: ...
    @property
    def DiagramDisplayStyles(self) -> CAE.Xyplot.DiagramDisplayStyles: ...
    @DiagramDisplayStyles.setter
    def DiagramDisplayStyles(self, value: CAE.Xyplot.DiagramDisplayStyles) -> None: ...
    @property
    def GeneralDisplayStyles(self) -> CAE.Xyplot.GeneralDisplayStyles: ...
    @GeneralDisplayStyles.setter
    def GeneralDisplayStyles(self, value: CAE.Xyplot.GeneralDisplayStyles) -> None: ...
    @property
    def OrdinateCustomMarkerLabel(self) -> str: ...
    @OrdinateCustomMarkerLabel.setter
    def OrdinateCustomMarkerLabel(self, value: str) -> None: ...
    @property
    def WallDisplayStyles(self) -> CAE.Xyplot.WallDisplayStyles: ...
    @WallDisplayStyles.setter
    def WallDisplayStyles(self, value: CAE.Xyplot.WallDisplayStyles) -> None: ...
    @property
    def ZCustomMarkerLabel(self) -> str: ...
    @ZCustomMarkerLabel.setter
    def ZCustomMarkerLabel(self, value: str) -> None: ...


class Plot3D(CAE.Xyplot.Plot):
    def __init__(self) -> None: ...
    def EditRecords(self, records: typing.List[CAE.FTK.BaseRecord]) -> None: ...


class Plot2D(CAE.Xyplot.Plot):
    def __init__(self) -> None: ...
    def EditRecord(self, nthRecordIdx: int, record: CAE.FTK.BaseRecord) -> None: ...


class Plot(CAE.Xyplot.BaseModel):
    def __init__(self) -> None: ...
    def GetRecordCount(self) -> int: ...
    def GetApplicationDataOfRecord(self, recordIndex: int) -> CAE.FTK.IApplicationData: ...
    def SaveRecords(self, recordIndexes: int, recordNames: str, outputFileName: str, reportError: bool) -> None: ...
    def GetDeviceAndViewIndex(self, viewIndex: int) -> int: ...
    def GetGraphs(self, graphs: typing.List[CAE.Xyplot.Graph]) -> None: ...
    def SaveRecordsToCsv(self, recordIndex: int, recordNames: str, csvFileName: str, isWriteHeader: bool) -> None: ...
    def CreateNote(self, lines: str, textPosition: Point2d) -> CAE.Xyplot.NoteModel: ...
    def GetNotes(self) -> typing.List[CAE.Xyplot.NoteModel]: ...
    def GetTitles(self) -> typing.List[CAE.Xyplot.BasicModel]: ...
    def GetViewBoundingBox(self, leftBottom: Point3d, rightTop: Point3d) -> None: ...
    def WriteToTemplateFile(self, inputTemplateFile: str) -> str: ...
    def GetRecordDisplayVisibility(self, recordIndex: int) -> bool: ...
    def SetRecordDisplayVisibility(self, recordIndex: int, visibility: bool) -> None: ...
    def GetModels(self, type: CAE.Xyplot.ModelType) -> typing.List[CAE.Xyplot.BasicModel]: ...
    def FitView(self) -> None: ...
    def DeleteRecord(self, recordIndex: int) -> None: ...
    def DeleteAllRecords(self) -> None: ...
    def CommitRecordsChange(self) -> None: ...
    def GetLegendTables(self) -> typing.List[CAE.Xyplot.LegendTable]: ...
    def GetPostEnvironmentSettings(self) -> TaggedObject: ...
    def GetCalculationLegendTables(self) -> typing.List[CAE.Xyplot.LegendTable]: ...
    @property
    def PlotTemplate(self) -> CAE.Xyplot.PlotGraphTemplate: ...
    @PlotTemplate.setter
    def PlotTemplate(self, value: CAE.Xyplot.PlotGraphTemplate) -> None: ...
    @property
    def SubGraphCountInStack(self) -> int: ...
    @SubGraphCountInStack.setter
    def SubGraphCountInStack(self, value: int) -> None: ...


class PlateColorOption(enum.Enum):
    Fill= 0
    Hidden= 1
    Shaded= 2


class PhaseRangeOption(enum.Enum):
    NegativeTwoPiToZero= 0
    ZeroToTwoPi= 1
    NegativePiToPi= 2
    NegativeOneHalfPiToHalfPi= 3
    NegativeHalfPiToOneHalfPi= 4


class PanToolSize(enum.Enum):
    Small= 0
    Normal= 1
    Large= 2


class PanStyle(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    def GetAnnotationStyle(self) -> CAE.Xyplot.TextStyleSetting: ...
    def GetLabelDisplayStyle(self) -> CAE.Xyplot.CustomTextStyleSetting: ...
    @property
    def ToolPosition(self) -> Point3d: ...
    @ToolPosition.setter
    def ToolPosition(self, value: Point3d) -> None: ...
    @property
    def ToolSize(self) -> CAE.Xyplot.PanToolSize: ...
    @ToolSize.setter
    def ToolSize(self, value: CAE.Xyplot.PanToolSize) -> None: ...


class PanDirection(enum.Enum):
    Up= 0
    Down= 1
    Left= 2
    Right= 3


class OverlayParameters(CAE.Xyplot.BasePlotParameters):
    def __init__(self, ptr: int) -> None: ...
    @property
    def SubGraphInStack(self) -> int: ...
    @SubGraphInStack.setter
    def SubGraphInStack(self, value: int) -> None: ...


class OverallMarkerModel(CAE.Xyplot.BasicModel):
    def __init__(self) -> None: ...
    def GetResult(self) -> float: ...
    def Delete(self) -> None: ...
    def GetTexts(self, textValues: str) -> None: ...


class OverallLevelAccessor(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def AskOverallLevelResult(self, resultValue: float) -> bool: ...
    def FreeResource(self) -> None: ...


class OrderMarkerModel(CAE.Xyplot.BasicModel):
    def __init__(self) -> None: ...
    def GetOrderValue(self) -> float: ...
    def Delete(self) -> None: ...
    def GetTexts(self, textValues: str) -> None: ...


class NoteStyleSetting(CAE.Xyplot.TextStyleSetting):
    def __init__(self) -> None: ...
    def GetNoteTexts(self) -> str: ...
    def SetNoteTexts(self, noteTexts: str) -> None: ...


class NoteModel(CAE.Xyplot.BasicModel):
    def __init__(self) -> None: ...
    def GetTexts(self) -> str: ...
    def SetTexts(self, content: str) -> None: ...
    def GetTextPosition(self) -> Point2d: ...
    def SetTextPosition(self, position: Point2d) -> None: ...
    def Delete(self) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class ModelType(enum.Enum):
    Plot= 1
    Graph= 2
    RecordDisplay= 3
    Marker= 4
    Note= 5
    Title= 6
    GraphName= 7
    FunctionName= 8
    XAxis= 9
    XAxisLabel= 10
    XAxisNumber= 11
    YAxis= 12
    YAxisLabel= 13
    YAxisNumber= 14
    ZAxis= 15
    ZAxisLabel= 16
    ZAxisNumber= 17
    ColorAxis= 18
    ColorAxisLabel= 19
    ColorAxisNumber= 20
    AngleAxis= 21
    AngleAxisNumber= 22
    UnknownResult= 23
    PageNumber= 24
    Legend= 25
    LegendTable= 26
    ResultLegend= 27
    FormulaGrid= 28
    FormulaGridValueText= 29
    CalculationLegendTable= 30


class MatrixPlot2DLayoutMode(enum.Enum):
    FillEachCellAsSquare= 0
    FillAllAvailableDisplayArea= 1


class MatrixPlot2D(CAE.Xyplot.Plot):
    def __init__(self) -> None: ...
    def EditRecord(self, nthRecordIdx: int, record: CAE.FTK.BaseRecord) -> None: ...


class MatrixGraph2D(CAE.Xyplot.Graph):
    def __init__(self) -> None: ...
    def GetSourcePointCount(self, recordIndex: int, sectionIndex: int) -> int: ...
    @typing.overload
    def CreateMarker(self, recordIndex: int, sectionIndex: int, pointIndex: int) -> CAE.Xyplot.MarkerModel: ...
    @typing.overload
    def CreateMarker(self, recordIndex: int, sectionIndex: int, prePointIndex: int, nextPointIndex: int, linearInterpoScale: float) -> CAE.Xyplot.MarkerModel: ...


class MatrixFunctionDataAccessor(CAE.Xyplot.IFunctionDataAccessor):
    def __init__(self, ptr: int) -> None: ...
    def AskDisplayData(self, dependentValues: float) -> None: ...
    def AskPointLabels(self, rowLabels: str, columnLabels: str) -> None: ...


class MarkerStyleSetting(CAE.Xyplot.TextStyleSetting):
    def __init__(self) -> None: ...
    def GetNoteTexts(self) -> str: ...
    def SetNoteTexts(self, noteTexts: str) -> None: ...
    @property
    def AbsPercentage(self) -> float: ...
    @AbsPercentage.setter
    def AbsPercentage(self, value: float) -> None: ...
    @property
    def AttachmentType(self) -> CAE.Xyplot.AnchorType: ...
    @AttachmentType.setter
    def AttachmentType(self, value: CAE.Xyplot.AnchorType) -> None: ...
    @property
    def NoteTextVisibility(self) -> bool: ...
    @NoteTextVisibility.setter
    def NoteTextVisibility(self, value: bool) -> None: ...
    @property
    def NumberTextVisibility(self) -> bool: ...
    @NumberTextVisibility.setter
    def NumberTextVisibility(self, value: bool) -> None: ...
    @property
    def SnapToData(self) -> bool: ...
    @SnapToData.setter
    def SnapToData(self, value: bool) -> None: ...


class MarkerModel(CAE.Xyplot.BasicModel):
    def __init__(self) -> None: ...
    def Delete(self) -> None: ...
    @property
    def PointIndex(self) -> int: ...
    @PointIndex.setter
    def PointIndex(self, value: int) -> None: ...
    @property
    def RecordIndex(self) -> int: ...
    @RecordIndex.setter
    def RecordIndex(self, value: int) -> None: ...


class LineStyle3DSetting(CAE.Xyplot.BaseLineStyleSetting):
    def __init__(self) -> None: ...
    @property
    def Direction(self) -> CAE.Xyplot.Direction: ...
    @Direction.setter
    def Direction(self, value: CAE.Xyplot.Direction) -> None: ...


class LineStyle2DSetting(CAE.Xyplot.BaseLineStyleSetting):
    def __init__(self) -> None: ...


class LimitsType(enum.Enum):
    FreeLimits= 0
    OptimizedLimits= 1
    FixedLimits= 2


class LegendTableTextStyle(CAE.Xyplot.TextStyleSetting):
    def __init__(self) -> None: ...
    def GetMargin(self, marginOption: CAE.Xyplot.TextBoxMarginOption) -> float: ...
    def SetMargin(self, marginOption: CAE.Xyplot.TextBoxMarginOption, marginValue: float) -> None: ...


class LegendTableStyle(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    def GetPositionType(self) -> CAE.Xyplot.LegendTablePositionType: ...
    def GetTextStyle(self) -> CAE.Xyplot.LegendTableTextStyle: ...
    def GetGridLineStyle(self) -> CAE.Xyplot.CurveDisplaySettings: ...
    def GetBorderLineStyle(self) -> CAE.Xyplot.CurveDisplaySettings: ...
    def GetColumnTitles(self, columnTitles: str) -> None: ...
    def SetColumnTitles(self, columnTitles: str) -> None: ...
    @property
    def BackgroundColor(self) -> NXColor: ...
    @BackgroundColor.setter
    def BackgroundColor(self, value: NXColor) -> None: ...
    @property
    def GridBackgroundColor(self) -> NXColor: ...
    @GridBackgroundColor.setter
    def GridBackgroundColor(self, value: NXColor) -> None: ...
    @property
    def IsBorderLineVisible(self) -> bool: ...
    @IsBorderLineVisible.setter
    def IsBorderLineVisible(self, value: bool) -> None: ...
    @property
    def IsGridBackgroundFilled(self) -> bool: ...
    @IsGridBackgroundFilled.setter
    def IsGridBackgroundFilled(self, value: bool) -> None: ...
    @property
    def IsGridLineVisible(self) -> bool: ...
    @IsGridLineVisible.setter
    def IsGridLineVisible(self, value: bool) -> None: ...
    @property
    def IsHeaderVisible(self) -> bool: ...
    @IsHeaderVisible.setter
    def IsHeaderVisible(self, value: bool) -> None: ...
    @property
    def MaximumLegendItemCount(self) -> int: ...
    @MaximumLegendItemCount.setter
    def MaximumLegendItemCount(self, value: int) -> None: ...
    @property
    def Visibility(self) -> bool: ...
    @Visibility.setter
    def Visibility(self, value: bool) -> None: ...


class LegendTablePositionType(enum.Enum):
    Floating= 0
    Docked= 1


class LegendTableGroupStyle(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    def GetLegendTableStyle(self, legendTablePositionType: CAE.Xyplot.LegendTablePositionType) -> CAE.Xyplot.LegendTableStyle: ...
    @property
    def ActiveLegendTablePosition(self) -> CAE.Xyplot.LegendTablePositionType: ...
    @ActiveLegendTablePosition.setter
    def ActiveLegendTablePosition(self, value: CAE.Xyplot.LegendTablePositionType) -> None: ...
    @property
    def Visibility(self) -> bool: ...
    @Visibility.setter
    def Visibility(self, value: bool) -> None: ...


class LegendTable(CAE.Xyplot.BaseModel):
    def __init__(self) -> None: ...
    def GetFreeTextOfLegendItem(self, dataIndex: int) -> str: ...
    def SetFreeTextOfLegendItem(self, dataIndex: int, freeText: str) -> None: ...
    def ResetFreeTextOfLegendItem(self, dataIndex: int) -> None: ...
    @property
    def LegendTableStyle(self) -> CAE.Xyplot.LegendTableStyle: ...
    @LegendTableStyle.setter
    def LegendTableStyle(self, value: CAE.Xyplot.LegendTableStyle) -> None: ...


class LegendAccessor(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def FreeText(self) -> str: ...
    @FreeText.setter
    def FreeText(self, value: str) -> None: ...


class LeaderStyle(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def AnchorColor(self) -> NXColor: ...
    @AnchorColor.setter
    def AnchorColor(self, value: NXColor) -> None: ...
    @property
    def LineStyle(self) -> CAE.Xyplot.CurveDisplaySettings: ...
    @LineStyle.setter
    def LineStyle(self, value: CAE.Xyplot.CurveDisplaySettings) -> None: ...
    @property
    def PointMarker(self) -> CAE.Xyplot.PointMarker: ...
    @PointMarker.setter
    def PointMarker(self, value: CAE.Xyplot.PointMarker) -> None: ...


class IVisibleDisplayStyle():
    @property
    def Visibility(self) -> bool: ...
    @Visibility.setter
    def Visibility(self, value: bool) -> None: ...


class ITextModel():
    def GetTexts(self, textValues: str) -> None: ...


class IFunctionDataAccessor(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def AskAxisAccessor(self, axisDirection: CAE.Xyplot.AxisDirection) -> CAE.Xyplot.AxisAccessor: ...
    def AskColorAxisAccessor(self) -> CAE.Xyplot.AxisAccessor: ...
    def AskLegendAccessor(self) -> CAE.Xyplot.LegendAccessor: ...
    def FreeResource(self) -> None: ...
    def AskFunctionLegendAccessor(self) -> CAE.Xyplot.FunctionLegendAccessor: ...
    def AskOverallLevelAccessor(self) -> CAE.Xyplot.OverallLevelAccessor: ...
    @property
    def FunctionType(self) -> str: ...
    @FunctionType.setter
    def FunctionType(self, value: str) -> None: ...
    @property
    def RecordName(self) -> str: ...
    @RecordName.setter
    def RecordName(self, value: str) -> None: ...
    @property
    def Type(self) -> CAE.Xyplot.FunctionDataAccessor: ...
    @Type.setter
    def Type(self, value: CAE.Xyplot.FunctionDataAccessor) -> None: ...


class IDisplayStyle():
    def CommitChange(self) -> None: ...
    @property
    def Owner(self) -> CAE.Xyplot.IDisplayStyle: ...
    @Owner.setter
    def Owner(self, value: CAE.Xyplot.IDisplayStyle) -> None: ...


class IDisplayableModel():
    def UpdateDisplay(self) -> None: ...


class IDeletableModel():
    def Delete(self) -> None: ...


class ICurveDisplaySettings():
    @property
    def Color(self) -> NXColor: ...
    @Color.setter
    def Color(self, value: NXColor) -> None: ...
    @property
    def Font(self) -> DisplayableObject.ObjectFont: ...
    @Font.setter
    def Font(self, value: DisplayableObject.ObjectFont) -> None: ...
    @property
    def Width(self) -> DisplayableObject.ObjectWidth: ...
    @Width.setter
    def Width(self, value: DisplayableObject.ObjectWidth) -> None: ...


class IAxisStyle():
    def GetAnnotationStyle(self) -> CAE.Xyplot.TextStyleSetting: ...
    def GetLabelDisplayStyle(self) -> CAE.Xyplot.CustomTextStyleSetting: ...


class I3DDataPlot():
    def EditRecords(self, records: typing.List[CAE.FTK.BaseRecord]) -> None: ...


class I3DDataGraph():
    def GetSourcePointCount(self, recordIndex: int, sectionIndex: int) -> int: ...
    @typing.overload
    def CreateMarker(self, recordIndex: int, sectionIndex: int, pointIndex: int) -> CAE.Xyplot.MarkerModel: ...
    @typing.overload
    def CreateMarker(self, recordIndex: int, sectionIndex: int, prePointIndex: int, nextPointIndex: int, linearInterpoScale: float) -> CAE.Xyplot.MarkerModel: ...


class I2DDataPlot():
    def EditRecord(self, nthRecordIdx: int, record: CAE.FTK.BaseRecord) -> None: ...


class GridStyle(enum.Enum):
    NoGrid= 0
    GridOnly= 1
    TicksOnly= 2
    GridAndTicks= 3
    DenseGrid= 4


class GridLayoutStyle3DSetting(CAE.Xyplot.BaseGridLayoutStyleSetting):
    def __init__(self) -> None: ...
    @property
    def ZxGridStyle(self) -> CAE.Xyplot.GridStyle: ...
    @ZxGridStyle.setter
    def ZxGridStyle(self, value: CAE.Xyplot.GridStyle) -> None: ...
    @property
    def ZyGridStyle(self) -> CAE.Xyplot.GridStyle: ...
    @ZyGridStyle.setter
    def ZyGridStyle(self, value: CAE.Xyplot.GridStyle) -> None: ...


class GridLayoutStyle2DSetting(CAE.Xyplot.BaseGridLayoutStyleSetting):
    def __init__(self) -> None: ...


class GraphStyle(enum.Enum):
    Line= 0
    Bar= 1
    Surface= 3
    Scatter= 4
    ColorBar= 5
    ColorMap= 6
    BarChart= 7
    Vector= 8
    Matrix2D= 9


class GraphOptionsStyleColorMap(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    @property
    def FreqBandSummationStyle(self) -> CAE.Xyplot.FrequencyBandSummationStyle: ...
    @FreqBandSummationStyle.setter
    def FreqBandSummationStyle(self, value: CAE.Xyplot.FrequencyBandSummationStyle) -> None: ...


class GraphOptionsStyle2D(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    @property
    def FrequencyBandSummationBandType(self) -> CAE.Xyplot.FrequencyBandSummationBandType: ...
    @FrequencyBandSummationBandType.setter
    def FrequencyBandSummationBandType(self, value: CAE.Xyplot.FrequencyBandSummationBandType) -> None: ...
    @property
    def FrequencyBandSummationBandTypeMode(self) -> CAE.Xyplot.FrequencyBandSummationBandTypeMode: ...
    @FrequencyBandSummationBandTypeMode.setter
    def FrequencyBandSummationBandTypeMode(self, value: CAE.Xyplot.FrequencyBandSummationBandTypeMode) -> None: ...
    @property
    def FrequencyBandSummationDisplayMode(self) -> CAE.Xyplot.FrequencyBandSummationDisplayMode: ...
    @FrequencyBandSummationDisplayMode.setter
    def FrequencyBandSummationDisplayMode(self, value: CAE.Xyplot.FrequencyBandSummationDisplayMode) -> None: ...
    @property
    def ShowFrequencyBandSummation(self) -> bool: ...
    @ShowFrequencyBandSummation.setter
    def ShowFrequencyBandSummation(self, value: bool) -> None: ...
    @property
    def ShowTotalResponseLineForPolar(self) -> bool: ...
    @ShowTotalResponseLineForPolar.setter
    def ShowTotalResponseLineForPolar(self, value: bool) -> None: ...
    @property
    def ShowTotalResponseLineForVector(self) -> bool: ...
    @ShowTotalResponseLineForVector.setter
    def ShowTotalResponseLineForVector(self, value: bool) -> None: ...
    @property
    def TotalResponseLineSetting(self) -> CAE.Xyplot.CurveDisplaySettings: ...
    @TotalResponseLineSetting.setter
    def TotalResponseLineSetting(self, value: CAE.Xyplot.CurveDisplaySettings) -> None: ...


class GraphNameStyle(CAE.Xyplot.TextStyleSetting):
    def __init__(self) -> None: ...
    @property
    def PositionOption(self) -> CAE.Xyplot.GraphNamePositionOption: ...
    @PositionOption.setter
    def PositionOption(self, value: CAE.Xyplot.GraphNamePositionOption) -> None: ...


class GraphNamePositionOption(enum.Enum):
    TopLeft= 0
    TopCenter= 1
    TopRight= 2
    BottomLeft= 3
    BottomCenter= 4
    BottomRight= 5


class Graph3D(CAE.Xyplot.Graph):
    def __init__(self) -> None: ...
    def GetSourcePointCount(self, recordIndex: int, sectionIndex: int) -> int: ...
    @typing.overload
    def CreateMarker(self, recordIndex: int, sectionIndex: int, pointIndex: int) -> CAE.Xyplot.MarkerModel: ...
    @typing.overload
    def CreateMarker(self, recordIndex: int, sectionIndex: int, prePointIndex: int, nextPointIndex: int, linearInterpoScale: float) -> CAE.Xyplot.MarkerModel: ...


class Graph(CAE.Xyplot.BaseModel):
    def __init__(self) -> None: ...
    def GetPointCount(self, recordIndex: int) -> int: ...
    @typing.overload
    def CreateMarker(self, recordIndex: int, pointIndex: int) -> CAE.Xyplot.MarkerModel: ...
    @typing.overload
    def CreateMarker(self, recordIndex: int, prePointIndex: int, nextPointIndex: int, linearInterpoScale: float) -> CAE.Xyplot.MarkerModel: ...
    def CreateAssociativeMarker(self, recordIndex: int, attachType: CAE.Xyplot.AnchorType, absPercentage: float) -> CAE.Xyplot.MarkerModel: ...
    def GetMarkers(self, markers: typing.List[CAE.Xyplot.MarkerModel]) -> None: ...
    def GetAnchorPointOfRecord(self, recordIndex: int, anchorType: CAE.Xyplot.AnchorType, anchorPoint: Point3d) -> bool: ...
    def GetRecordName(self, recordIndex: int) -> str: ...
    def GetGridBoundingBox(self, leftBottom: Point3d, rightTop: Point3d) -> None: ...
    def GetAbscissaAxes(self) -> typing.List[CAE.Xyplot.BasicModel]: ...
    def GetOrdinateAxes(self) -> typing.List[CAE.Xyplot.BasicModel]: ...
    def GetZAxis(self) -> CAE.Xyplot.BasicModel: ...
    def GetDisplayStyleOfRecord(self, recordIndex: int) -> int: ...
    def SetDisplayStyleOfRecord(self, recordIndex: int, displayStyleIndex: int) -> None: ...
    def RestoreStyleAssignments(self) -> None: ...
    def SaveStyleAssignmentsToTemplate(self) -> None: ...
    def ZoomAlongX(self, startScale: float, endScale: float) -> None: ...
    def ZoomAlongY(self, startScale: float, endScale: float) -> None: ...
    def ZoomAlongZ(self, startScale: float, endScale: float) -> None: ...
    def ZoomAlongXY(self, xStartScale: float, xEndScale: float, yStartScale: float, yEndScale: float) -> None: ...
    def Unzoom(self) -> None: ...
    def CreateOverallMarker(self, recordIndex: int) -> CAE.Xyplot.OverallMarkerModel: ...
    def CreateOrderMarker(self, recordIndex: int) -> CAE.Xyplot.OrderMarkerModel: ...
    def CreateSoundPlayer(self, recordIndex: int) -> CAE.Xyplot.SoundPlayer: ...
    @property
    def RecordCount(self) -> int: ...
    @RecordCount.setter
    def RecordCount(self, value: int) -> None: ...


class GeneralDisplayStylesMatrix2D(CAE.Xyplot.GeneralDisplayStyles):
    def __init__(self) -> None: ...
    def SwitchXYAxis(self) -> None: ...
    @property
    def ComplexOption(self) -> CAE.Xyplot.ComplexOptionMatrix2D: ...
    @ComplexOption.setter
    def ComplexOption(self, value: CAE.Xyplot.ComplexOptionMatrix2D) -> None: ...
    @property
    def LayoutMode(self) -> CAE.Xyplot.MatrixPlot2DLayoutMode: ...
    @LayoutMode.setter
    def LayoutMode(self, value: CAE.Xyplot.MatrixPlot2DLayoutMode) -> None: ...


class GeneralDisplayStyles3D(CAE.Xyplot.GeneralDisplayStyles):
    def __init__(self) -> None: ...
    @property
    def ComplexOption(self) -> CAE.Xyplot.ComplexOption3D: ...
    @ComplexOption.setter
    def ComplexOption(self, value: CAE.Xyplot.ComplexOption3D) -> None: ...


class GeneralDisplayStyles2DColorContour(CAE.Xyplot.GeneralDisplayStyles):
    def __init__(self) -> None: ...
    @property
    def ComplexOption(self) -> CAE.Xyplot.ComplexOption2DColorContour: ...
    @ComplexOption.setter
    def ComplexOption(self, value: CAE.Xyplot.ComplexOption2DColorContour) -> None: ...


class GeneralDisplayStyles2DBarChart(CAE.Xyplot.GeneralDisplayStyles):
    def __init__(self) -> None: ...
    @property
    def ComplexOption(self) -> CAE.Xyplot.ComplexOption2DBarChart: ...
    @ComplexOption.setter
    def ComplexOption(self, value: CAE.Xyplot.ComplexOption2DBarChart) -> None: ...


class GeneralDisplayStyles2D(CAE.Xyplot.GeneralDisplayStyles):
    def __init__(self) -> None: ...
    def SwitchXYAxis(self) -> None: ...
    @property
    def ComplexOption(self) -> CAE.Xyplot.ComplexOption2D: ...
    @ComplexOption.setter
    def ComplexOption(self, value: CAE.Xyplot.ComplexOption2D) -> None: ...


class GeneralDisplayStyles(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    @property
    def PhaseAngle(self) -> float: ...
    @PhaseAngle.setter
    def PhaseAngle(self, value: float) -> None: ...
    @property
    def PhaseRangeOption(self) -> CAE.Xyplot.PhaseRangeOption: ...
    @PhaseRangeOption.setter
    def PhaseRangeOption(self, value: CAE.Xyplot.PhaseRangeOption) -> None: ...


class FunctionLegendAccessor(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def AskFunctionName(self, funcType: CAE.Xyplot.CalculationFunctionType) -> str: ...
    def AskFunctionResult(self, funcType: CAE.Xyplot.CalculationFunctionType, results: float) -> bool: ...
    def FreeResource(self) -> None: ...


class FunctionDataAccessor(enum.Enum):
    None_= 0
    Xy= 1
    Xyz= 2
    Argand3D= 3
    BarChart= 4
    Matrix= 5
    Campbell= 6


class FrequencyBandSummationStyle(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    @property
    def BandType(self) -> CAE.Xyplot.FrequencyBandSummationBandType: ...
    @BandType.setter
    def BandType(self, value: CAE.Xyplot.FrequencyBandSummationBandType) -> None: ...
    @property
    def BandTypeMode(self) -> CAE.Xyplot.FrequencyBandSummationBandTypeMode: ...
    @BandTypeMode.setter
    def BandTypeMode(self, value: CAE.Xyplot.FrequencyBandSummationBandTypeMode) -> None: ...
    @property
    def DisplayMode(self) -> CAE.Xyplot.FrequencyBandSummationDisplayMode: ...
    @DisplayMode.setter
    def DisplayMode(self, value: CAE.Xyplot.FrequencyBandSummationDisplayMode) -> None: ...
    @property
    def Visibility(self) -> bool: ...
    @Visibility.setter
    def Visibility(self, value: bool) -> None: ...


class FrequencyBandSummationDisplayMode(enum.Enum):
    StepLines= 0
    ConnectCentralFrequencies= 1


class FrequencyBandSummationBandTypeMode(enum.Enum):
    Infer= 0
    UserDefined= 1


class FrequencyBandSummationBandType(enum.Enum):
    Octave= 0
    OneThirdOctave= 1
    OneTwelfthOctave= 2


class FormulaGridType(enum.Enum):
    None_= 0
    DiagonalLineInHaighDiagram= 1


class FormulaGridStyle(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    def GetExpressionStyle(self) -> CAE.Xyplot.FormulaExpressionStyle: ...
    def GetGridLineStyle(self) -> CAE.Xyplot.CurveDisplaySettings: ...
    def GetGridValueTextStyle(self) -> CAE.Xyplot.TextStyleSetting: ...
    @property
    def Visibility(self) -> bool: ...
    @Visibility.setter
    def Visibility(self, value: bool) -> None: ...


class FormulaExpressionStyle(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    def GetVariableValues(self) -> float: ...
    def SetVariableValues(self, variableValues: float) -> None: ...
    @property
    def FormulaGridType(self) -> CAE.Xyplot.FormulaGridType: ...
    @FormulaGridType.setter
    def FormulaGridType(self, value: CAE.Xyplot.FormulaGridType) -> None: ...
    @property
    def IsIncludeNegativeInfinity(self) -> bool: ...
    @IsIncludeNegativeInfinity.setter
    def IsIncludeNegativeInfinity(self, value: bool) -> None: ...
    @property
    def IsIncludePositiveInfinity(self) -> bool: ...
    @IsIncludePositiveInfinity.setter
    def IsIncludePositiveInfinity(self, value: bool) -> None: ...


class Fonttype(enum.Enum):
    Nx= 0
    Standard= 1


class FlowResultColor(enum.Enum):
    None_= 0
    Shaded= 1


class DisplayDataExportParameters(CAE.Xyplot.DataExportParameters):
    def __init__(self, ptr: int) -> None: ...
    def GetGraphIndices(self) -> int: ...
    def SetGraphIndices(self, graphIndices: int) -> None: ...


class Direction(enum.Enum):
    X= 0
    Z= 1
    Xz= 2


class DiagramDisplayStylesColorMap(CAE.Xyplot.DiagramDisplayStyles):
    def __init__(self) -> None: ...
    @property
    def GraphOptionsStyle(self) -> CAE.Xyplot.GraphOptionsStyleColorMap: ...
    @GraphOptionsStyle.setter
    def GraphOptionsStyle(self, value: CAE.Xyplot.GraphOptionsStyleColorMap) -> None: ...


class DiagramDisplayStylesCampbell(CAE.Xyplot.DiagramDisplayStyles):
    def __init__(self) -> None: ...
    @property
    def GraphType(self) -> CAE.Xyplot.CampbellGraphType: ...
    @GraphType.setter
    def GraphType(self, value: CAE.Xyplot.CampbellGraphType) -> None: ...
    @property
    def LineWidth(self) -> DisplayableObject.ObjectWidth: ...
    @LineWidth.setter
    def LineWidth(self, value: DisplayableObject.ObjectWidth) -> None: ...
    @property
    def PointMarker(self) -> CAE.Xyplot.PointMarker: ...
    @PointMarker.setter
    def PointMarker(self, value: CAE.Xyplot.PointMarker) -> None: ...
    @property
    def PointSizeScale(self) -> float: ...
    @PointSizeScale.setter
    def PointSizeScale(self, value: float) -> None: ...
    @property
    def PointSizeType(self) -> CAE.Xyplot.CampbellPointSizeType: ...
    @PointSizeType.setter
    def PointSizeType(self, value: CAE.Xyplot.CampbellPointSizeType) -> None: ...
    @property
    def ShowBackground(self) -> bool: ...
    @ShowBackground.setter
    def ShowBackground(self, value: bool) -> None: ...


class DiagramDisplayStyles2DBarChart(CAE.Xyplot.DiagramDisplayStyles):
    def __init__(self) -> None: ...
    def GetBarChartStyleSetting(self, styleIndex: int) -> CAE.Xyplot.BarChartStyleSetting: ...
    @property
    def SpaceBetweenFunctions(self) -> int: ...
    @SpaceBetweenFunctions.setter
    def SpaceBetweenFunctions(self, value: int) -> None: ...
    @property
    def SpaceBetweenItems(self) -> int: ...
    @SpaceBetweenItems.setter
    def SpaceBetweenItems(self, value: int) -> None: ...


class DiagramDisplayStyles2D(CAE.Xyplot.DiagramDisplayStyles):
    def __init__(self) -> None: ...
    def GetGraphOptionsStyle(self, styleIndex: int) -> CAE.Xyplot.GraphOptionsStyle2D: ...


class DiagramDisplayStyles(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    def GetGraphStyle(self, styleIndex: int) -> CAE.Xyplot.GraphStyle: ...
    def SetGraphStyle(self, styleIndex: int, graphStyle: CAE.Xyplot.GraphStyle) -> None: ...
    def GetLineStyleSetting(self, styleIndex: int) -> CAE.Xyplot.BaseLineStyleSetting: ...
    def GetBarStyleSetting(self, styleIndex: int) -> CAE.Xyplot.BaseBarStyleSetting: ...
    def GetScatterStyleSetting(self, styleIndex: int) -> CAE.Xyplot.ScatterStyleSetting: ...
    def GetSurfaceStyleSetting(self, styleIndex: int) -> CAE.Xyplot.SurfaceStyleSetting: ...
    def GetVectorStyleSetting(self, styleIndex: int) -> CAE.Xyplot.VectorStyle2DSetting: ...
    def SetGraphStyleName(self, styleIndex: int, graphStyleName: str) -> None: ...
    def GetGraphStyleName(self, styleIndex: int) -> str: ...
    @property
    def StyleCount(self) -> int: ...
    @StyleCount.setter
    def StyleCount(self, value: int) -> None: ...


class DecimalFormat(enum.Enum):
    Actual= 0
    X= 1
    Xx= 2
    Xxx= 3
    Xxxx= 4
    Xexx= 5
    Xxexx= 6
    Xxxexx= 7
    Xxxxexx= 8


class DataExportParameters(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def GetPlots(self, plots: typing.List[CAE.Xyplot.Plot]) -> None: ...
    def SetPlots(self, plots: typing.List[CAE.Xyplot.Plot]) -> None: ...
    def GetRecordIndices(self) -> int: ...
    def SetRecordIndices(self, plotDataIndices: int) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def Plot(self) -> CAE.Xyplot.Plot: ...
    @Plot.setter
    def Plot(self, value: CAE.Xyplot.Plot) -> None: ...


class DataExporter(Utilities.NXRemotableObject):
    def __init__(self, owner: CAE.Xyplot.XYPlotManager) -> None: ...
    def ExportToFiles(self, exportDataParam: CAE.Xyplot.DataExportParameters, exportFilesParam: CAE.FTK.ExportFilesParameter) -> None: ...
    def ExportToTableField(self, exportParam: CAE.Xyplot.DataExportParameters, customFieldNames: str, tables: typing.List[Fields.FieldTable]) -> None: ...
    def NewSourceDataExportParameters(self) -> CAE.Xyplot.SourceDataExportParameters: ...
    def NewDisplayDataExportParameters(self) -> CAE.Xyplot.DisplayDataExportParameters: ...
    def NewExportFilesParameters(self) -> CAE.FTK.ExportFilesParameter: ...
    def Tag(self) -> Tag: ...



class CustomTextStyleSetting(CAE.Xyplot.TextStyleSetting):
    def __init__(self) -> None: ...
    def GetUserDefinedText(self) -> str: ...
    def SetUserDefinedText(self, text: str) -> None: ...
    @property
    def UseAutomatic(self) -> bool: ...
    @UseAutomatic.setter
    def UseAutomatic(self, value: bool) -> None: ...


class CurveDisplaySettings(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    @property
    def Color(self) -> NXColor: ...
    @Color.setter
    def Color(self, value: NXColor) -> None: ...
    @property
    def Font(self) -> DisplayableObject.ObjectFont: ...
    @Font.setter
    def Font(self, value: DisplayableObject.ObjectFont) -> None: ...
    @property
    def Width(self) -> DisplayableObject.ObjectWidth: ...
    @Width.setter
    def Width(self, value: DisplayableObject.ObjectWidth) -> None: ...


class CoordinateType(enum.Enum):
    Xy= 0
    Yx= 1
    Xyz= 2
    Yxz= 3
    Zyx= 4
    Yzx= 5
    Xzy= 6
    Zxy= 7


class ContouringRange(enum.Enum):
    BorderGrid= 0
    FullGrid= 1


class ComplexOptionMatrix2D(enum.Enum):
    Magnitude= 0
    Phase= 1
    Real= 2
    Imaginary= 3
    AtPhaseAngle= 4
    SignedMagnitude= 5


class ComplexOption3D(enum.Enum):
    Magnitude= 0
    Phase= 1
    Real= 2
    Imaginary= 3
    Argand= 4
    Orbit= 5
    Nichols= 6
    AtPhaseAngle= 7
    SignedMagnitude= 8


class ComplexOption2DColorContour(enum.Enum):
    Magnitude= 0
    Phase= 1
    Real= 2
    Imaginary= 3
    AtPhaseAngle= 4
    SignedMagnitude= 5


class ComplexOption2DBarChart(enum.Enum):
    Magnitude= 0
    Phase= 1
    Real= 2
    Imaginary= 3
    AtPhaseAngle= 4
    SignedMagnitude= 5


class ComplexOption2D(enum.Enum):
    Magnitude= 0
    MagnitudePhase= 1
    Phase= 2
    Real= 3
    RealImaginary= 4
    RealImaginaryPhase= 5
    Polar= 6
    Argand= 7
    Polar3D= 8
    Argand3D= 9
    PhaseMagnitude= 10
    ImaginaryReal= 11
    PhaseRealImaginary= 12
    ImaginaryRealPhase= 13
    PhaseImaginaryReal= 14
    Nichols= 15
    AtPhaseAngle= 16
    SignedMagnitude= 17
    Directivity= 18
    Vector= 19


class ColorSpectrum(enum.Enum):
    Structural= 0
    Thermal= 1
    Grayscale= 2
    Stoplight= 3


class ColorScaleStyle(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    def GetColorLegendValuesOverridden(self, overridedValues: float) -> None: ...
    def SetColorLegendValuesOverridden(self, overridedValues: float) -> None: ...
    def GetColorLegendColorsOverridden(self, legendColors: int) -> None: ...
    def SetColorLegendColorsOverridden(self, legendColors: int) -> None: ...
    @property
    def AreColorLegendColorsOverridden(self) -> bool: ...
    @AreColorLegendColorsOverridden.setter
    def AreColorLegendColorsOverridden(self, value: bool) -> None: ...
    @property
    def AreColorLegendValuesOverridden(self) -> bool: ...
    @AreColorLegendValuesOverridden.setter
    def AreColorLegendValuesOverridden(self, value: bool) -> None: ...
    @property
    def AutoLevel(self) -> bool: ...
    @AutoLevel.setter
    def AutoLevel(self, value: bool) -> None: ...
    @property
    def ColorSpectrumType(self) -> CAE.Xyplot.ColorSpectrum: ...
    @ColorSpectrumType.setter
    def ColorSpectrumType(self, value: CAE.Xyplot.ColorSpectrum) -> None: ...
    @property
    def InvertionSpectrum(self) -> bool: ...
    @InvertionSpectrum.setter
    def InvertionSpectrum(self, value: bool) -> None: ...
    @property
    def Level(self) -> int: ...
    @Level.setter
    def Level(self, value: int) -> None: ...
    @property
    def MeasureName(self) -> str: ...
    @MeasureName.setter
    def MeasureName(self, value: str) -> None: ...


class ColorMapPlot(CAE.Xyplot.Plot):
    def __init__(self) -> None: ...
    def EditRecords(self, records: typing.List[CAE.FTK.BaseRecord]) -> None: ...


class ColorMapGraph(CAE.Xyplot.Graph):
    def __init__(self) -> None: ...
    def CreateOrderMarker(self, orderValue: float) -> CAE.Xyplot.MarkerModel: ...
    def GetSourcePointCount(self, recordIndex: int, sectionIndex: int) -> int: ...
    @typing.overload
    def CreateMarker(self, recordIndex: int, sectionIndex: int, pointIndex: int) -> CAE.Xyplot.MarkerModel: ...
    @typing.overload
    def CreateMarker(self, recordIndex: int, sectionIndex: int, prePointIndex: int, nextPointIndex: int, linearInterpoScale: float) -> CAE.Xyplot.MarkerModel: ...


class ColorBarPlot(CAE.Xyplot.Plot):
    def __init__(self) -> None: ...
    def EditRecord(self, nthRecordIdx: int, record: CAE.FTK.BaseRecord) -> None: ...


class ColorAxisStyleSetting(CAE.Xyplot.AxisStyleSetting):
    def __init__(self) -> None: ...
    @property
    def ColorScaleStyleSetting(self) -> CAE.Xyplot.ColorScaleStyle: ...
    @ColorScaleStyleSetting.setter
    def ColorScaleStyleSetting(self, value: CAE.Xyplot.ColorScaleStyle) -> None: ...
    @property
    def ResultLegendStyleSetting(self) -> CAE.Xyplot.ResultLegendStyle: ...
    @ResultLegendStyleSetting.setter
    def ResultLegendStyleSetting(self, value: CAE.Xyplot.ResultLegendStyle) -> None: ...


class ColorAxis(CAE.Xyplot.AxisModel):
    def __init__(self) -> None: ...
    def GetColorLegendLevelCount(self) -> int: ...


class CampbellPointSizeType(enum.Enum):
    Const= 0
    Variable= 1


class CampbellPlot(CAE.Xyplot.Plot):
    def __init__(self) -> None: ...
    def EditRecords(self, records: typing.List[CAE.FTK.BaseRecord]) -> None: ...


class CampbellGraphType(enum.Enum):
    Point= 0
    Line= 1


class CampbellFunctionDataAccessor(CAE.Xyplot.IFunctionDataAccessor):
    def __init__(self, ptr: int) -> None: ...
    def AskDisplayData(self, independentValues: float, dependentValues: float, rpmValues: float) -> float: ...


class CalculationFunctionType(enum.Enum):
    MaxAmplitude= 0
    MinAmplitude= 1
    MaximumRange= 2
    Rss= 3
    Rms= 4
    LinearAveraging= 5
    IntegratedValue= 6
    SignalPower= 7


class BasicModel(CAE.Xyplot.BaseModel):
    def __init__(self) -> None: ...
    @property
    def DisplayStyle(self) -> CAE.Xyplot.IDisplayStyle: ...
    @DisplayStyle.setter
    def DisplayStyle(self, value: CAE.Xyplot.IDisplayStyle) -> None: ...


class BaseTemplateManager(NXObject):
    def __init__(self) -> None: ...
    def LoadTemplate(self, templateFile: str) -> None: ...
    def UnloadTemplate(self, templateFile: str) -> None: ...
    def UnloadAllTemplates(self) -> None: ...
    def ResetTemplate(self, templateFile: str) -> None: ...
    def DeleteTemplate(self, templateFile: str) -> None: ...
    def SaveTemplate(self, templateFile: str) -> None: ...
    def SaveAsTemplate(self, sourceTemplateFile: str, destinationTemplateFile: str) -> None: ...
    def RenameTemplateFile(self, oldTemplateFile: str, newTemplateFileName: str) -> None: ...
    def SaveAllTemplates(self) -> None: ...
    def ResetSystemTemplate(self) -> None: ...
    def GetDefaultTemplate(self) -> str: ...
    def SetDefaultTemplate(self, templateFile: str) -> None: ...
    def ReloadAllTemplateFiles(self) -> None: ...


class BaseSymbolStyleSetting(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    @property
    def PointMarker(self) -> CAE.Xyplot.PointMarker: ...
    @PointMarker.setter
    def PointMarker(self, value: CAE.Xyplot.PointMarker) -> None: ...


class BasePlotParameters(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def GetRecords(self) -> typing.List[CAE.FTK.BaseRecord]: ...
    def SetRecords(self, records: typing.List[CAE.FTK.BaseRecord]) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def DeviceIndex(self) -> int: ...
    @DeviceIndex.setter
    def DeviceIndex(self, value: int) -> None: ...
    @property
    def ViewPortIndex(self) -> int: ...
    @ViewPortIndex.setter
    def ViewPortIndex(self, value: int) -> None: ...


class BaseModel(NXObject):
    def __init__(self) -> None: ...
    def UpdateDisplay(self) -> None: ...
    @property
    def StyleSetting(self) -> CAE.Xyplot.BaseDisplayStyleSetting: ...
    @StyleSetting.setter
    def StyleSetting(self, value: CAE.Xyplot.BaseDisplayStyleSetting) -> None: ...


class BaseLineStyleSetting(CAE.Xyplot.BaseSymbolStyleSetting):
    def __init__(self) -> None: ...
    @property
    def Color(self) -> NXColor: ...
    @Color.setter
    def Color(self, value: NXColor) -> None: ...
    @property
    def Font(self) -> DisplayableObject.ObjectFont: ...
    @Font.setter
    def Font(self, value: DisplayableObject.ObjectFont) -> None: ...
    @property
    def Width(self) -> DisplayableObject.ObjectWidth: ...
    @Width.setter
    def Width(self, value: DisplayableObject.ObjectWidth) -> None: ...


class BaseGridLayoutStyleSetting(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    @property
    def BackgroundColor(self) -> NXColor: ...
    @BackgroundColor.setter
    def BackgroundColor(self, value: NXColor) -> None: ...
    @property
    def ColorOfBackgroundPlane(self) -> NXColor: ...
    @ColorOfBackgroundPlane.setter
    def ColorOfBackgroundPlane(self, value: NXColor) -> None: ...
    @property
    def ContouringLevel(self) -> int: ...
    @ContouringLevel.setter
    def ContouringLevel(self, value: int) -> None: ...
    @property
    def ContouringRange(self) -> CAE.Xyplot.ContouringRange: ...
    @ContouringRange.setter
    def ContouringRange(self, value: CAE.Xyplot.ContouringRange) -> None: ...
    @property
    def DenseGridDisplayStyleSettings(self) -> CAE.Xyplot.CurveDisplaySettings: ...
    @DenseGridDisplayStyleSettings.setter
    def DenseGridDisplayStyleSettings(self, value: CAE.Xyplot.CurveDisplaySettings) -> None: ...
    @property
    def DisplayContouring(self) -> bool: ...
    @DisplayContouring.setter
    def DisplayContouring(self, value: bool) -> None: ...
    @property
    def MajorGridDisplayStyleSettings(self) -> CAE.Xyplot.CurveDisplaySettings: ...
    @MajorGridDisplayStyleSettings.setter
    def MajorGridDisplayStyleSettings(self, value: CAE.Xyplot.CurveDisplaySettings) -> None: ...
    @property
    def ShowBackground(self) -> bool: ...
    @ShowBackground.setter
    def ShowBackground(self, value: bool) -> None: ...
    @property
    def ShowBackgroundPlane(self) -> bool: ...
    @ShowBackgroundPlane.setter
    def ShowBackgroundPlane(self, value: bool) -> None: ...
    @property
    def TicksDisplayStyleSettings(self) -> CAE.Xyplot.CurveDisplaySettings: ...
    @TicksDisplayStyleSettings.setter
    def TicksDisplayStyleSettings(self, value: CAE.Xyplot.CurveDisplaySettings) -> None: ...
    @property
    def XyGridStyle(self) -> CAE.Xyplot.GridStyle: ...
    @XyGridStyle.setter
    def XyGridStyle(self, value: CAE.Xyplot.GridStyle) -> None: ...


class BaseDisplayStyleSetting(TaggedObject):
    def __init__(self) -> None: ...
    def Find(self, journalIdentifier: str) -> TaggedObject: ...
    def CommitChange(self) -> None: ...
    @property
    def JournalIdentifier(self) -> str: ...
    @JournalIdentifier.setter
    def JournalIdentifier(self, value: str) -> None: ...
    @property
    def Owner(self) -> CAE.Xyplot.IDisplayStyle: ...
    @Owner.setter
    def Owner(self, value: CAE.Xyplot.IDisplayStyle) -> None: ...


class BaseBarStyleSetting(CAE.Xyplot.BaseSymbolStyleSetting):
    def __init__(self) -> None: ...
    @property
    def FillingColor(self) -> NXColor: ...
    @FillingColor.setter
    def FillingColor(self, value: NXColor) -> None: ...
    @property
    def OutlineColor(self) -> NXColor: ...
    @OutlineColor.setter
    def OutlineColor(self, value: NXColor) -> None: ...
    @property
    def ShowOutline(self) -> bool: ...
    @ShowOutline.setter
    def ShowOutline(self, value: bool) -> None: ...
    @property
    def Width(self) -> int: ...
    @Width.setter
    def Width(self, value: int) -> None: ...


class BarStyle3DSetting(CAE.Xyplot.BaseBarStyleSetting):
    def __init__(self) -> None: ...
    @property
    def ColorOption(self) -> CAE.Xyplot.BarColorOption: ...
    @ColorOption.setter
    def ColorOption(self, value: CAE.Xyplot.BarColorOption) -> None: ...
    @property
    def Depth(self) -> int: ...
    @Depth.setter
    def Depth(self, value: int) -> None: ...


class BarStyle2DSetting(CAE.Xyplot.BaseBarStyleSetting):
    def __init__(self) -> None: ...
    @property
    def ConstantWidth(self) -> float: ...
    @ConstantWidth.setter
    def ConstantWidth(self, value: float) -> None: ...
    @property
    def ShowConstantWidth(self) -> bool: ...
    @ShowConstantWidth.setter
    def ShowConstantWidth(self, value: bool) -> None: ...


class BarColorOption(enum.Enum):
    Fill= 0
    Hidden= 1
    Shaded= 2


class BarChartStyleSetting(CAE.Xyplot.BaseSymbolStyleSetting):
    def __init__(self) -> None: ...
    @property
    def FillingColor(self) -> NXColor: ...
    @FillingColor.setter
    def FillingColor(self, value: NXColor) -> None: ...
    @property
    def OutlineColor(self) -> NXColor: ...
    @OutlineColor.setter
    def OutlineColor(self, value: NXColor) -> None: ...
    @property
    def PointMarkerIdx(self) -> CAE.Xyplot.PointMarker: ...
    @PointMarkerIdx.setter
    def PointMarkerIdx(self, value: CAE.Xyplot.PointMarker) -> None: ...
    @property
    def ShowOutline(self) -> bool: ...
    @ShowOutline.setter
    def ShowOutline(self, value: bool) -> None: ...
    @property
    def ShowText(self) -> bool: ...
    @ShowText.setter
    def ShowText(self, value: bool) -> None: ...
    @property
    def SpaceBetweenTextAndBar(self) -> int: ...
    @SpaceBetweenTextAndBar.setter
    def SpaceBetweenTextAndBar(self, value: int) -> None: ...


class BarChartPlot(CAE.Xyplot.Plot):
    def __init__(self) -> None: ...
    def EditRecord(self, nthRecordIdx: int, record: CAE.FTK.BaseRecord) -> None: ...


class BarChartFunctionDataAccessor(CAE.Xyplot.IFunctionDataAccessor):
    def __init__(self, ptr: int) -> None: ...
    def AskDisplayData(self, indenpendentValues: float, dependentValues: float) -> None: ...
    def AskPointLabels(self, pointLabels: str) -> None: ...


class AxisYStyleSetting(CAE.Xyplot.AxisStyleSetting):
    def __init__(self) -> None: ...
    @property
    def BarLowerLimit(self) -> bool: ...
    @BarLowerLimit.setter
    def BarLowerLimit(self, value: bool) -> None: ...


class AxisType(enum.Enum):
    Auto= 0
    Linear= 1
    Log= 2
    Db= 3
    Octave= 4
    OneThirdOctave= 5
    OneTwelfthOctave= 6


class AxisStyleSetting(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    def GetDBSettings(self) -> CAE.SignalProcessingDBSettings: ...
    def GetFixedLimits(self, lowerLimit: float, upperLimit: float) -> None: ...
    def SetFixedLimits(self, lowerLimit: float, upperLimit: float) -> None: ...
    def LogUnitChangedEvent(self) -> None: ...
    def GetDisplayUnit(self) -> CAE.FTK.BaseUnit: ...
    def GetAnnotationStyle(self) -> CAE.Xyplot.TextStyleSetting: ...
    def GetLabelDisplayStyle(self) -> CAE.Xyplot.CustomTextStyleSetting: ...
    @property
    def AxisType(self) -> CAE.Xyplot.AxisType: ...
    @AxisType.setter
    def AxisType(self, value: CAE.Xyplot.AxisType) -> None: ...
    @property
    def GraphOverhead(self) -> int: ...
    @GraphOverhead.setter
    def GraphOverhead(self, value: int) -> None: ...
    @property
    def LimitsType(self) -> CAE.Xyplot.LimitsType: ...
    @LimitsType.setter
    def LimitsType(self, value: CAE.Xyplot.LimitsType) -> None: ...
    @property
    def LogDecades(self) -> int: ...
    @LogDecades.setter
    def LogDecades(self, value: int) -> None: ...
    @property
    def UnitSystemType(self) -> CAE.XyFunctionUnitSystem: ...
    @UnitSystemType.setter
    def UnitSystemType(self, value: CAE.XyFunctionUnitSystem) -> None: ...
    @property
    def UseAbsoluteValue(self) -> bool: ...
    @UseAbsoluteValue.setter
    def UseAbsoluteValue(self, value: bool) -> None: ...


class AxisModel(CAE.Xyplot.BasicModel):
    def __init__(self) -> None: ...
    def GetDisplayLimits(self, startDisplayLimit: float, endDisplayLimit: float) -> None: ...
    def CalculateZoomScale(self, newStartDisplayLimit: float, newEndDisplayLimit: float, startScale: float, endScale: float) -> None: ...


class AxisLabelStyle(CAE.Xyplot.CustomTextStyleSetting):
    def __init__(self) -> None: ...
    @property
    def IncludeMeasureType(self) -> bool: ...
    @IncludeMeasureType.setter
    def IncludeMeasureType(self, value: bool) -> None: ...
    @property
    def IncludeUnit(self) -> bool: ...
    @IncludeUnit.setter
    def IncludeUnit(self, value: bool) -> None: ...
    @property
    def UseSingleLine(self) -> bool: ...
    @UseSingleLine.setter
    def UseSingleLine(self, value: bool) -> None: ...


class AxisItemStyle(CAE.Xyplot.TextStyleSetting):
    def __init__(self) -> None: ...
    @property
    def MaximumCharacterCount(self) -> int: ...
    @MaximumCharacterCount.setter
    def MaximumCharacterCount(self, value: int) -> None: ...


class AxisDirection(enum.Enum):
    X= 0
    Y= 1
    Z= 2


class AxisDBScale(enum.Enum):
    Ten= 0
    Twenty= 1


class AxisAccessor(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def GetLabel(self, axisLabels: str) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def AxisType(self) -> CAE.Xyplot.AxisType: ...
    @AxisType.setter
    def AxisType(self, value: CAE.Xyplot.AxisType) -> None: ...
    @property
    def Unit(self) -> CAE.FTK.BaseUnit: ...
    @Unit.setter
    def Unit(self, value: CAE.FTK.BaseUnit) -> None: ...


class AutotestUtils(Utilities.NXRemotableObject):
    def __init__(self, owner: CAE.Xyplot.XYPlotManager) -> None: ...
    def CreateHaighDiagramPlot(self, windowDevice: int, viewPortId: int, records: typing.List[CAE.FTK.BaseRecord]) -> CAE.Xyplot.Plot: ...
    def Tag(self) -> Tag: ...



class ArgumentAxisStyleSetting(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    def GetCustomerRange(self) -> int: ...
    def SetCustomerIndices(self, customerIndices: int) -> None: ...
    def GetNthItemLabel(self, nth: int) -> str: ...
    def GetIndicesOfLabel(self, itemLabel: str) -> int: ...
    def LogUnitChangedEvent(self) -> None: ...
    def GetDisplayUnit(self) -> CAE.FTK.BaseUnit: ...
    def GetAnnotationStyle(self) -> CAE.Xyplot.TextStyleSetting: ...
    def GetLabelDisplayStyle(self) -> CAE.Xyplot.CustomTextStyleSetting: ...
    @property
    def RangeAuto(self) -> bool: ...
    @RangeAuto.setter
    def RangeAuto(self, value: bool) -> None: ...
    @property
    def UnitSystemType(self) -> CAE.XyFunctionUnitSystem: ...
    @UnitSystemType.setter
    def UnitSystemType(self, value: CAE.XyFunctionUnitSystem) -> None: ...


class Argand3DFunctionDataAccessor(CAE.Xyplot.IFunctionDataAccessor):
    def __init__(self, ptr: int) -> None: ...
    def AskDisplayData(self, indenpendent1Values: float, indenpendent2Values: float) -> float: ...


class AngleUnit(enum.Enum):
    Degree= 0
    Radian= 1
    Rev= 2


class AngleAxisStyleSetting(CAE.Xyplot.BaseDisplayStyleSetting):
    def __init__(self) -> None: ...
    @property
    def AngleUnit(self) -> CAE.Xyplot.AngleUnit: ...
    @AngleUnit.setter
    def AngleUnit(self, value: CAE.Xyplot.AngleUnit) -> None: ...
    @property
    def LineDisplaySettings(self) -> CAE.Xyplot.CurveDisplaySettings: ...
    @LineDisplaySettings.setter
    def LineDisplaySettings(self, value: CAE.Xyplot.CurveDisplaySettings) -> None: ...
    @property
    def Visibility(self) -> bool: ...
    @Visibility.setter
    def Visibility(self, value: bool) -> None: ...


class AnchorType(enum.Enum):
    None_= 0
    Start= 1
    End= 2
    MaximumValue= 3
    MinimumValue= 4
    AbsPercentage= 5


