from ...NXOpen import *

import typing
import enum

class SelectBlend(TaggedObject):
    def __init__(self) -> None: ...
    def RecognizeBlends(self, baseFaces: typing.List[Face], blends: typing.List[Face]) -> None: ...
    def IncludeBlend(self, blendFace: Face) -> None: ...
    def ExcludeBlend(self, blendFace: Face) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def FaceCollector(self) -> ScCollector: ...
    @FaceCollector.setter
    def FaceCollector(self, value: ScCollector) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


