from ...NXOpen import *

import typing
import enum

class VectorFieldWrapper(NXObject):
    def __init__(self) -> None: ...
    def GetExpressionByIndex(self, index: int) -> Expression: ...
    def SetExpressions(self, expressions: typing.List[Expression]) -> None: ...
    def SetField(self, field: Fields.Field, scaleFactors: float) -> None: ...
    def GetField(self) -> Fields.Field: ...


class TimeSeriesProfileBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def SetMeasureFixed(self, isMeasureFixed: bool) -> None: ...
    def Validate(self) -> bool: ...
    def GetExternalFileReferenceAdapter(self, referenceObjectId: int) -> ExternalFileReferenceAdapter: ...
    def SetExternalFileReferenceAdapter(self, referenceObjectId: int, adapter: ExternalFileReferenceAdapter) -> None: ...
    def GetExternalFileDefinitionKey(self, adapter: ExternalFileReferenceAdapter) -> str: ...
    def EstablishReference(self, referenceObjectId: int, referenceType: ExternalFileReferenceAdapter.Type, externalFileSpec: str) -> ExternalFileReferenceAdapter: ...
    @property
    def ChannelHasMeasureUnknown(self) -> bool: ...
    @ChannelHasMeasureUnknown.setter
    def ChannelHasMeasureUnknown(self, value: bool) -> None: ...
    @property
    def ChannelName(self) -> str: ...
    @ChannelName.setter
    def ChannelName(self, value: str) -> None: ...
    @property
    def ExternalFile(self) -> str: ...
    @ExternalFile.setter
    def ExternalFile(self, value: str) -> None: ...
    @property
    def Interpolation(self) -> Fields.TimeSeriesProfileBuilder.InterpolationEnum: ...
    @Interpolation.setter
    def Interpolation(self, value: Fields.TimeSeriesProfileBuilder.InterpolationEnum) -> None: ...
    @property
    def Offset(self) -> Expression: ...
    @Offset.setter
    def Offset(self, value: Expression) -> None: ...
    @property
    def ScaleFactor(self) -> Expression: ...
    @ScaleFactor.setter
    def ScaleFactor(self, value: Expression) -> None: ...
    @property
    def TimeDelta(self) -> Expression: ...
    @TimeDelta.setter
    def TimeDelta(self, value: Expression) -> None: ...
    @property
    def UserDefinedUnitType(self) -> Unit: ...
    @UserDefinedUnitType.setter
    def UserDefinedUnitType(self, value: Unit) -> None: ...


    class InterpolationEnum(enum.Enum):
        Linear= 0
        Akima= 1
        Akima72= 2
        Cubic= 3
    

class SpatialMapBuilder(Builder):
    def __init__(self) -> None: ...
    def AutoTolerance(self) -> None: ...
    def CreateLatticeMap(self, numOfLatticeColumn: int, numOfColumns: int, indepVarArray: typing.List[Fields.FieldVariable], datapoint: float, parameterizedDatapoints: float) -> Fields.SpatialMap: ...
    def ResetMap(self, spatialMap: Fields.SpatialMap) -> None: ...
    def CreateSurfaceThroughPoints(self, locations: typing.List[Point3d], points: typing.List[Point], pointGroup: Group, feature: Features.FitSurface) -> None: ...
    def SetFitSurfaceOrientation(self, origin: Point3d, mtx: Matrix3x3) -> None: ...
    def GetBoundingBox(self) -> float: ...
    def SetBoundingBox(self, boundingbox: float) -> None: ...
    @property
    def BoundedObjects(self) -> SelectNXObjectList: ...
    @BoundedObjects.setter
    def BoundedObjects(self, value: SelectNXObjectList) -> None: ...
    @property
    def BoundingBoxMap(self) -> Fields.SpatialMap.BoundingBoxMapEnum: ...
    @BoundingBoxMap.setter
    def BoundingBoxMap(self, value: Fields.SpatialMap.BoundingBoxMapEnum) -> None: ...
    @property
    def ConstUObjects(self) -> Fields.PathObjectsList: ...
    @ConstUObjects.setter
    def ConstUObjects(self, value: Fields.PathObjectsList) -> None: ...
    @property
    def ConstVObjects(self) -> Fields.PathObjectsList: ...
    @ConstVObjects.setter
    def ConstVObjects(self, value: Fields.PathObjectsList) -> None: ...
    @property
    def CoordSystem(self) -> CoordinateSystem: ...
    @CoordSystem.setter
    def CoordSystem(self, value: CoordinateSystem) -> None: ...
    @property
    def EvaluationTolerance(self) -> Expression: ...
    @EvaluationTolerance.setter
    def EvaluationTolerance(self, value: Expression) -> None: ...
    @property
    def FaceTolerance(self) -> Expression: ...
    @FaceTolerance.setter
    def FaceTolerance(self, value: Expression) -> None: ...
    @property
    def FitSurfaceCoordinateSystem(self) -> CoordinateSystem: ...
    @FitSurfaceCoordinateSystem.setter
    def FitSurfaceCoordinateSystem(self, value: CoordinateSystem) -> None: ...
    @property
    def FitSurfaceDirectionOption(self) -> Fields.SpatialMapBuilder.FitSurfaceDirectionType: ...
    @FitSurfaceDirectionOption.setter
    def FitSurfaceDirectionOption(self, value: Fields.SpatialMapBuilder.FitSurfaceDirectionType) -> None: ...
    @property
    def FitSurfaceUDegree(self) -> int: ...
    @FitSurfaceUDegree.setter
    def FitSurfaceUDegree(self, value: int) -> None: ...
    @property
    def FitSurfaceUPatches(self) -> int: ...
    @FitSurfaceUPatches.setter
    def FitSurfaceUPatches(self, value: int) -> None: ...
    @property
    def FitSurfaceVDegree(self) -> int: ...
    @FitSurfaceVDegree.setter
    def FitSurfaceVDegree(self, value: int) -> None: ...
    @property
    def FitSurfaceVPatches(self) -> int: ...
    @FitSurfaceVPatches.setter
    def FitSurfaceVPatches(self, value: int) -> None: ...
    @property
    def FitSurfaceVector(self) -> Direction: ...
    @FitSurfaceVector.setter
    def FitSurfaceVector(self, value: Direction) -> None: ...
    @property
    def LatticePath(self) -> Fields.PathObjects: ...
    @LatticePath.setter
    def LatticePath(self, value: Fields.PathObjects) -> None: ...
    @property
    def MapSubtype(self) -> Fields.SpatialMap.SubtypeEnum: ...
    @MapSubtype.setter
    def MapSubtype(self, value: Fields.SpatialMap.SubtypeEnum) -> None: ...
    @property
    def MapSubtypeMapping(self) -> Fields.SpatialMap.SubtypeMappingEnum: ...
    @MapSubtypeMapping.setter
    def MapSubtypeMapping(self, value: Fields.SpatialMap.SubtypeMappingEnum) -> None: ...
    @property
    def MapType(self) -> Fields.SpatialMap.TypeEnum: ...
    @MapType.setter
    def MapType(self, value: Fields.SpatialMap.TypeEnum) -> None: ...
    @property
    def MappingFaces(self) -> SelectNXObjectList: ...
    @MappingFaces.setter
    def MappingFaces(self, value: SelectNXObjectList) -> None: ...
    @property
    def OppositeCorner(self) -> Point: ...
    @OppositeCorner.setter
    def OppositeCorner(self, value: Point) -> None: ...
    @property
    def Origin(self) -> Point: ...
    @Origin.setter
    def Origin(self, value: Point) -> None: ...
    @property
    def ParametricPlaneMap(self) -> Fields.SpatialMap.ParametricPlaneMapEnum: ...
    @ParametricPlaneMap.setter
    def ParametricPlaneMap(self, value: Fields.SpatialMap.ParametricPlaneMapEnum) -> None: ...


    class FitSurfaceDirectionType(enum.Enum):
        BestFit= 0
        Vector= 1
        Orientation= 2
        Csys= 3
    

class SpatialMap(NXObject):
    def __init__(self) -> None: ...


    class TypeEnum(enum.Enum):
        None_= 0
        Global= 1
        Cartesian= 2
        Cylindrical= 3
        Spherical= 4
        ParametricSpace= 5
        ParametricPlane= 6
        ParametricLine= 7
        ImportedParametricLine= 8
    

    class SubtypeMappingEnum(enum.Enum):
        Faces= 0
        IsoSections= 1
        IsoLines= 2
    

    class SubtypeEnum(enum.Enum):
        None_= 0
        Surface= 1
        FitSurface= 2
    

    class ParametricPlaneMapEnum(enum.Enum):
        IsoSections= 0
        IsoLines= 1
        ImportedIsoLines= 2
    

    class BoundingBoxMapEnum(enum.Enum):
        OppositeCorner= 0
        Objects= 1
    

class SketchProfileBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def SetMeasuresFixed(self, areMeasuresFixed: bool) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def ChordalTolerance(self) -> Expression: ...
    @ChordalTolerance.setter
    def ChordalTolerance(self, value: Expression) -> None: ...
    @property
    def DiscretePointType(self) -> Fields.FieldProfileTable.SamplingPointOption: ...
    @DiscretePointType.setter
    def DiscretePointType(self, value: Fields.FieldProfileTable.SamplingPointOption) -> None: ...
    @property
    def Interpolation(self) -> Fields.SketchProfileBuilder.InterpolationType: ...
    @Interpolation.setter
    def Interpolation(self, value: Fields.SketchProfileBuilder.InterpolationType) -> None: ...
    @property
    def NumberPoints(self) -> int: ...
    @NumberPoints.setter
    def NumberPoints(self, value: int) -> None: ...
    @property
    def Offset(self) -> Expression: ...
    @Offset.setter
    def Offset(self, value: Expression) -> None: ...
    @property
    def PointSamplingType(self) -> Fields.SketchProfileBuilder.SamplingPointType: ...
    @PointSamplingType.setter
    def PointSamplingType(self, value: Fields.SketchProfileBuilder.SamplingPointType) -> None: ...
    @property
    def Points(self) -> PointList: ...
    @Points.setter
    def Points(self, value: PointList) -> None: ...
    @property
    def Scale(self) -> Expression: ...
    @Scale.setter
    def Scale(self, value: Expression) -> None: ...
    @property
    def Sketch(self) -> SelectSketch: ...
    @Sketch.setter
    def Sketch(self, value: SelectSketch) -> None: ...
    @property
    def UnitType(self) -> Unit: ...
    @UnitType.setter
    def UnitType(self, value: Unit) -> None: ...


    class SamplingPointType(enum.Enum):
        ChordalTolerance= 0
        EqualArcLength= 1
    

    class InterpolationType(enum.Enum):
        Linear= 0
        Akima= 1
        Akima72= 2
        Cubic= 3
    

class ScalarFieldWrapper(NXObject):
    def __init__(self) -> None: ...
    def SetExpression(self, expression: Expression) -> None: ...
    def GetExpression(self) -> Expression: ...
    def GetField(self) -> Fields.Field: ...
    def SetField(self, field: Fields.Field, scaleFactor: float) -> None: ...
    def GetFieldScaleFactor(self) -> float: ...


class ProfileSolverOptionsBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def Cyclic(self) -> Fields.ProfileSolverOptionsBuilder.CyclicType: ...
    @Cyclic.setter
    def Cyclic(self, value: Fields.ProfileSolverOptionsBuilder.CyclicType) -> None: ...
    @property
    def SlopeLeft(self) -> Expression: ...
    @SlopeLeft.setter
    def SlopeLeft(self, value: Expression) -> None: ...
    @property
    def SlopeRight(self) -> Expression: ...
    @SlopeRight.setter
    def SlopeRight(self, value: Expression) -> None: ...
    @property
    def XExtrapolation(self) -> Fields.ProfileSolverOptionsBuilder.Extrapolation: ...
    @XExtrapolation.setter
    def XExtrapolation(self, value: Fields.ProfileSolverOptionsBuilder.Extrapolation) -> None: ...
    @property
    def XInterpolation(self) -> Fields.ProfileSolverOptionsBuilder.Interpolation: ...
    @XInterpolation.setter
    def XInterpolation(self, value: Fields.ProfileSolverOptionsBuilder.Interpolation) -> None: ...
    @property
    def YExtrapolation(self) -> Fields.ProfileSolverOptionsBuilder.Extrapolation: ...
    @YExtrapolation.setter
    def YExtrapolation(self, value: Fields.ProfileSolverOptionsBuilder.Extrapolation) -> None: ...
    @property
    def YInterpolation(self) -> Fields.ProfileSolverOptionsBuilder.Interpolation: ...
    @YInterpolation.setter
    def YInterpolation(self, value: Fields.ProfileSolverOptionsBuilder.Interpolation) -> None: ...


    class Interpolation(enum.Enum):
        Linear= 0
        Akima= 1
        Akima72= 2
        Cubic= 3
    

    class Extrapolation(enum.Enum):
        Linear= 0
        Parabolic= 1
        Cubic= 2
    

    class CyclicType(enum.Enum):
        None_= 0
        XOnly= 1
        YOnly= 2
        Both= 3
    

class PathObjectsList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[Fields.PathObjects]) -> None: ...
    @typing.overload
    def Append(self, object: Fields.PathObjects) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: Fields.PathObjects) -> int: ...
    def FindItem(self, index: int) -> Fields.PathObjects: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: Fields.PathObjects) -> None: ...
    @typing.overload
    def Erase(self, obj: Fields.PathObjects, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[Fields.PathObjects]: ...
    def SetContents(self, objects: typing.List[Fields.PathObjects]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: Fields.PathObjects, object2: Fields.PathObjects) -> None: ...
    def Insert(self, location: int, object: Fields.PathObjects) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class PathObjects(SelectObjectList):
    def __init__(self) -> None: ...
    def ReverseDirection(self) -> None: ...
    def HandleLatestSelDirection(self) -> None: ...
    def ReverseSectionDirection(self, index: int) -> None: ...


class NameVariable(NXObject):
    def __init__(self) -> None: ...
    @property
    def Measure(self) -> str: ...
    @Measure.setter
    def Measure(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class ManualInputProfileBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def SetDataPointValues(self, dataPoints: float) -> None: ...
    def SetDataPointExpressions(self, dataPointCellIds: int, dataPointExpressions: str) -> None: ...
    def SetMeasuresFixed(self, areMeasuresFixed: bool) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def Cyclic(self) -> Fields.ManualInputProfileBuilder.CyclicType: ...
    @Cyclic.setter
    def Cyclic(self, value: Fields.ManualInputProfileBuilder.CyclicType) -> None: ...
    @property
    def OrdinateOffset(self) -> Expression: ...
    @OrdinateOffset.setter
    def OrdinateOffset(self, value: Expression) -> None: ...
    @property
    def OrdinateScale(self) -> Expression: ...
    @OrdinateScale.setter
    def OrdinateScale(self, value: Expression) -> None: ...
    @property
    def OrdinateUnitType(self) -> Unit: ...
    @OrdinateUnitType.setter
    def OrdinateUnitType(self, value: Unit) -> None: ...
    @property
    def SlopeLeft(self) -> Expression: ...
    @SlopeLeft.setter
    def SlopeLeft(self, value: Expression) -> None: ...
    @property
    def SlopeRight(self) -> Expression: ...
    @SlopeRight.setter
    def SlopeRight(self, value: Expression) -> None: ...
    @property
    def SolverOptions(self) -> Fields.ProfileSolverOptionsBuilder: ...
    @SolverOptions.setter
    def SolverOptions(self, value: Fields.ProfileSolverOptionsBuilder) -> None: ...
    @property
    def XExtrapolation(self) -> Fields.ManualInputProfileBuilder.Extrapolation: ...
    @XExtrapolation.setter
    def XExtrapolation(self, value: Fields.ManualInputProfileBuilder.Extrapolation) -> None: ...
    @property
    def XInterpolation(self) -> Fields.ManualInputProfileBuilder.Interpolation: ...
    @XInterpolation.setter
    def XInterpolation(self, value: Fields.ManualInputProfileBuilder.Interpolation) -> None: ...
    @property
    def XOffset(self) -> Expression: ...
    @XOffset.setter
    def XOffset(self, value: Expression) -> None: ...
    @property
    def XScale(self) -> Expression: ...
    @XScale.setter
    def XScale(self, value: Expression) -> None: ...
    @property
    def XUnitType(self) -> Unit: ...
    @XUnitType.setter
    def XUnitType(self, value: Unit) -> None: ...


    class Interpolation(enum.Enum):
        Linear= 0
        Akima= 1
        Akima72= 2
        Cubic= 3
    

    class Extrapolation(enum.Enum):
        Linear= 0
        Parabolic= 1
    

    class CyclicType(enum.Enum):
        None_= 0
        XOnly= 1
    

class ManualInputProfile(Fields.FieldTable):
    def __init__(self) -> None: ...


class ImportTableDataBuilder(Builder):
    def __init__(self) -> None: ...
    def RescanImportFile(self) -> None: ...
    def SetClearTableOnImport(self) -> None: ...
    @property
    def CreateSpatialMap(self) -> bool: ...
    @CreateSpatialMap.setter
    def CreateSpatialMap(self, value: bool) -> None: ...
    @property
    def DuplicateValues(self) -> Fields.FieldTable.DuplicateValueOption: ...
    @DuplicateValues.setter
    def DuplicateValues(self, value: Fields.FieldTable.DuplicateValueOption) -> None: ...
    @property
    def ImportFile(self) -> str: ...
    @ImportFile.setter
    def ImportFile(self, value: str) -> None: ...
    @property
    def IsStructDataFormat(self) -> bool: ...
    @IsStructDataFormat.setter
    def IsStructDataFormat(self, value: bool) -> None: ...
    @property
    def NumStructDataColumns(self) -> int: ...
    @NumStructDataColumns.setter
    def NumStructDataColumns(self, value: int) -> None: ...
    @property
    def NumStructDataPlanes(self) -> int: ...
    @NumStructDataPlanes.setter
    def NumStructDataPlanes(self, value: int) -> None: ...
    @property
    def NumStructDataRows(self) -> int: ...
    @NumStructDataRows.setter
    def NumStructDataRows(self, value: int) -> None: ...


class ImportData(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def SetFileName(self, fileName: str) -> None: ...
    def GetFileName(self) -> str: ...
    def GetFields(self, fields: typing.List[Fields.Field]) -> None: ...
    def FreeResource(self) -> None: ...
    def GetMessages(self, messages: str) -> None: ...


class ImportBuilder(Builder):
    def __init__(self) -> None: ...
    def SetImportAction(self, nthField: int, action: int) -> None: ...
    def GetImportAction(self, nthField: int) -> int: ...
    def GetNumFields(self) -> int: ...
    def SetNthImportAction(self, nthField: int, action: Fields.ImportBuilder.ActionType) -> None: ...
    def GetNthImportAction(self, nthField: int) -> Fields.ImportBuilder.ActionType: ...
    def GetNthFieldName(self, nthField: int) -> str: ...
    def GetNthConflictType(self, nthField: int) -> Fields.ImportBuilder.ConflictType: ...
    @property
    def ConflictResolutionStrategy(self) -> Fields.ImportBuilder.ImportConflictStrategy: ...
    @ConflictResolutionStrategy.setter
    def ConflictResolutionStrategy(self, value: Fields.ImportBuilder.ImportConflictStrategy) -> None: ...
    @property
    def FilterOptions(self) -> Fields.ImportBuilder.ImportFilter: ...
    @FilterOptions.setter
    def FilterOptions(self, value: Fields.ImportBuilder.ImportFilter) -> None: ...
    @property
    def FilterString(self) -> str: ...
    @FilterString.setter
    def FilterString(self, value: str) -> None: ...
    @property
    def ImportField(self) -> Fields.Field: ...
    @ImportField.setter
    def ImportField(self, value: Fields.Field) -> None: ...
    @property
    def ImportFile(self) -> str: ...
    @ImportFile.setter
    def ImportFile(self, value: str) -> None: ...
    @property
    def ImportFolders(self) -> bool: ...
    @ImportFolders.setter
    def ImportFolders(self, value: bool) -> None: ...
    @property
    def PrependString(self) -> str: ...
    @PrependString.setter
    def PrependString(self, value: str) -> None: ...


    class ImportFilter(enum.Enum):
        All= 0
        Formula= 1
        Table= 2
        LinkedField= 3
        TableofFields= 4
        FilterbyName= 5
        FilterbyDomain= 6
        FilterbyDependentVariableName= 7
        FilterbyIndependentVariableName= 8
    

    class ImportFieldStrategy(enum.Enum):
        Skip= 0
        RenameExisting= 1
        RenameImported= 2
        Replace= 3
        BackupReplace= 4
    

    class ImportConflictStrategy(enum.Enum):
        AppendtoImportedFieldName= 0
        PrependStringtoImportedFieldName= 1
        UserSpecifiedReplaceandorRename= 2
    

    class ConflictType(enum.Enum):
        NoConflict= 0
        NameOnlyConflict= 1
        NameOnlyConflictInUse= 2
        CompatibleVariableConflict= 3
        CompatibleVariableConflictInUse= 4
        IncompatibleVariableConflict= 5
        IncompatibleVariableConflictInUse= 6
    

    class ActionType(enum.Enum):
        Import= 0
        DontImport= 1
        ImportAppend= 2
        Replace= 3
        BackupAndReplace= 4
        ImportPrepend= 5
    

class IApplicationData():
    def GetApplication(self) -> Fields.IApplication: ...
    def DeleteApplicationData(self) -> None: ...
    def CopyToField(self, field: Fields.Field) -> None: ...


class IApplication(TaggedObject):
    def __init__(self) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...


class FieldWrapper(NXObject):
    def __init__(self) -> None: ...
    def GetField(self) -> Fields.Field: ...
    def SetField(self, field: Fields.Field) -> None: ...


class FieldVariable(NXObject):
    def __init__(self) -> None: ...
    @property
    def DefaultValue(self) -> float: ...
    @DefaultValue.setter
    def DefaultValue(self, value: float) -> None: ...
    @property
    def Logarithmic(self) -> bool: ...
    @Logarithmic.setter
    def Logarithmic(self, value: bool) -> None: ...
    @property
    def NameVariable(self) -> Fields.NameVariable: ...
    @NameVariable.setter
    def NameVariable(self, value: Fields.NameVariable) -> None: ...
    @property
    def NumPoints(self) -> int: ...
    @NumPoints.setter
    def NumPoints(self, value: int) -> None: ...
    @property
    def Units(self) -> Unit: ...
    @Units.setter
    def Units(self, value: Unit) -> None: ...
    @property
    def VariableBounds(self) -> Fields.FieldVariable.Bounds: ...
    @VariableBounds.setter
    def VariableBounds(self, value: Fields.FieldVariable.Bounds) -> None: ...
    @property
    def VariableType(self) -> Fields.FieldVariable.Type: ...
    @VariableType.setter
    def VariableType(self, value: Fields.FieldVariable.Type) -> None: ...


    class ValueType(enum.Enum):
        Real= 0
        Imaginary= 1
        ComplexRealImaginary= 2
        ComplexMagnitudePhase= 3
        Complex= 4
        Integer= 5
    

    class Type(enum.Enum):
        Unknown= -1
        Independent= 0
        Dependent= 1
    

    class FieldVariableBounds():
        @property
        def IsMinimumDefined(self) -> bool: ...
        @IsMinimumDefined.setter
        def IsMinimumDefined(self, value: bool) -> None: ...
        @property
        def IsMinimumInclusive(self) -> bool: ...
        @IsMinimumInclusive.setter
        def IsMinimumInclusive(self, value: bool) -> None: ...
        @property
        def MinimumValue(self) -> float: ...
        @MinimumValue.setter
        def MinimumValue(self, value: float) -> None: ...
        @property
        def IsMaximumDefined(self) -> bool: ...
        @IsMaximumDefined.setter
        def IsMaximumDefined(self, value: bool) -> None: ...
        @property
        def IsMaximumInclusive(self) -> bool: ...
        @IsMaximumInclusive.setter
        def IsMaximumInclusive(self, value: bool) -> None: ...
        @property
        def MaximumValue(self) -> float: ...
        @MaximumValue.setter
        def MaximumValue(self, value: float) -> None: ...
        def ToString(self) -> str: ...
    

class FieldTable(Fields.Field):
    def __init__(self) -> None: ...
    def EditFieldTable(self, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float) -> None: ...
    def EditFieldTableComplexDisplay(self, indepVarArrayComplexDisplay: bool, depVarArrayComplexDisplay: bool) -> None: ...
    def EditFieldTableComplexUnits(self, depVarArrayComplexUnits: typing.List[Unit]) -> None: ...
    @typing.overload
    def GetIdwOptions(self, nearestOption: Fields.FieldEvaluator.InverseDistanceWeightingEnum, nearestFraction: float) -> None: ...
    @typing.overload
    def GetIdwOptions(self, nearestOption: Fields.FieldEvaluator.InverseDistanceWeightingEnum, nearestFraction: float, maximumRadius: float, numberOfPoints: int, powerOfDistance: Fields.FieldEvaluator.InverseDistanceWeightingPowerOfDistanceEnum) -> None: ...
    @typing.overload
    def SetIdwOptions(self, nearestOption: Fields.FieldEvaluator.InverseDistanceWeightingEnum, nearestFraction: float) -> None: ...
    @typing.overload
    def SetIdwOptions(self, nearestOption: Fields.FieldEvaluator.InverseDistanceWeightingEnum, nearestFraction: float, maximumRadius: float, numberOfPoints: int, powerOfDistance: Fields.FieldEvaluator.InverseDistanceWeightingPowerOfDistanceEnum) -> None: ...
    def LoadFromFile(self, filename: str, loadFileOption: Fields.FieldTable.LoadFileOption) -> None: ...
    def GetData(self, variable: Fields.FieldVariable) -> float: ...
    def EditTableVariables(self, indepVarArray: typing.List[Fields.FieldVariable], depExpArray: typing.List[Fields.FieldVariable]) -> None: ...
    def EditDbScaling(self, dbScaleFactor: float, dbRefValue: float, isDbScaling: bool) -> None: ...
    def CreateInterpolator(self) -> None: ...
    def ProcessPendingUpdate(self) -> None: ...
    def EditTableLatticeData(self, latticeType: Fields.FieldTable.StructDataTableType, numLatticeRows: int, numLatticeColumns: int, numLatticePlanes: int) -> None: ...
    def GetTablePoints(self, pointObjectRowIds: int, pointObjects: typing.List[Point]) -> None: ...
    def EditFieldTableWithPoints(self, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, pointObjectRowIds: int, pointObjects: typing.List[Point]) -> None: ...
    @typing.overload
    def EditFieldTableWithExpressions(self, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, expCellIds: int, valueStrings: str) -> None: ...
    @typing.overload
    def EditFieldTableWithExpressions(self, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, expCellIds: int, valueStrings: str, cellReadOnlys: bool) -> None: ...
    def XYGraph3DStructuredData(self, xAxisIndepVar: Fields.FieldVariable, zAxisIndepVar: Fields.FieldVariable, yAxisDepVar: Fields.FieldVariable, structuredDataPlaneIndex: int, windowDevice: int, viewIndex: int, overlay: bool, scaleFactor: float) -> CAE.Xyplot.Plot: ...
    def SetConservativeOptions(self, annTolerance: float, maximumRadius: float, numberOfPoints: int) -> None: ...
    def GetVariableScaleFactor(self, varType: Fields.FieldVariable.Type) -> Expression: ...
    def SetVariableScaleFactor(self, varType: Fields.FieldVariable.Type, scaleFactor: Expression) -> None: ...
    def GetVariableOffset(self, varType: Fields.FieldVariable.Type) -> Expression: ...
    def SetVariableOffset(self, varType: Fields.FieldVariable.Type, offset: Expression) -> None: ...
    @property
    def AnnTolerance(self) -> float: ...
    @AnnTolerance.setter
    def AnnTolerance(self, value: float) -> None: ...
    @property
    def CreateInterpolatorOnCommit(self) -> bool: ...
    @CreateInterpolatorOnCommit.setter
    def CreateInterpolatorOnCommit(self, value: bool) -> None: ...
    @property
    def DelaunayDeleteSlivers(self) -> bool: ...
    @DelaunayDeleteSlivers.setter
    def DelaunayDeleteSlivers(self, value: bool) -> None: ...
    @property
    def DelaunayRatioTolerance(self) -> float: ...
    @DelaunayRatioTolerance.setter
    def DelaunayRatioTolerance(self, value: float) -> None: ...
    @property
    def DelaunaySliverDetectionMethod(self) -> Fields.FieldEvaluator.DelaunaySliverDetectionMethodEnum: ...
    @DelaunaySliverDetectionMethod.setter
    def DelaunaySliverDetectionMethod(self, value: Fields.FieldEvaluator.DelaunaySliverDetectionMethodEnum) -> None: ...
    @property
    def DelaunaySnapVertices(self) -> bool: ...
    @DelaunaySnapVertices.setter
    def DelaunaySnapVertices(self, value: bool) -> None: ...
    @property
    def DelayedUpdate(self) -> bool: ...
    @DelayedUpdate.setter
    def DelayedUpdate(self, value: bool) -> None: ...
    @property
    def Discontinuities(self) -> bool: ...
    @Discontinuities.setter
    def Discontinuities(self, value: bool) -> None: ...
    @property
    def DuplicateValueProcessingOption(self) -> Fields.FieldTable.DuplicateValueOption: ...
    @DuplicateValueProcessingOption.setter
    def DuplicateValueProcessingOption(self, value: Fields.FieldTable.DuplicateValueOption) -> None: ...
    @property
    def FallbackToDefaultInterpolator(self) -> bool: ...
    @FallbackToDefaultInterpolator.setter
    def FallbackToDefaultInterpolator(self, value: bool) -> None: ...
    @property
    def IndependentValueDivisor(self) -> float: ...
    @IndependentValueDivisor.setter
    def IndependentValueDivisor(self, value: float) -> None: ...
    @property
    def IndependentValueDivisorOption(self) -> bool: ...
    @IndependentValueDivisorOption.setter
    def IndependentValueDivisorOption(self, value: bool) -> None: ...
    @property
    def IndependentValueShift(self) -> float: ...
    @IndependentValueShift.setter
    def IndependentValueShift(self, value: float) -> None: ...
    @property
    def IndependentValueShiftOption(self) -> bool: ...
    @IndependentValueShiftOption.setter
    def IndependentValueShiftOption(self, value: bool) -> None: ...
    @property
    def InterpolationMethod(self) -> Fields.FieldEvaluator.InterpolationEnum: ...
    @InterpolationMethod.setter
    def InterpolationMethod(self, value: Fields.FieldEvaluator.InterpolationEnum) -> None: ...
    @property
    def LinearLogOption(self) -> Fields.FieldEvaluator.LinearLogOptionEnum: ...
    @LinearLogOption.setter
    def LinearLogOption(self, value: Fields.FieldEvaluator.LinearLogOptionEnum) -> None: ...
    @property
    def ParameterizeIndependentDomain(self) -> bool: ...
    @ParameterizeIndependentDomain.setter
    def ParameterizeIndependentDomain(self, value: bool) -> None: ...
    @property
    def PersistentInterpolator(self) -> bool: ...
    @PersistentInterpolator.setter
    def PersistentInterpolator(self, value: bool) -> None: ...
    @property
    def ValuesOutsideHighTableUserdefinedValue(self) -> float: ...
    @ValuesOutsideHighTableUserdefinedValue.setter
    def ValuesOutsideHighTableUserdefinedValue(self, value: float) -> None: ...
    @property
    def ValuesOutsideTableInterpolation(self) -> Fields.FieldEvaluator.ValuesOutsideTableInterpolationEnum: ...
    @ValuesOutsideTableInterpolation.setter
    def ValuesOutsideTableInterpolation(self, value: Fields.FieldEvaluator.ValuesOutsideTableInterpolationEnum) -> None: ...
    @property
    def ValuesOutsideTableUserdefinedValue(self) -> float: ...
    @ValuesOutsideTableUserdefinedValue.setter
    def ValuesOutsideTableUserdefinedValue(self, value: float) -> None: ...


    class StructDataTableType(enum.Enum):
        Regular= 0
        Strict= 1
    

    class LoadFileOption(enum.Enum):
        Append= 0
        Replace= 1
    

    class DuplicateValueOption(enum.Enum):
        None_= 0
        Average= 1
        Minimum= 2
        Maximum= 3
        First= 4
        Last= 5
        Skip= 6
    

    class DBFactor(enum.Enum):
        AcousticPowerDefault= 0
        AcousticPressureDefault= 1
    

class FieldReference(Fields.Field):
    def __init__(self) -> None: ...
    def GetSecondaryValuesOutsideTableInterpolation(self) -> Fields.FieldEvaluator.ValuesOutsideTableInterpolationEnum: ...
    def SetSecondaryValuesOutsideTableInterpolation(self, interpolMethod: Fields.FieldEvaluator.ValuesOutsideTableInterpolationEnum) -> None: ...
    @property
    def ValuesOutsideTableInterpolation(self) -> Fields.FieldEvaluator.ValuesOutsideTableInterpolationEnum: ...
    @ValuesOutsideTableInterpolation.setter
    def ValuesOutsideTableInterpolation(self, value: Fields.FieldEvaluator.ValuesOutsideTableInterpolationEnum) -> None: ...


class FieldProfileTable(Fields.FieldTable):
    def __init__(self) -> None: ...


    class SamplingPointOption(enum.Enum):
        ChordalTolerance= 0
        EqualArcLength= 1
    

class FieldManager(NXObject):
    def __init__(self) -> None: ...
    def CreateFieldExpression(self, fieldExpString: str, unitType: Unit) -> Fields.FieldExpression: ...
    def CreateSubFieldExpression(self, depVar: Fields.FieldVariable) -> Fields.FieldExpression: ...
    def CreateFieldFormula(self, fieldName: str, indepVarArray: typing.List[Fields.FieldVariable], depExpArray: typing.List[Fields.FieldExpression]) -> Fields.FieldFormula: ...
    @typing.overload
    def CreateFieldTable(self, fieldName: str, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float) -> Fields.FieldTable: ...
    @typing.overload
    def CreateFieldTable(self, fieldName: str, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, duplicateValueProcessingOption: Fields.FieldTable.DuplicateValueOption) -> Fields.FieldTable: ...
    @typing.overload
    def CreateFieldTable(self, fieldName: str, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, duplicateValueProcessingOption: Fields.FieldTable.DuplicateValueOption, structDataType: Fields.FieldTable.StructDataTableType, numStructDataRows: int, numStructDataColumns: int, numStructDataPlanes: int) -> Fields.FieldTable: ...
    def CreateFieldTableFromData(self, fieldNamePrefix: str, ivarUnit: Unit, dvarUnit: Unit, dvarType: Fields.FieldVariable.ValueType, datapoints: float) -> Fields.FieldTable: ...
    def CreateFieldLink(self, fieldName: str, fieldToLink: Fields.Field) -> Fields.FieldLink: ...
    def DeleteField(self, field: Fields.Field) -> Fields.Field: ...
    def DeleteFields(self, fields: typing.List[Fields.Field]) -> bool: ...
    @typing.overload
    def CreateIndependentVariable(self, ownerField: Fields.Field, nameVariable: Fields.NameVariable, unitType: Unit, minValueSet: bool, minValueInclusive: bool, minValue: float, maxValueSet: bool, maxValueInclusive: bool, maxValue: float, numPtsSet: bool, numPts: int, defaultValueSet: bool, defaultValue: float) -> Fields.FieldVariable: ...
    @typing.overload
    def CreateIndependentVariable(self, ownerField: Fields.Field, nameVariable: Fields.NameVariable, unitType: Unit, type: Fields.FieldVariable.ValueType, minValueSet: bool, minValueInclusive: bool, minValue: float, maxValueSet: bool, maxValueInclusive: bool, maxValue: float, numPtsSet: bool, numPts: int, defaultValueSet: bool, defaultValue: float) -> Fields.FieldVariable: ...
    @typing.overload
    def EditIndependentVariable(self, indepVar: Fields.FieldVariable, varName: str, unitType: Unit, minValueSet: bool, minValueInclusive: bool, minValue: float, maxValueSet: bool, maxValueInclusive: bool, maxValue: float, numPtsSet: bool, numPts: int, defaultValueSet: bool, defaultValue: float) -> None: ...
    @typing.overload
    def EditIndependentVariable(self, indepVar: Fields.FieldVariable, unitType: Unit) -> None: ...
    @typing.overload
    def CreateDependentVariable(self, ownerField: Fields.Field, nameVariable: Fields.NameVariable, unitType: Unit) -> Fields.FieldVariable: ...
    @typing.overload
    def CreateDependentVariable(self, ownerField: Fields.Field, nameVariable: Fields.NameVariable, unitType: Unit, type: Fields.FieldVariable.ValueType) -> Fields.FieldVariable: ...
    @typing.overload
    def EditDependentVariable(self, depVar: Fields.FieldVariable, varName: str, unitType: Unit) -> None: ...
    @typing.overload
    def EditDependentVariable(self, depVar: Fields.FieldVariable, unitType: Unit) -> None: ...
    def CreateFieldWrapper(self, field: Fields.Field) -> Fields.FieldWrapper: ...
    def CreateScalarFieldWrapperWithExpression(self, expression: Expression) -> Fields.ScalarFieldWrapper: ...
    def CreateScalarFieldWrapperWithField(self, field: Fields.Field, scaleFactor: float) -> Fields.ScalarFieldWrapper: ...
    def CreateVectorFieldWrapperWithExpressions(self, expressions: typing.List[Expression]) -> Fields.VectorFieldWrapper: ...
    def CreateVectorFieldWrapperWithField(self, field: Fields.Field, scaleFactors: float) -> Fields.VectorFieldWrapper: ...
    def CreateComplexScalarFieldWrapperWithExpressions(self, expressions: typing.List[Expression]) -> Fields.ComplexScalarFieldWrapper: ...
    def CreateComplexScalarFieldWrapperWithField(self, field: Fields.Field) -> Fields.ComplexScalarFieldWrapper: ...
    def CreateDisplayPropertiesBuilder(self, fieldArray: typing.List[Fields.Field]) -> Fields.DisplayPropertiesBuilder: ...
    def CreateGlobalSpatialMap(self) -> Fields.SpatialMap: ...
    def CreateSpatialMapBuilder(self, spatialmap: Fields.SpatialMap) -> Fields.SpatialMapBuilder: ...
    def CreateExportData(self) -> Fields.ExportData: ...
    def ExportFields(self, exportData: Fields.ExportData) -> None: ...
    def CreateImportData(self) -> Fields.ImportData: ...
    def CreateImportBuilder(self) -> Fields.ImportBuilder: ...
    def ImportFields(self, importData: Fields.ImportData) -> None: ...
    def CreatePathObjects(self) -> Fields.PathObjects: ...
    def GetNameVariable(self, variableName: str, measureName: str) -> Fields.NameVariable: ...
    def GetValidFieldId(self) -> int: ...
    @typing.overload
    def CreateFieldLinksTable(self, fieldName: str, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, linkFieldsArray: typing.List[Fields.Field]) -> Fields.FieldLinksTable: ...
    @typing.overload
    def CreateFieldLinksTable(self, fieldName: str, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, linkFieldsArray: typing.List[Fields.Field], managedFieldsArray: bool) -> Fields.FieldLinksTable: ...
    def CreateFieldLinksTableWithConstants(self, fieldName: str, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, linkFieldsArray: typing.List[Fields.Field], managedFieldsArray: bool) -> Fields.FieldLinksTable: ...
    def CreateMeshSizeFieldData(self, elementSizeType: int, meshArray: typing.List[TaggedObject]) -> Fields.Field: ...
    def ConvertToLinksTable(self, table: Fields.FieldTable) -> Fields.FieldLinksTable: ...
    def CreateComplexScalarFieldWrapperWithFieldWithScaleFactor(self, field: Fields.Field, scaleFactor: float) -> Fields.ComplexScalarFieldWrapper: ...
    def CreateComplexVectorFieldWrapperWithExpressions(self, expressions: typing.List[Expression]) -> Fields.ComplexVectorFieldWrapper: ...
    def CreateComplexVectorFieldWrapperWithField(self, field: Fields.Field, scaleFactor: float) -> Fields.ComplexVectorFieldWrapper: ...
    def CreateImportTableDataBuilder(self, fieldName: str, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable]) -> Fields.ImportTableDataBuilder: ...
    def SetUndefinedVariableValue(self, undefinedValue: float) -> None: ...
    def CreateImportTableDataBuilderFromTable(self, fieldTable: Fields.FieldTable) -> Fields.ImportTableDataBuilder: ...
    def CreateFieldTableWithPoints(self, fieldName: str, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, duplicateValueProcessingOption: Fields.FieldTable.DuplicateValueOption, pointObjectRowIds: int, pointObjects: typing.List[Point]) -> Fields.FieldTable: ...
    @typing.overload
    def CreateFieldTableWithExpressions(self, fieldName: str, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, dupValueProcessOption: Fields.FieldTable.DuplicateValueOption, expCellIds: int, valueStrings: str) -> Fields.FieldTable: ...
    @typing.overload
    def CreateFieldTableWithExpressions(self, fieldName: str, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, dupValueProcessOption: Fields.FieldTable.DuplicateValueOption, expCellIds: int, valueStrings: str, cellReadOnlys: bool) -> Fields.FieldTable: ...
    def DeleteFolders(self, folders: typing.List[Fields.FieldFolder], survivingFields: typing.List[Fields.Field]) -> None: ...
    @property
    def Domains(self) -> Fields.FieldDomainCollection: ...
    @Domains.setter
    def Domains(self, value: Fields.FieldDomainCollection) -> None: ...
    @property
    def Fields(self) -> Fields.FieldCollection: ...
    @Fields.setter
    def Fields(self, value: Fields.FieldCollection) -> None: ...
    @property
    def FieldFolders(self) -> Fields.FieldFolderCollection: ...
    @FieldFolders.setter
    def FieldFolders(self, value: Fields.FieldFolderCollection) -> None: ...


class FieldLinksTable(Fields.Field):
    def __init__(self) -> None: ...
    @typing.overload
    def EditFieldLinksTable(self, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, linkFieldsArray: typing.List[Fields.Field]) -> None: ...
    @typing.overload
    def EditFieldLinksTable(self, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, linkFieldsArray: typing.List[Fields.Field], managedFieldsArray: bool) -> None: ...
    def EditFieldLinksTableWithConstants(self, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable], datapoints: float, linkFieldsArray: typing.List[Fields.Field], managedFieldsArray: bool) -> None: ...
    def SetSecondaryValuesOutsideTableInterpolation(self, interpolationMethod: Fields.FieldEvaluator.ValuesOutsideTableInterpolationEnum) -> None: ...
    def GetPrimaryIndependentVariableScaleFactor(self) -> Expression: ...
    def SetPrimaryIndependentVariableScaleFactor(self, scaleFactor: Expression) -> None: ...
    def GetPrimaryIndependentVariableOffset(self) -> Expression: ...
    def SetPrimaryIndependentVariableOffset(self, offset: Expression) -> None: ...
    @property
    def Discontinuities(self) -> bool: ...
    @Discontinuities.setter
    def Discontinuities(self, value: bool) -> None: ...
    @property
    def ValuesOutsideTableInterpolation(self) -> Fields.FieldEvaluator.ValuesOutsideTableInterpolationEnum: ...
    @ValuesOutsideTableInterpolation.setter
    def ValuesOutsideTableInterpolation(self, value: Fields.FieldEvaluator.ValuesOutsideTableInterpolationEnum) -> None: ...


class FieldLink(Fields.Field):
    def __init__(self) -> None: ...
    def EditFieldLink(self, fieldToLink: Fields.Field) -> None: ...


class FieldFormula(Fields.Field):
    def __init__(self) -> None: ...
    def EditFieldFormula(self, indepVarArray: typing.List[Fields.FieldVariable], depExpArray: typing.List[Fields.FieldExpression]) -> None: ...
    def EditFieldFormulaVariables(self, indepVarArray: typing.List[Fields.FieldVariable], depVarArray: typing.List[Fields.FieldVariable]) -> None: ...
    def GetDependentExpressions(self) -> typing.List[Fields.FieldExpression]: ...
    @property
    def CombineTable(self) -> Fields.FieldExpression.CombineTableOption: ...
    @CombineTable.setter
    def CombineTable(self, value: Fields.FieldExpression.CombineTableOption) -> None: ...


class FieldFolderCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Fields.FieldFolder]: ...
    @typing.overload
    def __init__(self, owner: Fields.FieldManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateFolder(self, name: str, parent: Fields.FieldFolder) -> Fields.FieldFolder: ...
    def FindObject(self, journalIdentifier: str) -> Fields.FieldFolder: ...
    def Tag(self) -> Tag: ...



class FieldFolder(NXObject):
    def __init__(self) -> None: ...
    def AddSubfolder(self, subfolder: Fields.FieldFolder) -> None: ...
    def RemoveSubfolder(self, subfolder: Fields.FieldFolder) -> None: ...
    def AddField(self, field: Fields.Field) -> None: ...
    def RemoveField(self, field: Fields.Field) -> None: ...
    def GetParent(self) -> CAE.IFolder: ...
    def GetChildren(self) -> typing.List[CAE.IFolder]: ...
    def GetMembers(self) -> typing.List[NXObject]: ...
    @property
    def Parent(self) -> Fields.FieldFolder: ...
    @Parent.setter
    def Parent(self, value: Fields.FieldFolder) -> None: ...


class FieldExpression(Fields.Field):
    def __init__(self) -> None: ...
    def EditFieldExpression(self, fieldExpString: str, unitType: Unit, indepVarArray: typing.List[Fields.FieldVariable], updateFlag: bool) -> None: ...
    def GetFieldExpressionString(self) -> str: ...
    def SetFieldExpressionString(self, fieldExpString: str, updateFlag: bool) -> None: ...
    @property
    def CombineTable(self) -> Fields.FieldExpression.CombineTableOption: ...
    @CombineTable.setter
    def CombineTable(self, value: Fields.FieldExpression.CombineTableOption) -> None: ...
    @property
    def FieldExpressionUnits(self) -> Unit: ...
    @FieldExpressionUnits.setter
    def FieldExpressionUnits(self, value: Unit) -> None: ...


    class CombineTableOption(enum.Enum):
        Intersection= 0
        Union= 1
    

class FieldEvaluator(TaggedObject):
    def __init__(self) -> None: ...
    def GetDependentVariables(self) -> typing.List[Fields.FieldVariable]: ...
    def GetIndependentVariables(self) -> typing.List[Fields.FieldVariable]: ...
    def SetIndependentVariableValues(self, independentVariable: Fields.FieldVariable, values: float) -> None: ...
    def Evaluate(self, dependentVariable: Fields.FieldVariable) -> float: ...
    def Delete(self) -> None: ...
    @property
    def InterpolationMethod(self) -> Fields.FieldEvaluator.InterpolationEnum: ...
    @InterpolationMethod.setter
    def InterpolationMethod(self, value: Fields.FieldEvaluator.InterpolationEnum) -> None: ...


    class ValuesOutsideTableInterpolationEnum(enum.Enum):
        Undefined= 0
        Extrapolate= 1
        Constant= 2
        Linear= 3
        Parabolic= 4
        Cubic= 5
        Userdefined= 6
    

    class LinearLogOptionEnum(enum.Enum):
        LinearLinear= 0
        LogLinear= 1
        LinearLog= 2
        LogLog= 3
        ScaleOffset= 4
    

    class InverseDistanceWeightingPowerOfDistanceEnum(enum.Enum):
        One= 1
        Two= 2
        Three= 3
    

    class InverseDistanceWeightingEnum(enum.Enum):
        All= 0
        Radius= 1
        NearestPoints= 2
        NumNearestPoints= 3
        MaximumRadiusAndPoints= 4
    

    class InterpolationEnum(enum.Enum):
        None_= 0
        Linear1d= 1
        NearestNeighbor1d= 2
        InverseDistanceWeighting1d= 3
        Delaunay2dFast= 4
        Delaunay2dMedium= 5
        Delaunay2dAccurate= 6
        NearestNeighbor2d= 7
        RenkaShepard2d= 8
        InverseDistanceWeighting2d= 9
        Delaunay3dFast= 10
        Delaunay3dMedium= 11
        Delaunay3dAccurate= 12
        NearestNeighbor3d= 13
        RenkaShepard3d= 14
        InverseDistanceWeighting3d= 15
        NearestNeighborNd= 16
        RenkaShepardNd= 17
        InverseDistanceWeightingNd= 18
        ApproxNearestNeighbor2d= 19
        ApproxNearestNeighbor3d= 20
        ApproxNearestNeighborNd= 21
        Akima1d= 22
        Akima721d= 23
        Cubic1d= 24
        Bilinear2d= 25
        Biakima2d= 26
        Biakima722d= 27
        Bicubic2d= 28
        AkimaLinear2d= 29
        Akima72Linear2d= 30
        CubicLinear2d= 31
        Conservative3d= 32
    

    class DelaunaySliverDetectionMethodEnum(enum.Enum):
        Edgelengthratio= 0
        Aspectratio= 1
    

class FieldDomainCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Fields.FieldDomain]: ...
    @typing.overload
    def __init__(self, owner: Fields.FieldManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def Tag(self) -> Tag: ...



class FieldDomain(NXObject):
    def __init__(self) -> None: ...


class FieldCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Fields.Field]: ...
    @typing.overload
    def __init__(self, owner: Fields.FieldManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def Tag(self) -> Tag: ...



class Field(DisplayableObject):
    def __init__(self) -> None: ...
    def GetFieldEvaluator(self) -> Fields.FieldEvaluator: ...
    def SetPartContext(self) -> None: ...
    def CreateCopyInPart(self, targetPart: BasePart) -> Fields.Field: ...
    def CreateTableInPart(self, targetPart: BasePart) -> Fields.FieldTable: ...
    def Rename(self, newName: str) -> None: ...
    def SetSpatialMap(self, overrideMap: Fields.SpatialMap) -> None: ...
    def GetSpatialMap(self) -> Fields.SpatialMap: ...
    def Delete(self) -> None: ...
    @typing.overload
    def XYGraph(self, indepVar: Fields.FieldVariable, abscissaMinimum: float, abscissaMaximum: float, abscissaPointCount: int, constantIndepVarArray: typing.List[Fields.FieldVariable], constantIndepVarValueArray: float) -> None: ...
    @typing.overload
    def XYGraph(self, indepVar: Fields.FieldVariable, abscissaMinimum: float, abscissaMaximum: float, abscissaPointCount: int, constantIndepVarArray: typing.List[Fields.FieldVariable], constantIndepVarValueArray: float, viewIndex: int, overlay: bool) -> None: ...
    @typing.overload
    def XYGraph(self, indepVar: Fields.FieldVariable, abscissaMinimum: float, abscissaMaximum: float, abscissaPointCount: int, constantIndepVarArray: typing.List[Fields.FieldVariable], constantIndepVarValueArray: float, windowDevice: int, viewIndex: int, overlay: bool) -> None: ...
    @typing.overload
    def XYGraph(self, indepVar: Fields.FieldVariable, abscissaMinimum: float, abscissaMaximum: float, abscissaPointCount: int, constantIndepVarArray: typing.List[Fields.FieldVariable], constantIndepVarValueArray: float, windowDevice: int, viewIndex: int, overlay: bool, plots: typing.List[CAE.Xyplot.Plot]) -> None: ...
    @typing.overload
    def XYGraph(self, indepVar: Fields.FieldVariable, abscissaMinimum: float, abscissaMaximum: float, abscissaPointCount: int, constantIndepVarArray: typing.List[Fields.FieldVariable], constantIndepVarValueArray: float, windowDevice: int, viewIndex: int, overlay: bool, scaleFactor: float, plots: typing.List[CAE.Xyplot.Plot]) -> None: ...
    def XYGraphPlotData(self, indepVar: Fields.FieldVariable, abscissaMinimum: float, abscissaMaximum: float, abscissaPointCount: int, constantIndepVarArray: typing.List[Fields.FieldVariable], constantIndepVarValueArray: float, windowDevice: int, viewIndex: int, overlay: bool, scaleFactor: float, plotOption: Fields.Field.PlotOption, plots: typing.List[CAE.Xyplot.Plot]) -> None: ...
    def XYGraphArgand(self, indepVar: Fields.FieldVariable, abscissaMinimum: float, abscissaMaximum: float, abscissaPointCount: int, constantIndepVarArray: typing.List[Fields.FieldVariable], constantIndepVarValueArray: float, windowDevice: int, viewIndex: int, plots: typing.List[CAE.Xyplot.Plot]) -> None: ...
    def SetDescription(self, lines: str) -> None: ...
    def GetDescription(self) -> str: ...
    def SetIdLabel(self, idLabel: int) -> None: ...
    def GetIdLabel(self) -> int: ...
    def GetDependentVariables(self) -> typing.List[Fields.FieldVariable]: ...
    def GetIndependentVariables(self) -> typing.List[Fields.FieldVariable]: ...
    def XYGraph3D(self, xAxisIndepVar: Fields.FieldVariable, xAxisBndsMinimum: float, xAxisBndsMaximum: float, xAxisBndsSampleSize: int, zAxisIndepVar: Fields.FieldVariable, zAxisBndsMinimum: float, zAxisBndsMaximum: float, zAxisBndsSampleSize: int, yAxisDepVar: Fields.FieldVariable, constantIndepVarArray: typing.List[Fields.FieldVariable], constantIndepVarValueArray: float, interpolateTableData: bool, windowDevice: int, viewIndex: int, overlay: bool, scaleFactor: float) -> CAE.Xyplot.Plot: ...
    def AddApplicationData(self, appData: Fields.IApplicationData) -> None: ...
    def GetApplicationData(self, applicationName: str) -> Fields.IApplicationData: ...
    def Reload(self) -> None: ...
    def SetLocked(self, locked: bool) -> None: ...
    def GetFolder(self) -> Fields.FieldFolder: ...
    @property
    def IsLocked(self) -> bool: ...
    @IsLocked.setter
    def IsLocked(self, value: bool) -> None: ...
    @property
    def IsUserField(self) -> bool: ...
    @IsUserField.setter
    def IsUserField(self, value: bool) -> None: ...


    class PlotOption(enum.Enum):
        InterpolatedValues= 0
        InterpolatedValuesWithBounds= 1
        RawTableValues= 2
    

class ExternalFileProfileBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def GetNumberOfColumns(self) -> int: ...
    def GetColumnTitle(self, columnNumber: int) -> str: ...
    def GetColumnUnit(self, columnNumber: int) -> Unit: ...
    def SetMeasuresFixed(self, areMeasuresFixed: bool) -> None: ...
    def GetColumnMeasureName(self, columnNumber: int) -> str: ...
    def Validate(self) -> bool: ...
    def GetExternalFileReferenceAdapter(self, referenceObjectId: int) -> ExternalFileReferenceAdapter: ...
    def SetExternalFileReferenceAdapter(self, referenceObjectId: int, adapter: ExternalFileReferenceAdapter) -> None: ...
    def GetExternalFileDefinitionKey(self, adapter: ExternalFileReferenceAdapter) -> str: ...
    def EstablishReference(self, referenceObjectId: int, referenceType: ExternalFileReferenceAdapter.Type, externalFileSpec: str) -> ExternalFileReferenceAdapter: ...
    @property
    def Cyclic(self) -> Fields.ExternalFileProfileBuilder.CyclicType: ...
    @Cyclic.setter
    def Cyclic(self, value: Fields.ExternalFileProfileBuilder.CyclicType) -> None: ...
    @property
    def Dimension(self) -> Fields.ExternalFileProfileBuilder.DimensionChoice: ...
    @Dimension.setter
    def Dimension(self, value: Fields.ExternalFileProfileBuilder.DimensionChoice) -> None: ...
    @property
    def FormatControlOption(self) -> Fields.ExternalFileProfileBuilder.FormatOptions: ...
    @FormatControlOption.setter
    def FormatControlOption(self, value: Fields.ExternalFileProfileBuilder.FormatOptions) -> None: ...
    @property
    def OrdinateColumn(self) -> int: ...
    @OrdinateColumn.setter
    def OrdinateColumn(self, value: int) -> None: ...
    @property
    def OrdinateOffset(self) -> Expression: ...
    @OrdinateOffset.setter
    def OrdinateOffset(self, value: Expression) -> None: ...
    @property
    def OrdinateScale(self) -> Expression: ...
    @OrdinateScale.setter
    def OrdinateScale(self, value: Expression) -> None: ...
    @property
    def SlopeLeft(self) -> Expression: ...
    @SlopeLeft.setter
    def SlopeLeft(self, value: Expression) -> None: ...
    @property
    def SlopeRight(self) -> Expression: ...
    @SlopeRight.setter
    def SlopeRight(self, value: Expression) -> None: ...
    @property
    def SolverOptions(self) -> Fields.ProfileSolverOptionsBuilder: ...
    @SolverOptions.setter
    def SolverOptions(self, value: Fields.ProfileSolverOptionsBuilder) -> None: ...
    @property
    def XColumn(self) -> int: ...
    @XColumn.setter
    def XColumn(self, value: int) -> None: ...
    @property
    def XExtrapolation(self) -> Fields.ExternalFileProfileBuilder.Extrapolation: ...
    @XExtrapolation.setter
    def XExtrapolation(self, value: Fields.ExternalFileProfileBuilder.Extrapolation) -> None: ...
    @property
    def XInterpolation(self) -> Fields.ExternalFileProfileBuilder.Interpolation: ...
    @XInterpolation.setter
    def XInterpolation(self, value: Fields.ExternalFileProfileBuilder.Interpolation) -> None: ...
    @property
    def XOffset(self) -> Expression: ...
    @XOffset.setter
    def XOffset(self, value: Expression) -> None: ...
    @property
    def XScale(self) -> Expression: ...
    @XScale.setter
    def XScale(self, value: Expression) -> None: ...
    @property
    def YColumn(self) -> int: ...
    @YColumn.setter
    def YColumn(self, value: int) -> None: ...
    @property
    def YExtrapolation(self) -> Fields.ExternalFileProfileBuilder.Extrapolation: ...
    @YExtrapolation.setter
    def YExtrapolation(self, value: Fields.ExternalFileProfileBuilder.Extrapolation) -> None: ...
    @property
    def YInterpolation(self) -> Fields.ExternalFileProfileBuilder.Interpolation: ...
    @YInterpolation.setter
    def YInterpolation(self, value: Fields.ExternalFileProfileBuilder.Interpolation) -> None: ...
    @property
    def YOffset(self) -> Expression: ...
    @YOffset.setter
    def YOffset(self, value: Expression) -> None: ...
    @property
    def YScale(self) -> Expression: ...
    @YScale.setter
    def YScale(self, value: Expression) -> None: ...


    class Interpolation(enum.Enum):
        Linear= 0
        Akima= 1
        Akima72= 2
        Cubic= 3
    

    class FormatOptions(enum.Enum):
        ComputerRegionalSettings= 0
        DotDecimalSeparator= 1
        CommaDecimalSeparator= 2
        DotDecimalSeparatorAndCommaValueDelimiter= 3
        CommaDecimalSeparatorAndSemicolonValueDelimiter= 4
    

    class Extrapolation(enum.Enum):
        Linear= 0
        Parabolic= 1
        Cubic= 2
    

    class DimensionChoice(enum.Enum):
        Curve= 0
        Surface= 1
        Any= 2
    

    class CyclicType(enum.Enum):
        None_= 0
        XOnly= 1
        YOnly= 2
        Both= 3
    

class ExportData(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def AddField(self, field: Fields.Field) -> None: ...
    def SetFileName(self, fileName: str) -> None: ...
    def AddFields(self, fields: typing.List[Fields.Field]) -> None: ...
    def GetFields(self, fields: typing.List[Fields.Field]) -> None: ...
    def GetFileName(self) -> str: ...
    def FreeResource(self) -> None: ...


class DisplayPropertiesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AxisColor(self) -> NXColor: ...
    @AxisColor.setter
    def AxisColor(self, value: NXColor) -> None: ...
    @property
    def BasicColor(self) -> NXColor: ...
    @BasicColor.setter
    def BasicColor(self, value: NXColor) -> None: ...
    @property
    def DepCalcSymblSize(self) -> float: ...
    @DepCalcSymblSize.setter
    def DepCalcSymblSize(self, value: float) -> None: ...
    @property
    def DepDispType(self) -> Fields.DisplayPropertiesBuilder.DepDispTypeEnum: ...
    @DepDispType.setter
    def DepDispType(self, value: Fields.DisplayPropertiesBuilder.DepDispTypeEnum) -> None: ...
    @property
    def DepDomColor(self) -> Fields.DisplayPropertiesBuilder.DepDomColorEnum: ...
    @DepDomColor.setter
    def DepDomColor(self, value: Fields.DisplayPropertiesBuilder.DepDomColorEnum) -> None: ...
    @property
    def DepLabelValues(self) -> Fields.DisplayPropertiesBuilder.DepLabelValueEnum: ...
    @DepLabelValues.setter
    def DepLabelValues(self, value: Fields.DisplayPropertiesBuilder.DepLabelValueEnum) -> None: ...
    @property
    def DepRangeMax(self) -> float: ...
    @DepRangeMax.setter
    def DepRangeMax(self, value: float) -> None: ...
    @property
    def DepRangeMin(self) -> float: ...
    @DepRangeMin.setter
    def DepRangeMin(self, value: float) -> None: ...
    @property
    def DepSelColor(self) -> NXColor: ...
    @DepSelColor.setter
    def DepSelColor(self, value: NXColor) -> None: ...
    @property
    def DepSymbolSize(self) -> float: ...
    @DepSymbolSize.setter
    def DepSymbolSize(self, value: float) -> None: ...
    @property
    def DisplayResolution(self) -> Fields.DisplayPropertiesBuilder.DispResolutionEnum: ...
    @DisplayResolution.setter
    def DisplayResolution(self, value: Fields.DisplayPropertiesBuilder.DispResolutionEnum) -> None: ...
    @property
    def DummyScale(self) -> float: ...
    @DummyScale.setter
    def DummyScale(self, value: float) -> None: ...
    @property
    def FaceAnalysis(self) -> bool: ...
    @FaceAnalysis.setter
    def FaceAnalysis(self, value: bool) -> None: ...
    @property
    def FieldQuantity(self) -> Fields.DisplayPropertiesBuilder.FieldQuantityType: ...
    @FieldQuantity.setter
    def FieldQuantity(self, value: Fields.DisplayPropertiesBuilder.FieldQuantityType) -> None: ...
    @property
    def HeteroTblDispOption(self) -> Fields.DisplayPropertiesBuilder.HeteroTblDispOptionEnum: ...
    @HeteroTblDispOption.setter
    def HeteroTblDispOption(self, value: Fields.DisplayPropertiesBuilder.HeteroTblDispOptionEnum) -> None: ...
    @property
    def IndepDispType(self) -> Fields.DisplayPropertiesBuilder.IndepDomDispType: ...
    @IndepDispType.setter
    def IndepDispType(self, value: Fields.DisplayPropertiesBuilder.IndepDomDispType) -> None: ...
    @property
    def LabelColor(self) -> NXColor: ...
    @LabelColor.setter
    def LabelColor(self, value: NXColor) -> None: ...
    @property
    def Layer(self) -> int: ...
    @Layer.setter
    def Layer(self, value: int) -> None: ...
    @property
    def LegendPosition(self) -> Fields.DisplayPropertiesBuilder.LegendPos: ...
    @LegendPosition.setter
    def LegendPosition(self, value: Fields.DisplayPropertiesBuilder.LegendPos) -> None: ...
    @property
    def LineFont(self) -> Fields.DisplayPropertiesBuilder.LineFontEnum: ...
    @LineFont.setter
    def LineFont(self, value: Fields.DisplayPropertiesBuilder.LineFontEnum) -> None: ...
    @property
    def LineWidth(self) -> Fields.DisplayPropertiesBuilder.LineWidthEnum: ...
    @LineWidth.setter
    def LineWidth(self, value: Fields.DisplayPropertiesBuilder.LineWidthEnum) -> None: ...
    @property
    def OverflowColor(self) -> NXColor: ...
    @OverflowColor.setter
    def OverflowColor(self, value: NXColor) -> None: ...
    @property
    def PartiallyShaded(self) -> bool: ...
    @PartiallyShaded.setter
    def PartiallyShaded(self, value: bool) -> None: ...
    @property
    def PrimaryVar(self) -> Expression: ...
    @PrimaryVar.setter
    def PrimaryVar(self, value: Expression) -> None: ...
    @property
    def Range(self) -> Fields.DisplayPropertiesBuilder.ValueRange: ...
    @Range.setter
    def Range(self, value: Fields.DisplayPropertiesBuilder.ValueRange) -> None: ...
    @property
    def RangeMax(self) -> float: ...
    @RangeMax.setter
    def RangeMax(self, value: float) -> None: ...
    @property
    def RangeMin(self) -> float: ...
    @RangeMin.setter
    def RangeMin(self, value: float) -> None: ...
    @property
    def ShowAxis(self) -> bool: ...
    @ShowAxis.setter
    def ShowAxis(self, value: bool) -> None: ...
    @property
    def ShowDefaultVal(self) -> bool: ...
    @ShowDefaultVal.setter
    def ShowDefaultVal(self, value: bool) -> None: ...
    @property
    def ShowDescription(self) -> bool: ...
    @ShowDescription.setter
    def ShowDescription(self, value: bool) -> None: ...
    @property
    def ShowLabels(self) -> bool: ...
    @ShowLabels.setter
    def ShowLabels(self, value: bool) -> None: ...
    @property
    def ShowMapTopo(self) -> bool: ...
    @ShowMapTopo.setter
    def ShowMapTopo(self, value: bool) -> None: ...
    @property
    def ShowName(self) -> bool: ...
    @ShowName.setter
    def ShowName(self, value: bool) -> None: ...
    @property
    def ShowOverflowValues(self) -> bool: ...
    @ShowOverflowValues.setter
    def ShowOverflowValues(self, value: bool) -> None: ...
    @property
    def ShowSrcTblVals(self) -> bool: ...
    @ShowSrcTblVals.setter
    def ShowSrcTblVals(self, value: bool) -> None: ...
    @property
    def ShowUndefValues(self) -> bool: ...
    @ShowUndefValues.setter
    def ShowUndefValues(self, value: bool) -> None: ...
    @property
    def ShowUnderflowValues(self) -> bool: ...
    @ShowUnderflowValues.setter
    def ShowUnderflowValues(self, value: bool) -> None: ...
    @property
    def SpectrumLevels(self) -> int: ...
    @SpectrumLevels.setter
    def SpectrumLevels(self, value: int) -> None: ...
    @property
    def SurfaceOffset(self) -> float: ...
    @SurfaceOffset.setter
    def SurfaceOffset(self, value: float) -> None: ...
    @property
    def TblDepColor(self) -> NXColor: ...
    @TblDepColor.setter
    def TblDepColor(self, value: NXColor) -> None: ...
    @property
    def TblDepDispType(self) -> Fields.DisplayPropertiesBuilder.DepDispTypeEnum: ...
    @TblDepDispType.setter
    def TblDepDispType(self, value: Fields.DisplayPropertiesBuilder.DepDispTypeEnum) -> None: ...
    @property
    def TblDepDomColor(self) -> Fields.DisplayPropertiesBuilder.DepDomColorEnum: ...
    @TblDepDomColor.setter
    def TblDepDomColor(self, value: Fields.DisplayPropertiesBuilder.DepDomColorEnum) -> None: ...
    @property
    def TblDepLabelValues(self) -> Fields.DisplayPropertiesBuilder.DepLabelValueEnum: ...
    @TblDepLabelValues.setter
    def TblDepLabelValues(self, value: Fields.DisplayPropertiesBuilder.DepLabelValueEnum) -> None: ...
    @property
    def TblDepPtType(self) -> Fields.DisplayPropertiesBuilder.TblPointTypeEnum: ...
    @TblDepPtType.setter
    def TblDepPtType(self, value: Fields.DisplayPropertiesBuilder.TblPointTypeEnum) -> None: ...
    @property
    def TblDepSymbolSize(self) -> float: ...
    @TblDepSymbolSize.setter
    def TblDepSymbolSize(self, value: float) -> None: ...
    @property
    def TblHetPrimaryValue(self) -> float: ...
    @TblHetPrimaryValue.setter
    def TblHetPrimaryValue(self, value: float) -> None: ...
    @property
    def TblIndepColor(self) -> NXColor: ...
    @TblIndepColor.setter
    def TblIndepColor(self, value: NXColor) -> None: ...
    @property
    def TblIndepPtType(self) -> Fields.DisplayPropertiesBuilder.ValuesEnum: ...
    @TblIndepPtType.setter
    def TblIndepPtType(self, value: Fields.DisplayPropertiesBuilder.ValuesEnum) -> None: ...
    @property
    def TblSurfaceOffset(self) -> float: ...
    @TblSurfaceOffset.setter
    def TblSurfaceOffset(self, value: float) -> None: ...
    @property
    def Translucency(self) -> int: ...
    @Translucency.setter
    def Translucency(self, value: int) -> None: ...
    @property
    def UndefValueColor(self) -> NXColor: ...
    @UndefValueColor.setter
    def UndefValueColor(self, value: NXColor) -> None: ...
    @property
    def UnderflowColor(self) -> NXColor: ...
    @UnderflowColor.setter
    def UnderflowColor(self, value: NXColor) -> None: ...
    @property
    def XMax(self) -> Expression: ...
    @XMax.setter
    def XMax(self, value: Expression) -> None: ...
    @property
    def XMin(self) -> Expression: ...
    @XMin.setter
    def XMin(self, value: Expression) -> None: ...
    @property
    def XNum(self) -> int: ...
    @XNum.setter
    def XNum(self, value: int) -> None: ...
    @property
    def YMax(self) -> Expression: ...
    @YMax.setter
    def YMax(self, value: Expression) -> None: ...
    @property
    def YMin(self) -> Expression: ...
    @YMin.setter
    def YMin(self, value: Expression) -> None: ...
    @property
    def YNum(self) -> int: ...
    @YNum.setter
    def YNum(self, value: int) -> None: ...
    @property
    def ZMax(self) -> Expression: ...
    @ZMax.setter
    def ZMax(self, value: Expression) -> None: ...
    @property
    def ZMin(self) -> Expression: ...
    @ZMin.setter
    def ZMin(self, value: Expression) -> None: ...
    @property
    def ZNum(self) -> int: ...
    @ZNum.setter
    def ZNum(self, value: int) -> None: ...


    class VectorType(enum.Enum):
        X= 0
        Y= 1
        Z= 2
        Mag= 3
    

    class ValuesEnum(enum.Enum):
        Hide= 0
        Point= 1
        PlusSign= 2
        Asterisk= 3
        Circle= 4
        PoundSign= 5
        Cross= 6
        Square= 7
        Triangle= 8
        Diamond= 9
        Centerline= 10
    

    class ValueRange(enum.Enum):
        Auto= 0
        Specified= 1
    

    class TensorType(enum.Enum):
        Xx= 0
        Yy= 1
        Zz= 2
        Xy= 3
        Yz= 4
        Zx= 5
        Mean= 6
        MidPrncpl= 7
        MinPrncpl= 8
        MaxPrncpl= 9
        Octahedral= 10
        VonMises= 11
    

    class TblPointTypeEnum(enum.Enum):
        Hide= 0
        Show= 1
    

    class ScalarType(enum.Enum):
        Hide= 0
        Mag= 1
    

    class LineWidthEnum(enum.Enum):
        Normal= 0
        Thick= 1
        Thin= 2
        One= 5
        Two= 6
        Three= 7
        Four= 8
        Five= 9
        Six= 10
        Seven= 11
        Eight= 12
        Nine= 13
    

    class LineFontEnum(enum.Enum):
        Solid= 0
        Dashed= 1
        Phantom= 2
        Centerline= 3
        Dotted= 4
        LongDashed= 5
        DottedDashed= 6
        Eight= 7
        Nine= 8
        Ten= 9
        Eleven= 10
    

    class LegendPos(enum.Enum):
        Hide= 0
        Left= 1
        Right= 2
    

    class Legacy3DType(enum.Enum):
        X= 0
        Y= 1
        Z= 2
    

    class IndepDomDispType(enum.Enum):
        Normal= 0
        Point= 1
        PlusSign= 2
        Asterisk= 3
        Circle= 4
        PoundSign= 5
        Cross= 6
        Square= 7
        Triangle= 8
        Diamond= 9
        Centerline= 10
        Hide= 11
    

    class HeteroTblDispOptionEnum(enum.Enum):
        ShowAverageValue= 0
        PrimaryVarValues= 1
        Show1StValue= 2
        ShowLastValue= 3
        ShowMinimumValue= 4
        ShowMaximumValue= 5
        Hide= 6
    

    class FieldQuantityType(enum.Enum):
        Type0= 0
        Type1= 1
        Type2= 2
        Type3= 3
        Type4= 4
        Type5= 5
        Type6= 6
        Type7= 7
        Type8= 8
        Type9= 9
        Type10= 10
        Type11= 11
        Type12= 12
        Type13= 13
        Type14= 14
        Type15= 15
    

    class DispResolutionEnum(enum.Enum):
        Coarse= 0
        Standard= 1
        Fine= 2
        ExtraFine= 3
        SuperFine= 4
        UltraFine= 5
        UserSpecified= 6
    

    class DepLabelValueEnum(enum.Enum):
        None_= 0
        MinimumMaximum= 1
        Maximum= 2
        Minimum= 3
        All= 4
    

    class DepDomColorEnum(enum.Enum):
        Inherit= 0
        Specified= 1
        Spectrum= 2
    

    class DepDispTypeEnum(enum.Enum):
        Symbol= 0
        Surface= 1
        SurfaceEdges= 2
        Hide= 3
    

    class ComplexVectorType(enum.Enum):
        XReal= 0
        YReal= 1
        ZReal= 2
        XImaginary= 3
        YImaginary= 4
        ZImaginary= 5
    

    class ComplexScalarType(enum.Enum):
        Mag= 0
        Real= 1
        Imaginary= 2
        Phase= 3
    

    class BalStrainType(enum.Enum):
        Xx= 0
        Yy= 1
        Zz= 2
        Xy= 3
        Yz= 4
        Zx= 5
        OffSetXX= 6
        OffSetYY= 7
        OffSetZZ= 8
        OffSetXY= 9
        OffSetYZ= 10
        OffSetZX= 11
    

class ComplexVectorFieldWrapper(NXObject):
    def __init__(self) -> None: ...
    def GetExpressionByIndex(self, index: int) -> Expression: ...
    def SetExpressions(self, expressions: typing.List[Expression]) -> None: ...
    def SetImaginaryExpressions(self, expressions: typing.List[Expression]) -> None: ...
    def GetImaginaryExpressionByIndex(self, index: int) -> Expression: ...
    def SetField(self, field: Fields.Field, scaleFactor: float) -> None: ...
    def GetField(self) -> Fields.Field: ...


class ComplexScalarFieldWrapper(NXObject):
    def __init__(self) -> None: ...
    def SetExpression(self, expression: Expression) -> None: ...
    def GetExpression(self) -> Expression: ...
    def SetImaginaryExpression(self, expression: Expression) -> None: ...
    def GetImaginaryExpression(self) -> Expression: ...
    def GetField(self) -> Fields.Field: ...
    def SetField(self, field: Fields.Field) -> None: ...
    def SetFieldWithScaleFactor(self, field: Fields.Field, scaleFactor: float) -> None: ...


