from ...NXOpen import *

import typing
import enum

class NetworkUtilizationSettingsBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def DisplayStyle(self) -> CableRouter.NetworkUtilizationSettingsBuilder.DisplayMethod: ...
    @DisplayStyle.setter
    def DisplayStyle(self, value: CableRouter.NetworkUtilizationSettingsBuilder.DisplayMethod) -> None: ...
    @property
    def ExceedingFillColor(self) -> NXColor: ...
    @ExceedingFillColor.setter
    def ExceedingFillColor(self, value: NXColor) -> None: ...
    @property
    def Range1Color(self) -> NXColor: ...
    @Range1Color.setter
    def Range1Color(self, value: NXColor) -> None: ...
    @property
    def Range1Number(self) -> float: ...
    @Range1Number.setter
    def Range1Number(self, value: float) -> None: ...
    @property
    def Range2Color(self) -> NXColor: ...
    @Range2Color.setter
    def Range2Color(self, value: NXColor) -> None: ...
    @property
    def Range2Number(self) -> float: ...
    @Range2Number.setter
    def Range2Number(self, value: float) -> None: ...
    @property
    def Range3Color(self) -> NXColor: ...
    @Range3Color.setter
    def Range3Color(self, value: NXColor) -> None: ...
    @property
    def SelectedColorCount(self) -> CableRouter.NetworkUtilizationSettingsBuilder.AmountOfColors: ...
    @SelectedColorCount.setter
    def SelectedColorCount(self, value: CableRouter.NetworkUtilizationSettingsBuilder.AmountOfColors) -> None: ...
    @property
    def SpecifiedFillAmount(self) -> float: ...
    @SpecifiedFillAmount.setter
    def SpecifiedFillAmount(self, value: float) -> None: ...
    @property
    def SpecifiedFillColor(self) -> NXColor: ...
    @SpecifiedFillColor.setter
    def SpecifiedFillColor(self, value: NXColor) -> None: ...


    class DisplayMethod(enum.Enum):
        ExceedingRange= 0
        ExceedingDefinedRange= 1
        RangeAreas= 2
    

    class AmountOfColors(enum.Enum):
        Two= 0
        Three= 1
    

class CableSettingsBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AvailableColor(self) -> NXColor: ...
    @AvailableColor.setter
    def AvailableColor(self, value: NXColor) -> None: ...
    @property
    def BasicDisplayProperties(self) -> LineColorFontWidthBuilder: ...
    @BasicDisplayProperties.setter
    def BasicDisplayProperties(self, value: LineColorFontWidthBuilder) -> None: ...
    @property
    def CableSelectionColor(self) -> NXColor: ...
    @CableSelectionColor.setter
    def CableSelectionColor(self, value: NXColor) -> None: ...
    @property
    def EndDeviceColor(self) -> NXColor: ...
    @EndDeviceColor.setter
    def EndDeviceColor(self, value: NXColor) -> None: ...
    @property
    def FitOnSelection(self) -> bool: ...
    @FitOnSelection.setter
    def FitOnSelection(self, value: bool) -> None: ...
    @property
    def LabelFontSize(self) -> float: ...
    @LabelFontSize.setter
    def LabelFontSize(self, value: float) -> None: ...
    @property
    def LabelTextProperties(self) -> TextColorFontWidthBuilder: ...
    @LabelTextProperties.setter
    def LabelTextProperties(self, value: TextColorFontWidthBuilder) -> None: ...
    @property
    def LayerNumber(self) -> int: ...
    @LayerNumber.setter
    def LayerNumber(self, value: int) -> None: ...
    @property
    def ShowDeviceLabels(self) -> bool: ...
    @ShowDeviceLabels.setter
    def ShowDeviceLabels(self, value: bool) -> None: ...
    @property
    def ShowDevices(self) -> bool: ...
    @ShowDevices.setter
    def ShowDevices(self, value: bool) -> None: ...
    @property
    def ShowNodeLabels(self) -> bool: ...
    @ShowNodeLabels.setter
    def ShowNodeLabels(self, value: bool) -> None: ...
    @property
    def ShowNodes(self) -> bool: ...
    @ShowNodes.setter
    def ShowNodes(self, value: bool) -> None: ...
    @property
    def ShowSegmentLabels(self) -> bool: ...
    @ShowSegmentLabels.setter
    def ShowSegmentLabels(self, value: bool) -> None: ...
    @property
    def ShowSegments(self) -> bool: ...
    @ShowSegments.setter
    def ShowSegments(self, value: bool) -> None: ...
    @property
    def StartDeviceColor(self) -> NXColor: ...
    @StartDeviceColor.setter
    def StartDeviceColor(self, value: NXColor) -> None: ...
    @property
    def VirtualDisplayProperties(self) -> LineColorFontWidthBuilder: ...
    @VirtualDisplayProperties.setter
    def VirtualDisplayProperties(self, value: LineColorFontWidthBuilder) -> None: ...


class CableRouterManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetCableRouterManager(self, owner: Session) -> CableRouter.CableRouterManager: ...
    def Tag(self) -> Tag: ...

    @property
    def CableRouterCollection(self) -> CableRouter.CableRouterCollection: ...
    @CableRouterCollection.setter
    def CableRouterCollection(self, value: CableRouter.CableRouterCollection) -> None: ...


class CableRouterCollection(Utilities.NXRemotableObject):
    def __init__(self, owner: CableRouter.CableRouterManager) -> None: ...
    def CreateCableSettingsBuilder(self, part: Part) -> CableRouter.CableSettingsBuilder: ...
    def CreateNetworkUtilizationSettingsBuilder(self, part: Part) -> CableRouter.NetworkUtilizationSettingsBuilder: ...
    def Tag(self) -> Tag: ...



