from ...NXOpen import *

import typing
import enum

class TransformBlockBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def ActiveTransformType(self) -> RoutingCommon.TransformBlockBuilder.Transformtype: ...
    @ActiveTransformType.setter
    def ActiveTransformType(self, value: RoutingCommon.TransformBlockBuilder.Transformtype) -> None: ...
    @property
    def ConstrainedPoint(self) -> Point: ...
    @ConstrainedPoint.setter
    def ConstrainedPoint(self, value: Point) -> None: ...
    @property
    def InitialOrientation(self) -> Matrix3x3: ...
    @InitialOrientation.setter
    def InitialOrientation(self, value: Matrix3x3) -> None: ...
    @property
    def InitialPosition(self) -> Point3d: ...
    @InitialPosition.setter
    def InitialPosition(self, value: Point3d) -> None: ...
    @property
    def OrientExpress(self) -> GeometricUtilities.OrientXpressBuilder: ...
    @OrientExpress.setter
    def OrientExpress(self, value: GeometricUtilities.OrientXpressBuilder) -> None: ...
    @property
    def Plane(self) -> Plane: ...
    @Plane.setter
    def Plane(self, value: Plane) -> None: ...
    @property
    def TempOrientation(self) -> Matrix3x3: ...
    @TempOrientation.setter
    def TempOrientation(self, value: Matrix3x3) -> None: ...
    @property
    def TempPosition(self) -> Point3d: ...
    @TempPosition.setter
    def TempPosition(self, value: Point3d) -> None: ...
    @property
    def Vector(self) -> Direction: ...
    @Vector.setter
    def Vector(self, value: Direction) -> None: ...


    class Transformtype(enum.Enum):
        None_= -1
        OrientXpress= 0
        Vector= 1
        View= 2
        Manipulator= 3
        Plane= 4
    

class SubdivideCurveBuilder(Builder):
    def __init__(self) -> None: ...
    def GetSubdividedCurves(self) -> typing.List[Curve]: ...
    @property
    def ArcLength(self) -> GeometricUtilities.OnPathDimensionBuilder: ...
    @ArcLength.setter
    def ArcLength(self, value: GeometricUtilities.OnPathDimensionBuilder) -> None: ...
    @property
    def CreateTangencySetting(self) -> bool: ...
    @CreateTangencySetting.setter
    def CreateTangencySetting(self, value: bool) -> None: ...
    @property
    def EndPercentage(self) -> GeometricUtilities.OnPathDimensionBuilder: ...
    @EndPercentage.setter
    def EndPercentage(self, value: GeometricUtilities.OnPathDimensionBuilder) -> None: ...
    @property
    def NumberOfSegments(self) -> int: ...
    @NumberOfSegments.setter
    def NumberOfSegments(self, value: int) -> None: ...
    @property
    def ReverseDirection(self) -> bool: ...
    @ReverseDirection.setter
    def ReverseDirection(self, value: bool) -> None: ...
    @property
    def SelectedSegment(self) -> Routing.RouteObjectCollector: ...
    @SelectedSegment.setter
    def SelectedSegment(self, value: Routing.RouteObjectCollector) -> None: ...
    @property
    def StartPercentage(self) -> GeometricUtilities.OnPathDimensionBuilder: ...
    @StartPercentage.setter
    def StartPercentage(self, value: GeometricUtilities.OnPathDimensionBuilder) -> None: ...
    @property
    def SubdivideAtPoint(self) -> GeometricUtilities.OnPathDimensionBuilder: ...
    @SubdivideAtPoint.setter
    def SubdivideAtPoint(self, value: GeometricUtilities.OnPathDimensionBuilder) -> None: ...
    @property
    def Type(self) -> RoutingCommon.SubdivideCurveBuilder.Types: ...
    @Type.setter
    def Type(self, value: RoutingCommon.SubdivideCurveBuilder.Types) -> None: ...


    class Types(enum.Enum):
        AtPoint= 0
        EqualSegments= 1
        ArcLengthSegments= 2
    

class StockBuilder(Builder):
    def __init__(self) -> None: ...
    def PreCommit(self) -> None: ...
    def GetLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    @property
    def IsNonCircular(self) -> bool: ...
    @IsNonCircular.setter
    def IsNonCircular(self, value: bool) -> None: ...
    @property
    def SegmentCollector(self) -> Routing.RouteObjectCollector: ...
    @SegmentCollector.setter
    def SegmentCollector(self, value: Routing.RouteObjectCollector) -> None: ...
    @property
    def StockSettings(self) -> Routing.StockBlockBuilder: ...
    @StockSettings.setter
    def StockSettings(self, value: Routing.StockBlockBuilder) -> None: ...


class SplitBuilder(Builder):
    def __init__(self) -> None: ...
    def GetCreatedComponents(self) -> typing.List[Assemblies.Component]: ...
    def PreCommit(self) -> None: ...
    def GetLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    @property
    def ControlPointCollector(self) -> Routing.RouteObjectCollector: ...
    @ControlPointCollector.setter
    def ControlPointCollector(self, value: Routing.RouteObjectCollector) -> None: ...


class SplinePointBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[RoutingCommon.SplinePointBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: RoutingCommon.SplinePointBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: RoutingCommon.SplinePointBuilder) -> int: ...
    def FindItem(self, index: int) -> RoutingCommon.SplinePointBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: RoutingCommon.SplinePointBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: RoutingCommon.SplinePointBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[RoutingCommon.SplinePointBuilder]: ...
    def SetContents(self, objects: typing.List[RoutingCommon.SplinePointBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: RoutingCommon.SplinePointBuilder, object2: RoutingCommon.SplinePointBuilder) -> None: ...
    def Insert(self, location: int, object: RoutingCommon.SplinePointBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class SplinePointBuilder(Builder):
    def __init__(self) -> None: ...
    def GetPoint(self) -> Point: ...
    def SetPoint(self, point: Point) -> int: ...
    def MovePoint(self, location: Point3d) -> None: ...
    def SetOffsetOption(self, offsetOption: RoutingCommon.SplinePointBuilder.OffsetOption) -> None: ...
    def GetOffsetOption(self) -> RoutingCommon.SplinePointBuilder.OffsetOption: ...
    def GetOffsetDirection(self) -> Direction: ...
    def SetOffsetDirection(self, dirr: Direction) -> None: ...
    def GetOffsetExpressionString(self) -> str: ...
    def SetOffsetExpressionString(self, offsetExpressionString: str) -> None: ...
    def DetachPoint(self) -> None: ...
    def InferExtension(self, spline: Curve, point: Point, direction: Direction, tangent: Vector3d, normal: Vector3d) -> None: ...
    def GetForwardExpression(self) -> Expression: ...
    def GetBackwardExpression(self) -> Expression: ...
    def ReverseDirection(self, direction: Direction) -> None: ...
    def SwapExtensions(self) -> None: ...
    def MoveDirection(self, direction: Direction) -> None: ...
    def AssignNewDirection(self, direction: Direction) -> None: ...
    def GetControlPoint(self) -> Routing.ControlPoint: ...
    def AskTangencyInformation(self, controlPoint: Routing.ControlPoint, targetCurve: Curve, origin: Point3d, vector: Vector3d) -> None: ...
    def AskTangencyGeometry(self, targetCurve: Curve, origin: Point3d, vector: Vector3d) -> None: ...
    @property
    def Direction(self) -> Direction: ...
    @Direction.setter
    def Direction(self, value: Direction) -> None: ...
    @property
    def LockToSelected(self) -> bool: ...
    @LockToSelected.setter
    def LockToSelected(self, value: bool) -> None: ...
    @property
    def Tangency(self) -> bool: ...
    @Tangency.setter
    def Tangency(self, value: bool) -> None: ...


    class OffsetOption(enum.Enum):
        None_= 0
        Point= 1
        Surface= 2
        Port= 3
    

class SplineBuilder(Builder):
    def __init__(self) -> None: ...
    def RemoveDefiningPoint(self, index: int) -> None: ...
    def GetLockedLengthExpression(self) -> Expression: ...
    def GetWorkPart(self) -> Part: ...
    def LockSplineLengthNoShaping(self, length: Expression) -> None: ...
    def RemoveAllShaping(self) -> None: ...
    def AddSlackToSpline(self, lengthType: RoutingCommon.SplineBuilder.LengthType, lengthValue: Expression, slackDirection: Direction) -> None: ...
    def AssignExtensionAtPointIndex(self, pointIndex: int, location: Point3d, direction: Vector3d, forward: float, backward: float) -> None: ...
    def AssignExtension(self, controlPoint: Routing.ControlPoint, targetCurve: Curve, location: Point3d, direction: Vector3d, distance: float) -> None: ...
    def AssignTangency(self, thisControlPoint: Routing.ControlPoint, thisCurve: Curve, targetControlPoint: Routing.ControlPoint, targetCurve: Curve) -> None: ...
    def LockSplineLengthWithShapingFixedPoints(self, length: Expression, slackDirection: Direction) -> None: ...
    def LockSplineLengthWithShaping(self, length: Expression, slackDirection: Direction) -> None: ...
    def ShapeByAdditionalLengthMovingPoints(self, length: Expression, lengthType: RoutingCommon.SplineBuilder.LengthType) -> None: ...
    def RemoveTangency(self, point: RoutingCommon.SplinePointBuilder) -> None: ...
    def CanAssignTangency(self, point: RoutingCommon.SplinePointBuilder) -> bool: ...
    def IsCurvatureControlled(self) -> bool: ...
    def EnableCurvatureControl(self, minRadiusExp: Expression) -> None: ...
    def DisableCurvatureControl(self) -> None: ...
    def GetBoundedCurvatureRadius(self) -> Expression: ...
    def HasCurvatureControlFailed(self) -> bool: ...
    @property
    def MinimumCheckingAllowableRatio(self) -> Expression: ...
    @MinimumCheckingAllowableRatio.setter
    def MinimumCheckingAllowableRatio(self, value: Expression) -> None: ...
    @property
    def MinimumCheckingAllowableValue(self) -> Expression: ...
    @MinimumCheckingAllowableValue.setter
    def MinimumCheckingAllowableValue(self, value: Expression) -> None: ...
    @property
    def MinimumCheckingMethod(self) -> RoutingCommon.SplineBuilder.SplineAttributeOptions: ...
    @MinimumCheckingMethod.setter
    def MinimumCheckingMethod(self, value: RoutingCommon.SplineBuilder.SplineAttributeOptions) -> None: ...
    @property
    def PointList(self) -> RoutingCommon.SplinePointBuilderList: ...
    @PointList.setter
    def PointList(self, value: RoutingCommon.SplinePointBuilderList) -> None: ...
    @property
    def RemoveExtensionUponDetach(self) -> bool: ...
    @RemoveExtensionUponDetach.setter
    def RemoveExtensionUponDetach(self, value: bool) -> None: ...
    @property
    def ShowSplineMinimumRadius(self) -> bool: ...
    @ShowSplineMinimumRadius.setter
    def ShowSplineMinimumRadius(self, value: bool) -> None: ...
    @property
    def SplineCurve(self) -> Curve: ...
    @SplineCurve.setter
    def SplineCurve(self, value: Curve) -> None: ...
    @property
    def StockSettings(self) -> Routing.StockBlockBuilder: ...
    @StockSettings.setter
    def StockSettings(self, value: Routing.StockBlockBuilder) -> None: ...
    @property
    def UseMinimumCheckingValue(self) -> bool: ...
    @UseMinimumCheckingValue.setter
    def UseMinimumCheckingValue(self, value: bool) -> None: ...


    class SplineAttributeOptions(enum.Enum):
        Radius= 0
        RatioToDiameter= 1
    

    class LengthType(enum.Enum):
        LockLength= 0
        TotalPercentage= 1
        TotalAdditional= 2
        Undefined= 3
    

class SimplifyCurvesBuilder(Builder):
    def __init__(self) -> None: ...
    def GetSimplifiedCurves(self) -> typing.List[Curve]: ...
    @property
    def SegmentCollector(self) -> Routing.RouteObjectCollector: ...
    @SegmentCollector.setter
    def SegmentCollector(self, value: Routing.RouteObjectCollector) -> None: ...


class RoutingManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def GetRoutingManager(self, owner: Session) -> RoutingCommon.RoutingManager: ...
    def IsRouteSystemAssembly(self, part: Part) -> bool: ...
    def IsShapeComponentPart(self, part: BasePart) -> bool: ...
    def IsReusableComponentPart(self, part: BasePart) -> bool: ...
    def MakeComponentReusable(self, component: Assemblies.Component) -> bool: ...
    def PerformDetachOperationOnRcp(self, rcp: Routing.ControlPoint) -> bool: ...
    def PerformDetachOperationOnPort(self, port: Routing.Port) -> bool: ...
    def IsStockComponentPart(self, part: BasePart) -> bool: ...
    def IsInsulationComponentPart(self, part: BasePart) -> bool: ...
    def StoreReuseLibraryDisciplineWithinPart(self, part: Part, discipline: str) -> bool: ...
    def StoreReuseLibrarySpecificationWithinPart(self, part: Part, specification: str) -> bool: ...
    def GetSavedDisciplineAndSpecificationFromThePart(self, part: Part, discipline: str, specification: str) -> None: ...
    def RestoreDisciplineAndSpecificationFromThePart(self, part: Part, disciplineSuccess: bool, specificationSuccess: bool) -> None: ...
    def ConditionAssemblyForTraditionalRouting(self, part: Part) -> bool: ...
    def Tag(self) -> Tag: ...

    @property
    def BuilderFactory(self) -> RoutingCommon.BuilderFactory: ...
    @BuilderFactory.setter
    def BuilderFactory(self, value: RoutingCommon.BuilderFactory) -> None: ...
    @property
    def InsulationService(self) -> RoutingCommon.InsulationService: ...
    @InsulationService.setter
    def InsulationService(self, value: RoutingCommon.InsulationService) -> None: ...


class ReparentPartsBuilder(Builder):
    def __init__(self) -> None: ...
    def PreCommit(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    def ShowStockSummary(self) -> None: ...
    @property
    def ActionType(self) -> RoutingCommon.ReparentPartsBuilder.StockActionType: ...
    @ActionType.setter
    def ActionType(self, value: RoutingCommon.ReparentPartsBuilder.StockActionType) -> None: ...
    @property
    def AllowSelectionOfLiveStock(self) -> bool: ...
    @AllowSelectionOfLiveStock.setter
    def AllowSelectionOfLiveStock(self, value: bool) -> None: ...
    @property
    def SelectedParts(self) -> Routing.RouteObjectCollector: ...
    @SelectedParts.setter
    def SelectedParts(self, value: Routing.RouteObjectCollector) -> None: ...


    class StockActionType(enum.Enum):
        CreateNew= 0
        TransferExisting= 1
    

class PathTransitionListManagerBuilder(Builder):
    def __init__(self) -> None: ...
    def CreatePathTransitionBuilder(self, part: Part) -> RoutingCommon.PathTransitionBuilder: ...
    @property
    def PathTransitionBuilderList(self) -> RoutingCommon.PathTransitionBuilderList: ...
    @PathTransitionBuilderList.setter
    def PathTransitionBuilderList(self, value: RoutingCommon.PathTransitionBuilderList) -> None: ...


class PathTransitionBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[RoutingCommon.PathTransitionBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: RoutingCommon.PathTransitionBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: RoutingCommon.PathTransitionBuilder) -> int: ...
    def FindItem(self, index: int) -> RoutingCommon.PathTransitionBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: RoutingCommon.PathTransitionBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: RoutingCommon.PathTransitionBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[RoutingCommon.PathTransitionBuilder]: ...
    def SetContents(self, objects: typing.List[RoutingCommon.PathTransitionBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: RoutingCommon.PathTransitionBuilder, object2: RoutingCommon.PathTransitionBuilder) -> None: ...
    def Insert(self, location: int, object: RoutingCommon.PathTransitionBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class PathTransitionBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def AddExtensionToggle(self) -> bool: ...
    @AddExtensionToggle.setter
    def AddExtensionToggle(self, value: bool) -> None: ...
    @property
    def BackwardExtension(self) -> Expression: ...
    @BackwardExtension.setter
    def BackwardExtension(self, value: Expression) -> None: ...
    @property
    def BoxOrientation(self) -> RoutingCommon.PathTransitionBuilder.HealOrientation: ...
    @BoxOrientation.setter
    def BoxOrientation(self, value: RoutingCommon.PathTransitionBuilder.HealOrientation) -> None: ...
    @property
    def ConnectedObject(self) -> NXObject: ...
    @ConnectedObject.setter
    def ConnectedObject(self, value: NXObject) -> None: ...
    @property
    def EndPoint(self) -> Point: ...
    @EndPoint.setter
    def EndPoint(self, value: Point) -> None: ...
    @property
    def ExtensionVector(self) -> Direction: ...
    @ExtensionVector.setter
    def ExtensionVector(self, value: Direction) -> None: ...
    @property
    def ForwardExtension(self) -> Expression: ...
    @ForwardExtension.setter
    def ForwardExtension(self, value: Expression) -> None: ...
    @property
    def HealSolutionCsys(self) -> CoordinateSystem: ...
    @HealSolutionCsys.setter
    def HealSolutionCsys(self, value: CoordinateSystem) -> None: ...
    @property
    def HealTraversalOrder(self) -> RoutingCommon.PathTransitionBuilder.TraversalOrder: ...
    @HealTraversalOrder.setter
    def HealTraversalOrder(self, value: RoutingCommon.PathTransitionBuilder.TraversalOrder) -> None: ...
    @property
    def PathForwardThroughExtensionVector(self) -> bool: ...
    @PathForwardThroughExtensionVector.setter
    def PathForwardThroughExtensionVector(self, value: bool) -> None: ...
    @property
    def TransitionType(self) -> RoutingCommon.PathTransitionBuilder.Type: ...
    @TransitionType.setter
    def TransitionType(self, value: RoutingCommon.PathTransitionBuilder.Type) -> None: ...


    class Type(enum.Enum):
        Direct= 0
        Heal= 1
        Intersect= 2
    

    class TraversalOrder(enum.Enum):
        Xyz= 0
        Xzy= 1
        Yzx= 2
        Yxz= 3
        Zxy= 4
        Zyx= 5
        Invalid= 6
    

    class HealOrientation(enum.Enum):
        Wcs= 0
        Absolute= 1
        Start= 2
        End= 3
        NewCsys= 4
    

class PathDimensionBuilder(GeometricUtilities.OnPathDimensionBuilder):
    def __init__(self) -> None: ...
    def UpdateExpression(self) -> None: ...
    def GetOrderedPathCurves(self, pathCurves: typing.List[Curve]) -> None: ...
    def SetOrderedPathCurves(self, pathCurves: typing.List[Curve]) -> None: ...
    def GetValueAsLength(self) -> float: ...


class PartPlacementBuilder(Builder):
    def __init__(self) -> None: ...
    def SetFileSpecificationOfPartToPlace(self, filename: str) -> None: ...
    def SetClassificationObjectIdentifier(self, classificationObjectId: str) -> None: ...
    def SetReferenceObjectForPlacement(self, referenceObject: TaggedObject, referencePositionPoint: Point3d) -> None: ...
    def LoadPart(self) -> BasePart: ...
    def CreatePartOccurrenceToPlace(self, referenceSet: str, layer: int) -> Assemblies.Component: ...
    def ProcessComponentsForEdit(self) -> None: ...
    def InitializePlacementEngineBuilder(self) -> Placement.PlacementEngineBuilder: ...
    def PreCommitThisPlacement(self) -> None: ...
    def ProcessPlacedPart(self) -> None: ...
    def ProcessPostPlaceParts(self) -> typing.List[Assemblies.Component]: ...
    def GetCoincidentPortForCompatibility(self, portFromPlacedPart: Routing.Port) -> Routing.Port: ...
    def ProcessCompatibilityPostPlaceParts(self) -> typing.List[Assemblies.Component]: ...
    def PrepareDataForConnectivity(self) -> None: ...
    def CommitThisPlacement(self) -> RoutingCommon.PartPlacementBuilder.PlacementValidationStatus: ...
    def SetPrimarySolutionsFlag(self, showPrimarySolutions: bool) -> None: ...
    def GetFilteredPlacementSolutions(self) -> typing.List[Placement.PlacementSolution]: ...
    def SetPortOfPlaceableObject(self, sourcePortObject: TaggedObject) -> None: ...
    def SetPositionAsOption(self, positioningType: RoutingCommon.PartPlacementBuilder.PositionAsType) -> None: ...
    def RotatePlaceableObjectByAngle(self, rotationAngle: float) -> None: ...
    def SetClassificationObjectIdentifierOfPartToPostPlace(self, classificationObjectId: str) -> None: ...
    def SetClassificationObjectIdentifierOfCompatibilityPart(self, ccType: Routing.ReuseLibrary.PartType, classificationObjectId: str, portOne: Routing.Port, portTwo: Routing.Port) -> None: ...
    def UpdateReferenceSet(self, referenseSetName: str) -> None: ...
    def UpdateLayer(self, layerNumber: int) -> None: ...
    def AutoAssignAttributes(self) -> None: ...
    def GetLogicalObjectsHavingUnassignedRequiredAttributes(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    def GetLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    def GetErrorCodeForPlacementSolution(self, placementSolution: Placement.PlacementSolution) -> int: ...
    def SetAddUnconnectedEquipmentToActiveRunOption(self, canAddEquipmentToActiveRun: bool) -> None: ...
    def GetLibraryDefinedAttributeHolder(self) -> Routing.AttributeHolder: ...
    def GetLibraryDefinedPostPlacementAttributeHolder(self) -> Routing.AttributeHolder: ...
    def CopyAttributesToPartToPlace(self, sourcePartOccurrence: Assemblies.Component) -> None: ...
    def ResetAttributesOnLibraryDefinedAttributeHolder(self) -> None: ...
    def ResetAttributesOnPostPlaceLibraryDefinedAttributeHolder(self) -> None: ...
    def DesignateComponentForPlacementSolutionComputation(self, partOccurrence: Assemblies.Component) -> None: ...
    def PerformOperationsAfterPlacement(self) -> None: ...
    @property
    def ComponentsToEditCollector(self) -> Routing.RouteObjectCollector: ...
    @ComponentsToEditCollector.setter
    def ComponentsToEditCollector(self, value: Routing.RouteObjectCollector) -> None: ...
    @property
    def LogicalDesignObject(self) -> NXObject: ...
    @LogicalDesignObject.setter
    def LogicalDesignObject(self, value: NXObject) -> None: ...


    class PositionAsType(enum.Enum):
        Routing= 0
        Equipment= 1
    

    class PlacementValidationStatus(enum.Enum):
        Success= 0
        PartNotConnectedToRout= 1
    

class MovePathBuilder(Builder):
    def __init__(self) -> None: ...
    def StartDrag(self) -> None: ...
    def DragObjects(self) -> None: ...
    def StopDrag(self) -> None: ...
    def ResetDrag(self) -> None: ...
    @property
    def CopyModeType(self) -> RoutingCommon.MovePathBuilder.CopyMode: ...
    @CopyModeType.setter
    def CopyModeType(self, value: RoutingCommon.MovePathBuilder.CopyMode) -> None: ...
    @property
    def DetachType(self) -> RoutingCommon.MovePathBuilder.DetachTypes: ...
    @DetachType.setter
    def DetachType(self, value: RoutingCommon.MovePathBuilder.DetachTypes) -> None: ...
    @property
    def MaintainLength(self) -> bool: ...
    @MaintainLength.setter
    def MaintainLength(self, value: bool) -> None: ...
    @property
    def Motion(self) -> GeometricUtilities.ModlMotion: ...
    @Motion.setter
    def Motion(self, value: GeometricUtilities.ModlMotion) -> None: ...
    @property
    def PathSelection(self) -> Routing.RouteObjectCollector: ...
    @PathSelection.setter
    def PathSelection(self, value: Routing.RouteObjectCollector) -> None: ...
    @property
    def Preview(self) -> bool: ...
    @Preview.setter
    def Preview(self, value: bool) -> None: ...
    @property
    def TargetAssembly(self) -> Assemblies.SelectComponent: ...
    @TargetAssembly.setter
    def TargetAssembly(self, value: Assemblies.SelectComponent) -> None: ...


    class DetachTypes(enum.Enum):
        AlwaysMaintainConnections= 0
        DetachSelectedObjects= 1
    

    class CopyMode(enum.Enum):
        NoCopy= 0
        CopyToWorkPart= 1
        CopyToTarget= 2
    

class MergeBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CandidateStockComponentCollector(self) -> Routing.RouteObjectCollector: ...
    @CandidateStockComponentCollector.setter
    def CandidateStockComponentCollector(self, value: Routing.RouteObjectCollector) -> None: ...
    @property
    def SimplifyPath(self) -> bool: ...
    @SimplifyPath.setter
    def SimplifyPath(self, value: bool) -> None: ...
    @property
    def TargetStockComponentCollector(self) -> Routing.RouteObjectCollector: ...
    @TargetStockComponentCollector.setter
    def TargetStockComponentCollector(self, value: Routing.RouteObjectCollector) -> None: ...


class ManageInlineBehaviorBuilder(Builder):
    def __init__(self) -> None: ...
    def SetModelElementRevision(self, modelElementRevision: PDM.ModelElementRevision) -> None: ...
    def SetComponent(self, component: Assemblies.Component) -> None: ...
    def SetComponents(self, components: typing.List[TaggedObject]) -> None: ...
    def SetInlineBehavior(self, isInline: bool) -> None: ...
    def GetInlineBehavior(self) -> bool: ...


class InsulationService(Utilities.NXRemotableObject):
    def __init__(self, owner: RoutingCommon.RoutingManager) -> None: ...
    def GetAllInsulatedObjectsInContainer(self, container: Assemblies.Component) -> typing.List[NXObject]: ...
    def Tag(self) -> Tag: ...



class InsulationBuilder(Builder):
    def __init__(self) -> None: ...
    def PreCommit(self) -> None: ...
    def GetLogicalObject(self) -> PDM.LogicalObject: ...
    def SuggestWrapMethodBasedOnStockSettings(self) -> RoutingCommon.InsulationBuilder.WrapType: ...
    def UpdatePath(self) -> None: ...
    def GetOrderedPath(self, orderedPath: typing.List[TaggedObject]) -> None: ...
    def CreateScalarPoint(self, partToCreatePointIn: Part, pointLocation: float) -> TaggedObject: ...
    @property
    def AddInsulationOnFittings(self) -> bool: ...
    @AddInsulationOnFittings.setter
    def AddInsulationOnFittings(self, value: bool) -> None: ...
    @property
    def ApplicationMethod(self) -> RoutingCommon.InsulationBuilder.ApplicationType: ...
    @ApplicationMethod.setter
    def ApplicationMethod(self, value: RoutingCommon.InsulationBuilder.ApplicationType) -> None: ...
    @property
    def EndOffsetPoint(self) -> RoutingCommon.PathDimensionBuilder: ...
    @EndOffsetPoint.setter
    def EndOffsetPoint(self, value: RoutingCommon.PathDimensionBuilder) -> None: ...
    @property
    def EndPoint(self) -> RoutingCommon.PathDimensionBuilder: ...
    @EndPoint.setter
    def EndPoint(self, value: RoutingCommon.PathDimensionBuilder) -> None: ...
    @property
    def GapDistance(self) -> Expression: ...
    @GapDistance.setter
    def GapDistance(self, value: Expression) -> None: ...
    @property
    def InsulationPartOccurrenceSelection(self) -> Assemblies.SelectComponent: ...
    @InsulationPartOccurrenceSelection.setter
    def InsulationPartOccurrenceSelection(self, value: Assemblies.SelectComponent) -> None: ...
    @property
    def OffsetMethod(self) -> RoutingCommon.InsulationBuilder.OffsetMethodType: ...
    @OffsetMethod.setter
    def OffsetMethod(self, value: RoutingCommon.InsulationBuilder.OffsetMethodType) -> None: ...
    @property
    def OverlapPercentage(self) -> Expression: ...
    @OverlapPercentage.setter
    def OverlapPercentage(self, value: Expression) -> None: ...
    @property
    def SegmentCollector(self) -> Routing.RouteObjectCollector: ...
    @SegmentCollector.setter
    def SegmentCollector(self, value: Routing.RouteObjectCollector) -> None: ...
    @property
    def StartOffsetPoint(self) -> RoutingCommon.PathDimensionBuilder: ...
    @StartOffsetPoint.setter
    def StartOffsetPoint(self, value: RoutingCommon.PathDimensionBuilder) -> None: ...
    @property
    def StartPoint(self) -> RoutingCommon.PathDimensionBuilder: ...
    @StartPoint.setter
    def StartPoint(self, value: RoutingCommon.PathDimensionBuilder) -> None: ...
    @property
    def StockSettings(self) -> Routing.StockBlockBuilder: ...
    @StockSettings.setter
    def StockSettings(self, value: Routing.StockBlockBuilder) -> None: ...
    @property
    def SwitchStartEnd(self) -> bool: ...
    @SwitchStartEnd.setter
    def SwitchStartEnd(self, value: bool) -> None: ...
    @property
    def WrapMethod(self) -> RoutingCommon.InsulationBuilder.WrapType: ...
    @WrapMethod.setter
    def WrapMethod(self, value: RoutingCommon.InsulationBuilder.WrapType) -> None: ...


    class WrapType(enum.Enum):
        NoWarp= 0
        OverlapSpiral= 1
        StripedSpiral= 2
    

    class OffsetMethodType(enum.Enum):
        FromBothEnds= 0
        FromOneEnd= 1
    

    class ApplicationType(enum.Enum):
        EntireSegments= 0
        Offsets= 1
        PointAndLength= 2
    

class EditPointBuilder(Builder):
    def __init__(self) -> None: ...
    def StartDrag(self) -> None: ...
    def DragObjects(self) -> None: ...
    def StopDrag(self) -> None: ...
    def ResetDrag(self) -> None: ...
    @property
    def ActiveEditSegmentType(self) -> RoutingCommon.EditPointBuilder.Editsegmenttype: ...
    @ActiveEditSegmentType.setter
    def ActiveEditSegmentType(self, value: RoutingCommon.EditPointBuilder.Editsegmenttype) -> None: ...
    @property
    def ActiveMotionType(self) -> RoutingCommon.EditPointBuilder.Motiontype: ...
    @ActiveMotionType.setter
    def ActiveMotionType(self, value: RoutingCommon.EditPointBuilder.Motiontype) -> None: ...
    @property
    def BendAngle(self) -> float: ...
    @BendAngle.setter
    def BendAngle(self, value: float) -> None: ...
    @property
    def MaintainAngle(self) -> bool: ...
    @MaintainAngle.setter
    def MaintainAngle(self, value: bool) -> None: ...
    @property
    def MaintainLength(self) -> bool: ...
    @MaintainLength.setter
    def MaintainLength(self, value: bool) -> None: ...
    @property
    def PointSelection(self) -> Routing.RouteObjectCollector: ...
    @PointSelection.setter
    def PointSelection(self, value: Routing.RouteObjectCollector) -> None: ...
    @property
    def Segment(self) -> Routing.ISegment: ...
    @Segment.setter
    def Segment(self, value: Routing.ISegment) -> None: ...
    @property
    def SegmentLength(self) -> float: ...
    @SegmentLength.setter
    def SegmentLength(self, value: float) -> None: ...
    @property
    def TransformTool(self) -> RoutingCommon.TransformBlockBuilder: ...
    @TransformTool.setter
    def TransformTool(self, value: RoutingCommon.TransformBlockBuilder) -> None: ...


    class Motiontype(enum.Enum):
        MovePoint= 0
        EditSegment= 1
    

    class Editsegmenttype(enum.Enum):
        None_= 0
        Length= 1
        Angle= 2
    

class EditPlacementBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def PartPlacementBuilder(self) -> RoutingCommon.PartPlacementBuilder: ...
    @PartPlacementBuilder.setter
    def PartPlacementBuilder(self, value: RoutingCommon.PartPlacementBuilder) -> None: ...


class DerivedPathBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Associativity(self) -> RoutingCommon.DerivedPathBuilder.AssociativityType: ...
    @Associativity.setter
    def Associativity(self, value: RoutingCommon.DerivedPathBuilder.AssociativityType) -> None: ...
    @property
    def CurveSelection(self) -> Section: ...
    @CurveSelection.setter
    def CurveSelection(self, value: Section) -> None: ...
    @property
    def NumberOfPoints(self) -> int: ...
    @NumberOfPoints.setter
    def NumberOfPoints(self, value: int) -> None: ...
    @property
    def SelectedCurveVisibility(self) -> RoutingCommon.DerivedPathBuilder.SelectedCurveStatus: ...
    @SelectedCurveVisibility.setter
    def SelectedCurveVisibility(self, value: RoutingCommon.DerivedPathBuilder.SelectedCurveStatus) -> None: ...


    class SelectedCurveStatus(enum.Enum):
        Visible= 0
        Hidden= 1
    

    class AssociativityType(enum.Enum):
        Associative= 0
        Copy= 1
    

class CustomManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def AddDesignRule(self, reason: Routing.CustomManager.DesignRuleReason, name: str, description: str, designRuleMethod: RoutingCommon.CustomManager.DesignRule) -> int: ...
    def RemoveDesignRule(self, designRuleMethodId: int) -> None: ...
    def RemoveAllDesignRulesForReason(self, reason: Routing.CustomManager.DesignRuleReason) -> None: ...
    def RemoveAllDesignRules(self) -> None: ...
    def GetDesignRulesRegisteredForReason(self, reason: Routing.CustomManager.DesignRuleReason, registeredDesignRuleIds: int) -> None: ...
    def GetViolationsForReason(self, reason: Routing.CustomManager.DesignRuleReason) -> typing.List[Routing.DesignRuleViolation]: ...
    def GetViolationsOfRule(self, designRuleName: str) -> typing.List[Routing.DesignRuleViolation]: ...
    def CreateViolationForReason(self, designRuleName: str, reason: Routing.CustomManager.DesignRuleReason, shortDescription: str, longDescription: str, objects: typing.List[NXObject]) -> Routing.DesignRuleViolation: ...
    def DeleteViolationsOnObjectForReason(self, reason: Routing.CustomManager.DesignRuleReason, nxObject: NXObject) -> None: ...
    def DeleteViolationsOfRuleOnObject(self, designRuleName: str, nxObject: NXObject) -> None: ...
    def RemoveAllPlugins(self) -> None: ...
    def SetRSDApplicationEnterPlugin(self, applicationEnterPlugin: RoutingCommon.CustomManager.RSDApplicationEnterPlugin) -> None: ...
    def RemoveRSDApplicationEnterPlugin(self) -> None: ...
    def SetRSDApplicationExitPlugin(self, applicationExitPlugin: RoutingCommon.CustomManager.RSDApplicationExitPlugin) -> None: ...
    def RemoveRSDApplicationExitPlugin(self) -> None: ...
    def SetCablewayXmlFileNamePlugin(self, xmlFileNamePlugin: RoutingCommon.CustomManager.CablewayXmlFileNamePlugin) -> None: ...
    def RemoveCablewayXmlFileNamePlugin(self) -> None: ...
    def SetCablewayUniqueNodeNamePlugin(self, uniqueNodeNamePlugin: RoutingCommon.CustomManager.CablewayUniqueNodeNamePlugin) -> None: ...
    def RemoveCablewayUniqueNodeNamePlugin(self) -> None: ...
    def SetCablewayUniqueSegmentNamePlugin(self, uniqueSegmentNamePlugin: RoutingCommon.CustomManager.CablewayUniqueSegmentNamePlugin) -> None: ...
    def RemoveCablewayUniqueSegmentNamePlugin(self) -> None: ...
    def SetCablewayDeviceIdentifierPlugin(self, cablewayDeviceIdentifierPlugin: RoutingCommon.CustomManager.CablewayDeviceIdentifierPlugin) -> None: ...
    def RemoveCablewayDeviceIdentifierPlugin(self) -> None: ...
    def SetCablewayPreExportPlugin(self, cablewayPreExportPlugin: RoutingCommon.CustomManager.CablewayPreExportPlugin) -> None: ...
    def RemoveCablewayPreExportPlugin(self) -> None: ...
    def SetCablewayPostExportPlugin(self, cablewayPostExportPlugin: RoutingCommon.CustomManager.CablewayPostExportPlugin) -> None: ...
    def RemoveCablewayPostExportPlugin(self) -> None: ...
    def SetCablewayAreaNamePlugin(self, cablewayAreaNamePlugin: RoutingCommon.CustomManager.CablewayAreaNamePlugin) -> None: ...
    def RemoveCablewayAreaNamePlugin(self) -> None: ...
    def SetWiringComponentNamePlugin(self, wiringComponentNamePlugin: RoutingCommon.CustomManager.ComponentNamePlugin) -> None: ...
    def RemoveWiringComponentNamePlugin(self) -> None: ...
    def Tag(self) -> Tag: ...



    

    

    

    

    

    

    

    

    

    

    

    class Application(enum.Enum):
        Electrical= 0
        Mechanical= 1
    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

class CreatePathBuilder(Builder):
    def __init__(self) -> None: ...
    def CreatePathTransitionManagerBuilder(self, workPart: Part, workOcc: Assemblies.Component, displayPart: Part) -> RoutingCommon.PathTransitionListManagerBuilder: ...
    def PreCommit(self) -> None: ...
    def GetLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    def GetBendCornerAttributes(self, attributes: typing.List[NXObject.AttributeInformation]) -> None: ...
    def SetBendCornerAttributes(self, attributes: typing.List[NXObject.AttributeInformation]) -> None: ...
    def RemoveBendCornerAttributes(self, corners: typing.List[Routing.Corner]) -> None: ...
    def SetLogicalConnection(self, connection: TaggedObject) -> None: ...
    def GetLogicalConnection(self) -> TaggedObject: ...
    @property
    def BendCornerSettings(self) -> RoutingCommon.BendCornerTypeBuilder: ...
    @BendCornerSettings.setter
    def BendCornerSettings(self, value: RoutingCommon.BendCornerTypeBuilder) -> None: ...
    @property
    def CornerSettings(self) -> RoutingCommon.CornerBuilder: ...
    @CornerSettings.setter
    def CornerSettings(self, value: RoutingCommon.CornerBuilder) -> None: ...
    @property
    def PathStockBuilder(self) -> RoutingCommon.StockBuilder: ...
    @PathStockBuilder.setter
    def PathStockBuilder(self, value: RoutingCommon.StockBuilder) -> None: ...
    @property
    def PathTransitionListManagerBuilder(self) -> RoutingCommon.PathTransitionListManagerBuilder: ...
    @PathTransitionListManagerBuilder.setter
    def PathTransitionListManagerBuilder(self, value: RoutingCommon.PathTransitionListManagerBuilder) -> None: ...
    @property
    def StockSettings(self) -> Routing.StockBlockBuilder: ...
    @StockSettings.setter
    def StockSettings(self, value: Routing.StockBlockBuilder) -> None: ...


class CornerBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def BendCornerSettings(self) -> RoutingCommon.BendCornerTypeBuilder: ...
    @BendCornerSettings.setter
    def BendCornerSettings(self, value: RoutingCommon.BendCornerTypeBuilder) -> None: ...
    @property
    def CornerType(self) -> RoutingCommon.CornerBuilder.Type: ...
    @CornerType.setter
    def CornerType(self, value: RoutingCommon.CornerBuilder.Type) -> None: ...


    class Type(enum.Enum):
        None_= 0
        Bend= 1
        Miter= 2
    

class ConnectBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def ComponentsCollector(self) -> Assemblies.SelectComponentList: ...
    @ComponentsCollector.setter
    def ComponentsCollector(self, value: Assemblies.SelectComponentList) -> None: ...


class BuilderFactory(Utilities.NXRemotableObject):
    def __init__(self, owner: RoutingCommon.RoutingManager) -> None: ...
    def CreateInsulationBuilder(self, part: Part, workOcc: Assemblies.Component, insulationPartOccurrence: Assemblies.Component) -> RoutingCommon.InsulationBuilder: ...
    def CreateAssignComponentNameBuilder(self, part: Part, workOcc: Assemblies.Component) -> RoutingCommon.AssignComponentNameBuilder: ...
    def CreateSubdivideCurveBuilder(self, part: Part, segment: NXObject, pickPoint: Point3d) -> RoutingCommon.SubdivideCurveBuilder: ...
    def CreateSimplifyCurvesBuilder(self, part: Part, workOcc: Assemblies.Component, segments: typing.List[Routing.ISegment]) -> RoutingCommon.SimplifyCurvesBuilder: ...
    def CreateStockBuilder(self, part: Part, workOcc: Assemblies.Component, segmentsOrStocks: typing.List[NXObject]) -> RoutingCommon.StockBuilder: ...
    def CreateSplitBuilder(self, part: Part, controlPoints: typing.List[Routing.ControlPoint]) -> RoutingCommon.SplitBuilder: ...
    @typing.overload
    def CreateConnectBuilder(self, part: Part, components: typing.List[Assemblies.Component]) -> RoutingCommon.ConnectBuilder: ...
    @typing.overload
    def CreateConnectBuilder(self, part: Part, workOcc: Assemblies.Component, components: typing.List[Assemblies.Component]) -> RoutingCommon.ConnectBuilder: ...
    def CreateMergeBuilder(self, part: Part, workOcc: Assemblies.Component) -> RoutingCommon.MergeBuilder: ...
    def CreateMovePathBuilder(self, part: Part, workOcc: Assemblies.Component) -> RoutingCommon.MovePathBuilder: ...
    def CreateEditPointBuilder(self, part: Part, workOcc: Assemblies.Component) -> RoutingCommon.EditPointBuilder: ...
    def CreateTransformBlockBuilder(self, part: Part) -> RoutingCommon.TransformBlockBuilder: ...
    def CreateAssignCornerBuilder(self, part: Part, workOcc: Assemblies.Component) -> RoutingCommon.AssignCornerBuilder: ...
    def CreatePathBuilder(self, part: Part, workOcc: Assemblies.Component) -> RoutingCommon.CreatePathBuilder: ...
    def CreatePartPlacementBuilder(self, part: Part, workOcc: Assemblies.Component) -> RoutingCommon.PartPlacementBuilder: ...
    def CreateEditPlacementBuilder(self, part: Part, workOcc: Assemblies.Component) -> RoutingCommon.EditPlacementBuilder: ...
    @typing.overload
    def CreateManageInlineBehaviorBuilder(self, part: Part) -> RoutingCommon.ManageInlineBehaviorBuilder: ...
    @typing.overload
    def CreateManageInlineBehaviorBuilder(self, part: Part, workOcc: Assemblies.Component) -> RoutingCommon.ManageInlineBehaviorBuilder: ...
    def CreateSplineBuilder(self, part: Part, rootpart: Part, activePathComp: Assemblies.Component, spline: Curve) -> RoutingCommon.SplineBuilder: ...
    def CreateSplinePointBuilder(self, part: Part, splineBuilder: RoutingCommon.SplineBuilder) -> RoutingCommon.SplinePointBuilder: ...
    def CreateReparentPartsBuilder(self, part: Part) -> RoutingCommon.ReparentPartsBuilder: ...
    def CreateDerivedPathBuilder(self, part: Part) -> RoutingCommon.DerivedPathBuilder: ...
    def Tag(self) -> Tag: ...



class BendCornerTypeBuilder(RoutingCommon.BaseCornerTypeBuilder):
    def __init__(self) -> None: ...
    @property
    def Method(self) -> RoutingCommon.BendCornerTypeBuilder.BendMethod: ...
    @Method.setter
    def Method(self, value: RoutingCommon.BendCornerTypeBuilder.BendMethod) -> None: ...
    @property
    def Radius(self) -> Expression: ...
    @Radius.setter
    def Radius(self, value: Expression) -> None: ...
    @property
    def RadiusFromBendTable(self) -> float: ...
    @RadiusFromBendTable.setter
    def RadiusFromBendTable(self, value: float) -> None: ...
    @property
    def RatioToAttributeName(self) -> str: ...
    @RatioToAttributeName.setter
    def RatioToAttributeName(self, value: str) -> None: ...
    @property
    def RatioToAttributeValue(self) -> Expression: ...
    @RatioToAttributeValue.setter
    def RatioToAttributeValue(self, value: Expression) -> None: ...
    @property
    def RatioToDiameter(self) -> Expression: ...
    @RatioToDiameter.setter
    def RatioToDiameter(self, value: Expression) -> None: ...
    @property
    def StockPartNumberFromBendTable(self) -> str: ...
    @StockPartNumberFromBendTable.setter
    def StockPartNumberFromBendTable(self, value: str) -> None: ...


    class BendMethod(enum.Enum):
        Radius= 0
        RatioToDiameter= 1
        RatioToAttribute= 2
        BendRadiusTable= 3
        InnerRadius= 4
    

class BaseCornerTypeBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...


class AssignCornerBuilder(Builder):
    def __init__(self) -> None: ...
    def GetCreatedComponents(self) -> typing.List[Assemblies.Component]: ...
    def PreCommit(self) -> None: ...
    def GetLogicalObjects(self, logicalObjects: typing.List[PDM.LogicalObject]) -> None: ...
    def GetBendCornerAttributes(self, attributes: typing.List[NXObject.AttributeInformation]) -> None: ...
    def SetBendCornerAttributes(self, attributes: typing.List[NXObject.AttributeInformation]) -> None: ...
    def RemoveBendCornerAttributes(self, corners: typing.List[Routing.Corner]) -> None: ...
    @property
    def BendCornerSettings(self) -> RoutingCommon.BendCornerTypeBuilder: ...
    @BendCornerSettings.setter
    def BendCornerSettings(self, value: RoutingCommon.BendCornerTypeBuilder) -> None: ...
    @property
    def ControlPointSelection(self) -> Routing.RouteObjectCollector: ...
    @ControlPointSelection.setter
    def ControlPointSelection(self, value: Routing.RouteObjectCollector) -> None: ...
    @property
    def CornerSettings(self) -> RoutingCommon.CornerBuilder: ...
    @CornerSettings.setter
    def CornerSettings(self, value: RoutingCommon.CornerBuilder) -> None: ...
    @property
    def Type(self) -> RoutingCommon.AssignCornerBuilder.CornerType: ...
    @Type.setter
    def Type(self, value: RoutingCommon.AssignCornerBuilder.CornerType) -> None: ...


    class CornerType(enum.Enum):
        None_= 0
        Bend= 1
        Miter= 2
    

class AssignComponentNameBuilder(Builder):
    def __init__(self) -> None: ...
    def SetPartSpecOnLogicalObject(self, logicalObject: PDM.LogicalObject, partSpec: str) -> None: ...


