from . import Mechanical
from . import Model
from ...NXOpen import *

import typing
import enum

class SymbolSourceOption(enum.Enum):
    ReuseLibrary= 0
    ExistingSymbol= 1
    ModelNode= 2


class SheetCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Schematic.Sheet]: ...
    @typing.overload
    def __init__(self, owner: Schematic.SchematicManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> Schematic.Sheet: ...
    def Tag(self) -> Tag: ...



class Sheet(NXObject):
    def __init__(self) -> None: ...


class SchematicManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Part) -> None: ...
    def CreateSheet(self) -> Schematic.Sheet: ...
    def CreateNodeBuilder(self, node: Schematic.Node) -> Schematic.NodeBuilder: ...
    def CreateConnectionBuilder(self, connection: Schematic.Connection) -> Schematic.ConnectionBuilder: ...
    def CreateFdaBuilder(self, node: Diagramming.Node) -> Schematic.FlowDirectionArrowBuilder: ...
    def CreateBulkEditBuilder(self) -> Schematic.BulkEditBuilder: ...
    def CreatePreferencesBuilder(self, sheet: Schematic.Sheet) -> Schematic.PreferencesBuilder: ...
    def CreatePortBuilder(self, port: Schematic.Port) -> Schematic.PortBuilder: ...
    def Tag(self) -> Tag: ...

    @property
    def Sheets(self) -> Schematic.SheetCollection: ...
    @Sheets.setter
    def Sheets(self, value: Schematic.SheetCollection) -> None: ...
    @property
    def Nodes(self) -> Schematic.NodeCollection: ...
    @Nodes.setter
    def Nodes(self, value: Schematic.NodeCollection) -> None: ...
    @property
    def Connections(self) -> Schematic.ConnectionCollection: ...
    @Connections.setter
    def Connections(self, value: Schematic.ConnectionCollection) -> None: ...
    @property
    def Ports(self) -> Schematic.PortCollection: ...
    @Ports.setter
    def Ports(self, value: Schematic.PortCollection) -> None: ...


class RotateAngleOption(enum.Enum):
    Zero= 0
    Ninety= 1
    OneHundredAndEighty= 2
    TwoHundredAndSeventy= 3


class PreferencesGeneralBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def HidePorts(self) -> bool: ...
    @HidePorts.setter
    def HidePorts(self, value: bool) -> None: ...


class PreferencesConnectionBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def AllowNonOrthogonalConnections(self) -> bool: ...
    @AllowNonOrthogonalConnections.setter
    def AllowNonOrthogonalConnections(self, value: bool) -> None: ...
    @property
    def ArrowSize(self) -> float: ...
    @ArrowSize.setter
    def ArrowSize(self, value: float) -> None: ...
    @property
    def ArrowStyle(self) -> Diagramming.DiagrammingFlowdirectionarrowstyle: ...
    @ArrowStyle.setter
    def ArrowStyle(self, value: Diagramming.DiagrammingFlowdirectionarrowstyle) -> None: ...
    @property
    def JumperGap(self) -> float: ...
    @JumperGap.setter
    def JumperGap(self, value: float) -> None: ...
    @property
    def JumperPriority(self) -> Diagramming.DiagrammingJumperprioritytype: ...
    @JumperPriority.setter
    def JumperPriority(self, value: Diagramming.DiagrammingJumperprioritytype) -> None: ...
    @property
    def JumperPriorityUseLineType(self) -> bool: ...
    @JumperPriorityUseLineType.setter
    def JumperPriorityUseLineType(self, value: bool) -> None: ...
    @property
    def JumperType(self) -> Diagramming.DiagrammingJumpertype: ...
    @JumperType.setter
    def JumperType(self, value: Diagramming.DiagrammingJumpertype) -> None: ...
    @property
    def MinimumSegmentLength(self) -> float: ...
    @MinimumSegmentLength.setter
    def MinimumSegmentLength(self, value: float) -> None: ...
    @property
    def SnapAngle(self) -> float: ...
    @SnapAngle.setter
    def SnapAngle(self, value: float) -> None: ...
    @property
    def TeeSize(self) -> float: ...
    @TeeSize.setter
    def TeeSize(self, value: float) -> None: ...


class PreferencesBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Annotation(self) -> Schematic.PreferencesAnnotationBuilder: ...
    @Annotation.setter
    def Annotation(self, value: Schematic.PreferencesAnnotationBuilder) -> None: ...
    @property
    def Connection(self) -> Schematic.PreferencesConnectionBuilder: ...
    @Connection.setter
    def Connection(self, value: Schematic.PreferencesConnectionBuilder) -> None: ...
    @property
    def General(self) -> Schematic.PreferencesGeneralBuilder: ...
    @General.setter
    def General(self, value: Schematic.PreferencesGeneralBuilder) -> None: ...


class PreferencesAnnotationBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def ConnectionLabelHorizontalOffsetPosition(self) -> Diagramming.DiagrammingConnectionlabelhorizontaloffsetposition: ...
    @ConnectionLabelHorizontalOffsetPosition.setter
    def ConnectionLabelHorizontalOffsetPosition(self, value: Diagramming.DiagrammingConnectionlabelhorizontaloffsetposition) -> None: ...
    @property
    def ConnectionLabelOffset(self) -> float: ...
    @ConnectionLabelOffset.setter
    def ConnectionLabelOffset(self, value: float) -> None: ...
    @property
    def ConnectionLabelPositionCenter(self) -> bool: ...
    @ConnectionLabelPositionCenter.setter
    def ConnectionLabelPositionCenter(self, value: bool) -> None: ...
    @property
    def ConnectionLabelVerticalOffsetPosition(self) -> Diagramming.DiagrammingConnectionlabelverticaloffsetposition: ...
    @ConnectionLabelVerticalOffsetPosition.setter
    def ConnectionLabelVerticalOffsetPosition(self, value: Diagramming.DiagrammingConnectionlabelverticaloffsetposition) -> None: ...
    @property
    def TablesBorderCellSettings(self) -> Diagramming.RenderingPropertiesBuilder: ...
    @TablesBorderCellSettings.setter
    def TablesBorderCellSettings(self, value: Diagramming.RenderingPropertiesBuilder) -> None: ...
    @property
    def TablesCellSettings(self) -> Diagramming.Tables.CellSettingsBuilder: ...
    @TablesCellSettings.setter
    def TablesCellSettings(self, value: Diagramming.Tables.CellSettingsBuilder) -> None: ...
    @property
    def TextStyleConnectionBuilder(self) -> Diagramming.TextStyleBuilder: ...
    @TextStyleConnectionBuilder.setter
    def TextStyleConnectionBuilder(self, value: Diagramming.TextStyleBuilder) -> None: ...
    @property
    def TextStyleNoteBuilder(self) -> Diagramming.TextStyleBuilder: ...
    @TextStyleNoteBuilder.setter
    def TextStyleNoteBuilder(self, value: Diagramming.TextStyleBuilder) -> None: ...


class PortDirectionOption(enum.Enum):
    Input= 0
    Output= 1
    BiDirectional= 2


class PortCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Schematic.Port]: ...
    @typing.overload
    def __init__(self, owner: Schematic.SchematicManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> Schematic.Port: ...
    def Tag(self) -> Tag: ...



class PortBuilder(Schematic.BaseObjectBuilder):
    def __init__(self) -> None: ...
    def GetNode(self) -> Schematic.Node: ...
    def SetNode(self, schNode: Schematic.Node) -> None: ...
    @property
    def ExistingSymbol(self) -> Diagramming.Port: ...
    @ExistingSymbol.setter
    def ExistingSymbol(self, value: Diagramming.Port) -> None: ...
    @property
    def LockAspectRatio(self) -> bool: ...
    @LockAspectRatio.setter
    def LockAspectRatio(self, value: bool) -> None: ...
    @property
    def RelativePercentX(self) -> float: ...
    @RelativePercentX.setter
    def RelativePercentX(self, value: float) -> None: ...
    @property
    def RelativePercentY(self) -> float: ...
    @RelativePercentY.setter
    def RelativePercentY(self, value: float) -> None: ...
    @property
    def RelativeValueX(self) -> float: ...
    @RelativeValueX.setter
    def RelativeValueX(self, value: float) -> None: ...
    @property
    def RelativeValueY(self) -> float: ...
    @RelativeValueY.setter
    def RelativeValueY(self, value: float) -> None: ...
    @property
    def Scale(self) -> float: ...
    @Scale.setter
    def Scale(self, value: float) -> None: ...
    @property
    def ScaleX(self) -> float: ...
    @ScaleX.setter
    def ScaleX(self, value: float) -> None: ...
    @property
    def ScaleY(self) -> float: ...
    @ScaleY.setter
    def ScaleY(self, value: float) -> None: ...
    @property
    def SymbolId(self) -> str: ...
    @SymbolId.setter
    def SymbolId(self, value: str) -> None: ...
    @property
    def SymbolSourceType(self) -> Schematic.SymbolSourceOption: ...
    @SymbolSourceType.setter
    def SymbolSourceType(self, value: Schematic.SymbolSourceOption) -> None: ...


class Port(NXObject):
    def __init__(self) -> None: ...


class NodeCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Schematic.Node]: ...
    @typing.overload
    def __init__(self, owner: Schematic.SchematicManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> Schematic.Node: ...
    def Tag(self) -> Tag: ...



class NodeBuilder(Schematic.BaseObjectBuilder):
    def __init__(self) -> None: ...
    def GetLocation(self) -> Point2d: ...
    def SetLocation(self, location: Point2d) -> None: ...
    def GetNode(self) -> Diagramming.Node: ...
    def DetachAllConnections(self) -> None: ...
    def SetInlineSymbolLocation(self, connection: Schematic.Connection, segementId: int, percent: float) -> None: ...
    def GetInlineSymbolLocation(self, connection: Schematic.Connection, segementId: int, percent: float) -> None: ...
    @property
    def ExistingSymbol(self) -> Diagramming.Node: ...
    @ExistingSymbol.setter
    def ExistingSymbol(self, value: Diagramming.Node) -> None: ...
    @property
    def FlipHorizontal(self) -> bool: ...
    @FlipHorizontal.setter
    def FlipHorizontal(self, value: bool) -> None: ...
    @property
    def FlipVertical(self) -> bool: ...
    @FlipVertical.setter
    def FlipVertical(self, value: bool) -> None: ...
    @property
    def LockAspectRatio(self) -> bool: ...
    @LockAspectRatio.setter
    def LockAspectRatio(self, value: bool) -> None: ...
    @property
    def Rotate(self) -> Schematic.RotateAngleOption: ...
    @Rotate.setter
    def Rotate(self, value: Schematic.RotateAngleOption) -> None: ...
    @property
    def Scale(self) -> float: ...
    @Scale.setter
    def Scale(self, value: float) -> None: ...
    @property
    def ScaleX(self) -> float: ...
    @ScaleX.setter
    def ScaleX(self, value: float) -> None: ...
    @property
    def ScaleY(self) -> float: ...
    @ScaleY.setter
    def ScaleY(self, value: float) -> None: ...
    @property
    def SymbolId(self) -> str: ...
    @SymbolId.setter
    def SymbolId(self, value: str) -> None: ...
    @property
    def SymbolSourceType(self) -> Schematic.SymbolSourceOption: ...
    @SymbolSourceType.setter
    def SymbolSourceType(self, value: Schematic.SymbolSourceOption) -> None: ...


class Node(NXObject):
    def __init__(self) -> None: ...


class FlowDirectionArrowBuilder(Builder):
    def __init__(self) -> None: ...
    def GetConnection(self) -> Schematic.Connection: ...
    def SetConnection(self, connection: Schematic.Connection) -> None: ...
    def ReverseDirection(self) -> None: ...
    @property
    def LocationPercent(self) -> float: ...
    @LocationPercent.setter
    def LocationPercent(self, value: float) -> None: ...
    @property
    def LocationSegment(self) -> int: ...
    @LocationSegment.setter
    def LocationSegment(self, value: int) -> None: ...


class FlowDirectionArrow(NXObject):
    def __init__(self) -> None: ...


class ConnectionEndType(enum.Enum):
    Start= 0
    End= 1


class ConnectionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Schematic.Connection]: ...
    @typing.overload
    def __init__(self, owner: Schematic.SchematicManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> Schematic.Connection: ...
    def Tag(self) -> Tag: ...



class ConnectionBuilder(Schematic.BaseObjectBuilder):
    def __init__(self) -> None: ...
    def GetLineType(self) -> str: ...
    def SetLineType(self, lineType: str) -> None: ...
    def GetBendPoints(self, points: typing.List[Point2d]) -> None: ...
    def SetBendPoints(self, points: typing.List[Point2d]) -> None: ...
    def GetConnection(self) -> Diagramming.Connection: ...
    def GetStartLocation(self) -> Point2d: ...
    def SetStartLocation(self, startLocation: Point2d) -> None: ...
    def GetEndLocation(self) -> Point2d: ...
    def SetEndLocation(self, endLocation: Point2d) -> None: ...
    def GetStart(self) -> Schematic.Port: ...
    def SetStart(self, port: Schematic.Port) -> None: ...
    def GetEnd(self) -> Schematic.Port: ...
    def SetEnd(self, port: Schematic.Port) -> None: ...
    def GetTeeStartLocation(self, connection: Schematic.Connection, segmentId: int, percent: float) -> None: ...
    def SetTeeStartLocation(self, connection: Schematic.Connection, segmentId: int, percent: float) -> None: ...
    def GetTeeEndLocation(self, connection: Schematic.Connection, segmentId: int, percent: float) -> None: ...
    def SetTeeEndLocation(self, connection: Schematic.Connection, segmentId: int, percent: float) -> None: ...
    @property
    def ElementId(self) -> str: ...
    @ElementId.setter
    def ElementId(self, value: str) -> None: ...


class Connection(NXObject):
    def __init__(self) -> None: ...


class BulkEditBuilder(Builder):
    def __init__(self) -> None: ...
    def SetSheetElements(self, sheetElements: typing.List[Diagramming.SheetElement]) -> None: ...
    def SetDeltaXCoordinate(self, deltaXCoordinate: float) -> None: ...
    def SetDeltaYCoordinate(self, deltaYCoordinate: float) -> None: ...
    def SetHide(self, hide: bool) -> None: ...
    def SetHideLabel(self, hideLabel: bool) -> None: ...


class BaseObjectBuilder(Builder):
    def __init__(self) -> None: ...
    def GetDisciplines(self) -> str: ...
    def SetDisciplines(self, disciplines: str) -> None: ...
    @property
    def Id(self) -> str: ...
    @Id.setter
    def Id(self, value: str) -> None: ...
    @property
    def Label(self) -> str: ...
    @Label.setter
    def Label(self, value: str) -> None: ...
    @property
    def Sheet(self) -> Schematic.Sheet: ...
    @Sheet.setter
    def Sheet(self, value: Schematic.Sheet) -> None: ...


