from ....NXOpen import *
from ...CAE import *

import typing
import enum

class Result(NXObject):
    def __init__(self) -> None: ...
    def GetConflictingNodes(self) -> typing.List[CAE.FENode]: ...
    def GetConflictingDofs(self) -> int: ...
    @property
    def FirstElement(self) -> CAE.FEElement: ...
    @FirstElement.setter
    def FirstElement(self, value: CAE.FEElement) -> None: ...
    @property
    def FirstMesh(self) -> CAE.Mesh: ...
    @FirstMesh.setter
    def FirstMesh(self, value: CAE.Mesh) -> None: ...
    @property
    def Id(self) -> str: ...
    @Id.setter
    def Id(self, value: str) -> None: ...
    @property
    def SecondElement(self) -> CAE.FEElement: ...
    @SecondElement.setter
    def SecondElement(self, value: CAE.FEElement) -> None: ...
    @property
    def SecondMesh(self) -> CAE.Mesh: ...
    @SecondMesh.setter
    def SecondMesh(self, value: CAE.Mesh) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class Manager(Utilities.NXRemotableObject):
    def __init__(self, owner: CAE.CaeSession) -> None: ...
    def PerformCheck(self) -> None: ...
    def AutoResolveAllResults(self) -> None: ...
    def AutoResolveSubsetResults(self, resultsToResolve: typing.List[CAE.ModelDependencyCheck.Result]) -> None: ...
    def ExportResults(self, resultsFile: str) -> None: ...
    def GetResults(self) -> typing.List[CAE.ModelDependencyCheck.Result]: ...
    def FindObject(self, journalIdentifier: str) -> INXObject: ...
    def Tag(self) -> Tag: ...



