from ....NXOpen import *
from ...Schematic import *

import typing
import enum

class RunCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Schematic.Mechanical.Run]: ...
    @typing.overload
    def __init__(self, owner: Part) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, journalIdentifier: str) -> Schematic.Mechanical.Run: ...
    def CreateRunBuilder(self, run: Schematic.Mechanical.Run) -> Schematic.Mechanical.RunBuilder: ...
    def Tag(self) -> Tag: ...



class RunBuilder(Builder):
    def __init__(self) -> None: ...
    def SetPartOperationCreateBuilder(self, createBuilder: PDM.PartOperationCreateBuilder) -> None: ...
    @property
    def Discipline(self) -> str: ...
    @Discipline.setter
    def Discipline(self, value: str) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> None: ...
    @property
    def Identifier(self) -> str: ...
    @Identifier.setter
    def Identifier(self, value: str) -> None: ...
    @property
    def LineType(self) -> str: ...
    @LineType.setter
    def LineType(self, value: str) -> None: ...
    @property
    def ObjectApplication(self) -> str: ...
    @ObjectApplication.setter
    def ObjectApplication(self, value: str) -> None: ...
    @property
    def Specification(self) -> str: ...
    @Specification.setter
    def Specification(self, value: str) -> None: ...
    @property
    def Standalone(self) -> bool: ...
    @Standalone.setter
    def Standalone(self, value: bool) -> None: ...


class Run(Schematic.Model.BaseObject):
    def __init__(self) -> None: ...
    @property
    def Discipline(self) -> str: ...
    @Discipline.setter
    def Discipline(self, value: str) -> None: ...
    @property
    def Specification(self) -> str: ...
    @Specification.setter
    def Specification(self, value: str) -> None: ...


