
import typing
import enum

class Win32Utilities(System.Object):
    def __init__(self) -> None: ...




class NXInputBox(System.Object):
    @typing.overload
    def GetInputString(self, prompt: str) -> str: ...
    @typing.overload
    def GetInputString(self, prompt: str, caption: str) -> str: ...
    @typing.overload
    def GetInputString(self, prompt: str, caption: str, initialText: str) -> str: ...
    @typing.overload
    def GetInputNumber(self, prompt: str) -> float: ...
    @typing.overload
    def GetInputNumber(self, prompt: str, caption: str) -> float: ...
    @typing.overload
    def GetInputNumber(self, prompt: str, caption: str, initialText: str) -> float: ...
    @typing.overload
    def GetInputNumber(self, prompt: str, caption: str, initialNumber: float) -> float: ...
    @typing.overload
    def ParseInputNumber(self, prompt: str, caption: str, initialText: str) -> bool: ...
    @typing.overload
    def ParseInputNumber(self, prompt: str, caption: str, initialNumber: float) -> bool: ...
    def __init__(self) -> None: ...


    class NXInputBoxForm(System.Object):
        def __init__(self, prompt: str, caption: str, initialText: str) -> None: ...
        def Dispose(self, disposing: bool) -> None: ...
        @property
        def InputText(self) -> str: ...
        @InputText.setter
        def InputText(self, value: str) -> None: ...
        @property
        def Prompt(self) -> str: ...
        @Prompt.setter
        def Prompt(self, value: str) -> None: ...
        @property
        def Caption(self) -> str: ...
        @Caption.setter
        def Caption(self, value: str) -> None: ...
    

class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class FormUtilities(System.Object):
    def GetNXIcon(self) -> None: ...
    def SetApplicationIcon(self) -> None: ...
    def GetDefaultParentWindowHandle(self) -> int: ...
    def ReparentForm(self) -> None: ...
    def __init__(self) -> None: ...


