from ....NXOpen import *
from ...CAE import *

import typing
import enum

class TestValueTypes(Utilities.NXRemotableObject):
    def __init__(self) -> None: ...


    class Validator(enum.Enum):
        None_= 0
        GreatThan= 1
        GreatThanOrEqual= 2
        SmallThan= 3
        SmallThanOrEqual= 4
    

    class TestType(enum.Enum):
        JacobianZero= 0
        JacobianRatio= 1
        JacobianSign= 2
        Volume= 3
        AxisymmetricY= 4
        AxisymmetricX= 5
        AspectRatio= 6
        SkewAngle= 7
        InteriorAngleMinimum= 8
        InteriorAngleMaximum= 9
        Taper= 10
        WarpFactor= 11
        FaceWarpCoefficient= 12
        EdgePointLengthRatio= 13
        EdgePointIncludedAngle= 14
        LengthRatioOffset= 15
        ParallelDeviation= 16
        ShapeFactor= 17
        Twist= 18
        LengthMinimum= 19
        LengthMaximum= 20
        TetCollapse= 21
        WarpageAngle= 22
        CohesiveElement= 23
        LaminateTaperRatio= 24
        LaminateThicknessRatio= 25
        Area= 26
    

    class Result(enum.Enum):
        Passed= 0
        Failed= 1
        Exception= 2
        NotApply= 3
        Warned= 4
    

    class TestValueTypesElementReference():
        @property
        def ElementTypeName(self) -> str: ...
        @ElementTypeName.setter
        def ElementTypeName(self, value: str) -> None: ...
        @property
        def ElementPropertyName(self) -> str: ...
        @ElementPropertyName.setter
        def ElementPropertyName(self, value: str) -> None: ...
        @property
        def ElementPropertyValue(self) -> int: ...
        @ElementPropertyValue.setter
        def ElementPropertyValue(self, value: int) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, ElementTypeName: str, ElementPropertyName: str, ElementPropertyValue: int) -> None: ...
    

    class CriteriaType(enum.Enum):
        Warning= 0
        Error= 1
    

    class TestValueTypes_ElementReference():
        @property
        def elementTypeName(self) -> int: ...
        @elementTypeName.setter
        def elementTypeName(self, value: int) -> None: ...
        @property
        def elementPropertyName(self) -> int: ...
        @elementPropertyName.setter
        def elementPropertyName(self, value: int) -> None: ...
        @property
        def elementPropertyValue(self) -> int: ...
        @elementPropertyValue.setter
        def elementPropertyValue(self, value: int) -> None: ...
    

class TestResult(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def HasTestValue(self) -> bool: ...
    @property
    def TestType(self) -> CAE.ModelCheck.TestValueTypes.TestType: ...
    @TestType.setter
    def TestType(self, value: CAE.ModelCheck.TestValueTypes.TestType) -> None: ...
    @property
    def TestValue(self) -> float: ...
    @TestValue.setter
    def TestValue(self, value: float) -> None: ...
    @property
    def ValidatedTestResult(self) -> CAE.ModelCheck.TestValueTypes.Result: ...
    @ValidatedTestResult.setter
    def ValidatedTestResult(self, value: CAE.ModelCheck.TestValueTypes.Result) -> None: ...


class SolidElementFaceNormalBuilder(Builder):
    def __init__(self) -> None: ...
    def DisplayNormals(self) -> None: ...
    def ReorientLeftHandedElements(self) -> None: ...
    def CreateGroupOfLeftHandedElements(self) -> None: ...
    @property
    def NegativeFaceColor(self) -> int: ...
    @NegativeFaceColor.setter
    def NegativeFaceColor(self, value: int) -> None: ...
    @property
    def PositiveFaceColor(self) -> int: ...
    @PositiveFaceColor.setter
    def PositiveFaceColor(self, value: int) -> None: ...
    @property
    def SelectionList(self) -> SelectTaggedObjectList: ...
    @SelectionList.setter
    def SelectionList(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def CheckScopeOption(self) -> CAE.ModelCheck.CheckScope: ...
    @CheckScopeOption.setter
    def CheckScopeOption(self, value: CAE.ModelCheck.CheckScope) -> None: ...


class ReverseShellElementNormalBuilder(Builder):
    def __init__(self) -> None: ...
    def DisplayNormals(self) -> None: ...
    def ReverseNormals(self) -> typing.List[CAE.FEElement]: ...
    def CreateInconsistentElementEdgeGroup(self) -> CAE.CaeGroup: ...
    def CreateElementGroupOfSubdomains(self, ppSubdomainGroupTag: typing.List[NXObject]) -> None: ...
    @property
    def DisplayType(self) -> CAE.ModelCheck.ReverseShellElementNormalBuilder.DisplayTypeValue: ...
    @DisplayType.setter
    def DisplayType(self, value: CAE.ModelCheck.ReverseShellElementNormalBuilder.DisplayTypeValue) -> None: ...
    @property
    def NegativeFaceColor(self) -> int: ...
    @NegativeFaceColor.setter
    def NegativeFaceColor(self, value: int) -> None: ...
    @property
    def PositiveFaceColor(self) -> int: ...
    @PositiveFaceColor.setter
    def PositiveFaceColor(self, value: int) -> None: ...
    @property
    def SelectionList(self) -> SelectTaggedObjectList: ...
    @SelectionList.setter
    def SelectionList(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def CheckScopeOption(self) -> CAE.ModelCheck.CheckScope: ...
    @CheckScopeOption.setter
    def CheckScopeOption(self, value: CAE.ModelCheck.CheckScope) -> None: ...


    class DisplayTypeValue(enum.Enum):
        Arrows= 0
        SolidFaceColors= 1
    

class ReverseBeamElementDirectionBuilder(Builder):
    def __init__(self) -> None: ...
    def DisplayDirections(self) -> None: ...
    def ReverseDirections(self) -> typing.List[CAE.FEElement]: ...
    @property
    def SelectionList(self) -> SelectTaggedObjectList: ...
    @SelectionList.setter
    def SelectionList(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def CheckScopeOption(self) -> CAE.ModelCheck.CheckScope: ...
    @CheckScopeOption.setter
    def CheckScopeOption(self, value: CAE.ModelCheck.CheckScope) -> None: ...


class QualityTestValue(NXObject):
    def __init__(self) -> None: ...
    def GetElementSpecificTestByIndex(self, index: int) -> CAE.ModelCheck.ElementSpecificTestValue: ...
    def GetTestType(self) -> CAE.ModelCheck.TestValueTypes.TestType: ...
    def GetValidator(self) -> CAE.ModelCheck.TestValueTypes.Validator: ...
    def HasCriteriaValue(self) -> bool: ...
    def GetCriteriaValue(self, criteriaType: CAE.ModelCheck.TestValueTypes.CriteriaType, criteriaValue: float) -> Unit: ...
    @typing.overload
    def SetCriteriaValue(self, criteriaType: CAE.ModelCheck.TestValueTypes.CriteriaType, criteriaValue: float, unit: Unit) -> None: ...
    @typing.overload
    def SetCriteriaValue(self, criteriaType: CAE.ModelCheck.TestValueTypes.CriteriaType, criteriaValue: str, unit: Unit) -> None: ...
    def GetIsSolverSpecificTest(self, isSystemTest: bool) -> bool: ...
    def GetElementReferences(self) -> typing.List[CAE.ModelCheck.TestValueTypes.ElementReference]: ...
    def ResetToCustomerDefault(self) -> None: ...
    @property
    def ElementSpecificTestCount(self) -> int: ...
    @ElementSpecificTestCount.setter
    def ElementSpecificTestCount(self, value: int) -> None: ...
    @property
    def DoTest(self) -> bool: ...
    @DoTest.setter
    def DoTest(self, value: bool) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class ModelSetupCheckBuilder(Builder):
    def __init__(self) -> None: ...
    def DoCheck(self) -> int: ...
    @property
    def CheckAllComponents(self) -> bool: ...
    @CheckAllComponents.setter
    def CheckAllComponents(self, value: bool) -> None: ...
    @property
    def CheckLabelConflicts(self) -> bool: ...
    @CheckLabelConflicts.setter
    def CheckLabelConflicts(self, value: bool) -> None: ...
    @property
    def CheckUnconnectedComponent(self) -> bool: ...
    @CheckUnconnectedComponent.setter
    def CheckUnconnectedComponent(self, value: bool) -> None: ...
    @property
    def IsDetailedMessage(self) -> bool: ...
    @IsDetailedMessage.setter
    def IsDetailedMessage(self, value: bool) -> None: ...
    @property
    def ReportFileName(self) -> str: ...
    @ReportFileName.setter
    def ReportFileName(self, value: str) -> None: ...


class ITestValue():
    def GetTestType(self) -> CAE.ModelCheck.TestValueTypes.TestType: ...
    def GetValidator(self) -> CAE.ModelCheck.TestValueTypes.Validator: ...
    def HasCriteriaValue(self) -> bool: ...
    def GetCriteriaValue(self, criteriaType: CAE.ModelCheck.TestValueTypes.CriteriaType, criteriaValue: float) -> Unit: ...
    @typing.overload
    def SetCriteriaValue(self, criteriaType: CAE.ModelCheck.TestValueTypes.CriteriaType, criteriaValue: float, unit: Unit) -> None: ...
    @typing.overload
    def SetCriteriaValue(self, criteriaType: CAE.ModelCheck.TestValueTypes.CriteriaType, criteriaValue: str, unit: Unit) -> None: ...
    def GetIsSolverSpecificTest(self, isSystemTest: bool) -> bool: ...
    def GetElementReferences(self) -> typing.List[CAE.ModelCheck.TestValueTypes.ElementReference]: ...
    def ResetToCustomerDefault(self) -> None: ...
    @property
    def DoTest(self) -> bool: ...
    @DoTest.setter
    def DoTest(self, value: bool) -> None: ...


class ISelectionBuilder():
    @property
    def CheckScopeOption(self) -> CAE.ModelCheck.CheckScope: ...
    @CheckScopeOption.setter
    def CheckScopeOption(self, value: CAE.ModelCheck.CheckScope) -> None: ...


class IElementQualityChecker(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def GetElementSize(self, pElem: CAE.FEElement, pMinSize: float, pMazSize: float, pAvgSize: float) -> None: ...
    def GetAspectRatio(self, pElem: CAE.FEElement) -> float: ...
    def GetCohesiveElementRatio(self, pElem: CAE.FEElement) -> float: ...
    def GetSkew(self, pElem: CAE.FEElement) -> float: ...
    def GetTaper(self, pElem: CAE.FEElement) -> float: ...
    def GetWarp(self, pElem: CAE.FEElement) -> float: ...
    def GetInteriorAngle(self, pElem: CAE.FEElement, pMinAngle: float, pMaxAngle: float) -> None: ...
    def GetJacobian(self, pElem: CAE.FEElement, pJacobianZero: float, pJacobianRatio: float, pJacobianSign: bool) -> None: ...
    def GetCollapse(self, pElem: CAE.FEElement) -> float: ...
    def GetTwist(self, pElem: CAE.FEElement) -> float: ...
    def GetEdgePointLengthRatioAndAngle(self, pElem: CAE.FEElement, pRatioValue: float, pAngleValue: float) -> None: ...
    def GetVolume(self, pElem: CAE.FEElement) -> float: ...
    def GetOffsetLengthRatio(self, pElem: CAE.FEElement) -> float: ...
    def GetConsistDistance(self, pElem: CAE.FEElement) -> float: ...
    def GetAxisRadius(self, pElem: CAE.FEElement) -> float: ...
    def GetParallelDeviation(self, pElem: CAE.FEElement) -> float: ...
    def GetShapeFactor(self, pElem: CAE.FEElement) -> float: ...
    def GetLaminateRatio(self, pElem: CAE.FEElement, matMatrix: Matrix3x3, stackAxis: int, totalPlyThick: float, lamEdgeRatio: float, lamThickRatio: float) -> None: ...
    def GetArea(self, pElem: CAE.FEElement) -> float: ...
    def FreeResource(self) -> None: ...


class FaceClearanceCheckBuilder(Builder):
    def __init__(self) -> None: ...
    def DoCheck(self) -> CAE.CaeGroup: ...
    @property
    def Clearance(self) -> Expression: ...
    @Clearance.setter
    def Clearance(self, value: Expression) -> None: ...


class ElementTestResult(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def GetTestResults(self) -> typing.List[CAE.ModelCheck.TestResult]: ...
    def GetTestElement(self) -> CAE.FEElement: ...
    @property
    def OverallResult(self) -> CAE.ModelCheck.TestValueTypes.Result: ...
    @OverallResult.setter
    def OverallResult(self, value: CAE.ModelCheck.TestValueTypes.Result) -> None: ...


class ElementSpecificTestValue(NXObject):
    def __init__(self) -> None: ...
    def GetTestType(self) -> CAE.ModelCheck.TestValueTypes.TestType: ...
    def GetValidator(self) -> CAE.ModelCheck.TestValueTypes.Validator: ...
    def HasCriteriaValue(self) -> bool: ...
    def GetCriteriaValue(self, criteriaType: CAE.ModelCheck.TestValueTypes.CriteriaType, criteriaValue: float) -> Unit: ...
    @typing.overload
    def SetCriteriaValue(self, criteriaType: CAE.ModelCheck.TestValueTypes.CriteriaType, criteriaValue: float, unit: Unit) -> None: ...
    @typing.overload
    def SetCriteriaValue(self, criteriaType: CAE.ModelCheck.TestValueTypes.CriteriaType, criteriaValue: str, unit: Unit) -> None: ...
    def GetIsSolverSpecificTest(self, isSystemTest: bool) -> bool: ...
    def GetElementReferences(self) -> typing.List[CAE.ModelCheck.TestValueTypes.ElementReference]: ...
    def ResetToCustomerDefault(self) -> None: ...
    @property
    def DoTest(self) -> bool: ...
    @DoTest.setter
    def DoTest(self, value: bool) -> None: ...


class ElementQualitySettingCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[CAE.ModelCheck.ElementQualitySetting]: ...
    @typing.overload
    def __init__(self, owner: CAE.CaePart) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def GetElementQualitySetting(self, solverName: str) -> CAE.ModelCheck.ElementQualitySetting: ...
    def FindObject(self, journalIdentifier: str) -> CAE.ModelCheck.ElementQualitySetting: ...
    def Tag(self) -> Tag: ...



class ElementQualitySetting(NXObject):
    def __init__(self) -> None: ...
    def GetTestValueByIndex(self, index: int) -> CAE.ModelCheck.QualityTestValue: ...
    def GetTestValueByType(self, testType: CAE.ModelCheck.TestValueTypes.TestType) -> CAE.ModelCheck.QualityTestValue: ...
    def GetQualityValue(self, descriptorName: str) -> CAE.ModelCheck.ITestValue: ...
    def LocateTestDescriptorName(self, element: CAE.FEElement, testType: CAE.ModelCheck.TestValueTypes.TestType, useElemSpecific: bool) -> str: ...
    def ResetToCustomerDefault(self) -> None: ...
    @property
    def LimitValueOption(self) -> CAE.ModelCheck.ElementQualitySetting.LimitValue: ...
    @LimitValueOption.setter
    def LimitValueOption(self, value: CAE.ModelCheck.ElementQualitySetting.LimitValue) -> None: ...
    @property
    def TestValueCount(self) -> int: ...
    @TestValueCount.setter
    def TestValueCount(self, value: int) -> None: ...
    @property
    def UseElementSpecificValue(self) -> bool: ...
    @UseElementSpecificValue.setter
    def UseElementSpecificValue(self, value: bool) -> None: ...


    class LimitValue(enum.Enum):
        WarningAndErrorLimit= 0
        ErrorLimitOnly= 1
    

class ElementQualityCheckResults(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def GetTestSummary(self) -> typing.List[CAE.ModelCheck.ElementQualityCheckResults.TestSummary]: ...
    def GetElementTestResultByIndex(self, index: int) -> CAE.ModelCheck.ElementTestResult: ...
    @property
    def ElementTestCount(self) -> int: ...
    @ElementTestCount.setter
    def ElementTestCount(self, value: int) -> None: ...


    class ElementQualityCheckResultsTestSummary():
        @property
        def TestType(self) -> CAE.ModelCheck.TestValueTypes.TestType: ...
        @TestType.setter
        def TestType(self, value: CAE.ModelCheck.TestValueTypes.TestType) -> None: ...
        @property
        def WorstTestValue(self) -> float: ...
        @WorstTestValue.setter
        def WorstTestValue(self, value: float) -> None: ...
        @property
        def HasTestValue(self) -> bool: ...
        @HasTestValue.setter
        def HasTestValue(self, value: bool) -> None: ...
        @property
        def TestCount(self) -> int: ...
        @TestCount.setter
        def TestCount(self, value: int) -> None: ...
        @property
        def ErrorCount(self) -> int: ...
        @ErrorCount.setter
        def ErrorCount(self, value: int) -> None: ...
        @property
        def WarnedCount(self) -> int: ...
        @WarnedCount.setter
        def WarnedCount(self, value: int) -> None: ...
        def ToString(self) -> str: ...
    

class ElementQualityCheckBuilder(Builder):
    def __init__(self) -> None: ...
    def ExecuteCheck(self) -> CAE.ModelCheck.ElementQualityCheckResults: ...
    def WriteResultsToFile(self, outputFile: str, eqcResults: CAE.ModelCheck.ElementQualityCheckResults) -> None: ...
    def AttemptFixFailingElements(self, testTypes: typing.List[CAE.ModelCheck.TestValueTypes.TestType]) -> None: ...
    @property
    def ElementReportFormat(self) -> CAE.ModelCheck.ElementQualityCheckBuilder.ReportFormat: ...
    @ElementReportFormat.setter
    def ElementReportFormat(self, value: CAE.ModelCheck.ElementQualityCheckBuilder.ReportFormat) -> None: ...
    @property
    def ElementsOutputOption(self) -> CAE.ModelCheck.ElementQualityCheckBuilder.OutputElements: ...
    @ElementsOutputOption.setter
    def ElementsOutputOption(self, value: CAE.ModelCheck.ElementQualityCheckBuilder.OutputElements) -> None: ...
    @property
    def FailedElementsColor(self) -> NXColor: ...
    @FailedElementsColor.setter
    def FailedElementsColor(self, value: NXColor) -> None: ...
    @property
    def NumberFormat(self) -> CAE.NumberFormat: ...
    @NumberFormat.setter
    def NumberFormat(self, value: CAE.NumberFormat) -> None: ...
    @property
    def SelectionList(self) -> SelectTaggedObjectList: ...
    @SelectionList.setter
    def SelectionList(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def ShowFailedElementsLabel(self) -> bool: ...
    @ShowFailedElementsLabel.setter
    def ShowFailedElementsLabel(self, value: bool) -> None: ...
    @property
    def WarningElementsColor(self) -> NXColor: ...
    @WarningElementsColor.setter
    def WarningElementsColor(self, value: NXColor) -> None: ...
    @property
    def CheckScopeOption(self) -> CAE.ModelCheck.CheckScope: ...
    @CheckScopeOption.setter
    def CheckScopeOption(self, value: CAE.ModelCheck.CheckScope) -> None: ...


    class ReportFormat(enum.Enum):
        None_= 0
        Failed= 1
        Warning= 2
        FailedAndWarning= 3
        All= 4
    

    class OutputElements(enum.Enum):
        None_= 0
        Failed= 1
        Warning= 2
        FailedAndWarning= 3
    

class ElementMaterialOrientationCheckBuilder(Builder):
    def __init__(self) -> None: ...
    def GetCheckOrientation(self, orientationType: CAE.ModelCheck.ElementMaterialOrientationCheckBuilder.MaterialOrientationType) -> bool: ...
    def SetCheckOrientation(self, orientationType: CAE.ModelCheck.ElementMaterialOrientationCheckBuilder.MaterialOrientationType, checkOrientation: bool) -> None: ...
    def GetOrientationColor(self, orientationType: CAE.ModelCheck.ElementMaterialOrientationCheckBuilder.MaterialOrientationType) -> NXColor: ...
    def SetOrientationColor(self, orientationType: CAE.ModelCheck.ElementMaterialOrientationCheckBuilder.MaterialOrientationType, color: NXColor) -> None: ...
    def DoCheck(self, orientationType: typing.List[CAE.ModelCheck.ElementMaterialOrientationCheckBuilder.MaterialOrientationType], elements: typing.List[CAE.FEElement]) -> typing.List[Vector3d]: ...
    def GetArrowheadDisplayType(self) -> CAE.ModelCheck.ElementMaterialOrientationCheckBuilder.MaterialOrientationArrowheadType: ...
    def SetArrowheadDisplayType(self, displayType: CAE.ModelCheck.ElementMaterialOrientationCheckBuilder.MaterialOrientationArrowheadType) -> None: ...
    def GetSolidElementDisplayType(self) -> CAE.ModelCheck.ElementMaterialOrientationCheckBuilder.MaterialOrientationSolidElementDisplayType: ...
    def SetSolidElementDisplayType(self, displayType: CAE.ModelCheck.ElementMaterialOrientationCheckBuilder.MaterialOrientationSolidElementDisplayType) -> None: ...
    def GetCheckTranslucency(self) -> bool: ...
    def SetCheckTranslucency(self, checkOrientation: bool) -> None: ...
    def GetTranslucencyValue(self) -> int: ...
    def SetTranslucencyValue(self, translucencyValue: int) -> None: ...
    def GetArrowShowThrough(self) -> bool: ...
    def SetArrowShowThrough(self, arrowShowThrough: bool) -> None: ...
    @property
    def SelectionList(self) -> SelectTaggedObjectList: ...
    @SelectionList.setter
    def SelectionList(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def CheckScopeOption(self) -> CAE.ModelCheck.CheckScope: ...
    @CheckScopeOption.setter
    def CheckScopeOption(self, value: CAE.ModelCheck.CheckScope) -> None: ...


    class MaterialOrientationType(enum.Enum):
        Shell= 0
        SolidFirstDirection= 1
        SolidSecondDirection= 2
        SolidThirdDirection= 3
    

    class MaterialOrientationSolidElementDisplayType(enum.Enum):
        SolidAllElements= 0
        SolidExteriorElements= 1
    

    class MaterialOrientationArrowheadType(enum.Enum):
        ShowArrowHead= 0
        HideArrowHead= 1
    

class ElementEdgeCheckBuilder(Builder):
    def __init__(self) -> None: ...
    def HideInputMeshes(self, hideInputMeshes: bool) -> None: ...
    def ExecuteCheck(self, freeEdges: typing.List[CAE.FEElemEdge], nonManifoldEdges: typing.List[CAE.FEElemEdge]) -> None: ...
    def DoCheck(self, freeEdges: typing.List[CAE.FEElemEdge], nonManifoldEdges: typing.List[CAE.FEElemEdge], assoElems: typing.List[CAE.FEElement], outputGroup: CAE.CaeGroup) -> None: ...
    @property
    def CheckFreeEdges(self) -> bool: ...
    @CheckFreeEdges.setter
    def CheckFreeEdges(self, value: bool) -> None: ...
    @property
    def CheckNonManifoldEdges(self) -> bool: ...
    @CheckNonManifoldEdges.setter
    def CheckNonManifoldEdges(self, value: bool) -> None: ...
    @property
    def ComputationScope(self) -> CAE.ModelCheck.ElementEdgeCheckBuilder.Scope: ...
    @ComputationScope.setter
    def ComputationScope(self, value: CAE.ModelCheck.ElementEdgeCheckBuilder.Scope) -> None: ...
    @property
    def FreeEdgeDisplayStyle(self) -> CAE.ModelCheck.ElementEdgeCheckBuilder.EdgeDisplayStyle: ...
    @FreeEdgeDisplayStyle.setter
    def FreeEdgeDisplayStyle(self, value: CAE.ModelCheck.ElementEdgeCheckBuilder.EdgeDisplayStyle) -> None: ...
    @property
    def NonManifoldEdgeDisplayStyle(self) -> CAE.ModelCheck.ElementEdgeCheckBuilder.EdgeDisplayStyle: ...
    @NonManifoldEdgeDisplayStyle.setter
    def NonManifoldEdgeDisplayStyle(self, value: CAE.ModelCheck.ElementEdgeCheckBuilder.EdgeDisplayStyle) -> None: ...
    @property
    def SelectionList(self) -> SelectTaggedObjectList: ...
    @SelectionList.setter
    def SelectionList(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def CheckScopeOption(self) -> CAE.ModelCheck.CheckScope: ...
    @CheckScopeOption.setter
    def CheckScopeOption(self, value: CAE.ModelCheck.CheckScope) -> None: ...


    class Scope(enum.Enum):
        EntireModel= 0
        VisibleModel= 1
        SelectedModels= 2
    

    class ElementEdgeCheckBuilderEdgeDisplayStyle():
        @property
        def Font(self) -> DisplayableObject.ObjectFont: ...
        @Font.setter
        def Font(self, value: DisplayableObject.ObjectFont) -> None: ...
        @property
        def Width(self) -> DisplayableObject.ObjectWidth: ...
        @Width.setter
        def Width(self, value: DisplayableObject.ObjectWidth) -> None: ...
        @property
        def Color(self) -> NXColor: ...
        @Color.setter
        def Color(self, value: NXColor) -> None: ...
        def ToString(self) -> str: ...
        def __init__(self, Font: DisplayableObject.ObjectFont, Width: DisplayableObject.ObjectWidth, Color: NXColor) -> None: ...
    

    class ElementEdgeCheckBuilder_EdgeDisplayStyle():
        @property
        def font(self) -> DisplayableObject.ObjectFont: ...
        @font.setter
        def font(self, value: DisplayableObject.ObjectFont) -> None: ...
        @property
        def width(self) -> DisplayableObject.ObjectWidth: ...
        @width.setter
        def width(self, value: DisplayableObject.ObjectWidth) -> None: ...
        @property
        def color(self) -> int: ...
        @color.setter
        def color(self, value: int) -> None: ...
    

class DuplicateNodesCheckBuilder(Builder):
    def __init__(self) -> None: ...
    def IdentifyDuplicateNodes(self) -> None: ...
    def GetDuplicateNodes(self, groupIndex: int) -> typing.List[CAE.FENode]: ...
    def MergeDuplicateNodes(self) -> None: ...
    @property
    def DisplaySettingsData(self) -> CAE.ModelCheck.DuplicateNodesCheckBuilder.DisplaySettings: ...
    @DisplaySettingsData.setter
    def DisplaySettingsData(self, value: CAE.ModelCheck.DuplicateNodesCheckBuilder.DisplaySettings) -> None: ...
    @property
    def DuplicateNodeGroupsCount(self) -> int: ...
    @DuplicateNodeGroupsCount.setter
    def DuplicateNodeGroupsCount(self, value: int) -> None: ...
    @property
    def IgnoreNodesConnectedToTinyEdges(self) -> bool: ...
    @IgnoreNodesConnectedToTinyEdges.setter
    def IgnoreNodesConnectedToTinyEdges(self, value: bool) -> None: ...
    @property
    def IgnoreNodesInSameMesh(self) -> bool: ...
    @IgnoreNodesInSameMesh.setter
    def IgnoreNodesInSameMesh(self, value: bool) -> None: ...
    @property
    def ListingType(self) -> CAE.ModelCheck.DuplicateNodesCheckBuilder.ListOption: ...
    @ListingType.setter
    def ListingType(self, value: CAE.ModelCheck.DuplicateNodesCheckBuilder.ListOption) -> None: ...
    @property
    def MergeOccurrenceNodes(self) -> bool: ...
    @MergeOccurrenceNodes.setter
    def MergeOccurrenceNodes(self, value: bool) -> None: ...
    @property
    def Preference(self) -> CAE.ModelCheck.DuplicateNodesCheckBuilder.MergePreference: ...
    @Preference.setter
    def Preference(self, value: CAE.ModelCheck.DuplicateNodesCheckBuilder.MergePreference) -> None: ...
    @property
    def SelectPreferenceNodesList(self) -> CAE.SelectFENodeList: ...
    @SelectPreferenceNodesList.setter
    def SelectPreferenceNodesList(self, value: CAE.SelectFENodeList) -> None: ...
    @property
    def SelectionList(self) -> SelectTaggedObjectList: ...
    @SelectionList.setter
    def SelectionList(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def Tolerance(self) -> Expression: ...
    @Tolerance.setter
    def Tolerance(self, value: Expression) -> None: ...
    @property
    def CheckScopeOption(self) -> CAE.ModelCheck.CheckScope: ...
    @CheckScopeOption.setter
    def CheckScopeOption(self, value: CAE.ModelCheck.CheckScope) -> None: ...


    class MergePreference(enum.Enum):
        None_= 0
        KeepHighLabel= 1
        KeepLowLabel= 2
        KeepSelected= 3
        RemoveSelected= 4
    

    class ListOption(enum.Enum):
        All= 0
        Mergeable= 1
        Unmergeable= 2
    

    class DuplicateNodesCheckBuilderDisplaySettings():
        @property
        def ShowDuplicateNodes(self) -> bool: ...
        @ShowDuplicateNodes.setter
        def ShowDuplicateNodes(self, value: bool) -> None: ...
        @property
        def ShowMergedNodeLabels(self) -> bool: ...
        @ShowMergedNodeLabels.setter
        def ShowMergedNodeLabels(self, value: bool) -> None: ...
        @property
        def ShowRetainedNodeLabels(self) -> bool: ...
        @ShowRetainedNodeLabels.setter
        def ShowRetainedNodeLabels(self, value: bool) -> None: ...
        @property
        def KeepNodesColor(self) -> NXColor: ...
        @KeepNodesColor.setter
        def KeepNodesColor(self, value: NXColor) -> None: ...
        @property
        def MergeNodesColor(self) -> NXColor: ...
        @MergeNodesColor.setter
        def MergeNodesColor(self, value: NXColor) -> None: ...
        @property
        def UnableToMergeNodesColor(self) -> NXColor: ...
        @UnableToMergeNodesColor.setter
        def UnableToMergeNodesColor(self, value: NXColor) -> None: ...
        def ToString(self) -> str: ...
    

    class DuplicateNodesCheckBuilder_DisplaySettings():
        @property
        def showDuplicateNodes(self) -> bool: ...
        @showDuplicateNodes.setter
        def showDuplicateNodes(self, value: bool) -> None: ...
        @property
        def showMergedNodeLabels(self) -> bool: ...
        @showMergedNodeLabels.setter
        def showMergedNodeLabels(self, value: bool) -> None: ...
        @property
        def showRetainedNodeLabels(self) -> bool: ...
        @showRetainedNodeLabels.setter
        def showRetainedNodeLabels(self, value: bool) -> None: ...
        @property
        def keepNodesColor(self) -> int: ...
        @keepNodesColor.setter
        def keepNodesColor(self, value: int) -> None: ...
        @property
        def mergeNodesColor(self) -> int: ...
        @mergeNodesColor.setter
        def mergeNodesColor(self, value: int) -> None: ...
        @property
        def unableToMergeNodesColor(self) -> int: ...
        @unableToMergeNodesColor.setter
        def unableToMergeNodesColor(self, value: int) -> None: ...
    

class DuplicateElementsCheckBuilder(Builder):
    def __init__(self) -> None: ...
    def IdentifyDuplicateElements(self) -> None: ...
    def GetDuplicateElements(self, groupIndex: int) -> typing.List[CAE.FEElement]: ...
    def DeleteDuplicateElements(self) -> None: ...
    @property
    def DisplaySettingsData(self) -> CAE.ModelCheck.DuplicateElementsCheckBuilder.DisplaySettings: ...
    @DisplaySettingsData.setter
    def DisplaySettingsData(self, value: CAE.ModelCheck.DuplicateElementsCheckBuilder.DisplaySettings) -> None: ...
    @property
    def DuplicateElementGroupsCount(self) -> int: ...
    @DuplicateElementGroupsCount.setter
    def DuplicateElementGroupsCount(self, value: int) -> None: ...
    @property
    def Preference(self) -> CAE.ModelCheck.DuplicateElementsCheckBuilder.DeletePreference: ...
    @Preference.setter
    def Preference(self, value: CAE.ModelCheck.DuplicateElementsCheckBuilder.DeletePreference) -> None: ...
    @property
    def PreferenceElements(self) -> CAE.SelectElementsBuilder: ...
    @PreferenceElements.setter
    def PreferenceElements(self, value: CAE.SelectElementsBuilder) -> None: ...
    @property
    def SelectionList(self) -> SelectTaggedObjectList: ...
    @SelectionList.setter
    def SelectionList(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def CheckScopeOption(self) -> CAE.ModelCheck.CheckScope: ...
    @CheckScopeOption.setter
    def CheckScopeOption(self, value: CAE.ModelCheck.CheckScope) -> None: ...


    class DuplicateElementsCheckBuilderDisplaySettings():
        @property
        def ShowDuplicateElements(self) -> bool: ...
        @ShowDuplicateElements.setter
        def ShowDuplicateElements(self, value: bool) -> None: ...
        @property
        def ShowElementLabels(self) -> bool: ...
        @ShowElementLabels.setter
        def ShowElementLabels(self, value: bool) -> None: ...
        @property
        def ElementsColor(self) -> NXColor: ...
        @ElementsColor.setter
        def ElementsColor(self, value: NXColor) -> None: ...
        @property
        def ElementsWidth(self) -> DisplayableObject.ObjectWidth: ...
        @ElementsWidth.setter
        def ElementsWidth(self, value: DisplayableObject.ObjectWidth) -> None: ...
        def ToString(self) -> str: ...
    

    class DeletePreference(enum.Enum):
        KeepHighLabel= 0
        KeepLowLabel= 1
        KeepSelected= 2
        RemoveSelected= 3
    

    class DuplicateElementsCheckBuilder_DisplaySettings():
        @property
        def showDuplicateElements(self) -> bool: ...
        @showDuplicateElements.setter
        def showDuplicateElements(self, value: bool) -> None: ...
        @property
        def showElementLabels(self) -> bool: ...
        @showElementLabels.setter
        def showElementLabels(self, value: bool) -> None: ...
        @property
        def elementsColor(self) -> int: ...
        @elementsColor.setter
        def elementsColor(self, value: int) -> None: ...
        @property
        def elementsWidth(self) -> DisplayableObject.ObjectWidth: ...
        @elementsWidth.setter
        def elementsWidth(self, value: DisplayableObject.ObjectWidth) -> None: ...
    

class CorrectBeamElementsBuilder(Builder):
    def __init__(self) -> None: ...
    def IdentifyFailedElements(self, failedElement: typing.List[CAE.FEElement]) -> None: ...
    def DeleteDanglingNodesInElements(self, failedElement: typing.List[CAE.FEElement]) -> None: ...
    def DeleteFailedElements(self, failedElement: typing.List[CAE.FEElement]) -> None: ...
    def CorrectFailedElements(self, failedElement: CAE.FEElement, nodeToReplace: CAE.FENode, replacementNode: CAE.FENode) -> None: ...
    @property
    def ElemCheckOption(self) -> CAE.ModelCheck.CorrectBeamElementsBuilder.ElementToCheck: ...
    @ElemCheckOption.setter
    def ElemCheckOption(self, value: CAE.ModelCheck.CorrectBeamElementsBuilder.ElementToCheck) -> None: ...
    @property
    def ElementSelection(self) -> CAE.SelectElementsBuilder: ...
    @ElementSelection.setter
    def ElementSelection(self, value: CAE.SelectElementsBuilder) -> None: ...
    @property
    def NodeToReplace(self) -> CAE.SelectFENodeList: ...
    @NodeToReplace.setter
    def NodeToReplace(self, value: CAE.SelectFENodeList) -> None: ...
    @property
    def ReplacementNode(self) -> CAE.SelectFENodeList: ...
    @ReplacementNode.setter
    def ReplacementNode(self, value: CAE.SelectFENodeList) -> None: ...
    @property
    def CheckScopeOption(self) -> CAE.ModelCheck.CheckScope: ...
    @CheckScopeOption.setter
    def CheckScopeOption(self, value: CAE.ModelCheck.CheckScope) -> None: ...


    class ElementToCheck(enum.Enum):
        Displayed= 0
        Selected= 1
    

class CheckScope(enum.Enum):
    Displayed= 0
    Selected= 1


class AlignShellElementNormalBuilder(Builder):
    def __init__(self) -> None: ...
    def FindAllVisibleConnectedElements(self) -> typing.List[CAE.FEElement]: ...
    def DisplayNormals(self) -> None: ...
    def AlignNormals(self) -> typing.List[CAE.FEElement]: ...
    @property
    def ElementConnectScope(self) -> CAE.ModelCheck.AlignShellElementNormalBuilder.ConnectedElementScope: ...
    @ElementConnectScope.setter
    def ElementConnectScope(self, value: CAE.ModelCheck.AlignShellElementNormalBuilder.ConnectedElementScope) -> None: ...
    @property
    def ElementSelectionList(self) -> SelectTaggedObjectList: ...
    @ElementSelectionList.setter
    def ElementSelectionList(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def OrientMethod(self) -> CAE.ModelCheck.AlignShellElementNormalBuilder.OrientMethodType: ...
    @OrientMethod.setter
    def OrientMethod(self, value: CAE.ModelCheck.AlignShellElementNormalBuilder.OrientMethodType) -> None: ...
    @property
    def ReverseSeedNormal(self) -> bool: ...
    @ReverseSeedNormal.setter
    def ReverseSeedNormal(self, value: bool) -> None: ...
    @property
    def SeedElement(self) -> CAE.FEElement: ...
    @SeedElement.setter
    def SeedElement(self, value: CAE.FEElement) -> None: ...
    @property
    def UserSpecifiedConnectElements(self) -> CAE.SelectElementsBuilder: ...
    @UserSpecifiedConnectElements.setter
    def UserSpecifiedConnectElements(self, value: CAE.SelectElementsBuilder) -> None: ...
    @property
    def CheckScopeOption(self) -> CAE.ModelCheck.CheckScope: ...
    @CheckScopeOption.setter
    def CheckScopeOption(self, value: CAE.ModelCheck.CheckScope) -> None: ...


    class OrientMethodType(enum.Enum):
        UsingSeedElement= 0
        Automatic= 1
    

    class ConnectedElementScope(enum.Enum):
        SeedMesh= 0
        AllVisible= 1
        UserSpecified= 2
    

class AlignShellElementFirstEdgeBuilder(Builder):
    def __init__(self) -> None: ...
    def DisplayFirstEdges(self) -> None: ...
    @property
    def Direction(self) -> bool: ...
    @Direction.setter
    def Direction(self, value: bool) -> None: ...
    @property
    def ElemSelectionMethod(self) -> CAE.ModelCheck.AlignShellElementFirstEdgeBuilder.ElemSelectionMode: ...
    @ElemSelectionMethod.setter
    def ElemSelectionMethod(self, value: CAE.ModelCheck.AlignShellElementFirstEdgeBuilder.ElemSelectionMode) -> None: ...
    @property
    def Elements(self) -> CAE.SelectElementsBuilder: ...
    @Elements.setter
    def Elements(self, value: CAE.SelectElementsBuilder) -> None: ...
    @property
    def SeedEdge(self) -> CAE.SelectElementsBuilder: ...
    @SeedEdge.setter
    def SeedEdge(self, value: CAE.SelectElementsBuilder) -> None: ...


    class ElemSelectionMode(enum.Enum):
        ConnectedElementsinSeedMesh= 0
        AllVisibleConnectedShellElements= 1
        SelectedConnectedElements= 2
    

class AlignBeamElementDirectionBuilder(Builder):
    def __init__(self) -> None: ...
    def FindAllVisibleConnectedElements(self) -> typing.List[CAE.FEElement]: ...
    def DisplayDirections(self) -> None: ...
    def AlignDirections(self) -> typing.List[CAE.FEElement]: ...
    @property
    def ElementConnectScope(self) -> CAE.ModelCheck.AlignBeamElementDirectionBuilder.ConnectedElementScope: ...
    @ElementConnectScope.setter
    def ElementConnectScope(self, value: CAE.ModelCheck.AlignBeamElementDirectionBuilder.ConnectedElementScope) -> None: ...
    @property
    def ReverseSeedDirection(self) -> bool: ...
    @ReverseSeedDirection.setter
    def ReverseSeedDirection(self, value: bool) -> None: ...
    @property
    def SeedElement(self) -> CAE.FEElement: ...
    @SeedElement.setter
    def SeedElement(self, value: CAE.FEElement) -> None: ...
    @property
    def UserSpecifiedConnectElements(self) -> CAE.SelectElementsBuilder: ...
    @UserSpecifiedConnectElements.setter
    def UserSpecifiedConnectElements(self, value: CAE.SelectElementsBuilder) -> None: ...


    class ConnectedElementScope(enum.Enum):
        SeedMesh= 0
        AllVisible= 1
        UserSpecified= 2
    

