from ....NXOpen import *
from ...GeometricAnalysis import *

import typing
import enum

class XYZPlaneBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def AnchorOrigin(self) -> Point3d: ...
    @AnchorOrigin.setter
    def AnchorOrigin(self, value: Point3d) -> None: ...
    @property
    def AnchorXAxis(self) -> Vector3d: ...
    @AnchorXAxis.setter
    def AnchorXAxis(self, value: Vector3d) -> None: ...
    @property
    def AnchorYAxis(self) -> Vector3d: ...
    @AnchorYAxis.setter
    def AnchorYAxis(self, value: Vector3d) -> None: ...
    @property
    def IsNumberEnabled(self) -> bool: ...
    @IsNumberEnabled.setter
    def IsNumberEnabled(self, value: bool) -> None: ...
    @property
    def IsSpacingEnabled(self) -> bool: ...
    @IsSpacingEnabled.setter
    def IsSpacingEnabled(self, value: bool) -> None: ...
    @property
    def IsXEnabled(self) -> bool: ...
    @IsXEnabled.setter
    def IsXEnabled(self, value: bool) -> None: ...
    @property
    def IsYEnabled(self) -> bool: ...
    @IsYEnabled.setter
    def IsYEnabled(self, value: bool) -> None: ...
    @property
    def IsZEnabled(self) -> bool: ...
    @IsZEnabled.setter
    def IsZEnabled(self, value: bool) -> None: ...
    @property
    def Number(self) -> int: ...
    @Number.setter
    def Number(self, value: int) -> None: ...
    @property
    def Spacing(self) -> float: ...
    @Spacing.setter
    def Spacing(self, value: float) -> None: ...


class TriangularGridBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def Spacing(self) -> GeometricAnalysis.SectionAnalysis.GridSpacingBuilder: ...
    @Spacing.setter
    def Spacing(self, value: GeometricAnalysis.SectionAnalysis.GridSpacingBuilder) -> None: ...
    @property
    def SpecifiedPlane(self) -> GeometricAnalysis.SectionAnalysis.SectionPlaneBuilder: ...
    @SpecifiedPlane.setter
    def SpecifiedPlane(self, value: GeometricAnalysis.SectionAnalysis.SectionPlaneBuilder) -> None: ...
    @property
    def TriangularFrame(self) -> GeometricUtilities.TriangularFrameBuilder: ...
    @TriangularFrame.setter
    def TriangularFrame(self, value: GeometricUtilities.TriangularFrameBuilder) -> None: ...


class SectionPlaneBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def Origin(self) -> Point3d: ...
    @Origin.setter
    def Origin(self, value: Point3d) -> None: ...
    @property
    def Plane(self) -> GeometricAnalysis.SectionAnalysis.SectionPlaneBuilder.PlaneType: ...
    @Plane.setter
    def Plane(self, value: GeometricAnalysis.SectionAnalysis.SectionPlaneBuilder.PlaneType) -> None: ...
    @property
    def XAxis(self) -> Vector3d: ...
    @XAxis.setter
    def XAxis(self, value: Vector3d) -> None: ...
    @property
    def YAxis(self) -> Vector3d: ...
    @YAxis.setter
    def YAxis(self, value: Vector3d) -> None: ...


    class PlaneType(enum.Enum):
        Xc= 0
        Yc= 1
        Zc= 2
        View= 3
        Plane= 4
    

class SectionAnalysisExObject(GeometricAnalysis.AnalysisObject):
    def __init__(self) -> None: ...


class SectionAnalysisExBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Alignment(self) -> GeometricAnalysis.SectionAnalysis.SectionAnalysisExBuilder.AlignmentType: ...
    @Alignment.setter
    def Alignment(self, value: GeometricAnalysis.SectionAnalysis.SectionAnalysisExBuilder.AlignmentType) -> None: ...
    @property
    def CalculationMethod(self) -> GeometricAnalysis.SectionAnalysis.SectionAnalysisExBuilder.CalculationMethodType: ...
    @CalculationMethod.setter
    def CalculationMethod(self, value: GeometricAnalysis.SectionAnalysis.SectionAnalysisExBuilder.CalculationMethodType) -> None: ...
    @property
    def CombOptions(self) -> GeometricUtilities.CombOptionsBuilder: ...
    @CombOptions.setter
    def CombOptions(self, value: GeometricUtilities.CombOptionsBuilder) -> None: ...
    @property
    def CurveAligned(self) -> GeometricAnalysis.SectionAnalysis.CurveAlignedBuilder: ...
    @CurveAligned.setter
    def CurveAligned(self, value: GeometricAnalysis.SectionAnalysis.CurveAlignedBuilder) -> None: ...
    @property
    def Interactive(self) -> GeometricAnalysis.SectionAnalysis.InteractiveBuilder: ...
    @Interactive.setter
    def Interactive(self, value: GeometricAnalysis.SectionAnalysis.InteractiveBuilder) -> None: ...
    @property
    def IsShowInflectionPointsEnabled(self) -> bool: ...
    @IsShowInflectionPointsEnabled.setter
    def IsShowInflectionPointsEnabled(self, value: bool) -> None: ...
    @property
    def IsShowLengthEnabled(self) -> bool: ...
    @IsShowLengthEnabled.setter
    def IsShowLengthEnabled(self, value: bool) -> None: ...
    @property
    def IsShowPeakPointsEnabled(self) -> bool: ...
    @IsShowPeakPointsEnabled.setter
    def IsShowPeakPointsEnabled(self, value: bool) -> None: ...
    @property
    def Isoparametric(self) -> GeometricAnalysis.SectionAnalysis.IsoparametricBuilder: ...
    @Isoparametric.setter
    def Isoparametric(self, value: GeometricAnalysis.SectionAnalysis.IsoparametricBuilder) -> None: ...
    @property
    def NeedleDirection(self) -> GeometricAnalysis.SectionAnalysis.SectionAnalysisExBuilder.NeedleDirectionType: ...
    @NeedleDirection.setter
    def NeedleDirection(self, value: GeometricAnalysis.SectionAnalysis.SectionAnalysisExBuilder.NeedleDirectionType) -> None: ...
    @property
    def Output(self) -> GeometricAnalysis.SectionAnalysis.SectionAnalysisExBuilder.OutputType: ...
    @Output.setter
    def Output(self, value: GeometricAnalysis.SectionAnalysis.SectionAnalysisExBuilder.OutputType) -> None: ...
    @property
    def ParallelPlanes(self) -> GeometricAnalysis.SectionAnalysis.ParallelPlanesExBuilder: ...
    @ParallelPlanes.setter
    def ParallelPlanes(self, value: GeometricAnalysis.SectionAnalysis.ParallelPlanesExBuilder) -> None: ...
    @property
    def Placement(self) -> GeometricAnalysis.SectionAnalysis.SectionAnalysisExBuilder.PlacementType: ...
    @Placement.setter
    def Placement(self, value: GeometricAnalysis.SectionAnalysis.SectionAnalysisExBuilder.PlacementType) -> None: ...
    @property
    def Radial(self) -> GeometricAnalysis.SectionAnalysis.RadialBuilder: ...
    @Radial.setter
    def Radial(self, value: GeometricAnalysis.SectionAnalysis.RadialBuilder) -> None: ...
    @property
    def ScalingMethod(self) -> GeometricAnalysis.SectionAnalysis.SectionAnalysisExBuilder.ScalingMethodType: ...
    @ScalingMethod.setter
    def ScalingMethod(self, value: GeometricAnalysis.SectionAnalysis.SectionAnalysisExBuilder.ScalingMethodType) -> None: ...
    @property
    def SelectObject(self) -> SelectTaggedObjectList: ...
    @SelectObject.setter
    def SelectObject(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def SpecifyPoint(self) -> SelectPointList: ...
    @SpecifyPoint.setter
    def SpecifyPoint(self, value: SelectPointList) -> None: ...
    @property
    def XYZPlane(self) -> GeometricAnalysis.SectionAnalysis.XYZPlaneBuilder: ...
    @XYZPlane.setter
    def XYZPlane(self, value: GeometricAnalysis.SectionAnalysis.XYZPlaneBuilder) -> None: ...


    class ScalingMethodType(enum.Enum):
        Linear= 0
        Logarithmic= 1
    

    class PlacementType(enum.Enum):
        Uniform= 0
        ThroughPoints= 1
        BetweenPoints= 2
        Interactive= 3
    

    class OutputType(enum.Enum):
        AnalysisObject= 0
        SectionCurves= 1
        Both= 2
    

    class NeedleDirectionType(enum.Enum):
        Inside= 0
        Outside= 1
    

    class CalculationMethodType(enum.Enum):
        Curvature= 0
        RadiusofCurvature= 1
    

    class AlignmentType(enum.Enum):
        XYZPlane= 0
        ParallelPlanes= 1
        CurveAligned= 2
        Isoparametric= 3
        Radial= 4
    

class SectionAnalysisBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def CalculationMethod(self) -> GeometricAnalysis.SectionAnalysis.SectionAnalysisBuilder.CalculationMethodType: ...
    @CalculationMethod.setter
    def CalculationMethod(self, value: GeometricAnalysis.SectionAnalysis.SectionAnalysisBuilder.CalculationMethodType) -> None: ...
    @property
    def CircularGrid(self) -> GeometricAnalysis.SectionAnalysis.CircularGridBuilder: ...
    @CircularGrid.setter
    def CircularGrid(self, value: GeometricAnalysis.SectionAnalysis.CircularGridBuilder) -> None: ...
    @property
    def CombOptions(self) -> GeometricUtilities.CombOptionsBuilder: ...
    @CombOptions.setter
    def CombOptions(self, value: GeometricUtilities.CombOptionsBuilder) -> None: ...
    @property
    def NeedleDirection(self) -> GeometricAnalysis.SectionAnalysis.SectionAnalysisBuilder.NeedleDirectionType: ...
    @NeedleDirection.setter
    def NeedleDirection(self, value: GeometricAnalysis.SectionAnalysis.SectionAnalysisBuilder.NeedleDirectionType) -> None: ...
    @property
    def Output(self) -> GeometricAnalysis.SectionAnalysis.SectionAnalysisBuilder.OutputType: ...
    @Output.setter
    def Output(self, value: GeometricAnalysis.SectionAnalysis.SectionAnalysisBuilder.OutputType) -> None: ...
    @property
    def QuadrilateralGrid(self) -> GeometricAnalysis.SectionAnalysis.QuadrilateralGridBuilder: ...
    @QuadrilateralGrid.setter
    def QuadrilateralGrid(self, value: GeometricAnalysis.SectionAnalysis.QuadrilateralGridBuilder) -> None: ...
    @property
    def References(self) -> SelectTaggedObjectList: ...
    @References.setter
    def References(self, value: SelectTaggedObjectList) -> None: ...
    @property
    def ScalingMethod(self) -> GeometricAnalysis.SectionAnalysis.SectionAnalysisBuilder.ScalingMethodType: ...
    @ScalingMethod.setter
    def ScalingMethod(self, value: GeometricAnalysis.SectionAnalysis.SectionAnalysisBuilder.ScalingMethodType) -> None: ...
    @property
    def ShowInflectionPoints(self) -> bool: ...
    @ShowInflectionPoints.setter
    def ShowInflectionPoints(self, value: bool) -> None: ...
    @property
    def ShowPeakPoints(self) -> bool: ...
    @ShowPeakPoints.setter
    def ShowPeakPoints(self, value: bool) -> None: ...
    @property
    def ShowSectionLength(self) -> bool: ...
    @ShowSectionLength.setter
    def ShowSectionLength(self, value: bool) -> None: ...
    @property
    def TriangularGrid(self) -> GeometricAnalysis.SectionAnalysis.TriangularGridBuilder: ...
    @TriangularGrid.setter
    def TriangularGrid(self, value: GeometricAnalysis.SectionAnalysis.TriangularGridBuilder) -> None: ...
    @property
    def Type(self) -> GeometricAnalysis.SectionAnalysis.SectionAnalysisBuilder.Types: ...
    @Type.setter
    def Type(self, value: GeometricAnalysis.SectionAnalysis.SectionAnalysisBuilder.Types) -> None: ...


    class Types(enum.Enum):
        Parallel= 0
        Isoparametric= 1
        AlongCurve= 2
        Quadrilateral= 3
        Triangular= 4
        Circular= 5
    

    class ScalingMethodType(enum.Enum):
        Linear= 0
        Logarithmic= 1
    

    class OutputType(enum.Enum):
        AnalysisObject= 0
        SectionCurves= 1
        Both= 2
    

    class NeedleDirectionType(enum.Enum):
        Inside= 0
        Outside= 1
    

    class CalculationMethodType(enum.Enum):
        Curvature= 0
        RadiusofCurvature= 1
    

class RadialBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def IsSpacingEnabled(self) -> bool: ...
    @IsSpacingEnabled.setter
    def IsSpacingEnabled(self, value: bool) -> None: ...
    @property
    def Number(self) -> int: ...
    @Number.setter
    def Number(self, value: int) -> None: ...
    @property
    def Offset(self) -> float: ...
    @Offset.setter
    def Offset(self, value: float) -> None: ...
    @property
    def RotationAxis(self) -> GeometricAnalysis.SectionAnalysis.RadialBuilder.RotationAxisType: ...
    @RotationAxis.setter
    def RotationAxis(self, value: GeometricAnalysis.SectionAnalysis.RadialBuilder.RotationAxisType) -> None: ...
    @property
    def RotationVector(self) -> Vector3d: ...
    @RotationVector.setter
    def RotationVector(self, value: Vector3d) -> None: ...
    @property
    def Spacing(self) -> float: ...
    @Spacing.setter
    def Spacing(self, value: float) -> None: ...
    @property
    def SpecifiedRotationPoint(self) -> Point: ...
    @SpecifiedRotationPoint.setter
    def SpecifiedRotationPoint(self, value: Point) -> None: ...
    @property
    def StartPosition(self) -> SelectPoint: ...
    @StartPosition.setter
    def StartPosition(self, value: SelectPoint) -> None: ...


    class RotationAxisType(enum.Enum):
        Xc= 0
        Yc= 1
        Zc= 2
        View= 3
        ArbitraryVector= 4
    

class QuadrilateralGridBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def QuadrilateralFrame(self) -> GeometricUtilities.QuadrilateralFrameBuilder: ...
    @QuadrilateralFrame.setter
    def QuadrilateralFrame(self, value: GeometricUtilities.QuadrilateralFrameBuilder) -> None: ...
    @property
    def Spacing(self) -> GeometricAnalysis.SectionAnalysis.GridSpacingBuilder: ...
    @Spacing.setter
    def Spacing(self, value: GeometricAnalysis.SectionAnalysis.GridSpacingBuilder) -> None: ...
    @property
    def SpecifiedPlane(self) -> GeometricAnalysis.SectionAnalysis.SectionPlaneBuilder: ...
    @SpecifiedPlane.setter
    def SpecifiedPlane(self, value: GeometricAnalysis.SectionAnalysis.SectionPlaneBuilder) -> None: ...


class ParallelPlanesExBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def IsNumberEnabled(self) -> bool: ...
    @IsNumberEnabled.setter
    def IsNumberEnabled(self, value: bool) -> None: ...
    @property
    def IsSpacingEnabled(self) -> bool: ...
    @IsSpacingEnabled.setter
    def IsSpacingEnabled(self, value: bool) -> None: ...
    @property
    def Number(self) -> int: ...
    @Number.setter
    def Number(self, value: int) -> None: ...
    @property
    def Offset(self) -> float: ...
    @Offset.setter
    def Offset(self, value: float) -> None: ...
    @property
    def Spacing(self) -> float: ...
    @Spacing.setter
    def Spacing(self, value: float) -> None: ...
    @property
    def SpecifiedPlane(self) -> GeometricAnalysis.SectionAnalysis.SectionPlaneBuilder: ...
    @SpecifiedPlane.setter
    def SpecifiedPlane(self, value: GeometricAnalysis.SectionAnalysis.SectionPlaneBuilder) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class IsoparametricBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def IsSpacingEnabled(self) -> bool: ...
    @IsSpacingEnabled.setter
    def IsSpacingEnabled(self, value: bool) -> None: ...
    @property
    def IsUEnabled(self) -> bool: ...
    @IsUEnabled.setter
    def IsUEnabled(self, value: bool) -> None: ...
    @property
    def IsVEnabled(self) -> bool: ...
    @IsVEnabled.setter
    def IsVEnabled(self, value: bool) -> None: ...
    @property
    def Number(self) -> int: ...
    @Number.setter
    def Number(self, value: int) -> None: ...
    @property
    def Spacing(self) -> float: ...
    @Spacing.setter
    def Spacing(self, value: float) -> None: ...


class InteractiveBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def InteractiveSection(self) -> GeometricUtilities.InteractiveSectionBuilder: ...
    @InteractiveSection.setter
    def InteractiveSection(self, value: GeometricUtilities.InteractiveSectionBuilder) -> None: ...
    @property
    def IsCutInfiniteEnabled(self) -> bool: ...
    @IsCutInfiniteEnabled.setter
    def IsCutInfiniteEnabled(self, value: bool) -> None: ...


class GridSpacingBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def BoundSections1(self) -> bool: ...
    @BoundSections1.setter
    def BoundSections1(self, value: bool) -> None: ...
    @property
    def BoundSections2(self) -> bool: ...
    @BoundSections2.setter
    def BoundSections2(self, value: bool) -> None: ...
    @property
    def Interval1(self) -> float: ...
    @Interval1.setter
    def Interval1(self, value: float) -> None: ...
    @property
    def Interval2(self) -> float: ...
    @Interval2.setter
    def Interval2(self, value: float) -> None: ...
    @property
    def LockInterval1(self) -> bool: ...
    @LockInterval1.setter
    def LockInterval1(self, value: bool) -> None: ...
    @property
    def LockInterval2(self) -> bool: ...
    @LockInterval2.setter
    def LockInterval2(self, value: bool) -> None: ...
    @property
    def SectionNumber1(self) -> int: ...
    @SectionNumber1.setter
    def SectionNumber1(self, value: int) -> None: ...
    @property
    def SectionNumber2(self) -> int: ...
    @SectionNumber2.setter
    def SectionNumber2(self, value: int) -> None: ...


class CurveAlignedBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def Curves(self) -> ScCollector: ...
    @Curves.setter
    def Curves(self, value: ScCollector) -> None: ...
    @property
    def IsSpacingEnabled(self) -> bool: ...
    @IsSpacingEnabled.setter
    def IsSpacingEnabled(self, value: bool) -> None: ...
    @property
    def Number(self) -> int: ...
    @Number.setter
    def Number(self, value: int) -> None: ...
    @property
    def Offset(self) -> float: ...
    @Offset.setter
    def Offset(self, value: float) -> None: ...
    @property
    def Spacing(self) -> float: ...
    @Spacing.setter
    def Spacing(self, value: float) -> None: ...
    @property
    def SpecifiedPlane(self) -> GeometricAnalysis.SectionAnalysis.SectionPlaneBuilder: ...
    @SpecifiedPlane.setter
    def SpecifiedPlane(self, value: GeometricAnalysis.SectionAnalysis.SectionPlaneBuilder) -> None: ...
    @property
    def UseProjectedCurve(self) -> bool: ...
    @UseProjectedCurve.setter
    def UseProjectedCurve(self, value: bool) -> None: ...


class CircularGridBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def CircularFrame(self) -> GeometricUtilities.CircularFrameBuilder: ...
    @CircularFrame.setter
    def CircularFrame(self, value: GeometricUtilities.CircularFrameBuilder) -> None: ...
    @property
    def Spacing(self) -> GeometricAnalysis.SectionAnalysis.GridSpacingBuilder: ...
    @Spacing.setter
    def Spacing(self, value: GeometricAnalysis.SectionAnalysis.GridSpacingBuilder) -> None: ...
    @property
    def SpecifiedPlane(self) -> GeometricAnalysis.SectionAnalysis.SectionPlaneBuilder: ...
    @SpecifiedPlane.setter
    def SpecifiedPlane(self, value: GeometricAnalysis.SectionAnalysis.SectionPlaneBuilder) -> None: ...


