from ...NXOpen import *

import typing
import enum

class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class MenuButtonEvent(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    def GetMenuAncestors(self) -> str: ...
    @property
    def ActiveButton(self) -> MenuBar.MenuButton: ...
    @ActiveButton.setter
    def ActiveButton(self, value: MenuBar.MenuButton) -> None: ...
    @property
    def ApplicationId(self) -> int: ...
    @ApplicationId.setter
    def ApplicationId(self, value: int) -> None: ...
    @property
    def MenuBarName(self) -> str: ...
    @MenuBarName.setter
    def MenuBarName(self, value: str) -> None: ...


class MenuButton(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def ButtonAvailability(self) -> MenuBar.MenuButton.AvailabilityStatus: ...
    @ButtonAvailability.setter
    def ButtonAvailability(self, value: MenuBar.MenuButton.AvailabilityStatus) -> None: ...
    @property
    def ButtonId(self) -> int: ...
    @ButtonId.setter
    def ButtonId(self, value: int) -> None: ...
    @property
    def ButtonName(self) -> str: ...
    @ButtonName.setter
    def ButtonName(self, value: str) -> None: ...
    @property
    def ButtonSensitivity(self) -> MenuBar.MenuButton.SensitivityStatus: ...
    @ButtonSensitivity.setter
    def ButtonSensitivity(self, value: MenuBar.MenuButton.SensitivityStatus) -> None: ...
    @property
    def ButtonType(self) -> MenuBar.MenuButton.Type: ...
    @ButtonType.setter
    def ButtonType(self, value: MenuBar.MenuButton.Type) -> None: ...
    @property
    def ButtonTypeName(self) -> str: ...
    @ButtonTypeName.setter
    def ButtonTypeName(self, value: str) -> None: ...
    @property
    def ToggleStatus(self) -> MenuBar.MenuButton.Toggle: ...
    @ToggleStatus.setter
    def ToggleStatus(self, value: MenuBar.MenuButton.Toggle) -> None: ...


    class Type(enum.Enum):
        CascadeButton= 0
        PushButton= 1
        ToggleButton= 2
        Separator= 3
        ApplicationButton= 4
        NullButton= 5
    

    class Toggle(enum.Enum):
        On= 0
        Off= 1
    

    class SensitivityStatus(enum.Enum):
        Sensitive= 0
        Insensitive= 1
    

    class AvailabilityStatus(enum.Enum):
        Available= 0
        Unavailable= 1
    

class MenuBarManager(Utilities.NXRemotableObject):
    def __init__(self, owner: UI) -> None: ...
    def AddMenuAction(self, name: str, actionCallback: MenuBar.MenuBarManager.ActionCallback) -> None: ...
    def GetButtonFromName(self, name: str) -> MenuBar.MenuButton: ...
    @typing.overload
    def RegisterApplication(self, name: str, initializeCallback: MenuBar.MenuBarManager.InitializeMenuApplication, enterCallback: MenuBar.MenuBarManager.EnterMenuApplication, exitCallback: MenuBar.MenuBarManager.ExitMenuApplication, supportsDrawings: bool, supportsDesignInContext: bool, supportsUndo: bool) -> int: ...
    @typing.overload
    def RegisterApplication(self, name: str, initializeCallback: MenuBar.MenuBarManager.InitializeMenuApplication, enterCallback: MenuBar.MenuBarManager.EnterMenuApplication, exitCallback: MenuBar.MenuBarManager.ExitMenuApplication, application: MenuBar.ApplicationProperties) -> int: ...
    def RegisterConfigureContextMenuCallback(self, name: str, description: str, configurePopupMenu: MenuBar.MenuBarManager.ConfigureContextMenu) -> int: ...
    def UnregisterConfigureContextMenuCallback(self, id: int) -> None: ...
    def NewApplicationProperties(self) -> MenuBar.ApplicationProperties: ...
    def RegisterApplicationSwitchCallback(self, switchCallback: MenuBar.MenuBarManager.ApplicationSwitchNotify) -> int: ...
    def UnregisterApplicationSwitchCallback(self, id: int) -> None: ...
    def Tag(self) -> Tag: ...



    class SwitchReason(enum.Enum):
        Enter= 0
        TaskEnter= 1
    

    

    

    

    

    class CallbackStatus(enum.Enum):
        Continue= 0
        Cancel= 1
        OverrideStandard= 2
        Warning= 3
        Error= 4
    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

class ContextMenuProperties(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def Context(self) -> str: ...
    @Context.setter
    def Context(self, value: str) -> None: ...
    @property
    def Location(self) -> str: ...
    @Location.setter
    def Location(self, value: str) -> None: ...


class ContextMenuEntry(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def EntryType(self) -> MenuBar.ContextMenuEntry.Type: ...
    @EntryType.setter
    def EntryType(self, value: MenuBar.ContextMenuEntry.Type) -> None: ...
    @property
    def IsDefault(self) -> bool: ...
    @IsDefault.setter
    def IsDefault(self, value: bool) -> None: ...
    @property
    def IsHidden(self) -> bool: ...
    @IsHidden.setter
    def IsHidden(self, value: bool) -> None: ...
    @property
    def IsSensitive(self) -> bool: ...
    @IsSensitive.setter
    def IsSensitive(self, value: bool) -> None: ...
    @property
    def Label(self) -> str: ...
    @Label.setter
    def Label(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...


    class Type(enum.Enum):
        Submenu= 0
        PushButton= 1
        ToggleButton= 2
        Separator= 3
        Label= 4
    

class ContextMenu(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def GetEntry(self, index: int) -> MenuBar.ContextMenuEntry: ...
    def GetSubmenu(self, index: int) -> MenuBar.ContextMenu: ...
    def HasEntryWithName(self, name: str) -> bool: ...
    def GetEntryWithName(self, name: str) -> MenuBar.ContextMenuEntry: ...
    def GetIndexOfEntry(self, entry: MenuBar.ContextMenuEntry) -> int: ...
    def AddMenuButton(self, button: MenuBar.MenuButton, index: int) -> MenuBar.ContextMenuEntry: ...
    def AddSeparator(self, index: int) -> None: ...
    def AddMenuLabel(self, label: str, index: int) -> MenuBar.ContextMenuEntry: ...
    def AddSubmenu(self, label: str, index: int) -> MenuBar.ContextMenu: ...
    def SetDefaultEntry(self, entry: MenuBar.ContextMenuEntry) -> None: ...
    def HideEntry(self, entry: MenuBar.ContextMenuEntry) -> None: ...
    def MoveEntry(self, entry: MenuBar.ContextMenuEntry, index: int) -> None: ...
    def FreeResource(self) -> None: ...
    @property
    def NumberOfEntries(self) -> int: ...
    @NumberOfEntries.setter
    def NumberOfEntries(self, value: int) -> None: ...


class ApplicationProperties(TransientObject):
    def __init__(self, ptr: int) -> None: ...
    def SupportsDrawings(self, supportsDrawings: bool) -> None: ...
    def SupportsUndoWithinApplication(self, supportsUndo: bool) -> None: ...
    def AllowsMultipleWindowDesigns(self, allowsMultipleWindowDesigns: bool) -> None: ...
    def AllowsMultipleWindowViews(self, allowsMultipleWindowViews: bool) -> None: ...
    def AllowsUndoOverApplicationChange(self, allowsUndoOverApplicationChange: bool) -> None: ...
    def FreeResource(self) -> None: ...


