from . import Tables
from . import Geometry
from ...NXOpen import *

import typing
import enum

class ZoneOrigin(enum.Enum):
    BottomRight= 0
    TopLeft= 1
    TopRight= 2
    BottomLeft= 3


class ViewOperations(Utilities.NXRemotableObject):
    def __init__(self, owner: Diagramming.SheetManager) -> None: ...
    def Fit(self, sheet: Diagramming.Sheet) -> None: ...
    def FitToElements(self, sheet: Diagramming.Sheet, elements: typing.List[Diagramming.SheetElement]) -> None: ...
    def SetViewport(self, sheet: Diagramming.Sheet, x: float, y: float, width: float, height: float) -> None: ...
    def Scale(self, sheet: Diagramming.Sheet, scale: float) -> None: ...
    def Tag(self) -> Tag: ...



class VerticalCenteringMarkType(enum.Enum):
    None_= 0
    BottomArrow= 1
    TopArrow= 2
    BottomandTopArrow= 3
    BottomandTopLine= 4


class TrimmingMarkStyleType(enum.Enum):
    Triangle= 0
    Corner= 1


class TitleBlockCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.TitleBlock]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateDefineTitleBlockBuilder(self, titleBlock: Diagramming.TitleBlock) -> Diagramming.DefineTitleBlockBuilder: ...
    def CreatePopulateTitleBlockBuilder(self, titleBlocks: typing.List[Diagramming.TitleBlock]) -> Diagramming.PopulateTitleBlockBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.TitleBlock: ...
    def Tag(self) -> Tag: ...



class TitleBlockCellBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[Diagramming.TitleBlockCellBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: Diagramming.TitleBlockCellBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: Diagramming.TitleBlockCellBuilder) -> int: ...
    def FindItem(self, index: int) -> Diagramming.TitleBlockCellBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: Diagramming.TitleBlockCellBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: Diagramming.TitleBlockCellBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[Diagramming.TitleBlockCellBuilder]: ...
    def SetContents(self, objects: typing.List[Diagramming.TitleBlockCellBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: Diagramming.TitleBlockCellBuilder, object2: Diagramming.TitleBlockCellBuilder) -> None: ...
    def Insert(self, location: int, object: Diagramming.TitleBlockCellBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class TitleBlockCellBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def Label(self) -> str: ...
    @Label.setter
    def Label(self, value: str) -> None: ...
    @property
    def Lock(self) -> bool: ...
    @Lock.setter
    def Lock(self, value: bool) -> None: ...
    @property
    def Value(self) -> str: ...
    @Value.setter
    def Value(self, value: str) -> None: ...


class TitleBlock(NXObject):
    def __init__(self) -> None: ...


class TextStyleBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def TextAlignment(self) -> Diagramming.TextStyleBuilder.TextAlignmentType: ...
    @TextAlignment.setter
    def TextAlignment(self, value: Diagramming.TextStyleBuilder.TextAlignmentType) -> None: ...
    @property
    def TextAllowWrapping(self) -> bool: ...
    @TextAllowWrapping.setter
    def TextAllowWrapping(self, value: bool) -> None: ...
    @property
    def TextAutoFit(self) -> Diagramming.TextStyleBuilder.TextAutoFitType: ...
    @TextAutoFit.setter
    def TextAutoFit(self, value: Diagramming.TextStyleBuilder.TextAutoFitType) -> None: ...
    @property
    def TextColorFontWidth(self) -> TextColorFontWidthBuilder: ...
    @TextColorFontWidth.setter
    def TextColorFontWidth(self, value: TextColorFontWidthBuilder) -> None: ...
    @property
    def TextHeight(self) -> float: ...
    @TextHeight.setter
    def TextHeight(self, value: float) -> None: ...
    @property
    def TextOverlined(self) -> bool: ...
    @TextOverlined.setter
    def TextOverlined(self, value: bool) -> None: ...
    @property
    def TextUnderlined(self) -> bool: ...
    @TextUnderlined.setter
    def TextUnderlined(self, value: bool) -> None: ...
    @property
    def TruncationMode(self) -> Diagramming.TextStyleBuilder.TruncationModes: ...
    @TruncationMode.setter
    def TruncationMode(self, value: Diagramming.TextStyleBuilder.TruncationModes) -> None: ...


    class TruncationModes(enum.Enum):
        None_= 0
        Trim= 1
        Suffix= 2
    

    class TextAutoFitType(enum.Enum):
        None_= 0
        ResizeOutline= 1
        ShrinkText= 2
    

    class TextAlignmentType(enum.Enum):
        Left= 0
        Center= 1
        Right= 2
    

class SmartDiagrammingManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Part) -> None: ...
    def CreateReferenceGeometryBuilder(self, referenceGeometry: Diagramming.ReferenceGeometry) -> Diagramming.ReferenceGeometryBuilder: ...
    def Tag(self) -> Tag: ...



class SheetZoneSettingsBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def ContinueZoneIndexingAcrossSheets(self) -> bool: ...
    @ContinueZoneIndexingAcrossSheets.setter
    def ContinueZoneIndexingAcrossSheets(self, value: bool) -> None: ...
    @property
    def CornerZoneModification(self) -> float: ...
    @CornerZoneModification.setter
    def CornerZoneModification(self, value: float) -> None: ...
    @property
    def CreateZoneLabels(self) -> bool: ...
    @CreateZoneLabels.setter
    def CreateZoneLabels(self, value: bool) -> None: ...
    @property
    def CreateZoneMarkings(self) -> bool: ...
    @CreateZoneMarkings.setter
    def CreateZoneMarkings(self, value: bool) -> None: ...
    @property
    def CreateZones(self) -> bool: ...
    @CreateZones.setter
    def CreateZones(self, value: bool) -> None: ...
    @property
    def HorizontalSize(self) -> float: ...
    @HorizontalSize.setter
    def HorizontalSize(self, value: float) -> None: ...
    @property
    def LabelColor(self) -> int: ...
    @LabelColor.setter
    def LabelColor(self, value: int) -> None: ...
    @property
    def LabelFont(self) -> int: ...
    @LabelFont.setter
    def LabelFont(self, value: int) -> None: ...
    @property
    def LabelHeight(self) -> float: ...
    @LabelHeight.setter
    def LabelHeight(self, value: float) -> None: ...
    @property
    def LabelItalicized(self) -> bool: ...
    @LabelItalicized.setter
    def LabelItalicized(self, value: bool) -> None: ...
    @property
    def LabelWidth(self) -> int: ...
    @LabelWidth.setter
    def LabelWidth(self, value: int) -> None: ...
    @property
    def LabelsToSkip(self) -> str: ...
    @LabelsToSkip.setter
    def LabelsToSkip(self, value: str) -> None: ...
    @property
    def MarkingHeight(self) -> float: ...
    @MarkingHeight.setter
    def MarkingHeight(self, value: float) -> None: ...
    @property
    def MarkingLineColorWidth(self) -> LineColorFontWidthBuilder: ...
    @MarkingLineColorWidth.setter
    def MarkingLineColorWidth(self, value: LineColorFontWidthBuilder) -> None: ...
    @property
    def Origin(self) -> Diagramming.ZoneOrigin: ...
    @Origin.setter
    def Origin(self, value: Diagramming.ZoneOrigin) -> None: ...
    @property
    def VerticalSize(self) -> float: ...
    @VerticalSize.setter
    def VerticalSize(self, value: float) -> None: ...


class SheetTemplateBuilder(Builder):
    def __init__(self) -> None: ...
    @property
    def Sheet(self) -> Diagramming.SheetBuilder: ...
    @Sheet.setter
    def Sheet(self, value: Diagramming.SheetBuilder) -> None: ...
    @property
    def SheetSize(self) -> Diagramming.SheetSizeBuilder: ...
    @SheetSize.setter
    def SheetSize(self, value: Diagramming.SheetSizeBuilder) -> None: ...


class SheetSizeBuilder(Builder):
    def __init__(self) -> None: ...


class SheetMarginSettingsBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def BottomTrimmedMargin(self) -> float: ...
    @BottomTrimmedMargin.setter
    def BottomTrimmedMargin(self, value: float) -> None: ...
    @property
    def BottomUntrimmedMargin(self) -> float: ...
    @BottomUntrimmedMargin.setter
    def BottomUntrimmedMargin(self, value: float) -> None: ...
    @property
    def CreateUntrimmedMargins(self) -> bool: ...
    @CreateUntrimmedMargins.setter
    def CreateUntrimmedMargins(self, value: bool) -> None: ...
    @property
    def LeftTrimmedMargin(self) -> float: ...
    @LeftTrimmedMargin.setter
    def LeftTrimmedMargin(self, value: float) -> None: ...
    @property
    def LeftUntrimmedMargin(self) -> float: ...
    @LeftUntrimmedMargin.setter
    def LeftUntrimmedMargin(self, value: float) -> None: ...
    @property
    def MarginLineColorFontWidth(self) -> LineColorFontWidthBuilder: ...
    @MarginLineColorFontWidth.setter
    def MarginLineColorFontWidth(self, value: LineColorFontWidthBuilder) -> None: ...
    @property
    def RightTrimmedMargin(self) -> float: ...
    @RightTrimmedMargin.setter
    def RightTrimmedMargin(self, value: float) -> None: ...
    @property
    def RightUntrimmedMargin(self) -> float: ...
    @RightUntrimmedMargin.setter
    def RightUntrimmedMargin(self, value: float) -> None: ...
    @property
    def TopTrimmedMargin(self) -> float: ...
    @TopTrimmedMargin.setter
    def TopTrimmedMargin(self, value: float) -> None: ...
    @property
    def TopUntrimmedMargin(self) -> float: ...
    @TopUntrimmedMargin.setter
    def TopUntrimmedMargin(self, value: float) -> None: ...


class SheetManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Session) -> None: ...
    def OpenSheet(self, sheet: Diagramming.Sheet) -> None: ...
    def Tag(self) -> Tag: ...

    @property
    def ViewOperations(self) -> Diagramming.ViewOperations: ...
    @ViewOperations.setter
    def ViewOperations(self, value: Diagramming.ViewOperations) -> None: ...
    @property
    def ActiveSheet(self) -> Diagramming.Sheet: ...
    @ActiveSheet.setter
    def ActiveSheet(self, value: Diagramming.Sheet) -> None: ...


class SheetElementBuilder(Diagramming.BaseObjectBuilder):
    def __init__(self) -> None: ...
    def GetMinNodeSize(self, sizeValues: float) -> None: ...
    def SetMinNodeSize(self, sizeValues: float) -> None: ...
    def GetAllowedTransformations(self, isAllowedTranslation: bool, isAllowedRotation: bool, isAllowedScale: bool, isAllowedShear: bool) -> None: ...
    def SetOwningSheet(self, owningSheet: Diagramming.Sheet) -> None: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> None: ...
    @property
    def HeightPolicy(self) -> Diagramming.DiagrammingSizingpolicy: ...
    @HeightPolicy.setter
    def HeightPolicy(self, value: Diagramming.DiagrammingSizingpolicy) -> None: ...
    @property
    def Internal(self) -> bool: ...
    @Internal.setter
    def Internal(self, value: bool) -> None: ...
    @property
    def Label(self) -> Diagramming.Annotation: ...
    @Label.setter
    def Label(self, value: Diagramming.Annotation) -> None: ...
    @property
    def LabelName(self) -> str: ...
    @LabelName.setter
    def LabelName(self, value: str) -> None: ...
    @property
    def Location(self) -> Diagramming.LocationBuilder: ...
    @Location.setter
    def Location(self, value: Diagramming.LocationBuilder) -> None: ...
    @property
    def LocationStyle(self) -> Diagramming.DiagrammingLocationstyle: ...
    @LocationStyle.setter
    def LocationStyle(self, value: Diagramming.DiagrammingLocationstyle) -> None: ...
    @property
    def MirrorX(self) -> bool: ...
    @MirrorX.setter
    def MirrorX(self, value: bool) -> None: ...
    @property
    def MirrorY(self) -> bool: ...
    @MirrorY.setter
    def MirrorY(self, value: bool) -> None: ...
    @property
    def Owner(self) -> Diagramming.SheetElement: ...
    @Owner.setter
    def Owner(self, value: Diagramming.SheetElement) -> None: ...
    @property
    def OwningSheet(self) -> Diagramming.Sheet: ...
    @OwningSheet.setter
    def OwningSheet(self, value: Diagramming.Sheet) -> None: ...
    @property
    def ResizeOption(self) -> Diagramming.SheetElementBuilder.ResizeOptionType: ...
    @ResizeOption.setter
    def ResizeOption(self, value: Diagramming.SheetElementBuilder.ResizeOptionType) -> None: ...
    @property
    def Rotation(self) -> float: ...
    @Rotation.setter
    def Rotation(self, value: float) -> None: ...
    @property
    def SourceElement(self) -> Diagramming.SheetElement: ...
    @SourceElement.setter
    def SourceElement(self, value: Diagramming.SheetElement) -> None: ...
    @property
    def UpToDate(self) -> bool: ...
    @UpToDate.setter
    def UpToDate(self, value: bool) -> None: ...
    @property
    def Visible(self) -> bool: ...
    @Visible.setter
    def Visible(self, value: bool) -> None: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> None: ...
    @property
    def WidthPolicy(self) -> Diagramming.DiagrammingSizingpolicy: ...
    @WidthPolicy.setter
    def WidthPolicy(self, value: Diagramming.DiagrammingSizingpolicy) -> None: ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> None: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> None: ...
    @property
    def ZDepth(self) -> int: ...
    @ZDepth.setter
    def ZDepth(self, value: int) -> None: ...


    class ResizeOptionType(enum.Enum):
        AnyDirection= 0
        OnAnchor= 1
        SameRatio= 2
        SameRationOnCorner= 3
        SameRatioOnEdge= 4
    

class SheetElement(Diagramming.BaseObject):
    def __init__(self) -> None: ...


class SheetCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.Sheet]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateSheetBuilder(self, sheet: Diagramming.Sheet) -> Diagramming.SheetBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.Sheet: ...
    def Tag(self) -> Tag: ...



class SheetBuilder(Diagramming.BaseObjectBuilder):
    def __init__(self) -> None: ...
    def GetFeatures(self) -> typing.List[Diagramming.SheetElement]: ...
    def GetSheetElements(self) -> typing.List[Diagramming.SheetElement]: ...
    def GetSize(self, height: float, width: float) -> None: ...
    def SetSize(self, height: float, width: float) -> None: ...
    @property
    def AllowJumpers(self) -> bool: ...
    @AllowJumpers.setter
    def AllowJumpers(self, value: bool) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def JumperType(self) -> Diagramming.DiagrammingJumpertype: ...
    @JumperType.setter
    def JumperType(self, value: Diagramming.DiagrammingJumpertype) -> None: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> None: ...
    @property
    def PaxFileName(self) -> str: ...
    @PaxFileName.setter
    def PaxFileName(self, value: str) -> None: ...
    @property
    def PresentationName(self) -> str: ...
    @PresentationName.setter
    def PresentationName(self, value: str) -> None: ...
    @property
    def ToolTip(self) -> str: ...
    @ToolTip.setter
    def ToolTip(self, value: str) -> None: ...
    @property
    def Units(self) -> Unit: ...
    @Units.setter
    def Units(self, value: Unit) -> None: ...
    @property
    def UpdatePAXFile(self) -> bool: ...
    @UpdatePAXFile.setter
    def UpdatePAXFile(self, value: bool) -> None: ...


class SheetBorderSettingsBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...
    @property
    def ArrowAngle(self) -> float: ...
    @ArrowAngle.setter
    def ArrowAngle(self, value: float) -> None: ...
    @property
    def ArrowDirection(self) -> Diagramming.ArrowDirectionType: ...
    @ArrowDirection.setter
    def ArrowDirection(self, value: Diagramming.ArrowDirectionType) -> None: ...
    @property
    def ArrowHeadTail(self) -> float: ...
    @ArrowHeadTail.setter
    def ArrowHeadTail(self, value: float) -> None: ...
    @property
    def ArrowLength(self) -> float: ...
    @ArrowLength.setter
    def ArrowLength(self, value: float) -> None: ...
    @property
    def ArrowStyle(self) -> Diagramming.ArrowStyleType: ...
    @ArrowStyle.setter
    def ArrowStyle(self, value: Diagramming.ArrowStyleType) -> None: ...
    @property
    def BorderLineWidth(self) -> float: ...
    @BorderLineWidth.setter
    def BorderLineWidth(self, value: float) -> None: ...
    @property
    def CenteringMarkLength(self) -> float: ...
    @CenteringMarkLength.setter
    def CenteringMarkLength(self, value: float) -> None: ...
    @property
    def CenteringMarksColorWidth(self) -> LineColorFontWidthBuilder: ...
    @CenteringMarksColorWidth.setter
    def CenteringMarksColorWidth(self, value: LineColorFontWidthBuilder) -> None: ...
    @property
    def CenteringMarksExtension(self) -> float: ...
    @CenteringMarksExtension.setter
    def CenteringMarksExtension(self, value: float) -> None: ...
    @property
    def CenteringMarksHorizontal(self) -> Diagramming.HorizontalCenteringMarkType: ...
    @CenteringMarksHorizontal.setter
    def CenteringMarksHorizontal(self, value: Diagramming.HorizontalCenteringMarkType) -> None: ...
    @property
    def CenteringMarksVertical(self) -> Diagramming.VerticalCenteringMarkType: ...
    @CenteringMarksVertical.setter
    def CenteringMarksVertical(self, value: Diagramming.VerticalCenteringMarkType) -> None: ...
    @property
    def CreateBorders(self) -> bool: ...
    @CreateBorders.setter
    def CreateBorders(self, value: bool) -> None: ...
    @property
    def CreateTrimmingMarks(self) -> bool: ...
    @CreateTrimmingMarks.setter
    def CreateTrimmingMarks(self, value: bool) -> None: ...
    @property
    def DisplaySheetSizeInBorder(self) -> bool: ...
    @DisplaySheetSizeInBorder.setter
    def DisplaySheetSizeInBorder(self, value: bool) -> None: ...
    @property
    def DistanceFromInnerBorder(self) -> float: ...
    @DistanceFromInnerBorder.setter
    def DistanceFromInnerBorder(self, value: float) -> None: ...
    @property
    def InnerLineCFW(self) -> LineColorFontWidthBuilder: ...
    @InnerLineCFW.setter
    def InnerLineCFW(self, value: LineColorFontWidthBuilder) -> None: ...
    @property
    def Method(self) -> Diagramming.Method: ...
    @Method.setter
    def Method(self, value: Diagramming.Method) -> None: ...
    @property
    def OuterLineCFW(self) -> LineColorFontWidthBuilder: ...
    @OuterLineCFW.setter
    def OuterLineCFW(self, value: LineColorFontWidthBuilder) -> None: ...
    @property
    def TrimmingMarkColor(self) -> NXColor: ...
    @TrimmingMarkColor.setter
    def TrimmingMarkColor(self, value: NXColor) -> None: ...
    @property
    def TrimmingMarkLength(self) -> float: ...
    @TrimmingMarkLength.setter
    def TrimmingMarkLength(self, value: float) -> None: ...
    @property
    def TrimmingMarkStyle(self) -> Diagramming.TrimmingMarkStyleType: ...
    @TrimmingMarkStyle.setter
    def TrimmingMarkStyle(self, value: Diagramming.TrimmingMarkStyleType) -> None: ...
    @property
    def TrimmingMarkWidth(self) -> float: ...
    @TrimmingMarkWidth.setter
    def TrimmingMarkWidth(self, value: float) -> None: ...


class SheetBordersAndZonesCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.SheetBordersAndZones]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def FindObject(self, name: str) -> Diagramming.SheetBordersAndZones: ...
    def CreateSheetBordersAndZonesBuilder(self, bordersAndZones: Diagramming.SheetBordersAndZones) -> Diagramming.SheetBordersAndZonesBuilder: ...
    def Tag(self) -> Tag: ...



    class ZoneOrigin(enum.Enum):
        BottomRight= 0
        TopLeft= 1
        TopRight= 2
        BottomLeft= 3
    

    class ZoneMethod(enum.Enum):
        None_= 0
        Standard= 1
        Custom= 2
    

class SheetBordersAndZonesBuilder(Builder):
    def __init__(self) -> None: ...
    def SetOwningSheet(self, owningSheet: Diagramming.Sheet) -> None: ...
    @property
    def BottomMargin(self) -> float: ...
    @BottomMargin.setter
    def BottomMargin(self, value: float) -> None: ...
    @property
    def CenteringMarkExtension(self) -> float: ...
    @CenteringMarkExtension.setter
    def CenteringMarkExtension(self, value: float) -> None: ...
    @property
    def CreateBorders(self) -> bool: ...
    @CreateBorders.setter
    def CreateBorders(self, value: bool) -> None: ...
    @property
    def CreateTrimmingMarks(self) -> bool: ...
    @CreateTrimmingMarks.setter
    def CreateTrimmingMarks(self, value: bool) -> None: ...
    @property
    def CreateZoneLabels(self) -> bool: ...
    @CreateZoneLabels.setter
    def CreateZoneLabels(self, value: bool) -> None: ...
    @property
    def CreateZoneMarking(self) -> bool: ...
    @CreateZoneMarking.setter
    def CreateZoneMarking(self, value: bool) -> None: ...
    @property
    def HorizontalCenteringMark(self) -> Diagramming.SheetBordersAndZonesBuilder.HorizontalCenteringMarkType: ...
    @HorizontalCenteringMark.setter
    def HorizontalCenteringMark(self, value: Diagramming.SheetBordersAndZonesBuilder.HorizontalCenteringMarkType) -> None: ...
    @property
    def HorizontalSize(self) -> float: ...
    @HorizontalSize.setter
    def HorizontalSize(self, value: float) -> None: ...
    @property
    def LabelFont(self) -> int: ...
    @LabelFont.setter
    def LabelFont(self, value: int) -> None: ...
    @property
    def LabelHeight(self) -> float: ...
    @LabelHeight.setter
    def LabelHeight(self, value: float) -> None: ...
    @property
    def LeftMargin(self) -> float: ...
    @LeftMargin.setter
    def LeftMargin(self, value: float) -> None: ...
    @property
    def MarkingHeight(self) -> float: ...
    @MarkingHeight.setter
    def MarkingHeight(self, value: float) -> None: ...
    @property
    def Method(self) -> Diagramming.SheetBordersAndZonesBuilder.ZoneMethod: ...
    @Method.setter
    def Method(self, value: Diagramming.SheetBordersAndZonesBuilder.ZoneMethod) -> None: ...
    @property
    def Origin(self) -> Diagramming.SheetBordersAndZonesBuilder.ZoneOrigin: ...
    @Origin.setter
    def Origin(self, value: Diagramming.SheetBordersAndZonesBuilder.ZoneOrigin) -> None: ...
    @property
    def RightMargin(self) -> float: ...
    @RightMargin.setter
    def RightMargin(self, value: float) -> None: ...
    @property
    def SheetBorderSettings(self) -> Diagramming.SheetBorderSettingsBuilder: ...
    @SheetBorderSettings.setter
    def SheetBorderSettings(self, value: Diagramming.SheetBorderSettingsBuilder) -> None: ...
    @property
    def SheetMarginSettings(self) -> Diagramming.SheetMarginSettingsBuilder: ...
    @SheetMarginSettings.setter
    def SheetMarginSettings(self, value: Diagramming.SheetMarginSettingsBuilder) -> None: ...
    @property
    def SheetZoneSettings(self) -> Diagramming.SheetZoneSettingsBuilder: ...
    @SheetZoneSettings.setter
    def SheetZoneSettings(self, value: Diagramming.SheetZoneSettingsBuilder) -> None: ...
    @property
    def TopMargin(self) -> float: ...
    @TopMargin.setter
    def TopMargin(self, value: float) -> None: ...
    @property
    def TrimmingMarkLength(self) -> float: ...
    @TrimmingMarkLength.setter
    def TrimmingMarkLength(self, value: float) -> None: ...
    @property
    def TrimmingMarkThickness(self) -> float: ...
    @TrimmingMarkThickness.setter
    def TrimmingMarkThickness(self, value: float) -> None: ...
    @property
    def VerticalCenteringMark(self) -> Diagramming.SheetBordersAndZonesBuilder.VerticalCenteringMarkType: ...
    @VerticalCenteringMark.setter
    def VerticalCenteringMark(self, value: Diagramming.SheetBordersAndZonesBuilder.VerticalCenteringMarkType) -> None: ...
    @property
    def VerticalSize(self) -> float: ...
    @VerticalSize.setter
    def VerticalSize(self, value: float) -> None: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> None: ...


    class VerticalCenteringMarkType(enum.Enum):
        None_= 0
        BottomArrow= 1
        TopArrow= 2
        BottomandTopArrow= 3
        BottomandTopLine= 4
    

    class TrimmingMarkStyleType(enum.Enum):
        Triangle= 0
        Corner= 1
    

    class HorizontalCenteringMarkType(enum.Enum):
        None_= 0
        LeftArrow= 1
        RightArrow= 2
        LeftandRightArrow= 3
        LeftandRightLine= 4
    

    class ArrowStyleType(enum.Enum):
        Filled= 0
        Closed= 1
        ClosedSolid= 2
        Open= 3
    

    class ArrowDirectionType(enum.Enum):
        OutofSheet= 0
        IntoSheet= 1
    

class SheetBordersAndZones(NXObject):
    def __init__(self) -> None: ...


class Sheet(Diagramming.BaseObject):
    def __init__(self) -> None: ...
    def LogGroupToDelete(self, group: Diagramming.Group) -> None: ...


class ShapeCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.Shape]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateShapeBuilder(self, shape: Diagramming.Shape) -> Diagramming.ShapeBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.Shape: ...
    def Tag(self) -> Tag: ...



class ShapeBuilder(Diagramming.SheetElementBuilder):
    def __init__(self) -> None: ...


class Shape(Diagramming.ConnectableElement):
    def __init__(self) -> None: ...


class RenderingPropertiesBuilder(Diagramming.BaseSubObjectBuilder):
    def __init__(self) -> None: ...
    @property
    def FillColor(self) -> NXColor: ...
    @FillColor.setter
    def FillColor(self, value: NXColor) -> None: ...
    @property
    def FillOpacity(self) -> float: ...
    @FillOpacity.setter
    def FillOpacity(self, value: float) -> None: ...
    @property
    def LineFont(self) -> DisplayableObject.ObjectFont: ...
    @LineFont.setter
    def LineFont(self, value: DisplayableObject.ObjectFont) -> None: ...
    @property
    def LineWidth(self) -> DisplayableObject.ObjectWidth: ...
    @LineWidth.setter
    def LineWidth(self, value: DisplayableObject.ObjectWidth) -> None: ...
    @property
    def StrokeColor(self) -> NXColor: ...
    @StrokeColor.setter
    def StrokeColor(self, value: NXColor) -> None: ...
    @property
    def StrokeOpacity(self) -> float: ...
    @StrokeOpacity.setter
    def StrokeOpacity(self, value: float) -> None: ...


class ReferenceGeometryBuilder(Diagramming.AnnotationBuilder):
    def __init__(self) -> None: ...
    def GetColor(self) -> float: ...
    def SetColor(self, color: float) -> None: ...
    def RefreshFromView(self, refresh: bool) -> None: ...
    def GetExternalFileReferenceAdapter(self, referenceObjectId: int) -> ExternalFileReferenceAdapter: ...
    def SetExternalFileReferenceAdapter(self, referenceObjectId: int, adapter: ExternalFileReferenceAdapter) -> None: ...
    def GetExternalFileDefinitionKey(self, adapter: ExternalFileReferenceAdapter) -> str: ...
    def EstablishReference(self, referenceObjectId: int, referenceType: ExternalFileReferenceAdapter.Type, externalFileSpec: str) -> ExternalFileReferenceAdapter: ...
    @property
    def DisplayBorder(self) -> bool: ...
    @DisplayBorder.setter
    def DisplayBorder(self, value: bool) -> None: ...
    @property
    def Scale(self) -> float: ...
    @Scale.setter
    def Scale(self, value: float) -> None: ...
    @property
    def Transparency(self) -> int: ...
    @Transparency.setter
    def Transparency(self, value: int) -> None: ...
    @property
    def View(self) -> str: ...
    @View.setter
    def View(self, value: str) -> None: ...


class ReferenceGeometry(Diagramming.Annotation):
    def __init__(self) -> None: ...


class PortCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.Port]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreatePortBuilder(self, port: Diagramming.Port) -> Diagramming.PortBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.Port: ...
    def Tag(self) -> Tag: ...



class PortBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[Diagramming.PortBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: Diagramming.PortBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: Diagramming.PortBuilder) -> int: ...
    def FindItem(self, index: int) -> Diagramming.PortBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: Diagramming.PortBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: Diagramming.PortBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[Diagramming.PortBuilder]: ...
    def SetContents(self, objects: typing.List[Diagramming.PortBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: Diagramming.PortBuilder, object2: Diagramming.PortBuilder) -> None: ...
    def Insert(self, location: int, object: Diagramming.PortBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class PortBuilder(Diagramming.SheetElementBuilder):
    def __init__(self) -> None: ...
    def GetAllowedParentSides(self, isAllowedLeftSide: bool, isAllowedRightSide: bool, isAllowedUpSide: bool, isAllowedDownSide: bool) -> None: ...
    def CanAnotherConnectionBeAdded(self) -> bool: ...
    def IsNumberOfConnectionInfinite(self) -> bool: ...
    def GetOwningConnectableElement(self) -> Diagramming.ConnectableElement: ...
    def GetConnections(self) -> typing.List[Diagramming.Connection]: ...
    @property
    def Direction(self) -> Diagramming.Direction: ...
    @Direction.setter
    def Direction(self, value: Diagramming.Direction) -> None: ...
    @property
    def NumberAllowedConnections(self) -> int: ...
    @NumberAllowedConnections.setter
    def NumberAllowedConnections(self, value: int) -> None: ...
    @property
    def Pinned(self) -> bool: ...
    @Pinned.setter
    def Pinned(self, value: bool) -> None: ...
    @property
    def Proxy(self) -> Diagramming.Port: ...
    @Proxy.setter
    def Proxy(self, value: Diagramming.Port) -> None: ...


class Port(Diagramming.SheetElement):
    def __init__(self) -> None: ...
    @property
    def Label(self) -> Diagramming.Annotation: ...
    @Label.setter
    def Label(self, value: Diagramming.Annotation) -> None: ...


class PopulateTitleBlockBuilder(Builder):
    def __init__(self) -> None: ...
    def GetCellValueForLabel(self, label: str) -> str: ...
    def SetCellValueForLabel(self, label: str, value: str) -> None: ...
    def GetCell(self, table: Diagramming.Tables.Table, rowIndex: int, columnIndex: int) -> Diagramming.TitleBlockCellBuilder: ...


class NodeCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.Node]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateNodeBuilder(self, node: Diagramming.Node) -> Diagramming.NodeBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.Node: ...
    def Tag(self) -> Tag: ...



class NodeBuilder(Diagramming.ConnectableElementBuilder):
    def __init__(self) -> None: ...
    def AddGroupMember(self, member: Diagramming.SheetElement) -> None: ...
    def RemoveGroupMember(self, member: Diagramming.SheetElement) -> None: ...
    def RemoveAllGroupMembers(self) -> None: ...
    @property
    def Expanded(self) -> bool: ...
    @Expanded.setter
    def Expanded(self, value: bool) -> None: ...
    @property
    def Fullfillment(self) -> bool: ...
    @Fullfillment.setter
    def Fullfillment(self, value: bool) -> None: ...
    @property
    def GroupingAllowed(self) -> bool: ...
    @GroupingAllowed.setter
    def GroupingAllowed(self, value: bool) -> None: ...
    @property
    def OffsheetReference(self) -> Diagramming.Node: ...
    @OffsheetReference.setter
    def OffsheetReference(self, value: Diagramming.Node) -> None: ...


class Node(Diagramming.ConnectableElement):
    def __init__(self) -> None: ...
    def GetPorts(self, ports: typing.List[Diagramming.Port]) -> None: ...
    @property
    def Label(self) -> Diagramming.Annotation: ...
    @Label.setter
    def Label(self, value: Diagramming.Annotation) -> None: ...


class NamespaceDoc(System.Object):
    def __init__(self) -> None: ...


class Method(enum.Enum):
    None_= 0
    Standard= 1
    Custom= 2


class LocationBuilder(Diagramming.BaseSubObjectBuilder):
    def __init__(self) -> None: ...
    def SetValueX(self, inputPercent: float, inputValue: float) -> None: ...
    def SetValueY(self, inputPercent: float, inputValue: float) -> None: ...
    @property
    def EvaluatedValueX(self) -> float: ...
    @EvaluatedValueX.setter
    def EvaluatedValueX(self, value: float) -> None: ...
    @property
    def EvaluatedValueY(self) -> float: ...
    @EvaluatedValueY.setter
    def EvaluatedValueY(self, value: float) -> None: ...
    @property
    def InputPercentX(self) -> float: ...
    @InputPercentX.setter
    def InputPercentX(self, value: float) -> None: ...
    @property
    def InputPercentY(self) -> float: ...
    @InputPercentY.setter
    def InputPercentY(self, value: float) -> None: ...
    @property
    def InputValueX(self) -> float: ...
    @InputValueX.setter
    def InputValueX(self, value: float) -> None: ...
    @property
    def InputValueY(self) -> float: ...
    @InputValueY.setter
    def InputValueY(self, value: float) -> None: ...
    @property
    def Reference(self) -> Diagramming.SheetElement: ...
    @Reference.setter
    def Reference(self, value: Diagramming.SheetElement) -> None: ...
    @property
    def UpToDate(self) -> bool: ...
    @UpToDate.setter
    def UpToDate(self, value: bool) -> None: ...


class LeaderLineCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.LeaderLine]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateLeaderLineBuilder(self, leaderLine: Diagramming.LeaderLine) -> Diagramming.LeaderLineBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.LeaderLine: ...
    def Tag(self) -> Tag: ...



class LeaderLineBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[Diagramming.LeaderLineBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: Diagramming.LeaderLineBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: Diagramming.LeaderLineBuilder) -> int: ...
    def FindItem(self, index: int) -> Diagramming.LeaderLineBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: Diagramming.LeaderLineBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: Diagramming.LeaderLineBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[Diagramming.LeaderLineBuilder]: ...
    def SetContents(self, objects: typing.List[Diagramming.LeaderLineBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: Diagramming.LeaderLineBuilder, object2: Diagramming.LeaderLineBuilder) -> None: ...
    def Insert(self, location: int, object: Diagramming.LeaderLineBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class LeaderLineBuilder(Diagramming.SheetElementBuilder):
    def __init__(self) -> None: ...
    def GetBendPoints(self, points: typing.List[Point2d]) -> None: ...
    def SetBendPoints(self, points: typing.List[Point2d]) -> None: ...
    def SetTerminator(self, terminator: Diagramming.SheetElement, segmentId: int, percentX: float, inputX: float, percentY: float, inputY: float) -> None: ...
    def GetTerminator(self, terminator: Diagramming.SheetElement, segmentId: int, percentX: float, inputX: float, percentY: float, inputY: float) -> None: ...
    @property
    def ArrowType(self) -> Diagramming.DiagrammingArrowtype: ...
    @ArrowType.setter
    def ArrowType(self, value: Diagramming.DiagrammingArrowtype) -> None: ...
    @property
    def StubLength(self) -> float: ...
    @StubLength.setter
    def StubLength(self, value: float) -> None: ...
    @property
    def StubSides(self) -> Diagramming.DiagrammingStubsides: ...
    @StubSides.setter
    def StubSides(self, value: Diagramming.DiagrammingStubsides) -> None: ...
    @property
    def VerticalAlignment(self) -> Diagramming.LeaderLineBuilder.VerticalAlignmentOption: ...
    @VerticalAlignment.setter
    def VerticalAlignment(self, value: Diagramming.LeaderLineBuilder.VerticalAlignmentOption) -> None: ...


    class VerticalAlignmentOption(enum.Enum):
        Top= 0
        Middle= 1
        Bottom= 2
    

class LeaderLine(Diagramming.Connection):
    def __init__(self) -> None: ...


class HorizontalCenteringMarkType(enum.Enum):
    None_= 0
    LeftArrow= 1
    RightArrow= 2
    LeftandRightArrow= 3
    LeftandRightLine= 4


class GroupCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.Group]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateGroupBuilder(self, group: Diagramming.Group) -> Diagramming.GroupBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.Group: ...
    def Tag(self) -> Tag: ...



class GroupBuilder(Diagramming.SheetElementBuilder):
    def __init__(self) -> None: ...
    def GetMember(self, memberSid: str) -> Diagramming.SheetElement: ...
    def GetMembers(self) -> typing.List[Diagramming.SheetElement]: ...
    def AddMember(self, sheetElement: Diagramming.SheetElement) -> None: ...
    def RemoveMember(self, member: Diagramming.SheetElement) -> None: ...
    def RemoveAllMembers(self) -> None: ...


class Group(Diagramming.SheetElement):
    def __init__(self) -> None: ...


class FormattedStringBuilder(Diagramming.BaseSubObjectBuilder):
    def __init__(self) -> None: ...
    @typing.overload
    def SetFormatValue(self, objTags: typing.List[NXObject], attrTitles: str, format: str) -> None: ...
    @typing.overload
    def SetFormatValue(self, objTags: typing.List[NXObject], parentTags: typing.List[NXObject], attrTitles: str, format: str) -> None: ...
    def AppendFormat(self, objTags: typing.List[NXObject], attrTitles: str, appendFormat: str) -> None: ...
    def ClearFormat(self) -> None: ...
    def GetReferencedAttributes(self, objTags: typing.List[NXObject]) -> str: ...
    @property
    def Format(self) -> str: ...
    @Format.setter
    def Format(self, value: str) -> None: ...
    @property
    def String(self) -> str: ...
    @String.setter
    def String(self, value: str) -> None: ...


class FontEnum(enum.Enum):
    Blockfont= 0


class Direction(enum.Enum):
    In= 1
    Out= 2
    Both= 3


class DiagrammingStubsides(enum.Enum):
    Auto= 0
    Left= 1
    Right= 2


class DiagrammingSizingpolicy(enum.Enum):
    Length= 0
    Auto= 1
    Percent= 2
    Inherit= 4


class DiagrammingRepeatstartposition(enum.Enum):
    Center= 0
    Start= 1
    End= 2


class DiagrammingManager(Utilities.NXRemotableObject):
    def __init__(self, owner: Part) -> None: ...
    def CreateBulkEditBuilder(self) -> Diagramming.BulkEditBuilder: ...
    def CreateCannedAnnotationBuilder(self, annotation: Diagramming.Annotation) -> Diagramming.CannedAnnotationBuilder: ...
    def OpenSheet(self, sheet: Diagramming.Sheet) -> None: ...
    def CreateSheetSizeBuilder(self, sheet: Diagramming.Sheet) -> Diagramming.SheetSizeBuilder: ...
    def CreateSheetTemplateBuilder(self, sheet: Diagramming.Sheet) -> Diagramming.SheetTemplateBuilder: ...
    def Tag(self) -> Tag: ...

    @property
    def Nodes(self) -> Diagramming.NodeCollection: ...
    @Nodes.setter
    def Nodes(self, value: Diagramming.NodeCollection) -> None: ...
    @property
    def Sheets(self) -> Diagramming.SheetCollection: ...
    @Sheets.setter
    def Sheets(self, value: Diagramming.SheetCollection) -> None: ...
    @property
    def Connections(self) -> Diagramming.ConnectionCollection: ...
    @Connections.setter
    def Connections(self, value: Diagramming.ConnectionCollection) -> None: ...
    @property
    def Groups(self) -> Diagramming.GroupCollection: ...
    @Groups.setter
    def Groups(self, value: Diagramming.GroupCollection) -> None: ...
    @property
    def Shapes(self) -> Diagramming.ShapeCollection: ...
    @Shapes.setter
    def Shapes(self, value: Diagramming.ShapeCollection) -> None: ...
    @property
    def Ports(self) -> Diagramming.PortCollection: ...
    @Ports.setter
    def Ports(self, value: Diagramming.PortCollection) -> None: ...
    @property
    def Annotations(self) -> Diagramming.AnnotationCollection: ...
    @Annotations.setter
    def Annotations(self, value: Diagramming.AnnotationCollection) -> None: ...
    @property
    def LeaderLines(self) -> Diagramming.LeaderLineCollection: ...
    @LeaderLines.setter
    def LeaderLines(self, value: Diagramming.LeaderLineCollection) -> None: ...
    @property
    def SheetBordersAndZones(self) -> Diagramming.SheetBordersAndZonesCollection: ...
    @SheetBordersAndZones.setter
    def SheetBordersAndZones(self, value: Diagramming.SheetBordersAndZonesCollection) -> None: ...
    @property
    def Tables(self) -> Diagramming.Tables.TableCollection: ...
    @Tables.setter
    def Tables(self, value: Diagramming.Tables.TableCollection) -> None: ...
    @property
    def TitleBlocks(self) -> Diagramming.TitleBlockCollection: ...
    @TitleBlocks.setter
    def TitleBlocks(self, value: Diagramming.TitleBlockCollection) -> None: ...
    @property
    def Lines(self) -> Diagramming.Geometry.LineCollection: ...
    @Lines.setter
    def Lines(self, value: Diagramming.Geometry.LineCollection) -> None: ...
    @property
    def Points(self) -> Diagramming.Geometry.PointCollection: ...
    @Points.setter
    def Points(self, value: Diagramming.Geometry.PointCollection) -> None: ...
    @property
    def Rectangles(self) -> Diagramming.Geometry.RectangleCollection: ...
    @Rectangles.setter
    def Rectangles(self, value: Diagramming.Geometry.RectangleCollection) -> None: ...
    @property
    def Arcs(self) -> Diagramming.Geometry.ArcCollection: ...
    @Arcs.setter
    def Arcs(self, value: Diagramming.Geometry.ArcCollection) -> None: ...
    @property
    def ActiveSheet(self) -> Diagramming.Sheet: ...
    @ActiveSheet.setter
    def ActiveSheet(self, value: Diagramming.Sheet) -> None: ...


class DiagrammingLocationstyle(enum.Enum):
    Absolute= 0
    Relative= 1


class DiagrammingJumpertype(enum.Enum):
    U= 1
    Break= 2


class DiagrammingJumperprioritytype(enum.Enum):
    Horizontal= 0
    Vertical= 1


class DiagrammingGeometrypointmarker(enum.Enum):
    Cross= 0
    Circle= 1


class DiagrammingFlowdirectionarrowstyle(enum.Enum):
    BottomFilledArrow= 0
    BottomOpenArrow= 1
    ClosedArrow= 2
    ClosedDoubleArrow= 3
    ClosedDoubleSolidArrow= 4
    ClosedSolidArrow= 5
    FilledArrow= 6
    FilledDoubleArrow= 7
    OpenArrow= 8
    OpenDoubleArrow= 9
    TopFilledArrow= 10
    TopOpenArrow= 11


class DiagrammingConnectionlabelverticaloffsetposition(enum.Enum):
    Left= 0
    Right= 1


class DiagrammingConnectionlabelposition(enum.Enum):
    Start= 1
    End= 2
    Center= 4
    Spaced= 8


class DiagrammingConnectionlabelhorizontaloffsetposition(enum.Enum):
    Above= 0
    Below= 1


class DiagrammingArrowtype(enum.Enum):
    None_= 0
    Open= 1
    Filled= 2
    ClosedSolid= 3


class DiagrammingAnnotationboundarytype(enum.Enum):
    None_= 0
    Circle= 1
    Ellipse= 2
    Rectangle= 3
    RoundedRectangle= 4


class DiagrammingAlignment(enum.Enum):
    Left= 0
    Center= 1
    Right= 2
    Justify= 3


class DefineTitleBlockBuilder(Builder):
    def __init__(self) -> None: ...
    def GetTables(self, tables: typing.List[Diagramming.Tables.Table]) -> None: ...
    def SetTables(self, tables: typing.List[Diagramming.Tables.Table]) -> None: ...
    def GetCell(self, table: Diagramming.Tables.Table, rowIndex: int, columnIndex: int) -> Diagramming.TitleBlockCellBuilder: ...
    @property
    def Cells(self) -> Diagramming.TitleBlockCellBuilderList: ...
    @Cells.setter
    def Cells(self, value: Diagramming.TitleBlockCellBuilderList) -> None: ...


class ConnectionLocationBuilderList(TaggedObject):
    def __init__(self) -> None: ...
    @typing.overload
    def Append(self, objects: typing.List[Diagramming.ConnectionLocationBuilder]) -> None: ...
    @typing.overload
    def Append(self, object: Diagramming.ConnectionLocationBuilder) -> None: ...
    def ClearIndex(self, deleteIdx: int) -> None: ...
    def FindIndex(self, obj: Diagramming.ConnectionLocationBuilder) -> int: ...
    def FindItem(self, index: int) -> Diagramming.ConnectionLocationBuilder: ...
    @typing.overload
    def Erase(self, index: int) -> None: ...
    @typing.overload
    def Erase(self, index: int, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Erase(self, obj: Diagramming.ConnectionLocationBuilder) -> None: ...
    @typing.overload
    def Erase(self, obj: Diagramming.ConnectionLocationBuilder, deleteOption: ObjectList.DeleteOption) -> None: ...
    @typing.overload
    def Clear(self) -> None: ...
    @typing.overload
    def Clear(self, deleteOption: ObjectList.DeleteOption) -> None: ...
    def GetContents(self) -> typing.List[Diagramming.ConnectionLocationBuilder]: ...
    def SetContents(self, objects: typing.List[Diagramming.ConnectionLocationBuilder]) -> None: ...
    @typing.overload
    def Swap(self, index1: int, index2: int) -> None: ...
    @typing.overload
    def Swap(self, object1: Diagramming.ConnectionLocationBuilder, object2: Diagramming.ConnectionLocationBuilder) -> None: ...
    def Insert(self, location: int, object: Diagramming.ConnectionLocationBuilder) -> None: ...
    def MoveToTop(self, index: int) -> None: ...
    def MoveToBottom(self, index: int) -> None: ...
    @property
    def Length(self) -> int: ...
    @Length.setter
    def Length(self, value: int) -> None: ...


class ConnectionLocationBuilder(Diagramming.LocationBuilder):
    def __init__(self) -> None: ...
    @property
    def SegmentIdentifier(self) -> int: ...
    @SegmentIdentifier.setter
    def SegmentIdentifier(self, value: int) -> None: ...


class ConnectionCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.Connection]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateConnectionBuilder(self, connection: Diagramming.Connection) -> Diagramming.ConnectionBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.Connection: ...
    def Tag(self) -> Tag: ...



class ConnectionBuilder(Diagramming.SheetElementBuilder):
    def __init__(self) -> None: ...
    def GetBendPoints(self, points: typing.List[Point2d]) -> None: ...
    def SetBendPoints(self, points: typing.List[Point2d]) -> None: ...
    @property
    def Discipline(self) -> str: ...
    @Discipline.setter
    def Discipline(self, value: str) -> None: ...
    @property
    def End(self) -> Diagramming.Port: ...
    @End.setter
    def End(self, value: Diagramming.Port) -> None: ...
    @property
    def EndLocation(self) -> Diagramming.LocationBuilder: ...
    @EndLocation.setter
    def EndLocation(self, value: Diagramming.LocationBuilder) -> None: ...
    @property
    def ReverseEnd(self) -> bool: ...
    @ReverseEnd.setter
    def ReverseEnd(self, value: bool) -> None: ...
    @property
    def Start(self) -> Diagramming.Port: ...
    @Start.setter
    def Start(self, value: Diagramming.Port) -> None: ...
    @property
    def StartLocation(self) -> Diagramming.LocationBuilder: ...
    @StartLocation.setter
    def StartLocation(self, value: Diagramming.LocationBuilder) -> None: ...


class Connection(Diagramming.SheetElement):
    def __init__(self) -> None: ...
    @property
    def Label(self) -> Diagramming.Annotation: ...
    @Label.setter
    def Label(self, value: Diagramming.Annotation) -> None: ...


class ConnectableElementBuilder(Diagramming.SheetElementBuilder):
    def __init__(self) -> None: ...
    def GetAllPorts(self) -> typing.List[Diagramming.Port]: ...
    def GetPorts(self, direction: Diagramming.Direction) -> typing.List[Diagramming.Port]: ...


class ConnectableElement(Diagramming.SheetElement):
    def __init__(self) -> None: ...


class CannedAnnotationBuilder(Builder):
    def __init__(self) -> None: ...
    def CreateLeaderLine(self) -> Diagramming.LeaderLineBuilder: ...
    def Inherit(self, inheritOption: Diagramming.CannedAnnotationBuilder.InheritOption, annotation: Diagramming.Annotation) -> None: ...
    @property
    def AnnotationBuilder(self) -> Diagramming.AnnotationBuilder: ...
    @AnnotationBuilder.setter
    def AnnotationBuilder(self, value: Diagramming.AnnotationBuilder) -> None: ...
    @property
    def LeaderLines(self) -> Diagramming.LeaderLineBuilderList: ...
    @LeaderLines.setter
    def LeaderLines(self, value: Diagramming.LeaderLineBuilderList) -> None: ...
    @property
    def TextBoxIndent(self) -> int: ...
    @TextBoxIndent.setter
    def TextBoxIndent(self, value: int) -> None: ...
    @property
    def TextBoxModifiable(self) -> bool: ...
    @TextBoxModifiable.setter
    def TextBoxModifiable(self, value: bool) -> None: ...
    @property
    def TextBoxShadowBox(self) -> bool: ...
    @TextBoxShadowBox.setter
    def TextBoxShadowBox(self, value: bool) -> None: ...


    class InheritOption(enum.Enum):
        Preferences= 0
        CustomerDefaults= 1
        Selection= 2
    

class BulkEditBuilder(Builder):
    def __init__(self) -> None: ...
    def SetSheetElements(self, sheetElements: typing.List[Diagramming.SheetElement]) -> None: ...
    def SetDeltaXCoordinate(self, deltaXCoordinate: float) -> None: ...
    def SetDeltaYCoordinate(self, deltaYCoordinate: float) -> None: ...
    def SetHide(self, hide: bool) -> None: ...
    def SetHideLabel(self, hideLabel: bool) -> None: ...
    @property
    def RenderingProperties(self) -> Diagramming.RenderingPropertiesBuilder: ...
    @RenderingProperties.setter
    def RenderingProperties(self, value: Diagramming.RenderingPropertiesBuilder) -> None: ...


class BaseTaggedObjectBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...


class BaseSubObjectBuilder(TaggedObject):
    def __init__(self) -> None: ...
    def Validate(self) -> bool: ...


class BaseObjectBuilder(Builder):
    def __init__(self) -> None: ...


class BaseObject(DisplayableObject):
    def __init__(self) -> None: ...


class Axis(enum.Enum):
    X= 1
    Y= 2


class ArrowStyleType(enum.Enum):
    Filled= 0
    Closed= 1
    ClosedSolid= 2
    Open= 3


class ArrowDirectionType(enum.Enum):
    OutofSheet= 0
    IntoSheet= 1


class AnnotationCollection(TaggedObjectCollection):
    def EnumerateMoveNext(self, currentTag: Tag, state: bytes) -> int: ...
    def ToArray(self) -> typing.List[Diagramming.Annotation]: ...
    @typing.overload
    def __init__(self, owner: Diagramming.DiagrammingManager) -> None: ...
    @typing.overload
    def __init__(self) -> None: ...
    def CreateAnnotationBuilder(self, annotation: Diagramming.Annotation) -> Diagramming.AnnotationBuilder: ...
    def FindObject(self, journalIdentifier: str) -> Diagramming.Annotation: ...
    def Tag(self) -> Tag: ...



class AnnotationBuilder(Diagramming.ConnectableElementBuilder):
    def __init__(self) -> None: ...
    @property
    def BoundaryDisplay(self) -> bool: ...
    @BoundaryDisplay.setter
    def BoundaryDisplay(self, value: bool) -> None: ...
    @property
    def BoundaryType(self) -> Diagramming.DiagrammingAnnotationboundarytype: ...
    @BoundaryType.setter
    def BoundaryType(self, value: Diagramming.DiagrammingAnnotationboundarytype) -> None: ...
    @property
    def FormattedStringBuilder(self) -> Diagramming.FormattedStringBuilder: ...
    @FormattedStringBuilder.setter
    def FormattedStringBuilder(self, value: Diagramming.FormattedStringBuilder) -> None: ...
    @property
    def Text(self) -> str: ...
    @Text.setter
    def Text(self, value: str) -> None: ...
    @property
    def TextStyleBuilder(self) -> Diagramming.TextStyleBuilder: ...
    @TextStyleBuilder.setter
    def TextStyleBuilder(self, value: Diagramming.TextStyleBuilder) -> None: ...
    @property
    def TextType(self) -> Diagramming.AnnotationBuilder.TextTypeOption: ...
    @TextType.setter
    def TextType(self, value: Diagramming.AnnotationBuilder.TextTypeOption) -> None: ...


    class TextTypeOption(enum.Enum):
        Fixed= 0
        Parametric= 1
    

class Annotation(Diagramming.ConnectableElement):
    def __init__(self) -> None: ...


